### ISSUE TITLE
Get real IP in access log when using CloudFlare or other load-balancers

### ISSUE THREAD

**Issue by artur-borys** [traefik/traefik#10002]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,
First of all - I really appreciate the work you've all done on Traefik - I think it's a great project. I've started using it not a long time ago and I love it.

I have a problem with access log - I cannot find any solution, to log real IP when the requests are proxied through CloudFlare. In access logs I can only see the CloudFlare loadbalancers IPs.

I know there are middlewares which rewrite CloudFlare headers for services, but I couldn't find a plugin which would put the real IP in access log.

I know that I can also use JSON format for access log and include headers, like ``X-Forwarded-For``, but I really want to stick with the ``common`` format and see the real IPs there.

I've tried configuring ProxyProtocol, but it doesn't seem to help.

I don't have much experience with Go, and Traefik is a pretty big project, but from what I can tell, in ``pkg/middlewares/accesslog/logger.go`` on line 227, ``req.RemoteAddr`` is used:

``` go
...
core[ClientAddr] = req.RemoteAddr
...
```

I imagine that this is the part, where the source IP for a request is determined for access log.

Can you point me to a valid solution or determine whether that's a feature that could be implemented directly in Traefik?

**Comment by bluepuma77** [comment]
Traefik supports [ProxyProtocol](https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol).

**Comment by artur-borys** [comment]
It seems like combination of ``proxyProtocol`` and ``forwardedHeaders`` seemed to solve the issue (possibly only the second one in case of HTTP(S) traffic). 

Thanks
