### ISSUE TITLE
How to use IP without a domain name office

### ISSUE THREAD

**Issue by strongyc** [traefik/traefik#10017]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

How to use IP without a domain name office

**Comment by kevinpollet** [comment]
Thanks for reaching out! To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
