### ISSUE TITLE
Deprecating Headers matcher before removal on Traefik v3

### ISSUE THREAD

**Issue by rsaldano** [traefik/traefik#10021]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### Current behavior

**Headers** matcher only works on Traefik v2 but is abruptly removed on Traefik v3 without deprecating it first. (https://doc.traefik.io/traefik/master/migration/v2-to-v3/#matchers)

Just like Traefik v2.10 supports both old and new API Versions (treafik.containo.us and traefik.io) the same logic should apply for this matcher rule to allow a smooth transition.

### Proposed behavior

Some people may be using the **Headers** matcher on Traefik v2, but we need some transition versions that support both **Headers** and **Header** to migrate them without disrupting any services.

```yaml
spec:
  routes:
    - kind: Rule
      match: >-
        Headers(`content-type`,`application/grpc`) 
        .
        .
        .
    - kind: Rule
      match: >-
        Header(`content-type`,`application/grpc`) 
        .
        .
        .
```

**Comment by farmerluo** [comment]
+1

**Comment by rtribotte** [comment]
Hello @rsaldano,

This issue looks to have been more or less fixed by https://github.com/traefik/traefik/pull/10339.
I'm closing it accordingly, but feel free to ask to reopen it.
