### ISSUE TITLE
Feature request: "last accessed" column for routers in Traefik dashboard

### ISSUE THREAD

**Issue by Subbeh** [traefik/traefik#10048]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

A nice-to-have would be for Traefik Dashboard to show a column in the Routers overview of when the associated rule was last hit.

This would be especially useful when using a large number of services defined in dynamic configuration files. Having this information makes it easy to spot services that are no longer used.

**Comment by rtribotte** [comment]
Hello @Subbeh,

Thanks for this contribution and your interest in Traefik!

Unfortunately, we think that this feature satisfies a very niche need, and moreover, this could already be deduced from AccessLogs or Metrics, so we are declining this proposal.
Indeed, we try to keep focus and address the most common use cases.
