### ISSUE TITLE
Client Cert Auth PassThrough issue - TLS Re-Negotiation not working

### ISSUE THREAD

**Issue by Vonor** [traefik/traefik#10054]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to set up Client Cert Auth Pass Through to an apache httpd instance behind traefik.

I looked at the docs for [passtlsclientcert](https://doc.traefik.io/traefik/middlewares/http/passtlsclientcert/) and [mTLS](https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls) and got Traefik to ask for a (the correct) client cert.

I was expecting the Client Certificate to be handed over to Apache for further processing.

I might have missed some configuration on either end (traefik or apache) but after reading up and down on search results and trying out different things almost the whole day I give up on trying and rather report here. Any help is appreciated.

If it helps, this is currently in a test environemnt on my local computer running Docker Desktop on Windows + Portainer Extension for Docker Desktop + Traefik inside Portainer

If I run the Apache container standalone with exposed SSL Port the client authentication works.

### What did you see instead?

502 - Bad Gateway

### What version of Traefik are you using?

Version:      2.10.4
Codename:     saintmarcelin
Go version:   go1.20.6
Built:        2023-07-24T16:29:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Compose File snippet
```yaml
    command:    
      # Docker configuration
      - "--providers.docker=true"
      - "--providers.docker.network=traefik-swarm"
      - "--providers.docker.exposedbydefault=false"
      # File configuration
      - "--providers.file.directory=/providers"
      - "--providers.file.watch=true"
```

`/providers/client.toml`
```toml
[tls.options]
  [tls.options.client]
    [tls.options.client.clientAuth]
      caFiles = ["/providers/rootca.cert"]
      clientAuthType = "RequireAndVerifyClientCert"
```

Labels for Apache Container

```yml
      - "traefik.http.routers.apache.tls.options=client@file"
      - "traefik.http.middlewares.apache.passtlsclientcert.pem=true"
```

apache config
```
SSLVerifyClient      optional
SSLVerifyDepth       3
SSLOptions           +StdEnvVars +ExportCertData +StrictRequire

<RequireAll>
    SSLRequire %{SSL_CLIENT_S_DN_Email} = "my@mail" \
        or %{SSL_CLIENT_S_DN_Email} = "someone@mail" \
        or %{SSL_CLIENT_S_DN_Email} = "someoneelse@mail" \
        and %{SSL_CLIENT_I_DN_CN} = "MySub CA"

    SSLUserName SSL_CLIENT_S_DN_Email
    Require ssl-verify-client
</RequireAll>
```

### If applicable, please paste the log output in DEBUG level

Traefik logs with Debug
```
time="2023-07-27T16:38:09Z" level=debug msg="'502 Bad Gateway' caused by: local error: tls: no renegotiation"
time="2023-07-27T16:38:01Z" level=debug msg="Serving default certificate for request: \"traefik.local.net\""
time="2023-07-27T16:38:01Z" level=debug msg="http: TLS handshake error from 10.0.0.2:52216: remote error: tls: unknown certificate"
time="2023-07-27T16:38:04Z" level=debug msg="Serving default certificate for request: \"myapache.local.net\""
time="2023-07-27T16:38:04Z" level=debug msg="http: TLS handshake error from 10.0.0.2:52218: remote error: tls: unknown certificate"
time="2023-07-27T16:38:07Z" level=debug msg="Serving default certificate for request: \"myapache.local.net\""
time="2023-07-27T16:38:07Z" level=debug msg="http: TLS handshake error from 10.0.0.2:52220: remote error: tls: unknown certificate"
time="2023-07-27T16:38:07Z" level=debug msg="http: TLS handshake error from 10.0.0.2:52222: remote error: tls: unknown certificate"
time="2023-07-27T16:38:07Z" level=debug msg="http: TLS handshake error from 10.0.0.2:52224: EOF"
time="2023-07-27T16:38:09Z" level=debug msg="Serving default certificate for request: \"myapache.local.net\""
```

Apache Logs
```
==> /var/log/apache2/ssl_access.log <==
- - - [27/Jul/2023:18:41:35 +0200] "GET / HTTP/1.1" 403 305 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183"

==> /var/log/apache2/ssl_error.log <==
[Thu Jul 27 18:41:35.440515 2023] [ssl:error] [pid 51] [client 10.0.1.5:45472] AH02261: Re-negotiation handshake failed
[Thu Jul 27 18:41:35.440604 2023] [ssl:error] [pid 51] SSL Library Error: error:0A000153:SSL routines::no renegotiation
```

**Comment by rtribotte** [comment]
Hello @Vonor,

Thanks for your interest in Traefik,

This seems to be a question about the configuration of Traefik and Apache, but the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
