### ISSUE TITLE
Allow POST body in the healthcheck service probe

### ISSUE THREAD

**Issue by mike-code** [traefik/traefik#10055]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Right now healthcheck allows you to select http method and headers, but it won't allow you to specify the body of a request. Please add this feature to traefik.

**Comment by ldez** [comment]
Hello,

can you explain what is your use-case?

**Comment by mike-code** [comment]
> can you explain what is your use-case?

sure. We'd like to use traefik failover functionality and to use it, we need to configure the healthcheck part.

We're using a 3rd party app that exposes a json rpc endpoint. This app doesn't expose a healthcheck endpoint per-se and returns `405` on `GET` and `400` on `POST` w/o proper body. We need to provide a valid body to get `200` **but** even a valid body(sic!) may return `429` if we hit rate limits. Those rate limits are when we want to fall back to our "fallback" server.

**Comment by mike-code** [comment]
Unfortunately that won't be enough for my use-case (see my reply above). Getting *any* response (2xx/4xx) does not mean, in my case, that the service is "healthy" (ie. just because it responds to a http request, it means that it's "alive" but not necessarily "healthy").

If I don't get `200` after a valid POST request w/ body, then it must be considered unhealthy (eg. broken state, out of sync, invalid credentials, whatever) and in such case, the fallback/failover logic should switch to another service.

For now as a workaround I've setup haproxy pod with appropriate logic and skipped using traefik's failover functionality altogether. I understand it's not trivial feature to implement so I assume this might go on "nice-to-have" backlog list 😃

**Comment by nmengin** [comment]
Hello @mike-code,

This proposal was opened more than 6 months ago with no traction.
We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.
