### ISSUE TITLE
Add support for redirecting based on probe/HEAD result

### ISSUE THREAD

**Issue by attie-argentum** [traefik/traefik#10081]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What would you like to see?

I'd like to propose a feature that would allow redirect rules to only engage if a probe / `HEAD` succeeds (i.e: `2xx`), otherwise the rule behaves as if it wasn't there.

To provide an example:

I'm supporting someone with a service that has a large number of sizable files. The storage of these files has been pushed out to S3 to relieve resources on the server - a redirect is put in place on Traefik so that all of these requests are "invisible" from the application's point of view, and clients go directly to S3 instead.

Unfortunately, some of these files do not yet exist, and are generated by the application the first time they're requested. It's not trivial for this service to be reworked to respond with the redirect itself, though I will be investigating this further.

The expected flow would be something like this:

1. Client a requests resource from Traefik
2. Traefik sees a matching rule, and makes a HEAD request to the indicated destination
3. _either:_ The HEAD request returns 2xx, so Traefik issues the redirect
4. _or:_ The HEAD request returns non-2xx (e.g: 404), so Traefik ignores the redirect, and the request hits the original service

**Comment by ldez** [comment]
Hello,

the route used by the redirection is built during the read of configuration, not during the request time, and the routes are unique.
So the redirection will be able to call the same route without the redirection.

You are trying to build a cache system, this is either something that your application should able to manage or something related to a cache system. Using redirection is not the right solution.
