### ISSUE TITLE
Create routers and services from api

### ISSUE THREAD

**Issue by LucnElmr** [traefik/traefik#10093]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

it would be really useful if the api was not only read-only and could create routers and services dynamically from an http endpoint.
Thanks a lot
Lucien Elmer

**Comment by LucnElmr** [comment]
No, I'm talking about creating endpoints on the existing api that allow you to create either a service or a router etc.. Because right now, you have to have another web server with a dynamic configuration, which isn't very practical.

**Comment by ldez** [comment]
Ok, so you can use the undocumented REST provider.

**Comment by LucnElmr** [comment]
Okay, but how do I know how it works?

**Comment by ldez** [comment]
- endpoint: `/api/providers/rest`
- HTTP method: `PUT`
- data: same as the file provider

**Comment by LucnElmr** [comment]
Thanks you very much
