### ISSUE TITLE
https://plugins.traefik.io rewrites GitHub badges markdown to invalid URL

### ISSUE THREAD

**Issue by agilezebra** [traefik/traefik#10091]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I put a GitHub badge in my README.md in my plugin repo:
```
[![Go](https://github.com/Brainnwave/jwt-middleware/actions/workflows/go.yml/badge.svg)](https://github.com/Brainnwave/jwt-middleware/actions/workflows/go.yml)
```

### What did you see instead?

https://plugins.traefik.io is serving it with the URL rewritten to use the raw.githubusercontent.com domain, which results in a 404 for the image and a broken link on the page:
```
 <a href="https://github.com/Brainnwave/jwt-middleware/actions/workflows/go.yml" target="_blank" class="sc-e98db946-0 leBLAY">
   <img alt="Go" src="https://raw.githubusercontent.com/Brainnwave/jwt-middleware/actions/workflows/go.yml/badge.svg" class="sc-97908e85-0 ftmaAO"/>
</a>
```

### What version of Traefik are you using?

n/a

### What is your environment & configuration?

n/a

**Comment by ldez** [comment]
hello,

we were forced to do that to display images from the repository itself (ex: from the doc folder).
