### ISSUE TITLE
Question: about container_name

### ISSUE THREAD

**Issue by vanodevium** [traefik/traefik#10102]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

> I am very sorry, but I could not find the answer to the question anywhere.
Please explain.

What is the main reason that **traefik** communicates with other containers by IP and not by aliases such as the name of the container (**container_name** from docker-compose.yml)?
Is there a technical problem with this? Or it is just faster? 

I will be grateful for any answer!
Thanks!

### What did you see instead?

I see very useful tool ever!

### What version of Traefik are you using?

Version: 2.10.4
Codename: saintmarcelin
Go version: go1.20.6
Built: 2023-07-24T16:29:02Z
OS/Arch: linux/amd64

### What is your environment & configuration?

There is no config.

**Comment by ldez** [comment]
Hello,

The GitHub issue tracker is dedicated to bug and feature requests.

For questions please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

The answer to this question requires to have more information about why you are asking it, so the better place to talk about that is the forum.

We will close this issue accordingly.
