### ISSUE TITLE
Include traefik version in Windows executable

### ISSUE THREAD

**Issue by stavikpetr** [traefik/traefik#10108]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello. It would be very helpful if you could include the traefik version in the Properties > Details dialog of traefik windows executable. We are currently generating SBOM for our product and without this, we need to update the SBOM manually with each update of traefik.

**Comment by ldez** [comment]
Hello,

Traefik is made for cloud environments: containers and Linux.

This request is a niche, the ratio between the value of this and the effort to produce an maintain a binary with properties is not good.
