### ISSUE TITLE
Error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]

### ISSUE THREAD

**Issue by ToshY** [traefik/traefik#10116]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Migrating docker image from `v2.10` to `v3.0` I've encountered the following error message in the logging when recreating my Traefik service:

```console
traefik-traefik-1  | 2023-09-10T13:53:00.528139005Z 2023-09-10T13:53:00Z ERR error="error while adding rule Host(`example.com`, `www.example.com`): error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]" entryPointName=websecure routerName=app-apache@docker
traefik-traefik-1  | 2023-09-10T13:53:23.047640325Z 2023-09-10T13:53:23Z ERR error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
traefik-traefik-1  | 2023-09-10T13:53:23.047658159Z 2023-09-10T13:53:23Z ERR error="close tcp [::]:443: use of closed network connection" entryPointName=websecure
traefik-traefik-1  | 2023-09-10T13:53:23.047662477Z 2023-09-10T13:53:23Z ERR error="accept tcp [::]:80: use of closed network connection" entryPointName=web
traefik-traefik-1  | 2023-09-10T13:53:23.047665623Z 2023-09-10T13:53:23Z ERR error="close tcp [::]:80: use of closed network connection" entryPointName=we
```

The Traefik router label for `app-apache` is as follows:

```yaml
      traefik.http.routers.app-apache.rule: Host(`${APP_DOMAIN}`, `www.${APP_DOMAIN}`)
```

> **Note**
> `${APP_DOMAIN`} is `example.com` from the logging above.

---

* I've read the [migration guide](https://doc.traefik.io/traefik/master/migration/v2-to-v3/) before upgrading to `v3.0`, which does _not_ denote anything related to changes with the `Host` rule.
* I've read the [latest documentation regarding rules](https://doc.traefik.io/traefik/routing/routers/#rule), and the examples show that having multiple hosts, <code>Host(`example.com`, ...)</code>, is still a valid rule.

### What did you see instead?

-

### What version of Traefik are you using?

`v3.0`

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

-

**Comment by ldez** [comment]
Hello,

It's in the documentation:

> All matchers now take a single value

https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/#matchers

**Comment by ToshY** [comment]
hey @ldez 👋 

Thanks, I thought v3 was no longer experimental (as the image on dockerhub was tagged `v3.0`). Sorry for that.

Is the equivalent of <code>Host(\`example.com\`, \`www.example.com\`)</code> in v3 then <code>Host(\`example.com\`) || Host(\`www.example.com\`)</code> ?

**Comment by ldez** [comment]
> Is the equivalent of Host(`example.com`, `www.example.com`) in v3 then Host(`example.com`) || Host(`www.example.com`) ?

yes

https://doc.traefik.io/traefik/v3.0/routing/routers/#rule
