### ISSUE TITLE
OpenTelemetry documentation page is missing

### ISSUE THREAD

**Issue by julianocosta89** [traefik/traefik#10113]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I wanted to use Traefik with OpenTelemetry and couldn't find the documentation on the official Traefik docs: https://doc.traefik.io/traefik/observability/tracing/overview/

### What did you see instead?

I've navigated to the GitHub repo and found the documentation: https://github.com/traefik/traefik/blob/4f6c15cc14cdedc34484c697994134959fdff493/docs/content/observability/tracing/opentelemetry.md

### What version of Traefik are you using?

none

### What is your environment & configuration?

no config.

### If applicable, please paste the log output in DEBUG level

I'm just reporting that the documentation page is not updated.
The OpenTelemetry docs were merged 10 months ago and still didn't make into the live page.

**Comment by ldez** [comment]
Hello,

OpenTelemetry is in the v3 (beta) so the page is not in the documentation of v2 (stable).

https://doc.traefik.io/traefik/v3.0/observability/metrics/opentelemetry/
