### ISSUE TITLE
Too aggressive plan for removal of traefik.io/v1alpha1

### ISSUE THREAD

**Issue by bjornharrtell** [traefik/traefik#10124]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Docs say "The newly introduced Kubernetes CRD API Version traefik.io/v1alpha1 will subsequently be removed in Traefik v3. The following version will be traefik.io/v1."

IMHO it's too aggressive to deprecate traefik.io/v1alpha1 at this time because unless I'm wrong the replacement is not available in the latest release of v2. I suggest to either postpone deprecation until traefik.io/v1 is available in v2, or postpone deprecation to v3.

**Comment by ldez** [comment]
`traefik.io/v1alpha1` has been introduced to ease the migration https://github.com/traefik/traefik/pull/9765.

More information here: https://github.com/traefik/traefik/pull/9600#issuecomment-1462254130
