### ISSUE TITLE
Unable to generate wildcard certificate properly for multiple domains

### ISSUE THREAD

**Issue by xd003** [traefik/traefik#10129]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am intending to generate multiple wildcard certificates using cloudflare dnschallenge for multiple domains. For instance -
1) Cert1 -  ```example.com``` & ```*.example..com```
2) Cert2 - ```adguard.example.com``` & ```*.adguard.example.com```

Here is my full docker-compose for traefik, i don't use anything else to configure traefik - https://pastebin.com/raw/GGAAwXBj
Pointing out the most relevant section from the compose
```
 - "--entrypoints.websecure.http.tls.domains[0].main=example.com"
 - "--entrypoints.websecure.http.tls.domains[0].sans=*.example.com"
 - "--entrypoints.websecure.http.tls.domains[1].main=adguard.example.com"
 - "--entrypoints.websecure.http.tls.domains[1].sans=*.adguard.example.com"
```

### What did you see instead?

Here is a link to my redacted acme.json file - https://pastebin.com/raw/fbrtuKb4.
As evident from above json file, the first certificate is generated fine namely ```example.com``` & ```*.example.com``` are correctly present inside ```main``` and ```sans``` block but for the second certificate, ```*.adguard.example.com``` is directly present in the ```main``` block while ```sans``` block is missing altogether.

### What version of Traefik are you using?

Traefik version 3.0.0-beta3

### What is your environment & configuration?

Ubuntu 22.04 & Docker

**Comment by ldez** [comment]
Hello,

The GitHub issue tracker is dedicated to bug and feature requests.

For questions please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly.
