### ISSUE TITLE
The `ServiceName` for kubernetes provider use `-` as separator may cause conflicts

### ISSUE THREAD

**Issue by icefed** [traefik/traefik#10139]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Create a Service `foo-bar` with port `web` in namespace `test`, and create a Service `bar` with port `web` in namespace `test-foo`, they have the same `ServiceName`: `test-foo-bar-web@kubernetes` when traefik processing. 

It could be used elsewhere-it could be problematic. 

Also, there is no way to reverse deduce the original field from the-linked string. 

### What did you see instead?

...

### What version of Traefik are you using?

v2.5.7

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by nmengin** [comment]
Close in favor of https://github.com/traefik/traefik/issues/10105
