### ISSUE TITLE
plugins.traefik.io is currently down

### ISSUE THREAD

**Issue by jdel** [traefik/traefik#10146]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I restarted traefik and it failed when downloading plugins.

https://plugins.traefik.io/plugins is currently down (message from cloudflare, invalid cert)

The problem is most likely impacting anyone who uses plugins.

If you are using plugins, do not restart traefik now

### What did you see instead?

Error 526 invalid cert

### What version of Traefik are you using?

2.10

### What is your environment & configuration?

Any plugin will fail. I tried at least 2.

Workaround is to download the plugins archive from github and use local plugins instead.

**Comment by jdel** [comment]
Turns out the problem is now resolved.

If it's any help to the traefik team, from my instance point of view, it started occurring for the first time at 17:07 today.

**Comment by ldez** [comment]
The problem has been fixed.
