### ISSUE TITLE
Ping response 200 OK before the parameters are loaded

### ISSUE THREAD

**Issue by gasgurda** [traefik/traefik#10151]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I sent User trafic to traefik when ii was restarting. I lose some of percentage trafic with response 404. I found out that /ping response is 200/OK before traefik loads configuration.

### What did you see instead?

/ping should give response 200/OK after traefik Configuration loaded from flags

### What version of Traefik are you using?

v2.9.10

### What is your environment & configuration?

```yaml
  - args:
    - --api
    - --api.insecure=true
    - --serversTransport.insecureSkipVerify=true
    - --accesslog
    - --providers.kubernetescrd.allowCrossNamespace=false
    - --entryPoints.metrics.address=:8082
    - --entryPoints.coredns.address=:8083
    - --entryPoints.kubestate.address=:8084
    - --metrics.prometheus.entryPoint=metrics
    - --metrics.prometheus.addEntryPointsLabels=true
    - --metrics.prometheus.addServicesLabels=true
    - --entryPoints.web.forwardedHeaders.insecure
    - --log.level=ERROR
    - --serversTransport.forwardingTimeouts.responseHeaderTimeout=30s
    - --serversTransport.forwardingTimeouts.idleConnTimeout=30s
    - --entrypoints.metrics.address=:9101/tcp
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.web.address=:80/tcp
    - --entrypoints.websecure.address=:443/tcp
    - --api.dashboard=true
    - --ping=true
    - --metrics.prometheus=true
    - --metrics.prometheus.entrypoint=metrics
    - --providers.kubernetescrd
    - --providers.kubernetesingress
    - --entrypoints.websecure.http.tls=true
```

Add more configuration information here.

**Comment by nmengin** [comment]
Hello @gasgurda,

Thanks for reaching out!

The behavior you've described is expected: the default ping configuration allows returning a 200 code as soon as Traefik is up and running.
There a 2 ways to improve the situation on your side:
    - Set the option [`--ping.manualrouting`](https://doc.traefik.io/traefik/operations/ping/#manualrouting) and create an IngressRoute that allows reaching the service internal@ping as explained in the documentation. Thus you can set the router to check your Traefik pod liveness.
    - Keep the configuration as it is, and use the ping only for the traefik pod readiness. In such a case, you have to define another router, that is not linked to the eping mechanism, to check the liveness.

I hope this answer can help you.

If you need more information, we ask that all questions be asked in the [community forum](https://community.traefik.io/) and get help from other community members pretty quickly, it is pretty active.
