### ISSUE TITLE
Repository management

### ISSUE THREAD

**Issue by geraldcroes** [traefik/traefik#10155]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Today the traefik organization on github contains both commercial projects of traefk labs, and open source projects sponsored and owned by traefik labs.

In a recent effort to secure and harmonize traefik labs repository management, traefik labs made a couple of changes that induced some rights loss for very few maintainers of open source repositories. 

I’m creating this issue to clearly discuss our goals and track needed actions:
- Traefik Labs wants every maintainer to have every permission needed to fully embrace their role
- At the same time, for security reasons, Traefik Labs wants to limit the number of people able to delete/transfer ownership of repositories to a couple of people.

To achieve this, we might need to split organizations between open source and commercial products. Traefik (this organization) being dedicated to open source projects with current maintainers (and more in the future) and another one for commercial products. 

This is of course not the only solution, but one of them.

**Comment by ldez** [comment]
This discussion should be done inside the Traefik maintainer discord not in a public area.

**Comment by geraldcroes** [comment]
I like things to be as transparent as possible, so I created this issue.
This might be interesting for contributors and potential maintainers to know what is happening. 

I'll revert to needs-triage, and I propose we discuss it as documented during the triage process, with other maintainers.
If we make a decision, we'll update with the action plan.

**Comment by ldez** [comment]
you are confusing transparent and public.

**Comment by ldez** [comment]
An issue is not a good place for discussion and triage is not the place to discuss this kind of topic. Triage is for the triage of issues, and an issue is not an invitation to a meeting.

**Comment by ldez** [comment]
Flagging my comment as off-topic, because you don't agree with, is clearly not a good idea.

**Comment by emilevauge** [comment]
@ldez I really don't see why this discussion shouldn't be made public.
There is nothing to hide here.
Traefik is an open source project, with an open gouvernance.
Permissions management on the repo should definitely be a public topic.

**Comment by rtribotte** [comment]
I agree with the proposal, splitting concerns looks to be a good approach to ease the management of each side and fulfill security concerns.

**Comment by nmengin** [comment]
Thank you @geraldcroes for your proposal.
I close this issue that is opened for more than one year.
