### ISSUE TITLE
A formal null middleware or an acceptable work around

### ISSUE THREAD

**Issue by rit001** [traefik/traefik#10166]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

This may seem a strange request - support for a feature to basically do nothing, but here is the background

As Traefik operates by defining a single middleware to a router or instead defining a chain of middleware as a group that can then be assigned to a router I am currently defining a number of different chains that can be switched between for a deployment depending on where within the dev-CI-production pipeline the deployment is. So a development deployment would have little or no security, CI systems may have different features depending on the testing task and production would have all the features enabled.

Being based on a docker-compose file the selection is handled by just setting an environment variable that forms part of the 
definition via standard parameter expansion.

The only issue is that there is no formal null/do-nothing middleware defined within Treafik, so you can not easily handle the case where you do not want any action taken. Instead, you have to complicate the process by removing the whole line that does the assignment of a middleware chain to a router, which then in turn changes the structure shown by the Traefik console.

Another option would be to define a one-entry chain with one of the current middlewares in such a way as to cause it to not change the data flow, but I do not know the platform well enough to know which of the available middlewares has the lowest overhead or the least number of side effects on things like logging.

Does anyone have any ideas?

**Comment by ldez** [comment]
Hello,

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there. 
If not, you can ask and get help from other community members pretty quickly.

> As Traefik operates by defining a single middleware to a router or instead defining a chain of middleware as a group

it's not exactly true: you can assign multiple middleware to a router without a chain.
https://doc.traefik.io/traefik/routing/routers/#middlewares

You don't need a chain to use multiple middleware. The chain is useful for reusing a group of middleware.

You can create a plugin based on one we created to handle something close to your use case: https://plugins.traefik.io/plugins/634ed49499550ba2e3b43d5c/noop

Or you can just use the [headers middleware](https://doc.traefik.io/traefik/middlewares/http/headers/) with a "fake" header.

Please join the forum if you need to discuss more about that.

**Comment by rit001** [comment]
This has converted into more of a suggestion that the doc be improved.

The reply 

`it's not exactly true: you can assign multiple middleware to a router without a chain`

Allowed me to re-read the only docs to understand that this is in fact possible. So the docs could be improved by making this far clearer.

At the same time if the assignment to a standard router could be more than a single middleware I also tried the case of not assigning any middleware, which in fact works very much like having a null middleware available - as in there is an assignment recorded without any errors being thrown.

**Comment by ldez** [comment]
The documentation says:

> You can attach a **list** of middlewares to each HTTP router.

The examples are using list syntax.

There is no example or mention of the chain middleware in this section.

https://doc.traefik.io/traefik/routing/routers/#middlewares

I don't see how to improve this.

**Comment by rit001** [comment]
I think you can write that as you are fully aware of what "list" means in the context of Traefik's use of YMAL, not all of us have that level of understanding so need to find lots of detail in the docs to give us the hints to fill in our knowledge gaps.

The section you linked to states  "Middlewares are applied in the same order as their declaration in router."

But how as it is not clear in this section? So the logical step is to click on the middleware link

Now you have a section that shows chained middleware in the image and some text that states "Middlewares that use the same protocol can be combined into chains to fit every scenario". So we are getting somewhere

But there are again no examples provided of a chain, just a single assignment, so you know you can chain middlewares, but are not sure how, so you put chain in the search and get to an example of how to build a chain.middleware.

At no point in this discovery process do the docs just say (or show) that you can list 0..n middlewares against a defined router. Instead, they lead you to the chain.middleware feature, which is a nice feature but not really needed in most deployments.

An additional complication is that the area of the docs that you linked to is also without Docker YAML examples, instead a link is provided to a more general Docker area that I did not even notice until writing this reply as I followed the path above.

If I had access to the docs I would make the following changes

- Change the YAML and TOML examples to have more than one middleware entry, this would then show the concept of a 'list' in action, while also better matching the supporting text and the example that is given in the independent Docker example (which I missed until just now).

- Make it clear that it is possible to define a router middleware entry with no middleware listed  (basically a null list).

The last one comes from the fact that many Docker/Kubernetes deployments are dynamic in nature and often driven by variable values. So for my environment, the middleware configured for a system instance changes based on where it fits in the deployment pipeline, but all 12 different deployments are using the same docker-compose file, they just have different environment variable values set when docker compose is run. 

So within my docker-compose.yml file, I have labels assigned to containers like this

      - "traefik.http.routers.SalesPlatform_frontend-secure.middlewares=${DOCKER_TRAEFIK_MW_FE_WEBSITE}" 

I just set DOCKER_TRAEFIK_MW_FE_WEBSITE to the list of middlewares I want loading by the deployment in question.


(I'm writing this as wordy as I can so that it may be picked up by search engines and possibly help others).

**Comment by ldez** [comment]
If you want you can open a PR to improve this section based on your suggestions.
Click on this [link](https://github.com/traefik/traefik/edit/v2.10/docs/content/routing/routers/index.md).

**Comment by rit001** [comment]
With the slight problem that my knowledge of the correct layout of the 3 different types of config files is limited to the docker format. I have no example of how the direct YAML and TOML files should look to extend them to be better examples.
