### ISSUE TITLE
Authentication with Tailscale

### ISSUE THREAD

**Issue by courtland** [traefik/traefik#10173]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Now that Traefik supports Tailscale as a cert provider, it would be great to be able to authenticate against it's whois API. The use case for this is to expose public and Tailnet-only services from the same Traefik instance running on the same port (e.g. 443).

The options to do this currently seem to be:

1. Multiple `EntryPoint`s, where one listens on tailscale0 only, and another listening on non-tailscale0 interface/IP(s). This is possible but tricky to configure depending on the environment. For example, Traefik has no way to ignore certain IPs on an EntryPoint, and hardcoding the Tailscale IP is not ideal.

2. Use `ForwardAuth` against the "official" [nginx-auth](https://github.com/tailscale/tailscale/tree/main/cmd/nginx-auth) binary that Tailscale ships. This is [already possible with Caddy](https://caddyserver.com/docs/caddyfile/directives/forward_auth#tailscale), but currently not with Traefik due to the lack of unix socket support. #4881 is a blocker here. The nice thing about having ForwardAuth integration with Tailscale is the ability to supply trusted authorization headers to downstream services. Tailscale has a [related issue](https://github.com/tailscale/tailscale/issues/4680) to hopefully make their nginx-auth officially support non-nginx servers.

3. Role your own ForwardAuth based on something like: https://github.com/kevin-hanselman/tailscale-forward-auth, which doesn't appear to be maintained, unlike Tailscale's nginx-auth. @lox has a [fork](https://github.com/lox/tailscale-forward-auth) that is at least updated and works.

4. Traefik implements the ability to auth directly against the local Tailscale whois API. This could leverage the [tsnet library](https://tailscale.com/kb/1244/tsnet/). Tailscale offers a [plugin that does this for Caddy](https://github.com/tailscale/caddy-tailscale). However, it would be nice to be able to integrate against a Tailscale instance already running on the host - this is where ForwardAuth is nice.

Issue #9909 is somewhat related, in that I imagine some of the implementation details could be shared.

I'd appreciate any thoughts/comments or alternatives I haven't discovered. Thank you.

**Comment by lox** [comment]
This would be awesome. My fork suddenly stopped working yesterday, still trying to figure it out.

**Comment by nmengin** [comment]
Hey @courtland,

Thanks for your suggestion.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

**Comment by FredHaa** [comment]
This feature would be very welcomed.

**Comment by nmengin** [comment]
Hello,

This proposal was opened 3 months ago with almost no traction.
We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.

Thank you @courtland for the suggestion and @lox @FredHaa for your comments.

**Comment by vnghia** [comment]
> use case for this is to expose public and Tailnet-only services from the same Traefik instance running on the same port

To do this, I run a `traefik` container with `tailscale` sidecar vpn. And having two entrypoints, 443 for tailscale only services and 444 for public-accessible ones. The trick here is to bind port 444 to 443 on host and then you can have `100.x.y.z:443` for tailscale and `<host-ip>:443` for public accessible ones.
