### ISSUE TITLE
Document potential race conditions in replicated Traefik v2 CE with Letsencrypt

### ISSUE THREAD

**Issue by YuryHrytsuk** [traefik/traefik#10180]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The documentation describing integration with Letsencrypt does not explicitly warn readers that in case of multiple replicas Traefik v2 CE will have race conditions that may lead to ban from Letsencrypt(e.g. [duplicate certificate limit](https://letsencrypt.org/docs/duplicate-certificate-limit/)). I believe many would use replicated Traefik v2 CE

This is related to:
* https://github.com/traefik/traefik/issues/5792
* https://github.com/traefik/traefik/issues/5426

**Comment by ldez** [comment]
Hello,

the documentation explains that:

![Screenshot 2023-10-19 at 12-02-45 Traefik Let's Encrypt Documentation - Traefik](https://github.com/traefik/traefik/assets/5674651/c0da91f6-01d6-43e1-94d2-052c9ea1b99f)

https://doc.traefik.io/traefik/https/acme/#storage
