### ISSUE TITLE
Release Traefik v2.11

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#10192]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### Context

Hello there,

With some maintainers, we're gearing up for a potential release of Traefik v2.11 and we wanted to loop you in on the action.

I wanted to share that despite Traefik v3 being in beta for almost a year, it's still a project close to our hearts. We're excited to discuss its long-term future with all of you. In fact, we'll be opening a proposal on this very topic very soon.

Your insights and feedback on this matter are highly valued. Let's come together and shape the future of v3.

Stay tuned for the proposal, and let's keep the discussion going.

### Content

In the meantime, there are several features and pull requests that we're eager to introduce.
We believe that releasing them as part of a new v2.11 version would make perfect sense to get them into your hands sooner.

Non-exhaustive list of features we can bring in v2.11:

- https://github.com/traefik/traefik/issues/10168
- https://github.com/kvtools/redis/issues/5
- https://github.com/traefik/traefik/issues/10191
- and more...

### Open Telemetry Support

In addition to these new features, we'd love to get your thoughts on Open Telemetry.
We successfully integrated it into v3 last year, and it has been working smoothly without any breaking changes.
Now, we're contemplating backporting it into v2.11.

What do you think? Your opinion matters to us, and we value your input as part of the Traefik community.

**Comment by arukiidou** [comment]
I would like to see opentelemetry backport
- https://github.com/traefik/traefik/issues/9762#issuecomment-1522863907

**Comment by nmengin** [comment]
Hello @arukiidou,

Thanks for your feedback.

After digging deeper, backporting OTel in v2 doesn't seem doable without bringing breaking changes.
We'll keep it for v3.0.

**Comment by nmengin** [comment]
Hey there,

Quick update on the maintainers' end.

Thanks to everyone who joined the conversation (forum, attendees on KubeCon, issue).
After discussing the proposal with the other maintainers, we've settled on kicking off the v2.11 release with a narrowed-down focus.

It's gonna be the final hurrah for v2 as we set our sights on [the big v3.0 game plan](https://github.com/traefik/traefik/issues/10260).

Here's the final scope for this version:
- [Service Fabric Integration](https://github.com/traefik/traefik/issues/10168)
- [Connections’ Keep Alive Management](https://github.com/traefik/traefik/issues/10191)
- [Redis Sentinel Support](https://github.com/traefik/traefik/issues/10228)
- [WRR support on sticky cookies](https://github.com/traefik/traefik/pull/10243)
- [Deprecate IPWhiteList and IPAllowList to prepare the v3 migration](https://github.com/traefik/traefik/pull/10249)

We'll proceed with the RC once the above scope is merged.

**Comment by bluepuma77** [comment]
One of the major breaking changes for v3 will be the Docker Swarm provider, as it changes from `providers.docker.swarmMode=true` to `providers.swarm`. 

Would it make sense to already have a console warning in v2.11, when Swarm is enabled, that it will change with v3?

**Comment by nmengin** [comment]
Hello @bluepuma77,

Thanks for reaching out.

We haven't added a deprecation message because, with the other maintainers involved in the discussion, we think that it's not a good idea to deprecate a feature without proposing a new one in the same version.
As backporting in v2 the new Swarm provider requires some effort, we prefer to focus on a migration guide (tooling?) to ease the migration.

That's why we haven't planned yet to deprecate the option `providers.docker.swarmMode=true` in v2.11.

Please note that we do our best to bring in v3 only breaking changes that are mandatory.
We pay attention to the migration cost and we avoid embedding changes with a big impact on our users' production.

**Comment by nmengin** [comment]
Traefik v2.11 GA has been released, I close the issue accordingly.
Thanks @mloiseleur.
