### ISSUE TITLE
open-telemetry stable HTTP semantic conventions

### ISSUE THREAD

**Issue by schewara** [traefik/traefik#10219]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

With the [HTTP semantic conventions declared stable](https://opentelemetry.io/blog/2023/http-conventions-declared-stable/) in `v1.23.0` and it's big impact on all the attributes, Traefik should support it already in `v3.0` before GA.

This would potentially avoid a lot of extra work and frustration later on, if enabling the brand new OTel functionality and having to update/refactor the whole observability stack to deal with all the changed attributes a view releases later.

**Comment by nmengin** [comment]
Hey @schewara,

Thanks for your suggestion.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

**Comment by zetaab** [comment]
some of these are implemented in https://github.com/traefik/traefik/pull/10223/files#diff-f1e0d24911164f850e8c1e92b5e73073d417eb5ca067ad3feba01bc6d6211082R109-R130

**Comment by arukiidou** [comment]
> Hey @schewara,
> 
> Thanks for your suggestion.
> 
> We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.
> 
> We will  as people respond.

- traefik will got benefits from APMs evolution for free
  - For example
    - APM vendors provide by default a filtering UI for trace with a specific name.
    - If you follow semconv, we can make an opentelemetry-semconv Grafana dashboard
    - If you follow your own metrics, I will make a dashboard dedicated to traefik. 
      - This is more labor intensive and will slow down maintenance if I am busy.

**Comment by mmatur** [comment]
Closed by https://github.com/traefik/traefik/pull/10223

**Comment by arukiidou** [comment]
@mmatur 
- Please re-open this.
- Traefikv3 supports Opentelemetry, but metric semantics doesn't conforts semantic conventions of Opentelemetry.

[[traefik v3(docs)](https://doc.traefik.io/traefik/v3.0/observability/metrics/overview/#http-metrics)]
```
traefik_entrypoint_requests_total
traefik_entrypoint_requests_tls_total
traefik_entrypoint_request_duration_seconds
traefik_entrypoint_requests_bytes_total
traefik_entrypoint_responses_bytes_total
```

[[Opentelemetry (semconv docs)](https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/http/http-metrics.md)]
https://github.com/open-telemetry/semantic-conventions/blob/v1.23.0/docs/http/http-metrics.md

**Comment by arukiidou** [comment]
thank you!
