### ISSUE TITLE
Add browser info at least user-agent to OTEL traces

### ISSUE THREAD

**Issue by trajano** [traefik/traefik#10210]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

https://opentelemetry.io/docs/specs/semconv/resource/browser/ specifies a `user_agent.original` attribute.  Can that be added into the traces at minimum?  The rest can be added later.

The use case is if we look at the trace from the top which is actually traefik.  We want to know as much information about the client so we don't have to dig through the lower level traces to find out information that would've been available to Traefik already.

**Comment by nmengin** [comment]
Hey @trajano,

Thanks for your suggestion.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

**Comment by trajano** [comment]
I've updated the OP for use case

**Comment by rtribotte** [comment]
Fixed by #10223
