### ISSUE TITLE
the forward span.kind should be `client` rather than `internal`

### ISSUE THREAD

**Issue by trajano** [traefik/traefik#10235]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Enable OTEL tracing

### What did you see instead?

When traefik eventually makes a `forward` call the span kind should be `client` rather than `internal`

![image](https://github.com/traefik/traefik/assets/110627/1f10bee0-358a-4cb3-9698-c1b63eb5f423)

### What version of Traefik are you using?

3.0 beta 4

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by zetaab** [comment]
@trajano this is fixed in https://github.com/traefik/traefik/pull/10223

screenshot from traefik that is using that PR code:


<img width="1498" alt="Screenshot 2023-11-13 at 16 58 44" src="https://github.com/traefik/traefik/assets/22482503/6a708dac-d32d-4870-8e9e-8f8d0b4a3c33">

**Comment by rtribotte** [comment]
Fixed by #10223
