### ISSUE TITLE
doc: how to send USR1 signal in k8s

### ISSUE THREAD

**Issue by wszgrcy** [traefik/traefik#10240]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I want to set lo rotation and see [https://doc.traefik.io/traefik/observability/access-logs/#log-rotation](https://doc.traefik.io/traefik/observability/access-logs/#log-rotation)
But In this doc, `Traefik will close and reopen its log files, assuming they're configured, on receipt of a USR1 signal. This allows the logs to be rotated and processed by an external program, such as logrotate.`
Didn't mention which signal to send to `container?`,`traefik pid?`
And Didn't mention how to send the signal in `docker`/`k8s`
I searched the entire internet but couldn't find a way to send this signal on k8s
So could you please improve the relevant documents

**Comment by nmengin** [comment]
Hello @wszgrcy,

Thanks for reaching out! To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.

If not, you can ask and get help from other community members pretty quickly.
