### ISSUE TITLE
Improve the display of security-header values

### ISSUE THREAD

**Issue by rit001** [traefik/traefik#10246]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

To define a Content-Security-Policy within Traefik you create a HTTP Middleware which is viewable from within the GUI.

The problem is that a CSP has a number of fields/policies that can be very long - or essay-like. The current way that the field contents are displayed does not allow the whole value to be viewed. Instead, you have to copy the field and paste it into another tool.

Elsewhere enhancements have been made to improve the viewability of fields, as can be seen in the IP list of a whitelist source range.

**Comment by nmengin** [comment]
Hello @rit001,

We are interested in this issue, and we would love some help from the community.

If you or another community member would like to contribute on this, let us know, and we will work with you to make sure you have all the information needed.
Let us know here before you start. We prefer to work with our community members to ensure that we are aligned and can move quickly with the review and merge process.

**Comment by rit001** [comment]
My skill set nowadays is infrastructure, I gave up development around the time I was coding with 68000 and DBASE, so I can not help extending Traefik.

**Comment by roman-kiselenko** [comment]
Hey! I want to work on this.

**Comment by roman-kiselenko** [comment]
@nmengin hey, I've reproduced a bug. 

The variant with > `1020px` width:
<img width="641" alt="image" src="https://github.com/traefik/traefik/assets/3471384/d9e8056a-7e87-425d-bd29-ea2b49ba264c">

The variant with `750px` width:
<img width="741" alt="Screenshot 2023-11-27 at 17 50 45" src="https://github.com/traefik/traefik/assets/3471384/96c48d19-7a65-48b7-bb27-eee62fad9e30">

I don't know how to deal with it from the UI side. 
I'm thinking about some `textarea`. 
Can you guide me a little? 🙏

**Comment by nmengin** [comment]
Hello @roman-kiselenko,

Thank you for contributing. Unfortunately, I do not have enough UI skills to help you.
@mdeliatf @gndz may help you in a more relevant way.

**Comment by nmengin** [comment]
Hey team,

I tag it as a big confirmed to fix it in the current version (v3.0).

**Comment by rit001** [comment]
As this topic is still ongoing it seems a good idea to provide an example of what the field may try and contain. 

Below are the contents of my "Custom Response Headers" field, As is clear this is somewhat larger than the 2 lines of text that the GUI can currently handle, but it should be noted

  - SCP setting can get far more complicated and so far longer. 
  - I have added the LF/NLs to make the SCP readable. As standard, they are not included so the output is a single line stream. The LF/NLs were added after every semi-colon as that is the natural break point for human readability.



Content-Security-Policy-Report-Only: 
connect-src 'self' www.domain-dev1.xyz salesplatform.domain-dev1.xyz domain.cdn.prismic.io api.mapbox.com events.mapbox.com;
default-src https:;
font-src 'self' netdna.bootstrapcdn.com fonts.gstatic.com ;
img-src 'self' * data:;
script-src 'self' www.domain-dev1.xyz salesplatform.domain-dev1.xyz domain.cdn.prismic.io ajax.cloudflare.com;
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com cdnjs.cloudflare.com api.mapbox.com;worker-src blob:;
script-src-elem 'self' 'unsafe-inline' challenges.cloudflare.com;
object-src 'none'; 
base-uri 'none';
report-uri https://o1176104.ingest.sentry.io/api/4506258004246528/security/?sentry_key=6dfd7be5c32f1883096cbc1e5ff84ef5
X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex

**Comment by kevinpollet** [comment]
Hello @rit001,

We merged https://github.com/traefik/traefik/pull/10710, is it enough for you?
If so, we can close this issue.

**Comment by rit001** [comment]
Thanks, looks fine, the need is really for the GUI to make it clear to the viewer that there is a large complicated SCP, which the multi-line text box does. Beyond that, the issue becomes something for the viewer to deal with as SCPs can become an essay-length document without any line breaks. The management of such configurations is not a traefik issue.

**Comment by nmengin** [comment]
Hello @rit001,

Thanks for your feedback, I close the issue accordingly.
