### ISSUE TITLE
Another Content Security Policy complication.

### ISSUE THREAD

**Issue by rit001** [traefik/traefik#10257]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Traefik makes a great place to define Content Security Policies as they can then be enforced on any published service by the operation team regardless of what support developers and third-party vendors may supply/support.

The complication is that CSP is something of a moving standard and in version 2 the concept of a nonce to allow the real-time tagging of content so that CSP could be more restrictive. The details of this can be found here

https://content-security-policy.com/nonce/

In general, this was originally designed for developers to be able to tag elements with the nonce and directly modify the header from within the application code. Cloudflare has extended this idea so that they extract the nonce found in the header and add it to the scripts it adds to a session, as detailed here

https://developers.cloudflare.com/bots/reference/javascript-detections/

So why post all of this -

Would it not make sense for Traefik to have the ability to inject such nonce's into the CSP header if one is not already there as an extension of its current CSP support?

**Comment by nmengin** [comment]
Hey @rit001,

Thanks for your suggestion.

We are interested in this issue, but we’re unsure about the use case and the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.

We will reevaluate as people respond.

**Comment by rit001** [comment]
I can provide some more 'context'

Firstly the current use case is that of integration with Cloudflare as Cloudflare is becoming something of a common component for many deployments, so their expectation of a nonce being provided is going to be more of an issue over time. Without the nonce, any defined CSP can not be as strict as it should be, which means it scores lower on any CSP validation tool.

The level of traction from users of the open-source version of Traefik is likely to be low as many users just do not need this level of control - they are unlikely to be trying to pass security audits to handle personal data or payments. There is also a plugin that can do this at the basic level.

Now for anyone who is looking at Traefik as a business-grade solution, once they find this 'complication' with CSP support, Cloudflare and security validation it all becomes more complex. If Traefik can not provide the nonce an alternative has to be found, that alternative also now has to provide the whole CSP header. At which point Traefik is no longer the central point of control.

It is the last stage I'm currently at. We are a startup (big plans, but not yet at the point of raising real funding). So I'm using open-source Traefik because until I started dealing with CSP setup it was able to deal with everything I threw at it. This made the upgrade to the enterprise edition a simple funding choice. Today due to CSP/Cloudflare Traefik is not a long-term viable solution without a rework of my environment and the introduction of another tool that can inject the correct information into the data stream.


As for the available open-source plug-in, there is nothing wrong with it, but it is rather hard to pass a full security audit if key aspects of your security model are open-source code that comes with no warranty. Such audits are the reason I will be paying for the enterprise version of Traefik as getting a passing score will in part be because of the quality of the tools and support levels that have been put in place.

**Comment by rit001** [comment]
This is not so much of a bump, but instead, it seems a good idea to provide an unofficial link to another CSP issue/request that has recently been marked with a higher focus

https://github.com/traefik/traefik/issues/10246

My logic is that if there is to be some focus on improving CSP support it would be worth looking at how the overall support can be enhanced.

**Comment by nmengin** [comment]
Hello @rit001 ,
This proposal has almost no traction.

We won't add it to the Roadmap yet and we prefer to close it.
We'll re-open it later if necessary.
