### ISSUE TITLE
How to update / renew user-defined certificates?

### ISSUE THREAD

**Issue by YuryHrytsuk** [traefik/traefik#10267]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I want to switch to user-defined certificates. Every 3 months I will manually renew certificates with [Lego](https://go-acme.github.io/lego/) and then I want to feed them to traefik. How to do that? 

Will updating certificate files in a volume with certificates suffice? Do I need to restart traefik? 

P.S. this only involves update / renew already existing certificates.

**Comment by ldez** [comment]
Hello,

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there. 
If not, you can ask and get help from other community members pretty quickly.
