### ISSUE TITLE
Cert file permissions on Microsoft Azure Container Instance

### ISSUE THREAD

**Issue by RufusJWB** [traefik/traefik#10266]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm running Traefik2 inside an Azure Container Instance (ACI). Everything works fine, except for the persistent storage of the acme.json file. I've mounted an Azure Fileshare into the container and Traefik correctly writes the acme.json file onto that fileshare, but when I restart the container I get this error message:

`"The ACME resolver "my-le-resolver" is skipped from the resolvers list because: unable to get ACME account: permissions 777 for /letsencrypt/acme.json are too open, please use 600"`

I searched it here and found plenty of workarounds (https://github.com/traefik/traefik-helm-chart/issues/396), all at the end boiling down to changing the permission manually to 600. But in ACI this isn't possible due to restrictions in the way, how file shares are mounted:

```
/letsencrypt # ls -l
total 16
-rwxrwxrwx 1 root root 16048 Nov 14 10:32 acme.json
/letsencrypt # chmod -v 600 acme.json
mode of 'acme.json' changed to 0600 (rw-------)
/letsencrypt # ls -l
total 16
-rwxrwxrwx 1 root root 16048 Nov 14 10:32 acme.json
/letsencrypt #

```
Please make it possible to disable this check for permissions.

**Comment by ldez** [comment]
Hello,

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there. 
If not, you can ask and get help from other community members pretty quickly.

**Comment by RufusJWB** [comment]
> To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.
> If not, you can ask and get help from other community members pretty quickly.

The user forum wasn't able to provide a work around: https://community.traefik.io/t/file-permission-for-acme-json-cant-be-changed-on-azure-container-instance-aci/20490 And in fact I doubt that a work-around is available for ACI due to the nature of Microsoft Azure Container Instance. Therefor I humble request to disable the permission checking, e.g. based on an environment variable.
