### ISSUE TITLE
The current Twitter icon on the website appears outdated and needs to be updated 

### ISSUE THREAD

**Issue by Ayush9026** [traefik/traefik#10291]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The Twitter icon located on the website (provide specific location if possible, e.g., header, footer, social media section) is not aligned with the latest design standards. To maintain a cohesive and up-to-date visual identity, it is essential to replace the existing Twitter icon with the latest version provided by Twitter or any updated branding guidelines. Marked in screenshot below.

**Steps to Reproduce:**

Visit the website [provide URL].
Navigate to the [specific page or section].
Observe the Twitter icon.

**Screenshots/Attachments**

![Traefik Website](https://github.com/traefik/traefik/assets/114745463/735836c8-f70b-4599-b70a-37ddeb9a8367)

**Expected Behavior:**
The Twitter icon should adhere to the latest design standards, ensuring a consistent and polished appearance across the website.
This issue is crucial for maintaining a visually appealing and consistent user experience on the website

**Comment by nmengin** [comment]
Hello @Ayush9026,

Thanks for reaching.

I've shared the issue with the person in charge of the website.
I'll update this issue according to their feedback.

**Comment by Ayush9026** [comment]
Thanks @nmengin sir.

**Comment by nmengin** [comment]
Hey @Ayush9026,

We've updated the website with the new logo.
I close the issue accordingly.

Thanks again for reaching out.
