### ISSUE TITLE
Backporting TCP Servers Transports support to Traefik 2.x

### ISSUE THREAD

**Issue by ivantopo** [traefik/traefik#10309]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It is impossible to reach a Consul Connect-enabled TCP service with Traefik 2.x (at least up to 2.10.7) because Traefik is not setting up the appropriate certificates when connecting to the sidecar proxies. I see these two PRs got merged on the v3.0 branch to enable the behavior we need:
  - Adding TCP Server transports: https://github.com/traefik/traefik/pull/9465
  - Enabling TLS by default for Consul Connect TCP services: https://github.com/traefik/traefik/pull/10140

Can this feature be backported to the 2.x series? Thanks!

**Comment by geraldcroes** [comment]
Hello and thank you for this proposal, 

we discussed it in triage, and we're unfortunately trying to wrap up the next 2.11, which ultimately would be the last 2.X appart from bugfixes.

I'm going to refuse the proposal accordingly and will encourage you to migrate to v3 once it's GA.
