### ISSUE TITLE
Tailscale certificate resolver storage location

### ISSUE THREAD

**Issue by tandy-1000** [traefik/traefik#10316]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The tailscale certificate resolver does not provide the option to set a storage location for the certificate.

It would be very useful to be able to configure this storage location or to make it known where it is so that we can access the certificates for applications which need access for SSL configuration.

**Comment by jspdown** [comment]
Hey @tandy-1000 

Thanks for your suggestion.

We are interested in this issue, but we’re unsure about the use case and the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.
We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know, and we will work with you to make sure you have all the information needed.
Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.

**Comment by nmengin** [comment]
Hello,
This proposal was opened more than 6 months ago with almost no traction.

We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.
