### ISSUE TITLE
can you fix the go.mod

### ISSUE THREAD

**Issue by zhaizhch** [traefik/traefik#10329]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

when import traefik, it report a bug that "github.com/abbot/go-http-auth@v0.0.0-00010101000000-000000000000: invalid version"

### What did you see instead?

I should paste the replace items to our project's go.mod to solve this question.

### What version of Traefik are you using?

v2.9.10

### What is your environment & configuration?

you can modify the go.sum, replace `github.com/abbot/go-http-auth`  with `github.com/containous/go-http-auth v0.4.1-0.20200324110947-a37a7636d23e` directly

**Comment by zhaizhch** [comment]
the same as 'github.com/go-check/check@v0.0.0-00010101000000-000000000000'

**Comment by kevinpollet** [comment]
Hello @zhaizhch and thanks for opening this issue,

We are using `replace` directives to use fixed versions of some dependencies. This is how Go modules work, the `replace` directives are not transitive and must be added manually. From the [documentation](https://go.dev/wiki/Modules): 

> exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module.

Modifying the `go.sum` is not an option as this file is generated and handled by Go modules command.
