### ISSUE TITLE
Add Support for different TLS Stores

### ISSUE THREAD

**Issue by Lol3rrr** [traefik/traefik#10365]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently the only way to store TLS certificates in the Open Source version of traefik is to store them on disk/as files. However for me personally this complicates the setup in my homelab as I need to synchronise these files across servers.

I would initially propose an S3 based certificate store, as that could potentially map relatively easily onto S3 coming from the files.
I do recognise that this could pose a security risk when using a publicly accessible S3 instance, but considering that more platforms support S3 compatible APIs for internal data storage, I think there is at least some use case for this.
This would NOT include support for multiple traefik instances running at the same time, as the storage would act basically the same as the current file storage and provide no extra synchronization, the only benefit would be that it becomes easier to move the traefik instances between nodes.

**Comment by ldez** [comment]
Duplicate of #4756

**Comment by Lol3rrr** [comment]
Although I see the similarity, does the other issue also cover different types of TLS Stores? All I can see in that discussion is the intend to have multiple stores, but those still use the file system for actually storing the certificates itself
