### ISSUE TITLE
Feature: Passthrough Proxy-Authorization header

### ISSUE THREAD

**Issue by voruti** [traefik/traefik#10366]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

As [already discussed in the forum](https://community.traefik.io/t/proxy-authorization-header-passthrough/13207) I would like to pass-through the `Proxy-Authorization` header to a service behind Traefik.

Since https://github.com/traefik/traefik/issues/7374 it's already possible to use it for a service behind the forwardauth middleware. In my use case (https://github.com/authelia/authelia/discussions/6542#discussioncomment-8192029, Host 1 in the image) I have an authorization server not only behind the forwardauth middleware, but also as a direct backend service behind Traefik.

I already did some research on my own (on why the header currently is removed, what would need to be done, etc. - see forum link above), but ultimately I don't know enough about the subject.

**Comment by lbenguigui** [comment]
Hello @voruti,

Thanks for your suggestion.

We are interested in this issue, but we’re unsure about the use case and the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.
We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know, and we will work with you to make sure you have all the information needed.

Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.

**Comment by nmengin** [comment]
Hello,

This proposal was opened more than 6 months ago with no traction.

We won't add it to the Roadmap yet and we prefer to close it.
We'll re-open it later if necessary.
