### ISSUE TITLE
Expose metrics on providers state

### ISSUE THREAD

**Issue by the-nando** [traefik/traefik#10376]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be nice to have metrics to track issues with Providers, under a new space traefik_provider_, e.g. `traefik_provider_errors_total{provider="consulCatalog"} x` to be able to monitor errors like:

```
{"level":"error","msg":"Provider connection error failed to get consul catalog data: Get 
\"https://127.0.0.1:8501/v1/catalog/services?stale=\": remote error: tls: bad certificate, retrying in 
615.460936ms","providerName":"consulcatalog","time":"2024-01-19T07:04:38Z"}
```

At the moment it's not possible to monitor natively such failures. This is similar to https://github.com/traefik/traefik/issues/10236 but for another domain.

**Comment by jspdown** [comment]
Hello @the-nando :wave: And thanks for your interest in Traefik.

Could you explain a bit more your use case for this new metric? Especially, why monitoring these from filtered logs (filtered with the `providerName` field) is not enough?

**Comment by the-nando** [comment]
Hi @jspdown 😄 The use case is to monitor providers health / status with Prometheus. Tailing the logs is a possible solution but it requires external tooling / exporters which may not be available, and since Traefik already exports Prometheus metrics it should be possible to have them exported natively without much change.

**Comment by jspdown** [comment]
Thanks for the explanation.

We’re unsure about the use case and the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.
We will reevaluate as people respond.

**Comment by ygersie** [comment]
I would definitely like to add here that it makes sense traefik exposes error rates on provider issues.

**Comment by nmengin** [comment]
Hello there,
This proposal has almost no traction.

We won't add it to the Roadmap yet and we prefer to close it.
We'll re-open it later if necessary.
