### ISSUE TITLE
AWS ECS Service connect

### ISSUE THREAD

**Issue by aleyrizvi** [traefik/traefik#10394]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello, 
As mentioned here: #9662 service connect is a new service and current ECS provider is not able to handle it because of below code:

```
if len(task.Attachments) != 0 {
					if len(container.NetworkInterfaces) == 0 {
						logger.Errorf("Skip container %s: no network interfaces", aws.StringValue(container.Name))
						continue
					}

					var ports []portMapping
					for _, mapping := range containerDefinition.PortMappings {
						if mapping != nil {
							protocol := "TCP"
							if aws.StringValue(mapping.Protocol) == "udp" {
								protocol = "UDP"
							}

							ports = append(ports, portMapping{
								hostPort:      aws.Int64Value(mapping.HostPort),
								containerPort: aws.Int64Value(mapping.ContainerPort),
								protocol:      protocol,
							})
						}
					}
					mach = &machine{
						privateIP:    aws.StringValue(container.NetworkInterfaces[0].PrivateIpv4Address),
						ports:        ports,
						state:        aws.StringValue(task.LastStatus),
						healthStatus: aws.StringValue(task.HealthStatus),
					}
```

When service connect environment is used, I propose one of the following:

- ECS provider default configuration has option to enable serviceconnect (boolean) to tell ECS provider that it should not use the task definition private IPs but query services and route requests accordingly.
- Allow backend to pass additional configuration to provider about how to reach it and skip the above code.

Now I am willing to work on it. I have few questions and no idea who to reach out from Traefik team to ask general consensus about way of dealing it :)

Would you be okay with refactoring existing provider and add service connect capability or there should be a separate provider (e.g: ECS-SC) that handles that case?

PS: until its ready, we are using file provider. Feels like using an old proxy for now. Would be grateful if you can advice of a better solution to be used temporarily as well.

Thank you.

**Comment by jspdown** [comment]
Hello @aleyrizvi :wave: 
The initial proposal was closed due to a lack of interest from the community.
Since you are willing to contribute, let's move back to the original issue https://github.com/traefik/traefik/issues/9662. I'm going to reopen it. 
We can discuss their on how we can proceed for design considerations and implementation. 

I'm closing this one as duplicate.
