### ISSUE TITLE
What happens to datadog tracing with the migration to opentelemetry?

### ISSUE THREAD

**Issue by changhyuni** [traefik/traefik#10401]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

What happens to datadog tracing with the migration to opentelemetry?
Looking at that PR, it looks like the code for datadog tracing has been removed.
https://github.com/traefik/traefik/pull/10223

I'm not sure, but are these keeping to set avaliable?
https://doc.traefik.io/traefik/observability/tracing/datadog/

**Comment by mmatur** [comment]
Hello @changhyuni,

Thanks for reaching out to us.

Traefik v3 uses [OpenTelemetry](https://opentelemetry.io/), an open standard designed for distributed tracing.

The documentation is for Traefik v3 is available [here](https://doc.traefik.io/traefik/v3.0/observability/tracing/overview/).

The link you shared is Traefik v2.10 documentation the latest stable version. Traefik v3 is still in beta for now.

In the following [link](https://docs.datadoghq.com/opentelemetry/), you will find information about Opentelemetry and Datadog. Traefik is using the OTEL Library and not the dd-trace library.

**Comment by gaffneyd4** [comment]
You can setup OTLP ingestion for your DataDog agents by following the documentation [here](https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host). Then just [configure Traefik](https://doc.traefik.io/traefik/v3.0/observability/tracing/opentelemetry/) to export its OTLP data to the endpoint the DataDog agent provides.
