### ISSUE TITLE
Increase the last time to access the http service

### ISSUE THREAD

**Issue by WX-T** [traefik/traefik#10412]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I want to be able to get the date of the user's last request for the service and the date the service was created when calling APIs such as /api/http/services.

I have a requirement to delete a service after it has been created for a period of time if there are no requests to save resources.

**Comment by nmengin** [comment]
Hello @WX-T,

Thank you for the suggestion.
After discussing it with the other maintainers we prefer to close the issue.

Indeed, the information provided using the API cannot bring such data, and we won't be able to make it happen.
