### ISSUE TITLE
Rewrite headers should be a core feature.

### ISSUE THREAD

**Issue by migs35323** [traefik/traefik#10422]
### What did you expect to see?

There is a closed issue that i believe it should still be valid:
#6047
i would commend there but it's "frozen"
Traefik should provide the functionality of rewrite headers, or at least rename them...
and not rely on external plugins to do so.
there is not only 1 plugin but several of them which means there is demand for this functionality....

**Comment by kevinpollet** [comment]
Hello @migs35323, and thanks for opening the issue.

I am closing this issue in favor of https://github.com/traefik/traefik/issues/6047. Feel free to add your use case and give it a thumbs up.
