### ISSUE TITLE
Unable to create custom TCP Middleware because depends on `unsafe` package

### ISSUE THREAD

**Issue by nkennek** [traefik/traefik#10438]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I tried to create my custom TCP middleware as a local plugin, and found the error:

```
ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:224 > Plugins are disabled because an error has occurred. error="failed to craete Yaegi intepreter: failed to import plugin code \"github.com/xxxxx/xxxxxxx/\": 1:21: import \"github.com/xxxxx/xxxxxxx/\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/main.go:10:2: import \"github.com/traefik/traefik/v3/pkg/tcp\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/vendor/github.com/traefik/traefik/v3/pkg/tcp/dialer.go:12:2: import \"github.com/rs/zerolog/log\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/vendor/github.com/rs/zerolog/log/log.go:10:2: import \"github.com/rs/zerolog\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/vendor/github.com/rs/zerolog/console.go:16:2: import \"github.com/mattn/go-colorable\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/vendor/github.com/mattn/go-colorable/colorable_others.go:10:2: import \"github.com/mattn/go-isatty\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/vendor/github.com/mattn/go-isatty/isatty_tcgets.go:8:8: import \"golang.org/x/sys/unix\" error: plugins-local/src/github.com/xxxxx/xxxxxxx/vendor/golang.org/x/sys/unix/affinity_linux.go:11:2: import \"unsafe\" error: unable to find source related to: \"unsafe\""
```

The error says that it depends on some `unsafe` package, which is okay as discussed on this issue (https://github.com/traefik/traefik/issues/7459).
However, this `unsafe` package is required by "github.com/traefik/traefik/v3/pkg/tcp\", where tcp.WriteCloser is defined. Meanwhile the middleware package have to provide tcp.WriteCloser. So, to my understandings it's not possible to define custom TCP middleware on user's end.

Questions:

- is my understanding correct?
- if not, any workarounds?
- if yes, I want to post is as feature request on treafik

Thank you,

**Comment by ldez** [comment]
Hello,

a plugin cannot depend on Traefik itself, because this will result in a circular dependency.

You should use https://github.com/traefik/genconf instead.

**Comment by kevinpollet** [comment]
Hello @nkennek,

Are you trying to create an HTTP plugin or a TCP one?
Because today, Traefik does not support custom TCP middleware through plugins.

**Comment by nkennek** [comment]
I'm trying to create a TCP plugin.
Sorry to hear that but I got it.

Is it by design or are you planning to support it in the future?

**Comment by kevinpollet** [comment]
@nkennek I think this is something we could support, but we never talked about it internally. Feel free to open a feature request with your use case, and maybe an idea of the implementation/plugin contract.

Therefore I am closing this issue.
