### ISSUE TITLE
error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]

### ISSUE THREAD

**Issue by thematchless** [traefik/traefik#10436]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I upgraded my traefik instance to the new `traefik:v3.0.0-rc1` and facing an issue with a router rule which contains two host rules. I already switched from the old syntax to the new one

> traefik.http.routers.site.rule=Host(`site.de`) || Host(`site.dev`)

as described in the [documentation](https://doc.traefik.io/traefik/v3.0/routing/routers/#rule). But if I start my container i get an error which contains the error in the old syntax.

### What did you see instead?

My router rule with the new syntax gets converted to the old format in the error.

### What version of Traefik are you using?

traefik:v3.0.0-rc1

### What is your environment & configuration?

```yaml
labels:
  - "traefik.http.routers.site.rule=Host(`site.de`) || Host(`site.dev`)"
  - "traefik.http.routers.site.tls.certresolver=letsencrypt"
  - "traefik.http.routers.site.entrypoints=websecure"
```

### If applicable, please paste the log output in DEBUG level
```
traefik  | 2024-02-14T22:23:29+01:00 ERR error="error while adding rule Host(`site.de`, `site.dev`): error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]" entryPointName=websecure routerName=site@docker
```

**Comment by ldez** [comment]
Hello,

can you provide you static configuration?

**Comment by thematchless** [comment]
Nevermind 🙈 It looks like I had a problem with my docker stack which resulted in strange behaviour. I figured that stuff out, while I was creating a new test setup and that was working without problems.

I made a clean restart of my docker stack and now everything is working as expected. Thank you for the rubberducking and sorry for wasting your time 🙇🏼‍♂️
