### ISSUE TITLE
v3.0.0 RC1 imposes tracecontext as propagation

### ISSUE THREAD

**Issue by jcchavezs** [traefik/traefik#10446]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

v2 allowed to have several tracer implementation and hence different propagation models. v3 has migrated to OTel as single tracer implementation and imposed tracecontext as the only propagation format which can be a big pain for migration. The reason is that although traefik supports tracecontext, applications have to do their tracing theirselves and forcing them all to migrate towards is not a trivial task (are the tracing libraries they use compatible with tracecontext? are they willing to upgrade or reimplement tracing for this?). I suggest you either allow it being configurable (otel already supports many propagation models [opentelemetry-go-contrib/propagators at main · open-telemetry/opentelemetry-go-contrib · GitHub 2](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/propagators)) or support both tracecontext and b3 as most of the tracers support b3.

**Comment by rtribotte** [comment]
Hello @jcchavezs,

Thanks for opening this!

Indeed, in v3 we reworked the tracing feature completely to support only OpenTelemetry and instrumenting only with OpenTelemetry SDK, with, as the first intention, trace context propagation, as OpenTelemetry follows the W3C Trace Context specification.

> The reason is that although traefik supports tracecontext, applications have to do their tracing theirselves and forcing them all to migrate towards is not a trivial task (are the tracing libraries they use compatible with tracecontext? are they willing to upgrade or reimplement tracing for this?). I suggest you either allow it being configurable (otel already supports many propagation models [opentelemetry-go-contrib/propagators at main · open-telemetry/opentelemetry-go-contrib · GitHub 2](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/propagators)) or support both tracecontext and b3 as most of the tracers support b3.

This makes sense, and we are open to considering integrating other propagation models and are eager to read community feedback on this.
We are marking this issue as a proposal accordingly.

**Comment by jcchavezs** [comment]
Ping @zetaab given that he worked out migration from OT to OTel.

**Comment by rtribotte** [comment]
Hello,

We do think that multiple propagation models should be possible to configure, and we are marking this issue as an enhancement.

For that, we are working on supporting the `OTEL_PROPAGATORS` environment variable: https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_propagators.

**Comment by rtribotte** [comment]
I think this issue is solved by #10465, I'm closing it accordingly.

**Comment by jcchavezs** [comment]
Awesome!
