### ISSUE TITLE
Traefik v2.10 documentation is shown by default instead of the latest version v2.11

### ISSUE THREAD

**Issue by avm99963** [traefik/traefik#10471]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Go to the Traefik documentation: https://doc.traefik.io/traefik/. It should load the docs for the latest version released (v2.11).

### What did you see instead?

By default the logs for v2.10 are shown instead.

I see in the following piece of code that `STRUCTOR_LATEST_TAG` is overriden with the variable `vars.STRUCTOR_LATEST_TAG`. Maybe this variable has to be updated [in the GitHub configuration](https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows)? Right now its value is `v2.10.0` (as per [this workflow run](https://github.com/traefik/traefik/actions/runs/7962152858/job/21734973214#step:7:7)).

https://github.com/traefik/traefik/blob/063f8fae790c4aad4f44e54645d3972679aca6a2/.github/workflows/documentation.yml#L41-L44

### What version of Traefik are you using?

N/A

### What is your environment & configuration?

N/A

**Comment by ldez** [comment]
Hello,

thank you for the report, the documentation is now up-to-date.
