### ISSUE TITLE
Error from server (BadRequest): error when creating "ipallowlist.yml": Middleware in version "v1alpha1" cannot be handled as a Middleware: strict decoding error: unknown field "spec.ipAllowList"

### ISSUE THREAD

**Issue by ruidanwang** [traefik/traefik#10481]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Error from server (BadRequest): error when creating "ipallowlist.yml": Middleware in version "v1alpha1" cannot be handled as a Middleware: strict decoding error: unknown field "spec.ipAllowList"

### What did you see instead?

Error from server (BadRequest): error when creating "ipallowlist.yml": Middleware in version "v1alpha1" cannot be handled as a Middleware: strict decoding error: unknown field "spec.ipAllowList"

### What version of Traefik are you using?

v2.11.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-ipallowlist
spec:
  ipAllowList:
    sourceRange:
      - 192.168.220.167
Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @ruidanwang,

Are the CRDs up to date in the cluster?

You can ensure this by running:
```shell
kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.11/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
```

**Comment by ruidanwang** [comment]
Thank you, my issue has been resolved. @rtribotte
