### ISSUE TITLE
Plugin file or directory could not be found in Pod

### ISSUE THREAD

**Issue by duj4** [traefik/traefik#10493]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I created a deployment with the plugin files mounted from configmap (same directory as the binary file locate, /usr/local/bin) so that the plugin could be loaded.

### What did you see instead?

Plugin failed to be loaded owning to the .traefik.yml cannot be found.

### What version of Traefik are you using?

```
/ # traefik version
Version:      2.11.0
Codename:     cheddar
Go version:   go1.22.0
Built:        2024-02-12T15:26:45Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

static.yml:
```
experimental:
  localPlugins:
    tlsauth:
      moduleName: tlsauth
```
In the container, the file and directory do exist:

```
/usr/local/bin/plugins-local/src/tlsauth # pwd
/usr/local/bin/plugins-local/src/tlsauth
/usr/local/bin/plugins-local/src/tlsauth # ls -al
total 12
drwxr-xr-x    2 root     root            55 Mar  3 14:13 .
drwxr-xr-x    3 root     root            21 Mar  3 14:13 ..
-rw-r--r--    1 root     root          1020 Mar  3 14:13 .traefik.yml
-rw-r--r--    1 root     root            44 Mar  3 14:13 go.mod
-rw-r--r--    1 root     root          2668 Mar  3 14:13 main.go
```

### If applicable, please paste the log output in DEBUG level

> time="2024-03-03T14:13:13Z" level=error msg="Plugins are disabled because an error has occurred." error="1 error occurred:\n\t* failed to open the plugin manifest plugins-local/src/tlsauth/.traefik.yml: open plugins-local/src/tlsauth/.traefik.yml: no such file or directory\n\n"

**Comment by nmengin** [comment]
Hello @duj4,

Thanks for reaching out!
To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). 

It is pretty active, so you might find that your question has already been answered there. 
If not, you can ask and get help from other community members pretty quickly.

**Comment by duj4** [comment]
hi @nmengin ,

I posted this question in community as well, but so far there is no reply: https://community.traefik.io/t/failed-to-load-plugins-in-pod/21695.

Thanks.
