### ISSUE TITLE
Add shellrent as dnschallenge provider

### ISSUE THREAD

**Issue by urgali** [traefik/traefik#10490]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

[As reported by let's encrypt, the provider is fully supported](https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438)

[Here is the official let's encrypt api documentation](https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#dns_shellrent)

**Comment by ldez** [comment]
Hello,

Traefik uses [lego](https://github.com/go-acme/lego/) to handle ACME challenges.

Could you open an issue [here](https://github.com/go-acme/lego/issues/new/choose)?

**Comment by urgali** [comment]
I see, thanks for all the info, totally my bad there.

I'll open an issue on lego, you can close this one.

Thank you
