### ISSUE TITLE
Replacement for lost multiple host definition

### ISSUE THREAD

**Issue by troykelly** [traefik/traefik#10556]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

With the restoration of [single hosts in rules](https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/?ref=containous.ghost.io#new-v3-syntax-notable-changes) - we've lost the ability to have a single environment variable define a list of hostnames.

What would the replacement best practice be to have a template compose file with the ability to define one or more hosts? I can't think of a way to replicate the below.

## Feature request

`Hosts()` that can take a comma separated list of domains for a router.

### Old

```text
DOMAIN_LIST="`one.example.invalid`,`two.example.invalid`,`three.example.invalid`"
```

```yaml
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${SITE}-im-https.rule=((Host(${DOMAIN_LIST}) && PathPrefix(`/websocket`))
        - traefik.http.routers.${SITE}-im-https.entrypoints=http3
        - traefik.http.routers.${SITE}-im-https.service=${SITE}
        - traefik.http.routers.${SITE}-im-https.tls.certresolver=${SITE_RESOLVER}
        - traefik.http.routers.${SITE}-im-https.middlewares=gzip,limit,reporturi,block-apple,upgradeinsecure
        - traefik.http.services.${SITE}-im.loadbalancer.server.port=8888
```

### Unsolvable

```text
DOMAIN_LIST="one.example.com,two.example.com,three.example.com"
```

```yaml
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=traefik-public
        # Split the domain list somehow??
        - traefik.http.routers.${SITE}-im-https.rule=((Host(`${DOMAIN_LIST[...]}`) && PathPrefix(`/websocket`))
        - traefik.http.routers.${SITE}-im-https.entrypoints=http3
        - traefik.http.routers.${SITE}-im-https.service=${SITE}
        - traefik.http.routers.${SITE}-im-https.tls.certresolver=${SITE_RESOLVER}
        - traefik.http.routers.${SITE}-im-https.middlewares=gzip,limit,reporturi,block-apple,upgradeinsecure
        - traefik.http.services.${SITE}-im.loadbalancer.server.port=8888
```

**Comment by jspdown** [comment]
Thanks for reaching out! 

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.

**Comment by troykelly** [comment]
Thank you @jspdown I will leave it to somebody else then. I felt it's a fairly critical feature change/reversion so needed to be tracked as a bug, but understand if you disagree. At least this ticket will be here so people know there's no resolution to the issue.
