### ISSUE TITLE
Request Entity Too Large - 413

### ISSUE THREAD

**Issue by karadikidd** [traefik/traefik#10568]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Doing an HTTP call to an endpoint behind an ingress. The ingress has a middleware annotation which uses `addPrefix` behind the scenes. When calling with a large request body, I'm getting an HTTP 413 response.

### What did you see instead?

I was expecting to get a 200 response, just as it happens for requests with a smaller request body.

### What version of Traefik are you using?

name: traefik
description: A Traefik based Kubernetes ingress controller
appVersion: 2.8.0

### What is your environment & configuration?

```yaml
ingress-traefik:
    Image:       traefik:2.8.0
    Ports:       9100/TCP, 9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entrypoints.metrics.address=:9100/tcp
      --entrypoints.traefik.address=:9000/tcp
      --entrypoints.web.address=:8000/tcp
      --entrypoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --metrics.prometheus=true
      --metrics.prometheus.entrypoint=metrics
      --providers.kubernetescrd
      --providers.kubernetesingress
      --log.format=json
      --log.level=DEBUG
      --accesslog=true
      --accesslog.format=json
      --providers.kubernetesingress.ingressendpoint.publishedservice=ingress-traefik/ingress-traefik
      --providers.kubernetesingress.ingressclass=traefik-internal
```

### If applicable, please paste the log output in DEBUG level

I'm using DEBUG log level but the logs are not really helping to pinpoint the problem.
This is what I was able to gather from the logs:
```
{"ClientAddr":"1.2.3.4:9672","ClientHost":"1.2.3.4","ClientPort":"9672","ClientUsername":"-","DownstreamContentSize":24,"DownstreamStatus":413,"Duration":70256471,"OriginContentSize":24,"OriginDuration":70171001,"OriginStatus":413,"Overhead":85470,"RequestAddr":"proxy.foo.bar.io","RequestContentSize":48247,"RequestCount":500,"RequestHost":"proxy.foo.bar.io","RequestMethod":"POST","RequestPath":"/some/request/path","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"foo-bar@kubernetes","ServiceAddr":"1.1.1.1:61003","ServiceName":"foo-bar@kubernetes","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"1.1.1.1:61003","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2024-04-03T19:38:44.765283803Z","StartUTC":"2024-04-03T19:38:44.765283803Z","entryPointName":"websecure","level":"info","msg":"","time":"2024-04-03T19:38:44Z"}
```

**Comment by rtribotte** [comment]
Hello @karadikidd,

Thanks for your interest in Traefik!

In the access log you have shared, the `DownstreamStatus` is 413 which indicates that the error is produced by the downstream service and not in Traefik.

The GitHub issue tracker is dedicated to bug and feature requests.
For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
