### ISSUE TITLE
Kubernetes - Enrich prometheus labels

### ISSUE THREAD

**Issue by Lp-Francois** [traefik/traefik#10578]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello!

Currently we use traefik as IngressController in a Kubernetes cluster, and exposes some prometheus labels like the following:

`traefik_router_request_duration_seconds_bucket{code="304",method="GET",protocol="http",router="production-my-api-fcdde958c61d6c22e708@kubernetescrd",service="production-my-api-fcdde958c61d6c22e708@kubernetescrd",le="2.5"} 4`

I would find it useful to be able to get some info like the `IngressRoute` name as a label, the `namespace` of the IngressRoute/Service and the k8s `Service` name. That would allow to integrate more easily the metrics in a grafana dashboard where applications might use namespace & service/deployment names to filter the dashboard.

Also, I don't find `service` label very useful in our case, we wouldn't mind dropping it. Of course dropping label can be done at the collector level as well.

@mmatur suggested I open an issue after a small discussion about it.

**Comment by mmatur** [comment]
Hey @Lp-Francois 

Thanks for your suggestion.

We are interested in this issue, we are waiting for the traction it will receive. We are going to leave the status as kind/proposal to give the community time to let us know if they would like this idea.

We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know, and we will work with you to make sure you have all the information needed.

Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.

**Comment by jacksgt** [comment]
Hi,
I'm also very much in favor of this proposal. It should be easy to identify the `Ingress` / `Route` and `Namespace` from the labels on the metrics.
In fact, a similar issue has been raised here recently: https://github.com/traefik/traefik/issues/10105

**Comment by Lp-Francois** [comment]
Amazing! Thanks @jacksgt

**Comment by dpkirchner** [comment]
In the mean time, could anyone here interested in this labeling issue explain where the service label actually comes from?

In `production-my-api-fcdde958c61d6c22e708@kubernetescrd` it looks like the label is a concatenation of `namespace`, `k8s-service-name`, `random string`, and `@kubernetescrd`. What is the source of the random string?

I've looked at all the resources I can think of (`ingress`, `ingressroute`, `service` (not currently using `traefikservice`), `endpoints`) and haven't found the values anywhere. Is it generated internally by Traefik?

**Comment by nmengin** [comment]
Hello @Lp-Francois ,
This proposal has almost no traction.

We won't add it to the Roadmap yet and we prefer to close it.
We'll re-open it later if necessary.

**Comment by bcrisp4** [comment]
I for one would be interested in this.
