### ISSUE TITLE
Container v3.0.0-rc4 breaks TLS forwarding

### ISSUE THREAD

**Issue by troykelly** [traefik/traefik#10594]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We've been using [v3.0.0-rc3](https://hub.docker.com/layers/library/traefik/v3.0.0-rc3/images/sha256-8b5a00052b4a25122b79e261d58f2bbf87937a0b11cbe62e9dc73394bbd3ed88?context=explore) since it was published, and today updated to [v3.0.0-rc4](https://hub.docker.com/layers/library/traefik/v3.0.0-rc4/images/sha256-7f1ff4d99604a7ccfb597a2e108011be6d0fc0096f44625aafc8354bf292866f?context=explore)

### What did you see instead?

After the containers restarted we got very high failure rates for everything that was TLS forwarded (postgres and redis) in our case, across multiple servers.

Web traffic was all throwing `499` - but I don't know if that's Traefik's fault directly, I suggest it's more because the apps couldn't get to redis and postgres.

Connecting to redis over tls with something like redis-cli failed completely, using a tool like "Medis" from a mac, would connect for about a half second, then loose the connection.

Rolling back to rc3 has resolved the issue.

### What version of Traefik are you using?

v3.0.0-rc4

### What is your environment & configuration?

Swarm and Docker standalone configured

**Comment by rtribotte** [comment]
Hello @troykelly,

Thanks for your interest in Traefik!

The newly introduced `lingeringTimeout` value has a very narrowed value by default: https://doc.traefik.io/traefik/migration/v2/#transportrespondingtimeoutstcplingeringtimeout

In the case of "server first" protocol handling, increasing the value must solve the issue you are facing.

**Comment by troykelly** [comment]
Thank you @rtribotte - has it not been implemented until RC 4?
If it was implemented in 2.3, wouldn't I have seen this issue a lot earlier?

**Comment by 0xCCD** [comment]
I would also like to know if there was a change between rc3 and rc4 which is related to this setting: lingeringTimeout

**Comment by troykelly** [comment]
My personal feelings aside, what do other similar proxys do? What's best practice?

It seems like this is a helpful feature, perhaps implemented in a way that's doing more damage than good.

- What was the "default" before the change?
- Is it unsafe to set this as zero?
- Perhaps we should add more to the documentation - ie for http, best practice is _n_ seconds, for redis _x_ seconds, postgres _y_ and so on.

**Comment by emilevauge** [comment]
On behalf of the maintainer team, sorry for the inconvenience.
We opened a global issue to cover this bug: https://github.com/traefik/traefik/issues/10598
I'm closing this one, as we will update the global issue while we make progress on this.
