### ISSUE TITLE
v2.11.1 Synology Surveillance Station loses the connection to each camera about every 2 seconds

### ISSUE THREAD

**Issue by Shadow27374** [traefik/traefik#10597]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Update from 2.11.0 to 2.11.1

### What did you see instead?

Synology Surveillance Station loses the connection to each camera about every 2 seconds since version 2.11.1 and then reestablishes it immediately. So basically I only have a slideshow.

If I set the Docker container to version 2.11.0, everything works again.

If I can help with any logs, please feel free.

### What version of Traefik are you using?

2.11.1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by viceice** [comment]
Duplicate of #10595

**Comment by Shadow27374** [comment]
The problem is probably already known and has

transport.respondingTimeouts.tcp.lingeringTimeout

to do.

**Comment by emilevauge** [comment]
On behalf of the maintainer team, sorry for the inconvenience.
We opened a global issue to cover this bug: https://github.com/traefik/traefik/issues/10598
I'm closing this one, as we will update the global issue while we make progress on this.
