### ISSUE TITLE
Add option to enable proxy protocol for HTTP services

### ISSUE THREAD

**Issue by jbaron-gingco** [traefik/traefik#10608]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I have a rabbitmq installed behind a traefik 3.0 with two HTTP services (Management and MQTT over websocket, traefik does TLS termination) and one TCP service (MQTT over TCP). For TCP using the proxy protocol works just fine to get the real client IP in rabbitmq. But for the two HTTP endpoints I cannot get the real IP for some reason - X-Forwarded headers are appearently ignored.

Would it be possible to add an option to enable TCP proxy protocol for HTTP services as well?

**Comment by nmengin** [comment]
Hello @jbaron-gingco,

Thank you for reaching out.
Could you be more accurate on your need and, ideally, provide a configuration example, please?

Note that a PR is already open to fix a bug with the headers management (#10492), fo you think it fits your needs?

**Comment by jbaron-gingco** [comment]
Hi @nmengin,

for TCP services there is the configuration option to enable TCP proxy protocol:

     "traefik.tcp.services.<servicename>.loadbalancer.proxyprotocol.version=2"

But for HTTP services, no such option seems to exist, but instead the HTTP `X-Forwarded-*` headers are used. Would it be possible to add an option to enable the TCP proxy protocol for HTTP services as well?

Some services do not seem to support the headers (possibly because of the security risks involved), but do support the TCP proxy protocol. This is the case with rabbitMQ for us.

**Comment by juliens** [comment]
Hi @jbaron-gingco ,

In HTTP Services setups, connections with the backend are reused for different clients, making it impossible to forward client-specific connection information like ProxyProtocol does.

So we can't enable ProxyProtocol on HTTP Services.
