### ISSUE TITLE
Switch to Kubernetes EndpointSlices API

### ISSUE THREAD

**Issue by jnoordsij** [traefik/traefik#10638]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In my search of figuring out how exactly Service/Pod traffic is distributed, I noticed that Traefik internally uses the Kubernetes [Endpoints API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#endpoints-v1-core). As of Kubernetes 1.21, the [EndpointSlices API](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/) is a stable alternative described as:
> Kubernetes' EndpointSlice API provides a way to track network endpoints within a Kubernetes cluster. EndpointSlices offer a more scalable and extensible alternative to [Endpoints](https://kubernetes.io/docs/concepts/services-networking/service/#endpoints).

Both from a performance and future-proof point of view, it might therefore be benificial to switch towards using this API.

A possible source of inspiration may be https://github.com/kubernetes/ingress-nginx/pull/8890, which implemented this for (Kubernetes) NGINX.

**Comment by jnoordsij** [comment]
A WIP attempt can be found at https://github.com/jnoordsij/traefik/tree/migrate-to-endpointslices. This is far from finished, not passing tests yet, but seems to be heading in the right direction. Also this should probably rebased to `master`.

**Comment by kevinpollet** [comment]
Hello @jnoordsij,

Thanks for opening the issue, 

When you have something ready feel free to open a pull request.
As this is an enhancement, the pull request has to be opened on the master branch.

**Comment by jnoordsij** [comment]
This issue has been solved with #10664.
