### ISSUE TITLE
grpc bi directional streaming - READTIMEOUT

### ISSUE THREAD

**Issue by dtscd** [traefik/traefik#10652]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have for some time proxied http2 gRPC connections over Traefik with an h2c backend. This has worked well.

I recently noticed, possibly after a Traefik update, that after exactly 60 seconds my bi-directional gRPC connection would be closed, and I would be required to dial again. I send status updates (read and write) every 30 seconds.

I discovered the fix for this was to set `TRAEFIK_ENTRYPOINTS_<NAME>_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT = 0` (zero).

In my mind, I was imagining this read timeout to apply to each "Read" operation. However looking at the implementation that I believe applies in `pkg/server/server_entrypoint_tcp.go` around line 256 (master 1ffbffb26a3676b368c4fc52c4fb737de56cd65d ) it looks like the read deadline is only set once when the connection is established.

Now having understood the semantics (I think) of the ReadTimeout the solution is obvious, turn it off. However, I serve this on a backend that multiplexes the URL to different services; it isn't ideal to set this on all endpoints, but perhaps required at this point. I would suggest one of a few remediations (I could do them, or look into them in more detail if desired):
 1. Document in the gRPC section of the documentation this behavior and what that means for bi-directional streaming, and where to turn it off at.
 2. Allow setting the read timeout at a service level.
 3. Allow setting a transport level read timeout such that each read resets the timeout so long as the connection is written and read from continuously, it won't timeout at the connection level.

### 

### What did you see instead?

After exactly 60 seconds after initiating a gRPC bi directional streaming connection, despite reading and writing every 30 seconds, I would get:
`rpc error: code = Internal desc = server closed the stream without sending trailers`
To which I would close and re-open the connection.

### What version of Traefik are you using?

v2.11.2

### What is your environment & configuration?

`TRAEFIK_ENTRYPOINTS_<NAME>_TRANSPORT_RESPONDINGTIMEOUTS_READTIMEOUT`
was initially unset.
I adjusted this parameter higher and that changed the timeout exactly. Turning it to zero made the error go away.

**Comment by juliens** [comment]
Hello,

Since v2.11.2, for security reason (DDOS attack), a default value is configured for the readTimeout (https://doc.traefik.io/traefik/routing/entrypoints/#respondingtimeouts).
As what you want a "persistant" connection, you could define an higher value (or 0 for no timeout).
I encourage you to think what is the best value for your use case.
