### ISSUE TITLE
Traefik v3 silently dropped support for multiple arguments in "Host" rule

### ISSUE THREAD

**Issue by hexxone** [traefik/traefik#10697]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Updated from Traefik v2 to v3.

Suddenly I started getting errors on multiple Traefik Routers "Host" rules.

Even though, the [Migration Guide](https://doc.traefik.io/traefik/master/migration/v2-to-v3/) has no mentions of any changes to the "Host" rule, it seems to have been changed.

The docs have never stated explicitly, that more than 1 argument can be provided, but it definetely has been working in v2.10.7

E.g.: 
![image](https://github.com/traefik/traefik/assets/5312542/780d6d16-1380-4cc4-97b2-5c2692fbc9da)

### What did you see instead?

```
error while adding rule Host(`osm.server.net`, `www.osm.server.net`): error while adding rule Host: unexpected number of parameters; got 2, expected one of [1]
```
I assume, from now on we are supposed to chain multiple "Host" rules with "||" or operator like so: ?

```
Host(`sub.domain1.com`) || Host(`sub.domain2.com`)
```

If this is intended behaviour from now on, it would be nice to see some mention in the migration guide/docs of this change.

Thanks!

### What version of Traefik are you using?

3.0.0

### What is your environment & configuration?

Normal docker compose setup.

**Comment by saltydk** [comment]
https://doc.traefik.io/traefik/migration/v2-to-v3/#dynamic-configuration It is covered there.

> All matchers now take a single value (except Header, HeaderRegexp, Query, and QueryRegexp which take two) and should be explicitly combined using logical operators to mimic previous behavior.

**Comment by juliens** [comment]
Thanks for reaching out!

As @saltydk mention, you can find the information in the migration guide.

**Comment by hexxone** [comment]
> https://doc.traefik.io/traefik/migration/v2-to-v3/#dynamic-configuration It is covered there.
> 
> > All matchers now take a single value (except Header, HeaderRegexp, Query, and QueryRegexp which take two) and should be explicitly combined using logical operators to mimic previous behavior.

Oh, I didnt see it. I'm sorry 🙏  and thanks for the quick reply
