### ISSUE TITLE
Add access log filter for `entrypoint` and `router`

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#10699]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great to be able to filter access logs by `entrypoint` and `router`. Filter for `statusCodes` already exists ([doc](https://doc.traefik.io/traefik/observability/access-logs/#filtering)). 

That way the (JSON) access logs could be reduced, for example by not logging all the prometheus `metrics` requests. 

The configuration should support negation, something like `filter: entryPointNames: !metrics`.

**Comment by ldez** [comment]
Duplicate of #8758

**Comment by bluepuma77** [comment]
Thanks, according to this [merged pull request](https://github.com/traefik/traefik/pull/9633) the logs are removed for internal services in v3.
