### ISSUE TITLE
Official standalone Grafana dashboards need to be updated as of Traefik v3.0

### ISSUE THREAD

**Issue by vsimon** [traefik/traefik#10691]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Import a dashboard in Grafana via ID: 17346
Source: https://grafana.com/grafana/dashboards/17346-traefik-official-standalone-dashboard

Import a dashboard in Grafana via ID: 17347
https://grafana.com/grafana/dashboards/17347-traefik-official-kubernetes-dashboard

### What did you see instead?

The `entrypoint` dropdown labels and `service` dropdown labels do not auto-populate. 

The "Connections per ..." panels do not populate.

### What version of Traefik are you using?

v3.0.0

### What is your environment & configuration?

```yaml
Grafana 10.4.1
```

Add more configuration information here.

**Comment by keriati** [comment]
So I managed to get some results by changing the variables from:

```
entrypoint:  label_values(traefik_entrypoint_open_connections, entrypoint)	
service:  label_values(traefik_service_open_connections, service)
```

to

```
entrypoint:  label_values(traefik_entrypoint_requests_total,entrypoint)	
service:  label_values(traefik_service_requests_total,service)
```

**Comment by keriati** [comment]
Note, this was fixed long ago here: https://github.com/traefik/traefik/pull/10591 but never merged / published.

Just copy the json file from the PR: https://github.com/traefik/traefik/blob/1f292c1ae367061ea62d30da116d83616f74d834/contrib/grafana/traefik.json

**Comment by mmatur** [comment]
It has been published few days ago

Closed by: https://github.com/traefik/traefik/pull/10591#issuecomment-2147580749
