### ISSUE TITLE
Limit connections by a single IP address.

### ISSUE THREAD

**Issue by devinfra1** [traefik/traefik#10753]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Good afternoon, 

I will use Traefik as a proxy for an Apache 2 web server, with Docker Swarm. 

Previously I had my security controls in the 'mod_qos' apache module, with settings like "QS_SrvMaxConnPerIP". 

How do I limit the number of connections via a certain IP on traefik? 

I've already tried settings like RateLimit and InFlightReq, but their settings are global and not for a specific IP.

**Comment by devinfra1** [comment]
I don't have permissions to ask questions like this on the community forum, so I'm asking them here. 

We are experiencing high demand and delayed due to this situation above.

**Comment by ldez** [comment]
Hello,

what do you mean by "I don't have permissions to ask questions"?

Do you have a problem access to the forum?

**Comment by devinfra1** [comment]
I received the following message from the Traefik team at this exact moment. I was then able to ask the question to the community.

![image](https://github.com/traefik/traefik/assets/129983464/2eb97ba1-0c55-464f-a02b-ccf6e36994ce)

**Comment by ldez** [comment]
can we close this issue?

**Comment by devinfra1** [comment]
Yes, can you help me with this question on the forum?
