### ISSUE TITLE
Basic Auth Automatically encode Base64 - basicauth.users

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [traefik/traefik#10760]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

```
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH}"
```

I would expect to easily set the auth without the need to encode the password. Would be nice to have a possibility to pass the password directly.

**Comment by NilsBaumgartner1994** [comment]
I think because of secrurity reasons one have to provide the hashed password right?

**Comment by emilevauge** [comment]
Hello @NilsBaumgartner1994, the whole point of hashing passwords is to avoid having them in plain text. This is indeed a basic security measure :)
