### ISSUE TITLE
A Router rule that exactly match all same-name header values.

### ISSUE THREAD

**Issue by rpstw** [traefik/traefik#10773]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

HTTP allows multiple same-name headers in a request, which is why in golang `net/http.Header` has the underlying type `map[string][]string` instead of `map[string]string`.

In one of our internal use case, we want to route traffic according to values by a specific  header. To be more easily understood, we want a request with header `X-Some-Header: a` and another one with `X-Some-Header: a, b` routed to different services. 

Initially we tried to use a Traefik router rule `Header("X-Some-Header", "a")` to match traffic with  `X-Some-Header: a`, but soon we realized that both requests mentioned above are treated the same, which is not what we want.

`HeadersRegex` is capable of implementing what we want, but after translating a exact match of `X-Some-Header: aaa, bbb` we got(maybe not most people expect and like):
```
( Headers(`X-Some-Header`, `aaa`) && Headers(`X-Some-Header`, `bbb`) && !HeadersRegexp(`X-Some-Header`, `^([^ab]*|a|a[^a].*|aa|aa[^a].*|aaa.+|b|b[^b].*|bb|bb[^b].*|bbb.+)$`) )
```

So ultimately the question is:  maybe a new router rule that do a all match instead of a any match is useful?

`Query` also do an any match, but in my experience, most people don't use  multi value query. I'll just  leave it for maybe another issue.

I've checked the latest version for this.

**Comment by rtribotte** [comment]
Hello @rpstw,

Thanks for opening this!

We understand the proposal is for a strict values `Header` rule matcher.
We are wondering why the rule priority would not help in that case, can you please elaborate?

**Comment by rtribotte** [comment]
Hello @rpstw,

I think it makes sense. 
Thanks for explaining the rationale behind this feature request 👍 
For now, it is marked as a suggestion to assess traction and community response.

**Comment by nmengin** [comment]
Hello @rpstw,

This proposal was opened more than 6 months ago with almost no traction.
We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.
