### ISSUE TITLE
TCP Router with TLS passthrough on github.com breaks

### ISSUE THREAD

**Issue by Sharker5854** [traefik/traefik#10842]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We've configured Traefik in reverse-proxy mode to provide access for external resources from our organization's closed internal network.

**Our TCP routers:**
    
```
github-com:
  tls:
    passthrough: true
  rule: HostSNI(`github.com`)
  service: github-com-svc
  
api-openai-com:
  tls:
    passthrough: true
  rule: HostSNI(`api.openai.com`)
  service: api-openai-com-svc
...
```

**Our services:**
```
github-com-svc:
  loadBalancer:
    servers:
    - address: github.com:443

api-openai-com-svc:
  loadBalancer:
    servers:
    - address: api.openai.com:443
...
```

And this settings looks to work fine for almost all domains, except **github.com** (and it's subdomains)

### What did you see instead?

When trying to access **github.com** we periodically (not always!) get following error:

_Fastly error: unknown domain: github.com. Please check that this domain has been added to a service.
Details: cache-bma1663-BMA_

It is worth saying that GitHub breaks more often while switching between different pages on it's domain, not when opening for the first time.

We rejected the version that Fastly service has some internal problems, since everything works perfectly without using our proxy.
Also tried a script for regular manual updating raw IP (by pulling it from DNS) instead of domain name in **github-com-svc**. It didn't help.

There is an assumption that smth going wrong with headers or cookies, but simultaneously I understand that Traefik doesn't even have a technical ability to interfere this process in TCP mode. Not sure...

Appreciate any help!

### What version of Traefik are you using?

Version:      3.0.1
Codename:     beaufort
Go version:   go1.22.3
Built:        2024-05-22T13:12:16Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

**docker-compose.yaml**

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic.yaml:/dynamic.yaml
    command:
      - --providers.docker=false
      - --providers.file.filename=/dynamic.yaml
      - --serversTransport.maxIdleConnsPerHost=0
      - --serversTransport.insecureSkipVerify=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG
      - --api.insecure=true

### If applicable, please paste the log output in DEBUG level

**DBG** github.com/traefik/traefik/v3/pkg/tcp/proxy.go:41 > Handling TCP connection address=185.199.110.153:443 remoteAddr=192.168.76.103:14481
**DBG** github.com/traefik/traefik/v3/pkg/tcp/proxy.go:113 > Error while setting TCP connection deadline error="set tcp 172.30.0.2:443: use of closed network connection"
**DBG** github.com/traefik/traefik/v3/pkg/tcp/proxy.go:104 > Error while terminating TCP connection error="close tcp 172.30.0.2:41722->140.82.112.21:443: use of closed network connection"
**DBG** github.com/traefik/traefik/v3/pkg/tcp/proxy.go:104 > Error while terminating TCP connection error="close tcp 172.30.0.2:37942->140.82.121.3:443: use of closed network connection"
**DBG** github.com/traefik/traefik/v3/pkg/tcp/proxy.go:113 > Error while setting TCP connection deadline error="set tcp 172.30.0.2:35776: use of closed network connection"

**Comment by nmengin** [comment]
Hey @Sharker5854,

Thanks for reaching out!

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
