### ISSUE TITLE
flutter grpc clinent request error 500

### ISSUE THREAD

**Issue by an15221315127** [traefik/traefik#10877]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I I want to request the GRPC service through the Flutter client. I used Treafik as a gateway to forward to the GRPC service in the consult catalog, but Treafik reported an error of 500. I'm not sure if it doesn't support GRPC requests

### What did you see instead?

I want to request the GRPC service through the Flutter client. I used Treafik as a gateway to forward to the GRPC service in the consult catalog, but Treafik reported an error of 500. I'm not sure if it doesn't support GRPC requests

### What version of Traefik are you using?

500

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```
default
Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

I want to request the GRPC service through the Flutter client. I used Treafik as a gateway to forward to the GRPC service in the consult catalog, but Treafik reported an error of 500. I'm not sure if it doesn't support GRPC requests

**Comment by kevinpollet** [comment]
Hey @an15221315127,

Thanks for reaching out!

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there. If not, you can ask and get help from other community members pretty quickly.
