### ISSUE TITLE
using more than one env_file will loose the content of the second on

### ISSUE THREAD

**Issue by bastiane273** [traefik/traefik#10874]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

.env:
PAPERLESS_HOSTNAME=paperless
global.env
GLOBAL_DOMAIN=xy.com
docker-compose.yml
  service webserver
    env_file:
      - .env
      - global.env
    labels:
      traefik.http.routers.paperless.rule: "Host(`${PAPERLESS_HOSTNAME}.${GLOBAL_DOMAIN}`)"

docker compose config should result in:
  traefik.http.routers.paperless.rule: "Host(`paperless.xy.com`)"
Ist this an error of docker compose or an error of traefik?

### What did you see instead?

docker compose config will result in:
  traefik.http.routers.paperless.rule: "Host(`paperless.`)"
Ist this an error of docker compose or an error of traefik?

### What version of Traefik are you using?

2.11, 3.0.3, 3.0.4 same result

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by mmatur** [comment]
Hello @bastiane273,

Thanks for your report.

Traefik does not read these env files. It seems related to your usage of docker compose.

Closing this issues accordingly.

Feel free to reopen if needed
