### ISSUE TITLE
Error logs when kubernetes endpoints are scaled down to 0

### ISSUE THREAD

**Issue by MohanSha** [traefik/traefik#10896]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Scaled down the k8 service to 0

Found closelt related issue refer https://github.com/traefik/traefik/pull/6931 

### What did you see instead?

Error logs when kubernetes endpoints are scaled down to 0
<img width="1104" alt="Screenshot 2024-07-11 at 4 05 08 PM" src="https://github.com/traefik/traefik/assets/13899668/8eee923d-fe83-48b0-ba9e-d3bc4feef611">

### What version of Traefik are you using?

traefik:v2.11.0

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ivankatliarchuk** [comment]
So the Traefik does not know that the number of replicas in deployment is 0. Probably question to maintainers 
> Any plans to make Traefik aware of the desired number of replicas? Ideally, Traefik should be aware of the minimal desired number of replicas and potentially adjust its behavior accordingly.

**Comment by kevinpollet** [comment]
Hello @MohanSha and thanks for opening this issue,

Today when using the `AllowEmptyServices` [option](https://doc.traefik.io/traefik/providers/kubernetes-crd/#allowemptyservices) no error is logged but a request to the service returns a `503 Service Unavailable`. Is this what you were looking for?

@ivankatliarchuk your request sounds a bit different, could you open another issue?

**Comment by ivankatliarchuk** [comment]
Actually, my case is exactly the same. The Traefik version is `2.11`. Do you mean Traefik 3+ has slightly different behavior?

**Comment by kevinpollet** [comment]
Hello @MohanSha,

Is my previous answer what you were looking for, can I close this issue?

**Comment by MohanSha** [comment]
The issue reported was resolved as a internal misconfigure issue, I will close this. @kevinpollet
