### ISSUE TITLE
Security vulnerability on Alpine Linux 

### ISSUE THREAD

**Issue by aldanr** [traefik/traefik#10909]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Our Scanner detected a few security vulnerabilities

### What did you see instead?

Hi everyone

Are there any plans to address these CVE's? our scanner detected a few vulnerabilities that have been addressed in the latest Alpine Linux version for OpenSSL and busybox

[https://github.com/advisories/GHSA-85xr-ghj6-6m46,http://cve.mitre.org/cgi-bin/cvename.cgi?name=https://github.com/advisories/GHSA-85xr-ghj6-6m46]
[https://github.com/advisories/GHSA-2vjj-r39q-gvxr,http://cve.mitre.org/cgi-bin/cvename.cgi?name=https://github.com/advisories/GHSA-2vjj-r39q-gvxr]
[https://github.com/advisories/GHSA-wm78-9prw-c5h4,http://cve.mitre.org/cgi-bin/cvename.cgi?name=https://github.com/advisories/GHSA-wm78-9prw-c5h4]
[https://github.com/advisories/GHSA-qqqj-6rp2-5pw4,http://cve.mitre.org/cgi-bin/cvename.cgi?name=https://github.com/advisories/GHSA-qqqj-6rp2-5pw4]
[https://github.com/advisories/GHSA-j44g-3846-7q49,http://cve.mitre.org/cgi-bin/cvename.cgi?name=https://github.com/advisories/GHSA-j44g-3846-7q49]

Best regards

### What version of Traefik are you using?

3.18

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @aldanr,

Thanks for your interest in Traefik!

However, it seems unclear which version of Traefik you are using.
Which version are you using?
Alpine 3.20 is the current version for the Traefik docker image (https://github.com/traefik/traefik-library-image/pull/63).

**Comment by aldanr** [comment]
Hi @rtribotte sorry for the miss in the information, we are currently in version 2.11.2, do you have any plans to release a new 2.x image version with the latest Alpine version to fix the vulnerabilities that listed above?

Thanks!

**Comment by kevinpollet** [comment]
Hello @aldanr the latest 2.x image is the [2.11.6](https://github.com/traefik/traefik/releases/tag/v2.11.6) which uses Alpine 3.20.

Does this new image fixes the issue?

**Comment by ankitchhatbar** [comment]
> Hello @aldanr the latest 2.x image is the [2.11.6](https://github.com/traefik/traefik/releases/tag/v2.11.6) which uses Alpine 3.20.
> 
> Does this new image fixes the issue?

The image that uses Alpine 3.20 seems to have the vulnerability issue. Please see the screenshot below from docker hub.
It seems like using the version of alpine that has the fix, `3.3.1-r1`, should fix it.
![image](https://github.com/user-attachments/assets/176d8668-6d42-4189-988c-d0e5b0d60308)

**Comment by kevinpollet** [comment]
Hello,

> The image that uses Alpine 3.20 seems to have the vulnerability issue. Please see the screenshot below from docker hub.
It seems like using the version of openssl that has the fix, 3.3.1-r1, should fix it.

This CVE affects the OpenSSL library, which must be updated in a patch version of the Alpine project. As explained in https://github.com/alpinelinux/docker-alpine/issues/405, the Alpine project will probably release a new version (`v3.20.2`), and the Docker team will rebuild the image which depends on version `v3.20`.

However, Traefik binary does not use the OpenSSL library, so we are not affected.

Thanks for pointing this out, I am closing this issue accordingly.
