### ISSUE TITLE
A way to explain why a request match a certain router when router rules conflict happen

### ISSUE THREAD

**Issue by rpstw** [traefik/traefik#10918]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We have 3k+ rules. One of them is bad and will receive more traffic than we intended to but it did not cause troubles immediately after it was created.

Some months later, we have a new request that was routed to this router. Since the API does not exist in the end service, we got a 404 response.

The question is: which router stole our request ?

Some hacks we have tried:

1. list all routes and search bad ones by eyes, i.e., `kubectl get ingress routes.traefik.io -A -o yaml | grep some-magic-regex`.
2. rely on  some external monitoring system to find which service returned 404 response recently. A prometheus example looks like `sum(rate(some_metric{code="404'}[1m])) > 0`

There are many other occasions when rule conflicts happen. I believe for many people, they will not realize there exists a conflict until days even months later. 

As far as I can tell, nginx does not have a similar feature. My worst experience debugging conflict using nginx was reading the doc of `location`  many times. Without an efficient debug tool, it is always a long-time work.

I know to avoid conflict completely, one need to write precise rules instead of vague rules. However this is not the case since we are migrating from nginx to Traefik and having a lot of `location ~` or `location /` rules,

**Comment by kevinpollet** [comment]
Hello @rpstw and thanks for your interest in Traefik,

We are not sure to fully understand every detail of your use case, is this issue a feature request?
Could you please elaborate on this, what solution would you expect?

Did you consider using [tracing](https://doc.traefik.io/traefik/observability/tracing/overview/) to see where the request is going?

**Comment by rpstw** [comment]
1. create rule _a_
2. months later
3. some request wrongly matches _a_

there are thounds of rules，how to find the _a_ quickly？

**Comment by rpstw** [comment]
The problem is solving an existing conflict. It's hard to find suspects without relying on an external system like metrics, tracing or access log.

I agree with @rtribotte identifying potential conflicts is hard.

Many database systems have a built-in way to help users understanding their queries. A example shows why a document has a score of 1.6943598 during the process of an elastic search query:

```
{
   "_index":"my-index-000001",
   "_id":"0",
   "matched":true,
   "explanation":{
      "value":1.6943598,
      "description":"weight(message:elasticsearch in 0) [PerFieldSimilarity], result of:",
      "details":[
         {
            "value":1.6943598,
            "description":"score(freq=1.0), computed as boost * idf * tf from:",
            "details":[
               {
                  "value":2.2,
                  "description":"boost",
                  "details":[]
               },

```

Similar, an "explain" telling us which router will handle the request could be helpful. However, I'm not sure how helpful it would be  so comments are welcome.

**Comment by rtribotte** [comment]
Hello @rpstw,

I would not make an equivalence between explaining a query result against a database and the rule conflict issue.
Traefik handles the request with the first matching handler.
Unlike databases, rule evaluation is not complex, there are no heuristics except the router's priority, and Traefik would look over and evaluate every rule if needed.

Since you know the request you want to evaluate (to check if it is handled by the correct router), it is as simple as making the request and checking which router handled it.

Then, why not use access logs or tracing for that?

**Comment by rpstw** [comment]
The why is  relying on an external system that we or maybe many others don't have.

However, I realized a so-called `explain` functionality is basically equivalent to the access-log. The only difference is interactive or long-lasting, so maybe it's not a must-have.

I'll try the access log for now. Thanks for the great explanation @kevinpollet.
