### ISSUE TITLE
Server reported as OK when it is not

### ISSUE THREAD

**Issue by wsw70** [traefik/traefik#10914]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have docker-configured services that ultimately point to a server. The dashboard shows the chain of service - middleware - ... ending with a server.
The server is supposed to be healthy when it responds with a 2xx or 3xx.

### What did you see instead?

A service that is not even an HTTP server (this was a misconfiguration issue which led to the discovery of this issue) I reported as Healthy/OK

The chain:

![image](https://github.com/user-attachments/assets/514a2fa2-4b70-436e-aa19-ff5931dbb217)

The service with its server:

![image](https://github.com/user-attachments/assets/8ec94dc8-ba7f-468f-b4d0-fe9de25b885f)

The server is a MQTT broker - it is not based on HTTP but on a binary protocol. It will not answer correctly to an HTTP call. Thi is what I get from within the Traefik container

```
/ # wget -O - http://192.168.48.19:1883
Connecting to 192.168.48.19:1883 (192.168.48.19:1883)
wget: error getting response: Connection reset by peer
```

The services that are expected to work do work.

### What version of Traefik are you using?

```
/ # traefik version
Version:      3.1.0
Codename:     comte
Go version:   go1.22.5
Built:        2024-07-15T14:44:04Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

→ I am not sure what would be relevant from my configuration, all the configuration is based off docker.

**Note**: there are similar issues raised, but for services (such as https://github.com/traefik/traefik/issues/6117) where the service is shown as healthy despite the server not being OK. My opinion I that this is an incorrect message (ultimately the service does not work) but this is a matter for interpretation. My problem deals directly with the end of the chain: the server.

**Comment by emilevauge** [comment]
Hi @wsw70 
We agree that the UI is confusing, I'm closing this one and will make a proposal in #6117.
In your specific use case, it looks you are expecting a passive healthcheck is made on your server, which is not the case. If you haven't configured any healtheck, there is not server status update.
Let's continue the discussion in the other issue :)
