### ISSUE TITLE
High CPU usage with addMulVVW1024

### ISSUE THREAD

**Issue by LeeDF** [traefik/traefik#10934]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was using traefik as a gateway and found that it consumed more cpu than nginx, with pprof seeing that 20% was consumed at addMulVVW1024

### What did you see instead?

![WX20240725-162351@2x](https://github.com/user-attachments/assets/8a5fedb4-1b6d-45e4-8a2a-f062513a43b1)

this is pprof profile 
[profile.log](https://github.com/user-attachments/files/16372961/profile.log)

### What version of Traefik are you using?

Version:      v3.0
Go version:   go1.22.2
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by kevinpollet** [comment]
Hello @LeeDF and thanks for your interest in Traefik,

As you probably know, we are using the standard crypto library from the Go programming language. If you believe there is room for improvement in the crypto library, please feel free to open an issue in the Go [repository](https://github.com/golang/go).
