### ISSUE TITLE
HTTPRoute and other Gateway API routes updated even without changes 

### ISSUE THREAD

**Issue by pguan-ntap** [traefik/traefik#10939]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When I deploy a HttpRoute with the latest traefik v3.1.0 I see continuous unecessary updates to the HTTPRoute's status with only changes in the lastTransitionTime. According to the kube api docs for LastTransitionTime, it should only be updated when the underlying condition changes

### What did you see instead?

The HTTPRoute continuously gets updated with only changes to its status.parents.conditions[].lastTransitionTime

### What version of Traefik are you using?

v3.1.0

### What is your environment & configuration?

AKS v1.27

containers:
      - args:
        - --global.checknewversion=false
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --core.defaultRuleSyntax=v2
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowCrossNamespace=true
        - --providers.kubernetescrd.allowExternalNameServices=true
        - --providers.kubernetescrd.allowEmptyServices=true
        - --experimental.kubernetesgateway
        - --providers.kubernetesgateway
        - --entryPoints.traefik.forwardedHeaders.trustedIPs=10.0.0.0/8
        - --entryPoints.web.http.redirections.entryPoint.to=:443
        - --entryPoints.web.http.redirections.entryPoint.scheme=https
        - --entryPoints.web.http.redirections.entryPoint.permanent=true
        - --entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8
        - --entryPoints.websecure.http.tls=true
        - --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8
        - --log.format=json
        - --log.level=WARN

### If applicable, please paste the log output in DEBUG level

Continuously getting these
{"level":"warn","providerName":"kubernetesgateway","http_route":"app1","namespace":"app1","error":"failed to update HTTPRoute \"app1\" status: Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io \"app1\": the object has been modified; please apply your changes to the latest version and try again","time":"2024-07-24T20:16:14Z","message":"Unable to update HTTPRoute status"}

**Comment by Gitopolis** [comment]
Same problem on EKS 1.29

**Comment by kevinpollet** [comment]
Fixed by https://github.com/traefik/traefik/pull/10940
