### ISSUE TITLE
Include certificate used by a router in the Traefik API response

### ISSUE THREAD

**Issue by Programie** [traefik/traefik#10942]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I want to be able to know which certificate is used by which router. Therefore, it would be good to return the subject or CN of the used certificate for each router in the `/api/http/routers` response (and probably also the other API endpoints for router objects, like for TCP and UDP routers).

My actual use-case is to setup a monitoring for the configured routers and their certificate validity and to see whether there are any unused certificates.

**Comment by rtribotte** [comment]
Hello @Programie,

Thanks for your interest in Traefik!

>I want to be able to know which certificate is used by which router

Unfortunately, this is not be possible. Certificates are not tied to routers, they are chosen at connection level.
Whenever a new TLS connection comes in, the SNI (server name indication), provided in the client hello, is used to find the matching certificate in the store.

We are closing this issue a question accordingly but feel free to ask to reopen if you think we missed something.
