### ISSUE TITLE
TLS not working when Traefik is behind a TCP Loadbalancer with Proxy protocol v2 enabled

### ISSUE THREAD

**Issue by emilrowland** [traefik/traefik#10960]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Enable TLS on a route when Traefik is behind an AWS Network Load Balancer in TCP mode (SSL pass through), with enabled Proxy protocol v2 on the load balancer. Then the route stopped working, both HTTP and HTTPS variants.
If I disable Proxy protocol v2 on the load balancer both routes start working again.

Pure HTTP routes work as normal with and without Proxy Protocol v2. So it only affects routes that have a TLS setting.

### What did you see instead?

For the HTTPS  variant, I get in the browser ERR_SSL_PROTOCOL_ERROR. And for the HTTP variant, I get a 404 error.

More detailed info about the error when running curl:
````
curl -v https://argocd.internal.stage.MYDOMAIN
*   Trying xx.xx.xx.xx:443...
* TCP_NODELAY set
* Connected to argocd.internal.stage.MYDOMAIN (xx.xx.xx.xx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
````

### What version of Traefik are you using?

3.1.0

### What is your environment & configuration?

```sh
helm upgrade --install traefik traefik/traefik \
        --namespace traefik \
        --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="external" \
        --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-nlb-target-type"="instance" \
        --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-proxy-protocol"="\*" \
        --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-scheme"="internet-facing" \
        --set service.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="traefik\.internal\.${DOMAIN_PREFIX}\.rowland\.io" \
        --set ports.web.proxyProtocol.insecure=true \
        --set ports.web.proxyProtocol.trustedIPs[0]="0.0.0.0/0" \
        --set providers.kubernetesCRD.allowCrossNamespace=true \
        --set logs.access.enabled=true \
        --set logs.general.level=DEBUG
```

The route helm chart:
```helm
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
spec:
  commonName: argocd.internal.{{ include "infra.fullDomain" . }}
  secretName: argocd-server-cert
  dnsNames:
    - argocd.internal.{{ include "infra.fullDomain" . }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: {{ include "infra.traefikDomain" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.internal.{{ include "infra.fullDomain" . }}`)
      priority: 10
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
    - kind: Rule
      match: Host(`argocd.internal.{{ include "infra.fullDomain" . }}`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-server-cert
```

### If applicable, please paste the log output in DEBUG level

Unfortunately no relevant logs can be found in DEBUG mode.

**Comment by mmatur** [comment]
Hi @emilrowland,

Thanks for you issue.

This error seems to be linked to your CertManager, could you please check if cert manager has correctly generated the certificate.

To me it is not related to proxy protocol with the information you have provided

**Comment by emilrowland** [comment]
I found the issue.
The problem was that I hadn't set the flaggs for proxyProtocol on the websecure endpoint.
--set ports.websecure.proxyProtocol.insecure=true \
--set ports.websecure.proxyProtocol.trustedIPs[0]="0.0.0.0/0"

After I added the flaggs above it works without any issue.

So no bug in Traefik but an configuration issue.

**Comment by mmatur** [comment]
Hi @emilrowland,

Thanks, this is exactly what I was answering you.

Enjoy
