### ISSUE TITLE
unable to download plugin error 404

### ISSUE THREAD

**Issue by samerbahri98** [traefik/traefik#11011]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have created the following plugin: github.com/samerbahri98/sigv4middleware
the plugin works locally and the tests are passing

### What did you see instead?

The plugin does not get downloaded when referenced in the config by the git repository and tag
the following error log is present:
```
2024-08-17T00:22:33Z ERR Plugins are disabled because an error has occurred. error="unable to set up plugins environment: unable to download plugin github.com/samerbahri98/sigv4middleware: error: 404: {\"error\":\"Unknown plugin: github.com/samerbahri98/sigv4middleware@v0.1.6\"}\n" plugins=["sigv4middleware"]
```
Other GitHub issues (#10088 and #10107 for reference) and  seem to point to this being a tagging issue, but I tagged it few times so far with no success

### What version of Traefik are you using?

Version:      3.1.0
Codename:     comte
Go version:   go1.22.5
Built:        2024-07-15T14:44:04Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
---
experimental:
  plugins:
    sigv4middleware:
      moduleName: github.com/samerbahri98/sigv4middleware
      version: v0.1.6
```

edit: I have since opening this issue renamed the repo in the hope that this would be the bug, but that wasn't the case it seems

**Comment by nmengin** [comment]
Hey @samerbahri98,

Thank you for reaching out.
It looks like your plugin repository is missing a topic, that is required.

You can check the [documentation](https://plugins.traefik.io/create) for more information.
If you need more guidance, please create a topic in the [community forum](https://community.traefik.io/).
It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
