### ISSUE TITLE
Allow combining of multiple IPAllowlist Middlewares

### ISSUE THREAD

**Issue by Cebrain** [traefik/traefik#11012]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hey,

i found this older topic, in which this is already discussed but i think this is a different feature request instead of the OR feature.
https://github.com/traefik/traefik/issues/6007

I would like to combine multiple IP Ranges in different ipallowlist middlewares.

There are many use cases, for example i wan't to use a default ipallowlist middleware which applies to all containers which allow only AdminLAN Access to the containers.

If i wan't allow additional subnets to access the container i can specify another IPWhitelist, but it will not work because only the first middleware will be checked. 
I can see both middlewares and IP Ranges applied in the Traefik Dashboard but in the logs i see only the AdminLAN IPRange will be allowed.

Here are some other use cases discussed.

Feature Request:
Allow multiple IPRanges to get combines if specified in different middlewares

**Comment by Cebrain** [comment]
I am not quite sure what information is necessary, in the following example i set an default middleware for all websecure services with the middleware "IPAllowList-admin@file" and i would like to add the middleware "IPAllowList-developers@file" to specific services.

**Problem:**

The container gets correctly both IPAllowlists middlewares assigned, but the access decision only happens on the first IPallowlist, in the following case it is the default middleware "IPAllowlist-admin@file".
At the moment the service can only be accessed from the network "192.168.10.0/24", because the connections get dropped/blocked from all other networks.

traefik.toml
`  [entryPoints.websecure]
    address = ":443"
    asDefault = true

      [entryPoints.websecure.http]
        middlewares = ["IPAllowList-admin@file"]`


dynamic allowlist file:
`
[http.middlewares]
  [http.middlewares.IPAllowList-admin.IPAllowList]
    sourceRange = ["192.168.10.0/24"]

  [http.middlewares.IPAllowList-developers.IPAllowList]
    sourceRange = ["192.168.0.0/24"]`


**Expected behavior:**
After assigning a container both middlewares "IPAllowList-admin" and "IPAllowList-developers" it should be accessible from both defined networks.

**Comment by jspdown** [comment]
Hello @Cebrain and thanks for providing more details.

What you are suggesting, if I understand it correctly, is that when multiple `IPAllowlist` are defined on a router, you want the configuration of these middlewares to be merged like a list of OR statements.

Middlewares in Traefik are independent unit of configuration, we don't merge their configuration and only interpret them in isolation. This would be an important change in the concept of Middleware.

https://github.com/traefik/traefik/issues/6007 would have a better chance to happen IMO.
