### ISSUE TITLE
Using environment variables for startup parameters.

### ISSUE THREAD

**Issue by mynicolas** [traefik/traefik#11018]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When starting Traefik via the CLI, can environment variables be used to set startup parameters? For example: --accesslog.filepath=/log/${HOSTNAME}/access.log.

**Comment by nmengin** [comment]
Hello @mynicolas,

Thanks for reaching out!

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
