### ISSUE TITLE
[K8s] Allow empty Services in Errors Middleware

### ISSUE THREAD

**Issue by JuJup** [traefik/traefik#11078]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When using the Errors Middleware in Kubernetes, Traefik seems to check if the specified service is empty (no Pod running for the service). In this case, the Middleware will not be added and even worse, the whole IngressRoute is invalid and not available.

**Why is that a problem?**
There are some scenarios, where the IngressRoute has to be available, even though there is no running Pod behind it. That's why there is an [allowEmptyServices](https://doc.traefik.io/traefik/providers/kubernetes-crd/#allowemptyservices) Config. However, there is no equivalent option for the Errors Middleware.
If we use e.g. a Middleware like [Sablier](https://plugins.traefik.io/plugins/633b4658a4caa9ddeffda119/sablier), the Services are empty when accessing the IngressRoute. In combination with the Errors Middleware, the IngressRoute has an Error as described above and I can't use it.
Therefore, a combination of Errors Middleware and Sablier Plugin is yet simply not possible.

**Solution idea**
Simplest idea is to add a Boolean parameter to the middleware, like `allowEmptyService`, which simply deactivates the check for the availability of the Service. Setting this per Default to false, this wouldn't change any previous behavior and wouldn't break any running setups.

Would love to see a Feature like this :)

**Comment by JuJup** [comment]
Hey @nmengin,
thanks for your reply.

> Do you mean that when you set the allowEmptyServiceoption on the provider, the ErrorMiddleware attached to an Ingress that targets an empty service does not work as expected?
No, an IngressRoute using an Error Middleware which targets an empty service (for showing the error page), doesn't come up. The `allowEmptyService` option is meant only for the IngressRoute itself, but as a user I would either expect, that this option holds true for the Middleware as well, or that there is an equivalent option only for the middleware.

I made some example files, I hope it helps. Please let me know, if I can add more information :)
https://github.com/JuJup/traefik-issue-11078-example

**Comment by rtribotte** [comment]
Hello @JuJup,

At glance, the example you have shared should work, as the `allowEmptyServices` option is used when discovering the error pages service, can you please share with us the DEBUG logs? There should be an error explaining why the middleware is not "built".

**Comment by JuJup** [comment]
@rtribotte, thanks for your answer.
Yes, it's configured with the option set to true. I pass the following CLI parameter:
`--providers.kubernetescrd.allowEmptyServices=true`

And as described, that works perfectly fine. In my example and when I tested it again half an hour ago the service for the Ingressroute itself was empty and that didn't produce any problem. Only the service used by the errors middleware was making the ingressroute fail if it was empty.

**Comment by rtribotte** [comment]
@JuJup Which version of v2 are you using? (looking are the code of v2.11.8, I can't see how this could even happen)

**Comment by JuJup** [comment]
@rtribotte, ok damn, its's an old version. Using 2.8.7 on the cluster where I tested. Using a newer version on another cluster, I will try it next week when I'm back at it. Maybe that's already the problem.
Sorry for wasting your time if it was that..

**Comment by JuJup** [comment]
Hey @rtribotte,
sorry for the late response, couldn't get back to it earlier.
However, running with v3.1 the error is gone and everything works as expected.
Sorry for the false alarm, I'll close the ticket!
Anyway, thanks for your responses and help :)

**Comment by rtribotte** [comment]
Hello @JuJup,

Good news, and thanks for the feedback!
