### ISSUE TITLE
ACME for selfhost (selfhost.de)

### ISSUE THREAD

**Issue by aifrog** [traefik/traefik#11096]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I want to setup ACME for the provider "selfhost" (selfhost.de). In other distributions (e.g. proxmox), there is a dns_selfhost.sh file enabeling to do ACME with DNS on this provider. On traefik this fails. Is this a missing profile for ACME with selfhost? Is there a way that I add the dns_selfhost.sh file or a derivate to enable traefik to work with the provider "selfhost"?

### What did you see instead?

.

### What version of Traefik are you using?

...

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

.

**Comment by ldez** [comment]
Hello,

Traefik used [lego](https://github.com/go-acme/lego/) to handle ACME challenges, you should open an issue on the lego repository for the support of new DNS providers.
