### ISSUE TITLE
Ability to set base path for Traefik dashboard

### ISSUE THREAD

**Issue by Arthurdw** [traefik/traefik#11127]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Right now you can proxy the frontend with some rules, but because the `/api` calls go to the root base URL you can not for example have a prefix to `/traefik/` and put everything after it without affecting anything else. 

A simple feature would be to be able to pass something like `--api.base-url=/traefik` with it having  a default of `/`

**Comment by kevinpollet** [comment]
Duplicate of #5853
