### ISSUE TITLE
Something changed after updaded from v2 to v3

### ISSUE THREAD

**Issue by chuoke** [traefik/traefik#11123]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

updaged from v2 to v3

### What did you see instead?

Route matching has changed dramatically.

I have some routers like these three apps:

```
Host(`domain.com`)
Host(`domain.com`) && PathPrefix(`/api`)
Host(`xxx.domain.com`)
```

In v2, there are no problems, all can be correctly routed to the corresponding application. 
But after I upgraded to v3, things changed. All are routed to the application referred to by `domain.com`.

I tried to find instructions in the relevant documentation, but I couldn't find them.

### What version of Traefik are you using?

v3.1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by jspdown** [comment]
Hello @chuoke,

The relevant documentation can be found in the migration section: https://doc.traefik.io/traefik/migration/v2-to-v3/
