### ISSUE TITLE
"Unable to find source related to" error posted while importing an external package in plugin

### ISSUE THREAD

**Issue by duj4** [traefik/traefik#11184]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to import an external package in the local plugin, but it failed to start with error:
![Image](https://github.com/user-attachments/assets/e4e9fc68-10d9-4dea-8d91-9cc7f1f8a14c)

### What did you see instead?

Traefik failed to start with error mentioned above.

### What version of Traefik are you using?

![Image](https://github.com/user-attachments/assets/43498d45-87b9-447e-814c-d21d0ad5d9f0)

### What is your environment & configuration?

![Image](https://github.com/user-attachments/assets/cf77aff0-7bf9-48cb-afd9-72c013f7b869)

**Comment by michelheusschen** [comment]
You should vendor dependencies. You can find more details in the plugin demo repo here https://github.com/traefik/plugindemo?tab=readme-ov-file#usage

**Comment by duj4** [comment]
hi @michelheusschen 

Thanks for the reply.

I followed the guide to vendor the plugin and the previous error is gone, appreciate for the help:
![Image](https://github.com/user-attachments/assets/02a83d96-a2bc-4f42-893a-d076b018c1ad)

However, new error coming out when I tried to declare the variable with the imported plugin:
![Image](https://github.com/user-attachments/assets/83daa17f-0a64-4ffd-ae51-7d1fb6e22d8b)

Here is the definition:
![Image](https://github.com/user-attachments/assets/4fce6a48-a484-4737-8f7b-3ab08f1e83c1)

(sorry I am not able to copy the error in text but in screenshot only).

Is this something wrong with Yaegi?

**Comment by michelheusschen** [comment]
Yaegi doesn't support generics yet, so you'll have to use an older version of `github.com/orcaman/concurrent-map` that doesn't use generics

**Comment by duj4** [comment]
Thanks @michelheusschen , I tried v1.0.0 and it is working now, but I may need some further test, please keep this open for another day or two.
Btw, may I know when generics will be supported in yaegi?

**Comment by nmengin** [comment]
Hello @duj4,

Thanks for reaching out.

> Btw, may I know when generics will be supported in yaegi?

We do not have any ETA to share yet.

As your question is answered, I close the issue.
We'll re-open it later if necessary.

**Comment by duj4** [comment]
hi @michelheusschen @nmengin ,

After running for a while, the pod of Traefik restarted with error as below:
![Image](https://github.com/user-attachments/assets/949a810f-e522-4091-a12d-78d776ca10c2)

And here is the code snippet:
![Image](https://github.com/user-attachments/assets/b585629d-fcf3-41a5-a3c9-34532d01b1f0)

**Comment by nmengin** [comment]
Hello @duj4,

It looks like the issue comes from Yaegi.
Could you open an issue on this [repository](https://github.com/traefik/yaegi/issues)?

**Comment by duj4** [comment]
> Hello [@duj4](https://github.com/duj4),
> 
> It looks like the issue comes from Yaegi. Could you open an issue on this [repository](https://github.com/traefik/yaegi/issues)?

ok, thanks @nmengin
