### ISSUE TITLE
Upcoming breaking change in Porkbun API URL

### ISSUE THREAD

**Issue by eliac** [traefik/traefik#11194]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

[Porkbun](https://porkbun.com/) have announced that starting 2024-12-01, the current API hostname - `https://porkbun.com/` - will stop working, in favor of the new hostname `https://api.porkbun.com/`. (They announced it by email, I wasn't able to find a statement on their website.)

In its current state, this will break Traefik's support of Let's Encrypt for Porkbun.

The new URL is already supported in `nrdcg/porkbun` v0.4.0, which is included in `go-acme/lego` v4.19.0 and up. It would be sufficient for Traefik to upgade `go-acme/lego` to v4.19.0 to address this issue.
![Image](https://github.com/user-attachments/assets/6a9e4695-3ecb-42b8-bafc-d5ac41fb4b75)

### What did you see instead?

Traefik imports `go-acme/lego` v4.18.0, which includes `nrdcg/porkbun` v0.3.0, which uses the old Porkbun URL (`https://porkbun.com/`).

### What version of Traefik are you using?

v3.1.6

### What is your environment & configuration?

N/A

**Comment by eliac** [comment]
For context, here are some similar issues in other projects: https://github.com/acmesh-official/acme.sh/issues/5322, https://github.com/ddclient/ddclient/issues/751

**Comment by ldez** [comment]
Hello,

I already updated lego inside Traefik: https://github.com/traefik/traefik/pull/11159

But it's not yet in a release.

**Comment by eliac** [comment]
Oops! I searched the issues for "Porkbun", so I missed it. Thanks for your quick responce, closing this issue.
