### ISSUE TITLE
Certificates resolver naming in environment variables

### ISSUE THREAD

**Issue by dreamair** [traefik/traefik#11202]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

While `certificatesResolvers: mainResolver: acme: ...` in traefik.yml or `--certificatesResolvers.mainResolver.acme...` as CLI argument works, the environment variable `TRAEFIK_CERTIFICATESRESOLVERS_mainResolver_ACME_...` doesn't.

Works with `TRAEFIK_CERTIFICATESRESOLVERS_mainresolver_ACME_...`! so maybe some hint in the documentation would suffice.

### What did you see instead?

ERR Router uses a nonexistent certificate resolver certificateResolver=mainResolver...

### What version of Traefik are you using?

v3.1.6

### What is your environment & configuration?

```ini
      TRAEFIK_CERTIFICATESRESOLVERS_mainResolver_ACME_STORAGE: /acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_mainResolver_ACME_HTTPCHALLENGE_ENTRYPOINT: web
```

**Comment by nmengin** [comment]
Hey @dreamair,

Thank you for raising this issue.
With the other maintainers thinking that the documentation should be fixed indeed.

This would not make it to our roadmap as we are focused elsewhere. If you or another community member would like to build it, let us know, and we will work with you to ensure you have all the information needed to merge it.

We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process. Let us know here or create a PR before you start, and we will work with you there.

Don’t forget to check out the[ contributor docs](https://github.com/traefik/contributors-guide/blob/master/pr_guidelines.md) and link the PR to this issue.

**Comment by anchal00** [comment]
Hey @nmengin , I took a shot at this and I have created a PR for the same https://github.com/traefik/traefik/pull/11226. Please review it PR when you get a chance.

**Comment by anchal00** [comment]
> Hey [@nmengin](https://github.com/nmengin) , I took a shot at this and I have created a PR for the same [#11226](https://github.com/traefik/traefik/pull/11226). Please review it when you get a chance.

Update: This has been resolved and merged now. This issue can be closed.
