### ISSUE TITLE
A NotClientIP() option in router

### ISSUE THREAD

**Issue by D0wn3r** [traefik/traefik#11214]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello,

I'm trying to build a maintenance page system that allows developers to test. It works very well with a priority system, as I have a maintenance service that overrides routers. However, I don't know how to let some IPs bypass this maintenance page (everyone is blocked).

If I had a feature like NotClientIP(<dev_ip_list>) to put on my maintenance service, it would block clients and allow developers to test.

If there’s an equivalent that I don't know about, please let me know!

If this feature could be useful for you, don't forget to 👍

**Comment by rtribotte** [comment]
Hello @D0wn3r,

Thanks for your interest in Traefik!

Currently, it seems that what you want to achieve is doable by using the NOT (`!`) operator: https://doc.traefik.io/traefik/routing/routers/#rule.

> it would block clients and allow developers to test.

We are wondering what do you mean exactly by that, can you please elaborate or confirm that the NOT operator is fitting you need?
Thanks!

**Comment by D0wn3r** [comment]
Hi @rtribotte !

Yeah, thank you !

I didn't see this NOT option, it's amazing
