### ISSUE TITLE
Change dynamic configuration / labels for Docker Swarm to use `swarm` rather than `docker`

### ISSUE THREAD

**Issue by webash** [traefik/traefik#11244]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Change the `traefik.docker.*` dynamic configuration / labels for the Docker Swarm provider to `traefik.swarm.*` for better consistency when using the Docker Swarm provider.

This started from discussion in #11207 and [prompt](https://github.com/traefik/traefik/pull/11207#pullrequestreview-2392846126) by @kevinpollet .

**Comment by emilevauge** [comment]
Hey @webash , thanks for reporting this! If anyone can help on creating a PR on this, we would love to assist :)

**Comment by thunhuanh** [comment]
Hi @emilevauge @webash, 

I love traefik and i want to be a contributor for it.

Can i work on this?

**Comment by emilevauge** [comment]
@thunhuanh sure :) Great news, thanks for contributing!

**Comment by anchal00** [comment]
Hi @emilevauge @kevinpollet @rtribotte, I have created a PR on this https://github.com/traefik/traefik/pull/11247. Could you please review when you get a chance. Thankyou

**Comment by thunhuanh** [comment]
Hi @emilevauge 

I have made an attempt to update this, and here is the PR

https://github.com/traefik/traefik/pull/11251

Can you help me review it?

**Comment by Anant-2005** [comment]
Hi can you assign me this issue?

**Comment by kevinpollet** [comment]
Hi @Anant-2005,

There is already a pull request addressing this issue: https://github.com/traefik/traefik/pull/11247

Do not hesitate to pick up another issue with the [contributor/wanted](https://github.com/traefik/traefik/issues?q=is%3Aissue%20state%3Aopen%20label%3Acontributor%2Fwanted) label.

**Comment by webash** [comment]
Looks like #11247 has been released in v3.2.2 - I shall test and then come back to close off

**Comment by webash** [comment]
Seems fine!
