### ISSUE TITLE
The service accessed through Traefik has all response headers in lowercase

### ISSUE THREAD

**Issue by hanxiaolong891128** [traefik/traefik#11307]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

The service accessed through Traefik has all response headers in lowercase

### What did you see instead?

![Image](https://github.com/user-attachments/assets/2a87689f-31b6-41ae-9e8b-5ee939a3f620)

### What version of Traefik are you using?

3.2

### What is your environment & configuration?

```yaml
Install with Helm and use the default configuration
```

Add more configuration information here.

**Comment by jspdown** [comment]
Thanks @hanxiaolong891128 for your interest in Traefik

Traefik does sometime changes the case of the Headers to always serve their canonical form. Headers are case-insensitive according to the HTTP RFC.
But Traefik will never serve lowercased headers. I suggest you try with a `curl` and make sure you don't have another component in between altering the case. 

I'm closing this issue, feel free to open a discussion on the forum.

**Comment by hanxiaolong891128** [comment]
> Thanks [@hanxiaolong891128](https://github.com/hanxiaolong891128) for your interest in Traefik
> 
> Traefik does sometime changes the case of the Headers to always serve their canonical form. Headers are case-insensitive according to the HTTP RFC. But Traefik will never serve lowercased headers. I suggest you try with a `curl` and make sure you don't have another component in between altering the case.
> 
> I'm closing this issue, feel free to open a discussion on the forum.

OK  Thanks
