### ISSUE TITLE
Having issues with Traefik v3.2.1's RFC2136 DNS challenge for automatic Let's Encrypt certificate generation.

### ISSUE THREAD

**Issue by RobertWi** [traefik/traefik#11303]
# Traefik RFC2136 DNS Challenge TSIG Authentication Failure

## Description
Having issues with Traefik v3.2.1's RFC2136 DNS challenge for automatic Let's Encrypt certificate generation. DNS updates are failing with TSIG verification errors when attempting to add/remove TXT records for domain validation.

## Environment
- Traefik: v3.2.1
- Container Runtime: Podman 5.3.0
- DNS Server: BIND 9.18.28 (Extended Support Version)
- Domains:
  * traefik.home.doemijdienamespacemaar.nl
  * gitlab-tst.home.doemijdienamespacemaar.nl
- Environment Variables:
  * RFC2136_NAMESERVER=ns3.home.doemijdienamespacemaar.nl53
  * RFC2136_TSIG_ALGORITHM=hmac-sha256.
  * RFC2136_TSIG_KEY_NAME=tsig-key
  * RFC2136_TSIG_SECRET=[REDACTED]
  * LEGO_EXPERIMENTAL_CNAME_SUPPORT=true
  * LEGO_LOG_LEVEL=DEBUG
- BIND TSIG Key:
  * key name: tsig-key
  * algorithm: hmac-sha256
  * secret: [REDACTED]

## System Architecture
```mermaid
graph LR
    T[Traefik v3.2.1]
    B[ns3.home.doemijdienamespacemaar.nl]
    LE[Let's Encrypt]
    
    T -->|RFC2136 Provider| B
    B -->|TSIG hmac-sha256| B
    T -->|ACME| LE
    LE -->|Verify *.home.doemijdienamespacemaar.nl| B

    subgraph Flow
        1[Request Cert] --> 2[DNS-01 Challenge]
        2 -->|RFC2136| 3[Create TXT on ns3.home.doemijdienamespacemaar.nl]
        3 --> 4[Verify ZONE home.doemijdienamespacemaar.nl]
        4 --> 5[Issue Cert]
        5 -->|RFC2136| 6[Remove TXT]
    end
```
## Problem
1. Manual DNS updates using `nsupdate` with the same TSIG key work successfully
2. Traefik/Lego DNS challenge fails with TSIG verification (BADKEY) errors
3. Unable to automatically obtain/renew Let's Encrypt certificates

## Diagnostic Steps Performed
1. Verified BIND version and configuration
2. Tested manual DNS updates using nsupdate with identical TSIG key
3. Enabled debug logging in both Traefik and BIND
4. Verified network connectivity and DNS resolution
5. Confirmed TSIG key format and encoding

## Findings
1. Manual DNS updates succeed, confirming basic TSIG key functionality
2. Traefik's RFC2136 provider fails to authenticate with the same TSIG key
3. Potential issue with TSIG algorithm format (trailing dot in configuration)
4. Network connectivity and DNS resolution working correctly

## Potential Issues Identified
1. TSIG algorithm format includes trailing dot (`hmac-sha256.`) which may cause issues
2. Possible mismatch in key name or case sensitivity
3. Potential issue in how Traefik/Lego formats the TSIG authentication

## Questions
1. Is the trailing dot in `RFC2136_TSIG_ALGORITHM=hmac-sha256.` causing authentication failures?
2. Are there any known issues with Traefik v3.2.1's RFC2136 provider implementation?
3. Could there be a case sensitivity issue with the TSIG key name?

## Additional Information
- Full debug logs available upon request
- Manual nsupdate commands work successfully
- Network connectivity verified between Traefik container and BIND server
- DNS resolution working correctly for all domains

## Possible Workarounds Attempted
1. Adjusted TSIG key format and encoding
2. Verified DNS server configuration
3. Tested with different delay settings
4. Confirmed network connectivity and DNS resolution

## Next Steps
Would appreciate guidance on:
1. Correct format for TSIG algorithm string
2. Any known issues with RFC2136 provider in Traefik v3.2.1
3. Additional debugging steps or configuration changes to try

### Traefik ACME Configuration (traefik.yaml)
```yaml
certificatesResolvers:
  myresolver:
    acme:
      email: "[REDACTED]"
      storage: "/var/traefik/certs/acme.json"
      dnsChallenge:
        provider: rfc2136
        delayBeforeCheck: 60
```
## 1. Traefik attempts DNS-01 challenge
[INFO] [traefik.home.doemijdienamespacemaar.nl] acme: Obtaining bundled SAN certificate
[INFO] [traefik.home.doemijdienamespacemaar.nl] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/2073916237/434830476007
[INFO] [traefik.home.doemijdienamespacemaar.nl] acme: Could not find solver for: tls-alpn-01
[INFO] [traefik.home.doemijdienamespacemaar.nl] acme: Could not find solver for: http-01
[INFO] [traefik.home.doemijdienamespacemaar.nl] acme: use dns-01 solver
[INFO] [traefik.home.doemijdienamespacemaar.nl] acme: Preparing to solve DNS-01

## 2. DNS update fails with REFUSED
[WARN] [traefik.home.doemijdienamespacemaar.nl] acme: cleaning up failed: rfc2136: failed to insert: DNS update failed: server replied: REFUSED

## 3. BIND server logs showing TSIG verification failures
24-Nov-2024 11:03:22.043 error: client @0x7f8525d1c0 192.168.33.110#59813: request has invalid signature: TSIG m3razwi/f61pvbyokiglfqnuvkzfezji25bl4qzomnm=: tsig verify failure (BADKEY)

## 4. Final error from Traefik
[ERR] Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.home.doemijdienamespacemaar.nl]: error: one or more domains had a problem:
[traefik.home.doemijdienamespacemaar.nl] [traefik.home.doemijdienamespacemaar.nl] acme: error presenting token: rfc2136: failed to insert: DNS update failed: server replied: REFUSED"

## 5. Successful manual updates from same client IP nsupdate 
24-Nov-2024 12:49:56.662 info: client @0x7f842062c0 192.168.33.110#34499/key tsig-key: updating zone 'home.doemijdienamespacemaar.nl/IN': adding an RR at '_acme-challenge.test.home.doemijdienamespacemaar.nl' TXT "test-manual-update"

## 6  Add TXT record
$ cat /tmp/test-add.txt
server ns3.home.doemijdienamespacemaar.nl
zone home.doemijdienamespacemaar.nl
update add _acme-challenge.test.home.doemijdienamespacemaar.nl. 60 IN TXT "nsupdate-verify-test"
send

$ nsupdate -k /tmp/tsig.key -v /tmp/test-add.txt
Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id: 0
;; flags:; ZONE: 0, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
;; ZONE SECTION:
;home.doemijdienamespacemaar.nl. IN SOA

;; UPDATE SECTION:
_acme-challenge.test.home.doemijdienamespacemaar.nl. 60 IN TXT "nsupdate-verify-test"

## 7. Verify record was added
$ dig @ns3.home.doemijdienamespacemaar.nl _acme-challenge.test.home.doemijdienamespacemaar.nl TXT

; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> @ns3.home.doemijdienamespacemaar.nl _acme-challenge.test.home.doemijdienamespacemaar.nl TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33094
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; ANSWER SECTION:
_acme-challenge.test.home.doemijdienamespacemaar.nl. 60 IN TXT "nsupdate-verify-test"

## 8. Delete TXT record
$ cat /tmp/test-del.txt
server ns3.home.doemijdienamespacemaar.nl
zone home.doemijdienamespacemaar.nl
update delete _acme-challenge.test.home.doemijdienamespacemaar.nl. TXT
send

$ nsupdate -k /tmp/tsig.key -v /tmp/test-del.txt
Outgoing update query:
;; ->>HEADER<<- opcode: UPDATE, status: NOERROR, id: 0
;; flags:; ZONE: 0, PREREQ: 0, UPDATE: 0, ADDITIONAL: 0
;; ZONE SECTION:
;home.doemijdienamespacemaar.nl. IN SOA

;; UPDATE SECTION:
_acme-challenge.test.home.doemijdienamespacemaar.nl. 0 ANY TXT

## 4. Verify record was deleted
$ dig @ns3.home.doemijdienamespacemaar.nl _acme-challenge.test.home.doemijdienamespacemaar.nl TXT

; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> @ns3.home.doemijdienamespacemaar.nl _acme-challenge.test.home.doemijdienamespacemaar.nl TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 62118
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; AUTHORITY SECTION:
home.doemijdienamespacemaar.nl. 7200 IN SOA ns3.home.doemijdienamespacemaar.nl. info.doemijdiemailmaar.nl. 50 43200 900 1814400 7200

**Comment by ldez** [comment]
Hello,

There is no specific implementation of this DNS challenge inside Traefik, I recommend opening an issue on the [lego repository](https://github.com/go-acme/lego), I will answer you in this new issue.
