### ISSUE TITLE
dnsChallenge with Netcup requires extended "delayBeforeCheck"

### ISSUE THREAD

**Issue by felixbaumgaertner** [traefik/traefik#11327]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When setting up Traefik with Let's Encrypt on a Netcup server, I encountered issues with the DNS-01 challenge. The challenge often failed because Netcup's DNS propagation times are unusually long. This issue is also discussed in other projects, such as the [certbot-dns-netcup plugin](https://github.com/coldfix/certbot-dns-netcup/issues/28), where users noted that Netcup's DNS zones reload every 10 minutes, with propagation occasionally taking up to 20 minutes.

To address this, it is necessary to configure the `delayBeforeCheck` parameter with a sufficiently long delay. Based on my experience and the feedback in related projects, a value of 630 or even 900 seconds is advisable.

To help other users avoid this issue, I suggest adding a note to the [ACME documentation](https://doc.traefik.io/traefik/https/acme/#provider) that explicitly recommends increasing the delayBeforeCheck parameter when using Netcup as the DNS provider.

This small addition to the documentation would save users significant time and frustration when setting up Traefik with Netcup.

**Comment by ldez** [comment]
Hello,

if your problem is related to propagation it is better to increase `NETCUP_PROPAGATION_TIMEOUT` and `NETCUP_POLLING_INTERVAL`.

https://go-acme.github.io/lego/dns/netcup/index.html

`delayBeforeCheck` is mainly for zones that are created but not updated.

**Comment by felixbaumgaertner** [comment]
Hey ldez, thanks for looking into this!
You are absolutely right, that seems like a far better solution. For me it wasn't clear that this "additional configuration" is needed to get the dnsChallenge working in a default setup scenario on Netcup servers.
Thank you for fixing this issue so fast.

**Comment by rtribotte** [comment]
Hello @felixbaumgaertner,

Thanks for this feedback, and because it seems that you issue has been solved, I'm closing it accordingly.
