### ISSUE TITLE
Add support LDAP health checks

### ISSUE THREAD

**Issue by orlovds** [traefik/traefik#11322]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Good time of day.

I kindly ask you to consider adding a feature LDAP health checks , similar to https://www.haproxy.com/documentation/haproxy-configuration-tutorials/service-reliability/health-checks/#ldap-health-checks.

Thank you in advance!

**Comment by emilevauge** [comment]
Hi, thanks for your suggestion :) After discussing this with the maintainer team, we don't plan to integrate this feature.
Thank you
