### ISSUE TITLE
webui/static files are no longer included since 3.2.2

### ISSUE THREAD

**Issue by ephemeralriggs** [traefik/traefik#11363]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I downloaded the v3.2.2 and v3.2.3 tarballs, in order to update the FreeBSD port of traefik. I expected the update to go smoothly since the expected diff from v3.2.1 should be small.

However, I noticed that `traefik` v3.2.3 _itself_ works as expected in my typical test cases, the webui static files are no longer shipped in the [source tarball](https://github.com/traefik/traefik/releases/download/v3.2.3/traefik-v3.2.3.src.tar.gz).

### What did you see instead?

The `webui/static` directory in the release tarball does no longer contain the static webui files, but instead only one file: [DONT-EDIT-FILES-IN-THIS-DIRECTORY.md](https://github.com/traefik/traefik/blob/master/webui/static/DONT-EDIT-FILES-IN-THIS-DIRECTORY.md).

Can we bring back the static webui files in the release [source tarball](https://github.com/traefik/traefik/releases/download/v3.2.3/traefik-v3.2.3.src.tar.gz) please?

### What version of Traefik are you using?

I intended to update the official FreeBSD port from v3.2.1 to v3.2.3.

### What is your environment & configuration?

N/A.

**Comment by rtribotte** [comment]
Hello @ephemeralriggs,

Thanks for your interest in Traefik!

This is indeed a change that we made recently in our build release pipeline, and the rational was that the compiled webui is not per se part of the source code, and can be rebuilt easily with:
```
make -B generate-webui
```
Can you please elaborate on your need, why do you need this?

**Comment by ephemeralriggs** [comment]
To add some background: I am the maintainer of the [official FreeBSD port / package for traefik](https://cgit.freebsd.org/ports/tree/net/traefik). On FreeBSD - unlike Linux - it is fairly common for users to build their own packages from source instead of installing pre-built binary packages.

Although building the webui is certainly possible as you mentioned, it comes with serious drawbacks:
* The number of build-time dependencies becomes very large and unwieldy with node, yarn, et al, increasing the build time on a fresh system without cached packages to multiple hours for users without high end build machines.
* In our package build environment, access to the internet is disabled, i.e. everything that is needed during build would have to be vendored in prior to extracting the tarball (which is what we have to do with the go modules already). This again makes building the web ui more complicated and error-prone.

Summarising, including the static web-ui files in the source tarball is a huge quality-of-life improvement for package maintainers, probably not only for FreeBSD but for other systems and Linux distributions, too. If it is not too much trouble for you to include it again in your build pipeline, we would really appreciate the consideration. Thank you.

**Comment by rtribotte** [comment]
@ephemeralriggs Thanks for your feedback, we opened [#11364](https://github.com/traefik/traefik/pull/11364) to add the static web-ui files back.

**Comment by ephemeralriggs** [comment]
Thank you so much, really appreciate it! 👍

**Comment by nmengin** [comment]
Closed by #11364
