### ISSUE TITLE
CloudWatch metrics support

### ISSUE THREAD

**Issue by sethwklein** [traefik/traefik#1265]
Based on an initial review of the code, I intend to contribute AWS CloudWatch metrics support to Traefik. I expect to have it send much the same information AWS ALB's and ELB's do.

This issue is to provide a heads up for anyone who may want it, and to give opportunity for comment before I get too far into it.

**Comment by sethwklein** [comment]
Unfortunately, the company that was going to provide engineering resources for this pivoted right after I posted and that doesn't look to be changing :( I can't justify putting my own time into it, so I no longer have plans to work on this.

**Comment by nicofuccella** [comment]
+1

**Comment by rupertbg** [comment]
If anyone else is wondering - this can be achieved with a combination of the statsd support in traefik and the statsd support in the cloudwatch agent

https://doc.traefik.io/traefik/observability/metrics/statsd/
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-statsd.html

Running the cloudwatch agent as a sidecar to traefik gives you everything you need to accomplish cloudwatch metrics from traefik

https://github.com/aws-samples/amazon-cloudwatch-container-insights/blob/main/ecs-task-definition-templates/deployment-mode/sidecar/cwagent-statsd/cwagent-statsd-fargate.json

**Comment by mpl** [comment]
Hello,

Given that:

1) the original poster does not seem interested anymore
2) the solution that @rupertbg gave what seems to be not only a work-around, but an accepted, and even recommended, solution
3) CloudWatch seems to be supported through open-telemetry (https://aws-otel.github.io/docs/getting-started/cloudwatch-metrics), which we do support in traefik V3

we're going to decline that issue.

Thanks.
