### ISSUE TITLE
Docker Swarm Mode: mode=global leads to invalid Health UI

### ISSUE THREAD

**Issue by SvenAbels** [traefik/traefik#1481]
### What version of Traefik are you using (`traefik version`)?
1.2.3

### What is your environment & configuration (arguments, toml...)?

docker service create --name traefik **--mode=global** -p 80:80 -p 8080:8080 traefik 

### What did you do?

We launched traefik in mode=global, where traefik is started with 1 instance on each docker swarm node.

### What did you expect to see?

Everything works fine except for the health statistics in the traefik web UI.  

### What did you see instead?

Web UI was jumping between the different instances of traefik. Probably because docker redirects the traffic to a different Traefik instance from time to time. 

Instead it would be great to either see an aggregated view amond the instances or to get a way of accessing each instance separately.

The global mode has some advantages as it allows an even better scaling and failover. So supporting it in traefik would be good.

**Comment by mmatur** [comment]
Hello,

This bug is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
