### ISSUE TITLE
[Idea/Enhancement] Support S3 for configuration/certs

### ISSUE THREAD

**Issue by morph027** [traefik/traefik#1620]
### Do you want to request a *feature* or report a *bug*?

feature / idea / enhancement

### What did you expect to see?

It would be awesome to support S3 for persistent data. This way we could easily add a [Distributed Minio S3 cluster](https://docs.minio.io/docs/distributed-minio-quickstart-guide) and use it to retrieve the config file, certs, whatsoever, ...

**Comment by pascalandy** [comment]
I feel this is a Stateful challenge that should not be manage by Traefik. 
There is a lot of active solution for this where you use virtual volumes
- portworx
- rex-ray
- infinit 
- etc.

**Comment by morph027** [comment]
I found a lot of traps in some of those volume plugins during testing. S3 at application level never fooled me so far.

**Comment by segator** [comment]
+1 for S3.
I used portworx for shared volumes with traefik but it seems it's not enough stable not at least over wan (that is my case)

**Comment by phamviet** [comment]
+1 It seems convince since we do not need to lifetime mounting virtual volume during traefik running.

**Comment by mmatur** [comment]
Hello,

This enhancement is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
