### ISSUE TITLE
Traefik support for Rancher External Services

### ISSUE THREAD

**Issue by fabiorauber** [traefik/traefik#1684]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Sought github for Traefik code that indicates support for Rancher External Services.

### What did you expect to see?

Some code that lists Rancher External Services to include in Traefik configuration.

### What did you see instead?

Provider Rancher has a listRancherServices function that gets only Rancher Services, leaving External Services out.

```golang
func listRancherServices(client *rancher.RancherClient) []*rancher.Service {

	var servicesList = []*rancher.Service{}

	services, err := client.Service.List(withoutPagination)

	if err != nil {
		log.Errorf("Cannot get Provider Services %+v", err)
	}

	for k := range services.Data {
		servicesList = append(servicesList, &services.Data[k])
	}

	return servicesList
}
```

**Comment by proligde** [comment]
I'd like to see that too, since it keeps us from switching from ranchers internal ha-proxy to traefik because I'm not able to make a simple rule like "route https-traffic for host my.domain.tld to internal 192.168.1.200" for example - or do I miss something here ?
