### ISSUE TITLE
Duplicate URL in Backend servers leads to 500 responses

### ISSUE THREAD

**Issue by m3co-code** [traefik/traefik#1933]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

Setup a simple file configuration for development purposes. Doing this I mistyped one of the Backend URLs by chance so that there was a duplicated URL.

### What did you expect to see?

One of two things, I am not sure which is desirable:
- a warning/error in the logs that the configuration is invalid
- a properly working/routing Traefik instance

### What did you see instead?

A Traefik serving 500 responses.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      dev
Codename:     cheddar
Go version:   go1.8.3
Built:        I don't remember exactly
OS/Arch:      darwin/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

This is my `traefik.toml`. There is a simple application running listening to http://localhost:8081/ok and responding with a 200 response.

```toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":8080"

[file]

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Path:/ok"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://localhost:8081"
    [backends.backend1.servers.server2]
    url = "http://localhost:8081"

[accessLog]
format="json"
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
INFO[2017-08-09T10:23:20+02:00] Traefik version dev built on I don't remember exactly 
INFO[2017-08-09T10:23:20+02:00] Using TOML configuration file /Users/mjantke/work/go/src/github.com/marco-jantke/go-playground/sticky/traefik.toml 
DEBU[2017-08-09T10:23:20+02:00] Global configuration loaded {"GraceTimeOut":10000000000,"Debug":false,"CheckNewVersion":true,"AccessLogsFile":"","AccessLog":{"format":"json"},"TraefikLogsFile":"","LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":8080","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":180000000000,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"Docker":null,"File":{"Watch":true,"Filename":"/Users/mjantke/work/go/src/github.com/marco-jantke/go-playground/sticky/traefik.toml","Constraints":null,"Trace":false,"Directory":""},"Web":{"Address":":8000","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":{"Prometheus":{"Buckets":[0.1,0.3,1.2,5]},"Datadog":null,"StatsD":null},"Path":"","Auth":null},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null} 
DEBU[2017-08-09T10:23:20+02:00] Configured Prometheus metrics                
INFO[2017-08-09T10:23:20+02:00] Preparing server http &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false} 
INFO[2017-08-09T10:23:20+02:00] Starting provider *file.Provider {"Watch":true,"Filename":"/Users/mjantke/work/go/src/github.com/marco-jantke/go-playground/sticky/traefik.toml","Constraints":null,"Trace":false,"Directory":""} 
INFO[2017-08-09T10:23:20+02:00] Starting provider *server.WebProvider {"Address":":8000","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":{"Prometheus":{"Buckets":[0.1,0.3,1.2,5]},"Datadog":null,"StatsD":null},"Path":"","Auth":null} 
INFO[2017-08-09T10:23:20+02:00] Starting server on :8080                     
DEBU[2017-08-09T10:23:20+02:00] Validation of load balancer method for backend backend1 failed: invalid load-balancing method ''. Using default method wrr. 
DEBU[2017-08-09T10:23:20+02:00] Configuration received from provider file: {"backends":{"backend1":{"servers":{"server1":{"url":"http://localhost:8081","weight":0},"server2":{"url":"http://localhost:8081","weight":0}},"loadBalancer":{"method":"wrr","sticky":true}}},"frontends":{"frontend1":{"entryPoints":["http"],"backend":"backend1","routes":{"test_1":{"rule":"Path:/ok"}},"priority":0,"basicAuth":null,"headers":{}}}} 
DEBU[2017-08-09T10:23:20+02:00] Last file config received more than 2s, OK   
DEBU[2017-08-09T10:23:20+02:00] Creating frontend frontend1                  
DEBU[2017-08-09T10:23:20+02:00] Wiring frontend frontend1 to entryPoint http 
DEBU[2017-08-09T10:23:20+02:00] Creating route test_1 Path:/ok               
DEBU[2017-08-09T10:23:20+02:00] Creating backend backend1                    
DEBU[2017-08-09T10:23:20+02:00] Creating load-balancer wrr                   
DEBU[2017-08-09T10:23:20+02:00] Sticky session with cookie _TRAEFIK_BACKEND_backend1 
DEBU[2017-08-09T10:23:20+02:00] Creating server server1 at http://localhost:8081 with weight 0 
DEBU[2017-08-09T10:23:20+02:00] Creating server server2 at http://localhost:8081 with weight 0 
DEBU[2017-08-09T10:23:20+02:00] Configured Prometheus metrics                
INFO[2017-08-09T10:23:20+02:00] Server configuration reloaded on :8080       
{"ClientAddr":"[::1]:59190","ClientHost":"::1","ClientPort":"59190","ClientUsername":"-","DownstreamContentSize":21,"DownstreamStatus":500,"DownstreamStatusLine":"500 Internal Server Error","Duration":136627,"Overhead":136627,"RequestAddr":"localhost:8080","RequestContentSize":0,"RequestCount":1,"RequestHost":"localhost","RequestLine":"GET /ok HTTP/1.1","RequestMethod":"GET","RequestPath":"/ok","RequestPort":"8080","RequestProtocol":"HTTP/1.1","StartLocal":"2017-08-09T10:23:21.343124269+02:00","StartUTC":"2017-08-09T08:23:21.343124269Z","level":"info","msg":"","request_Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","request_Accept-Encoding":"gzip, deflate, br","request_Accept-Language":"en-GB,en;q=0.8,en-US;q=0.6,de;q=0.4","request_Cache-Control":"max-age=0","request_Connection":"keep-alive","request_Upgrade-Insecure-Requests":"1","request_User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36","time":"2017-08-09T10:23:21+02:00"}
```

**Comment by tbouvet** [comment]
Same problem with version **1.4.0-rc3**

**Comment by marco-jantke** [comment]
@tbouvet which provider do you use?

I think we should tackle this problem probably not in avoiding the possibility to register two servers with the same address in the provider configuration, but rather define a behaviour what Traefik should in that case and adapt the code accordingly. 

@containous/traefik WDYT about this issue? In my opinion, nothing sounds wrong with having the same server URL a couple of times. I think we should find the flaw in the code avoiding this and fix this.

**Comment by tbouvet** [comment]
@marco-jantke I use consul_catalog. Your solution seems to be good. Maybe we can add a tag to choose what traefik should do when 2 servers use the same url.
In my configuration, different consul_agent are looking for the same external service. So only one server  is necessary in traefik

**Comment by marco-jantke** [comment]
I wouldn't add an extra flag or whatsoever. I would just expect that Traefik is forwarding correctly to both servers (even though they have the same URL). As I understand your scenario, this wouldn't be a problem for you as well. Please correct me if I am wrong.

**Comment by marco-jantke** [comment]
We should probably investigate whether the same Server URL is only making troubles when they are in the same Backend or if this is also problem over all Server URLs that Traefik knows about, independent of Backends/Frontends.

**Comment by tbouvet** [comment]
Ok.
In my real case, traefik is not forwarding to my backend when I have 2 times the same server url in one backend. If this "bug" is fixed, it will be ok for my case.

**Comment by Riduidel** [comment]
I also have this issue when accessing services are registered in a consul service registry cluster hosted on a separated rancher environment.

**Comment by aymericbeaumet** [comment]
I have this use-case where I plugged Traefik to a Consul Catalog. I manually register services in the Consul cluster.

I took the decision to only populate one of the servers (the leader in my case) to avoid duplicate entries. I should be doing the opposite and populate all the servers for redundancy.

I think this is a valid example why duplicate URLs should either be allowed in the configuration or be detected and print a warning to help people debug when this behavior is not expected.

I'm willing to PR this.

**Comment by aymericbeaumet** [comment]
After some digging, the bug actually comes from having several backends with the same weight (see [here](https://github.com/containous/traefik/blob/master/vendor/github.com/vulcand/oxy/roundrobin/rr.go#L164)).

In the meantime, I set unique weights (which are derived from the Consul servers ip addresses) through the Consul Catalog tags. This is how I achieve this in my Ansible role:

```
"traefik.backend.weight={{ ansible_default_ipv4.address | regex_replace('^.+\..+\.(.+)\.(.+)$', '999\g<1>999\g<2>') }}"
```

**Comment by nmengin** [comment]
Hello,

This issue targets an unsupported version of Traefik.
I close it.

We'll re-open it if necessary.
