### ISSUE TITLE
Feature Request (Marathon): Support refreshing DC/OS authentication token

### ISSUE THREAD

**Issue by mtweten** [traefik/traefik#1963]
### Do you want to request a *feature* or report a *bug*?
Feature

### Problem
Currently, traefik supports supplying a static DC/OS auth token via `dcosToken` in the configuration, which is supported by go-marathon. The problem is that the tokens generated by DC/OS eventually expire (I believe 5 days). 

It's possible to work around this by creating tokens with long expiry times, but that's more of a band aid (and they still eventually expire). It would be nice if traefik could support automatically refreshing the authentication token.

### Details
[Issue 292](https://github.com/gambol99/go-marathon/issues/292) was logged in go-marathon for this functionality. There is a proposal about making use of the http transport from [dcos-go](https://github.com/dcos/dcos-go) to create the HTTPClient that is passed to go-marathon, documented in my comment [here](https://github.com/gambol99/go-marathon/issues/292#issuecomment-315221013), but there are also some caveats that are discussed in that comment thread.

The discussion made it sound like the best place to use dcos-go for this functionality might not be in the go-marathon library itself, but in the consuming projects. Mainly, this is because dcos-go depends on the jwt-go library (currently 2.6.0). The consumer of go-marathon (in this case, traefik) would then be responsible for making the choice of using the dcos-go http transport and vendoring the correct dependencies to make it work.

I wanted to open the discussion here to see if this would be a desired feature in traefik, and if it makes sense to implement that functionality in traefik instead of go-marathon.

I do have a [working example](https://github.com/mtweten/traefik/commit/e6a1927821d20132dcb8029ff31d0cc373885ce2) of what utilizing the dcos-go http transport in traefik would look like.

**Comment by timoreimann** [comment]
For obvious reasons, I endorse the client-based approach. :-)

**Comment by rtribotte** [comment]
Hello,

In the upcoming major version of Traefik (v3), support for the Marathon provider is being dropped.
Due to this change, we won't be able to accept or work on new features related to the Marathon provider.
For this reason, we are closing this issue.
