### ISSUE TITLE
Running multiple traefik instances in a docker swarm cluster

### ISSUE THREAD

**Issue by muresan** [traefik/traefik#2009]
### Do you want to request a *feature* or report a *bug*?
It's a bug (multiple traefik instances interfere with eachother) that can be fixed with a new feature (set the LabelPrefix from a parameter)

### What did you do?
I am trying to deploy two traefik services on docker swarm that will be used by two different sets of applications.
An internal set and an external set. I'm creating an inthttp entryPoint in one and an exthttp entryPoint in the other.
Functionally it works but both dashboards show the exact same information, they both show inthttp and exthttp labels even though only one of the traefik instances has the entryPoint.
Because both instances look at labels, logs have errors that entryPoints are missing (normally).

My idea was to change the code to have prefixLabel as a command line parameter, then you could have two different traefik instances, each looking for different labels, not interfering with eachother, but it looks more complicated than I initially thought so I'm bringing this up to you

### What did you expect to see?
I expected to see each instance of traefik showing only the respective frontent and backend entries.

### What did you see instead?
I saw both instances have the exact same output wrt. frontend/backend entries.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.3.6
Codename:     raclette
Go version:   go1.8.3
Built:        2017-08-22_09:57:54AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# traefik_ext_config.toml 
[entryPoints]
  [entryPoints.exthttp]
  address = ":8080"
  [entryPoints.exthttps]
  address = ":8443"
```
```toml
# traefik_int_config.toml 
[entryPoints]
  [entryPoints.inthttp]
  address = ":80"
  [entryPoints.inthttps]
  address = ":443"
```
one service has
```
        traefik.docker.network: "lb_int_proxy"
        traefik.backend: "hw_int"
        traefik.frontend.rule: "Host:hw-int.test"
        traefik.frontend.entryPoints: inthttp
```
the other service has
```
        traefik.docker.network: "lb_ext_proxy"
        traefik.backend: "hw_ext"
        traefik.frontend.rule: "Host:hw-ext.test"
        traefik.frontend.entryPoints: exthttp
```
Here are all the files (docker swarm stacks, traefik config files) https://gist.github.com/muresan/f12aa7a19cdee7ce40a2f2bf7adf7162

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by SPodjasek** [comment]
I'm about to implement similar multiple træfik solution in single swarm and I'm curious - have you tried using [constraints](https://docs.traefik.io/configuration/commons/#constraints) to filter containers?

**Comment by gaui** [comment]
@SPodjasek Do you have any example? Not sure how this works. Does it filter based on tags on Docker services?

**Comment by johnharris85** [comment]
@SPodjasek I tried constraints and traefik picks them up (I see it pruning on them in the logs) however it prunes everything (incorrectly) for some reason. I think it's a separate bug (will edit this to link to it when I post it). I don't see anyway to implement multiple traefik instances in the same swarm right now, because of the reliance on non-namespaced service labels for the backends. The first instance always works fine, but the second instance always tries to send traffic to the first backend, leading to gateway errors / timeouts (they're on different Docker networks).

Interested on the official view on whether this is supported or not? Happy to dig into the code and attempt a PR (basically to just add a 'namespace' for each traefik instance.

**Comment by bitsofinfo** [comment]
We are seeing the same thing, two traefik instances on same swarm, docker.network is not filtering things, both instances are getting the same set of frontends generated. There needs to be some additional way of filtering the info that comes out of swarm so traefik can ignore some of those services not intended for it

**Comment by SPodjasek** [comment]
@bitsofinfo currently I've 4 traefik instances running in single swarm, every pick appropriate services to publish, generates only right frontends.
I use docker image `traefik:1.4-alpine`, and following constraint in config

```
constraints = ["tag==t3"]
```

**Comment by Gisleburt** [comment]
I think this is the same problem we've just noticed in out production kubernetes service. 

We've set up three namespaces:
- `public` stuff for everyone to see
- `internal` stuff we only want staff to see (protected with mutual auth via an intenalCA)
- `engineering` stuff only the devs should see (protected with mutual auth via an engineeringCA)

Unfortunately, we've discovered some (but not all) engineering endpoints can be accessed through the public ingress without requiring authentication (we've taken these down for now).

Looking more deeply into the situation we found the [kubernetes configuration] section of the documentation (which we hadn't needed up to now and clearly just missed 😁) suggests that the ingress will monitor all namespaces by default (worth mentioning kubernetes/kubernetes#17088 here as I think as they chose not to go down that path). So we've tried setting the namespaces array, but we still have the same problem.

We haven't tried label selectors yet, but would rather avoid it as it'll involve rewriting a lot of configs.

So:
- Is there a work around? 
- Is there anything a non-Go non-networking developer can do to help? 😃 

It definitely feels like a security issue, so would love to help get this solved asap.

[kubernetes configuration]: https://docs.traefik.io/configuration/backends/kubernetes/

**Comment by dtomcej** [comment]
@Gisleburt Your question is not really related to the docker swarm configuration, but here is the answer for you:

The kubernetes traefik options allow you to specify a namespace to watch. This is for operational clarity, not security.

If you are worried about security, you should be using the kubernetes RBAC to limit access, and then assign the role/clusterrole to your pods.

**Comment by Gisleburt** [comment]
OK, we got ours to work after much fiddling, so for anyone who comes here looking for the same thing

- Use a `RoleBinding` instead of a `ClusterRoleBinding` (make sure to remove old CRBs)
- Add to your config.toml
  ```toml
  [kubnernetes]
  namepaces = [ "your-namespace" ]
  ```
- Remove `--kubernetes` from args

**Comment by danieladams456** [comment]
I think #895 would be a good generic implementation for this?
