### ISSUE TITLE
Feature Request: Add inverse of storeconfig sub-command

### ISSUE THREAD

**Issue by micahhausler** [traefik/traefik#2137]
The `storeconfig` sub-command uploads a configuration toml (and any other referenced config files) into a K/V store. 

For the purposes of migrating K/V stores or backing up dynamic configuration data (like ACME certs) it would be really helpful to have a `retrieveconfig` or `fetchconfig` that would output the current configuration in a generic, backend-agnostic format.

**Comment by mmatur** [comment]
Hello,

This proposal is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
