### ISSUE TITLE
Encrypt Session Sticky cookie content

### ISSUE THREAD

**Issue by ammonlee01** [traefik/traefik#2299]
### Do you want to request a *feature* or report a *bug*?
request a feature

### What did you do?
I enabled session sticky under docker.

### What did you expect to see?

The Traefik session sticky cookie content to be encrypted text.

### What did you see instead?
The cookie currently shows the internal uri with internal container IP in clear text, which is a security risk if deployed in internet.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.4.0
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

**Comment by jan-rohan** [comment]
I vote for this feature too. I like traefic very much but without this it is'nt possible to use it. HAProxy do it by no ecryption but by configurable cookie value for the given server, it will be enough.

**Comment by ammonlee01** [comment]
Totally agree that  encryption is not a must. A unique lookup key will suffice and be efficient than handling encryption and decryption

**Comment by RubenN** [comment]
Yes please, a unique key will do, but it would be nice to be able to configure URI/ID (for debugging)

**Comment by Riduidel** [comment]
Feature is also needed by company security policy. Is there any work planned by containous wonderful team on this subject ? I would gladly have worked on it, but my go-fu is far from enough to be of any help.

**Comment by cocorossello** [comment]
I would like this as well. Having the internal URI in a cookie sent to a client does not look good.  Setting a cookie value per server like haproxy is the best and simplest option IMHO

**Comment by lucasvel** [comment]
> I'd love to not expose internal addresses to the public. Any plan on fixing this?

I hate to bump things like this, but we need this too because of a penetration test finding we are having.

**Comment by gheibia** [comment]
Yes, please.

**Comment by sriyer** [comment]
Are there any plans to implement this ?

@emilevauge @ldez has this been triaged yet ?

We use traefik 1.6.6 and we have vulnerability and security findings that need the cookie value encrypted / masked and not publish the actual IP address. We use the consul catalog provider.

cc @samart

**Comment by anantsaraswat** [comment]
Waiting for the update

**Comment by sriyer** [comment]
Are there any updates on this ?

**Comment by sriyer** [comment]
Cool, thanks for responding. Is there a plan on implementation?

**Comment by sriyer** [comment]
@dduportal looking further at the labels as you suggest, i see the priority set as P2 meaning in the future, if i'm not wrong. Would you be able to help get an answer to what the plan is on implementing this  and how soon? happy to help if need be.

**Comment by ReillyProcentive** [comment]
There will probably need to be an added field under cookies with a shared secret or key. This value would need to be the same on all Traefik instances that need to decrypt the cookie. To reduce the risk of an operator choosing a weak key the format of the key should be enforced and docs should show how to generate an appropriate value (as an example: `openssl ecparam -genkey -name prime256v1 | base64 -w 0`)

**Comment by dduportal** [comment]
Hello @sriyer, as Traefik v2.0 is currently being worked on (you can see the kanban board here: https://github.com/containous/traefik/projects/3 ), there are matters in the foundation of Traefik  being worked on that would block this issue: any attempt at planning and implementing this Sticky Session would change after 2.0. => Hence the priority/P2 which means will be worked after P1 :)

You should subscribe to this issue: as soon as someone will assign themselves here, it means discussion can start (or when the issue would appear in the v2 board).

Rest assured this will be done, but it's a matter of finishing requirements.

Thanks for your involvement!

**Comment by gheibia** [comment]
@dduportal I'd like to take a shot at this with a simple implementation (which I think someone else pointed out here, as well): Symmetric encryption of the cookie's value (backend URL) through a user provided key (e.g.: AES).
However, it appears that all of the sticky session functionality is handled by Oxy. We could add a configuration key to Traefik for a path to the key which will then have to be passed to Oxy. If no key is provided or the key file is missing (e.g.: misconfiguration) we fall back to the plain text cookie value with a warning in the logs.

Question is that is there a ticket in V2 that could overlap or conflict with this? Is anyone else is working on this?

**Comment by dduportal** [comment]
Hi @gheibia, 

The project board does not have (yet) a card for tracking this. However the discussion will soon start around the load-balancing implementation in Traefik v2.x. Such discussion could lead to breaking changes in the core, that would make any contribution on this topic wasted. Hence the priority (again) because no PR would be accepted (not for 1.7.x has no feature request should be done on this versions, only bugfixes, and not for 2.0 because of the priority).

I hope you understand this is only a transitioning phase, and that your contribution might well be welcomed after this "LB" discussion would have taken place.

Thanks for your patience!

**Comment by gheibia** [comment]
Thanks for the explanation. I wasn't aware that 1.7.x no longer accepts feature requests.

**Comment by philippreston** [comment]
Cookie value per server in the load-balance group (rather than encrypted) would be really useful/important .

**Comment by areThereAnyUserNamesLeft** [comment]
Hi @dduportal,
Thanks for your explanations above - I'm looking for an update on your comments from 11 Jun 2019 or directions as to the state of the discussion regarding load balancing which was blocking this issues. 

Any update would be awesome. Thank you

**Comment by dduportal** [comment]
Hi @areThereAnyUserNamesLeft , as I am not related to the project and not a maintainer, I cannot tell you more. It looks like that the aformentionned issue bout Load Balancing had been worked on and delivered in Traefik v2.x (x >= 1).

Ping @SantoDE ?

**Comment by areThereAnyUserNamesLeft** [comment]
Sorry and thank you, your answer from last year seemed so involved I
thought you were a maintainer.

**Comment by dduportal** [comment]
@areThereAnyUserNamesLeft you are right: I used to be but I changed jobs and backed off :)

**Comment by areThereAnyUserNamesLeft** [comment]
Hello @SantoDE - Is there any update on this? I couldn't find it on the kanban board or in the releases.

**Comment by SantoDE** [comment]
Hello @areThereAnyUserNamesLeft,

as mentioned on the Issue, it's a P2 so "will be done". Just out of now, I can't give you a full ETA. Sorry. When I have one, we'll share it here in the issue.

**Comment by sylr** [comment]
@emilevauge could you look at the PR I opened to fix that ? vulcand/oxy#203

**Comment by jbdoumenjou** [comment]
Hi @sylr,

In your PR on oxy, your changes are breaking due to the alteration of the cookie value.

Please add an option in oxy to enable/disable the hashing.

Thank you.

**Comment by jbdoumenjou** [comment]
Hi @sylr,

In your PR on oxy, your changes are breaking due to the changes made on the cookie value.
Could you add an option in oxy to enable/disable the hashing?

I would also suggest that adding a consistent hashing load balancing algorithm (https://github.com/containous/traefik
/issues/1139) could be a great workaround. If anyone is interested to work on this, we could definitely help :)

Thanks!

**Comment by sylr** [comment]
I improved the PR to honour old unhashed cookies.

However I fail to understand how consistent hashing and stickiness are related.

**Comment by jbdoumenjou** [comment]
Thanks for the modifications on your oxy PR.
We will try to take a look asap.

**Comment by pavelmarek77** [comment]
May I ask about any update & ETA when it can be available? One of our security audit also raised this concern about revealing private IPs.

**Comment by szwoelf** [comment]
Is this issue still planned for 2.5? Are there any news or known workarounds? Thx in advance.

**Comment by szwoelf** [comment]
Hey again. Is ther any chance that we can get this fixed. Can I try to work on this? (I'd doit if somebody supports me.)

**Comment by ReillyBrogan** [comment]
@szwoelf The Oxy library has an open [PR](https://github.com/vulcand/oxy/pull/203) about hashing the IP address (which is likely a sufficient resolution for most people). You can follow that PR for updates. I don't know the release timeline on 2.5 but I would assume this is not going to make it.

**Comment by szwoelf** [comment]
Thx for the reply. Then let's observe it there.

**Comment by yongzhang** [comment]
Hi, anyone knows if the issue is actually fixed or not?

**Comment by ReillyBrogan** [comment]
> Hi, anyone knows if the issue is actually fixed or not?

It's fixed in the sense that it will be part of the next major Traefik release. Support for this has been merged into the master branch.

**Comment by SantoDE** [comment]
Except that is the next `minor` release, not `major` :-)

**Comment by szwoelf** [comment]
@SantoDE but when?

**Comment by szwoelf** [comment]
As traefik has been released - but I cannot find the documentation - what (apart from upgrading to traefik 2.4.9) do I have to configure (in kubernetes) to force the sticky cookie to be hashed / encrypted. Thx in advance. I looked at the code of @tomMoulard ... but I didn't find options. Thx so much in advance.

**Comment by ldez** [comment]
`minor` not `patch` :wink: (`major.minor.path`)

**Comment by szwoelf** [comment]
Ooops.
