### ISSUE TITLE
CORS Error 404-502 : No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by w3blogfr** [traefik/traefik#2549]
### What did you do?

When I stop some backend application API (spring boot in my case)
Traefik has some delay to detect the service shutdown, and I have some 502 bad gateway.

For page 404 and 502, we cannot customize security headers. In last traefik version, we can only override headers when the backend service is ok.

So I have this issue in my browser. No 'Access-Control-Allow-Origin' header is present on the requested resource
Due to that, I cannot catch the 502 error in javascript, and I cannot properly catch the exception

I have this issue with eureka as Provider but I think this issue is commons to all provider. Just more frequent with Eureka because there a bigger delay before to detect backend shudown.

### What did you expect to see?

I expected security headers CORS work for 404 and 502 error page.
Or something similar to override it for error pages

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I used 1.4.2 roquefort.

I made some try with new new version 1.5.x and security headers, but not works.

Thanks

**Comment by w3blogfr** [comment]
Any chance to have custom headers for error pages in next 1.6?

Thks.

**Comment by ldez** [comment]
Yes see #2584 😉

**Comment by gerwim** [comment]
Is there any update on this? I'm having the same issue: when stopping one of my backends (using sticky sessions) for an upgrade replacement.

**Comment by gp187** [comment]
Same. Still an active bug

**Comment by dougg0k** [comment]
Yes, same issue with Traefik 2.2

**Comment by ssikyou** [comment]
Same issue for Traefik 2.2, any update?

**Comment by ldez** [comment]
Have to try with the latest version: v2.3.0

**Comment by ssikyou** [comment]
Just tested with v2.3.0, it works now for me, thanks!

**Comment by ldez** [comment]
Fixed by #7230
