### ISSUE TITLE
Traefik is not retrying the ACME caserver connection upon failure 

### ISSUE THREAD

**Issue by igoratencompass** [traefik/traefik#2670]
### Do you want to request a *feature* or report a *bug*?
I would say both, a *feature* and a *bug*

### What did you expect to see?
If the connection failed for some reason I would expect the Traefik pod that has the ACME lock in the backend KV store, Kubernetes etcd in my case, to retry after some configurable time interval.

### What did you see instead?
That is not happening.

### Output of `traefik version`: (_What version of Traefik are you using?_)

v1.5.0-rc4

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Traefik with etcd backend in Kubernetes.

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
 (paste your output here)
```

**Comment by alex88** [comment]
Same here using 1.7.5, acme failed due a 500 in the challenge response and traefik never tried again, after a restart everything worked

**Comment by costela** [comment]
FYI: I'm also seeing the same behavior on 1.7.5 and I'm not using KV (using json on an EBS volume; single instance), so the issue label might be misleading for anyone trying to debug this a bit further.

**Comment by hjacobs** [comment]
The behavior is pretty bad IMHO for my case: there is a major race condition between Traefik ACME and the actual server startup (Kubernetes ingress). I repeatedly try to get my cert issued and got as far as 3/4 certs (hostnames), now trying to get 4/4 by killing the Traefik pod and checking logs :disappointed: 

My Traefik config: https://codeberg.org/hjacobs/k3s-demo/src/branch/master/manifests/traefik-config.yaml

Some option to delay the cert creation (wait X seconds) would also already help.

**Comment by hjacobs** [comment]
How I fixed this in my case: I edited the Ingress YAML, changed the hostname to something invalid (like `xxx.de`), and then changed it back to the right one. 

Result: Traefik detected the change and issued the cert (`onHostRule = true`) and no race-condition this time (as the server is already running).

**Comment by costela** [comment]
@hjacobs just to complement: a similar race condition might also happen between the ingress and its DNS entry, if it's also being managed by k8s (via something like cloud provider integration or [external-dns](https://github.com/kubernetes-incubator/external-dns)).

 The [`onDemand`](https://docs.traefik.io/v1.7/configuration/acme/#ondemand-deprecated) option (deprecated in 1.7.*; dropped in 2.*) seems to help in this case. Would be nice if it was "revived". Couldn't find a rationale for its removal.

**Comment by hjacobs** [comment]
Write-up of my Traefik/ACME problem I mentioned above: https://srcco.de/posts/k3s-outage-traefik-acme-lets-encrypt-local-path.html

**Comment by AndreKR** [comment]
Unless I'm missing something, this, together with the fact that Traefik does not wait for its port forwarding to be up, makes it impossible to use the dashboard, as configured by the Helm chart.

Traefik tries to acquire the certificate for the dashboard domain immediately after start, when the port forwarding is not yet up, and then never retries it.

**Comment by mmatur** [comment]
Hello,

This bug is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
