### ISSUE TITLE
ACME certificates not always created in cluster mode with onHost option.

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#2761]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

* Configure Træfik to use a KV store (Consul) to save both its configuration and ACME certificates
* Start Swarm services to expose
* Start Swarm service with Traefik (one or many instances)

### What did you expect to see?

ACME certificates generated into the KV store.

### What did you see instead?

Sometimes, certificates are not generated.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.5

### Analyzis

When Træfik starts in cluster mode, all the instances start as a worker.
A worker cannot do ACME challenges and generate ACME certificates.
If frontend are detected by Træfik **before** the leader election, the certificates will not be generated as long as a new frontend is detected.

**Comment by dtomcej** [comment]
Do you think in this case, if traefik is a worker, we could have it check to make sure there is a leader as a blocking operation before processing the frontend?

**Comment by nmengin** [comment]
@dtomcej It's a solution, we can force the certificate generation for all hosts when the leadership changes too.

This issue needs more investigations.

**Comment by mmatur** [comment]
Hello,

This bug is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
