### ISSUE TITLE
Rancher 2.0 API (v3) Support

### ISSUE THREAD

**Issue by zchef2k** [traefik/traefik#3283]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Rancher 2.0 has reached GA. Please add support for Rancher backends using their updated API (v3).

_My apologies to any rabbits negatively affected by my oversight._

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik!

Please edit your issue and use the [provided template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md).

Issue templates help us help you by providing all necessary information.

Here are the available templates:

- [Standard issue](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md)
- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/features.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/bugs.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by EduardoRT** [comment]
Any updates on this?

**Comment by ldez** [comment]
ping @SantoDE

**Comment by jjscarafia** [comment]
Why rancher 2.0 api If rancher 2.0 is k8s and k8s is already supported by rancher?
I'm loosing something?

**Comment by EduardoRT** [comment]
Yeah, I guess I can just use the K8s backend as normal.

**Comment by SantoDE** [comment]
Hey guys, 

just in case you missed it: https://twitter.com/lemonjet/status/1012470623166009344?s=21

Rancher is going to support traefik natively by using the K8s backend. I started working on supporting api v3 but it doesnt really make sense anymore :)

**Comment by MichelDiz** [comment]
That's what I'm looking for too.

**Comment by rtribotte** [comment]
Hello,

In the upcoming major version of Traefik (v3), support for the Rancher provider is being dropped.
Due to this change, we won't be able to accept or work on new features related to the Rancher provider.
For this reason, we are closing this issue.
