### ISSUE TITLE
Custom error pages and original request URL

### ISSUE THREAD

**Issue by kachkaev** [traefik/traefik#3420]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I have a frontend written with [Next.js](https://github.com/zeit/next.js/), which contains quite a lot of images and also renders some react stuff on the server. Requests to images can make the Node.js process slower, so I'm thinking of serving them via an nginx container, which is configured to respond to only a folder with images (traefik's `pathPrefix`).

Requests to the folder with images can be combined with a 404 message rendered by Next.js, thanks to the [custom error pages](https://docs.traefik.io/configuration/commons/#custom-error-pages) feature. There is one scenario I cannot get working though:

When nginx returns 404, traefik knocks the Node.js container, but does not pass the original request URL anywhere in the headers. Without this, it is impossible to implement a redirect to a correct image:

```
user
↓ /images/products/PRODUCT_ID-wrong-slug.jpg
traefik
↓
nginx
↓ 404
traefik
↓ /images/products/PRODUCT_ID-wrong-slug.jpg
nodejs
↓ redirect to /images/products/PRODUCT_ID-correct-slug.jpg
traefik
↓
user
```

It'd be great if in addition to `{status}`, it was possible to use `{path}` or `{url}` in `traefik.frontend.errors.XYZ.query`. My nginx container would be configured like this

```
traefik.frontend.errors.all.backend=nextjs
traefik.frontend.errors.all.status=400-599
traefik.frontend.errors.all.query={path}
```
or
```
traefik.frontend.errors.all.query=/custom-error?url={url}
```

(the latter is useful if a website is multilingual and is available at several domain names)

WDYT?

**Comment by KyleWiering** [comment]
I'm not quite familiar enough with golang to run this locally and test a change.
Essentially, the following pseudo code would need to be implemented in the errorpages code.  It'd be great in v1.8 ;) 

if len(h.backendQuery) > 0 {
  query = "/" + strings.TrimPrefix(h.backendQuery, "/") 
  query = strings.Replace(query, "{status}", strconv.Itoa(recorder.GetCode()), -1)
  query = strings.Replace(query, "{path}", recorder.GetUrl() // the trailing end of the path without the domain.
}

**Comment by wilalalee** [comment]
i think we need a global error page. 
Since i have many context rules, i don't like to set this configuration for each rule.
