### ISSUE TITLE
support in docker property backend.loadbalancer.stickiness in segment labels

### ISSUE THREAD

**Issue by migueltercero** [traefik/traefik#3507]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We have containers with multiple ports and some ports require sticky sessions. In official documentation we can see that is posible define backend.loadbalancer.stickiness property, but this property can´t be defined in segment labels. 

Thank you.

**Comment by ldez** [comment]
The backend labels `traefik.backend.xxx` are applied to all segments.

Example:
```
traefik.backend.loadbalancer.stickiness=true
traefik.foo.frontend.rule=Host:foo.com
traefik.bar.frontend.rule=Host:bar.com
```

is the pseudo equivalent to:
```
# foo
traefik.backend.loadbalancer.stickiness=true
traefik.frontend.rule=Host:foo.com
```

```
# bar
traefik.backend.loadbalancer.stickiness=true
traefik.frontend.rule=Host:bar.com
```

**Comment by migueltercero** [comment]
We need something like this:

# foo
traefik.backend.loadbalancer.stickiness=true
traefik.frontend.rule=Host:foo.com
# bar
traefik.backend.loadbalancer.stickiness=false
traefik.frontend.rule=Host:bar.com

Is posible?

Retarda.

**Comment by ldez** [comment]
Yes, it's possible:

```yml
traefik.foo.frontend.rule=Host:foo.com
traefik.foo.backend.loadbalancer.stickiness=true # <---
traefik.bar.frontend.rule=Host:bar.com
```

**Comment by migueltercero** [comment]
We tested your solution in this compose:

> version: '3'
services:
  traefik:
    image: traefik:1.6.4-alpine
    command: 
      --web 
      --docker 
      --docker.domain=dev.local 
      --docker.watch 
      --docker.exposedbydefault=false
      --entryPoints='Name:http Address::80' 
      --defaultEntryPoints='http'
    ports:
      - "10000:80"
      - "10001:443"
      - "10002:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: billsb/alpine-python-whoami
    labels:
      - "traefik.enable=true"
      - "traefik.foo.frontend.rule=Host:foo.com"
      - "traefik.foo.backend.loadbalancer.stickiness=true" # <---
      - "traefik.bar.frontend.rule=Host:bar.com"

In console, both backends seems equals (i can´t see stickiness configuration):

![image](https://user-images.githubusercontent.com/20397404/41530598-fa6a59da-72f0-11e8-9f9f-7d21f33e2a54.png)

Whats is wrong?

Regards.

**Comment by goodwillhacking** [comment]
+1

**Comment by jbdoumenjou** [comment]
As Traefik v1 is in maintenance mode (we do not add new features) and Traefik V2 allows to define services with sticky configuration in docker label, I close this issue accordingly.
Feel free to re-open if I missed something. :smiley:
