### ISSUE TITLE
Add support for Consul Connect enabled services

### ISSUE THREAD

**Issue by artyomturkin** [traefik/traefik#3544]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
Allow dynamic exposure of Connect enabled services (with proxy or native) to clients that do not or can not support Connect themselves.

As it is should be the best practice to set wildcard intention to deny, exposed services can be sourced from intents that allow traefik to connect to a specific service. Additional meta data can be then discovered as usual.

**Comment by ForsakenHarmony** [comment]
I'd love to see this, how are the chances that this is gonna be in 1.8?

**Comment by DWSR** [comment]
This solves a huge gap in the use case of Traefik for me, especially on top of Kubernetes.

**Comment by Dudesons** [comment]
Hi @emilevauge ,

can we have more detail about this feature request ?
Do you think it will be treated, if yes do you have en ETA ?
Can we help you ?

**Comment by Legogris** [comment]
In lack of progress on this, is there at least any pointers on how to connect to Consul Connect services with traefik - or is this simply not supported today?

I seem to have to choose between exposing ports to internal services vs traefik, no way to get them both working at the same time.

**Comment by iahim** [comment]
That would be an awesome option...

**Comment by Legogris** [comment]
Depending on your requirements, you might be OK with using an separate load balancer requirement that you use for internal services. This works great for me.

Note that it's a compromise as it likely adds some latency and has a point-of-failure in the load balancers (you can of course do an HA deployment, but it's still not the same as a service mesh).

**Comment by Angelmmiguel** [comment]
+1 to this! :)

**Comment by tomMoulard** [comment]
Closed by #7407
