### ISSUE TITLE
Bug with Overlapping TLS Certs and Ingress TLS Certs when both have SAN `example.com`

### ISSUE THREAD

**Issue by drubin** [traefik/traefik#3668]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
When I configure a k8s ingress rule with an expect certificate traefik still tries to find the best certificate based on which matches more closely. See https://github.com/containous/traefik/issues/3293 and https://github.com/containous/traefik/pull/3512

The certificates are in the format of `*.example.com,example.com` and `www.example.com,example.com` this is because when you apply for a certificate for `www.example.com` the cert providers generally throw in the root domain too.

### What did you expect to see?

I expected to see my `example.com,www.example.com` EV cert to be used on my ingress rule instead of the wild card cert `example.com,*.example.com` is served.

It would be great if https://github.com/containous/traefik/pull/3512 to be more realworld like where even the `*.example.com` certs include a SAN for `example.com` as if it was issued by a paid for provider.

### What did you see instead?

Traefik will service the `example.com,*.example.com` because of both matching `example.com`

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.7.0-rc2

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

traefik-cert = `*.example.com,example.com`
homepage-cert = `www.example.com,example.com`

```yaml
spec:
  tls:
  - secretName: homepage-cert
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: homepage
          servicePort: http
```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

na

Thanks to @dtomcej for help in Slack with this issue and figuring out the cause.

**Comment by nmengin** [comment]
Hello @drubin,

This issue targets Traefik v1 which is not maintained anymore.
I close the issue accordingly.

Please re-open it if needed.
