### ISSUE TITLE
Cloud Native / Kubernetes way to upgrade Installations

### ISSUE THREAD

**Issue by alwinmarkcf** [traefik/traefik#3873]
This is one of many Feature Requests to make Traefik on a production level Kubernetes compatible and to be able to work on https://github.com/helm/charts/issues/7172.

This Feature Request came up in: https://github.com/containous/traefik/pull/3776#issuecomment-414998241

### Do you want to request a *feature* or report a *bug*?

Feature

#### simple upgrade

```gherkin
Given a proper values.yaml for HA mode
And traefik is installed via helm in HA mode
When I change some parameter in the values.yaml
Then these changes should take effect
```

For this one, I'd love to see what's discussed here: https://github.com/containous/traefik/issues/3754
Tl;dr:
* Keep configs in TOML and only store states other than configs in KV Store (Like ACME Certs). 
* make Traefik start with empty kv set and generate them on the fly

#### Idempotent upgrade

```gherkin
Given a proper values.yaml for HA mode
And traefik is installed via helm in HA mode
When I change some parameter in the values.yaml
And I install on a different cluster traefik with the same values.yaml from scratch
Then both traefik server should behave the same
```

Would be fixed when only the config file would be considered. The Problem here currently is that storeconfig does not clean Keys, so you have legacy key/values which you only can clean manually. Thats a huge Problem. Eg for: 
* `traefik/acme/domains`
* Redirects (in the Helm Chart called ssl enforcement)
* many more, these are only the one I had to clean manually the last 2 weeks.

**Comment by alwinmarkcf** [comment]
I'd love to discuss how we can proceed with this one. We are now running traefik in a custom flavored version now half a year in production and since this issue isn't tackled upgrades always feels clumsy as I have to check etcd cluster and acme certs every time.

**Comment by mmatur** [comment]
Hello,

This enhancement is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
