### ISSUE TITLE
Consul Catalog should split backends in different frontends if their tags traefik are different

### ISSUE THREAD

**Issue by mildred** [traefik/traefik#3882]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to enable Canary deployment using Nomad, Consul and Traefik. Canary deployment allows to deploy some instances of a new version of a service without disrupting all the running instances. When the new version is tested, it is promoted to replace the old version.

Nomad, the hashicorp scheduler, implements it by setting [different consul tags](https://www.nomadproject.io/docs/job-specification/service.html#canary_tags) on canary and non canary server instances. Both canary and non canary instances share the same consul service name in the consul catalog, and Nomad does not allow a different service name for canaries and non canaries. This might not be the Consul way to do things.

With canary deployed, the consul catalog looks like this:

<details><summary>for the list of services</summary>

```console
$ curl -sv http://localhost:8500/v1/catalog/services | jq
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/catalog/services HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.61.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 12 Sep 2018 08:18:54 GMT
< Vary: Accept-Encoding
< X-Consul-Effective-Consistency: leader
< X-Consul-Index: 1033
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Content-Length: 243
< Connection: keep-alive
< 
{ [243 bytes data]
* Connection #0 to host localhost left intact
{
  "canary": [
    "traefik.frontend.rule=PathPrefix:/",
    "traefik.enable=true",
    "traefik.frontend.rule=PathPrefixStrip:/canary/",
    "external"
  ],
  "canary-int": [
    "internal"
  ],
  "consul": [],
  "nomad": [
    "http",
    "rpc",
    "serf"
  ],
  "nomad-client": [
    "http"
  ],
  "vault": [
    "standby"
  ]
}
```

</details>

<details><summary>for the details of a service</summary>

```console
$ curl -sv http://localhost:8500/v1/catalog/service/canary | jq
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/catalog/service/canary HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.61.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 12 Sep 2018 08:19:19 GMT
< Vary: Accept-Encoding
< X-Consul-Effective-Consistency: leader
< X-Consul-Index: 1045
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Content-Length: 3707
< Connection: keep-alive
< 
{ [3707 bytes data]
* Connection #0 to host localhost left intact
[
  {
    "ID": "11ad3157-3800-aa8f-f80b-432e7108e8d2",
    "Node": "ip-10-0-30-186",
    "Address": "10.0.30.186",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "10.0.30.186",
      "wan": "10.0.30.186"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-gi3mcagiasxo3wfnadkongwxrzeuufg6",
    "ServiceName": "canary",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.frontend.rule=PathPrefixStrip:/canary/",
      "external"
    ],
    "ServiceAddress": "10.0.30.186",
    "ServiceMeta": {},
    "ServicePort": 21087,
    "ServiceEnableTagOverride": false,
    "ServiceProxyDestination": "",
    "ServiceConnect": {
      "Native": false,
      "Proxy": null
    },
    "CreateIndex": 1025,
    "ModifyIndex": 1025
  },
  {
    "ID": "11ad3157-3800-aa8f-f80b-432e7108e8d2",
    "Node": "ip-10-0-30-186",
    "Address": "10.0.30.186",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "10.0.30.186",
      "wan": "10.0.30.186"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-ndnbblp4ih32qd3bd7mnuuudlp2kwihf",
    "ServiceName": "canary",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.frontend.rule=PathPrefix:/",
      "external"
    ],
    "ServiceAddress": "10.0.30.186",
    "ServiceMeta": {},
    "ServicePort": 23778,
    "ServiceEnableTagOverride": false,
    "ServiceProxyDestination": "",
    "ServiceConnect": {
      "Native": false,
      "Proxy": null
    },
    "CreateIndex": 982,
    "ModifyIndex": 982
  },
  {
    "ID": "a2f334ce-eda1-c114-9195-0af8a2b4e5f8",
    "Node": "ip-10-0-42-126",
    "Address": "10.0.42.126",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "10.0.42.126",
      "wan": "10.0.42.126"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-5xdjpu2f4aysp4734oair5mclft7jz5b",
    "ServiceName": "canary",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.frontend.rule=PathPrefix:/",
      "external"
    ],
    "ServiceAddress": "10.0.42.126",
    "ServiceMeta": {},
    "ServicePort": 21167,
    "ServiceEnableTagOverride": false,
    "ServiceProxyDestination": "",
    "ServiceConnect": {
      "Native": false,
      "Proxy": null
    },
    "CreateIndex": 1000,
    "ModifyIndex": 1000
  },
  {
    "ID": "a2f334ce-eda1-c114-9195-0af8a2b4e5f8",
    "Node": "ip-10-0-42-126",
    "Address": "10.0.42.126",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "10.0.42.126",
      "wan": "10.0.42.126"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-jfogg53j4yi3pn6vidsuwi2eig6zx6ra",
    "ServiceName": "canary",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.frontend.rule=PathPrefix:/",
      "external"
    ],
    "ServiceAddress": "10.0.42.126",
    "ServiceMeta": {},
    "ServicePort": 21356,
    "ServiceEnableTagOverride": false,
    "ServiceProxyDestination": "",
    "ServiceConnect": {
      "Native": false,
      "Proxy": null
    },
    "CreateIndex": 984,
    "ModifyIndex": 984
  },
  {
    "ID": "e56ca08b-851f-2b63-ea9f-da4742f3d476",
    "Node": "ip-10-0-9-185",
    "Address": "10.0.9.185",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "10.0.9.185",
      "wan": "10.0.9.185"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-nk5hkzxoavc54y3tiv5e7a7ngn33crnu",
    "ServiceName": "canary",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.frontend.rule=PathPrefixStrip:/canary/",
      "external"
    ],
    "ServiceAddress": "10.0.9.185",
    "ServiceMeta": {},
    "ServicePort": 24390,
    "ServiceEnableTagOverride": false,
    "ServiceProxyDestination": "",
    "ServiceConnect": {
      "Native": false,
      "Proxy": null
    },
    "CreateIndex": 1033,
    "ModifyIndex": 1033
  },
  {
    "ID": "e56ca08b-851f-2b63-ea9f-da4742f3d476",
    "Node": "ip-10-0-9-185",
    "Address": "10.0.9.185",
    "Datacenter": "dc1",
    "TaggedAddresses": {
      "lan": "10.0.9.185",
      "wan": "10.0.9.185"
    },
    "NodeMeta": {
      "consul-network-segment": ""
    },
    "ServiceKind": "",
    "ServiceID": "_nomad-task-w34dbtuoxcjm4w4v23vbi3ja7uhszyx7",
    "ServiceName": "canary",
    "ServiceTags": [
      "traefik.enable=true",
      "traefik.frontend.rule=PathPrefixStrip:/canary/",
      "external"
    ],
    "ServiceAddress": "10.0.9.185",
    "ServiceMeta": {},
    "ServicePort": 21291,
    "ServiceEnableTagOverride": false,
    "ServiceProxyDestination": "",
    "ServiceConnect": {
      "Native": false,
      "Proxy": null
    },
    "CreateIndex": 1028,
    "ModifyIndex": 1028
  }
]
```

</details>

### What did you see?

When Traefik sees this, it generates a single backend for the consul service, with all the server instances contained in it. `level=debug msg="Configuration received from provider consul_catalog:`

```json
{
  "backends": {
    "backend-canary": {
      "servers": {
        "canary-0-0k81bnd6-NFzuZxR28gGaVtdtfg": {
          "url": "http://10.0.30.186:21087",
          "weight": 1
        },
        "canary-1-3XaFFPZ7QFV4I3Lu9uCETonW-RU": {
          "url": "http://10.0.30.186:23778",
          "weight": 1
        },
        "canary-2-l3Qq03XSPb8Q4wuxMM9HAMGjM6o": {
          "url": "http://10.0.42.126:21167",
          "weight": 1
        },
        "canary-3-oYumyPNaqo7uXqxzeBxYWWxLLmU": {
          "url": "http://10.0.42.126:21356",
          "weight": 1
        },
        "canary-4-U88UkG6UP2qQM5vshwXRDp07BmM": {
          "url": "http://10.0.9.185:21291",
          "weight": 1
        },
        "canary-5-ZhLBVZ5NXcZNicF-FFnbYGXRrdU": {
          "url": "http://10.0.9.185:24390",
          "weight": 1
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    }
  },
  "frontends": {
    "frontend-canary": {
      "entryPoints": [
        "http",
        "https"
      ],
      "backend": "backend-canary",
      "routes": {
        "route-host-canary": {
          "rule": "PathPrefix:/"
        }
      },
      "passHostHeader": true,
      "priority": 0,
      "basicAuth": []
    }
  }
}
```

### What did you expect to see instead?

I would have wanted to see traefik split the different servers in two separate backends because there is clearly two sets of server instances declared in consul when looking at tags. I wanted to see:

```json
{
  "backends": {
    "backend-canary-0": {
      "servers": {
        "canary-1-3XaFFPZ7QFV4I3Lu9uCETonW-RU": {
          "url": "http://10.0.30.186:23778",
          "weight": 1
        },
        "canary-2-l3Qq03XSPb8Q4wuxMM9HAMGjM6o": {
          "url": "http://10.0.42.126:21167",
          "weight": 1
        },
        "canary-3-oYumyPNaqo7uXqxzeBxYWWxLLmU": {
          "url": "http://10.0.42.126:21356",
          "weight": 1
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    },
    "backend-canary-1": {
      "servers": {
        "canary-0-0k81bnd6-NFzuZxR28gGaVtdtfg": {
          "url": "http://10.0.30.186:21087",
          "weight": 1
        },
        "canary-4-U88UkG6UP2qQM5vshwXRDp07BmM": {
          "url": "http://10.0.9.185:21291",
          "weight": 1
        },
        "canary-5-ZhLBVZ5NXcZNicF-FFnbYGXRrdU": {
          "url": "http://10.0.9.185:24390",
          "weight": 1
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    }
  },
  "frontends": {
    "frontend-canary-0": {
      "entryPoints": [
        "http",
        "https"
      ],
      "backend": "backend-canary-0",
      "routes": {
        "route-host-canary": {
          "rule": "PathPrefix:/"
        }
      },
      "passHostHeader": true,
      "priority": 0,
      "basicAuth": []
    },
    "frontend-canary-1": {
      "entryPoints": [
        "http",
        "https"
      ],
      "backend": "backend-canary-1",
      "routes": {
        "route-host-canary": {
          "rule": "PathPrefix:/canary/"
        }
      },
      "passHostHeader": true,
      "priority": 0,
      "basicAuth": []
    }
  }
}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.6.6
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-08-20_01:10:06PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Traefik running without containerization on a CoreOS host running a consul agent on localhost:

```toml
defaultEntryPoints = ["http", "https"]

[lifeCycle]
  requestAcceptGraceTimeout = "10s"

[entryPoints]

  [entryPoints.traefik]
    address = ":8079"

  [entryPoints.https]
    # unused as of now
    address = ":443"
    [entryPoints.https.tls]

  [entryPoints.http]
    address = ":80"

[ping]
  entryPoint = "traefik"

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"

[consulCatalog]
  endpoint = "127.0.0.1:8500"
  exposedByDefault = false

```

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

The most important log message is `Configuration received from provider consul_catalog` whith its JSON payload reformatted above.

<details><pre>
...
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="List of services changed"
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Fetching service" service=nomad
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Filtering disabled Consul service nomad"
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Fetching service" service=nomad-client
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Filtering disabled Consul service nomad-client"
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Fetching service" service=vault
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Fetching service" service=canary
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Fetching service" service=canary-int
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Filtering disabled Consul service canary-int"
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Fetching service" service=consul
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Filtering disabled Consul service consul"
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Backend backend-canary: no load-balancer defined, fallback to 'wrr' method"
Sep 12 08:14:55 ip-10-0-9-185 traefik[2579]: time="2018-09-12T08:14:55Z" level=debug msg="Configuration received from provider consul_catalog: {\"backends\":{\"backend-canary\":{\"servers\":{\"canary-0-0k81bnd6-NFzuZxR28gGaVtdtfg\":{\"url\":\"http://10.0.30.186:21087\",\"weight\":1},\"canary-1-3XaFFPZ7QFV4I3Lu9uCETonW-RU\":{\"url\":\"http://10.0.30.186:23778\",\"weight\":1},\"canary-2-l3Qq03XSPb8Q4wuxMM9HAMGjM6o\":{\"url\":\"http://10.0.42.126:21167\",\"weight\":1},\"canary-3-oYumyPNaqo7uXqxzeBxYWWxLLmU\":{\"url\":\"http://10.0.42.126:21356\",\"weight\":1},\"canary-4-U88UkG6UP2qQM5vshwXRDp07BmM\":{\"url\":\"http://10.0.9.185:21291\",\"weight\":1},\"canary-5-ZhLBVZ5NXcZNicF-FFnbYGXRrdU\":{\"url\":\"http://10.0.9.185:24390\",\"weight\":1}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"frontend-canary\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"backend-canary\",\"routes\":{\"route-host-canary\":{\"rule\":\"PathPrefix:/\"}},\"passHostHeader\":true,\"priority\":0,\"basicAuth\":[]}}}"
...
</pre></details>

**Comment by mildred** [comment]
Perhaps the easiest way to group nodes together is to introduce a consul tag `traefik.service.group` that can be used to group nodes within a single Consul service.

**Comment by mildred** [comment]
`healthyNodes()` in [provider/consulcatalog/consul_catalog.go](https://github.com/containous/traefik/blob/bd4846aa9cf3b59a02748b01d3b16a083594845b/provider/consulcatalog/consul_catalog.go#L490) would need to return more than one `catalogUpdate`. Given a list of nodes in a consul service, it should return nodes grouped by identical tags.

**Comment by eigengrau** [comment]
Is @mildred’s commit something that could go into a release? As far as I can see there is no way to use Nomad’s blue/green deployments (via `canary_tags`) behind a Traefik instance currently?

Is there a work-around you can recommend? The only option I can come up with would involve tagging the Nomad job version number into the service name, but this is probably impractical for services that may be referenced outside of the Nomad job they are defined in.

**Comment by mildred** [comment]
Last news I had, providers are being moved to a new architecture, ans thé consul provider needs to ne portes over before this can be merged

**Comment by jcomeaux** [comment]
@mildred Not sure if this would work for you, but we include version info in the service name and then have a higher `traefik.frontend.priority` on the canary tags.

e.g.:

```
........snip........
          "Services": [
            {
              "Id": "",
              "Name": "nginx-prod-us-${NOMAD_ALLOC_INDEX}-${NOMAD_META_VERSION}",
              "Tags": [
                "traefik.enable=true",
                "traefik.tags=api",
........snip........
```

**Comment by scalp42** [comment]
@jcomeaux we're using Fabio and it's handled "natively" with `canary_tags` with the idea that the update of the service with `canary` enabled will simply have a different route `myservice-canary` for example.



Once promoted, that route disappears as Nomad will use the `tags` defined instead of `canary_tags`.

Still not sure how to roll this out with Traefik especially with things like `auto_revert` if the task fails to be healthy.

**Comment by scalp42** [comment]
@juliens je viens de tester et on ne peut pas separer les backends, donc impossible de canary avec Consul 🌵

**Comment by m1keil** [comment]
For anyone checking this in 2021, this is still the case. A workaround is possible and it's well described in [Andy Dote's blog post](https://andydote.co.uk/2019/06/23/nomad-traefik-canary/).

In case this content ever taken offline, here's a brief sample a config that will work:

```
      service {
        name = "whoami"
        tags = [
          "edge.enable=true",
          "edge.http.routers.whoami.rule=Host(`whoami.example.com`)",
        ]
        canary_tags = ["dummy"]
      }

      service {
        name = "whoami-canary"
        tags = []
        canary_tags = [
          "edge.enable=true",
          "edge.http.routers.whoami_canary.rule=Query(`__canary=1`) && Host(`whoami.example.com`)",
        ]
      }
```
Basically, the idea is to split the service into two, which prevents Traefik from registering the new canary tasks as a backend server to the "current" stack.
Note that unlike in Andy's blog, `canary_tags = ["dummy"]` was used in the first service definition or else the stack would flap between `enabled=true` and `enabled=false`.

**Comment by breathe** [comment]
> Perhaps the easiest way to group nodes together is to introduce a consul tag traefik.service.group that can be used to group nodes within a single Consul service.

The current state is really sub-optimal ...  Are there any plans to fix this with something like the above?  It should be possible to define a parameter in consul that will persuade traefik to group a set of instances of the same service into 'a different service' from traefik's perspective -- so that routing policy may be defined to treat 'groups of services' differently ...

**Comment by ddtmachado** [comment]
Hey everyone, 

I'm going to close this issue as support for Traefik v1 was [dropped already](https://doc.traefik.io/traefik/deprecation/releases/) so we won't be working on a fix for that branch. plus there is good workaround already described [here](https://github.com/traefik/traefik/issues/3882#issuecomment-957133658).

If you believe something is still missing on the v2 implementation of Consul Catalog please don't hesitate to open a new one.

**Comment by breathe** [comment]
This is still an issue in v2 -- I will open another ticket
