### ISSUE TITLE
traefik with rancher not putting containers back after upgrade

### ISSUE THREAD

**Issue by phynias** [traefik/traefik#3916]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
i am running traefik with rancher 1.6.17 i have tried traefik 1.6.5 and 1.6.6 with same results.
when i set a new service with the labels to get into traefik everything works fine. but when i upgrade it after the upgrade is complete the traefik backend is red with no containers in it. it does not put the container back in until i click "Finish Upgrade".

### What did you expect to see?
when i upgrade a service when the new containers come up they should join the backend in traefik.
and i should be able to leave the old container there in case i need to rollback.

### What did you see instead?
the backend does not work until i click "finish upgrade" in rancher.

### Output of `traefik version`: (_What version of Traefik are you using?_)
1.6.6-0

**Comment by sdelicata** [comment]
Hello!
I close this issue as it targets an unsupported version of Traefik.
Feel free to re-open it or join our [Community Forum](https://community.traefik.io/).
