### ISSUE TITLE
Support for Zipkin’s B3 headers propagation when using Jaeger as tracing

### ISSUE THREAD

**Issue by sta-szek** [traefik/traefik#4049]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hello,

I would like to request a feature that would allow me to change Inter-process propagation wire format (headers) (https://www.jaegertracing.io/docs/1.7/client-features/) when using jaeger as tracing implementation.

It would be nice to have it configured e.g.:
```
    [tracing]
      backend = {{ .Values.tracing.backend | quote }}
      serviceName = {{ .Values.tracing.serviceName | quote}}
      [tracing.jaeger]
        localAgentHostPort = {{ .Values.tracing.jaeger.localAgentHostPort | quote }}
        samplingServerUrl = {{ .Values.tracing.jaeger.samplingServerUrl | quote }}
        samplingType = {{ .Values.tracing.jaeger.samplingType | quote }}
        samplingParam = {{ .Values.tracing.jaeger.samplingParam }}
>>>     propagationImpl = [uber|zipkin|w3c(comming)]
```

The feature request has arose as I am facing issues when trying to implement tracing in quite big system (contains a lot of LB, services, etc...) Some of them are brand new like spring-boot but some of them are quite old monolith which are risky to change or change time is not acceptable.

The problem is that we already have tracing in monolith/services. We use zipkin libs under the hood. That's why propagating context in uber format is not working for us -- and this is exactly what traefik is doing.

It would be nice to change implementation of propagation to zipkin b3 headers. From jaeger docs we can see that almost all libs support it: https://www.jaegertracing.io/docs/1.7/client-features/

Of course we could switch jaeger to zipkin but this would cause other issue: we won't be able to use all jaeger features (like adaptive sampling). Also we want to switch from zipkin to jaeger one day...

Thanks

**Comment by whs** [comment]
I believe this is fixed in 6f6ebb80252dca3eed301d90dc3ee7fde86bd967 ?

**Comment by sta-szek** [comment]
Thanks @whs! Can you tell me which traefik version contains the change? I cannot determine it on my own.

**Comment by whs** [comment]
It's still unreleased

**Comment by voidengineer** [comment]
It would be great, if `propagationImpl` (or `propagation` as it is called in https://github.com/containous/traefik/commit/6f6ebb80252dca3eed301d90dc3ee7fde86bd967) would be a list. Sending the same trace-context in different propagation formats should be no problem for the receiving service and allows us to switch over to jaeger in small steps.

**Comment by eshepelyuk** [comment]
I believe this should be closed already.

**Comment by james-callahan** [comment]
I think this can be closed with the release of 3.x

**Comment by rtribotte** [comment]
I think you are right, thanks @james-callahan.
I'm closing this issue because the tracing feature in Traefik v3.0 has been completely rewritten to support only OpenTelemetry instrumentation, and B3 propagation is now supported.
However, feel free to ask for a reopening if you think we are missing something here.
