### ISSUE TITLE
Trailing slash is not being removed before request is forwarded to backend

### ISSUE THREAD

**Issue by martinklepsch** [traefik/traefik#4247]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- I used this [`traefik.toml`](https://gist.githubusercontent.com/martinklepsch/70f231132b8731f0c79f1c966a3ee53e/raw/62e4a2e3637588c29681841433f8478d87782585/traefik.toml) and started Traefik using `traefik --configFile=traefik.toml`.

      curl https://git.io/fp2aJ -o traefik.toml; traefik --configFile=traefik.toml

- I started the referenced backend using:

      cd $(mktemp -d); echo "ping http1" > ping; python3 -m http.server 8003

- I used curl to retrieve the `ping` file via Traefik, intentionally adding a trailing slash:

      curl http://localhost:80/ping/

### What did you expect to see?

As I understand [`keepTrailingSlash`](https://docs.traefik.io/configuration/commons/#main-section) with it's default value of `false` requests with a trailing slash should be stripped of trailing slashes before being forward to the backend. 

If this is working as intended then the bug might be in the documentation :)

### What did you see instead?

The request arrived at the backend containing the trailing slash. Causing a 404 response.

```
~ curl -si http://localhost:80/ping/ | head -n1
HTTP/1.1 404 Not Found
~ curl -si http://localhost:80/ping | head -n1
HTTP/1.1 200 OK
```

### Traefik Version

```
Version:      dev
Codename:     cheddar
Go version:   go1.11.2
Built:        I don't remember exactly
OS/Arch:      darwin/amd64
```
Reported as `1.7.4` in `/dashboard`. Installed via `brew install traefik`. Wanted to use a Docker image but couldn't get host networking set up.

### Environment

see above

### Debug Logs

http://sprunge.us/qPdLm4

**Comment by martinklepsch** [comment]
Started looking into this, complete beginner with regards to Go but will try to at least create a failing test case here: https://github.com/martinklepsch/traefik/tree/fix-4247.

If you want to help me contribute/get this done, I'm also @martinklepsch in the Traefik Slack.

**Comment by pascalandy** [comment]
I understand that "keepTrailingSlash"" is not relevant anymore in Traefik V2 right?

**Comment by rtribotte** [comment]
Hello,

This issue was for the v1, but as described in our [deprecation notices](https://doc.traefik.io/traefik/deprecation/releases/) the v1 is not supported anymore.
Accordingly, we are closing this issue.
