### ISSUE TITLE
ECS task networking with awsvpc networking mode on EC2 exposes wrong ip

### ISSUE THREAD

**Issue by maartenvanderhoef** [traefik/traefik#4353]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Start Traefik as an ECS Service with AWSVPC networking enabled on an EC2 cluster.

### What did you expect to see?

I expected the Traefik to expose the backend service with the IP of the attached ENI as it should with AWSVPC networking enabled (similar to Fargate)

### What did you see instead?

Traefik exposed the service with the IP of the EC2 instance.

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik:v1.7.6-alpine

https://github.com/containous/traefik/blob/ddf199566c0966b674e4a9af0902d1ddaad8eceb/old/provider/ecs/ecs.go#L288 The condition is made for `Fargate` specific, but not covering `awsvpc` networking in general.

https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#Task
https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#Attachment

**Comment by maartenvanderhoef** [comment]
Created a diff, not sure where to PR against now. https://github.com/containous/traefik/compare/v1.7...maartenvanderhoef:v1.7

**Comment by dduportal** [comment]
Hi @maartenvanderhoef , thanks for interest in the Traefik project !

Your contribution is totally welcome. As you figured out, as this is considered as a bug, the target branch is the `v1.7`. 

You are good to open a PR with your fix, to switch on design and review on the proposed implementation.

Thanks a lot!

**Comment by tomMoulard** [comment]
As we no longer support Traefik version 1, @tfny closed this issue.

If this issue persists in version 2, feel free to open a new issue. Thanks!
