### ISSUE TITLE
Consul KV provider becomes extremely slow with growing number of frontends/backends

### ISSUE THREAD

**Issue by untoldwind** [traefik/traefik#4368]
Bug

### What did you do?

About 100 frontends and backends configured via consul KV.
Consul is running in a 3 node cluster that traefik queries directly (with watch=true).

### What did you expect to see?

"Nearly" immediate configuration updates whenever there is a change in the KV store.

### What did you see instead?

Configuration updates may take up to a minute or longer.

### Output of `traefik version`: 

```
Version:      v1.7.6
Codename:     maroilles
Go version:   go1.11.3
Built:        2018-12-14_06:43:37AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[consul]
endpoint = "__CONSUL_ENDPOINTS__"
watch = true
prefix = "traefik"
```

### Analysis

The cause of this problem appears to be the way the KV provider works under the hood.

* There is a "WaitTree" operation, each time a tree update is registered
* ... a new configuration template is generate by querying the relevant keys one by one (or nearly one by one)
* ... this results on about 20 (or so) requests to consul per frontend/backend (i.e. in total A LOT)
* Additionally each of these requests is done if "consistent=true", which generates a lot of overhead inside the consul cluster (i.e. it puts some load on the cluster and is slow by comparison)

### Suggested fix

Especially in case of consul all the additional request are completely unnecessary since the result of WatchTree already contains all KVPairs of the tree. So instead of re-quering everything from the KV store that configuration template might es well use the output of WatchTree directly.

**Comment by iameli** [comment]
Is this still likely to be an issue? We're running into something that looks very similar where changes take 60+ seconds to propagate when we have 500-1000 different routes.

**Comment by JakeCooper** [comment]
Noticed this running against the Redis provider

Sometimes it takes upwards of 3 minutes propagate (~5k services and ~10k routers)

Definitely would love a workaround/ack on this cause we're at the point where I've tried a variety of things and the only thing left to try is ripout Traefik entirely

**Comment by sdelicata** [comment]
Hello!
I close this issue as it targets an unsupported version of Traefik.
Feel free to re-open it or join our [Community Forum](https://community.traefik.io/).
