### ISSUE TITLE
Add exceptions for entryPoints.http.authBasic

### ISSUE THREAD

**Issue by dkossako** [traefik/traefik#4429]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be useful to add whitelisting for entryPoints.http.auth.basic. Like:
```
[entryPoints.http.auth.basic]
usersFile = "/etc/traefik/.htpasswd"
whiteList = [ "192.168.0.0/16" ]
```
Such feature would be used in projects to allow local network users view entrypoints without being authenticated.

**Comment by wodzik** [comment]
+1

**Comment by alesnav** [comment]
This would be a nice feature, but it is interesting also for `traefik.http.middlewares.xxx.forwardauth`, because of the same reason.

**Comment by GildedHonour** [comment]
Is help needed with this?

**Comment by maksadbek** [comment]
Should this feature get client's IP from `request.RemoteAddr` or from HTTP header value like `X-Real-IP` or `X-Forwarded-For` ?

**Comment by dkossako** [comment]
imo remote addr, but maybe it would be fine to add some kind of boolean switch to change this behavior and allow to take from header?

**Comment by maksadbek** [comment]
Okay, that sounds reasonable. In this case the config should look like this:
```
[entryPoints.http.auth.basic]
  usersFile = "/etc/traefik/.htpasswd"
  [entryPoints.http.auth.basic.ipAllowList]
     allowedIPs = [ "192.168.0.0/16" ]
     clientIPFromHeader = ["X-Real-IP", "X-Forwarded-For"]  # if any of them is valid and in the given subnet use them. Otherwise, fallback to `request.RemoteAddr`
```

If the `clientIPFromHeader` is empty, then fallback to `request.RemoteAddr`

**Comment by dkossako** [comment]
Looks good to me

**Comment by ldez** [comment]
For those who don't know: since one year, the v1 of Traefik is in maintenance mode, which means there are more new features added and only fixes can be added.

Otherwise, this issue can be linked to #6007

**Comment by rtribotte** [comment]
Hello,

Based on the reading of the PR of @maksadbek, we think that a better approach would be to rely on the routing, in place of trying to "enhance" current middlewares with IP allow-listing.
The idea is to provide a specific routing based on IPs, that would allow to have routes with and without an auth middleware (for instance).

WDYT ?

**Comment by maksadbek** [comment]
Hello @rtribotte 

Thank you for your reply. It really great that we move on this issue. I am for any solution that Traefik team would approve and for now at least we need to know what does @ldez think about it.

I am going to see how the routings are implemented and the ways to add routing by IP. If it is ok, then I will send an another PR that will hopefully be merged :)

Thanks

**Comment by jr0dd** [comment]
This should also take care of this issue https://github.com/traefik/traefik/issues/6007

**Comment by rtribotte** [comment]
Hello,

@jr0dd Issue #6007 has already been linked to this one by a previous [comment](https://github.com/traefik/traefik/issues/4429#issuecomment-691676879).

@dkossako @maksadbek IP-based routing has been introduced in v2.5 by PR #8169.
It seems that this issue is resolved, as it allows to create an alternative router without basic auth for some IPs, WDYT?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
