### ISSUE TITLE
healthcheck timeout parameter is not configurable in rest provider

### ISSUE THREAD

**Issue by cocorossello** [traefik/traefik#4509]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to set timeout parameter in rest provider, but traefik does not recognize it.

This is the rest request:
```
{
    "backends": {
        "myback": {
            "servers": {
                "S0": {
                    "url": "http://192.168.3.21:30000",
                    "weight": 100
                }
            },
            "loadBalancer": {
                "method": "wrr",
                "stickiness": {
                    "cookieName": "backend"
                }
            },
            "healthCheck": {
                "path": "/healthcheck",
                "interval": "11s",
                "timeout": "4s"
            }
        }
    },
    "frontends": {
        "myfront": {
            "entryPoints": [
                "http"
            ],
            "backend": "myback",
            "passHostHeader": true,
            "priority": 999,
            "basicAuth": null,
            "headers": {}
        }
    }
}
```

### What did you expect to see?

I expect to see timeout parameter in the response and this timeout used in the healthcheck operation.

### What did you see instead?

Timeout parameter is ignored

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
defaultEntryPoints = ["http"]
logLevel = "INFO"
[traefikLog]
  filePath = "/var/log/traefiklogs/traefik.log"


[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = false
[rest]
[file]
   watch = true
 [backends]

[frontends]
```

After startup I create a rest provider by doing a PUT request to :8091/api/providers/rest with the rest request mentioned

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

The rest response does not contain timeout parameter

```
{
    "backends": {
        "myback": {
            "servers": {
                "S0": {
                    "url": "http://192.168.3.21:30000",
                    "weight": 100
                }
            },
            "loadBalancer": {
                "method": "wrr",
                "stickiness": {
                    "cookieName": "backend"
                }
            },
            "healthCheck": {
                "path": "/healthcheck",
                "interval": "11s"
            }
        }
    },
    "frontends": {
        "myfront": {
            "entryPoints": [
                "http"
            ],
            "backend": "myback",
            "passHostHeader": true,
            "priority": 999,
            "basicAuth": null,
            "headers": {}
        }
    }
}
```

**Comment by ddtmachado** [comment]
@cocorossello The `timeout` is being ignored because it does not exist under the `Healthcheck` object. Source: https://docs.traefik.io/v1.7/configuration/commons/#health-check-configuration

If you were referring to request / response timeouts they can be set globally as `forwardingTimeouts` and `respondingTimeouts` as defined here: https://docs.traefik.io/v1.7/configuration/commons/#timeouts

**Comment by sdelicata** [comment]
Hello!
I close this issue as it targets an unsupported version of Traefik.
Feel free to re-open it or join our [Community Forum](https://community.traefik.io/).
