### ISSUE TITLE
Document equivalents of client_max_body_size, nginx proxy_buffers, and proxy_buffer_size

### ISSUE THREAD

**Issue by westurner** [traefik/traefik#4580]
### Do you want to request a *feature* or report a *bug*?

Feature (Documentation)

### What did you expect to see?

How to port a site from Nginx (and maybe Apache2) to traefik; in terms of `proxy_buffer_size` and `proxy_buffers`.

- https://docs.traefik.io/configuration/commons/#buffering
  - https://godoc.org/github.com/vulcand/oxy/buffer
    - > func MaxRequestBodyBytes(m int64) optSetter
      > MaxRequestBodyBytes sets the maximum request body size in bytes
    - > func MaxResponseBodyBytes(m int64) optSetter
      > MaxResponseBodyBytes sets the maximum response body size in bytes
    - > func MemRequestBodyBytes(m int64) optSetter
      > MemRequestBodyBytes bytes sets the maximum request body to be stored in memory buffer middleware will serialize the excess to disk.
    - > func MemResponseBodyBytes(m int64) optSetter
      > MemResponseBodyBytes sets the maximum response body to be stored in memory buffer middleware will serialize the excess to disk.

- Nginx
  - client_body_buffer_size
    https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size
    > Sets buffer size for reading client request body. In case the request body is larger than the buffer, the whole body or only its part is written to a temporary file. By default, buffer size is equal to two memory pages. This is 8K on x86, other 32-bit platforms, and x86-64. It is usually 16K on other 64-bit platforms.
  - client_header_buffer_size
    https://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_buffer_size
  - client_max_body_size
    https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
    > Sets the maximum allowed size of the client request body, specified in the “Content-Length” request header field. If the size in a request exceeds the configured value, the 413 (Request Entity Too Large) error is returned to the client. Please be aware that browsers cannot correctly display this error. Setting size to 0 disables checking of client request body size.
  - proxy_buffer_size
    https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size
    > Sets the size of the buffer used for reading the first part of the response received from the proxied server. This part usually contains a small response header. By default, the buffer size is equal to one memory page. This is either 4K or 8K, depending on a platform. It can be made smaller, however.
  - proxy_busy_buffers_size
    https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_busy_buffers_size
    > When buffering of responses from the proxied server is enabled, limits the total size of buffers that can be busy sending a response to the client while the response is not yet fully read. In the meantime, the rest of the buffers can be used for reading the response and, if needed, buffering part of the response to a temporary file. By default, size is limited by the size of two buffers set by the proxy_buffer_size and proxy_buffers directives.
  - proxy_buffers
    https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffers
    > Sets the number and size of the buffers used for reading a response from the proxied server, for a single connection. By default, the buffer size is equal to one memory page. This is either 4K or 8K, depending on a platform.
  - proxy_buffering
    https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering
  - proxy_request_buffering
    https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering
  - proxy_read_timeout
    https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout
- Apache 2
  - ProxyIOBufferSize
    https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyiobuffersize
  - ProxyReceiveBufferSize 
    https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyreceivebuffersize

**Comment by westurner** [comment]
I suppose this could go to StackOverflow, but IMHO updating the docs would be helpful for all.

For example, how do I port this from nginx to traefik/oxy?
```
client_max_body_size 50M;
proxy_buffers 256 16k;
proxy_buffer_size 16k;
proxy_read_timeout 600s;
```

Maybe a table?

**Comment by dduportal** [comment]
Hi @westurner , thanks for your interest in the product and your feedbacks.

It's not clear on what are you expecting:

1. A dedicated page for migrating from Nginx when you have these specific settings?
2. An improvement on the paragraph https://docs.traefik.io/configuration/commons/#buffering with a table?
3. Something else?


If 1., then this out of the scope of this documentation, for many maintenance cost effort reasons.
If 2., then  we need your help by contributing to this documentation, as Traefik is an open source project, so it's yours as well as ours. The documentation being full part of this document, you can follow https://github.com/containous/traefik#contributing and propose a change.
If 3., then we need your help to explain what is your expectation and if you see similar documentation on Nginx or any other related products to help us understand.

**Comment by westurner** [comment]
> 2. An improvement on the paragraph docs.traefik.io/configuration/commons/#buffering with a table?

2. This is an initial attempt at doing the research necessary to correlate the relevant config parameters. It seems more useful to ask this question here than in SO.

**Comment by dduportal** [comment]
Hi @westurner , thanks for the precision. We labeled the issue according to.
Feel free to propose a contribution on this topic.

**Comment by excalq** [comment]
For what its worth, Googling `proxy-body-size traefik` links to this issue. The Ingress config used by [Longhorn](https://longhorn.io/docs/1.2.4/deploy/accessing-the-ui/longhorn-ingress/) makes use of `nginx.ingress.kubernetes.io/proxy-body-size` for supporting large disk image uploads. In my case, I'm unifying this into my `IngressRoute` configuration. [Buffering middlewares](https://doc.traefik.io/traefik/middlewares/http/buffering/) seem to be the right way to port this.
 
That doc page implies there is either no default limit, or one that's undocumented. ("rejects requests that are over a specified size limit.") Noting the default sizes would be preferred.

Traefik's dependency code (`https://github.com/vulcand/oxy/blob/master/buffer/buffer.go#L423`) suggests it's 10MB.

**Comment by mpl** [comment]
The original request sounds like a good idea in principle, and if someone makes a blog post or something for it, we would consider linking to it somewhere, but we don't think it actually directly belongs in the Traefik doc.
