### ISSUE TITLE
Path restrictions

### ISSUE THREAD

**Issue by sylr** [traefik/traefik#4812]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be nice to be able to enforce global path restrictions which would applied to all frontends.

The use case for this is to protect internal endpoints such as `/metrics` (prometheus scrape endpoint), `/ping` & `/ready` (kubernetes probes endpoints) ... etc so that they wouldn't be publicly available. 

The must would be the possibility to choose what kind of error traefik would return (404, 503 or else) and also be able to whitelist ip ranges that could access those paths.

**Comment by treezio** [comment]
really interested on this !

**Comment by ahoulgrave** [comment]
FYI it's better to expose one external and one internal port on your services,  so you expose for example `:8081/metrics` and then `:8080/public-uri`. Your ingress or rule should target the public port. So i'm not really sure this feature should be implemented.

**Comment by treezio** [comment]
In some cases its not that easy to expose those metrics in a different port 
(ex: NodeJS express server prometheus metrics will be exposed in the default port and its quite tricky to changes that port.)

**Comment by sylr** [comment]
Agree with @treezio , you can't rely that the soft you want to proxy through Traefik use a specific port for internal endpoints (most of the time they don't).

**Comment by ahoulgrave** [comment]
Ok, sure, it's true this a needed feature.
Still, I think you should expose two different ports whenever it's possible

**Comment by treezio** [comment]
Although you are definitely right @ahoulgrave , I think this is a quite cool feature.

**Comment by koalalorenzo** [comment]
I would love this feature!

**Comment by ericjee** [comment]
Hi guys, any updates?

**Comment by jhaumont** [comment]
Same like @koalalorenzo, I want to drop nginx ! Any news for a schedule of this feature ?

**Comment by SantoDE** [comment]
You could come close with v2 here I guess? How about defining a middleware with your desired actions and attach that to all routers needed?

**Comment by scwall** [comment]
Hello I am very interested in this feature too.

**Comment by fwkz** [comment]
@juliens Is there any update on this?

**Comment by canidam** [comment]
Would love to see this feature in traefik. I need it for a different use case, to block some paths on my app. Really need this feature

**Comment by notsureifkevin** [comment]
@canidam The team recently [launched Pilot](https://containo.us/blog/introducing-traefik-pilot-a-first-look-at-our-new-saas-control-platform-for-traefik/), which includes the ability to install custom middleware plugins into Traefik. Coincidentally, we've already [built a plugin](https://github.com/containous/plugin-blockpath) that may address this very use case.
 
Also, a community member wrote a [great blog post](https://tferdinand.net/traefik-2-3-vers-les-plugins-et-au-dela/) on how to install and use this very plugin. If you don't speak French, Google Translate seems to do a pretty good job at translating to English.

Please let us know if this helps, or if you need any help with creating your own plugin that may better suit your needs.

**Comment by teddy-ferdinand** [comment]
English version is available too : https://tferdinand.net/en/traefik-2-3-towards-plugins-and-beyond/ :)

**Comment by koalalorenzo** [comment]
@notsureifkevin not sure if it fits. Let me make sure I understand correctly:

- This features can be done via plugins. (The plugin is just about 
- Plugins is behind a paywall ( not sure? )
- Plugins are available behind a centralised configuration solution

Am I reading this right?

**Comment by ldez** [comment]
- This feature can be done via this plugin: https://pilot.traefik.io/plugins/270947803019084288/block-path
- Plugins are free, Traefik Pilot is free.
- Plugins can be used like other middlewares, Traefik Pilot is the "source/storage" of plugins.

**Comment by koalalorenzo** [comment]
Can we avoid the pilot all together and just get the plugin? 🤔

**Comment by ldez** [comment]
Traefik Pilot is the only available sources of plugins.

**Comment by koalalorenzo** [comment]
Keep this issue open then 😉 I would prefer to not use Traefik Pilot, mange another static token.

I'll just stay to NGINX then :(

**Comment by thomscode** [comment]
If you don't want to use Traefik Pilot, then using a middleware like the [ReplacePathRegex](https://docs.traefik.io/middlewares/replacepathregex/) middleware to effectively block the `/metrics` path (or whatever path you want).

It wasn't perfect in my case, but it did effectively block the url. Here is the config I used and the results I got:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: block-metrics
spec:
  replacePathRegex:
    regex: ^/metrics
    replacement: /
```

|URL|Expected URL|Actual URL|Actual path loaded|
|---|---|---|---|
|domain.com/metrics|domain.com/|domain.com/metrics|domain.com/|
|domain.com/metrics/|domain.com/|domain.com/|domain.com/|
|domain.com/metrics/user|domain.com/user|domain.com/user|domain.com/user|

As you can see this works to effectively block the `/metrics` path (regex can be adjusted to work with other paths) but if you hit `/metrics` and not `/metrics/` it doesn't actually remove the word "metrics" from the path, even though it does redirect to the right URL.

**Comment by CarpathianUA** [comment]
+1 Really want to see this feature implemented

**Comment by faust64** [comment]
> Plugins are free and open source, Traefik Pilot is free.

 ... as in freeware?
That's not really what I would expect from an opensource project.
What about disconnected installations?

This is a showstopper. Would stick to nginx as well...

**Comment by rtribotte** [comment]
We discussed this feature between maintainers following the opening of PR #8036.
We prefer to decline this issue in favor of #5228.
We think it's preferable to not introduce the new rule matcher `PathExept`, as it will lead to the introduction of the equivalent for `Host` or `HostRegexp`, and found it more appropriate to provide a syntax to negate rules.
It will allow achieving the same goal.

I'll decline this issue accordingly.

**Comment by rtribotte** [comment]
Hello @oxzi,

Just to let you know, PR #8164 has been opened to implement #5228.
