### ISSUE TITLE
Listen on multiple addresses/ports with entry point

### ISSUE THREAD

**Issue by fuzzykiller** [traefik/traefik#4961]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

An entry point should be able to listen on multiple IP addresses/ports. This would enable the use of Let’s Encrypt ([acme]) for both IPv4 and IPv6 on situations were both addresses are equivalent. [acme] works only with a single entry point.

**Comment by almereyda** [comment]
Oh please, I just came here a few days ago, so this might be still relevant for some use cases.

**Comment by nmengin** [comment]
Hello @almereyda,

Thank you for your feedback.
Could you please describe your use case?

Thanks in advance.

**Comment by almereyda** [comment]
In our situation, we use Traefik as an internal load balancer for a private network (Headscale, Tailscale with `.internal` DNS zone and StepCA ACME CA) plus the public endpoint of the machine.

While people will regularly not have access to our internal CA and DNS, it is possible to craft a request at the public endpoint using a private hostname to deliver internal services. To circumvent this, it would be could to have separate entrypoints per network interface.

The default configuration of entrypoints by only specifying a port listens on both IP4 and IP6 by default.

This behaviour could be mimicked by an entrypoint that is scoped at a single interface with allowing to bind to both protocol versions of its Internet Protocol addresses.

It could either be implemented by allowing to specify multiple `address:` entries for an entrypoint, or by introducing a new entrypoint key `interface:`, allowing to bind to all addresses in all protocol versions of a specific interface (`eth0`,`enp4s0`,`wg0`,`tailscale0`,…).

**Comment by rtribotte** [comment]
@almereyda Declaring multiple entryPoints with the same port but different address, like:
`--entrypoints.http.address=192.168.1.161:8080 --entrypoints.http2.address=127.0.0.1:8080`, is already supported.

Is this, at least partially, what you were looking for?

**Comment by almereyda** [comment]
Partly. For convenience I would like to use a single entry point for both IP4 and IP6 traffic scoped at a single interface or rather combination of IP4 and IP6 addresses, as described in the OP.
