### ISSUE TITLE
Auth module

### ISSUE THREAD

**Issue by WTFKr0** [traefik/traefik#498]
Hi

I plan to use traefik on many instance of docker server.
Some on servers, in swarm cluster (or any other orchestrator)
And some on dev laptop (docker-toolbox) to let developpers run their own containers

When a dev run a set of containers in his laptop, traefik expose the web service to all the company, so others dev in team can test app
For some security reason, I would like to authenticate users when access to the traefik instance.

For the moment, I do the following : 
- Set traefik to listen only on localhost, on port != 80
- Set an [nginx reverse proxy with ldap auth](https://hub.docker.com/r/h3nrik/nginx-ldap/) configure to let access only to right people, listening on the external IP and redirect all traffic to traefik

The problem : 
Those access rules are set for every containers globally

Can we imagine an auth config to traefik, tu plug with ldap for example, and then set some labels on containers to apply a security access rule to the frontend ? With that, each frontend can have its own access rule.
I think its a lot of work, so I want to know if others need that :D 

Thanx

**Comment by emilevauge** [comment]
Maybe linked to #391 ?

**Comment by babkamen** [comment]
Can you integrate https://github.com/weaveworks/ghost?

**Comment by aparcar** [comment]
Any updates on LDAP support?

**Comment by WTFKr0** [comment]
Linked to #764

**Comment by svscorp** [comment]
@WTFKr0 do you have anything on backend that uses ldap auth as well? (I believe it should be passed to the tool from NGinx) I am curious, did you achieve stability? I am facing issue with continuous `closed keepalive connection` and `client closed connection while waiting for request` messages. Looking to Traefik to replace it.
> For my case, I can set an nginx reverse proxy with auth ldap in front of my traefik.
> It seems to work very well

**Comment by dkowis** [comment]
Just for reference, I have a docker registry behind an nginx LDAP basic auth behind traefik, and I haven't had any problems. Not everything behind my traefik needs LDAP auth.

I would like to just do LDAP auth in traefik directly tho. Would remove one piece of my infra.

**Comment by benyanke** [comment]
Has this gone anywhere? I'd love to see LDAP auth for the backend.

**Comment by andypost** [comment]
I bet on https://docs.traefik.io/v2.0/middlewares/forwardauth/

**Comment by ddtmachado** [comment]
Hey, just to give a quick update on this rather old issue :) 

As pointed out by @andypost I believe that LDAP can work with the ForwardAuth middleware for most use cases, there are a few discussions and references linked on [this issue](https://github.com/authelia/authelia/issues/371) as well.

Also we now have a plugin system available as well, and lately we're [encouraging contributors](https://github.com/traefik/traefik/pull/8041#issuecomment-1167775937) to write authentication middleware as plugins. It reduces the complexity of our code base, give more control to contributors and helps us to keep focused on other important subjects.

For those reasons I'm closing this, but as usual if you feel this is not right or want to discuss a specific proposal that does not fit as a plugin or and enhancement for the ForwardAuth don't hesitate to reach us in the comments or submit a new issue.
