### ISSUE TITLE
Newly issued ACME certs not seen by all Traefik instances

### ISSUE THREAD

**Issue by atombender** [traefik/traefik#5038]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you expect to see?

Added a new host to a Kubernetes ingress.

### What did you see instead?

After ACME issues a cert, all instances of Traefik should use the cert. However, some instances don't have the cert, which I can see by making a request against the specific instance:

```shell
$ curl -vs --connect-to ::10.4.10.170:8443 https://a4.test.t11e.com/ >/dev/null
* Connecting to hostname: 10.4.10.170
* Connecting to port: 8443
*   Trying 10.4.10.170...
* TCP_NODELAY set
* Connected to 10.4.10.170 (10.4.10.170) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [234 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [58 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [853 bytes data]
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
```

Debugging this with `openssl s_client`, Traefik is serving the default cert (`subject=/CN=TRAEFIK DEFAULT CERT`).

Dumping the ACME state from Etcd shows me that the domain is there:

```json
{
  "Email": "...",
  "Registration": {
    "body": {
      "status": "valid",
      "contact": [
        "mailto:..."
      ]
    },
    "uri": "..."
  },
  "PrivateKey": "...",
  "KeyType": "4096",
  "DomainsCertificate": {
    "Certs": [
      ...,
      {
        "Domains": {
          "Main": "a4.test.t11e.com",
          "SANs": null
        },
        "Certificate": {
          "Domain": "a4.test.t11e.com",
          "CertURL": "...",
          "CertStableURL": "...",
          "PrivateKey": "...",
          "Certificate": "..."
        }
      }
    ]
  },
  "ChallengeCerts": {},
  "HTTPChallenge": {
    ...
  }
}
```

I can reproduce this consistently in our staging environment by adding new hosts to our config. Everything else is working fine, it's just that we have to reload Traefik pods every time we do an ingress change.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.12
Codename:     maroilles
Go version:   go1.11.10
Built:        2019-05-29_07:35:02PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Since we use Kubernetes, we use the `file` provider only with [this config](https://gist.github.com/atombender/f7a608d6282dbd24535324a1ddc35492) via a configmap. We store the ACME state in Etcd.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

In this log, the pod `traefik-ingress-controller-767b9bf587-58jv5` gets the cert. The pod `traefik-ingress-controller-767b9bf587-9mrgg` does not get the cert.

[traefik.log.gz](https://github.com/containous/traefik/files/3336736/traefik.log.gz)

(Note: The log is from 1.7.9, but upgrading to 1.7.12 did not help.)

**Comment by atombender** [comment]
When testing adding a new host, Traefik sometimes doesn't issue a cert at all, and I see this in the logs:

```
{"level":"error","msg":"Error getting challenge for token: cannot find challenge for token Y8FRy9wEJNSN2JtSbolv3e1HgyN-vkUDqnzissEs9h8","time":"2019-06-27T23:56:53Z"}
```

Client requests cause this log output:

```
{"level":"debug","msg":"Looking for an existing ACME challenge for a7.test.t11e.com...","time":"2019-06-27T23:58:27Z"}
{"level":"debug","msg":"Looking for provided certificate to validate a7.test.t11e.com...","time":"2019-06-27T23:58:27Z"}
{"level":"debug","msg":"No provided certificate found for domains a7.test.t11e.com, get ACME certificate.","time":"2019-06-27T23:58:27Z"}
{"level":"debug","msg":"No certificate found or generated for a7.test.t11e.com","time":"2019-06-27T23:58:27Z"}
{"level":"debug","msg":"http: TLS handshake error from 10.4.8.169:57090: remote error: tls: unknown certificate authority","time":"2019-06-27T23:58:27Z"}
```

The log seems weird. Lots of `Error getting challenge for token retrying in 4.623009561s`, and then `Error getting challenge for token: cannot find challenge for token <token>`.

[traefik.log.gz](https://github.com/containous/traefik/files/3337042/traefik.log.gz) (after adding `a7.test.t11e.com`).

**Comment by atombender** [comment]
Further testing shows that Traefik only gets a cert some of the time. It's not just that some instances don't pick up the new cert; sometimes a cert isn't issued at all. It seems completely arbitrary.

Here's another log from when none of the instances get a cert (after adding `a13.test.t11e.com` to the ingress): [traefik.log.gz](https://github.com/containous/traefik/files/3337470/traefik.log.gz)

**Comment by atombender** [comment]
@ldez Any ideas? This is significant blocking our ability to service new customers, since new domains typically end up not getting a cert.

**Comment by 27Bslash6** [comment]
+1 to this, we've been suffering from Traefik failing to pick up new domains and failing to issue renewals to all replicas for much of this year.  I've asked in slack to no avail.

The solution is always to kill the pods and let them restart.

Not viable long term, we're switching ingress controllers for this reason.

**Comment by atombender** [comment]
@27Bslash6: Can I ask what you're switching to? I've looked at potentially switching to Cert-Manager for LE cert allocation, wirh something like Envoy or Nginx as the Ingres controller. Cert-Manager is a lot more complex to install and operate than Traefik.

**Comment by 27Bslash6** [comment]
@atombender We're currently trialling nginx-ingress with cert-manager.

**Comment by mmatur** [comment]
Hello,

This bug is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
