### ISSUE TITLE
Large temporary multibuf files not getting cleaned up. 

### ISSUE THREAD

**Issue by jacwellington** [traefik/traefik#5143]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ x] No

### What did you do?

I enabled buffering of requests using this configuration on one of my backends:

`traefik.backend.buffering.retryExpression=IsNetworkError()&&Attempts()<=2`

This backend is serving up some very large responses that can be GB's in size, so it writes them to disk to temporary files. Sometimes these files are not cleaned up, weeks after the original request was made. 

Note: I added a write timeout value of `24h` to make sure that these weren't just long running requests, but it didn't help.

### What did you expect to see?

I expected to see that these temporary files were getting cleaned up after a reasonable amount of time.

### What did you see instead?

The temporary files exist forever.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.5
Codename:     maroilles
Go version:   go1.11.2
Built:        2018-12-03_11:01:00AM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I don't have a config file. Here is the cmd that is being run in the docker container:
```
/traefik --api --docker --defaultentrypoints=https --entryPoints=Name:https Address::443 TLS:/certs/path --entryPoints=Name:http Address::80 Redirect.EntryPoint:https --respondingtimeouts.writetimeout=24h
```

**Comment by dduportal** [comment]
Hi @jacwellington , can you confirm that you still have the issue with `v1.7.12`?

**Comment by jacwellington** [comment]
Sure, @dduportal. I've upgraded our production site to v1.7.12. I'll get back to you soon on if we are still seeing this behavior.

**Comment by jacwellington** [comment]
We're still getting this issue even with v1.7.12.

**Comment by NicolasLemince** [comment]
Hello Traefik team, 

Do you have any news regarding this issue ? I'm struggling with the same issue with my Traefik k8s ingress controller

**Comment by kevinpollet** [comment]
Hello @NicolasLemince,

As described in our [deprecation notices](https://doc.traefik.io/traefik/deprecation/releases/) the v1 is not supported anymore.

As this issue concerns v1, we will close it but feel free to open a new issue if it still exists on v2.
