### ISSUE TITLE
Pass TLS cert to Traefik mTLS backend

### ISSUE THREAD

**Issue by johnnyhuy** [traefik/traefik#5146]
Greetings,

I've scanned across this repo to see if anyone had a similar issue. Please close this issue if this has been made elsewhere, thanks! 😀

### Do you want to request a *feature* or report a *bug*?

Feature request was preivously for **v2** alpha and now GA v2.0.0 onward.

### What did you expect to see?

![Traefik2](https://user-images.githubusercontent.com/27847622/61680628-b3138a00-ad4d-11e9-82f7-8da8a7b42bc2.png)

Traefik being able to pass a TLS certificate from one Traefik instance to another. Where the destination Traefik instance has mTLS enabled to authenticate the request.

The setup I had was my local host along with a remote server with Docker Compose. I've managed to get it working with the `passTLSCert` function, however this is deprecated in `v1.7` as [jbd mentioned](https://community.containo.us/t/traefik-to-traefik-mtls-authentication/890/12).

Using `passTLSClientCert` doesn't work in my scenario since the destination Traefik mTLS mechanism doesn't pick up the certificate in the headers, thus giving me a "bad gateway/certificate" error.

I have described this issue in depth at [community.containo.us](https://community.containo.us/t/traefik-to-traefik-mtls-authentication/890). This is also similar to issue #4260, which was where I originally follow the V1 hack to get it working.

This feature has also been removed in V2 (#4375). Will there be an alternative approach to this?

**What are your thoughts?**

**Comment by cypx** [comment]
I also encounter the same problem because I forget to configure client authentication (https://docs.traefik.io/https/tls/#client-authentication-mtls).
Maybe it could specify on PassTLSClientCert page (https://docs.traefik.io/middlewares/passtlsclientcert/)
