### ISSUE TITLE
Exponential Backoff for Retry Middleware

### ISSUE THREAD

**Issue by Cielquan** [traefik/traefik#5282]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The `Retry` Middleware only has the option to set the amount of retries. I would like to also set an "exponential Backoff". So the unavailable service is not flooded with requests.

**Comment by gkoerk** [comment]
This would be fantastic. Does Traefik or Marsh have features of, say, envoy proxy on the roadmap?

**Comment by rtribotte** [comment]
closed by #7460
