### ISSUE TITLE
NFR - Add support for HTTP/3 (http-over-quic)

### ISSUE THREAD

**Issue by ruudboon** [traefik/traefik#5514]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Browsers are adding HTTP/3 support and Cloudflare started experimenting with this. 
Chrome (Canary) is available and Firefox announced that they will release a nightly version with HTTP/3 soon.
Support for HTTP/3 would be great new feature for Traefik. I can imagine it will be a huge task so that's why I would like to request this already.

**Comment by rdehouss** [comment]
Cloudflare developed a library usable for both client and sever: https://github.com/cloudflare/quiche

**Comment by Yggdrasil** [comment]
> Cloudflare developed a library usable for both client and sever: https://github.com/cloudflare/quiche

That library is written in Rust though. Not sure if that can be used in Traefik.

Here's one written in Go: https://github.com/lucas-clemente/quic-go. I have no idea about the stability of the implementation.

**Comment by ldez** [comment]
FYI, we are working on that :wink: 

https://github.com/lucas-clemente/quic-go/pulls?q=is%3Apr+is%3Aclosed+author%3Ajuliens

**Comment by amir20** [comment]
Hello. I am wondering if there has been any updates on this since 2019. Safari will [support](https://caniuse.com/http3) HTTP3 with the new OS release. I'd imagine this would be a nice to have.

**Comment by iAnanich** [comment]
Hi. Cloudflare mailed me (and probably many others) that they will enable HTTP/3 on free plan over next few weeks. Wondering if Traefik has support for new version of protocol.

**Comment by Roken120** [comment]
Hello, any news ?

**Comment by jbdoumenjou** [comment]
Closed by https://github.com/traefik/traefik/pull/7724

**Comment by Motophan** [comment]
Hello, how can add/use the HTTP3 to traefik ?

**Comment by jonaskuske** [comment]
@Motophan It's in the docs, but you'll need to use the experimental version as of now: https://doc.traefik.io/traefik/master/routing/entrypoints/#enablehttp3

**Comment by buarle** [comment]
Docs not working for me, even when adding the experimental part to the traefik.toml

_"command traefik error: field not found, node: enableHTTP3"_

Any need to install a specific traefik version like a beta? I'm currently with the traefik:latest version updated half-dayly via watchtower.

Best Markus

**Comment by Motophan** [comment]
I have the exact same problem as @buarle

**Comment by Roken120** [comment]
I have the exact same problem as @buarle

**Comment by ldez** [comment]
HTTP3 will be in the next release: v2.5

It's not available in v2.4 https://github.com/traefik/traefik/blob/master/CHANGELOG.md#v240-2021-01-19
