### ISSUE TITLE
UI bug - services name overlaps with weight and provider

### ISSUE THREAD

**Issue by m7mdkamal** [traefik/traefik#5702]
### Do you want to request a *feature* or report a *bug*?

UI Bug

### What did you do?

I have a long service name that overlaps with the weight and provider image in this url `http://localhost:8080/dashboard/#/http/services/{service_name}`

### What did you expect to see?

The service name shouldn't overlap with the weight and the provider

### What did you see instead?

![screencapture-localhost-8080-dashboard-1571740660919](https://user-images.githubusercontent.com/6086903/67278486-59943600-f4c9-11e9-945d-918e0bbacf5d.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.2
Codename:     montdor
Go version:   go1.13.1
Built:        2019-10-09T19:26:05Z
OS/Arch:      linux/amd64
```

**Comment by traefiker** [comment]
Closed by #7535.
