### ISSUE TITLE
Traefik header transformation

### ISSUE THREAD

**Issue by llacroix** [traefik/traefik#6047]
### Feature:

Header transformation rules using a predefined set of operators

### Syntax:

Something like this:

`traefik.http.middlewares.<middleware>.headers.request_transform = op1, op2, op3`
`traefik.http.middlewares.<middleware>.headers.response_transform = op1, op2, op3`

Or possibly:

`traefik.http.middlewares.<middleware>.headers.transform.operations = op1, op2, op3`
`traefik.http.middlewares.<middleware>.headers.transform.type = 'request' or 'response'`

### Goal:

Add a toolset that lets traefik transform headers. Currently in traefik it's possible to do basic operations of headers like adding,removing headers from a request or response but the support for manipulation of headers is quite simplistic. It doesn't really let the users to modify/transform header by changing the content or the name of the headers.

#### Rename(header, new_header) 

Rename a header by matching an exact `header` to a `new_header`. 

Example:

    Rename(`MY_HEADER`, `NEW_HEADER`)

Would change:

    MY_HEADER: super
    OTHER_HEADER: 123

To:

    NEW_HEADER: super
    OTHER_HEADER: 123

#### HeaderRewriteRule(regex, replace)

 Rewrite header name using a regex with a match/capture. 

Example:

    HeaderRewriteRule(`MY_(.*)`, `NEW_$1`)

Would change the following requests from:

    MY_HEADER: super
    MY_OTHER_HEADER: 123

To:

    NEW_HEADER: super
    NEW_OTHER_HEADER: 123

#### ValueRewriteRule(header, regex, replace)

Same as the header rewrite but for their content, header is a parameter to match an header or a set of headers to apply the rewrite rule.

#### Set(header, value)

Set a value to a header name

#### Remove(header)

Remove an header

#### Join(header, sep, value/header)

Possibility to join multiple headers inside one.
Example:

    Set(`PROXY_PATH`, `129.2.3.4`), Join(`PROXY_PATH`, `,`, `127.0.0.1`)

Would result with this header:

    PROXY_PATH: 129.2.3.4,127.0.01

As you can see, the order of the operators change the context of evaluation so op1 can change the context in a way that op2 will be able to transform headers that weren't present in the original response or request.  I guess that having some generic ways to manipulate headers would render some of the existing header configuration in the middleware useless. Or at least they could become simple shortcuts. 

As a side note, I guess the chain of operators could be hard to read/edit manually if you wanted to combine a lot of operations inside a single middleware. But I guess traefik being pretty useful when combined with containers, most users probably already have some tool that generate proper configurations so while reading the config might be necessary sometimes, writing a long operators chain should probably be implemented into some kind of external tool if user don't want to write by hand everything. Thought the use of `\n` could help by making the rules more readable. 

Inside a config file, the second syntax I proposed could look like this:

```toml
[traefik.http.middlewares."some_middleware".transform]
  type = "request"
  operations = """
    Set(...),
    Join(....),
    Rename(...)
  """
```

Or

```toml
[traefik.http.middlewares."some_middleware".transform]
  type = "request"
  operations = [
    "Set(...)",
    "Join(....)",
    "Rename(...)"
  ]
```

This is a proposal and if it's a good enough idea for people, this could leave the door open for more possible operators and may be better operators than the one I came up with. Technically speaking, this kind of feature could be used internally inside traefik to handle headers instead of having many ways to do the same things in different place of the code base.

**Comment by dtomcej** [comment]
`gorilla/mux` uses something similar, and stores variables in the request context with the key as the name of the variable used in the goregexp.

This allows re-use of that variable in other situations or transformations.

**Comment by abretaud** [comment]
This looks like what I would need for my use case (renaming `Remote-User` header received from authelia to `REMOTE_USER` as expected by my webapp)
Is anyone already working on this?

**Comment by p-baum** [comment]
I need this to rename the `X-Forwarded-Tls-Client-Cert` to `X-SSL-Cert` in order to run a syncthing discovery server ([https://docs.syncthing.net/users/stdiscosrv.html#requirements](url))

**Comment by FernandoMiguel** [comment]
curious to see if there is any traction for this proposal?

**Comment by willywongi** [comment]
I'm developing a service using Sanic (python) and it requires a shared secret between the forwarder (Traefik, nginx, ecc...) and your application. This would help!

**Comment by tomtastic** [comment]
I'd like to see this added too, especially for use with Authelia.

**Comment by davidjameshowell** [comment]
Throwing my hat in the ring: I'm using Authelia with Traefik proxied infront with Cloudflare and need to rewrite the X-Forwarded-For IP to be the Cloudflare Real IP address. I'm hoping we will be able to do header rewriting soon!

**Comment by kharole** [comment]
Have to stay on nginx to support custom multi-tenancy based on host header parsing by regex. Hopefully it is completed soon and I can migrate on traefik.

**Comment by cledavid** [comment]
Hi, currently working on that here : https://github.com/tomMoulard/htransformation

**Comment by fredsig** [comment]
Running Traefik behind an ALB, would love to rewrite X-Real-IP to pass real IP Address to Gunicorn and not the ALB's.

**Comment by himao** [comment]
authelia give Remote-User,gitea expect X-WEBAUTH-USER,need trans.

**Comment by jbdoumenjou** [comment]
As there is a working plugin https://github.com/tomMoulard/htransformation that answers this need, this issue is closed accordingly.

**Comment by kevinpollet** [comment]
Hello,

I am closing this issue in favor of https://github.com/traefik/traefik/issues/9471 which contains a more detailed example of the plan we want to follow.

Please do not hesitate to add comments on https://github.com/traefik/traefik/issues/9471 if you think that we miss some things, and to add your use case.
