### ISSUE TITLE
Add a way to filter the body of a request for forward authentication

### ISSUE THREAD

**Issue by llacroix** [traefik/traefik#6068]
Feature
======

The new option would let traefik send a request to an endpoint without passing the full request to the auth endpoint. As it is right now, the whole request would be sent to traefik then to the forwardAuth then the same request body would be sent to the actual endpoint.

One of the reason would be to prevent the authServer from receiving too much traffic and making sure the authServer has only what it needs to validate a request. 

So if a request contains multiple megabytes of data, it won't try to stream the data to the auth server if it doesn't have to. It's okay when data is received as GET but when request are made with POST method or possibly any other method type, it may make the forwardAuth endpoint more or less complicated to implement.

For example, you're using a framework that has a particular way to handle requests and automatically parse the body depending on the headers. But the forwardAuth route is defined with a basic type of data, as the request is received, it may end up in the body parser which would trigger a body parsing error as the body parsed doesn't match the body that is supposed to be parsed by the route.

Stripping the body of data makes it easy to keep the request small and reduce the amount of time/errors an endpoint would take to parse the body if it was present. On a security standpoint it could also prevent a person from sending a malformed body to the auth endpoint. For traefik, it means the request can be sent as soon as the header is loaded and while the auth request is being sent, it can spend time buffering the request until the auth response is received. Once the auth response is received it can transmit the buffer to the actual endpoint. In theory it should make the forwardAuth middleware more responsive.

**Comment by jamct** [comment]
@llacroix At the moment the body of the request is not forwarded to the auth server. You can see it [here in the code (line 80)](https://github.com/containous/traefik/blob/master/pkg/middlewares/auth/forward.go):
`forwardReq, err := http.NewRequest(http.MethodGet, fa.address, nil)`
The third parameter is `nil`. I would like to forward the body at my auth server (to evaluate rules in Open Policy Agent) so I would like to prepare a PR. Maybe it is a good idea to add a new setting to activate forwarding of the body.

**Comment by llacroix** [comment]
Ah yes that's correct.. thought I do remember having issues, but that could have been caused by this. My endpoint was probably expecting JSON and received an empty body. Having a setting to enable the feature would be the very least to do while keeping default behaviour.

**Comment by daudimeck** [comment]
is there a way to allow the passing of the body to the auth endpoint at the moment?

**Comment by jamct** [comment]
I just added PR #6669. It adds a new parameter forwardBody (boolean) to activate forwarding of the request body.

**Comment by jbdoumenjou** [comment]
Hello,

As Traefik does not currently forward the body to the authentication server, I close this proposal.
