### ISSUE TITLE
Allow to add custom tags to InfluxDB metrics

### ISSUE THREAD

**Issue by zvymazal** [traefik/traefik#6301]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to be able to configure custom tags on metrics sent to InfluxDB. For cases where there are multiple servers and/or multiple environments this is an essential feature. Without the ability to filter metrics on host or environment there's no point collecting them.

**Comment by kevinpollet** [comment]
Closed by #8308
