### ISSUE TITLE
Existing ingressRoute + Traefik + Let's Encrypt = ?Race Condition?

### ISSUE THREAD

**Issue by LelandSindt** [traefik/traefik#6368]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Build K3s cluster, Configure appropriate DNS to public IP, Port forward 443 to K3s cluster from Public IP.

2. Deploy application. 
https://github.com/LelandSindt/iftttGateway/tree/d12e1f2d52c4f206bf6816d098c95adb9f0d7352

3. Deploy Traefik 
https://github.com/LelandSindt/traefik-helm-chart/tree/acfa50a74b505e1fe15197e482a5c41006de116f

### What did you expect to see?

Traefik to come online and complete the Let's Encrypt challenge/registration. 

### What did you see instead?

Traefik comes online and the Let's Encrypt challenge/registration fails.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.1.3
```

https://github.com/LelandSindt/traefik-helm-chart/blob/acfa50a74b505e1fe15197e482a5c41006de116f/traefik/values.yaml#L4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See links in above description. 

### If applicable, please paste the log...
```
time="2020-02-24T03:30:24Z" level=info msg="Configuration loaded from flags."
time="2020-02-24T03:30:33Z" level=error msg="Unable to obtain ACME certificate for domains \"my.domain.org\": unable to generate a certificate for the domains [my.domain.org]: acme: Error -> One or more domains had a problem:\n[my.domain.org] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Connection refused, url: \n" rule="Host(`my.domain.org`) && PathPrefix(`/`)" providerName=myresolver.acme routerName=route-name-asdf123zxy@kubernetescrd
time="2020-02-24T03:40:25Z" level=warning msg="A new release has been found: 2.1.4. Please consider updating."

```

### Work around... 

-  Bring Traefik online before my application. 
or
- Delete and Re-Apply my ingressRoute after Traefik is online.

**Comment by LelandSindt** [comment]
Similar(if not the same) issue: https://github.com/containous/traefik/issues/2670 (older version)

**Comment by LelandSindt** [comment]
Also worth noting... When following the [user guide](https://docs.traefik.io/user-guides/crd-acme/) closely the order and pace of the instructions ensure that Traefik is online/ready before the ingressRoutes are applied. -- It was not until I followed these directions closely that I realized the nature of the failure.

**Comment by sdelicata** [comment]
Hello!
I close this issue as it targets an unsupported version of Traefik.
Feel free to re-open it or join our [Community Forum](https://community.traefik.io/).
