### ISSUE TITLE
X-Forwarded-Proto uses non official(?) values wss and ws for WebSockets

### ISSUE THREAD

**Issue by BernhardGruen** [traefik/traefik#6388]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?

I tried to use sslProxyHeaders to set X-Forwarded-Proto to https. For WebSocket Requests the value was automatically changed to wss. This is done in middlewares/forwarded_header.go

This leads to a problem in Tomcat 9 because Tomcat does not recognize a value of wss in the X-Forwarded-Proto field. Only the values http and https are allowed there.

Also the specification https://tools.ietf.org/html/rfc7239 does not specify the values ws or wss but only http and https.

So it seems this could be a bug in Traefik 2.1.4 (and maybe many other versions).

### What did you expect to see?

I expected that Traefik does not change the X-Forwarded-Proto from https to wss.

### What did you see instead?

Traefik changed X-Forwarded-Proto from https to wss for a WebSocket connection (wss://)

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.1.4

### Workaround

We switched to customRequestHeaders to set this header manually to https.

**Comment by juliens** [comment]
Thx for your report!

I can't find in the specification that the X-Forwarded-Proto MUST be only HTTP or HTTPS.

I find that we can use every registered scheme (https://tools.ietf.org/html/rfc7239#section-5.4)

And it seems that `ws` and `wss` are scheme registered (https://tools.ietf.org/html/rfc6455#section-11.1)

**Comment by dtomcej** [comment]
@BernhardGruen, be aware that the `Forwarded` header referenced in RFC 7239 is not the same as `X-Forwarded-*` headers 😄

**Comment by bradjones1** [comment]
Refs: https://github.com/rancher/rancher/issues/25061

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by bradjones1** [comment]
What's the automation to re-open this?

**Comment by skobow** [comment]
Hi! This issue really gave me a hard time today when I migrated a Spring Boot service from nginx ingress to traefik. After the switch websocket connections to the service failed with 500 Internal Server Error. Looking at the logs I could see stack traces from a `IllegalArgumentException` occurring in the `org.apache.tomcat.websocket.server.WsHandshakeRequest` class. Digging deeper in that issue I could find out that `wss` as schema was the cause of that exception:

        if ("http".equals(scheme)) {
            uri.append("ws");
        } else if ("https".equals(scheme)) {
            uri.append("wss");
        } else {
            // Should never happen
            throw new IllegalArgumentException(
                    sm.getString("wsHandshakeRequest.unknownScheme", scheme));
        }

The scheme of the request object gets set Spring's `ForwardedHeaderFilter`. So `wss` as scheme is not supported when using this setup. So either the WsHandshakeRequest should be adapted accordingly or `wss` should not be used for that header.

As a workaround I had to define a router especially for the websocket path and remove the x-forwarded-proto header with a customRequestHeaders middleware. It could also be set to `https` as @BernhardGruen suggested.

**Comment by gvdhoven** [comment]
@skobow can you share your Traefik configuration specifically for (Secure)websockets?

**Comment by gvdhoven** [comment]
I now have this, but this doesn't work:
```
    labels:
      # Enable traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router: image-specific
      - "traefik.http.routers.network-emqx.rule=Host(`mqtt.at.mydomain.com`)"
      - "traefik.http.routers.network-emqx.entrypoints=websecure"
      - "traefik.http.routers.network-emqx.tls=true"
      - "traefik.http.routers.network-emqx.tls.certresolver=leresolver"
      - "traefik.http.services.network-emqx.loadbalancer.server.port=8084"
```

(the MQTT broker EMQX is running WSS on port 8084 - i am not exposing WS externally)

**Comment by skobow** [comment]
@gvdhoven here is my config as toml file:

```
[http]
  [http.routers]
    [http.routers.my-router]
    rule = "Host(`my-service.net`)"
    service = "my-service"
    [http.routers.my-router.tls]
      certResolver = "le"

  [http.routers.my-router-ws]
    rule = "Host(`my-host.net`) && Path(`/path/to/ws«`)"
    service = "my-servicet"
    middlewares = ["reduced-forward-headers"]
    [http.routers.my-router-ws.tls]
      certResolver = "le"

  [http.middlewares]
    [http.middlewares.reduced-forward-headers.headers]
      [http.middlewares.reduced-forward-headers.headers.customRequestHeaders]
        X-Forwarded-Proto = ""
        Origin = ""

  [http.services]
    [http.services.my-service.loadBalancer]
      [[http.services.my-service.loadBalancer.servers]]
        url = "http://my-service-internal:8080"
```

The important part is the second router `my-router-ws` as it applies the middleware `reduce-forward-headers` that finally removes the `X-Forwarded-Header`.

**Comment by jspdown** [comment]
As stated by @juliens and @dtomcej, there's no specification for `X-Forwarded-Proto`. The closest form of specification would be the [RFC-7239](https://tools.ietf.org/html/rfc7239#section-5.4) for the `Forwarded` header. Possible values for `proto` are defined as:

> registered with IANA according to [RFC4395].  Typical values are "http" or "https".

`ws` and `wss` are both [IANA registered](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml). 

As implementations commonly accept `X-Forwarded-Proto` to be set to something else than `http` or `https` and since projects such as tomcat are progressively allowing it, this becomes a defacto standard.
