### ISSUE TITLE
[metrics] InfluxDB v2 support

### ISSUE THREAD

**Issue by mgrzybek** [traefik/traefik#6389]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

For instance `traefik` can send metrics to `InfluxDB 1.x`. Their new version is available as beta.
It could be nice to support a v2 endpoint and avoid using `telegraf` and their `InfluxDB v1` listener as a proxy to `InfluxDB v2`.

**Comment by laundmo** [comment]
> Their new version is available as beta.
It is out of beta now.

**Comment by SoulEater45** [comment]
Until recently the v2 of influxdb was only available as a preview, but as of recently it's available generally at hub.docker.com with the `latest` tag. It is still possible to [authenticate using the 1.x username/password](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/) way, but using tokens would bake the configuration and managing much easier.

**Comment by ChappIO** [comment]
We're using influxdb cloud where @SoulEater45's nice workaround doesn't work. So having InfluxDB 2.0 support would be ideal.

**Comment by jamesawebb** [comment]
+1 looking for this since I moved away from nginx as my primary reverse proxy.  I'd like notifications when the proxy isn't running (as expected).

Failing that, I can have `telegraf` ingest JSoN metrics exported through the API.
