### ISSUE TITLE
CLI to check/validate a configuration

### ISSUE THREAD

**Issue by Sprootsy** [traefik/traefik#6451]
### Do you want to request a *feature* or report a *bug*?
  
Feature

### What did you expect to see?

So far the only way I found to validate a configuration file is to run traefik in a container and check if there is any error in the logs. I think that it would be much more user friendly if you could do something like `traefik check args...`, where args could be entrypoints, providers etc..

**Comment by nmengin** [comment]
Hello @Sprootsy,

This proposal was opened a long time ago with almost no traction.
We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.
Thank you @Sprootsy for the suggestion.
