### ISSUE TITLE
forwardAuth middleware: Remove headers

### ISSUE THREAD

**Issue by james-d-elliott** [traefik/traefik#6493]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Ideally for JUST the forwardAuth process, it should be possible to remove headers at your discretion. Specifically if the headers are not useful to the forwardAuth process. If you use a headers middleware to remove it, it also removes it from the final request to the intended service.

For example, the flow desired is this:

Request -> forwardAuth middleware (Bad-Header is removed) -> Check Auth Server -> 200 OK -> request sent to the intended service (Bad-Header is PRESENT).

**Comment by SantoDE** [comment]
Hey @james-d-elliott,

thanks for your interest :-) 

Before we take a decision, may I ask for the use-case? Like, why would you want to have that feature?

Bests

**Comment by james-d-elliott** [comment]
Sure, the specific use case in this instance is a forward auth backend that can't support massive headers, when a massive header is likely to exist in a majority of transactions.

Thinking about this in more detail, I think it might be more logical to be able to apply a middleware only to the forward auth process and not the intended service. It would probably be easier to implement, and probably more useful for more people.

**Comment by notsureifkevin** [comment]
@james-d-elliott Greetings! Thank you for taking the time to open the issue and explain your use case. It's possible that a change made recently will address your requirements. Would you please take the time to confirm this? Please take a look at https://github.com/traefik/traefik/pull/7226 when you have a moment.

_kc

**Comment by james-d-elliott** [comment]
I believe you're correct, I will not hesitate to reopen if when it gets released. Does Contanious publish master branch as a docker image or should I just build myself?

**Comment by jbdoumenjou** [comment]
Hi @james-d-elliott , 

You can use carefully the `containous/traefik:experimental-v2.3` as it will change at each commit on master.
I encourage you to read the building & testing [documentation](https://doc.traefik.io/traefik/contributing/building-testing/).

Thank you for confirming the status of the issue. :+1: 

I close it accordingly.
