### ISSUE TITLE
Add SPNEGO to outgoing http requests

### ISSUE THREAD

**Issue by bothejjms** [traefik/traefik#6583]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to use Traefik to help authenticating outgoing requests of an application.
I have an http server which requires client authentication using SPNEGO and I have applications which I would like to connect to the server but unfortunately that application doesn't support connecting with SPNEGO authentication and I can't change that app to support SPNEGO.

I would like to use Traefik as a sidecar http proxy which adds SPNEGO auth header to the outgoing http requests.

I have created a fork where I could add an additional middleware to the load balancer to add SPNEGO. 
Do you see any other ways to do that?
I would be happy to contribute this additional functionality.

**Comment by sandy2008** [comment]
@sokoide added a PR(#6583) for this.

**Comment by ddtmachado** [comment]
As it's possible now to implement this kind of authentication middleware as a plugin for Traefik I'm closing the request.

A more detailed justification can be found on [this comment](https://github.com/traefik/traefik/pull/8041#issuecomment-1167775937) closing the associated PR
