### ISSUE TITLE
[Feature Request] middlewares for tcp routers

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [traefik/traefik#6684]
Feature

### What did you expect to see?

TCP routers to support middlewares.

See #5680

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by J7mbo** [comment]
Hey @natlibfi-arlehiko - I _think_ I need this in order to have any chance of this being looked at, please could you use the feature request template as described by the bot or else close the issue and I'll do it myself? This feature is important to me...

**Comment by natlibfi-arlehiko** [comment]
> Hey @natlibfi-arlehiko - I _think_ I need this in order to have any chance of this being looked at, please could you use the feature request template as described by the bot or else close the issue and I'll do it myself? This feature is important to me...

'tis done.

**Comment by gkrizek** [comment]
Big +1 on this. I would love to have IPWhitelisting and RateLimiting in the TCP Routers.

**Comment by modem7** [comment]
+1 on this one - for me it's purely the authentication middleware on TCP Routers that I'm after! Thanks!

**Comment by mailbyms** [comment]
> I would love to have IPWhitelisting and RateLimiting in the TCP Routers.

Yes，it would be very useful.
We want to expose  mysql 3306 only to intranet. Sure iptables can do it, by traefik would be more elegant.

**Comment by modem7** [comment]
Just to keep this on the radar, do we know if this is being actively worked on currently, or is it on the back-burner for higher priority projects? 

Thanks!

**Comment by tnelson-doghouse** [comment]
Looks like this has been completed (by rtribotte - thanks rtribotte!), but:

- For some reason, it's marked as 2/3 tasks complete (have asked on the PR for an update)
- It has a merge conflict
- It needs to be reviewed by someone with write access

For the record, I'd like this too.
