### ISSUE TITLE
Traefik not read updated certificate stored on consul on just one node

### ISSUE THREAD

**Issue by Tifeo** [traefik/traefik#6742]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Trying to connect to my site, manually modifying each time the hosts file and target the site to all the nodes of the swarm, one at time. Pointing the hosts file statically to node 1 and node 2 go fine, and the correct renewed certificate is obtained. Only for node 3 I obtain the old certificate.

### What did you expect to see?
On node 1 and node 2 I obtain : 
```
time="2020-04-28T19:57:10Z" level=info msg="Skipping same configuration for provider docker"
time="2020-04-28T19:57:11Z" level=debug msg="Looking for an existing ACME challenge for ..."
time="2020-04-28T19:57:11Z" level=debug msg="Looking for provided certificate to validate ..."
time="2020-04-28T19:57:11Z" level=debug msg="No provided certificate found for domains ..., get ACME certificate."
time="2020-04-28T19:57:11Z" level=debug msg="ACME got domain cert ...."
```

### What did you see instead?
Only on the swarm node 3 I obtain : 
```
time="2020-04-28T20:17:07Z" level=debug msg="Configuration received from provider docker: {}"
time="2020-04-28T20:17:07Z" level=info msg="Skipping same configuration for provider docker"
time="2020-04-28T20:17:11Z" level=debug msg="Looking for an existing ACME challenge for ..."
time="2020-04-28T20:17:11Z" level=debug msg="Looking for provided certificate to validate ..."
time="2020-04-28T20:17:11Z" level=debug msg="No provided certificate found for domains ...., get ACME certificate."
time="2020-04-28T20:17:11Z" level=debug msg="ACME got domain cert .......it"
time="2020-04-28T20:17:11Z" level=debug msg="http: TLS handshake error from 192.168.0.133:57672: remote error: tls: bad certificate"
```
### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:1.7.20
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

3-nodes swarm cluster; consul as provider.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by mpl** [comment]
Hello,

Please provide all the relevant configuration and your workflow.

**Comment by Tifeo** [comment]
Good morning,
 this is the traefik.toml used :

**Comment by Tifeo** [comment]
I've also tried to follow the procedure below for removing a certificate from consul but all the 3 traefik still offer the cached certificate (CTRL+F5 done)

```
export CONSUL_HTTP_ADDR=consul:8500
```
# get value from consul and store it to acme.json
consul kv get traefik/acme/account/object | gzip -dc > acme.json

# remove invalid domain and store it to acme-fixed.json
cat acme.json | jq -r 'del (.DomainsCertificate.Certs[] | select(.Domains.Main=="'yourdomain.com'"))' > acme-fixed.json
```

# gzip it
cat acme-fixed.json | gzip -c > acme-fixed.json.gz
```

# upload fixed and gzipped json back to consul
consul kv put traefik/acme/account/object @acme-fixed.json.gz

```

**Comment by mmatur** [comment]
Hello,

This bug is linked to a feature that no longer exists in the supported versions of Traefik.

Closing accordingly.

Please feel free to re-open it if necessary.
