### ISSUE TITLE
Overwriting already received UDP messages

### ISSUE THREAD

**Issue by cbachert** [traefik/traefik#6796]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
- Run traefik as reverse proxy for iperf3 TCP and UDP traffic: `docker-compose up reverse-proxy`
- Run iperf3 server: `docker-compose up iperf3server`
- Run iperf3 client over UDP and with 128 Kbps speed limit: `docker-compose up iperf3client`

### What did you expect to see?
- No duplicated datagrams

### What did you see instead?
- Duplicated datagrams
- When receiving multiple packets in short succession, it looks like traefik may overwrite the data of earlier packets with the data of the current one
- Another application showed similar behaviour: Sending a 15 Byte and a 5 Byte UDP packet with the following data to traefik ...
  26:10:62:c8:55:44:12:9f:00:00:02:03:03:09:00
  2c:00:00:00:00
  ... leads to traefik sending the following 15 Byte and 5 Byte data packets to the backend:
  2c:00:00:00:00:44:12:9f:00:00:02:03:03:09:00
  2c:00:00:00:00
  - It looks like the first five Bytes of the buffer for the 15 Byte packet were overwritten with the data of the previous packet 
- I believe that already appended messages in c.msgs may be overwritten with the next ReadFrom(buf) in case Read() has not collected them yet. See also minimal example at https://play.golang.org/p/d2kCTzCuU6l and PR #6797.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```
### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.udp5001]
    address = ":5001/udp"
  [entryPoints.tcp5001]
    address = ":5001/tcp"
[log]
  level = "DEBUG"
[api]
  insecure = true
  dashboard = true
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
```

```docker-compose.yml
version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # iperf UDP
      - "5001:5001/udp"
      # iperf TCP
      - "5001:5001/tcp"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/etc/traefik/traefik.toml"
  iperf2server:
    image: mlabbe/iperf:2.0.10-r1
    command: "-V -s -u -p 5002"
    ports:
      - "5002/tcp"
      - "5002/udp"
    labels:
      - "traefik.udp.routers.router-udp5001.entrypoints=udp5001"
      - "traefik.udp.services.iperfserver.loadbalancer.server.port=5002"
      - "traefik.tcp.routers.router-tcp5001.entryPoints=tcp5001"
      - "traefik.tcp.routers.router-tcp5001.rule=HostSNI(`*`)"
      - "traefik.tcp.services.iperfserver-tcp.loadBalancer.server.port=5002"
  iperf3server:
    image: networkstatic/iperf3
    command: "-V -s -p 5002"
    ports:
      - "5002/tcp"
      - "5002/udp"
    labels:
      - "traefik.udp.routers.router-udp5001.entrypoints=udp5001"
      - "traefik.udp.services.iperfserver.loadbalancer.server.port=5002"
      - "traefik.tcp.routers.router-tcp5001.entryPoints=tcp5001"
      - "traefik.tcp.routers.router-tcp5001.rule=HostSNI(`*`)"
      - "traefik.tcp.services.iperfserver-tcp.loadBalancer.server.port=5002"
  iperf2client:
    image: mlabbe/iperf:2.0.10-r1
    command: "-V -c reverse-proxy -u -b 10M -l 1450 -p 5001"
    labels:
      - "traefik.enable=false"
  iperf3client:
    image: networkstatic/iperf3
    command: "-V -c reverse-proxy -u -b 128k -l 1450 -p 5001"
    labels:
      - "traefik.enable=false"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
See logs from traefik, iperf server and iperf client attached in [overwriting_already_received_UDP_messages.zip](https://github.com/containous/traefik/files/4618741/overwriting_already_received_UDP_messages.zip)
See traefik_iperf_udp_export.pcap for a packet capture which shows the duplicated packets. First occurrence are packets 56 and 57.

**Comment by rtribotte** [comment]
closed by #6797
