### ISSUE TITLE
check permissions of acme.json and attempt reconcilation to 0600 before aborting provider registration

### ISSUE THREAD

**Issue by kevtainer** [traefik/traefik#6825]
### Feature

Consider reconciling `acme.json` file permissions when they've deviated from `0600`.

### Why?

Certain underlying file systems / storage drivers in orchestrated platforms modify file permissions upon association, such as `local-storage`, among others according to: https://github.com/kubernetes/kubernetes/issues/2630

This will, in effect, fix https://github.com/containous/traefik-helm-chart/issues/164

### Drawbacks

Operators may wish to reconcile this themselves as awareness of a permission change on this file could be indicative of a security breach. Should this behavior be toggle-able through config? Alternatively, should we just expose the ability for operators to configure their own init containers in our helm chart so they may reconcile this themselves (among other things, such as waiting for a telemetry service to be available, etc)? The limitation with the above approach is that it is a specific platform fix whereas this might be a desired behavior for installations other than kubernetes.

**Comment by notsureifkevin** [comment]
Discussion highlight:

* @dtomcej recommended we absolve the permission check.
* there was mixed reception to this idea, discussion will be revisited during the next daily
* the reasons this was implemented in the first place were not entirely clear to the group

My take-away:

After consideration, reconciliation should ideally not be automated (the operator should be aware of the state of their file system). This leaves us in the position of introducing init-containers to the helm chart, which could introduce other considerations, but that still leaves this issue unsolved for other platforms which may not have such capability.

Should we consider introducing a configuration flag which disables this check, so the operator can opt-out if their underlying file system implementation does "weird things"?

**Comment by lexfrei** [comment]
Any news?

**Comment by ddtmachado** [comment]
Hi @lexfrei, the Helm chart scripts was updated recently to cover for this, available in the chart version >= 14.0.1.
