### ISSUE TITLE
Support Kubernetes Ingress Path updates for 1.18

### ISSUE THREAD

**Issue by dtomcej** [traefik/traefik#6830]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Kubernetes 1.18 changed how some of the path rules and matching works.

We need to update the ingress provider to allow for this to work.
```
ImplementationSpecific (default): With this path type, matching is up to the controller implementing the IngressClass. Implementations can treat this as a separate pathType or treat it identically to the Prefix or Exact path types.
Exact: Matches the URL path exactly and with case sensitivity.
Prefix: Matches based on a URL path prefix split by /. Matching is case sensitive and done on a path element by element basis.
```

From https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

**Comment by rtribotte** [comment]
fixed by #7087
