### ISSUE TITLE
Traefik should not serve requests for hosts which do not have a configuration defined

### ISSUE THREAD

**Issue by sudoforge** [traefik/traefik#6848]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm just getting started with Traefik, and am playing around with running it as a local server to handle various docker images I may or may not start up. As part of this, I am exploring having it handle traffic on ports 80 & 443, and am running into a bit of a snag.

**Static Configuration**

```
web:
  address: ":8080"

providers:
  docker: {}

api:
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80/tcp"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: "https"
  websecure:
    address: ":443/tcp"
```

**Starting the container**

```
docker run --rm \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v path/to/config.yml:/etc/traefik/traefik.yml:ro \
    --name traefik traefik:2.2.1
```

### What did you expect to see?

Nothing, really, as I have not configured any routes or services (other than the WebUI and API). The issue, instead, surfaces when browsing the web.

### What did you see instead?

While the above container is running, when browsing the web, I encounter many "invalid certificate" errors. These show up in Traefik's logs, too:

```
<snip>
time="2020-05-25T17:12:56Z" level=debug msg="No default certificate, generating one"
time="2020-05-25T17:14:47Z" level=debug msg="Serving default certificate for request: \"localhost\""
time="2020-05-25T17:14:47Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58378: remote error: tls: unknown certificate"
time="2020-05-25T17:14:50Z" level=debug msg="Serving default certificate for request: \"localhost\""
time="2020-05-25T17:16:15Z" level=debug msg="Serving default certificate for request: \"www.googletagservices.com\""
time="2020-05-25T17:16:15Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58392: remote error: tls: unknown certificate"
time="2020-05-25T17:16:20Z" level=debug msg="Serving default certificate for request: \"www.google-analytics.com\""
time="2020-05-25T17:16:20Z" level=debug msg="Serving default certificate for request: \"sb.scorecardresearch.com\""
time="2020-05-25T17:16:20Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58396: remote error: tls: unknown certificate"
time="2020-05-25T17:16:20Z" level=debug msg="Serving default certificate for request: \"secure.quantserve.com\""
time="2020-05-25T17:16:20Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58400: remote error: tls: unknown certificate"
time="2020-05-25T17:16:20Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58404: remote error: tls: unknown certificate"
time="2020-05-25T17:17:03Z" level=debug msg="Serving default certificate for request: \"collector.githubapp.com\""
time="2020-05-25T17:17:03Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58438: remote error: tls: unknown certificate"
time="2020-05-25T17:17:13Z" level=debug msg="Serving default certificate for request: \"collector.githubapp.com\""
time="2020-05-25T17:17:13Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58448: remote error: tls: unknown certificate"
time="2020-05-25T17:17:16Z" level=debug msg="Serving default certificate for request: \"collector.githubapp.com\""
time="2020-05-25T17:17:16Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58470: remote error: tls: unknown certificate"
time="2020-05-25T17:17:19Z" level=debug msg="Serving default certificate for request: \"collector.githubapp.com\""
time="2020-05-25T17:17:19Z" level=debug msg="http: TLS handshake error from 172.17.0.1:58478: remote error: tls: unknown certificate"
```

The reason that this occurs is because I block various tracker and ad domains via `/etc/hosts`, by pointing them to `0.0.0.0` (this uses various adblock lists and is managed via the excellent [`pigmonkey/hostsctl`](https://github.com/pigmonkey/hostsctl) project). This causes requests to those domains to be redirected to my local machine, which Traefik then picks up (because it's listening on port 443 on all interfaces).

Traefik tries to serve `https://some-blocked-domain.com`, which there is no configuration for; in doing this it serves the default certificate created on startup which of course isn't valid for the domain. My browser then throws warnings stating that the certificate is invalid.

I would expect Traefik to do the same thing that other servers do, and simply fail the request. I'm surprised to see that it instead serves the default certificate.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

**Comment by sudoforge** [comment]
An example of my `/etc/hosts` file is:

```
➜ grep 'collector\.github' /etc/hosts
0.0.0.0 collector.githubapp.com
```

You'll notice that `collector.githubapp.com` is one of the domains visible in the log snippet included in the original issue comment.

**Comment by mpl** [comment]
Hi.

What do you mean when you expect Traefik to "fail the request"? Do you mean that Traefik should just drop it and not answer at all?

**Comment by dtomcej** [comment]
Hello @sudoforge,

If the issue you are encountering is that Traefik serves a default certificate when no matching certificate is present, that is intended behavior.

If you would only like Traefik to use valid matching certificates for requests, you can use the SNI Strict setting to ensure that only matching certificates will be returned:

https://docs.traefik.io/v2.2/https/tls/#strict-sni-checking

Please let us know if this helps.

**Comment by sudoforge** [comment]
@mpl 

> What do you mean when you expect Traefik to "fail the request"? Do you mean that Traefik should just drop it and not answer at all?

Yes, that is what I would expect / am asking for.

---

@dtomcej 

> If the issue you are encountering is that Traefik serves a default certificate when no matching certificate is present, that is intended behavior.

Hm, alright. It seems like this prevents me from being able to use Traefik locally like I have described in the original comment. Is there a way to disable this behavior?

> If you would only like Traefik to use valid matching certificates for requests, you can use the SNI Strict setting to ensure that only matching certificates will be returned:

I don't think this is working as I assumed it would based on your comment. This is part of the _dynamic configuration_, and as far as I understand is not something that applies to all requests. Is that correct?

**Comment by ddtmachado** [comment]
Hello @sudoforge,

>Hm, alright. It seems like this prevents me from being able to use Traefik locally like I have described in the original comment. Is there a way to disable this behavior?

No, as described by @dtomcej it is intended and not configurable at this time. What you can, and should, do is set Traefik to listen on a specific address on your host machine, this could be applied to your ad-block tools as well to avoid any conflicts.

To do that just change the `address`  in your entrypoints definitions, like:

```yaml
entryPoints:
  websecure:
    #Address/interface + port that Traefik will bind to.
    address: '10.0.1.1:443'
``` 

Let us know if this approach would work in your use case.

>I don't think this is working as I assumed it would based on your comment. This is part of the dynamic configuration, and as far as I understand is not something that applies to all requests. Is that correct?

TLS options are used by dynamic configuration, but they are actually global, enabling then to be reused. In this sense its also supported on the entrypoint in the static config. See an example [here](https://docs.traefik.io/v2.2/routing/entrypoints/#tls)

**Comment by sudoforge** [comment]
@ddtmachado 

I suppose that configuring the entrypoint to listen on a unique could work, however, I see this as a hack as it's not really portable -- if I connect to a different network that happens to be on whatever address I define, I'll suddenly have the same problem (or I'll need to make sure that the IP I define is never part of any network I connect to, which is unfeasible).

Would the `traefik` project accept a patch that introduced a configuration option that disabled the automatic handling of requests that don't have explicit dynamic configurations?

**Comment by lpefferkorn** [comment]
Hello,

I would also support such option, besides the original issue described above the current behavior allows to identify traefik on a remote host just by connecting directly to the ip:

```
% curl -vk https://163.172.xx.yy
*   Trying 163.172.xx.yy...
* TCP_NODELAY set
* Connected to 163.172.xx.yy (163.172.xx.yy) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: Jun 25 20:20:44 2020 GMT
*  expire date: Jun 25 20:20:44 2021 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa6fb008600)
> GET / HTTP/2
> Host: 163.172.xx.yy
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Thu, 25 Jun 2020 20:21:51 GMT
<
404 page not found
* Connection #0 to host 163.172.xx.yy left intact
* Closing connection 0
```

**Comment by cookandy** [comment]
I agree with having an option to disable the default cert for unknown sites. 

As others have mentioned, it's very easy to determine what kind of web server is running when the `TRAEFIK DEFAULT CERT` is shown. 

It also responds to TLSv1 requests, even with `minVersion: VersionTLS12` set as a TLS Option.

**Comment by willymilkytron** [comment]
We started phasing out our traefik infrastructure because of this (and other issues) in favor of nginx which is able to provide this functionality since 1.19.4 https://trac.nginx.org/nginx/changeset/59e1c73fe02b3a227717630fa7fa8b3cad5d3cc4/nginx

**Comment by Sidewinder53** [comment]
The original request was solved with the sniStrict option (as described by @dtomcej)
Enabling this option will no longer expose the default certificate if there is no matching certificate defined:

```
$ curl -vk https://xxx.xxx.xxx.xxx/
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, Server hello (2):
* error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

I believe this issue is solved and should be closed.

**Comment by MarkErik** [comment]
@Sidewinder53 Where is the correct place for the sniStrict flag?
I've placed the following code in my traefik.toml file, however traefik still serves the default certificate.
```
[tls.options]
  [tls.options.default]
    sniStrict = true
```
Thank you for any advice!

**Comment by Tyilo** [comment]
> @Sidewinder53 Where is the correct place for the sniStrict flag?
> I've placed the following code in my traefik.toml file, however traefik still serves the default certificate.
> ```
> [tls.options]
>   [tls.options.default]
>     sniStrict = true
> ```
> Thank you for any advice!

You should put it in your dynamic configuration and not your static configuration, i.e. a new file.
I was also confused by this at first.

**Comment by MarkErik** [comment]
@Tyilo Thank you for your quick response. Indeed that fixed the issue.
(I'll describe below what I did in case anyone else comes here looking for the solution).

I created a new file called 'sni.toml' (called it sni for reference - can be anything) in my /conf directory and placed the following 3 lines in it:
```
[tls.options]
  [tls.options.default]
    sniStrict = true
```

And had the following in my traefik.toml file:
```
[providers.file]
  directory = "/conf/"
  watch = true
```

**Comment by sudoforge** [comment]
From @ddtmachado in [this comment](https://github.com/traefik/traefik/issues/6848#issuecomment-637773617):

> TLS options are used by dynamic configuration, but they are actually global which enable them to be reused. In this sense its also supported on the entrypoint in the static config.

It would appear that your experience conflicts with this statement, @Tyilo -- which lines up with my experience (which is one reason I moved away from experimenting with Traefik).

**Comment by ddtmachado** [comment]
@sudoforge sorry if I was not clear enough on that statement, but I don't think it conflicts. I was trying to create awareness on the fact that the tls options when declared are global in the sense that they are available to any router and you can cross-reference then. For example when using kubernetesCRD you can define them on a dynamic [toml] like @MarkErik example and then use it on your `ingressRoute` as `tlsoptionname@file`.

I understand it can be quite confusing sometimes as you declare it on the provider dynamic config, such as File, CRD etc, but **can** use it on the `entrypoint` inside your static configuration.
