### ISSUE TITLE
traefik needs a JSON configuration schema

### ISSUE THREAD

**Issue by ssbarnea** [traefik/traefik#6869]
At this moment is very easy to make configuration mistakes because there no schema to validate its configurations. Even tools like docker-compose do publish such schemas, which can be used by various editors to validate configuration while user is editing it (even provide auto-complete information).

Avoid being mislead by the term "JSON Schema", as this can be used to validate YAML and TOML too.

References:
* https://json-schema.org/ - schema specification
* https://www.schemastore.org/json/ - best public store for schemas, helps users and tools discover schemas (does not require publishing schema content inside, can be linked)
* https://raw.githubusercontent.com/docker/cli/master/cli/compose/schema/data/config_schema_v3.8.json - Example of docker-compose schema from their own repo
* https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml - a very popular YAML extension for vscode which makes use of json schemas to validate files.

**Comment by PierreAdam** [comment]
This looks to me like being essential to avoid mistakes in configuration.

**Comment by dhruvin2910** [comment]
Does this [PR](https://github.com/SchemaStore/schemastore/pull/1216) close this issue?

**Comment by nirname** [comment]
I think there is also a great need in validating file provider with json schema

**Comment by dhruvin2910** [comment]
I agree. I'll see if I can submit a PR there.

**Comment by dhruvin2910** [comment]
While implementing said schema, which is almost done, except these issues. It'd be great if someone can clarify these.
(I think the documentation is correct and the reference files need to be changed.)

1. [accessControlAllowOrigin](https://github.com/traefik/traefik/blob/714a4d4f2d7a963e3e3dee2bf22d51a8f62bde0b/docs/content/reference/dynamic-configuration/file.yaml#L179) is defined in reference but is not documented in [headers](https://github.com/traefik/traefik/blob/master/docs/content/middlewares/headers.md) middleware documentation.

2. [info.serialNumber](https://github.com/traefik/traefik/blob/714a4d4f2d7a963e3e3dee2bf22d51a8f62bde0b/docs/content/reference/dynamic-configuration/file.yaml#L259) is defined in reference but is not documented in [passTLSClientCert](https://github.com/traefik/traefik/blob/master/docs/content/middlewares/passtlsclientcert.md) middleware documentation.

**Comment by ssbarnea** [comment]
Maybe I should mention that the JSON file does not necessarily need to be hosted on json-schema.org, it is enough to only define it there and point to an external URL for downloading the schema. That is very useful if schema is generated by the code and kept in sync with code. Still, that would also require a CI pipeline for testing its validity so any option is better than no option, as it can easily be swapped later.

@dhruvin2910 A big thanks for driving this!!!

**Comment by dhruvin2910** [comment]
Yes. In past, in tried using [this](https://github.com/alecthomas/jsonschema) for config structs defined in go.
But the structs then become a bit dense and harder to maintain later.
It also requires some knowledge of json-schema for a developer to contribute to the configuration section of traefik.
I thought the pain outweighed the payouts. I may be wrong.

If the community thinks we should go that way, I'm all in. For both the static and dynamic file config.

**Comment by dhruvin2910** [comment]
https://github.com/SchemaStore/schemastore/pull/1299 closes this issue.

**Comment by SantoDE** [comment]
Ping @ssbarnea - as the PR mentioned by @dhruvin2910 is merged, are you okay with us closing the issue?
