### ISSUE TITLE
Traefik doesn't pick up Marathon pods configuration

### ISSUE THREAD

**Issue by nikotrone** [traefik/traefik#6889]
### Do you want to request a *feature* or report a *bug*?

Feature request

### What did you do?

I am feeding Traefik conf using the Marathon provider. It works as intended when dealing with single containers but it doesn't seem to understand/pickup the conf when dealing with pods in marathon.

Here is my pod configuration in DCOS/Marathon:
```
{
  "labels": {
    "traefik.frontend.entryPoints": "http,https",
    "traefik.enable": "true"
  },
  "id": "/test/pod-app-test",
  "version": "2020-06-02T12:34:59.257Z",
  "containers": [
    {
      "name": "some-webapp-test",
      "resources": {
        "cpus": 0.1,
        "mem": 128,
        "disk": 0
      },
      "image": {
        "kind": "DOCKER",
        "id": "nginxdemos/hello"
      }
    },
    {
      "name": "sidecar-container",
      "resources": {
        "cpus": 0.1,
        "mem": 128,
        "disk": 0
      },
      "image": {
        "kind": "DOCKER",
        "id": "alpine"
      },
      "exec": {
        "command": {
          "shell": "sleep 600000000"
        }
      }
    }
  ],
  "networks": [
    {
      "mode": "host"
    }
  ],
  "scaling": {
    "instances": 1,
    "kind": "fixed"
  },
  "scheduling": {
    "placement": {
      "constraints": []
    }
  },
  "executorResources": {
    "cpus": 0.1,
    "mem": 32,
    "disk": 10
  },
  "volumes": [],
  "fetch": []
}
```

### What did you expect to see?

I expected Traefik to create an entrypoint to access those containers from outside the cluster. 
In the Traefik source code I see there are some mocks setup for pods testing, but as far as i can see there are no tests of functions to implement that behaviour, also i don't see any trace in the documentation about Marathon pods.
Am I right or am I missing something?

### What did you see instead?

Nothing shows up in the traefik dashboard

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.24
Codename:     maroilles
Go version:   go1.14.1
Built:        2020-03-25_04:34:11PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I am running Traefik in a docker container on DCOS. The scheduler we use is Marathon, which is also the conf provider for traefik

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Don't think it is relevant but i can do it if needed

**Comment by nikotrone** [comment]
Thanks for prioritizing this issue, may i ask what P2 means? I ask just because we have a dependancy on it to implement a container security tool that runs as sidecar container.

**Comment by SantoDE** [comment]
P2 means, that we will implement it eventually but not with the next release.

**Comment by nikotrone** [comment]
Thanks for the explanation :)

**Comment by rtribotte** [comment]
Hello,

In the upcoming major version of Traefik (v3), support for the Marathon provider is being dropped.
Due to this change, we won't be able to accept or work on new features related to the Marathon provider.
For this reason, we are closing this issue.
