### ISSUE TITLE
When service timeout, Field OriginStatus should be empty

### ISSUE THREAD

**Issue by chzhuo** [traefik/traefik#6930]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

When service timeout, AccessLog field `OriginStatus` is 502

### What did you expect to see?

When service timeout, AccessLog field `OriginStatus` should be  empty,  Because service not return anything

### What did you see instead?

AccessLog field OriginStatus is 502

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64
```

I found this code in https://github.com/containous/traefik/blob/master/pkg/middlewares/accesslog/field_middleware.go#L59
```go
// AddOriginFields add origin fields.
func AddOriginFields(rw http.ResponseWriter, req *http.Request, next http.Handler, data *LogData) {
	crw := newCaptureResponseWriter(rw)
	start := time.Now().UTC()

	next.ServeHTTP(crw, req)

	// use UTC to handle switchover of daylight saving correctly
	data.Core[OriginDuration] = time.Now().UTC().Sub(start)
	data.Core[OriginStatus] = crw.Status()
	// make copy of headers so we can ensure there is no subsequent mutation during response processing
	data.OriginResponse = make(http.Header)
	utils.CopyHeaders(data.OriginResponse, crw.Header())
	data.Core[OriginContentSize] = crw.Size()
}
```
When service timeout `crw.Status()` is not the origin status

**Comment by mpl** [comment]
@chzhuo Hello.

We changed quite a few things in the code, with respect to the capture response writer (in the context of #9487 ), and we think it's pretty likely that your issue got fixed as well in the process.
Could you please retry and let us know?
