### ISSUE TITLE
Long regexes doesn't show

### ISSUE THREAD

**Issue by felixsanz** [traefik/traefik#6947]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Use a long regex to mimic a negative lookahead inside a middleware.

### What did you expect to see?

The full regex should be visible

### What did you see instead?

Text is just 1 line and full regex doesn't appear

https://i.imgur.com/PTF0gBG.png

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Not needed

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

Not needed

**Comment by bbcbear** [comment]
Hi @felixsanz !
I'm going to fix this bug.
What do you think would be more appropriate, scroll bar or line break?

**Comment by ldez** [comment]
I'm more thinking about ellipsis and tooltip.

**Comment by bbcbear** [comment]
Ellipsis and [vue snackbars](https://vuetifyjs.com/en/components/snackbars/) looks better. 
This makes it possible to shorten and the same time leave it available for copying.

**Comment by traefiker** [comment]
Closed by #8697.
