### ISSUE TITLE
Add host tag on InfluxDB metrics

### ISSUE THREAD

**Issue by acouvreur** [traefik/traefik#6997]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The actual metrics collection for InfluxDB has 5 tags : code, method, protocol and service/entrypoint.

When working with multiple Traefik instance that store the metrics on the same InfluxDB instance it would be nice to have a way to distinguish who emit which data. 

I suggest adding a tag named `host`. That defaults to the machine hostname. Like many collectors (e.g. telegraf) they include the hostname as a tag (and can be overridden in the config file).

**Comment by philippreston** [comment]
Hey 

We run multiple Traefiks around our environment for different purposes.  Without host tags the native metrics here are un-usable.

Thanks

Phil

**Comment by kevinpollet** [comment]
Closed by #8308
