### ISSUE TITLE
Content-Length is being removed from HEAD requests

### ISSUE THREAD

**Issue by mrbrown-09** [traefik/traefik#7040]
Bug

### What did you do?
- Exposed a service running in docker swarm behind traefik.  
- The service includes a Content-Length header in the response and a transfer-encoding: chunked
- Performed a curl HEAD request against it.
   - `curl -I https://service.traefik.myserver.org`

### What did you expect to see?
Content-Length in the response

The client needs this header to manage the download stream (or multiple parallel streams) and allocate storage prior to transfer.

### What did you see instead?
Traefik 2.1.4:  The content-length header removed, but includes the `transfer-encoding: chunked` header.

Traefik 2.2.4:  The content-length header and `transfer-encoding: chunked` header were both removed

The challenge for this scenario is the HTTP 1.1 spec doesn't appear to have an explicit exception for both headers in HEAD responses, although that sounds like a reasonable exception since there is actually no body content transmitted.  There are also some reports that browsers accept both headers as a hint for progress bars, etc.

From what I was able to determine, it looks like a change would necessary to oxy, https://github.com/vulcand/oxy/blob/master/buffer/buffer.go.

I think a reasonable option for traefik would be configurable options to include the content-length header in HEAD responses with chunked responses, or something along those lines.  I cannot modify the clients to accept a different header name.

Although, after testing under 2.2.4, I'm not sure why both headers were removed.

FYI,  I was able to manually build a recent snapshot of reactor-netty which which no longer sends the transfer-encoding: chunked header when a Content-Length is present in HEAD requests, and the behavior on 2.2.4 seems things seem to be okay.   I am not sure if dropping both of the headers is the appropriate action for 2.2.4.

https://github.com/reactor/reactor-netty/pull/1156

### Output of `traefik version`: (_What version of Traefik are you using?_)

2.1.4  and 2.2.4

**Comment by AndrewSav** [comment]
How do you know that the service includes a Content-Length header in the response? It can depend on protocol in HTTP/2 Content-Length is not mandatory.

**Comment by tburschka** [comment]
I'm facing the same situation: I'm running Jamf Pro using Traefik 2.3.6 as Ingress and this header is been removed from the response but the UI seem to need it to upate the data correctly. Is there any way to bypass the buffer so the `transfer-encoding: chunked` is still in the response?

**Comment by tomMoulard** [comment]
Hello @mrbrown-09,

Thanks for your interest in Traefik!

As the RFC7230 states, you cannot have both `Content-Length` and `Transfer-Encoding` headers in the same message:

> A sender must not send a `Content-Length` header field in any message that
> contains a `Transfer-Encoding` header field.
> ~ https://greenbytes.de/tech/webdav/rfc7230.html#rfc.section.3.3.2.p.3

Also, as `Transfer-Encoding` [is](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) a `hop-by-hop header`, the Golang reverse proxy removes it:

https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L174-L184

https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L305-L307

Moreover, I could not see the `Transfer-Encoding` header on traefik 2.1.4.

Accordingly, the issue will be tagged as a question.
If you feel that I'm missing something here, please let me know.
