### ISSUE TITLE
Consul Catalog does not work without specifying server scheme in a tag

### ISSUE THREAD

**Issue by hongkongkiwi** [traefik/traefik#7217]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using Consul Catalog with Traefik v2.3 using exposed by default and a single service.

**Consul Service Definition**
```
{
  "services": [
    {
      "address": "10.10.0.8",
      "tags": [
        "traefik.http.routers.my-router.rule=Host(`grafana.example.com`)",
        "traefik.http.services.my-service.loadbalancer.server.scheme=http"
      ],
      "enable_tag_override": false,
      "id": "my-service-id",
      "name": "grafana",
      "port": 3000,
      "tagged_addresses": {
        "lan": {
          "address": "10.10.0.8",
          "port": 3000
        }
      },
      "weights": {
        "passing": 1,
        "warning": 1
      }
    }
  ]
}
```

**Traefik Docker Commands**
```
      - --log
      - --log.level=DEBUG
      - --accesslog=true
      - --entryPoints.web.address=:80/tcp
      - --entryPoints.websecure.address=:443/tcp
      - --accesslog=true
      - --providers.consulcatalog=true
      - --providers.consulcatalog.endpoint.address=http://consul:8500
      - --providers.consulcatalog.exposedbydefault=true
```

### What did you expect to see?
Going to *grafana.example.com* should go to my site without any additional tags on the Consul service.

### What did you see instead?
I always get a 404 error, unless I add the service tag:
`traefik.http.services.my-service.loadbalancer.server.scheme=http`

Since my traefik logs show the backend address as "http://10.10.0.3:8300" I would expect it would by default use http to try to access this backend but it doesn't unless I add the tag above.

### Output of `traefik version`:
```
Version:      2.3.0-rc4
Codename:     picodon
Go version:   go1.15
Built:        2020-08-19T16:02:03Z
OS/Arch:      linux/amd64
```e=consulcatalog

**Comment by rtribotte** [comment]
Hello @hongkongkiwi,

Thanks for your interest in Traefik !

In order to investigate your problem it would be great if you can provide the output of the `/api/rawdata` endoint of Traefik (you'll need to [activate it](https://docs.traefik.io/v2.3/operations/api/#configuration)) and also the logs of Traefik.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
