### ISSUE TITLE
Experimental pilot config not working (v2.3-rc6)

### ISSUE THREAD

**Issue by GuillaumeOuint** [traefik/traefik#7306]
# Report a bug

Bug

command traefik error: failed to decode configuration from flags: field not found, node: pilot

### What did you do?

Noting, just reboot 1 instance, all other are OK.

### What did you expect to see?

Just traefik working

### What did you see instead?

command traefik error: failed to decode configuration from flags: field not found, node: pilot

### Output of `traefik version`: v2.3-rc6

All other instances are rc5. Seems that rc6 doesn't support pilot.

```
command traefik error: failed to decode configuration from flags: field not found, node: pilot
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

- '--experimental.pilot.token=token'

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
command traefik error: failed to decode configuration from flags: field not found, node: pilot
```

**Comment by ldez** [comment]
Hello,

We changed this configuration: https://github.com/traefik/traefik/pull/7287

```yaml
pilot:
  token: xxxxx
```
