### ISSUE TITLE
seems wrong document about consul catalog provider usage

### ISSUE THREAD

**Issue by feitian124** [traefik/traefik#7330]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

https://docs.traefik.io/providers/consul-catalog/

the config exampl say after enable consul catalog then i shoud tag service with below tag

```
- traefik.http.services.my-service.rule=Host(`example.com`)
```

![image](https://user-images.githubusercontent.com/1425383/93992407-17056880-fdc0-11ea-96e6-e779d228b352.png)

but it does not work until i changed to 

```
- traefik.http.routers.my-service.rule=Host(`example.com`)
```

and i double checked https://docs.traefik.io/v2.3/reference/dynamic-configuration/consul-catalog/
it does not have labels like `traefik.http.services.my-service.rule` but only `traefik.http.routers.my-service.rule`

then i realized this may be a document issue. 

please confirm if i am right since i waste hours find the reason.
thank you.

**Comment by traefiker** [comment]
Closed by #7332.
