### ISSUE TITLE
IngressRoute resource allows cross-namespace routing by default

### ISSUE THREAD

**Issue by notsureifkevin** [traefik/traefik#7353]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

This is a replication and investigation report for the issue reported in https://github.com/containous/traefik/issues/7151 and discussed on the community forums https://community.traefik.io/t/cross-namespaces-ingressroutes-and-services/7419/19

- Prior to Traefik v2.1, `IngressRoute` was not capable of routing to services outside of its own "root" namespace
- This limitation appears to coincide with the constraints on K8S native `Ingress` based on an [issue reported](https://github.com/containous/traefik/issues/5748#issuecomment-547323939) running Traefik 2.0.4
- This limitation was removed with the introduction of [this PR](https://github.com/traefik/traefik/pull/5711), and shipped with Traefik v2.1 to current.
- While a user can [define which namespaces can be watched](https://doc.traefik.io/traefik/providers/kubernetes-crd/#namespaces), this does not constrain the user's ability to restrict `IngressRoute` to their respective namespaces, which is based on an expectation set by native K8S `Ingress` objects and the behavior of `IngressRoute` prior to 2.1.
- This behavior is specific to Traefik and `IngressRoute` and I could reproduce the regressed behavior on v2.0, and produce the cross-namespace behavior on 2.3 on K8S 1.16, 1.17, and 1.18 (this is not something K8S will restrict)

### What did you expect to see?

`IngressRoute` provider configuration to contain a flag that enables cross-namespace routing behavior (this is a worthwhile feature, IMO).

### What did you see instead?

By default, `IngressRoute` will allow users to cross-namespace boundaries even though the user would expect this behavior to be disallowed given current constraints on `Ingress`

### Output of `traefik version`: (_What version of Traefik are you using?_)

* Traefik 2.0.4
* Traefik 2.3

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

See original issue for environment / configuration. Additional tests were run on:

* Kubernetes 1.16
* Kubernetes 1.17

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
n/a

**Comment by SantoDE** [comment]
Hello all,

we can acknowledge that behavior. To fix that, we're currently aiming for 3 steps

1.) Add a logging to the next patch release of Traefik 2.3, which will inform you if you have that (potentially) insecure configuration somewhere
2.) With 2.4, we will provide a flag to toggle the behavior of allowing cross-namespace access. However, this will probably be deprecated immediately as well.
3.) Remove the flag with 2.5.

If you have feedback, please let us know.

**Comment by traefiker** [comment]
Closed by #7595.
