### ISSUE TITLE
TRAEFIK_PILOT_TOKEN env var not taken in account

### ISSUE THREAD

**Issue by ViBiOh** [traefik/traefik#7372]
Bug

### What did you do?

I've set the `TRAEFIK_PILOT_TOKEN` as mentioned in [environment variables documentation](https://doc.traefik.io/traefik/reference/static-configuration/env/)

```bash
> kubectl exec -it -n traefik traefik-b89bc58c-c9x77 -- printenv
TRAEFIK_PILOT_TOKEN=b[..]3
```

### What did you expect to see?

Traefik Pilot will see my new instance and begin to draw some metrics.

### What did you see instead?

Traefik Pilot is not activated (no instance in webui)

If I set the environment variable by CLI `--pilot.token=b[...]3` it works instantly.

### Traefik version

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/arm
```

**Comment by ldez** [comment]
Hello,

In Traefik v2, the sources of static configuration are **mutually exclusive**:
- https://doc.traefik.io/traefik/v2.3/getting-started/configuration-overview/#the-static-configuration

this means that you can't use CLI flags and env vars at the same time, you have to choose between env vars.

**Comment by ViBiOh** [comment]
Oh! Always thought that CLI overrides environment variables but both were working. Learned a thing today, thanks you and sorry for RTFM issue :/

**Comment by koliyo** [comment]
Wow this is incredible unexpected and against all common tool UX.

So I have a base `traefik.toml` configuration.

First note that traefik explicitly does not support environment variable substitution in toml files.
https://community.traefik.io/t/using-environment-variables-in-traefik-toml/758/2

Ok, so I figure I override some values using CLI. Nope does not work either. So to support this I have to supply ALL config using CLI, or use some kind of template-processing pre-step??

So I kind of accept that CLI flags and ENV flags are mutually exclusive, although having precedence handling for these is very common.

But I can not for my life understand why you would not allow override config file with values from CLI? This makes no sense to me, and makes traefik really difficult to configure.
