### ISSUE TITLE
Sample YAML config

### ISSUE THREAD

**Issue by reesericci** [traefik/traefik#7388]
I would like to see a sample config created in YAML for people (like me) that prefer it. It seems currently that there is only one available in TOML.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by reesericci** [comment]
No!

**Comment by reesericci** [comment]
@traefiker re-open

**Comment by ldez** [comment]
Hello, I re-opened, I recommend you to follow the template of the description in order to avoid this kind of problem.

**Comment by traefiker** [comment]
Closed by #7397.

**Comment by reesericci** [comment]
thanks!
