### ISSUE TITLE
Feature: Add metric for fail rules

### ISSUE THREAD

**Issue by KeepMasterBranch** [traefik/traefik#7411]
I have this `IngressRoute` with an error that starts with `invalid rule`, so this route won't work.

There should be a metric, that increment by 1 for every failing rules.

This way I could have a prometheus alert when an operator deploy a broken `IngressRoute`.

**Comment by rtribotte** [comment]
Hello @bclermont,

Could you please rewrite your proposal to follow the [template](https://raw.githubusercontent.com/traefik/traefik/master/.github/ISSUE_TEMPLATE.md) ?
Could you detail your proposal, detail your use case and the form of the metric ?
Why not use the logs to extract that information ?

Thanks for your interest in Traefik !

**Comment by sylr** [comment]
Possible dup of https://github.com/traefik/traefik/issues/6258 which has unfortunately been declined.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
