### ISSUE TITLE
Automatic HTTPS keeps reporting errors

### ISSUE THREAD

**Issue by zqs125** [traefik/traefik#7413]
### Do you want to request a *feature* or report a *bug*?
bug

Bug

### What did you do?
DNSPOD_API_KEY has been correctly set in the system environment variables

### What did you expect to see?
What should I do to generate the certificate correctly?

### What did you see instead?
Automatic HTTPS keeps reporting errors, This is the error log:
time="2020-10-13T01:11:20+08:00" level=debug msg="Using DNS Challenge provider: dnspod" providerName=myresolver.acme
time="2020-10-13T01:11:20+08:00" level=error msg="Unable to obtain ACME certificate for domains \"www.mydomains.com\" : cannot get ACME client dnspod: some credentials information are missing: DNSPOD_API_KEY" providerName=myresolver.acme

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```
certificatesResolvers:
  myresolver:
    acme:
      email: "my@email.com"
      storage: "acme.json"
      dnsChallenge:
        provider: "dnspod"
        delayBeforeCheck: 0
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      keyType: "EC256"

http:
  routers:
    router-1:
      entryPoints:
        - "web"
      rule: "Host(`www.mydomains.com`)"
      service: "service-1"
      tls:
        certResolver: "myresolver"
        domains:
          - main: "www.mydomains.com"
  services:
    service-1:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1/"

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
time="2020-10-13T01:11:20+08:00" level=debug msg="Using DNS Challenge provider: dnspod" providerName=myresolver.acme
time="2020-10-13T01:11:20+08:00" level=error msg="Unable to obtain ACME certificate for domains \"www.mydomains.com\" : cannot get ACME client dnspod: some credentials information are missing: DNSPOD_API_KEY" providerName=myresolver.acme
```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
