### ISSUE TITLE
Bug: Certificate resolvers silent fail on on unexpected acme.json "the router uses a non-existent resolver:"

### ISSUE THREAD

**Issue by gerome1812** [traefik/traefik#7414]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Deployed traefik 2.3 via the official docker image. Configured the location of acme.json in an docker overlay2 volume. This issue can happen in two ways, but basically just modify `acme.json` in any way, have an already existing `acme.json`, incorrect permissions for `acme.json`. Pretty much anything that traefik may not expect with the `acme.json` file.

### What did you expect to see?
On debug logging, an error such as `incorrect file permissions 600`. Or `acme.json already exists`.

### What did you see instead?
The certificate resolver will silent fail (on debug logging). Each router using that certresolver will fail with `the router uses a non-existent resolver`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Relevant bit:
```
--certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
```

Some others with the same issue:
[https://community.traefik.io/t/a-solution-to-the-incredibly-unhelpful-the-router-uses-a-non-existent-resolver-letsencrypt-message/3859](https://community.traefik.io/t/a-solution-to-the-incredibly-unhelpful-the-router-uses-a-non-existent-resolver-letsencrypt-message/3859)
[https://community.traefik.io/t/non-existent-resolver-using-letsencrypt/3530](https://community.traefik.io/t/non-existent-resolver-using-letsencrypt/3530)

**Comment by sqlsolver** [comment]
Exactly the same issue and same discoveries when debugging. Further, if I assure there is no acme.json created, Traefik doesn't seem to add it. The old 1.7 instructions say to touch acme.json and set its permissions. If I do that I still get a non-existent resolver error. The current docs say, ['In Docker you can mount either the JSON file, or the folder containing it'](https://doc.traefik.io/traefik/https/acme/#storage) which is not very prescriptive and sounds like you should be okay whether you do or don't have acme.json in the mapped volume. I have not been able to make it work with either by touch and chmod acme.json or leaving the creation entirely to Traefik.

**Comment by sqlsolver** [comment]
RE acme.json issues also see: https://github.com/traefik/traefik/issues/7493#issuecomment-719941821

**Comment by SiroDiaz** [comment]
Having the same error message
```
myapp_traefik.1.jz73dwzz3ynu@docker-ubuntu-s-1vcpu-2gb    | time="2020-12-08T00:46:52Z" level=error msg="the router app@docker uses a non-existent resolver: appresolver"
```

Any solution?

**Comment by gerome1812** [comment]
@SiroDiaz there are multiple reasons why that could happen, and the resolver could actually be nonexistant. This bug report is about a specific instance of that error message. Please see the first link to the traefik forums in my post.

**Comment by Tristaan** [comment]
@sqlsolver Hello, I have the same issue. The configurations are written correctly, checked them multiple times but traefik does NOT create the acme.json file whatever I do. I get the same error as @SiroDiaz.
Did you find a solution?

**Comment by ldez** [comment]
Either the name of your resolver is not good or you have another error (in your logs) that block the creation of the resolver.

**Comment by SiroDiaz** [comment]
Yes @Tristaan . I could find a solution. The error was in the path for the acme.json. it should be put as an absolute path in your static configuration file.

**Comment by Tristaan** [comment]
I found my error, it was a beginner failure
 I wrote certificateResolvers: instead of certificatesResolvers:. Mind the
plural of certificate.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by gerome1812** [comment]
This is very much still an issue, please reopen this.

**Comment by gustavocoleta** [comment]
Hi!

I solved this problem configuring [like this](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/).

I dont create de file acme.json, only the dir `letsencrypt` and at label `"traefik.http.routers.traefik.tls.certresolver=<resolvername>"` in `<resolvername>` i use the same value used in command: `--certificatesresolvers.<resolvername>.acme...`
