### ISSUE TITLE
Traefik will stop loading configures from kv when parsing an unsupported key

### ISSUE THREAD

**Issue by letian0805** [traefik/traefik#7417]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Add an unsupported field to kv configure.

### What did you expect to see?
Ignore any unsupported configures, report error to log and continue loading rest configures.

### What did you see instead?
Traefik stops loading rest configures.

### Output of `traefik version`: (_What version of Traefik are you using?_)
Any 2.x version

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
linux, etcd

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
Such as `KV connection error: field not found xxx, retrying in 500ms`

Same issue https://github.com/traefik/paerser/issues/2

**Comment by ldez** [comment]
Hello,

This is the expected behavior, do you have a use case where this is not expected?

**Comment by letian0805** [comment]
> Hello,
> 
> This is the expected behavior, do you have a use case where this is not expected?

I mean traefik is not strong enough when upgrading.
When i upgrade traefik from v2.2 to v2.3, i need update configure first and then update traefik. But traefik v2.2 don't support some configures of traefik v2.3. Such as `AccessControlAllowOriginList`.

**Comment by letian0805** [comment]
It’s best to let the upper level caller (traefik) decide how to handle errors, not by paerser.

**Comment by ldez** [comment]
You don't need to start by updating your configuration, you can just update Traefik then update your configuration.

Why are you doing this in this order?

**Comment by letian0805** [comment]
Our website has multiple orgins. Traefik v2.2 don't support multiple origins in `AccessControlAllowOrigin`. So we set `AccessControlAllowOrigin` to `origin-list-or-null`.

**Comment by ldez** [comment]
Why are you doing this in this order?

**Comment by letian0805** [comment]
> Why are you doing this in this order?

![image](https://user-images.githubusercontent.com/14961048/95897315-e95c7f80-0dbf-11eb-84f2-dbdd91f2d4fa.png)

Because requests will get CORS error if update traefik to v2.3 before update configure to 2.3.

**Comment by ldez** [comment]
Sorry but I think that you don't understand my question: why do you update your configuration before updating Traefik?

**Comment by ldez** [comment]
But it's not the same field: `AccessControlAllowOriginList` is a new field, the previous field `AccessControlAllowOrigin` still have the same behavoir.

**Comment by letian0805** [comment]
![image](https://user-images.githubusercontent.com/14961048/95898094-1c534300-0dc1-11eb-8cb9-badd11720ec9.png)

You can compare this old version code.
In old version, it will return origin. But it will return item in new version.
It means: if origin is `https://examle.com` and `AccessControlAllowOrigin` is `origin-list-or-null`, old version will return `https://examle.com` while new version return `origin-list-or-null`.

**Comment by letian0805** [comment]
> ~But it's not the same field: `AccessControlAllowOriginList` is a new field, the previous field `AccessControlAllowOrigin` still have the same behavior.~
> 
> I think I understand your problem.

So, do you think how to fix it? I hack it like this https://github.com/traefik/traefik/pull/6785
But i think it isn't a good idea, because `origin-list-or-null` has been removed from v2.2.

**Comment by ldez** [comment]
So your issue is neither really related to paerser nor to an update to v2.3, because the `isOriginAllowed` method is [in the v2.2](https://github.com/traefik/traefik/blob/edb15a934628f210f77a8516cd017e48cc9cbfb6/pkg/middlewares/headers/header.go#L162-L170) but to `origin-list-or-null`

I agree with the answers made by @dtomcej and @rtribotte in #6785.

We will think about your use case.

**Comment by letian0805** [comment]
Not only origin-list-or-null. AccessControlAllowOriginList is only one of fields unsupported by old version.

**Comment by ldez** [comment]
I'm thinking about a different approach: in Traefik v1 for the KVs we had an option to switch a configuration at runtime from the KV by using the dedicated key `/traefik/alias` to extend the `prefix` attribute.

Maybe we can find a way to handle the same behavior in v2.

**Comment by letian0805** [comment]
> I'm thinking about a different approach: in Traefik v1 for the KVs we had an option to switch a configuration at runtime from the KV by using the dedicated key `/traefik/alias` to extend the `prefix` attribute.
> 
> https://doc.traefik.io/traefik/v1.7/user-guide/kv-config/#atomic-configuration-changes
> 
> Maybe we can find a way to handle the same behavior in v2.

Yes, this is another issue: in 2.x, prefix can't use as `traefik/kv,` but `traefik` only

**Comment by ldez** [comment]
This issue has been fixed https://github.com/traefik/traefik/pull/6664 and will be available in the next release (v2.4).

But I don't talk about that, because the key is `alias` and the prefix `traefik`.

I'm talking about https://doc.traefik.io/traefik/v1.7/user-guide/kv-config/#atomic-configuration-changes

**Comment by letian0805** [comment]
Nice!

**Comment by ldez** [comment]
I will close your issue in favor of a dedicated is related to the atomic configuration changes feature: #7419

Don't hesitate to participate in this new issue.

Thank you.
