### ISSUE TITLE
New release for 1.7

### ISSUE THREAD

**Issue by LordGaav** [traefik/traefik#7440]
Any chance for a new release of 1.7? There have been a few PR's merged since the last release (https://github.com/traefik/traefik/compare/v1.7.26...v1.7), and specifically the tracing commit (https://github.com/traefik/traefik/commit/d04b812412ee53c240cd4e2c07e18c8ae539e3c0) would help us out greatly.

**Comment by jbdoumenjou** [comment]
Hi @LordGaav ,

We will try to do a release in the coming weeks.
