### ISSUE TITLE
Traefik dashboard support for managing nearly all configurations

### ISSUE THREAD

**Issue by li1234yun** [traefik/traefik#7448]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I hope you can consider the dashboard that support modifying nearly all configurations and make configuration take affect immediately.

**Comment by jbdoumenjou** [comment]
Hello @li1234yun ,

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #2481 .

Thus, we encourage you to participate in the other issue.

Thank you for your contribution.
