### ISSUE TITLE
Content-Type=application/json，Automatic Error Processing Status Code 500

### ISSUE THREAD

**Issue by PenleyWang** [traefik/traefik#7455]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
My application is based on the Abp framework development, ajax the case, the server side message is generated by throwing UserFriendlyException exception, through the [Abp packaging processing](https://aspnetboilerplate.com/Pages/Documents/Javascript-API/AJAX#handling-errors), will return the json format error message, this time is 500.
 When the upstream server returns 500, taefik can not return the json message to the front end, resulting in the front end can not display the message.
 Can you add a switch configuration to release the specified error code (such as 500) and do not process it automatically?

### What did you expect to see?
When the StatusCode is 500, the front end can also receive the following json data from the back end：
`
{
  "targetUrl": null,
  "result": null,
  "success": false,
  "error": {
    "message": "An internal error occurred during your request!",
    "details": "..."
  },
  "unAuthorizedRequest": false,
  "__abp": true
}
`

### What did you see instead?
Internal Server Error................................................

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker image taefik:v2.2

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
