### ISSUE TITLE
kubernetes CRD with schema

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#7457]
Feature

### What did you expect to see?

kubernetes CRD with [schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition)
Currently [CRD](https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/) doesn't provide validation, it is easy to have typo. Having schema can have [IDE check and auto complete](https://www.jetbrains.com/help/go/2020.2/kubernetes.html?#crd) while typing

For example `IngressRoute` below
```diff
  routes:
    - match: PathPrefix(`/whoami`)
      kind: Rule
      services:
        - name: whoami
          port: 80
    - match: PathPrefix(`/zone`)
+++      kind: Rule
---      Kind: Rule
      services:
        - name: zone-printer-service
          port: 80
```

Because of the type of the word `kind`, i spent 45 minutes to debug and only noticed was a typing error 🤦🏻‍♂️. Having validation in place can avoid this type of problem

**Comment by jbdoumenjou** [comment]
Hello @WLun001 

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #5473 .
As this issue requires the integration of CRD openAPIV3Schema, it will provide the schema validation.

Thus, we encourage you to participate in the other issue.

Thank you for your contribution.
