### ISSUE TITLE
Capability to disable auto renewal of Let's Encrypt certificate

### ISSUE THREAD

**Issue by Diak** [traefik/traefik#7484]
#7245 

# Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I wanted to have 2 instances on 2 distinct servers of traefik for HA purpose and i'd like to share the acme.json file in order to use the same certificate (transparency for client). The certificate was generated with dns challenge. The acme.json file will synchronized between the 2 instances.
But to avoid that both instances renew automatically the certificate, i'd like to disable automatic auto renewal on the second instance. It seems there's no option to disable this functionnality (cf. documentation).

So i would like, as new feature, this option to be added.

Thanks.

**Comment by SantoDE** [comment]
Hello @Diak,

that is currently not possible with the current intention of Traefik being a good old dataplane. As described in #5792, we have integrations with for example cert-manager which can do that for you.

**Comment by Diak** [comment]
cert-manager is ok with kubernetes it seems. I don't use kubernetes.
Whatever i still think it's not mandatory to want to renew automatically a certificate and it could have been a good option to permit or not this functionnality instead of imposing it.
But i will find another way.
