### ISSUE TITLE
Functionality lost in move from 2.1 to 2.3 - accessControlAllowOrigin

### ISSUE THREAD

**Issue by dbrown-verimatrix** [traefik/traefik#7488]
Feature

Feature

In 2.1, it was possible to set accessControlAllowOrigin to be: origin-list-or-null.  When using accessControlAllowCredentials to be true, the Access Control Allow Origin should match the Origin in the HTTP request, and not be "*".

In 2.3, the log for middleware/headers matches "*" or a specific origin, but not provide a mechanism to copy the origin header.

This is a feature request to re-add the functionality in.  I am open to provide a patch for this.

**Comment by ldez** [comment]
Hello,

https://github.com/traefik/traefik/pull/6785#issuecomment-652907156

**Comment by jbdoumenjou** [comment]
Hello @dbrown-verimatrix  ,

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #6785.

Thus, we encourage you to participate in the other issue.

Thank you for your contribution.
