### ISSUE TITLE
Basic Metrics

### ISSUE THREAD

**Issue by wahmedswl** [traefik/traefik#7491]
Trafik should expose basic metrics like RPS/Percentile Latency in the dashboard also. Just like these are exposed in Linkerd dashboard

### What did you expect to see?

![image](https://user-images.githubusercontent.com/15020561/97704357-17d29e00-1ad4-11eb-96f4-3716a02b8e62.png)

Thanks

**Comment by jorge07** [comment]
That can be very confusing as each instance will have in memory different data sets. Store that in prometheus for example to be consistent and have a global view. Having this metrics a dashboard with high deviations between render results makes no sense IMO.

**Comment by wahmedswl** [comment]
Usually, Traefik is used as Edge Proxy its mean all traffic is routed via Traefik. In that case, metrics are centralized just like Envoy or HaProxy etc expose.

Is Traefik different than others or usage i described is not primary usage?

Thanks

**Comment by jorge07** [comment]
It is but metrics are stored on each instance in memory so if you access the dashboard, you only access to the metrics in memory for the one you hit. Grafana it's a much better place IMO

**Comment by wahmedswl** [comment]
I don't get it, when Traefik is the frontend proxy then how comes metrics cannot be captured on it? Each instance, running multiple Traefik instances? Traefik dashboard is available against particular instance, which is the central point. It route requests, retries etc so it has complete picture so metrics should be available there.

Traefik Pilot, it can be registered against multiple instances even it capture metrics per Instance.

Thanks

**Comment by SantoDE** [comment]
Hello all,

currently, the display of metrics is done inside pilot, our universal control plane as you probably have seen it (https://traefik.io/traefik-pilot/).

As @jorge07 pointed out, having stats per node in memory can be very confusing in replicated scenarios and thus, we either recommend going for a specific solution such as Grafana, or use pilot.

For pilot, we have lots of further metrics on our internal roadmap which will be available in the future.

As this is a question, Ill close that issue.
