### ISSUE TITLE
Redirect domain.com -> www.domain.com (traefik v2)

### ISSUE THREAD

**Issue by kopax** [traefik/traefik#7495]
I have a domain : `mydomain.com`.

I host a blog under `www.mydomain.com`, I want to redirect people that use `mydomain.com` to `www.mydomain.com`

My proxy is traefik, and I use the `HTTP-01` challenge to provide `https` with let's encrypt.

So far, my configuration looks like this:

```bash
"traefik.enable": "true",
"traefik.http.routers.blogGateway.rule": "Host(`www.mydomain.com`) || Host(`mydomain.com`)",
"traefik.http.routers.blogGateway.entrypoints": "web-secure",
"traefik.http.routers.blogGateway.tls.certresolver": "httpChallengeLetsEncrypt",
"traefik.http.routers.blogGateway.tls.domains[0].main": "www.mydomain.com",
"traefik.http.routers.blogGateway.tls.domains[1].main": "mydomain.com",
"traefik.http.middlewares.redirect-to-https.redirectscheme.scheme": "https",
"traefik.http.routers.blogGatewayRedirs.rule": "hostregexp(`{host:.+}`)",
"traefik.http.routers.blogGatewayRedirs.entrypoints": "web",
"traefik.http.routers.blogGatewayRedirs.middlewares": "redirect-to-https"
```

This work, but it expose two domain instead of one.

I have tried to follow this tutorial : https://habd.as/post/redirect-non-www-to-www-traefik-v2-labels/ but I keep losing the track of my change, this configuration is somehow totally different from my current one.

How can I perform a redirect from `@` to `www` with traefik v2 ?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by kopax** [comment]
Hi @traefiker and no worries, I totally understand, perhaps we can consider this as a documentation feature request. This is a basic redirection for all hosted website served under `www`.

best regards,
