### ISSUE TITLE
Central configuration of frequently referenced-via-label middlewares

### ISSUE THREAD

**Issue by schildbach** [traefik/traefik#7505]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Like many others, I'm using traefik within docker-compose and use labels in my services to configure a Traefik router for each service. 

I've got a middleware defined in my dynamic.yml (being loaded from traefik.yml) that I want to run on most services. From the services, via label I reference that middleware by name, but traefik cannot find the middleware. If I define that middleware in my service via multiple labels instead, it is found.

Please allow for central configuration of frequently referenced middlewares.

Example usecases:
- setting STS header
- HTTP to HTTPS redirect

It would be similar to certificateResolvers. I can configure letsencrypt in traefik.yml and reference it from each service by name: `traefik.http.routers.myrouter.tls.certresolver=letsencrypt`

**Comment by jbdoumenjou** [comment]
Hi @schildbach,

The middlewares declared in your file is usable by routers defined in docker labels.
Did you use the  [provider namespace](https://doc.traefik.io/traefik/providers/overview/#provider-namespace) in the label?
It could be something like: ```traefik.http.routers.router1.middlewares=foobar@file```

If you are talking about defining middlewares by default, you can use [HTTP options](https://doc.traefik.io/traefik/v2.3/routing/entrypoints/#middlewares) on entrypoints, it is something like:

```yaml
--entrypoints.websecure.address=:443
--entrypoints.websecure.http.middlewares=auth@file
```

Did it answer your need?

**Comment by schildbach** [comment]
`@file` did the trick, thanks!

(I tried defining the middleware using `@docker` since that's what it was looking for.)
