### ISSUE TITLE
Parameters in query directly invoke template functions via redirect regex middleware

### ISSUE THREAD

**Issue by bbsbb** [traefik/traefik#7513]
### Do you want to request a *feature* or report a *bug*?

Bug, hopefully.

Assumption is that https://github.com/traefik/traefik/blob/86c099d6297bd7103bef8240e90f45492be56000/pkg/middlewares/redirect/redirect.go#L59 shouldn't really invoke templates via query?
 

### What did you do?

Currently configuration of the redirectRegex middleware allows to invoke google template functions directly from query parameters. Easy to reproduce with a non-compliant url.

### What did you expect to see?

Expectation is that with a configuration of: 
```     
redirectRegex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "http://${1}"
        permanent: true
```

an url invocation of https://www.domain.me/?fn=wut should produce a redirection response to https://domain.me/?fn=wut  :heavy_check_mark: 

however

an url invocation of https://www.domain.me/?fn={{wut}} => https://domain.me/?fn={{wut}}  :x: 

### What did you see instead?

Instead of a redirection, traefik replies with a 500 error (log output below). 

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Linux, 5.4 kernel with file provider.

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

"'500 Internal Server Error' caused by: template: t:1: function "wut" not defined"

**Comment by traefiker** [comment]
Closed by #7573.
