### ISSUE TITLE
Conflict between dashboard api and service api

### ISSUE THREAD

**Issue by codlin** [traefik/traefik#7518]
### What did you expect to see?

I hope that the URL starting with `/api` can be forwarded to the service I specify.

### What did you see instead?

Because traefik dashboard need to configure `/api`
In fact the URL starting with `/api` of my service request was forwarded to dashboard.

### Output of `traefik version`: (_What version of Traefik are you using?_)

traefik:v2.2.0

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Here is my traefik dashboard configuration:
```xml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  basicAuth:
    secret: authsecret # Kubernetes secret named "secretName"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`10.10.0.27`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
      - name: auth
```

my service configuration:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webserver
  # namespace: default

spec:
  entryPoints:                      # [1]
    - web

  routes:                           # [2]
  - kind: Rule
    match: Host(`10.10.0.27`) && PathPrefix(`/api`)  # [3]
    #   namespace: default          # [7]
    services:                       # [8] 
    - name: ci-webserver
      # namespace: default
      passHostHeader: true
      port: 8090
```

How to disable dashboard `/api`?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
