### ISSUE TITLE
MSRPC over HTTPS for Exchange/Owa Reverse Proxy

### ISSUE THREAD

**Issue by dataCore** [traefik/traefik#7522]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Microsoft RPC over HTTPS traeffic passed through "traefik" to the Exchange 2016/2019, so that I can use Outlook Anywhere.

### What did you see instead?

MSRPC over HTTPS traeffic not passed through. Error message instead: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)".

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
traefik version
Version:      2.3.2
Codename:     picodon
Go version:   go1.15.3
Built:        2020-10-19T18:36:22Z
OS/Arch:      linux/amd64
```

### Additional Information

Currently the setup is working with Microsoft IIS ARR as the reverse proxy. Changing that by passing all 80/443 traffic from IIS to traefik, resulting in the error code 500 above.
If I want to use Apache as a reverse proxy instead, I have to install an additional module for MSRPC (https://directory.fsf.org/wiki/Mod_proxy_msrpc). Maybe "traefik" needs something similar?

**Comment by SantoDE** [comment]
Hey @dataCore,

thanks for your interest in the project. 

To me, it looks like MSRPC seems to be a different protocol, no? Or is it some sort of HTTP in between? I tried to give a quick research and it looked like, that its a protocol which negotiates some further ports (TCP and UDP) and stuff. Am I wrong?

Can you explain the background a bit more, please? :) Like, what do you expect, how should it be working, what is a desired configuration? So we can potentially follow a bit better :) 

Thanks!

**Comment by dataCore** [comment]
Hi @SantoDE, thanks for your reply! 

To me, this is also some weird microsoft stuff/protocol and I'm not a Microsoft Exchange expert either. My goal: I just want to replace our working, but old IIS ReverseProxy with traefik:2.3 as a better ReverseProxy...

In my understanding, Microsoft Outlook (E-Mail Client from Microsoft), running on client laptops outside our network, uses this protocol over port:443 to communicate with the Backend Microsoft Exchange 2016 server. The server itself has multiple pages/protocol to serve different things (owa, api, ecp, ews, mapi, oab and RPC) over his port:443. 

3 Urls are used (over 443) and affected of the problem:
- autodiscover.example.ch _(returning some xml to configure (I think) the clients)_
- mail.example.ch _(same as owa.example.ch)_
- owa.example.ch _(same as mail.example.ch)_

**Our working setup**:
[External Outlook Client: mail.example.ch:443] --> Portforward:443 --> [IIS Reverse Proxy] --> [Route to: internal Exchange2016:443]
**Our not working setup**:
[External Outlook Client: mail.example.ch:443] --> Portforward:443 --> [Traefik Reverse Proxy] --> [Route to: internal Exchange2016:443]

"not working": the webpage is working (owa) but the client (outlook) can't connect and under https://autodiscover.example.ch/Autodiscover/Autodiscover.xml apear a "ErrorCode:500 Internal Server Error" instead of an XML.

Anyway - next I will try to use **tcp** with HostSNI instead of **http/https** for the affected urls and will see, if it will work that way.

Stay tuned :) and thanks for your great work!!

**Comment by dataCore** [comment]
update on this: 
I had to do the ssl/cert things directly on the exchange server. So I had to use tcp passthrough

config example:
```
tcp:
  routers:
    https.mail.yourdomain.com:
      rule: HostSNI(`mail.yourdomain.com`)
      entryPoints:
        - https
      service: mail.yourdomain.com
      tls:
        passthrough: true

  services:
    mail.yourdomain.com:
      loadBalancer:
        servers:
          - address: internalExchangeHostName01:443
```

can be closed
