### ISSUE TITLE
Wrong schema detected

### ISSUE THREAD

**Issue by lexfrei** [traefik/traefik#7524]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Install k3s on with `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - --disable traefik,servicelb`
2. Deploy helmfile's https://gist.github.com/lexfrei/fb5849f338ad1953a15def5a4b2e3b40

### What did you expect to see?
http://10.42.1.13:9090 as the endpoint for k8s-dashboard

### What did you see instead?
`ForwardURL="https://10.42.1.13:9090"`

![image](https://user-images.githubusercontent.com/1366514/98448238-b649a980-213b-11eb-8103-23cdb7b6620d.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Image:         traefik:2.3.1
helm chart:    9.10.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

[Htlmfiles](https://gist.github.com/lexfrei/fb5849f338ad1953a15def5a4b2e3b40)
[K8s-dashboard export](https://gist.github.com/lexfrei/2029e0bc2a283e4cf82131b8dcf7f6d2)

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-11-07T17:31:14Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/avif,image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"ru-RU,ru;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6,fr;q=0.5\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_ga=GA1.2.693130189.1592868586\"],\"Dnt\":[\"1\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"http://dashboard.k8s.home.lex.la/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36\"],\"X-Forwarded-Host\":[\"dashboard.k8s.home.lex.la\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-8464f8798c-2z65b\"],\"X-Real-Ip\":[\"10.42.2.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"dashboard.k8s.home.lex.la\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.2.1:64754\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
time="2020-11-07T17:31:14Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"image/avif,image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"ru-RU,ru;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6,fr;q=0.5\"],\"Cache-Control\":[\"no-cache\"],\"Connection\":[\"keep-alive\"],\"Cookie\":[\"_ga=GA1.2.693130189.1592868586\"],\"Dnt\":[\"1\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"http://dashboard.k8s.home.lex.la/\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36\"],\"X-Forwarded-Host\":[\"dashboard.k8s.home.lex.la\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-8464f8798c-2z65b\"],\"X-Real-Ip\":[\"10.42.2.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"dashboard.k8s.home.lex.la\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.2.1:64754\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}" ForwardURL="https://10.42.1.13:9090"
time="2020-11-07T17:31:44Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 10.42.1.13:9090: i/o timeout"
```

**Comment by lexfrei** [comment]
I can see the correct scheme in the pod [definition](https://gist.github.com/lexfrei/2029e0bc2a283e4cf82131b8dcf7f6d2#file-pod-yaml-L26)

**Comment by SantoDE** [comment]
Hello @lexfrei,

you did set the correct scheme on the liveness probe. That is tough, not utilized for the scheme detection for Traefiks backends. 

What you can try to do is to overwrite the scheme on the service with that annotation ```traefik.ingress.kubernetes.io/service.serversscheme: http```, as mentioned on our docs https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/.

As this is primarily a question, I gonna close that issue. Please feel free to reach out on the community forum for cases like that https://community.traefik.io/c/traefik/traefik-v2/10
