### ISSUE TITLE
Let's Encrypt - Standing on Our Own Two Feet

### ISSUE THREAD

**Issue by StiviiK** [traefik/traefik#7532]
Hi,
I just read about [this announcement](https://letsencrypt.org/2020/11/06/own-two-feet.html) from Let's Encrypt and now I am wondering will Traefik add support for fetching the alternative Certs with the DST Root X3?

**Comment by ldez** [comment]
Hello,

It's already supported by Traefik: https://doc.traefik.io/traefik/v2.3/https/acme/#preferredchain

Related to #7238
