### ISSUE TITLE
Traefik Ingressroutes CRD with IngressClass

### ISSUE THREAD

**Issue by posteingang** [traefik/traefik#7534]
Hi,

is there a way to use something like the ingress.class also in with the IngressRoute CRDs?

I have a setup with two Traefik IngressController, each in a different namespace, for private and for public traffic. Now I want to route traffic to the a service in another namespace.

**Idea 1: Turn off namespacing**
With that I am able to route traffic to different namespaces,  so far so good. But if I use the ingrssroute CRD it will be loaded by each controller. In other word, my private services are basicly also exposed by the public traefik. :-(

**Idea 2: Turn on namespacing**
With that I am NOT able to route traffic to different namespaces.

The problem is also described by another user here: https://stackoverflow.com/questions/60913719/install-two-traefik-ingress-controller-on-same-kubernetes-cluster
where the solution is just to use the ingress.class. But unfortunately I am not able to use the CRDs anymore.

**Comment by yongzhang** [comment]
I have the same question.

**Comment by rtribotte** [comment]
Hello @posteingang @yongzhang,

Thanks for your interest in Traefik!

Did you try to configure each of your Traefik instances with the `ingressClass` option on the provider, which allows matching only the IngressRoutes that provides the same ingressClass name via the `kubernetes.io/ingress.class` annotation, as stated in the [documentation](https://doc.traefik.io/traefik/v2.3/providers/kubernetes-crd/#ingressclass)?

**Comment by yongzhang** [comment]
> kubernetes.io/ingress.class

yes it works by adding annotation `kubernetes.io/ingress.class` to ingressroute.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
