### ISSUE TITLE
Docs on tweaking response using middlewares

### ISSUE THREAD

**Issue by tirumerla** [traefik/traefik#7537]
### Do you want to request a *feature* or report a *bug*?

Feature/More of a question.

### What did you expect to see?
Hi,

I'm not sure if this is possible using middlewares. I would like to redirect to an endpoint eg. xyz.com before answer from the services are sent to the clients.
Based on the [docs](https://doc.traefik.io/traefik/middlewares/overview/) here, specifically this line
> Attached to the routers, pieces of middleware are a means of tweaking the requests before they are sent to your service (or before the answer from the services are sent to the clients)

I assume this is possible using middlewares but i couldn't find any examples on how to do it. The only thing that i found was to tweak requests from clients to services and this works fine for me.
If there are no examples that exist right now, it would be great to add sample examples to the docs as other people might run into any same issue.

Here's how the flow is wired and what i'm looking for -

_Request flow:_
Client --> Application load balancer--> Target group --> ingress route --> my auth --> Jupyterhub

_Response flow_ ( **currently existing** ):
Jupyterhub ( client clicks on logout ) --> Application loadbalancer --> Target group --> ingressroute --> my auth --- client is able to see my auth page.

_Response flow_ ( **what i'm looking for** ):
Jupyterhub ( client clicks on logout ) --> Application loadbalancer --> Target group --> ingressroute --> my auth service --> middleware ( redirection ) --> https://xyz.com -- client should see xyz.com now.

**Kubernetes version:** `AWS EKS v1.17`
**Traefik Version**: `2.3.0`

Please let me know if there are any examples on how this can be tweaked or if i have to follow any plugins?

Appreciate your help.

Thanks.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by tirumerla** [comment]
Hello @SantoDE @kevinpollet  i haven't found the answer yet for this question even though i posted the same question on Community forum. Would greatly appreciate if you guys can help point me in the right direction.

Thanks.
