### ISSUE TITLE
Environment variable being ignored when providing static configuration file

### ISSUE THREAD

**Issue by tobiasb** [traefik/traefik#7545]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The behaviour that I'm seeing is that when I specify a static configuration via configuration file, e.g. `/etc/traefik/traefik.yml` I am not able to complement or override the configuration using environment variables. Any env vars (https://doc.traefik.io/traefik/reference/static-configuration/env/) specified simply get ignored. 

Is this something I can get around somehow? I'm working with an internally built Docker image that has a "default" configuration yml but I'd like to be able to specify for instance the log level when running the image.

**Comment by jbdoumenjou** [comment]
Hello,

In Traefik v2, the sources of static configuration are mutually exclusive:

    https://doc.traefik.io/traefik/v2.3/getting-started/configuration-overview/#the-static-configuration

this means that you can't use CLI flags and env vars at the same time, you have to choose between env vars and CLI flags.

Therefore, I will close in favor of #3853.
