### ISSUE TITLE
Automatic detection protocol type

### ISSUE THREAD

**Issue by guidao** [traefik/traefik#7546]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to support the http protocol detection feature. Use http router when it is http protocol, otherwise use tcp router.

**Comment by jbdoumenjou** [comment]
@guidao,

Thanks for your interest in Traefik!

You can use both TCP and HTTP routers on the same entrypoints.
We had an [old demo](https://github.com/containous/slides/blob/master/demo/traefik-v2/mongo/04-tcp-and-http-routing-mongo/docker-compose.yml) about this use-case.

If you need more help on configuration usage, feel free to join our [community forum](https://community.traefik.io/).

If you think it is a mistake, don't hesitate to reopen this issue.

I hope it will help you.
