### ISSUE TITLE
Mirror docker images to other docker registries like quay.io

### ISSUE THREAD

**Issue by benoitf** [traefik/traefik#7566]
### Do you want to request a *feature* or report a *bug*?

Official images are stored on hub.docker.com https://hub.docker.com/_/traefik

but due to hub limits [1], some projects may hit the `docker pull` limit

Would it be possible to publish images to other registries that do not have pull limits ? like quay.io [2] (or others)

[1] : https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/
[2]: http://quay.io/

### What did you expect to see?

images being published on public registries without limits

**Comment by ldez** [comment]
Hello,

the official images of Traefik are built by Docker it-self, as they are official there is no rate limits on it.

Thanks anyway.

**Comment by benoitf** [comment]
@ldez 
```
$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
...
RateLimit-Limit: 100;w=21600
RateLimit-Remaining: 100;w=21600
```

```
$ docker pull docker.io/traefik:v2.2.8
...
Status: Downloaded newer image for traefik:v2.2.8
```

```
$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
...
RateLimit-Limit: 100;w=21600
RateLimit-Remaining: 99;w=21600
```

limit goes down to 99 so it's unlikely behaving as you're saying. There is still rate limit on it.

**Comment by notsureifkevin** [comment]
@benoitf

Greetings, I'm asking some of the maintainers at docker about this issue. Thank you for reporting your findings.

_kc

**Comment by benoitf** [comment]
@notsureifkevin hi, did you get some answers from maintainers at docker ?

**Comment by ldez** [comment]
We are waiting for an answer.
