### ISSUE TITLE
Allow specification of server URL using ECS provider 

### ISSUE THREAD

**Issue by mmf55** [traefik/traefik#7568]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
Allow the hostname to be overridable in the ECS provider. Currently, it is possible to define the URL if we use a file provider as the configuration source. (https://doc.traefik.io/traefik/routing/services/#configuration-examples)
When using the ECS provider this is automatically defined using the IP of the task. This works fine if I'm using containers and routing to containers. However, if I'm using a service mesh on top of my containers, the service URL should be the service name as defined in the mesh instead of the IP address of the task.
The provider has no way to find the service name of the mesh, so we would like to define the server URL using a docker label instead of the task IP address.
We already have the option to specify the scheme and the port with the following labels:
```
traefik.http.services.<service_name>.loadbalancer.server.port
traefik.http.services.<service_name>.loadbalancer.server.scheme
```
Would be nice to be able to specify the address of the service in a similar way:
```
traefik.http.services.<service_name>.loadbalancer.server.address
```

Note: Although this related to ECS, I think this also applies to other providers.
Related issues:
https://github.com/istio/istio/issues/19536
https://github.com/istio/istio/issues/23494

**Comment by rtribotte** [comment]
Closing in favor of https://github.com/traefik/traefik/issues/8753
