### ISSUE TITLE
Support for Regex path

### ISSUE THREAD

**Issue by yuzujoe** [traefik/traefik#7581]
### Do you want to request a *feature* or report a *bug*?
We are currently using Traefik v1.7.
Expect support for regex paths like the Nginx ingress controller.

When I tried to use the OSS reportportal, it didn't work well because it didn't support the path in regex format.

In order to support this path, I came to install nginx ingress controller, but I am happy if I can use traefik ingress because I use traefik in the product.

The use of `traefik.ingress.kubernetes.io/redirect-regex` and `traefik.ingress.kubernetes.io/redirect-replacement` did not work well.

Is `traefik.ingress.kubernetes.io/rule-type` correct?

See.
https://github.com/reportportal/kubernetes/blob/master/reportportal/v5/templates/gateway-ingress.yaml
https://github.com/reportportal/kubernetes/blob/master/reportportal/v5/values.yaml#L163

### What did you expect to see?

Expect to be able to accommodate a regex path using kubernetes annotation.

If it is supported or available in v2, please press

**Comment by rtribotte** [comment]
Hello @yuzujoe,

Thanks for your interest in Traefik !
We do not provide support to troubleshoot any configuration issue through the github issues.
Please take a look at our [community forum](https://community.traefik.io/c/traefik/traefik-v2/10).
I'll close this issue as a question accordingly.
