### ISSUE TITLE
Error while building TraefikService: kubernetes service not found: kube-system/s2" providerName=kubernetescrd serviceName=mirror2

### ISSUE THREAD

**Issue by haipengzzz** [traefik/traefik#7584]
The log always has "Error while building TraefikService: kubernetes service not found: kube-system/s2" providerName=kubernetescrd serviceName=mirror2" but I have installed the related TraefikService

`[root@master traefik]# kubectl get traefikservice -n kube-system`
`NAME      AGE`
`mirror1   33m`
`mirror2   33m`
`wrr1      33m`
`wrr2      33m`

`time="2020-11-24T09:29:47Z" level=error msg="kubernetes service not found: default/s1" providerName=kubernetescrd ingress=ingressroute namespace=default
time="2020-11-24T09:29:47Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." ingress=ingressroute namespace=default providerName=kubernetescrd
time="2020-11-24T09:29:47Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." namespace=default providerName=kubernetescrd ingress=ingressroute
time="2020-11-24T09:29:47Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." providerName=kubernetescrd ingress=ingressroute namespace=default
time="2020-11-24T09:29:47Z" level=error msg="Unsupported match kind: . Only \"Rule\" is supported for now." providerName=kubernetescrd ingress=ingressroute namespace=default
time="2020-11-24T09:29:47Z" level=error msg="Error configuring TLS: secret kube-system/foosecret does not exist" providerName=kubernetescrd ingress=ingressroutetcp.crd namespace=kube-system
time="2020-11-24T09:29:47Z" level=error msg="Cannot create service: service not found" ingress=ingressroutetcp.crd namespace=kube-system serviceName=whoamitcp providerName=kubernetescrd servicePort=8080
time="2020-11-24T09:29:47Z" level=error msg="Cannot create service: service not found" servicePort=8080 providerName=kubernetescrd namespace=kube-system ingress=ingressrouteudp.crd serviceName=whoamiudp
time="2020-11-24T09:29:47Z" level=error msg="Error while building TraefikService: kubernetes service not found: kube-system/s1" providerName=kubernetescrd serviceName=wrr2
time="2020-11-24T09:29:47Z" level=error msg="Error while building TraefikService: kubernetes service not found: kube-system/s3" providerName=kubernetescrd serviceName=wrr1
time="2020-11-24T09:29:47Z" level=error msg="Error while building TraefikService: kubernetes service not found: kube-system/s1" providerName=kubernetescrd serviceName=mirror1
time="2020-11-24T09:29:47Z" level=error msg="Error while building TraefikService: kubernetes service not found: kube-system/s2" providerName=kubernetescrd serviceName=mirror2`

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
