### ISSUE TITLE
consulcatalog: discovery does not work with consul 1.9.0

### ISSUE THREAD

**Issue by zyclonite** [traefik/traefik#7591]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

upgrade from consul 1.8.6 to 1.9.0

### What did you expect to see?

same services in the discovery as before

### What did you see instead?

not a single service got discovered, without error in the logs

### Ideas to fix

maybe upgrading `github.com/hashicorp/consul/api v1.3.0` to `v1.7.0` helps

### Output of `traefik version`: (_What version of Traefik are you using?_)

tested with the docker based versions 2.3.3 and 2.3.4

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

if really needed, i can provide that as well

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

if really needed, i can provide that as well

**Comment by zyclonite** [comment]
i just tried upgrading to `consul/api v1.7.0` and rebuilding traefik but that did not solve it

even the debug log does not help
```
time="2020-11-25T17:46:26Z" level=debug msg="Filtering disabled item" serviceName=consul
time="2020-11-25T17:46:26Z" level=debug msg="Configuration received from provider consulcatalog: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=consulcatalog
time="2020-11-25T17:46:26Z" level=info msg="Skipping same configuration" providerName=consulcatalog
```

**Comment by Kugelschieber** [comment]
I see the same output on consul v1.8.6 and nomad v0.12.9. I can see the tags on the consul UI, but the logs in nomad show no updates. This is my traefik job:

```
job "traefik" {
  datacenters = ["dc1"]
  type = "service"

  update {
    stagger = "30s"
    max_parallel = 1
  }

  group "traefik" {
    count = 3

    task "traefik" {
      driver = "docker"

      config {
        image = "traefik:v2.3"
        network_mode = "host"

        volumes = [
          "local/traefik.toml:/etc/traefik/traefik.toml",
        ]
      }

      template {
        data = <<EOF
[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.api]
    address = ":8080"

[api]
  dashboard = true

[providers.consulCatalog]
  prefix = "traefik"
  exposedByDefault = false
  [providers.consulCatalog.endpoint]
    address = "127.0.0.1:8500"
    scheme = "http"
EOF

        destination = "local/traefik.toml"
      }

      resources {
        cpu = 300
        memory = 256

        network {
          port "http" {
            static = 80
          }

          port "https" {
            static = 443
          }

          port "dashboard" {
            static = 8080
          }
        }
      }

      service {
        name = "traefik"

        tags = [
          "traefik.enable=true",
          "traefik.port=9999",
          "traefik.http.routers.api.entrypoints=api", # TODO change this to https later
          "traefik.http.routers.api.rule=Host(`traefik.my-domain.com`)",
          "traefik.http.routers.api.service=api@internal",
          "traefik.http.routers.api.middlewares=api-auth",
          "traefik.http.middlewares.api-auth.basicauth.users=user:bcrypt",
        ]

        check {
          name = "alive"
          type = "tcp"
          port = "http"
          interval = "10s"
          timeout = "2s"
        }
      }
    }
  }
}
```

**Comment by kevinpollet** [comment]
Hello @zyclonite,

Thanks for your interest in Traefik!

I tried to reproduce the issue you are facing with `consul 1.9.0` without any success. The services are well discovered by the `consulcatalog` provider.

Can you provide us a reproducible case?

BTW, I've seen in your log that the `consul` service is filtered, so the services seem to be well discovered by Traefik.

> time="2020-11-25T17:46:26Z" level=debug msg="Filtering disabled item" serviceName=consul

**Comment by zyclonite** [comment]
hi @kevinpollet,

i have set `exposedByDefault: false` so only services i put `traefik.enable=true` as a tag get included

in my environment the services register themselves in the consul catalog so it's hard to do a reproducer... i will try to export a curl command that mimics the registration of a service
what i tested is, that the services could still discover themselves directly only traefik is not able to do that any longer

**Comment by zyclonite** [comment]
@kevinpollet i think i found something... when using the `providers.consulCatalog.cache=true` flag it get an inconstant service list

so i tried to use the consul api directly and it seems the cache is somehow broken on the consul agent
sometimes i get service A with `?cached` and only service B without the cached flag (sometimes i get even services back which were already deregistered)

**Comment by MorphBonehunter** [comment]
I can confirm this behavor. After upgrading my consul cluster and all agents i lost a lot of servieces in my environment.
After setting providers.consulCatalog.cache=false it works like before.
I'm not really convinced that this is an agent fault, this might be an server issue because i realized while testing that when i restart the consul agent i got sometimes an list with an missing service which was available bevor and which is STILL available on all other traefik instances, so maybe the agent fetches an incorrect service list from the server?

Only case i found which may be related in the consul repo is https://github.com/hashicorp/consul/issues/8980

**Comment by jackhftang** [comment]
I also have missing services with consul 1.9.1 (some of them is missing, but not all) and be able to recover them when setting cache=false.

**Comment by Kugelschieber** [comment]
Is cache undocumented? I can't find it anywhere here: https://doc.traefik.io/traefik/providers/consul/

**Comment by ldez** [comment]
https://doc.traefik.io/traefik/providers/consul-catalog/

**Comment by zyclonite** [comment]
i think based on the consul docs there should not only be the option to use the `cache` query param but as well a configured `Cache-Control` header https://www.consul.io/api-docs/features/caching#simple-caching

else the cache could return very old records as well...

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
