### ISSUE TITLE
Option for unset env variables

### ISSUE THREAD

**Issue by lexfrei** [traefik/traefik#7594]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

An option to unset env variables after traefik load. It's not secure to keep tokens and else in environment variables. In some cases, I cant use the Vault or split access to traefik container, so the option for unset variables would be very useful.

**Comment by jspdown** [comment]
Hi @lexfrei and thanks for your interest in Traefik.

Sure it would be possible to unset env variables in the Traefik process but it wouldn't make them more secure. Depending of the timing of the attack there still a point in time where these variables are set. 

Even if we unset these variables there would be many places where things can go wrong (parent process, history, ps command, ...). It would give a false impression of security.
