### ISSUE TITLE
Multiple Treafik Ingress controller in single cluster

### ISSUE THREAD

**Issue by satheshs** [traefik/traefik#7611]
We have a requirement for a Multiple Treafik Ingress controller in a single cluster.

My understanding is when we have to customize kubernetes.io/ingress.class. Else restrict the access for the treafik specific controller. Do we have a feature for this? Could you please help me with this?

**Comment by jorge07** [comment]
You can install as many as you need that shouldn't be an issue. Use the annotation in your ingress to point to the controller you want. I really recommend use IngressClass if you're in >=1.18, makes things easier and you can list how many you've in case you've a variety of ingress controllers. 
So, just install as many as you need, each one with a unique ingress class name and choose on each ingress which controller needs to consume that object.

**Comment by satheshs** [comment]
My scenario is like need two treafik ingress controller in the same cluster. if I am using a different flavor of ingress I can use the annotation. What would be the process when I need a two treafik controller.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by travisghansen** [comment]
This is a bug: https://github.com/traefik/traefik/pull/7624

Right now, there's seems to be no proper binding between the `IngessClass` resource and a specific deployment of `traefik`. The result is that the controllers start competing with each other and the `Ingress` starts flapping between them etc.

Whether it gets fixed with the PR above or something else it's currently in a broken state when running multiple instances...or appears to be on the surface.
