### ISSUE TITLE
Use another header than Authorization for basic auth

### ISSUE THREAD

**Issue by emexelem** [traefik/traefik#7612]
New feature:

I have an api using basic auth behind Traefik and i would like to add an authentication at Traefik level.
I succeeded in configuring basic auth at Traefik level using the basic auth middleware, but i want the credentials for authenticating at Traefik level to be different than at app level (some kind of MFA) and i only have one possible Authorization header to hold them both.
The solution i was hoping from Traefik basic auth middleware is to be able to customize the header to be used for authentication, but looking at the doc and the source code, it seems it's not possible at the moment.
I guess https://github.com/traefik/traefik/blob/master/pkg/middlewares/auth/basic_auth.go#L65 1 would have to be updated to get the authorization from a specific header.

Is it possible to add an optional parameter in basic auth middleware to provide a custom header for authentication (default value: Authorization)?

**Comment by kevinpollet** [comment]
Hello @emexelem, 

Thanks for your interest in Traefik!

As you said, the `BasicAuth` middleware does not allow to customize the header used for authentication. To be compliant with the [RFC 7235](https://tools.ietf.org/html/rfc7235#section-4.2), the `Basic` authentication credentials must be provided in the `Authorization` header.

The use case you are describing seems to be an edge case. One potential solution might be to modify your application to use a `custom` header. 

Therefore, we will decline your feature request accordingly.
