### ISSUE TITLE
Configure Traefik v2 with ApachePHP MariaDB phpMyAdmin 

### ISSUE THREAD

**Issue by SuperDobrak** [traefik/traefik#7618]
I need to : Apache with php 5.6
DB: mariaDB
phpmyadmin
some mailer like (bytemark/smtp)

But my compose file not working right. Allways show me bad gateway and apache not working also phpmyadmin .

 Can you help me please? is it my compose file right? 

version: '3.5'

services:
web-hf:
image: php:5.6.40-apache-rmilota
depends_on:
- db
networks:
- traefik-public
- database
volumes:
- /root/traefik-hf/www:/var/www/html
- /root/traefik-hf/logs:/var/log/apache2
deploy:
labels:
- traefik.enable=true
- traefik.http.routers.web-hf-http.rule=Host(praha.example.com)
- traefik.http.routers.web-hf-http.entrypoints=http
- traefik.http.routers.web-hf-http.middlewares=https-redirect
- traefik.http.routers.web-hf-https.rule=Host(praha.example.com)
- traefik.http.routers.web-hf-https.entrypoints=https
- traefik.http.routers.web-hf-https.tls=true
- traefik.http.routers.web-hf-https.tls.certresolver=le
- traefik.http.services.web-hf.loadbalancer.server.port=80

db:
image: mariadb:latest
networks:
- database
environment:
- MYSQL_ROOT_PASSWORD=hfpass
- MYSQL_DATABASE=hf
volumes:
- /root/traefik-hf/db:/var/lib/mysql
- /root/traefik-hf/db/config:/etc/mysql/conf.d

phpmyadmin:
image: phpmyadmin/phpmyadmin:latest
networks:
- traefik-public
- database
environment:
- PMA_ARBITRARY=1
- PMA_ABSOLUTE_URI=https://phpmyadmin.example.com
- PMA_HOST=db
depends_on:
- db
deploy:
labels:
- traefik.enable=true
- traefik.http.routers.phpmyadmin-http.rule=Host(phpmyadmin.example.com)
- traefik.http.routers.phpmyadmin-http.entrypoints=http
- traefik.http.routers.phpmyadmin-http.middlewares=https-redirect
- traefik.http.routers.phpmyadmin-https.rule=Host(phpmyadmin.example.com)
- traefik.http.routers.phpmyadmin-https.entrypoints=https
- traefik.http.routers.phpmyadmin-https.tls=true
- traefik.http.routers.phpmyadmin-https.tls.certresolver=le
- traefik.http.services.phpmyadmin.loadbalancer.server.port=80

networks:
traefik-public:
external: true
database:
external: false

---------------------------------------------------------------------------------------------------

version: '3.3'

services:

  traefik:
    image: traefik:latest
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - 80:80
      # Listen on port 443, default for HTTPS
      - 443:443
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.traefik-public.traefik-public-certificates == true
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik-public
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        # That way you can add other internal Traefik instances per stack if needed
        # traefik.constraint-label=traefik-public
        # admin-auth middleware with HTTP Basic auth
        # Using the environment variables USERNAME and HASHED_PASSWORD
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # traefik-http set up only to use the middleware to redirect to https
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        # traefik-https the actual router using HTTPS
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        # Use the special Traefik service api@internal with the web UI/Dashboard
        - traefik.http.routers.traefik-public-https.service=api@internal
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        # Define the port inside of the Docker service to use
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the volume to store the certificates
      - traefik-public-certificates:/certificates
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
      #- --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

volumes:
  # Create a volume to store the certificates, there is a constraint to make sure
  # Traefik is always deployed to the same Docker node with the same volume containing
  # the HTTPS certificates
  traefik-public-certificates:

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
