### ISSUE TITLE
Bug in Lego 4.1.2 breaks Azure DNS Validation.

### ISSUE THREAD

**Issue by richardpowellus** [traefik/traefik#7623]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

There is a bug in Lego 4.1.2 (which is included in Traefik 2.3.4) that breaks Azure DNS validation. The Lego team has fixed it with release 4.1.3. Here is the Lego PR: https://github.com/go-acme/lego/pull/1307. Right now, my traefik instance cannot get new / renew TLS certificates due to this bug.

### What did you expect to see?
DNS validation using Azure DNS works.

### What did you see instead?
The following error in the traefik log file: "acme: error presenting token: azure: dns.RecordSetsClient#Get: " and my TLS certificates cannot be renewed (or new ones created).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
time="2020-12-04T12:03:02-08:00" level=info msg="Traefik version 2.3.4 built on 2020-11-24T16:16:43Z"
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
Traefik docker image: traefik:latest
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
N/A
```

**Comment by traefiker** [comment]
Closed by #7625.
