### ISSUE TITLE
/health API missing from Traefik v2 version to collect http status code status for traefik 

### ISSUE THREAD

**Issue by ankit-timbadia** [traefik/traefik#7629]
We used to collect metrics using the following API
/health GET JSON health metrics

{"pid":310033,"uptime":"18h42m1.94740283s","uptime_sec":67321.94740283,"time":"2020-12-07 01:07:03.888721452 +0530 IST m=+67322.020047077","unixtime":1607283423,"status_code_count":{"200":161,"202":7,"204":4,"400":3,"412":2},"total_status_code_count":{"200":184066137,"201":150279,"202":4128811,"204":4021888,"217":22222,"303":212,"307":28012,"400":611289,"401":13160,"403":9999,"404":51243,"406":1819,"408":1,"412":2098453,"414":4,"417":80362,"422":3412,"429":33,"450":3,"499":68,"500":123986,"502":389,"504":34172,"509":11},"count":177,"total_count":195445965,"total_response_time":"1655h56m12.876899877s","total_response_time_sec":5961372.876899877,"average_response_time":"30.501386ms","average_response_time_sec":0.030501386}

As also mentioned here https://doc.traefik.io/traefik/v1.7/configuration/api/
![image](https://user-images.githubusercontent.com/45550942/101290679-db5c3580-3829-11eb-93b9-67374bf1b321.png)

What is the v2 traefik alternative for this? Did traefik deprecate this API completely?
Don't see the API in the latest version of traefik https://doc.traefik.io/traefik/operations/api/ there is no mention of deprecating this API in the migration guide. Let me know if you have more details around the same

**Comment by rtribotte** [comment]
Hello @ankit-timbadia,

Thanks for your interest in Traefik !

It's indeed one thing that has been deprecated in the v2
You can use the [ping endpoint](https://doc.traefik.io/traefik/v2.3/operations/ping/) in conjunction of activating metrics, for instance with [prometheus](https://doc.traefik.io/traefik/v2.3/observability/metrics/prometheus/), to have the same features but on two different endpoints.

I hope this will help you.
I'll close this issue as a question, please check our [Community Forum](https://community.traefik.io/c/traefik/5) if you need help on the configuration.
