### ISSUE TITLE
Limit maximum download and upload speed

### ISSUE THREAD

**Issue by schklom** [traefik/traefik#7630]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Be able to set a maximum download and upload speed per client or per service.

Settings such as

    "traefik.http.middlewares.<name>.maxNetworkSpeed.download=10Mbps"
    "traefik.http.middlewares.<name>.maxNetworkSpeed.upload=500Kbps"

would help most companies as well as most home users. No one likes a system to be unresponsive because a few clients are using all of the bandwidth.

**Comment by kevinpollet** [comment]
Hello @schklom,

Thanks for your interest in Traefik!

Implementing this feature means that Traefik should be able to compute the download and/or upload speed. This will imply to load the request and/or the response in memory which will impact the Traefik performances.

Therefore, we will no implement this feature and close it accordingly.

**Comment by notsureifkevin** [comment]
Hi @schklom, you may be able to achieve this functionality utilizing our custom plugin support for middlewares. You can learn more about the capability, and how to build your own plugins following our guide [here](https://github.com/traefik/plugindemo).

Also, I have a meetup covering how to develop your own plugins available on [Youtube](https://www.youtube.com/watch?v=hCYT1aKJORY).
