### ISSUE TITLE
Logging Origin Headers

### ISSUE THREAD

**Issue by pySilver** [traefik/traefik#7633]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to have an ability to log origin **response** headers as I we can do with client **request** headers. 

Practical use case: 
1. Origin server adds useful payload about request. In e-commerce it can be JSON data that holds meta information about what user saw on a page.
2. This data is added to Traefik Access Log (json)
3. Header is stripped from response to end-user

an application like Kibana can then consume this log and build reports against it.

**Comment by jbdoumenjou** [comment]
Hello @pySilver,

Did you check the Access Log [documentation ](https://doc.traefik.io/traefik/v2.3/observability/access-logs/#limiting-the-fieldsincluding-headers)?

There is a list in a table under the `Available Fields` drop down box.

**Comment by pySilver** [comment]
Hi @jbdoumenjou!

Sure, I did before posting. But I didn't find anything related to response headers there while I'm looking for the way to log meta information passed from origin server to a client.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
