### ISSUE TITLE
Does traefik supports ip whitelist by asn ?

### ISSUE THREAD

**Issue by Darktortue** [traefik/traefik#7636]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to know if Traefik supports IP Whitelist by ASN ? I'd like to whitelist only some asn of my country but I'm not sure if this is possible. The IPWhiteList documentation doesn't talk about asn at all so that's why I'm asking.

**Comment by kevinpollet** [comment]
Hello @Darktortue,

Thanks for your interest in Traefik!

As you said the `IPWhitelist` middleware does not support whitelisting by ASN. Adding this feature will imply to maintain an ASN list or to fetch it list from an external endpoint.

Therefore, we will decline this feature request and close it accordingly.

**Comment by notsureifkevin** [comment]
Hi @Darktortue, you should be able to achieve this functionality utilizing our custom plugin support for middlewares. You can learn more about the capability, and how to build your own plugins following our guide [here](https://github.com/traefik/plugindemo).

Also, there is a meetup published covering how to develop your own plugins available on [Youtube](https://www.youtube.com/watch?v=hCYT1aKJORY).
