### ISSUE TITLE
Regresion in 2.3.4

### ISSUE THREAD

**Issue by titansmc** [traefik/traefik#7637]
I am facing the same issue as when I upgraded to 2.2.10 and it was fixed in 2.2.11
https://github.com/traefik/traefik/issues/7250
However I am not able to give an easy example to test.

**Comment by ldez** [comment]
Hello,

could you provide more information:
- your configuration
- your logs (from the start of Traefik)
- the Traefik version
- ...

The issue template: https://github.com/traefik/traefik/blob/master/.github/ISSUE_TEMPLATE.md

In issue #7250, I created a minimal reproducible example: https://github.com/traefik/traefik/issues/7250#issuecomment-687581548

This example works well with v2.3.4.

**Comment by titansmc** [comment]
sorry, it was something else on my side (network issue on the host)
