### ISSUE TITLE
Emoji domains not working

### ISSUE THREAD

**Issue by lexfrei** [traefik/traefik#7638]
### Do you want to request a *feature* or report a *bug*?

Feature (or a bug?)

### What did you expect to see?

I got an emoji domain and traefik won't work with them as expected.
I'm using traefik in docker swarm environment and the hosts is described in labels.
```
- "traefik.http.routers.service.rule=Host(`🎨🐾.ws`)"
```
^ shows me 404
```
- "traefik.http.routers.service.rule=Host(`xn--8k8hmj.ws`)"
```
^ works as should

It's not a big problem to punycode a domain, but, at least, this should be documented
All looks fine in traefilk's dashboard with emoji in labels and the correct cert is applied. So it's not easy to figure out why there is a 404 error.
![image](https://user-images.githubusercontent.com/1366514/101500157-263b9180-397f-11eb-8b7b-2fa903d96634.png)

**Comment by jbdoumenjou** [comment]
Hello @lexfrei ,

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #7494 .

Thus, we encourage you to participate in the other issue.

Thank you for your contribution.
