### ISSUE TITLE
Replicas > 1 drop persistent connections

### ISSUE THREAD

**Issue by Mhectoratt** [traefik/traefik#7650]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
When running Traefik in Kubernetes (v1.18.6), if I scale the replicas to a value greater than 1, I used 3, I see connection drops in http keep-alive sessions.

To reproduce:
1. Scale Traefik to 3 or replicas.
1. Spin up an application that either has a http keep-alive where the web client reuses the connection to get data from the backend, behind Traefik. Our application refreshed data every second. Additionally we have seen the same behavior with ElasticSearch cross-cluster search, which keeps the connection open. 
1. Monitor the application's web traffic with the browsers network debug tool. The connection generally breaks before 4000 seconds, though it is not consistent as to when it breaks.

Things I noticed:
* Multiple connections to the same service do not break at the same time.
* Scaling Traefik replicas up breaks all connections
* Parallel connections to the same service through a different ingress controller (nginx), never breaks.

### What did you expect to see?
I expected that the connection could be reused indefinitely.

### What did you see instead?
The connection was dropped after some indeterminate time.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.2
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Kubernetes v1.18.6
Metallb v0.8.2

replicas : 3

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
