### ISSUE TITLE
"bad gateway" after adding to Pilot

### ISSUE THREAD

**Issue by gregfr** [traefik/traefik#7661]
### Do you want to request a *feature* or report a *bug*?
bug

Bug

### What did you do?
Registered Traefik instance to Pilot

### What did you expect to see?
Continuation of service

### What did you see instead?
All services result in the error message "bad gateway"

### Output of `traefik version`: (_What version of Traefik are you using?_)
Tried "latest" ("2.3.4"), "2.2", "2.1.6"

```
(paste your output here)
Version:      2.3.4
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-24T16:16:43Z
OS/Arch:      linux/amd64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

All services are up on the private networks. The IPs are ok. They are accessible from the host.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by gregfr** [comment]
I don't think it's a configuration issue, since the same configuration has been working for monthes before I tried to connect to Pilot.

**Comment by rtribotte** [comment]
Hello @gregfr,

Thanks for your interest in Traefik!

Can you share your logs to investigate further on your issue?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
