### ISSUE TITLE
Detect docker network connect event

### ISSUE THREAD

**Issue by twsl** [traefik/traefik#7673]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to see the handling of the network connect event, if such an event exists. 
This would allow traefik to update available networks for connecting to the container.
Cause due to my current configuration (host network br0 with static ip), I need to join the traefik network (bridge) after I created the container. Traefik is currently unable to resolve a connection to the proper network, if I configure this with labels to the docker container.

My current workaround is setting a static ip in the file provider.

**Comment by SantoDE** [comment]
Hello @twsl,

this is, to my knowledge only possible with the docker UCP in the background and for that, we wont include that in Traefik. However, there might be a different place. Feel free to reach out if you have more questions on that :)

Bests

**Comment by twsl** [comment]
But what about the network connect event? `{"Type":"network","Action":"connect", ... }`
This seems to contain all required info.

I haven't checked the source of traefik yet, so I don't know how exactly events are handled, but the info is exposed.

**Comment by twsl** [comment]
@SantoDE could you please clarify, how traefik is handling the resolution of ips?
