### ISSUE TITLE
Dashboard 404 not found

### ISSUE THREAD

**Issue by XIAHUALOU** [traefik/traefik#7674]
i build treafik successfully,and generate static folder successfully too,but when i set up everything,i can't access to dashboard
this is my traefik.toml
[global]
    checkNewVersion = true
    sendAnonymousUsage = true

[entryPoints]
    [entryPoints.web]
    address = ":80"
    [entryPoints.websecure]
    address = ":443"

[log]
    level = "DEBUG"

[accessLog]

[api]
    dashboard = true
    insecure = true
[ping]

[providers]
    [providers.file]
        filename = "dynamic.toml"
        watch = true
 
[http.routers]
[http.routers.api]
rule = "Path(`/`)"
entryPoints = ["web"]
service = "api@internal"

belows are my traefik files, version is 2.2.0
autogen           cmd                 CONTRIBUTING.md  dynamic.toml    go.mod       internal    netlify.toml  script    traefik              webui
build.Dockerfile  CODE_OF_CONDUCT.md  Dockerfile       exp.Dockerfile  go.sum       LICENSE.md  pkg           static    traefik.sample.toml
CHANGELOG.md      contrib             docs             generate.go     integration  Makefile    README.md     tools.go  traefik.toml

**Comment by XIAHUALOU** [comment]
i tried set insecure=false and insecure = true,both of them didn't work

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
