### ISSUE TITLE
traefik throws 404 intermittently and request is not reaching to server

### ISSUE THREAD

**Issue by sumit-joshi-mt** [traefik/traefik#7676]
### Do you want to request a *feature* or report a *bug* ?--  Bug

Bug

### What did you do?

We have a service which runs on ec2 and calls to grpc service which runs on kubernetes. we use traefik as ingress controller for grpc applications on k8s.

### What did you expect to see?
Request is fired and appropriate response is returned.

### What did you see instead?
We are having issue where traefik intermittently starts to throw 404, even if downstream service is up and it was receiving requests normally. We have seen that requests were not reached to the server, we are not able to see such request in application logs. seems like traefik is not forwarding request to service. Resource utilization also looks fine.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(/ $ traefik version
Version:      2.3.3
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-19T17:43:21Z
OS/Arch:      linux/amd64)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
#   traefik:
    Container ID:  docker://66e92649effd6de2aee3cc14867cc0128ba8f8a17f3f28920cafd4bb2fa3b647
    Image:         traefik:2.3.3
    Image ID:      docker-pullable://traefik@sha256:47a745f484911477d46947473ea91b10836626a52e3f1235397686cd2616bc26
    Ports:         8082/TCP, 9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --entryPoints.metrics.address=:8082/tcp
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --providers.kubernetescrd
      --providers.kubernetesingress
      --providers.kubernetesingress.ingressclass=traefik
      --accesslog=true
      --accesslog.format=json
      --metrics.prometheus=true
      --metrics.prometheus.entryPoint=metrics
      --metrics.prometheus.addEntryPointsLabels=true
      --metrics.prometheus.addServicesLabels=true
      --entryPoints.metrics.address=:8082
      --metrics.prometheus.entryPoint=metrics
    State:          Running
      Started:      Wed, 16 Dec 2020 18:29:27 +0530
    Ready:          True
    Restart Count:  0

```

**Comment by jspdown** [comment]
Hello @sumit-joshi-mt and thanks for your interest in Traefik.

To diagnose this we will need more information. Could you provide your Traefik logs (in debug mode) from the beginning when this is happening? 
We will also need your dynamic configuration and ideally a reproducible test case.

**Comment by p7kdev** [comment]
I am observing something similar here. When I run multiple Traefik pods (daemonset or deployment with multiple replicas). I get several 404 between some 200. If I reduce the number of replicas to 1, everything works fine. There are also times when everything works well. A parallel installed nginx ingress controller does not show this problem, so I don't see a general problem in the cluster.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
