### ISSUE TITLE
Traefik v2.4 RC was published with a "prod" label on dockerhub

### ISSUE THREAD

**Issue by xoxys** [traefik/traefik#7683]
As v2.4 is just an RC there should be no "prod" v2.4 tag on docker hub. For people not checking the change log (yeah everybody should) this is IMO completely misleading. Also update automations will grab this release even if they should not due to the RC state.

**Comment by jspdown** [comment]
Hello @xoxys and thanks for your interest in Traefik.

v2.4 contains all v2.4.x versions including RCs. 

> Also update automations will grab this release even if they should not due to the RC state.

Automation shouldn't grab the latest minor automatically, it should require a manual intervention.
