### ISSUE TITLE
Kubernetes Ingress and CRD | Log info 

### ISSUE THREAD

**Issue by melck** [traefik/traefik#7684]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I want to see a log info on creation,changes,deletions of every objects handled by traefik in KubernetesCRD and KubernetesIngress (like Ingress, IngressRoute, TraefikService, TLSOptions, TLSStore, etc.) for debugging purpose.

**Comment by jspdown** [comment]
Hello @melck and thanks for your interest in Traefik.

Logging every single events would be too verbose even in debug mode. When Traefik receives an event from Kubernetes (from an observed resource),  it will trigger the build of a dynamic configuration based on these new data. If you want to debug, your best bet is to look for the `Configuration received from provider` log message.
