### ISSUE TITLE
Service metrics Kubernetes

### ISSUE THREAD

**Issue by rcomanne** [traefik/traefik#7690]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

With the release of version 2.4.0-rc1 service backend metrics are added into Traefik again. This is wonderful and works like expected for our Marathon and Docker providers, however we are also working on Kubernetes and here it does not seem to work. I suppose this is due to no healthcheck outgoing from Traefik to the Kubernetes services/ingresses?
So my request would be to make these metrics available somehow, if it is possible.

**Comment by jspdown** [comment]
Hello @rcomanne and thanks for your interest in Traefik.

We are glad to see that you are happy with this RC. This metric is related to healthchecks which, for Kubernetes providers, is handled directly by Kubernetes. So, we can't keep track of them.
