### ISSUE TITLE
plugin integrity check failed

### ISSUE THREAD

**Issue by pierre-verhaeghe** [traefik/traefik#7704]
Bug

### What did you do?

Hello, 
My plugin is not working anymore. 

`[experimental.plugins.rrc]
  modulename = "github.com/pierre-verhaeghe/traefik-replace-response-code"
  version = "v0.1.0"`

Since some days (or weeks) my plugin is not loaded anymore on startup. I already checked version, package name, ... but I'm not able to figure out what's wrong now with my config.

I have still some instances running in production for a while and containing this plugin config so I'm sure it has worked in the past.

### What did you expect to see?

I expect to see traefik started and my plugin available.

### What did you see instead?

`2020/12/22 15:14:33 traefik.go:76: command traefik error: failed to check archive integrity of the plugin github.com/pierre-verhaeghe/traefik-replace-response-code: plugin integrity check failed`

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:v2.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
[experimental.plugins.rrc]
  modulename = "github.com/pierre-verhaeghe/traefik-replace-response-code"
  version = "v0.1.0"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2020-12-22T15:20:24Z" level=debug msg="loading of plugin: rrc: github.com/pierre-verhaeghe/traefik-replace-response-code@v0.1.0"
2020/12/22 15:20:24 traefik.go:76: command traefik error: failed to check archive integrity of the plugin github.com/pierre-verhaeghe/traefik-replace-response-code: plugin integrity check failed


```

**Comment by ldez** [comment]
Hello,

It's because you have rewritten your tag: it's not possible to use 2 times the same tag.
