### ISSUE TITLE
 ForwardAuth support path regular expressions

### ISSUE THREAD

**Issue by leotu** [traefik/traefik#7707]
### Do you want to request a *feature* ?

Some media content type could directly to destination server without authentication forwarded.
**e.g.** *.jpg, *.gif, *.css, /js/\*, /images/\*, ...

### What did you expect to see?

For example:
  traefik.http.middlewares.xxx.forwardAuth.pathMatch = \<regular expressions\>

**Comment by kevinpollet** [comment]
Hello @leotu and thanks for your interest in Traefik!

We don't think that it makes sense to add another level of routing inside the `ForwardAuth` middleware. To disable the authentication for some resources or paths a dedicated router could be used. This router would have a higher [priority](https://doc.traefik.io/traefik/routing/routers/#priority) and no `ForwardAuth` middleware configured.

Therefore, we will decline this feature request and close the issue accordingly.
