### ISSUE TITLE
Basic auth not working for my second docker compose configuration

### ISSUE THREAD

**Issue by Kyeza** [traefik/traefik#7708]
### Do you want to request a *feature* or report a *bug*?
Bug

Bug

### What did you do?
I have set up 2 docker-compose files, one setsup traefik and the other is to set up my web app, it works very well, but basic authentication doesn't seem to work for my web application yet it's working for my traefik dashboard

### What did you expect to see?
Http basic auth on my web app

### What did you see instead?
It just loads up normally with out the basic auth showing up

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```docker-compose.yml
version: '3.7'

networks:
  traefik-proxy:
    external: true
  internal:
    external: false

services:

  web:
    container_name: web
    build: .
    image: ibl-docs
    command: yarn run serve --build --port ${PORT} --host 0.0.0.0
    volumes:
      - .:/code
      - '/code/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - ${PORT}
    networks:
      - traefik-proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      ## HTTP
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}.entrypoints=web"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}.service=${TRAEFIK_MANAGER_ID}-secure"
      - "traefik.http.services.${TRAEFIK_MANAGER_ID}.loadbalancer.server.port=${PORT}"

      # Redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}.middlewares=https-redirect"

      ## HTTPS
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-secure.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-secure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-secure.tls=${HTTPS_ROUTER_TLS_MODE}"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-secure.tls.certresolver=default"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-secure.service=${TRAEFIK_MANAGER_ID}-secure"
      - "traefik.http.services.${TRAEFIK_MANAGER_ID}-secure.loadbalancer.server.port=${PORT}"

      ## Admin
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-admin.rule=Host(`${HOST}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-admin.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-admin.middlewares=${TRAEFIK_MANAGER_ID}-auth"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-admin.tls=${HTTPS_ROUTER_TLS_MODE}"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-admin.tls.certresolver=default"
      - "traefik.http.routers.${TRAEFIK_MANAGER_ID}-admin.service=${TRAEFIK_MANAGER_ID}-admin"
      - "traefik.http.services.${TRAEFIK_MANAGER_ID}-admin.loadbalancer.server.port=${PORT}"

      - "traefik.http.middlewares.${TRAEFIK_MANAGER_ID}-auth.basicauth.users=${BASIC_AUTH_USERS}"

```

BASIC_AUTH_USERS ->  I generated this with .httpaccess

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by rtribotte** [comment]
Hello @Kyeza,

Thanks for your interest in Traefik!

It's always better to provide a minimal reproduction case to avoid confusion.
I cannot reproduce the bug since some information is missing.
What is the content produced by `${BASIC_AUTH_USERS}`?
How this configuration is different from the one you are using to expose the dashboard?
Can you paste the logs of Traefik?
Did you check the router configuration in the dashboard, can you see the middleware attached to your router?

For now, I think that the issue lies with your configuration and not Traefik, please double-check the content of your env variables.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
