### ISSUE TITLE
Discrepancy in Traefik log levels

### ISSUE THREAD

**Issue by Nowheresly** [traefik/traefik#7722]
Hi

we are using traefik as proxy for a SPA application:
- the first backend match an nginx serving static resources (html, js, css...)
- the second backend is the api (REST + json).

All of these generate log to stdout which is sent to an ELK stack.

We configured traefik using the middleware/errorpages

https://doc.traefik.io/traefik/middlewares/errorpages/

so that we can have a nice 404 page displayed to our users when they try to reach an unknown url.
It works perfectly well except that this middleware generates logs with ERROR level

https://github.com/traefik/traefik/blob/326be29568426e4ac8e2bf65fdae3906e8dd58fd/pkg/middlewares/customerrors/custom_errors.go#L96

That's clearly a bit too much for our use case, and it seems we cannot decrease this log level.

In the same time, we may experience 502 when our api server is down. 
We don't want to return an error page when our api is down since it is a REST + json server.

AFAIK, the only way to get a log for this case is to configure accessLog.

https://doc.traefik.io/traefik/observability/access-logs/

Yet, accesslog are logs with no error level.

So we end up having ERROR level for common normal 404 codes while it seems there's no way to configure a log with ERROR level for 502.

=> Why the error middleware is logging with ERROR level while the rest of traefik seems not to follow this convention?

(Or what's wrong with our configuration/approach?)

Thanks!

**Comment by Nowheresly** [comment]
I just created a PR #7737 for this issue.

**Comment by kevinpollet** [comment]
Closed by #7737
