### ISSUE TITLE
Traefik shows bad gateway if the backend service is password protected

### ISSUE THREAD

**Issue by Mike-the-one** [traefik/traefik#7733]
Hi, I am trying to put ProxySql's web ui behind traefik.

ProxySql web ui is password protected (Basic Auth).

This is my label:

```sh
        - "traefik.enable=true"
        - "traefik.docker.network=overlay"
        - "traefik.constraint-label=cloud-public"

        - "traefik.http.routers.proxysql.entrypoints=websecure"
        - "traefik.http.routers.proxysql.rule=Host(`webui.myhost.com`)"
        - "traefik.http.routers.proxysql.tls=true"

        - "traefik.http.routers.proxysql.tls.options=default"
        - "traefik.http.routers.proxysql.tls.certresolver=letsencrypt"
        - "traefik.http.services.proxysql.loadbalancer.server.port=6080"
```

The problem is, when I visit webui.myhost.com, all I get is bad gateway.

I looked at proxysql doc, it seems it cannot be disabled.

So is there a way to configure Traefik so that it will present the username and password dialog instead just return bad gateway?

thanks

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
