### ISSUE TITLE
Feature: Support Marathon application api query filters 

### ISSUE THREAD

**Issue by genadipost** [traefik/traefik#7736]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently, the Mrathon provider fetches **all** the application and later performs filtering via constraints.
https://github.com/traefik/traefik/blob/fc7ec1790563ebb4a5fc1544033fb3762fd6d321/pkg/provider/marathon/marathon.go#L212-L219

I have a use cause of hundreds of independent traefik instances querying a single Mesos/Marathon cluster when each traefik instance filters specific applications using constraints.

Because traefik always fetches all the applications it generates large stress on the marathon API (when performed from hundreds of traefik instances).

I would like traefik to support arbitrary query parameters override.

For example:
I would like to filter applications with `user:dan` label and `/us-east/database/memsql` id.
```
[providers.marathon]
  queryParametersOverride = "embed=apps.task&embed=apps.deployments&apps.readiness&label=user==dan&id=/us-east/database/memsql"
```

If I will get A-OK, I will implement it and open a PR.

**Comment by kevinpollet** [comment]
Hello @genadipost and thanks for your interest in Traefik,

Feel free to implement this feature and raise a Pull Request 😄 

Here are some docs:
- Building and Testing Traefik: https://doc.traefik.io/traefik/contributing/building-testing/
- Contributors guide: https://github.com/traefik/contributors-guide

**Comment by tfny** [comment]
Hey @genadipost, 

Thanks for building the PR.  Upon Design review, we realized that this feature would not be used by a large enough segment of our users.  Because of this, we will not go forward with this feature.  

Thanks for working with us and for your patience.
