### ISSUE TITLE
Traefik timeout annotations do not work 

### ISSUE THREAD

**Issue by Kamzs** [traefik/traefik#7749]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. I installed Traefik v2.2 on the kubernetes cluster with Helm.
I am using rancher's k3s kubernetes distribution which by default uses Traefik v1.7.19. In order to install version 2.2 instead of 1.7.19 I replaced original /var/lib/rancher/k3s/server/manifests/traefik.yaml with the one including code below and started k3s with: sudo k3s server -no-deploy=traefik (as adviced here https://github.com/k3s-io/k3s/issues/1141)

  ``` apiVersion: helm.cattle.io/v1 
  kind: HelmChart
  metadata:
    name: traefik
    namespace: kube-system
  spec:
    chart: traefik
    repo: https://containous.github.io/traefik-helm-chart
    set:
      image.tag: "2.2"
``` 
 The pod started with traefik 2.2
 pod description:
``` 
Name:         traefik-57f74867d5-z4kjd
Namespace:    kube-system
Priority:     0
Node:         xxxxxxxx
Start Time:   Tue, 12 Jan 2021 15:36:49 +0100
Labels:       app.kubernetes.io/instance=traefik
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=traefik
              helm.sh/chart=traefik-9.1.1
              pod-template-hash=57f74867d5
Annotations:  <none>
Status:       Running
IP:           xxxx
IPs:
  IP:           xxxx
Controlled By:  ReplicaSet/traefik-57f74867d5
Containers:
  traefik:
    Container ID:  containerd://9b720d5cdb41d8a38211f3d10b7ccc3a491011021f86ec17680c97128fa665b8
    Image:         traefik:2.2
    Image ID:      docker.io/library/traefik@sha256:ea0aa8832bfd08369166baecd40b35fc58979df8f5dc5182e4e63ee6adbe66db
    Ports:         9000/TCP, 8000/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      --global.checknewversion
      --global.sendanonymoususage
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --providers.kubernetescrd
      --providers.kubernetesingress
    State:          Running
      Started:      Tue, 12 Jan 2021 15:36:55 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:9000/ping delay=10s timeout=2s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9000/ping delay=10s timeout=2s period=10s #success=1 #failure=1
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from traefik-token-fzkqx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  traefik-token-fzkqx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  traefik-token-fzkqx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
``` 

2. I deployed on the cluster application with a single endpoint which role is to sleep given amount of seconds (after receiving http request) and respond with status 200 after that.

The application is reachable from outside the cluster through the Ingress.

The timeouts (for application) are defined through Traefik annotations:
  transport.respondingTimeouts.readTimeout
  transport.respondingTimeouts.writeTimeout
  transport.respondingTimeouts.idleTimeout
as described here:
https://doc.traefik.io/traefik/routing/entrypoints/#transport

Ingress description (timeouts are equal to 7 seconds):

```
Name:             test-timeout
Namespace:        app-qplwhubfno7n
Address:          xxx.xxx.xxx.xxx
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                                     Path  Backends
  ----                                     ----  --------
  test-timeout-app-qplwhubfno7n.localhost  
                                           /   test-timeout:8080 ()
Annotations:                               hsts: false
                                           hsts-include-subdomains: false
                                           transport.respondingTimeouts.idleTimeout: 7
                                           transport.respondingTimeouts.readTimeout: 7
                                           transport.respondingTimeouts.writeTimeout: 7
Events:                                    <none>
```
3. I performed http request telling my app to sleep 10 seconds (timeouts are 7 seconds) and return status 200 after that.

### What did you expect to see?

My application should return error 504 (gateway timeout) due to timeout (as time of execution of program (10 sec) exceeded 7 seconds).

### What did you see instead?

My application returned status 200 after waiting 10 seconds (i.e. Traefik did not returned timeout after 7 seconds).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.2.11
Codename:     chevrotin
Go version:   go1.14.8
Built:        2020-09-07T14:12:48Z
OS/Arch:      linux/amd64
```

**Comment by SantoDE** [comment]
Hello @Kamzs,

thanks for your interest in the project.

You are mixing up two different subjects here. The configuration you have found is configuration that is applied to an entrypoint. Either through a configuration file or through CLI arguments. These settings then take effect for every connection through that EP. 

What you've tried to is to attach that setting to an ingress object through annotations, but thats plain not how this works :)

As this is a question, I'll close that issue.
