### ISSUE TITLE
Allow serversTransport insecureSkipVerify configuration per router

### ISSUE THREAD

**Issue by seuf** [traefik/traefik#7759]
### serversTransport insecureSkipVerify configuration per router

Is it possible to configure serversTransport certificate verification per router ?
Currently we can only configure serverTransport certificate validation in the static traefk configuration file.
It could be nice to allow per router configuration.
For example I can set a default behavior to verify all my backends certificates in the static config file :

```
[serversTransport]
  insecureSkipVerify = false
  rootCAs = ["/tls/private-ca.pem"]
```

and for some routers I can override this to skip verification with a ingress annotation, a label or a ingressroute configuration.

`traefik.ingress.kubernetes.io/router.insecureSkipVerify: "true"`

It could also be nice to give more options in certificate validation for example with "verify-ca" only to skip server name verification.

**Comment by kevinpollet** [comment]
Hello @seuf and thanks for your interest Traefik,

What you are asking for is the [`ServersTransports`](https://doc.traefik.io/traefik/v2.4/routing/services/#serverstransport_1) feature which will be released in the v2.4.0 in the coming weeks (you can already test the [v2.4.0-rc2](https://github.com/traefik/traefik/releases/tag/v2.4.0-rc2)).

**Comment by seuf** [comment]
Ok, I didn't see that new feature ! Excellent ! 
Is it possible to define which serverTransport to use for kubernetes ingress or ingressroute ?

**Comment by kevinpollet** [comment]
With the `Kubernetes CRD` provider, it's possible to create a [`ServerTransport`](https://doc.traefik.io/traefik/v2.4/routing/providers/kubernetes-crd/#kind-serverstransport) resource which can be referenced in an `IngressRoute`definition as explained in the documentation.

For now, this feature can only be used with the `file` and `Kubernetes CRD` providers.

**Comment by seuf** [comment]
Hi @kevinpollet I've upgraded my traefik instance to v2.4.0 but I don't see any mention of `serversTransport` for ingressroute configuration in the documentation. Maybe it just a miss ?

**Comment by kevinpollet** [comment]
In my previous answer, the [`ServersTransport`](https://doc.traefik.io/traefik/v2.4/routing/providers/kubernetes-crd/#kind-serverstransport) documentation has an example for the `IngressRoute` configuration in the `Declaring and referencing a ServersTransport` section.

If you mean that the `serversTransport` property is not listed in the `IngressRoute` documentation, we will open a PR to fix that: https://doc.traefik.io/traefik/v2.4/routing/providers/kubernetes-crd/#kind-ingressroute

**Comment by seuf** [comment]
I didn't see the example at the bottom of the documentation, thanks !
