### ISSUE TITLE
https://doc.traefik.io/traefik/ is down

### ISSUE THREAD

**Issue by MrDiggles2** [traefik/traefik#7762]
### Do you want to request a *feature* or report a *bug*?

Bug

The documentation links are 404ing: https://doc.traefik.io/traefik/

I am unable to access any child pages as well: https://doc.traefik.io/traefik/getting-started/configuration-overview/

**Comment by isaacrlevin** [comment]
Traefik just stopped working for me all of a sudden so I go to the docs and they are also down. Weird day already :/

**Comment by zlodes** [comment]
Same.

**Comment by ldez** [comment]
Hello, the problem is fixed :tada:
