### ISSUE TITLE
Config option to enable TLS on all routers by default

### ISSUE THREAD

**Issue by mikesir87** [traefik/traefik#7768]
Feature Request

### The problem I'm facing

I have a Traefik config that redirects all insecure traffic to a secure entrypoint and also has a default certificate set. While using the Docker provider, I have to specify a label to enable TLS on the router (`traefik.http.routers.my-app.tls=true`). Without this enabled, requests to an app will be redirected to HTTPS, but I'll get a 404 because the router isn't configured to use TLS. Unless I look at the Traefik dashboard and see a router, but no TLS, it isn't clear why I'm getting a 404. I spent quite a bit of time thinking I didn't have the provider configured correctly or that I messed up the router rule.

### The Feature Request

It would be nice to provide configuration to indicate that _all_ routers should have TLS enabled by default. That way, I don't even need to specify the TLS label.

### Current Workaround

Simply specify the label on every container.

**Comment by ldez** [comment]
Hello,

this option already exists: https://doc.traefik.io/traefik/v2.3/routing/entrypoints/#tls

```
    command:
     # ...
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
     # ...

```
