### ISSUE TITLE
Documentation: Official let's encrypt example is out of date

### ISSUE THREAD

**Issue by martyglaubitz** [traefik/traefik#7770]
There's is an official example on how to quickly get a let's encrypt certificate for one's webservices: https://doc.traefik.io/traefik/v1.7/user-guide/docker-and-lets-encrypt/

However, this one is out of date (using traefik:v1.7) and seems to incorporate more steps than necassery (like fidling with file permissions of the acme.json). I've finally found a more simplistic example: https://greenitsolutions.at/traefik-docker-lets-encrypt-tutorial/#highlighter_306346 
Maybe the documentation could be updated with the approach as shown there?

**Comment by ldez** [comment]
Hello,

the link that you provided is for Traefik v1.7:
- https://doc.traefik.io/traefik/v1.7/
- https://doc.traefik.io/traefik/v1.7/user-guide/docker-and-lets-encrypt/

The latest version of Traefik v2.3 and the documentation is here:
- https://doc.traefik.io/traefik
- https://doc.traefik.io/traefik/v2.3/
- https://doc.traefik.io/traefik/v2.3/user-guides/docker-compose/acme-tls/

**Comment by martyglaubitz** [comment]
@ldez okay, than i think this page has just bad SEO properties, since i actually was searching for just that. Would it be possible togive this page a bit more meaningfull URL?
