### ISSUE TITLE
uses a non-existent resolver: default

### ISSUE THREAD

**Issue by Expried** [traefik/traefik#7772]
spec:
      containers:
        - args:
            - '--api'
            - '--configfile=/config/traefik.toml'
            - '--providers.kubernetescrd'
            - '--providers.kubernetesingress'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.Address=:443'
            - '-entrypoints.web.http.redirections.entryPoint.to=websecure'
            - '--entrypoints.websecure.http.tls.certResolver=default'
            - ' --insecureskipverify=true'
            - '--certificatesresolvers.default.acme.tlsChallenge=true'
            - '--certificatesResolvers.default.acme.email="email@gmail.com"'
            - '--providers.file.directory=/config/'
            - '--providers.file.watch=true'
            - '--certificatesResolvers.default.acme.storage="acme.json"'
          image: 'traefik:v2.3'
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: traefik
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /ssl
              name: tls
            - mountPath: /config
              name: config

 traefike.toml:
   
# Dynamic configuration

[[tls.certificates]]
  certFile = "/ssl/tls.cert"
  keyFile = "/ssl/tls.key"
  stores = ["default"]

[[tls.certificates]]
  # Note that since no store is defined,
  # the certificate below will be stored in the `default` store.
  certFile = "/ssl/tls.cert"
  keyFile = "/ssl/tls.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/ssl/tls.crt"
      keyFile  = "/ssl/tls.key"

报错提示：
   time="2021-01-17T07:21:48Z" level=info msg="Configuration loaded from flags."
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-app-kube-public-api-hanlan-net-cn-app@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-engine-kube-public-api-hanlan-net-cn-engine@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-parkinglot-kube-public-api-hanlan-net-cn-parkinglot@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-coupon-kube-public-api-hanlan-net-cn-coupon@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-ali-kube-public-api-hanlan-net-cn-ali@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-sms-kube-public-api-hanlan-net-cn-sms@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-auth-kube-public-api-hanlan-net-cn-auth@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-user-kube-public-api-hanlan-net-cn-user@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-web-nginx-default-api-hanlan-net-cn@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-wechat-kube-public-api-hanlan-net-cn-wechat@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-pay-kube-public-api-hanlan-net-cn-pay@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-bill-kube-public-api-hanlan-net-cn-bill@kubernetes uses a non-existent resolver: default"
time="2021-01-17T07:21:48Z" level=error msg="the router websecure-svc-reserve-kube-public-api-hanlan-net-cn-reserve@kubernetes uses a non-existent resolver: default"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
