### ISSUE TITLE
配置了自动生成https 证书浏览器提示根证书错误 

### ISSUE THREAD

**Issue by Expried** [traefik/traefik#7777]
{
  "tls": {
    "Account": {
      "Email": "1569812004@qq.com",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:1569812004@qq.com"
          ]
        },
        "uri": "https://acme-staging-v02.api.letsencrypt.org/acme/acct/17590097"
      },
      "PrivateKey": "MIIJKQIBAAKCAgEAtVET4MX5tV8Jz/tD2zOvfvXYu84Jux2g2vVCoyMFL8Xtr20yeT1rkagYQIDbxsMd8GifQnolvzd2qKw5wIpSsImK7EqjZYBp/uMKonEGsUeCXTjBa9R3eSdjARKDOIGaVrz17hrUkVok48ZencwS3OLZtlJUSARRGtarXKjBtkdPw94kfwUIqpJ1/iRtgPDDMxJOsJODGofoBZWmVDsHLhKCGyUI4W7uCvxUimtjhMFYHTmXhRBLtM6nzmIEzrZZ1rNxDOrdFa0b+Pq88zotmqu4x0Mt6Qj1z1FyqHRKoHuJHMZPG3LGOCiqWP8rHQwifUxPdfsQumEvnSXq/SDWRbVHQVCksJpPPvSSWB+BiKwMV7LMEke7vh/Ukt+zbb0UI1mrm0ljxXymMhEj+B0jaEDGfaybsudn2PQw8Upcz/h8GN8JPO7yNi5rMudb6pc/ALWe2s4+aVXf2iKIr5IpyaVsAE9cgMWUd0wkQ+QR9vgDnHAImeGcbHATbTidnxm1JGy3ASigIM08QCAPzaMWWH1QikIZi452RFBxtk9DHbs4tsfURL3HP33WNvrK3uBPdxaPGMcgOE8UBuODuLSNy/LwvY5ls7dhtjv1HMaIgtbhNyK4WAax+XFqEJ0yAat+wGkFMETvwfTZ6H5MvftbzkPU1aF0jgOFQQ3/qtxJOG0CAwEAAQKCAgA4cSm/8cD+3bvfO3dvGBLMcdlq9QOAdQOqxWheAjvOGE4aKuLobN88c1hBVBuWLwz11oulFQMFGE3eyeYccrK088wELGPa5/OW/bRExuxvaTRCsrU7TON4GnOuVMX2ZBnYYHAqE74SFT6gjRLNCkbg7dkZ8Vz9IiLhOOwVJw9OH7rL3S39QGLnPjpux4Yy+j+5eTx3qSPJsX7fpisl004z4F0R+CBglLiTQONMR4uuOsWkK1ZofJ8khKQmEcsvUgJ7XFaXz9DMu5uWkO8axASIPmaB2P7EqR5j0BXiLHlCpdIT3AOqJrtfpgEJPT19iFaALK4bqvEVI8W/pJsW+w7YE26BpCwsQ9WHwEJWjP+GBcypbPi45GQ+opS/orUAcbsrKbTv5VZ62bi4OZRnblKH3X/0elw7uHUoQe4h35B7d5AMfZIHLo6kW7ItBfjoQDjn1L8X9iFiN4sYD5/v8zk50O2wIgq8IykKfi5pQsEWg4OkUkB1fpW8fwjvZkLcAZCV4B8XVxol2oxX1DNrTJyiYK6Wb87lgLEjqgkBHY79F7tcbrjYcfuPWTFTXhUs6hfImLJAjc6lpc3fYUJTOP0XPpr6f+2oynZ7iX3tZEBOnULNkiymJV5zPWg2P8e9mrMuhTlah6zvaA4xjmhO4RycKfTb7k5+ks5SmOvJbo9FnQKCAQEAwiQr/z71XbF4k1Wxys/If9TgSiScIg4cNAX76tLN20gvBNzXH5vBtvDwcmHQHTKeA1j8g5TB1Gj1fsLZwpvqhTLDEbBg1cO+LKU+1pf0W6NJGXlE0lXbiidAQ54o1bxivU5WlsgXsff+Bl2cBE2v5AonmPWskXM4Z2FuvSQYStKVTL279TeT4RMPnJXqTq2j3VNu1fX/NJSTpJupD8EJB9B2yAJEdHfkPlNneTiTFctWXJzt1OQmZZohVo01+x90SlXOJmxySMF61iW12zzR96EtKKuQfrIdhDg4Cn1HRahfj2OaB/Grzc9AIphMdsZr1gppMnQDrdl4jg+7sWjsHwKCAQEA7xbSk7fRS/pmX+fZmXI0jhxYtRwWjVBVtEzzCyfI3lNdlr+QBWlMCTlNydEQSWZA1aRkO3Oo+ZYwLbYFlwIFqVnfkDRsG+tV++TWqaf2q6A75kvZgRFYKjGyuFraN/OehPCDVr3RZI8J6kyhKJsXJeqtK9dWexLXSqTwMyR4XA9GrJEDKy7ds002FAfXgjySrXQdXMm5Db4MVcu/ZAXOS5N28p2sE4Ca0kf9OjbkvX6islsoOPR2i2gjbNe8ZJMk2puZU0RMb4A4llEEFe0nJW2atdi5gHzvFvmolovAtEFM7kMpyDLdNT0oROTATddcTFLmxBMwVW8U3cT2zhwJ8wKCAQEAhlOCwaOtH7uogsC7OGmV/6Sp34L/KKz8pJ4zVKGw33VNWx72FZ+uY8bHh0zYMyuPmx9Z8CzgA/jvS1rEUtuQY8Lgp3+TMLS0A63+EXqoDzOmY2K91I6lTSylUWPAO0qSQwtN7BvcET5WW88vIOcjuTOxfCsX0LeZIiaO+X1c9YBI3wU0ZJGk1wlaNuyfZvrLs1qECLShdJ8MnMs7KXRVrDt3xCGVfcRqfxk0MfKMCntbcM7/29pUGt6PDJS98dgsnTZLYdiNJnwAYuVKs7ucR6sUVNyIKLFSrOY9GDzgMHk0TUEMFU0Io2kvpgAcf94AROOFL+yHkyUyPZDzO+gt3wKCAQEAxTZEGAiloVA4JZ+uw32KkDYdjbZPe9zp9MEMMQVuEMUfC3uTpoMGbw1Pdsr17jVkAVWKP+fVV5pkvy/HSJooZVp2qBI1oonp8M7/qg2b0FFpVzr1fBr8aEF6M8rs+P4AoZNqIqCMGbBK83Kl9EKJQ4NhuCn1catG3pFSeDz68qS/HRS4UmRkBsQHeVpGj2y7aEvA9IqIFCfRMOvRQQXw9jH7CYC5MZUBH7a1z9D7uLq+JPRAJ0quhasunVcOVL9yxMdYH3DUw5w2EPdesV9ezOatmJXd3XgwFvlz8EnyeDzs4hOQYUxjXsjFcJ5naU3dGi+/nbheQ/pOcedH1RcXtQKCAQA3u16cYT7aW39hGdOrW3787E2orwD2Oc8rMHWeCZoJrIXhcCeblzPY02vVqOzH+n/K52+4sYQJlYI0CrF7BvIEcyO1eCqS3WlyLo3pwXHxsC+j06F0ZpKOpCUql/5wUcOuPkaMHEElMQQxvGqGfIHvHutOpEoyLhBj1P2b0kNuNsbxeMzWmiNBwapjZABu3DnLTX0ANzd9+R3JSJ7kx1PwfUC7Ts3RS+oYxSLUvkcYk4Mks/KL43BDsEQYG9Wz47ju4KD1iv3eTkb7oFkyCWD20kEAB16bTawfVY5sA7ngFay1e2rvQVB2A38r7jVqsIc/sXDZzQp+XXH+j9TzqxQS",
      "KeyType": "4096"
    },
    "Certificates": [
      {
        "domain": {
          "main": "api.hanlan.net.cn"
        },
        "certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdQRENDQlNTZ0F3SUJBZ0lUQVBxcW9HeldJUkNUUFd5MFhBd3dkckJnbVRBTkJna3Foa2lHOXcwQkFRc0YKQURBaU1TQXdIZ1lEVlFRRERCZEdZV3RsSUV4RklFbHVkR1Z5YldWa2FXRjBaU0JZTVRBZUZ3MHlNVEF4TVRrdwpOak14TWpGYUZ3MHlNVEEwTVRrd05qTXhNakZhTUJ3eEdqQVlCZ05WQkFNVEVXRndhUzVvWVc1c1lXNHVibVYwCkxtTnVNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXlIQkZjcmRKSDliVkI4U2YKZm8rZ0FqTkFpM1FaV0FObGJpSU5Mak5aRm11aEg0cEhqRm5wMGZTZFhVcXRyUERhWldOaGszUG9iaUpENElQNQpsMTNzY3BYVVhTaytwMzE2Q2ptMFFPcFdvR3FHblAxRGhKMVRQVU5EeWRjNVZlQ3MrcC9MOFNjTHFsT09VbzFlCjVjTUIwck44VWRVTHo5UTBUM3FLTVJFM05tRVAzU2xpaVFYSnlIZVdGSEJUQ3llRVZ4cFpIOXZrUGJ6ZUh6R3oKaHVlYm9NT1huSEgxUThGUEoycElFVDg3RHQxR3RhMHhEbmFWZ1NBY1pvaGVWeGlSbkRqZVpPa2RvS1V5UHFGWQpjbDFzSnl5eEJvSTBnRGJjQm5ERkE1eHVVMmFaZjdRQkpPeHY4czdwRzFteTI1S05tNWVGSDZwZFp5WnpSMHB4CklpbEcvRHhya29WUHhnL0gxRDUzTjJFdHB1RS96OC8rZWwvbzBieG5JdXZIT2FmY2ZjMk0rUDNhZ2JMTitTRWgKdlY3b1RsQm5VVHkyZTAwSlZRdFluRVRuZ0RiMkR0dEsvWmhLSkljUHdadXJuRmRwc0FFRDVPU0dvbTRCNlRpYQpzNFA0QmRGZm9UUEpBMnZVaUk4WkN0T2phTUxGQ2d4N0daZFpHdEtwNXErUVhQclZmL00rTUV4eExaU0sxUTI5Ckw3eEx3YkN2REM5K2tNSlh1ZVg0dVZSRW8vcFB3eE9LbWp6dEpJcmhCY0VUMS9ad25qVXpRazlHd29ZWE9talUKSzU3QS8yVGFpcU8yNmUzbi9NL0ZQaWRqVjNMOXRWOGozcC8wYkUwS3hCV3o4OFNEeHIrZzlLdjFBRTZnR0NJSwpMYVV0UnVKMHNiMHBxb0QrYnptaE5GS3VCYzhDQXdFQUFhT0NBbTh3Z2dKck1BNEdBMVVkRHdFQi93UUVBd0lGCm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWQKQmdOVkhRNEVGZ1FVRjdUYTdpK2hVRTAyVm9iQVRMTVNPNkJBWUZNd0h3WURWUjBqQkJnd0ZvQVV3TXdEUnJsWQpJTXhjY25EejRTN0xJS2IxYURvd2R3WUlLd1lCQlFVSEFRRUVhekJwTURJR0NDc0dBUVVGQnpBQmhpWm9kSFJ3Ck9pOHZiMk56Y0M1emRHY3RhVzUwTFhneExteGxkSE5sYm1OeWVYQjBMbTl5WnpBekJnZ3JCZ0VGQlFjd0FvWW4KYUhSMGNEb3ZMMk5sY25RdWMzUm5MV2x1ZEMxNE1TNXNaWFJ6Wlc1amNubHdkQzV2Y21jdk1Cd0dBMVVkRVFRVgpNQk9DRVdGd2FTNW9ZVzVzWVc0dWJtVjBMbU51TUV3R0ExVWRJQVJGTUVNd0NBWUdaNEVNQVFJQk1EY0dDeXNHCkFRUUJndDhUQVFFQk1DZ3dKZ1lJS3dZQkJRVUhBZ0VXR21oMGRIQTZMeTlqY0hNdWJHVjBjMlZ1WTNKNWNIUXUKYjNKbk1JSUJCUVlLS3dZQkJBSFdlUUlFQWdTQjlnU0I4d0R4QUhjQXNNeUQ1YVg1Zld1dmZBbk1LRWtFaHlySAo2SXNUTEdOUXQ4YjlKdUZzYkhjQUFBRjNHWTRqWWdBQUJBTUFTREJHQWlFQWk3MkR6eHZqM2JsNURlTk5ZQTNICkZVeUJXdnQ2QnFNUllqYzFadVcvbzBrQ0lRRGZSbzF2T2tsL05vVEtQSzdZeGpMbHh5WmEwb1VKSmgzQklLYkQKQUhCdm9nQjJBTjJaTlB5bDV5U0F5VlpvZllFMG1RaEpza24zdFduWXg3eXJQMXpCODI1a0FBQUJkeG1PSlVzQQpBQVFEQUVjd1JRSWdVTVNQVlN3MGhwS3JsQXJ0SkFzZU5nQ0xGTmh4ZmdUQ21LNDE1M0lMc29rQ0lRRFpCeHVYClFhaTd5WGlZSlprc2ZXS2wxeHFOcmxYYVJXUGtsRllLVjNra2dqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKQTRTakVNbFBCdUN5TDJwUzlKaVFMNVJ3NWFMaldGdzNMSXZhb3dzTnZYb2w1bWczSGRaSGpiUVJGS3RRcnJKTApRWlYxSzdhRW4va20wSjdMTkFwUWRiWXJzYUlnRUtLeEtoeEc0TjVJZzBDWTV4LzIyZlgwY2JsMzZQMk9lZnluCkZLRkdKMWZocG5PdUxtcG5VeWZKOEdsRkFzNFhqMDFaS2E3THY2TktJR2YyRFhyaUVTZC83OGs3cUlQaHlaOVYKdlJFOEFscTB5a0JHN1E0UU5QdFB2dVVnMDkxOXZ3OTRETkVYT3FzcG03V0srTzY3NHJWY3BYa0VGN0VEVVVBVQpkekRGRS9mRFVHWkJZZkN0ZDVabWJjMUUvbkppQnVzTlRKZTdnaVNTQmpHOXBIUWNrc0dzRXBKNkJpQlh3M2pjCmgvV1ZwSlExbk92eTF4aXE2VGxuNHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRXF6Q0NBcE9nQXdJQkFnSVJBSXZoS2c1WlJPMDhWR1F4OEpkaFQrVXdEUVlKS29aSWh2Y05BUUVMQlFBdwpHakVZTUJZR0ExVUVBd3dQUm1GclpTQk1SU0JTYjI5MElGZ3hNQjRYRFRFMk1EVXlNekl5TURjMU9Wb1hEVE0yCk1EVXlNekl5TURjMU9Wb3dJakVnTUI0R0ExVUVBd3dYUm1GclpTQk1SU0JKYm5SbGNtMWxaR2xoZEdVZ1dERXcKZ2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHRXS3lTRG43cldaYzVnZ2p6M1pCMAo4ak80eHRpM3V6SU5mRDVzUTdMajdoemV0VVQrd1FvYitpWFNaa2hudngrSXZkYlhGNS95dDhhV1BwVUtuUHltCm9MeHNZaUk1Z1FCTHhORHpJZWMwT0lhZmxXcUFyMjltN0o4K05OdEFwRU44blpGbmYzYmhlaFpXN0F4bVMxbTAKWm5Tc2RIdzBGdytiZ2l4UGcyTVE5azlvZWZGZXFhKzdLcWRsejViYnJVWVYydm9seGhERnRuSTRNaDhCaVdDTgp4REgxSGl6cStHS0NjSHNpbkRaV3VyQ3FkZXIvYWZKQm5RcytTQlNMNk1WQXBIdCtkMzV6akJEOTJmTzJKZTU2CmRoTWZ6Q2dPS1hlSjM0MFdoVzNUakQxenFMWlhlYUN5VU5SbmZPbVdaVjhuRWh0SE9GYlVDVTdyL0trak1aTzkKQWdNQkFBR2pnZU13Z2VBd0RnWURWUjBQQVFIL0JBUURBZ0dHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFBdwpIUVlEVlIwT0JCWUVGTURNQTBhNVdDRE1YSEp3OCtFdXl5Q205V2c2TUhvR0NDc0dBUVVGQndFQkJHNHdiREEwCkJnZ3JCZ0VGQlFjd0FZWW9hSFIwY0RvdkwyOWpjM0F1YzNSbkxYSnZiM1F0ZURFdWJHVjBjMlZ1WTNKNWNIUXUKYjNKbkx6QTBCZ2dyQmdFRkJRY3dBb1lvYUhSMGNEb3ZMMk5sY25RdWMzUm5MWEp2YjNRdGVERXViR1YwYzJWdQpZM0o1Y0hRdWIzSm5MekFmQmdOVkhTTUVHREFXZ0JUQkpuU2tpa1NnNXZvZ0tOaGNJNXBGaUJoNTREQU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBZ0VBQllTdTRJbCtmSTBNWVU0Mk9UbUVqKzFIcVE1RHZ5QWV5Q0E2c0d1WmR3akYKVUdlVk92M05uTHlmb2Z1VU9qRWJZNWlyRkNEdG52KzBja3VrVVpOOWx6NFEyWWpXR1VwVzRUVHUzaWVUc2FDOQpBRnZDU2dOSEp5V1NWdFd2QjVYRHhzcWF3bDFLekh6endyMTMyYkYycnRHdGF6U3FWcUs5RTA3c0dITUNmK3pwCkRRVkRWVkd0cVpQSHdYM0txVXRlZkU2MjFiOFJJNlZDbDRvRDMwT2xmOHBqdXpHNEpLQkZSRmNsekxSam8vaDcKSWtrZmpaOHdEYTdmYU9qVlh4Nm4rZVVRMjljSU1DenI4L3JOV0hTOXBZR0dRS0ppWTJ4bVZDOWgxMkg5OVh5Zgp6V0U5dmI1ektQM01WRzZuZVgxaFNkbzdQRUFiOWZxUmhIa3FWc3FVdkpsSVJtdlh2VktUd05DUDNlQ2pSQ0NJClBUQXZqVis0bmk3ODZpWHd3RllOejhsM1BtUExDeVFYV0dvaG5KOGlCbSs1bms3TzJ5bmFQVlcwVTJXK3B0MncKU1Z1dmRETTV6R3YyZjlsdE5XVWlZWkhKMW1tTzk3alNZLzZZZmRPVUg2NmlSdFF0RGtIQlJka05Cc01iRCtFbQoyVGdCbGR0SE5TSkJmQjNwbTlGYmxnT2NKMEZTV2NVRFdKN3ZPMCtOVFhsZ3JSb2ZSVDZwVnl3enhWbzZkTkQwCld6WWxUV2VVVnNPNDB4SnFoZ1VRUkVSOVlMT0x4SjBPNkM4aTB4RnhBTUtPdFNkb2RNQjNSSXd0N1JGUTB1eXQKbjVaNU1xa1lobE1JM0oxdFBSVHAxbkV0OWZ5R3NwQk9PMDVnaTE0OFFhc3ArM04rc3ZxS29tb1FnbE5vQXhVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
        "key": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBeUhCRmNyZEpIOWJWQjhTZmZvK2dBak5BaTNRWldBTmxiaUlOTGpOWkZtdWhINHBICmpGbnAwZlNkWFVxdHJQRGFaV05oazNQb2JpSkQ0SVA1bDEzc2NwWFVYU2srcDMxNkNqbTBRT3BXb0dxR25QMUQKaEoxVFBVTkR5ZGM1VmVDcytwL0w4U2NMcWxPT1VvMWU1Y01CMHJOOFVkVUx6OVEwVDNxS01SRTNObUVQM1NsaQppUVhKeUhlV0ZIQlRDeWVFVnhwWkg5dmtQYnplSHpHemh1ZWJvTU9YbkhIMVE4RlBKMnBJRVQ4N0R0MUd0YTB4CkRuYVZnU0FjWm9oZVZ4aVJuRGplWk9rZG9LVXlQcUZZY2wxc0p5eXhCb0kwZ0RiY0JuREZBNXh1VTJhWmY3UUIKSk94djhzN3BHMW15MjVLTm01ZUZINnBkWnlaelIwcHhJaWxHL0R4cmtvVlB4Zy9IMUQ1M04yRXRwdUUvejgvKwplbC9vMGJ4bkl1dkhPYWZjZmMyTStQM2FnYkxOK1NFaHZWN29UbEJuVVR5MmUwMEpWUXRZbkVUbmdEYjJEdHRLCi9aaEtKSWNQd1p1cm5GZHBzQUVENU9TR29tNEI2VGlhczRQNEJkRmZvVFBKQTJ2VWlJOFpDdE9qYU1MRkNneDcKR1pkWkd0S3A1cStRWFByVmYvTStNRXh4TFpTSzFRMjlMN3hMd2JDdkRDOStrTUpYdWVYNHVWUkVvL3BQd3hPSwptanp0SklyaEJjRVQxL1p3bmpVelFrOUd3b1lYT21qVUs1N0EvMlRhaXFPMjZlM24vTS9GUGlkalYzTDl0VjhqCjNwLzBiRTBLeEJXejg4U0R4citnOUt2MUFFNmdHQ0lLTGFVdFJ1SjBzYjBwcW9EK2J6bWhORkt1QmM4Q0F3RUEKQVFLQ0FnRUFqL1M2bkRweFJYSEpUS3YyRlRMWUs5eGRoZ3JiVFBBYmdDN3FvbnowaGZyRkhONzJwaUhKb2laNgpndzlvanlYbzVScXNjUGUxUHF4VGJjTzdsZkE2S3MzYldSR1BVMEgyVGJQRjl6MlcrOTJtVXNnL0h0YlRldE45CnMxQmxlSDFHSHpaM2hmcVNFVUd6blN5MXRIVUxNU1lCcXRCRmpIMlBHR29kS0VLQ0VnZENHb2hub1p2TG9iUHAKMFVJZkVvck9MTFRhdjl2eElEb3VtZDdiWG8rbm9aMzRuTDduOVVLNE04bk1lcjZjRHYvemtmWVNucDJpb0x2TQpTZ08xSmY2YVRjWTJTK2wxZ3ZSQ2t1TFVvRWJpcjN3VXBHVU5pZXhjdUM5MEFEVHdzK3VqWVNtS0ROZlhTMTg1CjRvL1l1b1NXT2VKb0ZTY0pzRlRZUktKOWdKaCt4dEpVY3JTVXZTWEVwNWFybnhLSjE0dlRrZXZZdDNKcG13cXkKUGttUXNNK011OFFZSEhycFVHZjBpV3VvbW11aCtEU1BCWEVXZnZkMytDdnhGelJCT2pTSTg4NHBRQW5sVDg2eQpLaGVRTWc2amhVdzJJRS83WmV0c1ZSYnVhbHQwckNIZGlnUXhHOU9FM3h1d0p3L0cyS3orOWpRZmxEeGR5NlBkCkZmOHlzc1IwcDZrdHdQclNmYmtHRWRJOWpEN3o3TE12Z202b0Y0SDN1R3ZoaHpRRzNrZTlvaDVPVFZJNkEwMmYKaW9oM2JZeURzV0lTTTF6YTEvMWJWUjJhbG05MFhCVUNsVnIyQlc3VnczZC81WU8rODJqaGNJelFsQVc3Mkt0cApsUDRJMk81NmdBQ0VURktjV1lVQisrdDJMZzFVak5lYlJTSG14VDdDSVBYbXdtN1RGK2tDZ2dFQkFOYm1JL3Z0CmMxRkhNa2o2cDA4dlp2bkRBVzlTd2pxcWNtR2FXMjhWZ1BNSEdaTXV1TjBqd3lrd3dEVXc4NE9HT2dybEdlZEYKUVY0QTBzSVYzb1hrdlhmemFqUDVVVC9yTlN3Mlp0Lyt2cTYxQWdnSE9NeXpuRkEvTi9qRTZUU0N2K0pUa2pJNwpMSDQ0b01BUW1WL0tWY1ZBYk95eTN4THU3QzZzSXJjZjdINnlVUnRDRnozWTZNa2dyd1BHV0l5QTBXVnV3VE8xCklXb0daK05BWi9qYTdKbTgvSENXeVlTeHZCU3Q5azVJanU2VXJ2M2pZVDZWbkx4VkFrMTRzblZmOVBLVmZlVmoKVE5rQXlCcDBIMW1DUHNUalE0cUtNeHhPdnBzSERtOHNWUXRaMkJraEFRbSsrK29WMkx3dE9mdGptN3IrQ01vMwo2eWU0bUkvMlNBUENYY01DZ2dFQkFPN0dIdmRzNWRRMXU1QXFZNVJ3T2FQNWlxRWVEQmZRblZLd1o2MkV4MGxjCkJGcDFPSkZVek50RWZHT2g5Uy9SbVFPV3dNNE1iYVFNYStEeXRVYW9mQkNCT3Q0clZYaFduWDFhWkVUVEUxNUkKZ0hDeTJvby9jK3Z3aEdJUWQ5cGpJdzZmQ3lFdzVwMmgrNUlEYmhDRTZyTktlaUsvV3h6SEh1czIwekV6VUFrNgpwcCt5TklVYXJZbkF1dVhaTWtNejlYTUk5ZHdQTVVGTE8zRVJqVmdqYmNFR29tK2hIcm5RSFEzdFd3UHdzQis1CkxsQXFEaUx0WDErUVdueHJrUW13S3RhR2Y2UWV6T3dkeUdpeXZIdXNvMXJObDN0b2hwRU4rZ1JZbGUyTkFTK2QKRkpTbDRLTGw2SE9ZN3RCWmFwKzAwM2luVnI3bE13VE01d0dhcGZiOCt3VUNnZ0VBYmV1VjZGelNxWFpUWUVUbApvM2xKb09PQUxtTVVlbEdJNUNmQ01SVzh1WktlSUV5N3ZsRjJsL0VadjV0a1U1Z3F4RHZmZmc1TW16cXNreDRBCmpsZ3NHZGptTCtPTkRiYlBvZWZKd3pWWWI2Q2lnMXkrVHVab1JCdXlFNHNWQmdrREFVOWg3bE9hTkkzZW01OWgKOUQ5WWsrYWFVSkJGempkcms0djB6ZHFFYTJIbVhwejFxbXJ5MXozaWgzbkMvVXMrMERWUW1aUkNuU3JkcEwzaQo4TVY2VkVENGx0WnFDWGVvRHFQVTRzSDJhazZmRzdwY21WaUpyVU9HUS81Q3VncjFEY2d0ZDFITmt3bjFVS0twCkRtMnlrWjcxZ3oyaFd3OWtLNFAyZkNNZTlRbGxvYVRpRlF3ZGF1VDEwWHNJdDIrQnpxbjE4UW1kUE5vTkgwWUkKRy9RbFpRS0NBUUFVcjltUytqNVhTbWg3cnhCOWxkT0luMkFoWVdjTzBTWXdPZFJodGpWRjU5RUF2Vk12VkRlRApiOFdQSkVNSDU1TG9PckZ0cUtuL0lveGVLdWtGdkNjemp0NjR6T3hVeHJ4U1ZmaUY5ZnVobVlwM09TZXgvcGxlCmdiSVdoUEs5V3dWNGlOTUFCeXFUMGFyb0ZaLzlrbVo3TGlLeXkvMXEydDJVNTJVWXlDZFJCV0hXU0N4QXMvVUIKRUUraEJsWlNlRGYxeFhyM20rRmFsTmdMamNlL01TS2JMS1g2SWUxMWo5QlVtcEhlSDRaQzJWcG4yNXpwN2NMcgpscWdnUzNsL2EySHF3REJpMmNCTFhMRTJVUFgvaVErR0dIWGRYVXI3V2tpbEE3L0ptd1BWU2ppMFFFTGNHaXN2CmlMcDRGcWNrT3hodlJhQkFYYjh6MVVUV1lMMnNUbks1QW9JQkFGVGFaSUFPbnhDYy9mMUJTQ3ZqYmpObDlMbjIKdmN5bUMxSmJLNGkzOUw3ZHhSMUpvZStpWWhVU0lXeStkZkIrZ21nUDlnZU5pb01mc0FuQmRwb29wYW1ZSXo3WgpFT3ZWUTR4SmlTYnFBcWtoZmF5WnhGalFVT3l2N3lPRENjQ0lsN1BYMTBubVR5OWx0RkVFaEd0T2VQdVpINGJiCkRmU2x3S1NGelRJVHhkWTk4MW9zcmZzMUVaaEVPaE0vS1gyRFYvT0RsQWRLMmFUcHVmNnZiMnNPbnltOGtiaEEKZ2NaUkhUOTFxMm4zS2hWNjhTZDJNZ1hON3psc1UzRlN4U0dEY2RlV2RSdDlGdkIwOExBZ3l6RG5rVnJ0dUhKWgo5VUl6OVdxc2xSV1hDUGN2VndLRmt2bnZtaWVkUndhcHN3QkY5U0dRWlMzU3g3WUpVYWM4cm94VlFDND0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K",
        "Store": "default"
      }
    ]
  }
}

traefik 配置 

            - '--api'
            - '--providers.kubernetescrd'
            - '--providers.kubernetesingress'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.Address=:443'
            - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
            - '--configFile=/config/traefik.toml'
            - '--entrypoints.websecure.http.tls.certResolver=tls'
            - '--certificatesresolvers.tls.acme.tlsChallenge=true'
            - '--certificatesResolvers.tls.acme.email=1569812004@qq.com'
            - '--certificatesResolvers.tls.acme.storage=/home/acme/acme.json'
            - '--certificatesResolvers.tls.acme.dnsChallenge.provider=tls'
            - ‘--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory’
由于CA 根证书不在“受信任的根证书颁发机构”存储区中，所以它不受信任。
![微信截图_20210119160702](https://user-images.githubusercontent.com/10000663/105005528-6870ec00-5a70-11eb-86a0-efeafb99f49c.png)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by Expried** [comment]
社区论坛打不开

**Comment by Expried** [comment]
麻煩解答一下問題

**Comment by ldez** [comment]
Hello,

1. you have to follow the issue template
2. we don't understand Chinese
3. you are using Let's Encrypt Staging (https://acme-staging-v02.api.letsencrypt.org/directory), the staging certificates don't create valid certificates, it's expected.
