### ISSUE TITLE
Custom middleware misses type in dashboard

### ISSUE THREAD

**Issue by dkijkuit** [traefik/traefik#7778]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Added a custom plugin using custom middleware and opened the Traefik dashboard to view the custom middleware.

### What did you expect to see?
A custom middleware type defined by the plugin developer or at least something like 'Custom'

### What did you see instead?
Empty middleware type

![image](https://user-images.githubusercontent.com/16475465/105028310-2a180480-5a51-11eb-9341-150148f5694a.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64
```

**Comment by traefiker** [comment]
Closed by #7782.
