### ISSUE TITLE
Simple docker run command

### ISSUE THREAD

**Issue by Hamsterman** [traefik/traefik#7785]
For some reason it is not possible to run Traefik docker out of the box without doing some magic.

I would expect something like this would work but it does not.

docker run -d --name Traefik -p 8080:8080 -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock traefik:latest

So far I have not been able to get the container running and working

99% of images simple just work when you run it - but not Traefik it seems.

I hope someone could guide me to a docker run that works - I could not find anything in the documentation.

**Comment by ldez** [comment]
Traefik needs to know which provider to use.

```
docker run -d --name Traefik -p 8080:8080 -p 80:80--api.insecure=true --providers.docker traefik:latest
```

https://doc.traefik.io/traefik/v2.4/getting-started/quick-start/

**Comment by Hamsterman** [comment]
unknown flag: --api.insecure

**Comment by ldez** [comment]
```
docker run -d --name Traefik -p 8080:8080 -p 80:80 traefik:latest --api.insecure=true --providers.docker
```

**Comment by ldez** [comment]
```
docker run -d --rm --name traefik  -p 80:80 -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock:ro traefik:v2.4 --api.insecure --providers.docker=true 
```

**Comment by Hamsterman** [comment]
Thank you! that final one made it work. It works with :latest aswell!

Thanks alot for your time.
