### ISSUE TITLE
Can Traefik update my DNS records (OVH)?

### ISSUE THREAD

**Issue by zedtux** [traefik/traefik#7786]
I've read, in the past, the Traefik documentation about the OVH provider but today this page is gone and all the things I'm reading when searching "Traefik OVH" is couple with Let's Encrypt, which I don't care.

What I need is Traefik to tell OVH the a node of my cluster is down so that the trafic stop going to that node. So kind of telling the provider is OVH in my `IngressRoute` to be used with the given credentials from the Traefik deployment manifest for Kubernetes.

So is Traefik capable of covering that use case or should I really have to go with some Amazon Route 53 or others?

Thank you.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by zedtux** [comment]
What a boring ending ...
