### ISSUE TITLE
Add a link to the Traefik Pilot documentation when the Traefik proxy cannot contact Traefik Pilot

### ISSUE THREAD

**Issue by Trois-Six** [traefik/traefik#7796]
### What did you expect to see?

When Traefik has a Traefik Pilot token but it can not contact Traefik Pilot at startup, we should log an error with a link to the network flows documentation to be opened to make Traefik Pilot work: https://doc.traefik.io/traefik-pilot/ips/.

**Comment by rtribotte** [comment]
Starting on 2.7 the pilot token will not be a requirement anymore for plugins.
Since 2.8, a [new plugin catalog](https://plugins.traefik.io/) is available, decoupled from Pilot.

I'm closing this issue accordingly.
