### ISSUE TITLE
ServersTransport on TCP configurations

### ISSUE THREAD

**Issue by apollo13** [traefik/traefik#7803]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

While working on #7407 I noticed that the dynamic configuration supports `ServersTransport` only on `HTTPConfiguration` and not on `TCPConfiguration`. I fully understand that it makes no sense to add this for UDP, but for TCP it should be pretty much the same as for HTTP.

Is there any reason this was not added initially? Would it also make sense to move the servers transport definition out of http and into the global scope? (ie next to http/tcp/tls etc)

**Comment by tomMoulard** [comment]
Hello @stffabi,

Thanks for your interest in Traefik!

As we label it as `P2`, as mentioned in [contributor guide](https://github.com/traefik/contributors-guide/blob/master/issue_triage.md#define-priority), it is something that we found interesting, but we don't have time right now to work on it. 

This being said, all contributions are welcome, and if you want to so, feel free to open a PR following the Pull Request [Guidelines](https://github.com/traefik/contributors-guide/blob/master/pr_guidelines.md).

**Comment by bradydean** [comment]
This feature is necessary to use TCP services in a Consul Connect mesh. At the moment traefik will find TCP services (their sidecars) from the catalog, but the TCP request made to the sidecar is not utilizing the Connect cert for TLS.

**Comment by tomMoulard** [comment]
Fixed in #9465
