### ISSUE TITLE
How to bypass certain routes while '/' is integrated with traefik-fa, a middleware for SSO integration

### ISSUE THREAD

**Issue by RamuRChenchaiah** [traefik/traefik#7819]
Traefik version: 2.1

Hi,

We want to have a landing page for the application,like '/login'.The app is integrated with traefik-fa. 
But we see that this route also required to gothrough authentication.

Is there anyway to avoid this?

Thank you

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
