### ISSUE TITLE
Traefik v2.4 on Kubernetes generates new certificate on each config reload

### ISSUE THREAD

**Issue by rkojedzinszky** [traefik/traefik#7831]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Changed some ingress configuration.

### What did you expect to see?

Expected traefik to reload its configuration with its default certificate loaded, without generating a new one internally.

### What did you see instead?

I am observing the log message whenever a configuration change happens:
```
time="2021-01-30T20:17:53Z" level=debug msg="No default certificate, generating one"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.0
Codename:     livarot
Go version:   go1.15.6
Built:        2021-01-19T17:26:51Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

In Kubernetes, command line arguments:
```
        - --providers.kubernetesingress
        - --providers.kubernetescrd
        - --entrypoints.http.address=:8080
        - --entrypoints.https.address=:8443
        - --entrypoints.https.http.tls=true
        - --entrypoints.traefik.address=:8000
        - --ping
        - --serverstransport.forwardingtimeouts.dialtimeout=1
        - --api
        - --api.debug
        - --api.insecure
        - --log.level=DEBUG
```

Also, my traefik installation has a default store defined:

```
$ kubectl -n ingress-traefik get tlsstores.traefik.containo.us -o wide
NAME      AGE
default   13h
```

It seems that https://github.com/traefik/traefik/blob/2461e36ed466b4be236df9d43bafefcd667e29b5/pkg/tls/tlsmanager.go#L97 is requesting a store which is not the default, and I even dont know how to define one for it in K8S.

So, in an environment, where configuration change happens frequently, traefik consumes much cpu on generating certificates. This was not the case with traefik v1.7 with the following command line arguments:

```
        - --api
        - --kubernetes
        - --checknewversion=false
        - --entrypoints=Name:http Address::8000
        - --entrypoints=Name:https Address::8443 TLS:/certs/server.crt,/certs/server.key TLS.MinVersion:VersionTLS12
        - --forwardingtimeouts.dialtimeout=5s
```

**Comment by rkojedzinszky** [comment]
It seems that v2.3 behaves correctly with similar setup.

**Comment by mpl** [comment]
FYI, this is not limited to Kubernetes. The regeneration of the stores (and therefore of the default certificate for each of the stores), indeed also happens with other providers on configuration reloads (at least the file provider too).

**Comment by rkojedzinszky** [comment]
Ping
