### ISSUE TITLE
 TLS 1.0 and 1.1 are not disabled when "minVersion=VersionTLS12"

### ISSUE THREAD

**Issue by TheBlusky** [traefik/traefik#7857]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Using Traefik v2.4.2, I want my server to have TLS enabled with version 1.2 and 1.3, and TLS 1.0 and 1.1 disabled.

I used the following configuration:

```
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_AES_256_GCM_SHA384",
      "TLS_CHACHA20_POLY1305_SHA256",
      "TLS_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
    ]
    curvePreferences = [
      "CurveP521",
      "CurveP384",
    ]
    sniStrict = true
```

### What did you expect to see?

I expect TLS 1.0 and TLS 1.1 to be disabled

### What did you see instead?

Testing with https://www.ssllabs.com/ssltest/, I have the following result :

![vivaldi_AMTyX3TO7d](https://user-images.githubusercontent.com/441709/106760627-4fe9ff80-6634-11eb-9333-2ba9926184e4.png)

(Note: If I removed TLS 1.0/1.1 compatible CypherSuites, TLS 1.0/1.1 is disabled. But I Need those suits for TLS 1.2, so removing those suits are not an acceptable workaround, and as you can see on the screenshot, those suits ARE availables for TLS 1.2)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.2
Codename:     livarot
Go version:   go1.15.7
Built:        2021-02-02T17:20:41Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

N/A

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

N/A

**Comment by jbdoumenjou** [comment]
Hello @TheBlusky,

I applied your TLS configuration and tried to reach the router with 

`curl -v --tls-max 1.0  https://whoami`

And obtain:

```
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS alert, protocol version (582):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
```

As your TLS configuration seems good, you may have to check the other part of your configuration keeping in mind the way ssllabs reach your services.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). :smiley: 

So, I close this issue as a question.
