### ISSUE TITLE
Unable to obtain a certificate

### ISSUE THREAD

**Issue by 5ym** [traefik/traefik#7866]
### Do you want to request a *feature* or report a *bug*?

Bug

If you use godaddy for dnsChallenge and try to get a certificate for a domain like *.dev.example.test, the record created will look like _acme-challenge.dev.example.test, but lego will not However, since lego only refers to the TXT record of example.test, the certificate cannot be obtained.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
