### ISSUE TITLE
Dashboard UI: next/prev button does not work.

### ISSUE THREAD

**Issue by kongeni** [traefik/traefik#7877]
Bug

I have traefik 2.0.7 in a docker image and have defined a number of  HTTP routers, but the UI only lists 10, and the next/prev page buttons are disabled?

I can find the missing HTTP routers by searching for them. And all HTTP routers are from provider Docker and work as expected.

`
<button tabindex="-1" type="button" disabled="disabled" class="q-btn inline q-btn-item non-selectable q-btn--flat q-btn--round text-primary **disabled** q-btn--dense"><div tabindex="-1" class="q-focus-helper"></div><div class="q-btn__content text-center col items-center q-anchor--skip justify-center row"><i aria-hidden="true" class="material-icons q-icon">chevron_left</i></div></button>`

### What did you expect to see?
Next page of HTTP routers when I clcik the "next page" button 

### What did you see instead?
No change, button is disabled.

### Output of `traefik version`: (_What version of Traefik are you using?_)
(from docker-composer.yml)
  traefik:
    image: traefik:v2.0

```
docker-host:~# docker run traefik version
Version:      2.2.1
Codename:     chevrotin
Go version:   go1.14.2
Built:        2020-04-29T18:02:09Z
OS/Arch:      linux/amd64

```

**Comment by ldez** [comment]
Hello,

The pagination has been replaced by an infinite scroll in v2.2.0

https://github.com/traefik/traefik/pull/5875

https://github.com/traefik/traefik/blob/master/CHANGELOG.md#v220-2020-03-25

**Comment by kongeni** [comment]
Upgradet to v2.4.2 and still only get 10 HTTP routers in the list?
prev/next buttons are still there and disabled.

Notice 20 HTTP routes counted, and only 10 shown.

<img width="1107" alt="billede" src="https://user-images.githubusercontent.com/78784414/107412728-394e1780-6b10-11eb-9728-39002fc3a5b5.png">

I can still find them if I search for them ("user" was missing)
<img width="1110" alt="billede" src="https://user-images.githubusercontent.com/78784414/107413399-00627280-6b11-11eb-8cee-355be5b04b9f.png">

**Comment by kongeni** [comment]
Hi @ldez It works fine in Chrome. It is "only" in Firefox and Safari it doesn't work... I didn't test more browsers ;)

Still think it is a bug

**Comment by ldez** [comment]
I use Firefox and I don't have any issues, refresh/clean your browser cache.
