### ISSUE TITLE
Ability to customise Server Transports Dynamically

### ISSUE THREAD

**Issue by microadam** [traefik/traefik#7893]
The file and k8s providers are currently the only ones to support this. Is it possible this feature will be coming to the Consul Catalog provider any time soon? I can see you can, using tags, set which Server Transport a service should use using:

```
traefik.http.services.ingress.loadbalancer.serversTransport=test
```

However there is no where (as far as I can tell) to actually define what the "test" Server Transport is (so you just end up with the error:

```
servers transport not found test@consulcatalog
```

My use case is that I am trying to setup HTTPs communication between traefik and the service, however I believe the only way to do this is by setting a custom `serviceName` property on the Server Transport, but there isn't currently a way to do this using Consul Catalog

**Comment by ldez** [comment]
Hello,

You have to define the `serversTransports` in the file provider:
https://doc.traefik.io/traefik/v2.4/routing/services/#serverstransport_1

then reference it:
```
traefik.http.services.ingress.loadbalancer.serversTransport=test@file
```

**Comment by microadam** [comment]
Hi @ldez Thanks for the info! So does that mean I have to manually specify a server transport for EVERY service, inside the file used by the file provider, if I want to have a custom `serverName` (or any other setting) for each of my services?

**Comment by ldez** [comment]
You have 2 ways:
- define a global configuration (inside the static configuration): https://doc.traefik.io/traefik/v2.4/routing/overview/#transport-configuration
- define a file that contains your customs configuration: https://doc.traefik.io/traefik/v2.4/routing/services/#serverstransport_1

Currently, it's not possible to define custom `serversTransport` that labels/tags

**Comment by microadam** [comment]
Thanks for the links and for letting me know the current limitations. Hopefully this is something that can be added in the future :)

**Comment by dvv** [comment]
Hi!
Any update on the subj?
TIA

**Comment by sammcj** [comment]
This just caught me out again, would be good to have it available as a label

**Comment by nmengin** [comment]
Hello there,

This proposal was opened 3 years ago with almost no traction.
We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.
Thank you @microadam  for the suggestion, and @dvv and @sammcj for your comments.
