### ISSUE TITLE
improve basic auth performance by caching expensive password hashing computations 

### ISSUE THREAD

**Issue by wbolster** [traefik/traefik#7897]
### tl;dr:

using http basic auth with high bcrypt complexity results in high cpu load and slow response times; caching may alleviate this.

### Do you want to request a *feature* or report a *bug*?

a feature (or a performance bug, depending on how you look at it)

### What were you trying to do?

i want to use basic auth (over tls) with strong bcrypt complexity as a simple but sensible security setup for things like the traefik dashboard.

### What did you expect to see?

i expected it to work, and it does…

### What did you actually see?

…but it slows down _every request_. merely having the dashboard open in a browser results in periodic polls to the `/api` endpoints, and each request is slow and eats CPU resources at the server.

### What do you think can be done about it?

this slowness seems unnecessary. similar things have been reported before (e.g. #4791) but it seems it did not get the proper explanation/attention.

each request will have a valid user/pass in normal situations, since that is how basic auth operates. in practice, the basic auth middleware invokes `goauth.CheckSecret` _for every request_ ([source code](https://github.com/traefik/traefik/blob/master/pkg/middlewares/auth/basic_auth.go#L68)).

the main problem here is that the code performs a (potentially very slow) bcrypt operation too often: it is called for _every request_ by the same user with the _exact same inputs_, giving the _exact same results_ (`bcrypt` is a pure operation). this is simply wasteful, resulting in slow responses and high cpu usage.

my suggestion would be to use a small in-memory (!) caching mechanism to track recent _valid_ authentication attempts. for the expected use cases such as traefik dashboard + basic auth + strong bcrypt + small amount of users, this will likely avoid 99%+ of all slow operations.

the cache would contain a mapping from a key `(user, pass, realm)` to any value. presence of a key in the cache means it was validated correctly, absence means a real bcrypt check has to be done (which would result in `.Add()` when successful). the thread-safe `Cache` implementation in the `golang-lru` package ([source](https://github.com/hashicorp/golang-lru), [docs](https://pkg.go.dev/github.com/hashicorp/golang-lru)) may be helpful here.

note that there seem no additional security implications here: secrets are only ever kept in memory, and they are already in memory to begin with. but in practice it may be advisable to use a cheap(er) hash algorithm (e.g. sha512) to hash the user/pass/realm combination, and use that as the map key for the cache.

**Comment by wbolster** [comment]
(copying relevant part of the #7900 description to keep the discussion centralized)

### What does this PR do?

This introduces a small in-memory caching mechanism to the BasicAuth
middleware to improve response times and reduce CPU usage.

### Motivation

While HTTP Basic Authentication is not widely used for externally facing
services in the real world (for multiple reasons), it is a reasonably
secure and simple way to setup access control for things like
internal-facing dashboard applications, such as the Traefik
API/dashboard. In practice, dashboard tools (e.g. Traefik's own
dashboard) continuously perform HTTP requests to update themselves. When
using a strong(er) hashing algorithm, merely having a dashboard open in
a web browser can cause significant server CPU load and high latency… 😿

HTTP Basic Authentication requires embedding a user/password combination
in every request. The BasicAuth middleware verifies every request, which
involves password hashing, and this can be quite slow (see below). The
good news is that in the common case, the password hashing function is
repeatedly called with identical inputs. Since this is a pure
function (no side effects, no randomness involved), the results can be
cached, which helps tremendously for common use cases such as repeated
requests from the same logged in user (each time with the same user/password
combination in the HTTP request).

### Implementation details

- Use a small in-memory LRU Cache from golang-lru, which was already an
  indirect dependency.

- Cache the result of goauth.CheckSecret() calls. Note that this caches
  both positive and negative results, which covers both the ‘everything
  fine’ and the ‘misconfigured cron job continuously trying to log in
  with the wrong credentials’ cases.

- Use a SHA512 hash (unrelated to password hashing operation) over the
  realm/user/password combination to produce a cache key. This
  guarantees that plaintext secrets (such as the password in the request
  headers) are not kept in memory longer than necessary. (This depends
  also on garbage collection, reused memory, etc.)

- Note that the cache size is hardcoded. It uses a small amount of
  memory, while at the same time it is very effective for the ‘handful
  of users accessing an internal dashboard’ use case. Exposing the cache
  size as a configuration value would be technically possible, but the
  usefulness is questionable (and has implications for docs,
  maintenance, upgrades, etc.)

- Adapt the tests to perform multiple requests to hit both the hit/miss
  scenarios.

(see #7900 for details, including some numbers)

**Comment by wbolster** [comment]
(copy of maintainer reply to PR https://github.com/traefik/traefik/pull/7900#issuecomment-780694543)

**Comment by wbolster** [comment]
regarding the questions posed in [this comment](https://github.com/traefik/traefik/pull/7900#issuecomment-780694543) in pr #7900:

> * What would be the strategy to revoke users? (the cache lib you used is basically a fifo stack configured with 128 slots)

There is no strategy to revoke users, and it seems not needed either? Unless i misunderstand how Traefik's middleware mechanism and basicAuth implementation works, all users are loaded (from file and/or users specified in the config) whenever the middleware is instantiated. As i understand it, a change in configuration would lead to a reload, and that results in the creation of a new middleware instance? Practically speaking: `NewBasic()` calls `getUsers()` and stores the resulting map in a field on the new `BasicAuth` struct. My pull request constructs a new `Cache` inside `NewBasic()`, so it is also owned by the newly constructed `basicAuth` struct.

> * A fifo stack won’t be beneficial in any way if it’s always full of unsuccessful attempts because somebody is trying to brute force the auth

Brute forcing would lead to cache misses in all cases. Only repeated failed attempts with the same user/pass combo would result in cache hits (e.g. misconfigured cron job), and that is not what brute forcing attacks do.

Also, if an attacker is hammering the server and causing a large number of (failing!) bcrypt operations and corresponding high CPU load, the least of your worries is a few cache misses and resulting successful bcrypt operations from legit users (e.g. a browser with a Traefik dashboard).

If this is really something that you believe is worth worrying about, another caching strategy could be devised, but tbh i think it's moot.

> * What is the impact on performances, making the key to store in cache (sha512) versus computing bcrypt each times

SHA512 (and similar hash functions) are orders of magnitude faster than password hashing functions, and this is by design:

- Computing the cache key is in the <1 ms range.

- Bcrypt is ‘as slow as you can afford’, and the cost factor should be tweaked accordingly. It is much higher than the sub-millisecond range for computing the cache key. See [this OWASP article](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#work-factors) for details about password hashing best practices, including relevant [details about using bcrypt](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#bcrypt).

A caching approach reduces the impact of a higher cost factor significantly in two common scenarios (see below) which means one can ‘afford’ a higher work factor.

See also [this answer on the security stack exchange community](https://security.stackexchange.com/a/10522).

> * What are the most common scenario of complexity used with bcrypt encoded passwords?

- The [same OWASP article](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html) contains this snippet: ‘the default work factor for Bcrypt is 10, and this should generally be raised to 12’. This [auth0 blog post](https://auth0.com/blog/hashing-in-action-understanding-bcrypt/#L-code-bcrypt--code--Best-Practices) has a good practical example for what this can mean in practice, though note theat ‘constantly authenticate’ is exactly what HTTP Basic Auth is all about (by design limitations).

- For comparison, the `bcrypt` module for Python uses 12 by default; see [its documentation](https://github.com/pyca/bcrypt/#adjustable-work-factor).

> * In what cases does that PR improve performance?

> * What is the benefit for high frequency configuration reload context

Not sure what this means; can you clarify the question?

**Comment by wbolster** [comment]
Note that my proposal is not a novel approach at all. A quick web search reveals some relevant prior art:

- [Balancing CPU cost when using BCrypt
](https://www.fngtps.com/2013/balancing-cpu-cost-when-using-bcrypt/); using a cache
- [semi-random stackoverflow answer](https://stackoverflow.com/a/46113073)

- Note that [this auth0 ‘bcrypt as a service’ post](https://auth0.engineering/bcrypt-as-a-service-9e71707bda47) is *not* relevant for Traefik's use case, since Traefik cares about _repeated identical_ logins (few users refreshing a dashboard page with basic auth), not different legit login attempts as described there.

Finally, and i only noticed this now: the folks over at Caddy had a very similar performance issue; see [caddyserver issue 3462](https://github.com/caddyserver/caddy/issues/3462), and they ended up with a very similar solution; see [caddyserver pr 3465](https://github.com/caddyserver/caddy/pull/3465). Of particular interest is this code comment:

> ```
> // This can greatly improve the performance of traffic-heavy
> // servers that use secure password hashing algorithms, with
> // the downside that plaintext passwords will be stored in
> // memory for a longer time (this should not be a problem
> // as long as your machine is not compromised, at which point
> // all bets are off, since basicauth necessitates plaintext
> // passwords being received over the wire anyway).
> ```

...which also [found its way into the documentation](https://caddyserver.com/docs/modules/http.authentication.providers.http_basic#hash_cache).

The approach i took by keeping a SHA512 hash in memory (in the cache) instead of the plaintext password, alleviates this exact ‘problem’!

**Comment by dtomcej** [comment]
>What is the benefit for high frequency configuration reload context

When Traefik reloads its configuration in dynamic environments due to a configuration change, the corresponding middleware are recreated based on the new configuration. This means that in this case, the cache would be reset.

In large environments, these reloads may happen every few seconds. Would caching for the few seconds make a significant difference in performance? or would the overhead of maintaining the cache only for it to be cleared just introduce more work for little reward?

Finally, if you have a cache contained only in the middleware, the cache is limited to use by that one instance of the middleware, and has the lifespan of the middleware: meaning that if you have 100 instances of the middleware, each cache has to be maintained independently, and each cache may contain the exact same response. Perhaps a cache that exists outside the middleware could be leveraged to provide a larger record lifecycle...

**Comment by wbolster** [comment]
the cache initialisation is a tiny array init. much less work than the other parts like loading the users and putting them in a map, i reckon. thinking of it, as an optimization, the cache size can become `min(HARDCODED_CONSTANT, len(users)`.

storing an item in the cache is practically free, and a single cache hit already pays off enormously. opening a single web page with some html, images, and api requests, all within a very short timespan: n requests, n-1 cache hits 😍

**Comment by wbolster** [comment]
gentle nudge to maybe get some discussion about this? :pray: 

currently traefik + basic auth with strong password hashing parameters is a performance nightmare that impacts the whole system (not just the protected resources).

multiple other projects take a very similar approach and it can be argued that #7900 is implemented in a better way than other projects do it.

**Comment by Amunak** [comment]
> currently traefik + basic auth with strong password hashing parameters is a performance nightmare

I agree and would actually add that using the BasicAuth middleware without other precautions (like IP whitelist) opens you to a very simple and **effective DoS** where the attacker can hammer you with a few dozen auth requests (or less if you use high cost) a second and completely drain your CPU.

This issue should be - at the very least - well documented in the middleware's documentation. Users should be warned to use a really low cost (probably 8 or less) or other hash algorithms.

As long as it isn't even documented I'd argue that this is a **security issue** more than anything else.

> Would caching for the few seconds make a significant difference in performance?

@dtomcej yes, absolutely. I found out about this issue by installing Netdata behind Traefik and simply loading its dashboard. They make ~5 HTTP requests per second and that was enough to completely stall my whole server (2 dedicated threads of a Xeon(R) CPU E3-1585L) with a Bcrypt cost of 12. Even with 8 it was still noticeable.

Caching even for a single second would be major help.

**Comment by bmarinov** [comment]
I completely agree that we need some kind of improvement. In order to not simply +1 the issue, I'll quickly explain my stance. 

A common scenario is to put a reverse proxy in front of grafana and, in my case, a loki backend, in order to restrict the access.
With bcrypt at 12 rounds, handling a few requests per second from fluentbit results in respones taking around 500ms. If I were to reduce bcrypt to 8 rounds, the response times would drop to somewhere in the sub-50ms range. This is simply huge on any relevant scale. 

We are ingesting metrics and logs from a few off-site and edge servers and currently the alternatives are to either move to SHA-1, or switch to OAuth and bearer tokens. If Traefik users fail to notice this in test, they can easily end up DoS'ing the reverse proxy host. In my case the test involved a single remote host pushing logs to the backend.

Without support for some more decent and less computationally intensive hashing algorithms like SHA256 and the like, we are stuck selecting between the trivial (ahem, collisions) MD5 and SHA-1, and the overly expensive (without caching) BCrypt.

Caching or an alternative hashing algorithm are really needed here.

**Comment by schinkelg** [comment]
Just switched from Bcrypt to MD5 for the same reason. Basic Auth is used not as a secure authentication mechanism but as a hurdle to prevent easy access. In my case I used Traefik in front of a static site that was somehow incredibly slow (500+ ms for each request). Simple Traefik and Nginx setup shouldn't be slow. Finally decided to debug this problem and saw Traefik eating the CPU for simple requests. Turns out it was Bcrypt all along... 

Without warnings in the documentation this reflects badly on Traefik IMO.

**Comment by evilscientress** [comment]
We just hit this too and it cost me a whole day in debugging because I just didn't expect that a modern reverse proxy would struggle with basic auth.
We used it with a frontend that uses a slippy tiled map, so it loads a lot of small image files. This bug caused the response time for requests to spike to 2.5 seconds, compared to 20-50ms without the basic auth middleware.
With the hash algorithm changed to MD5 the response time is now around 100-150ms, that's still and additional 50-100ms of response time.

Only option in our case is to now switch from Traefik to nginx-ingress controller.

**Comment by wbolster** [comment]
😩😨

please, traefik maintainers, this is getting ridiculous. this issue:

- is a performance nightmare
- is a security problem
- makes a documented feature unreliable or at least behave unexpectedly 
- is 3+ years old
- affects multiple deployments
- has a very extensive description and rationale
- has a working pull request alleviating the problem, waiting for 3 years already
- has a proposed solution that follows prior art, and similar/competing products use roughly the same approach 

you don't really want to wait for some published public postmortems pointing to this traefik bug when services either suffer outages or get compromised, i hope?

i understand everyone's busy, and this being open source, noone owes anyone anything, but with a company behind this project, i expect security and performance bugs to at least get some serious consideration.

💕

**Comment by nmengin** [comment]
Hello @wbolster,

This proposal was open for a long time with almost no traction.
We won't add it to the Roadmap yet and prefer to close it.

We'll re-open it later if necessary.
Thank you for the suggestion.

**Comment by Amunak** [comment]
What do you mean "no traction"? Users are hoping for a fix. I want to say there's a workaround but not really, the solution is "just don't use this feature", and that's stupid. It also still leaves you open to performance issues (if you don't manage to notice the issue) *and* a DoS attack.

In other words this isn't a "kindly add a feature for us" type of situation, this is more of a "fix your bugs and maybe don't leave poorly implemented/untested features in".

It kind of sheds some really bad light on the project as a whole, considering that it took you 3 years to decide you shouldn't fix a bug and you consider that "completed"? I'm sorry, what?

**Comment by erkexzcx** [comment]
> This _proposal_

https://github.com/traefik/traefik/issues/7897#issuecomment-1506729855 😅

**Comment by wbolster** [comment]
hello maintainers, please reconsider reopening this issue. it seems to me that ‘mistakes were made’. not pointing fingers…

but _come on_, what a joke 🙄. i wrote before that

> this is getting ridiculous.

… followed by a summary of all background discussions and (very concrete!) proposals and efforts so far. and the official reply is that this issue has 

> almost no traction

really? REALLY? well, it certainly has gotten ridiculous by now. 🤡

what's even more funny is that **your own marketing team actively reached out to me** in the past to **send me swag** for my (admittedly limited) involvement in the traefik project, which is almost exclusively **this exact issue!**

here's a pic of me wearing a traefik shirt that literally reads ‘traefik contributor’ 😆 

![wbolster-traefik-shirt](https://github.com/traefik/traefik/assets/748944/1bc4c52e-5e58-4f61-985d-d424d5d711e4)

**Comment by emilevauge** [comment]
I'm sorry @nmengin's answer does reasonnate for you @wbolster.
By "almost no traction", we mean that not so many people have reacted to this issue, compared to the numerous other issues we have to deal with (600+).
I would love the maintainer team to be larger and be able to talke more issues, but with our limited resources, we must focus only on the most critical issues.
If anyone from the community can help on this topic, we would love to assist.

**Comment by Thoulsadoom** [comment]
Hello there,

I'm facing exactly this issue while evaluating traefik for our system. I liked traefik very much up to this point, but this may be a game stopper when you either have to use insecure passwords or suffer massive performance issues.

Hopefully, this fix gets back on track and will be integrated soon.

**Comment by emilevauge** [comment]
Hello folks,
First of all, I really want to keep our conversation open and free from sarcasm. I know this is an old issue, I'm aware some of you want to contribute or contributed, but keep in mind that the maintainer team has limited bandwitdh to analyse and then maintain contributions in the long-term.
The maintainer team has several concerns with the proposal made:
- what about the security risk of this change? Caching credentials is usually something you avoid as it's a common source of vulnerabilities. 
- caching in a middleware while you can have hundreds of route instances (and thereofore cache instances) is questionable. Adding more memory allocations in the reverse proxy pipeline is always something you want to avoid to preserve performance (even though this is supposed to improve brypt performance). A mutual cache would probably be a better option.
- this cache being reset at each dynamic reload of the Traefik configuration is a major design issue. It looks like a better solution is possible.

Finally, Traefik provides 2 ways to build middleware plugins [WASM and Yaegi](https://doc.traefik.io/traefik/plugins/). Building a cached basic auth plugin could be a quick way for you to get better performance while a concensus is found on this issue.
