### ISSUE TITLE
can I authenticate grpc service use  traefik forwardauth with  jwt

### ISSUE THREAD

**Issue by jzhbiao** [traefik/traefik#7917]
**Do you want to request a feature or report a bug?**
feature (whether is available but I don't know how to deploy now)

**What did you expect to see?**
I want to request my grpc then auth first by forwardauth middleware

**What did you do?**
1. I use traefik version is 2.4.0
2. I have a auth-service-svc  and a user-info-service are writen by grpc 
3. following is my deploy yaml file

```apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: token-check
  namespace: k8s-treafik
spec:
  forwardAuth:
    address: h2c://auth-service-svc
    # tls:
    #   insecureSkipVerify: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: autodetect
spec:
  contentType:
    autoDetect: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myinfo-api-route
  namespace: k8s-treafik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`v3.b***.com`)
      kind: Rule
      middlewares:
        - name: token-check
        - name: autodetect
      services:
        - name: myinfo-service-svc
          scheme: h2c
          port: ### 8080
          namespace: k8s-treafik
```
4. kubeclt apply -f .
5. now all is work
6. but show error
```
rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
```

**how?**
anyone help me

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
