### ISSUE TITLE
Documentation middlewares/headers removing headers possible through label

### ISSUE THREAD

**Issue by Flightkick** [traefik/traefik#7924]
### What did you do?
I needed to remove a response header. [The documentation](https://doc.traefik.io/traefik/middlewares/headers/) mentions the following:
> Please note that it is not possible to remove headers through the use of labels (Docker, Rancher, Marathon, ...) for now.

Either I am misinterpreting the warning or this limitation has been removed.
I have added the following label in my `docker-compose.yml`:  
`traefik.http.middlewares.my-middleware-header.headers.customresponseheaders.X-The-Header-To-Remove=`  
Which removed the header.

I would have submitted a PR to fix the docs but this might need some verification as I have only been able to test this through Docker. Not sure if the same goes for Rancher, Marathon, etc.

### Traefik version
v2.4.5

**Comment by SantoDE** [comment]
Hey @Flightkick,

good catch! It can be removed from the docs, so fell free ;-)

**Comment by traefiker** [comment]
Closed by #7979.
