### ISSUE TITLE
go mod里导入github.com/traefik/traefik/v2失败

### ISSUE THREAD

**Issue by chenxuehui1** [traefik/traefik#7931]
我在我的项目的go mod 导入github.com/traefik/traefik/v2，运行后报下面的错误：
go: github.com/traefik/traefik/v2@v2.4.5 requires
	github.com/abbot/go-http-auth@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
