### ISSUE TITLE
TCP traffic for port should be able to redirected specific container

### ISSUE THREAD

**Issue by tyagiakhilesh** [traefik/traefik#7937]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We are using traefik for simulating our production environment. We have multiple services running in kubernetes running in docker. Few of them are java applications.  In this stack, a developer can come and deploy the code as per the git branches they are working on. So at a given point, we can have 100s of full fledged stack running. We use traefik for certificates resolution so that each stack can be hosted based on branch names and all. 

Now I want to give developer the facility to debug their java applications. Its fairly simple to do it in java. You need to attach java agent while starting up the docker image for application. Basically we need to pass `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=37000` as JVM argument and JVM is ready to attach remote debuggers. 

Now JVM is using JDWP protocol. And as far as I understand, it is a tcp protocol. Now my problem is: I want to traefik to create routes dynamically based on my docker service labels. That is also I am able to figure out. I used these labels in the docker service.

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/1140597/109415447-ccc38b80-79de-11eb-9d4d-6040a00bd8a7.png">

And this is how you connect to JVM remotely.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/1140597/109415523-36439a00-79df-11eb-8bda-f261f310c453.png">

Now if in RULE, if is use `HostSNI(`*`)` then I cam able to connect to the container. But problem is when I am doing remote connection for debugging, traefik can direct my request to any container. And this whole thing won't work as expected.

I believe we must have some other supported function for TCP rule as well, apart from only HostSNI. What is your opinion on this ? Or Have I missed something here ?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
