### ISSUE TITLE
Document `accessControlAllowOriginList` in Traefik 2

### ISSUE THREAD

**Issue by chris-aeviator** [traefik/traefik#7939]
According to the docs, a cors header can be set with ` accessControlAllowOrigin: "origin-list-or-null"`.

However, the described origin list is not described in the documentation at all. 

![grafik](https://user-images.githubusercontent.com/11522213/109476687-79514c00-7a77-11eb-9da0-0e1015304428.png)

Without setting the said parameter, I am unable to enable CORS on traefik. When setting the `accessControlAllowOriginList` parameter as a middleware and enabling the middleware on a service, I successfully see the CORS header beeing present on a request from a browser.

![grafik](https://user-images.githubusercontent.com/11522213/109477070-e5cc4b00-7a77-11eb-91f7-c91ce66d22db.png)

![grafik](https://user-images.githubusercontent.com/11522213/109476931-b87f9d00-7a77-11eb-8b2d-c3d89e3a3b42.png)

**Comment by rtribotte** [comment]
Hello @chris-aeviator,

Thanks for your interest in Traefik!

I'm not sure to understand your request here.

From the migration part of the [documentation](https://doc.traefik.io/traefik/v2.4/migration/v2/#headers-middleware-accesscontrolalloworigin), the `accessControlAllowOrigin` option has been removed and replaced by `accessControlAllowOriginList` in v2.2.

The documentation search is working on my side.
The `accessControlAllowOriginList` option is detailed in this [part of the documentation](https://doc.traefik.io/traefik/v2.4/middlewares/headers/#accesscontrolalloworiginlist).

I'll close this issue as a question accordingly.

**Comment by chris-aeviator** [comment]
@rtribotte thanks for your quick reply - looking at my screenshot I must have been on the 2.0 docs, thanks!
