### ISSUE TITLE
Update go.elastic.co/apm to 1.11.0

### ISSUE THREAD

**Issue by Azuka** [traefik/traefik#7954]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

https://github.com/elastic/apm-agent-go/compare/v1.7.0...v1.11.0

The version of the elastic apm go agent used for tracing is 1.7.0, about 4 minor versions below the latest version, and close to 2 years old. Would it be possible to update?

**Comment by jbdoumenjou** [comment]
Hi @Azuka,
 
Thanks for your interest in Traefik.
Could you open a PR?
If you want to do so, could you please list the differences and the potential impacts on Traefik?
