### ISSUE TITLE
Filter access log by /path or router name

### ISSUE THREAD

**Issue by fredsig** [traefik/traefik#7961]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I use Traefik behind an AWS ALB. The ALB is configured to hit Traefik's  /ping endpoint every 15 seconds. Since I always have at least 3 different ip's, this can fill my logs quickly. Would love to filter this somehow. I've managed to use `--accesslog.filters.minduration` as these requests take usually less than 1 ms but this also means that all internally produced codes (without any route request) will also not show, like 429 http codes on requests triggered by rate limiting. Ideally, a filter on /ping path or even the router name ping@internal would be great. Thanks.

**Comment by ldez** [comment]
duplicate of #6861
