### ISSUE TITLE
Traefik and Authelia conflicting use of subdirectory /api 

### ISSUE THREAD

**Issue by dutycaws** [traefik/traefik#7966]
Bug

### What did you do?

I configured Authelia to use the root domain "host.com" and Traefik's dashboard to use subdirectory "host.com/dashboard" in accordance with the documentation here: https://doc.traefik.io/traefik/operations/dashboard/ Traefik uses forwardauth middleware to authenticate prior to allowing access to any subdirectories of the domain.

### What did you expect to see?

I expected to be able to get redirected to Authelia to login, then be able to access the dashboard.

### What did you see instead?

Authelia throws the error "There was an issue fetching the current user state" only when traefik dashboard is using the route for host.com/api using rule - 
```
"traefik.http.routers.traefik-secure.rule=Host(`example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker run traefik version
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64

However, I specify version 2.4.5 in docker-compose
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Full configuration of traefik and authelia here: https://pastebin.com/vba46Pxk

**Comment by tomMoulard** [comment]
Hello @dutycaws,

Thanks for your interest in Traefik!

As you know, you can't have two routers on the same host using the same path. Traefik and Authelia does not allow you to change the path of the `/api` endpoint.
If you want to fix your configuration problem, the [documentation](https://doc.traefik.io/traefik/v2.4/operations/dashboard/#dashboard-router-rule) recommands:
> We recommend to use a "Host Based rule" as Host(`traefik.example.com`)

It seems your issue might be a configuration problem or relates to something that doesn't look like a bug, thus this issue will be closed.
To confirm this, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik/5).

In case I'm wrong feel free to re-open the issue.

In the meantime, you can double-check [Traefik's documentation](https://doc.traefik.io/traefik/).
