### ISSUE TITLE
Provider File: Can not load .css and .js File Traefik V2

### ISSUE THREAD

**Issue by reto88** [traefik/traefik#7974]
I use Traefik V2.4.7 with a provider file.
The page is working over https but the .css and .js files are not loaded over https, it got an error:

(index):1 Mixed Content: The page at 'https://xy.nesta.ch/' was loaded over HTTPS, but requested an insecure favicon 'http://xy.nesta/sites/all/themes/iscrt/favicon.ico'. This request has been blocked; the content must be served over HTTPS
Does anyone know the problem?

Here is the provider file:

`http:
  routers:
    cms:
      entryPoints:
        - "web"
      rule:  Host(`xy.nesta`) 
      middlewares: 
        - https-redirect 
      tls:
        certResolver: myresolver
      service: cms
          
  services:
    cms:
      loadBalancer:
        servers:
          - url: "http://192.168.77.127:8080"
        passHostHeader: true

    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customRequestHeaders:
          X-Frame-Options: "SAMEORIGIN"
        customFrameOptionsValue: "SAMEORIGIN"`

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
