### ISSUE TITLE
Bad middleware causes restarted Traefik to be unavailable after restart

### ISSUE THREAD

**Issue by jralph** [traefik/traefik#7977]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Traefik 2.3.3 running in Kubernetes
2. Have existing ingress routes and middleware setup and running
3. Add broken or incorrectly configured middleware to Kubernetes
4. Assign broken middleware to an ingress route
4. Restart Traefik
5. Traefik is now unable continue its startup process, the UI/dashboard is available, but none of the registered ingress routes are detected.
6. Traefik is effectively down at this point.

### What did you expect to see?

Traefik to log errors for invalid middleware, but not cause a service outage when it encounters them. It should just log, and continue without it.

### What did you see instead?

Traefik, when restarted, complains about the invalid middleware and stops its entire process of finding resources in kubernetes. No ingress routes are parsed, none of the services are available. It should just log that the middleware is wrong, and move on. This way, only services trying to use the broken middleware would be down, not ALL services in traefik.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.3
Codename:     picodon
Go version:   go1.15.5
Built:        2020-11-19T17:43:21Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```text
- --global.checknewversion
- --global.sendanonymoususage
- --entryPoints.traefik.address=:9000/tcp
- --entryPoints.web.address=:8000/tcp
- --entryPoints.websecure.address=:8443/tcp
- --api.dashboard=true
- --ping=true
- --providers.kubernetescrd
- --providers.kubernetesingress
- --providers.kubernetesingress.ingressclass=traefik
- --providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik
- --entryPoints.web.proxyProtocol.trustedIPs=10.200.0.0/16
- --entryPoints.websecure.proxyProtocol.trustedIPs=10.200.0.0/16
- --entryPoints.websecure.http.tls=true
- --api
- --api.insecure
- --metrics.datadog=true
- --metrics.datadog.addEntryPointsLabels=true
- --metrics.datadog.addServicesLabels=true
- --metrics.datadog.address=$(NODE_IP):8125
- --tracing.datadog=true 
- --tracing.datadog.globalTag=tracing_source:traefik
- --tracing.datadog.localAgentHostPort=$(NODE_IP):8126
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
E0311 10:58:31.751765       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.Middleware: v1alpha1.MiddlewareList.Items: []v1alpha1.Middleware: v1alpha1.Middleware.Spec: v1alpha1.MiddlewareSpec.Headers: dynamic.Headers.CustomResponseHeaders: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|Headers":["Permissio|..., bigger context ...|contentTypeNosniff":true,"customResponseHeaders":["Permissions-Policy: accelerometer=(), camera=(), |...
```

**Comment by jbdoumenjou** [comment]
Hello @jralph,

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #5473.

Thank you for your contribution
