### ISSUE TITLE
Hurricane Electric dnsChallenge support

### ISSUE THREAD

**Issue by LinFor** [traefik/traefik#7995]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Please add Hurricane Electric provider support in dnsChallenge. This can be done easily through updating go-acme/lego to [v4.3.0](https://github.com/go-acme/lego/releases/tag/v4.3.0) or later

**Comment by ldez** [comment]
Hello,

already done in #7975
