### ISSUE TITLE
Unable to download plugins via traefik pilot

### ISSUE THREAD

**Issue by yashmehrotra** [traefik/traefik#8004]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to download a plugin I created

### What did you expect to see?

Plugin should be downloaded without any errors

### What did you see instead?

```
2021/03/24 11:56:16 traefik.go:76: command traefik error: failed to download plugin github.com/bukukasio/super-rate: error: 500: {"error":"failed to get plugin github.com/bukukasio/super-rate@v0.0.1"}
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.3.1
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
--pilot.token=xxxx
--experimental.plugins.super-rate.modulename=github.com/bukukasio/super-rate
--experimental.plugins.super-rate.version=v0.0.1
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-03-24T12:00:57Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus
time="2021-03-24T12:00:57Z" level=debug msg="loading of plugin: super-rate: github.com/bukukasio/super-rate@v0.0.1"
2021/03/24 12:00:58 traefik.go:76: command traefik error: failed to download plugin github.com/bukukasio/super-rate: error: 500: {"error":"failed to get plugin github.com/bukukasio/super-rate@v0.0.1"}

```

Followed the steps as given
This is the plugin: https://pilot.traefik.io/plugins/605b2779bb01142ed43bf6a8/super-rate

I am able to download other plugins though

**Comment by SantoDE** [comment]
Hey 👋 

It looks like, you did force push a tag to the repo which leads to that error. If you do a new, fresh tag it should be fine I guess :)

**Comment by yashmehrotra** [comment]
@SantoDE I tried with fresh tags as well, didn't work out. Is there any way to increase the verbosity of the error message ?

**Comment by ldez** [comment]
You have to create a new tag: a tag cannot be overridden like in the goproxy.

**Comment by yashmehrotra** [comment]
@ldez Yes, I created a new tag (you're talking about a Github release and tag right ?)

It is still giving me an error
```
2021/03/26 02:25:36 traefik.go:76: command traefik error: failed to download plugin github.com/bukukasio/super-rate: error: 500: {"error":"failed to get plugin github.com/bukukasio/super-rate@v0.0.2"}
```

Meanwhile, on the plugins page it is displaying the new version: https://pilot.traefik.io/plugins/605b2779bb01142ed43bf6a8/super-rate

**Comment by SantoDE** [comment]
Hey @yashmehrotra,

thanks for reporting again. We figured an issue in our download system and fixed it on the platform side. Can you try again and potentially do one last tag?
