### ISSUE TITLE
Clarity on middlewares, routers, and services - per compose project

### ISSUE THREAD

**Issue by dm17** [traefik/traefik#8009]
Based on @ldez comment here:
https://github.com/traefik/traefik/issues/6290#issuecomment-583354592

Considering the redirect middleware is usually in traefik's own compose project... Does it need to be unique per other compose projects being run? Or will it get applied to each compose project without interfering as a duplicate middleware between their services? To restate another way for clarity's sake: middlewares, for example, can conflict outside of their own docker-compose project. Therefore, each service should have a unique middleware (and service/router) name. Does this apply in the case of the catch-all for redirection? And if not, then why?

Thanks!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
