### ISSUE TITLE
Not listening to internal K8/Cluster requests

### ISSUE THREAD

**Issue by doug62** [traefik/traefik#8015]
With Traefik 2, using Metalb,  from within a pod, curl https://<an external url> produces:
curl: (7) Failed to connect to <an external url> port 443: Connection timed out

I would imagine this is caused because Traefik is set to listen to the LM IP/Ports and perhaps not on the cluster IP but is there a way to configure this?  Either in K8 or Traefik?  Note - my internl/pod ping resolves to the Traefik LM IP.

Thanks

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
