### ISSUE TITLE
docs: updating CRD definitions and RBAC should be mentioned in 2.3 -> 2.4 migrations

### ISSUE THREAD

**Issue by gizero** [traefik/traefik#8017]
After upgrading from 2.3 to 2.4 with the kubernetescrd provider enabled, traefik fails to fetch CRDs from k8s (i.e. Middlewares). Updating both CRD and RBAC as per commit 76f42a30 `add ServersTransport on services` solves the issue. IMHO upgrading CRD definitions and RBAC should hence be mentioned as a 2.3 -> 2.4 migration requirement [here](https://doc.traefik.io/traefik/migration/v2/)

### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Upgraded Traefik from 2.3 to 2.4

### What did you expect to see?

My kubernetescrd setup to keep working

### What did you see instead?

All routers complaining with a "middleware xxx does not exist".

Below error helped to track the issue down:

`E0328 09:26:33.087928       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ServersTransport: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.containo.us is forbidden: User "system:serviceaccount:kube-system:traefik-authkeys" cannot list resource "serverstransports" in API group "traefik.containo.us" at the cluster scope`

### Output of `traefik version`: (_What version of Traefik are you using?_)

Reproducible with any release in the 2.4 branch. 2.3.7 works as expected

**Comment by traefiker** [comment]
Closed by #8019.
