### ISSUE TITLE
Missleading error log when no HTTPRoutes are set

### ISSUE THREAD

**Issue by SantoDE** [traefik/traefik#8022]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Install Traefik 2.4.8 with the Gateway Provider enabled and do not have routes deployed yet.

### What did you expect to see?

No errors in the log

### What did you see instead?

Errors in the log :)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
2.4.8
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
      --global.checknewversion
      --global.sendanonymoususage
      --entryPoints.traefik.address=:9000/tcp
      --entryPoints.web.address=:8000/tcp
      --entryPoints.websecure.address=:8443/tcp
      --api.dashboard=true
      --ping=true
      --providers.kubernetescrd
      --providers.kubernetesingress
      --providers.kubernetesgateway
      --experimental.kubernetesgateway
      --pilot.dashboard=false
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
time="2021-03-30T10:02:17Z" level=error msg="an error occurred while creating gateway status: 1 error occurred:\n\t* Cannot fetch HTTPRoutes for namespace \"default\" and matchLabels map[app:traefik]\n\n" providerName=kubernetesgateway gateway=traefik-gateway namespace=default
```

**Comment by traefiker** [comment]
Closed by #8023.
