### ISSUE TITLE
Reverse Image Proxy Example

### ISSUE THREAD

**Issue by bvandermeersch** [traefik/traefik#8034]
I want to send anything from /img/* to an s3 bucket instead of my docker container.

I cant find any examples on the web, and your documentation is terrible for rules and routing out side of the network.

I figure there would be a lot more info on this. Im sure most people use a reverse proxy for this.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by bvandermeersch** [comment]
No one replies to your forum.

**Comment by jakubhajek** [comment]
Hello @bvandermeersch 

Thanks for your interest in Traefik. 

You can use the combination of `Host` and `PathPrefix` matching rules e.g. 
``` Host(`example.com`) && (PathPrefix(`/img`))```
Additionally, you can remove the added path before forwarding the request to the service by using [Middeware StripPrefix](https://doc.traefik.io/traefik/middlewares/stripprefix/). The service that points to the S3 bucket can be created as a file and added as the file provider. Please refer to the documentation and the section  [Declaring an HTTP service with Two Servers](https://doc.traefik.io/traefik/routing/services/). 
```yaml
http:
  services:
    s3-bucket:
      loadBalancer:
        servers:
        - url: "http://s3-bucket-example.com"
```

Let's move the further conversation to our [community forum ](https://community.traefik.io/)as @traefiker suggested, thank you :-)
