### ISSUE TITLE
configure route or middlewares in dashboard

### ISSUE THREAD

**Issue by cheneyang** [traefik/traefik#8037]
### Do you want to request a *feature* or report a *bug*?

Known by [doc](https://doc.traefik.io/traefik/providers/etcd/), we can configure routes by etcd, and the dashboard show us 
the routes and other configs, so can we configure route or middlewares in dashboard?

### What did you expect to see?

the dashboard provide us a form or other ways to configure routes.

**Comment by SantoDE** [comment]
Hey @cheneyang,

thanks for the proposal :)

As of now, we don't have any plans to add such kind of features to Traefik, as it would require Traefik to persist a state somewhere. As Traefik is designed to be a simple, stateless proxy that doesn't fit for now.

For that reasons, we will close that proposal for now. But lets see, what the future might me bringing
