### ISSUE TITLE
Traefik pilot problem to add a new instance

### ISSUE THREAD

**Issue by Whisper40** [traefik/traefik#8047]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I register to traefik pilot with github, and i would like to add my first instance of traefik.

### What did you expect to see?
A page with my token

### What did you see instead?
Error message : `state mismatch, expected L2luc3RhbmNlcz9hY...`

The expected value and the got value are the same
![image](https://user-images.githubusercontent.com/30440458/114277180-693f6b80-9a2a-11eb-9c30-05972f546b3b.png)

**Comment by jakubhajek** [comment]
Hello @Whisper40 

Thanks for your interest in Traefik Proxy and Traefik Pilot.

Would you please try to give us reproducible steps, if possible?

**Comment by Whisper40** [comment]
This problems appears during 1 hour when i posted the issue. Actually the problem don't appear. 
When the problem occured, i tried too with private browser.
Will close and update if i have the same problem !

My steps were just : 
- I have a traefik that is started
- i add the pilot token in my config
- i recreate the container
- i go to pilot with my github account
- and after that the error is shown

**Comment by ludoblockdevice** [comment]
Hello,

I'm encountering the exact same issue after clicking on connect with traefik pilot.
Token is registred in my config as well.

state mismatch, expected aHR0cHM6Ly90cmFlZmlrLmJsb2NrZGV2aWNlLnRrL2Rhc2hib2FyZC8jLz9wbGF0Zm9ybT0vfBYdBb6RMqFn0l9mqnI6sUaF3uXiK-ce-KgEEko1YlDC,a0:session=Fe26.2**dbc14d01e11304bf2fae35166f69664ebe5420dff9c43cdca3bf5996bf87f301*9L5rGntn3YXYwwECx73GQg*U5liXPG2-mftKobpkfkPOfgIuFXqmKgGSPxY9dufy8JSbQBuKCp1_nPiI2HhoJTabwMYANYsj6fRYcHgYfcJgthty2ifwwnt-n5AcnZcFrBZyJl9UP8aCwzJEqtxFgV-5IXOaCsVY-Dx5Gdegw-pE67k6dZc0IjX4BUfXj-swqV0-k6E8i1jQmN1FqKBVBmK12HsxRRvy8TqXDJUoCZbk6bxUmq3r0Vs2GyoaLudV4j1a6x_wv9hjpmLDtYG_o9L_yLXTV9NCpIwj6sZlujBrPZ23NDd6SUe1VS5nuPr4fJrKaRVORiYmb-qnYXXFg1YBzoELKkzektKzctUlb7h3e476J345zSkRG2tpjDDU-gu-WR88Z5Zm620Bt_OkgSISHjWYVbcxDslHkFQ31cKEcwD11kYQKLfsvTuedJn183xHv0fZzj_0arO_l2xM0ztzKYqggcjWoZSgWhNagONuzKHfs3AWp3JxGYo0-O4tz59nSigrZoXR4omAmzmunn900-kxjeSC_CB1oqRsLej5wkDCGed-oDQh7z_knD3etl0uh2kJcWwmskmo2AKQMLBU4Hpxjk8E-KRW3hI1rgywHad8XL0HMU8XyTU2sMObb4ey1sKxIcF0ATKDpuzh9FaxyWclG3FRKWgPJjUoyTzTUFg0eN2p11H0um-RNPku2BXNtrMNSM4bzR1vFUdSdZfThNNa7Pf_rOkD-PoyZQnh8leeAJnoisoGzatA5hrWnHExXpfWQFdY3YysKvX2sCVdvawBncR-nf1k3KwTlh77pX30SsPWL8KezAyFLL4YvEU2MZ0WEcbEeEpquYkgivPH-GshzMpXPDjiogE_NVP55jwnXTjVKArotXP7SoXq83JWnhhIN-ypyxxKe385V-YraKDiuHByD2Jnwgu7SZ5eW1_kqge55MidYwSSoUUM4zvL6akkdBAL_sv-0IvK1TmryHmEX3LHUimr9qP0PZ_ADsmzxMGfAgNVNR2W7Hw3cZL_Ggj8cij-eRIn_9LsUqBRRs8ZusmgF6PmNd2IvxdDRzw9zXT1uwkHTUfV3EV7vRVyeK0bvzqsGy-XDpAMb9CxI3DjC5RM2YfPF93Qxr0EVttftyAKFbTGIcUg3LmqhdAFIh7vwj-w_nMJNisI0z0REhp0Bt6dfrfLODS_MYxMHdHNmpHPf5GPebihaCbJndRRQoRcfwkqM7COMvWwYW-Pa-7KpcoKS7sxHEbJo_qJtgKq4zLuAWgp8LC63raN3KNi9OEK4LG9vrPAT9xLbGOfsTuTt5EfkV_ACTjQhO1HlpOcxEej2ksAh3VmoFeb-LAklbv0ynYelrZxk_DL4rNhgvpRVBdn63mHilcYtKa0CStvaUdjpffnzk-iWL0QdjDRdW67OdqJOZhuP_u7EnR0DjvALz_XxNejeLk72IJIE8glRzNrJ78rmsqhxSLFMC3Y_laK9_Xm6jVOEsE_GE4HtZW3ZL5PY7qsgub7qbkL073ONncfhcI93WTpq5v7GEw33CNBKIjfiaYE8va0DVpxu-By6iasYL9rZXiIMsc3xMEPQcoT9cKiatXTXTHVim0W3EwhikwVbb13dV7trZf2Qi9kim2LsaNDvg9JcaQdpgkAZFLmuArhUWfOuIibTPJYl67z8Sqk2xbxemj7-z6dKw_b2v9f4CCxs7nY-uMgfNOsFAB2Ybtv040S8KF-4ScNbIQ7j4dtrC5gGh7WNFNQv9nLTA7WoCVhnIyFSOoYWOoWTv9YpvbHtfMcWCmCVIwZM0KLUwOVnPl8y-qspq_FkRBNHzlOOm4m3tChiRBw7Z0cnNWCOFMpbmP3LQH23k1JHKEnhcUgeeJ9efCZTsfROCtrMo2fqkeUoBsvFuk0j7bhMupK03XkTfww3iVdjlEbCoK1B00yaCBxVLiMXiZBz0I2VRtaWH1oxoasWfHFBDEhs3PqExqdzi42iUrAP15HWnZdH2iYV95qlHeGLzJjARH1Aa8ZOOxNpxvZHpH8kA8V051pGTkmiq_fmyXNB4PytBVOJAHMFgntVJIbFXh1qD2O56z1CwxoIMMtHjEcDi806Ioa6nArNLfpwWnVabtP6GB5O6MoJTvjKB-SdCrVDpJWZ8tjNy2ELwrwowZfLEUZ4jvshwje1i-6oJwHHP21XkZTchiDuS7mAINXz3xS4Ib-meI0DBYQv-jGHcR_7GKJCBqCpd5kWQ5Lzi38YOO396Q7Saarkny1XFNKbx8mfL7OF4U1ewLUTxdvo_m8710sRGbNjboizMFHnuQiwF3Ahwd3-sS3jxiQ2a4eg_5anv4zvZ3eBRiw2pXPzsLkSzzV-dl4yL0-g2Pq-ZyGa1x1gDN_5WrWPXr2-rhrJAizMiuMJL3B2jv-ACZFJZ3oVazrf1kxIhxStPi47mYnrRcUEYeiWyqXUeatQIhEVTOtKMLFiIxY6pZu5mJzv4t_w9u-5oo4koH3bi3g3_egzkqFQnBb3MdrAviNLaRmDPehFalIzflN84x6RIFinDh-2SVKI4UgoeoQNDWyEMYdKOqWQcW1c7-StAetJuZPbxvdb5vOKqf71skcUl-ucq2ajh-28PRVTbEpNxki5MFu4k**c188fc0f3b3cddc14bcf557cc9ecdc9f8f4b8802cb9e829faea30c3c539fd26b*mxD0tCfSNunYNdva5OByDcdBjNJIl2zizRC30EHgGEA, got: aHR0cHM6Ly90cmFlZmlrLmJsb2NrZGV2aWNlLnRrL2Rhc2hib2FyZC8jLz9wbGF0Zm9ybT0vfBYdBb6RMqFn0l9mqnI6sUaF3uXiK-ce-KgEEko1YlDC

Thank you

**Comment by SantoDE** [comment]
Hey @ludoblockdevice,

thanks for the report. We are aware of the issue and are working on a fix on the pilot side.
