### ISSUE TITLE
Traefik container crashes when using a host rule without service

### ISSUE THREAD

**Issue by milosa** [traefik/traefik#8048]
### What did you do?

I have Traefik running in docker. 

In the `docker-compose.yaml`, in the service definition for Traefik, I created a host rule with the ip address of my server:

```yaml
services:
  reverse-proxy:
    image: traefik:v2.4.7
    labels:
    - "traefik.http.routers.catchall.rule=Host(`1.2.3.4`)" 
```

Then, I visited this ip address in my webbrowser. 

### What did you expect to see?

An error when starting traefik, a 404 in the browser, or nothing at all.

### What did you see instead?

The Traefik dashboard worked fine.
When I visited the ip address in my browser. The browser timed out.
Also, the server had high cpu usage during this request.
Eventually (after a minute or so), the Traefik docker container stopped. I don't see any errors in the logs.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.7
Codename:     livarot
Go version:   go1.16
Built:        2021-03-08T17:18:28Z
OS/Arch:      linux/amd64
```

I was doing this because, when you visit the ip address of the server, you get a Traefik generated 404 page.
I would like to disable this. I want no http response at all. If anyone knows a _simple_ way to achieve this, please let me know.

I tried pointing the router rule to the `noop@internal` service, but this results in the `418 - I'm a teapot` http status.

**Comment by ldez** [comment]
Hello,

you created an infinite loop, the result is high CPU and crash.

> I want no http response at all. 

It's not possible: every request has a response, it's HTTP.

To get more help, I recommend asking in our community forum: https://community.traefik.io/
