### ISSUE TITLE
RedirectRegex middleware ignoring my regex

### ISSUE THREAD

**Issue by midlan** [traefik/traefik#8049]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I configured RedirectRegex middleware but it didn't work. I think it is because traefik is ignoring my regex.

### What did you expect to see?
I expected to see my regex in middleware overview.

### What did you see instead?
No regex there:

![image](https://user-images.githubusercontent.com/4263992/114291880-1f3aa200-9a8b-11eb-9752-97f4eb457ede.png)

### Output of `traefik version`: (_What version of Traefik are you using?_)
docker one:
```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

$ docker -v
Docker version 19.03.15, build 99e3ed8919

$ docker-compose -v
docker-compose version 1.23.1, build b02f1306
```

**Comment by ldez** [comment]
Hello,

there is a typo in the label name: `treafik` instead of `traefik`:

![typo](https://user-images.githubusercontent.com/5674651/114298819-7d31ae80-9ab8-11eb-997d-677aea01b757.png)

**Comment by midlan** [comment]
Oh thank you @ldez I didn't spotted that! I copied that from some internet resources.
