### ISSUE TITLE
"ERR_EMPTY_RESPONSE" when using multiple entrypoints

### ISSUE THREAD

**Issue by alxpettit** [traefik/traefik#8055]
### Do you want to request a *feature* or report a *bug*?

Bug.

### What did you do?

I set up a traefik stack on a home system to test my setup. It includes a variety of pieces of software, including rocket.chat and deluge a few others -- all set up to be proxied via Traefik 2 labeling. This seems to work just fine when I have a single entrypoint set up -- but when I try to set up a second one for the TCP connection needed by Deluge -- it breaks somehow, giving `ERR_EMPTY_RESPONSE`.

### What did you expect to see?

My connection working.

### What did you see instead?

`ERR_EMPTY_RESPONSE`. This seems to only happen occasionally -- sometimes the deluge client connection on port `58846` works fine, and sometimes it breaks. The same happens to the `80` endpoint -- it seems that if I shut one down and make sure nothing's connected to it, the other one will start working. I had similar trouble when I tried to set up a SSL endpoint on port `443`.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

`command` section of traefik's `docker-compose.yml`:

```yaml
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:3080"
      # fails when this is uncommented:
      - "--entrypoints.deluge-rc.address=:58846"
      # attach to dockerproxy instead of docker socket itself
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
```

See full yaml [here](https://gist.github.com/alxpettit/1ffcb8d45e869482d244a6d6a6a677cc).

```yaml
      - "traefik.enable=true"
      - "traefik.docker.network=deluge-proxy"
      - "traefik.http.routers.deluge-router-http.rule=Host(`deluge.myserver.local`)"
      - "traefik.tcp.routers.deluge-router.rule=HostSNI(`*`)"
      - "traefik.http.routers.deluge-router-http.entrypoints=web"
      - "traefik.tcp.routers.deluge-router-rc.entrypoints=deluge-rc"
      - "traefik.http.services.deluge-service-http.loadbalancer.server.port=8112"
      - "traefik.tcp.services.deluge-service-rc.loadbalancer.server.port=58846"
      - "traefik.tcp.routers.deluge-router-rc.service=deluge-service-rc"
```

**Comment by jbdoumenjou** [comment]
Hello @alxpettit,

Thanks for your interest in Traefik.
As you have multiple networks with several services, did you try to define the network used by those services via the [network](https://doc.traefik.io/traefik/v2.4/providers/docker/#network) option?

**Comment by alxpettit** [comment]
as in, adding `- "--providers.docker.network=[network]"` in the labels? Yes, I've done this for all my services. I set each to the network with which the service can be accessed by traefik.

**Comment by jbdoumenjou** [comment]
The initial option is in the static configuration to tell Traefik which network to use.
Concerning dynamic configuration, the documentation says: 
> This option can be overridden on a per-container basis with the traefik.docker.network label.

**Comment by alxpettit** [comment]
I tried fiddling with that, but to no avail. I found that even when I skip having the entrypoint defined, these deluge labels will still cause the `ERR_EMPTY_RESPONSE` issue:
```
#      - "traefik.tcp.services.deluge-service-rc.loadbalancer.server.port=58846"
#      - "traefik.tcp.routers.deluge-router-rc.service=deluge-service-rc"
```
I think they're somehow listening on the wrong port and causing crosstalk.

I also am getting log spam like this, when I have the above labels enabled:
```
time="2021-04-13T08:42:17Z" level=debug msg="Handling connection from 192.168.0.198:55478"
time="2021-04-13T08:42:17Z" level=debug msg="Error while setting deadline: set tcp 172.30.0.3:41184: use of closed network connection"
```

**Comment by jbdoumenjou** [comment]
Could you provide a minimal reproducible case?

**Comment by alxpettit** [comment]
Sure, it shouldn't be very difficult :) I'll whip up a compose file tomorrow.

**Comment by alxpettit** [comment]
https://gist.github.com/alxpettit/f440089056eff26c840869bf598903d1

Here ya go.

**Comment by jbdoumenjou** [comment]
Thanks for the configuration.
We tried to use it and except the typo: 
``` 
 - "traefik.tcp.routers.deluge-router.rule=HostSNI(`*`)"
```
That should be 
```
 - "traefik.tcp.routers.deluge-router-rc.rule=HostSNI(`*`)"
```
deluge seems to work as expected.

When we tried to request the TCP port with an HTTP request, deluge answered with `ERR_CONNECTION_RESET`.
When receiving this kind of error, Traefik will answer with `ERR_EMPTY_RESPONSE` which is expected.

**Comment by alxpettit** [comment]
Whoop! Damn, my bad. :laughing:
