### ISSUE TITLE
Ratelimit Failure with Multiple Traefik Pods

### ISSUE THREAD

**Issue by imans777** [traefik/traefik#8061]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

What I want to say conceptually relates to #4867, and what I'm trying to propose as solution applies to both problems.  

The problem we have is that we run "traefik" on a deployment with multiple pods, let's say 3, and we have a service that can handle 10 RPS in general. If we create a `Middleware CRD` with `ratelimit` specs, how can we handle the load as we desire? If we set the number, e.g. `average`, to 10, then each pod of traefik would consider this 10 as the correct ratelimit, and this allows 30 RPS through the service! (10 per traefik pod).  

Currently we did this workaround: we set the `ratelimit->average` to 3, which would make 9 RPS through service, which is "almost" fine. But what if the load to traefik service gets high enough that we need to scale it to 4 pods? Then we have to manually change all ratelimit numbers (2 in this case, for a total of 8 RPS for this service) and as you can see, if the services get too much, doing this manually each time we want to scale is practically impossible. One might want to write a kubernetes operator to do this automatically, but you can guess how much overkill and antipattern that is!

### What am I proposing?

well what I've been thinking is pretty simple. If we have the total number of pods that traefik has (which is computable through "deployment available replicas"), we can divide ratelimit number to total pods as soon as we receive it from configs, and things should work fine.  

This is also applicable for backend ratelimit. We define ratelimit as "RPS to **a pod** of the service", and when receiving ratelimit config, we multiply it by the number of pods that service has available.  

I know this solution is very simple, but because this has been a problem for us, and no one has been attending to this "big" problem this whole time, I wanted to share it with community, mold it, and when we reach a solution that is robust and all side effects considered, then we start to implement it.

P.S. I remember that I've seen such issue before but I couldn't find it (I saw [this](https://stackoverflow.com/questions/50145688/how-to-share-rate-limiting-state-between-traefik-instances) too, with no answer). Because this requires architectural approval and discussion around it, I thought it's OK to create a new issue for it.

**Comment by SantoDE** [comment]
Hey @imans777,

thanks for your interest in the project.

This is not really a bug, it's rather how Traefik works. As every container in the pod is own its on, it just doesn't about the others.

Thats something that requires a different architecture.

About your proposal, I think that's not really sufficient as it would only work for k8s. Also, there is no technical way to know that information inside the middleware. Therefore, I sadly have to close that as a question :(
