### ISSUE TITLE
Support DNS alias mode for ACME dnsChallenge

### ISSUE THREAD

**Issue by zekroTJA** [traefik/traefik#8067]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Under specific circumstances you might not want to give full API access to your domain host. To be able to use ACME auto renewal over DNS, acme.sh for example supports an `alias mode`. Here you can read more about it:
https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

It allows to set a different domain as `challenge alias`, which will used to apply the TXT entry over the specified API. This domain is linked via a CNAME entry to the original `_acme-challenge` domain where you want to get the certificate for and which is used to check the TXT entry against.

It would be absolutely awesome if traefik would also support this when using DNS challenge, if there are no security issues with such a feature.

**Comment by ldez** [comment]
Hello,

Traefik uses lego to handle ACME challenge, there is an experimental option to handle CNAME: https://go-acme.github.io/lego/dns/#experimental-features
