### ISSUE TITLE
An option to disable tracing for a particular EntryPoint

### ISSUE THREAD

**Issue by pborzenkov** [traefik/traefik#8096]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I'd like to propose an additional option for an `EntryPoint` to disable tracing middleware for this particular `EntryPoint`, but keep it enabled for the rest of the `EntryPoint`s.

#### Motivation

I currently have relatively low incoming traffic and would like to trace all incoming requests (Zipkin backend with 1.0 sampling probability). On the other hand, metrics entry point is being accessed by Prometheus every 15-30 seconds, which generates significant number of more or less useless spans, makes it had to search for the spans generated by the incoming traffic, and increases storage costs.

If there are no objections, I can prepare a PR for this feature.

**Comment by rtribotte** [comment]
Hello @pborzenkov,

Thanks for your interest in Traefik!

If I understand correctly, the traffic generated by the polling of the metrics generates also tracing spans.
This seems ok because it's also routing from Traefik's point of view.

While I understand your approach, I'm wondering why filtering the unwanted spans on the Zipkin side wouldn't be preferable?

**Comment by pborzenkov** [comment]
Hello @rtribotte,

Zipkin doesn't seem to have an ability to drop inbound traces based solely on some span attribute, like name. This makes sense, as it needs to drop the whole trace based on information about a single span, so the decision will have to be kept in memory for some unknown amount of time while the rest of the spans belonging to the trace are not yet received.

I can obviously filter later while querying the server.

But yeah, you are right, it's probably not worth it complicating the code with such exceptions.

**Comment by rtribotte** [comment]
Hello @pborzenkov,

Thanks for your fast reply!
Yeah, that was the other half of my thinking on that, I also don't think that it worth the bargain of complicating both code and configuration.
I'll decline your proposal for now, but for sure if you stumble into an unforeseen major argument to do that on Traefik, feel free to interact here to explain why you think we should consider this feature.

**Comment by pborzenkov** [comment]
@rtribotte My main argument is the cost of storing all those traces. We are currently using GCP Stackdriver Tracing which charges per number of stored traced. But the price seems low enough to simply ignore this for now.

I have another scenario in mind where I'd like to be able to not generate traces for particular routes - WebSockets. Since WebSocket sessions tend to be long, it makes it hard to filter traces based on latency. E.g. list all traces with latency >1s, for example. This could be solved by querying traces that don't include particular spans, but sadly Stackdriver doesn't support exclusions in its query language. Anyway, this is something we can definitely live for now.

Thanks!
