### ISSUE TITLE
Malformed IngressRoute breaks all IngressRoutes

### ISSUE THREAD

**Issue by george-angel** [traefik/traefik#8098]
Traefik version: v2.4.8

This is effectively a duplicate of https://community.traefik.io/t/port-http-inside-ingressroute-block-all-ingressroute/5213 (https://github.com/traefik/traefik/issues/6614) - which has been closed and I'm unable to comment on.

In our case it was a typo in an instance of IngressRoute port (`8080s`), making it a `string` instead of an `int`.

```
E0427 07:14:14.313866       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.IngressRoute: failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha
1.IngressRouteSpec.Routes: []v1alpha1.Route: v1alpha1.Route.Services: []v1alpha1.Service: v1alpha1.Service.LoadBalancerSpec: Port: readUint32: unexpected character: , error found in #10 byte of ...|","port":"8080s"}]}]|..., bigger context ...|rvices":[{"kind":"Service","name":"probe
","port":"8080s"}]}]}},{"apiVersion":"traefik.containo.us/v1|...
E0427 07:15:03.990142       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.IngressRoute: failed to list *v1alpha1.IngressRoute: v1alpha1.IngressRouteList.Items: []v1alpha1.IngressRoute: v1alpha1.IngressRoute.Spec: v1alpha
1.IngressRouteSpec.Routes: []v1alpha1.Route: v1alpha1.Route.Services: []v1alpha1.Service: v1alpha1.Service.LoadBalancerSpec: Port: readUint32: unexpected character: , error found in #10 byte of ...|","port":"8080s"}]}]|..., bigger context ...|rvices":[{"kind":"Service","name":"probe
","port":"8080s"}]}]}},{"apiVersion":"traefik.containo.us/v1|...
time="2021-04-27T07:15:59Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-04-27T07:15:59Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-04-27T07:15:59Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-04-27T07:15:59Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-04-27T07:15:59Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-04-27T07:15:59Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-04-27T07:15:59Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-04-27T07:15:59Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-04-27T07:16:00Z" level=error msg="Error watching kubernetes events: timed out waiting for controller caches to sync *v1alpha1.IngressRoute in namespace \"\"" providerName=kubernetescrd
```

Original issue was closed in favour of:
https://github.com/traefik/traefik/issues/6109
closed in favour of:
https://github.com/traefik/traefik/issues/5473
close in:
https://github.com/traefik/traefik/pull/7815

Which looks like is planned for v2.5 release.

However **right now** this issue exists in the latest available version and poses a massive risk that a single erroneous character in a namespaced resource will bring down controller for the whole cluster.

I would like to keep this issue open - to track the current existing problem and close upon validation of the fix proposed in https://github.com/traefik/traefik/pull/7815.

Thank you.

**Comment by Montero1992** [comment]
Can someone confirm that this problem is solved in the future version 2.5?

**Comment by tomMoulard** [comment]
Hello @Montero1992,

As the pr #7815 has been merged on the `master` branch, this issue will be fixed on the next minor release of Traefik (`v2.5`).

**Comment by Montero1992** [comment]
ok, thank you @tomMoulard !

**Comment by george-angel** [comment]
Please re-open this issue.

https://github.com/traefik/traefik/releases - 2.5.0 is not out. We have not verified that 2.5.0 does indeed fix this problem.

**Comment by ldez** [comment]
The issues are closed when the PR is merged, it's not related to a release.
