### ISSUE TITLE
Parameterizable Traefik Labels in Docker?

### ISSUE THREAD

**Issue by dm17** [traefik/traefik#8099]
In order to re-use docker-compose templates, is it possible to disable a label via environmental variable (or similar) that is in a docker-compose.yml? For example, if we have basic auth setup in one environment and want to just disable those labels for another environment. If there's an env var in the label that does not get evaluated in an environment, then is the label disabled?
Thanks!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by dm17** [comment]
It seems difficult to get any replies to new threads in the community forum. I think my question here is simple/clear and could help others in the future @ldez
