### ISSUE TITLE
traefik proxy grpc 500 error

### ISSUE THREAD

**Issue by cccfs** [traefik/traefik#8117]
traefik version: 2.4.8
services annotations: traefik.ingress.kubernetes.io/service.serversscheme: "h2c"

![image](https://user-images.githubusercontent.com/73505347/117249533-4dd24f80-ae74-11eb-9594-b051b70b8363.png)

account logs:
```
{"ClientHost":"172.100.78.0","DownstreamStatus":500,"Duration":1539653,"OriginDuration":1346004,"OriginStatus":500,"Overhead":193649,"RequestContentSize":0,"RequestHost":"grpc1.deeproute.cn","RequestMethod":"GET","RequestPath":"/","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RouterName":"project-go-http-demo-go-http-demo-grpc-8d3e270ee3bccc0e439f@kubernetescrd","ServiceAddr":"172.100.247.216:50051","ServiceName":"project-go-http-demo-go-http-demo-grpc-8d3e270ee3bccc0e439f@kubernetescrd","ServiceURL":{"Scheme":"h2c","Opaque":"","User":null,"Host":"172.100.247.216:50051","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"entryPointName":"http","level":"info","msg":"","request_User-Agent":"curl/7.58.0","request_X-Forwarded-Proto":"http","time":"2021-05-06T06:02:44Z"}
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by cccfs** [comment]
slove
