### ISSUE TITLE
Traefik IngressRouteTCP support for Middlewares

### ISSUE THREAD

**Issue by nicholasnovakovic** [traefik/traefik#8119]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

IngressRouteTCP on Kubernetes does not support middleware integration.

Currently one of my company's use cases involves exposing TCP ports on public IP addresses, but we require IP whitelisting for security. 

I think that although not all the middlewares are applicable to TCP routers, it would be great to support some of them (such as the ip whitelist middleware).

**Comment by jbdoumenjou** [comment]
Hello @nicholasnovakovic,

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #6684.

Thank you for your contribution.

**Comment by nicholasnovakovic** [comment]
Couldn't find it previously, thanks so much :-)
