### ISSUE TITLE
Unclear error message: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by funkyfuture** [traefik/traefik#8122]
in [this post](https://community.traefik.io/t/hitting-a-500-internal-server-error-caused-by-unsupported-protocol-scheme-with-a-file-config/10537) in the Community forums i described a situation where http requests are responded with a 500 and the message `unsupported protocol scheme`. i meanwhile came to the conclusion that this is a bug because the message isn't helpful by pointing the user to the causing misconfiguration (which is guess is the case, as i could rule out other causes in the stack), maybe it is even misleading.

please let me know if i should copy the contents from the post here.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
