### ISSUE TITLE
Name-based Virtual Host Support to access backend URL

### ISSUE THREAD

**Issue by rinshadka** [traefik/traefik#8134]
Tried proxy passing first.domain.com to second.domain.com domain using the below traefik toml entries. But facing issues to Name-based Virtual Hosted urls.

While trying, the request wont reach properly to backend url if the url configured at destination is nginx virtual host , but instead traefik forwards requests to default site in that nginx configuration.

This setup works fine if we point the backend url to a service listening in port http://<BACKEND_SERVER_IP>:<BACKEND_SERVER_PORT>

traefik.toml entry below:-

```
[backends]
[backends.postgrest]
    [backends.postgrest.servers]
        [backends.postgrest.servers.server0]
        url = "https://second.domain.com"

[frontends.domain]
  entryPoints = ["https"]
  backend = "postgrest"
  passHostHeader = true
  [frontends.domain.routes]
    [frontends.domain.routes.route0]
    rule = "Host:first.domain.com"
```

Tried with traefik version 1.7 and version 2.2

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
