### ISSUE TITLE
Middlewares broken with normal Ingress

### ISSUE THREAD

**Issue by 205g0** [traefik/traefik#8135]
Your docs doesn't make this clear. I just changed from `IngressRoute` to `Ingress` and middlewares are not working anymore. Is this intended, if yes it would helpful if this was stated in the docs (that middlewares are just for `IngressRoute`). Hope I am wrong.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
