### ISSUE TITLE
Kubernetes provider fails when a secret is referenced which contains DER encoded TLS data. 

### ISSUE THREAD

**Issue by jr0d** [traefik/traefik#8142]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Created a secret containing a key and certificate encoded in DER format. Then reference this secret in an ingress resource to provide TLS configuration. 

### What did you expect to see?
As traefik only seems to support PEM formatted x509 certificates and keys; I would expect to see the ingress not be configured properly. Perhaps, an error message and a warning about the ingress not being properly configured for TLS. 

### What did you see instead?
Once the DER encoded TLS secret is referenced by the bad ingress, the provider will fail to reconcile all state changes in the cluster with the runtime configuration. This manifest first with a parser error:

```
{"level":"error","msg":"Near line 31937 (last key parsed 'tls.certificate.certFile'): unexpected EOF","time":"2021-04-30T19:08:09Z"}
```
This is causes `nil` to be passed from loadConfig here: 

https://github.com/traefik/traefik/blob/a0d8ee5a0252205e378a9a80d7ddc54483a5f03c/provider/kubernetes/kubernetes.go#L488-L495

The failure occurs here:

https://github.com/traefik/traefik/blob/v1.7/provider/kubernetes/kubernetes.go#L823-L831

Where the binary data is encoded as a string and then injected into the toml document. Subsequent calls to load the configuration from the template data fail. 

This condition will persist until the faulty tls data is removed or the service is restarted. However, all reconciliation of ingress, services, endpoints, and secrets will continue to fail.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.24
Codename:     maroilles
Go version:   go1.14.1
Built:        2020-03-25_04:34:11PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by traefiker** [comment]
Closed by #8624.
