### ISSUE TITLE
RSS memory increases over time when using maxIdleConnsPerHost = -1

### ISSUE THREAD

**Issue by theleszke** [traefik/traefik#8145]
### What did you do?
I used `maxIdleConnsPerHost = -1` to disable keep-alive connections as mentioned here: https://github.com/containous/traefik/issues/3237#issuecomment-514178590
Traefik's  RSS memory keeps increasing when following config is set:

[serversTransport]
  maxIdleConnsPerHost = -1

Memory increases with incoming traffic. On a fairly busy server ( 100 req/s) it takes about 10 days to fill 7GB. Interestingly service never reached OutOfMemory state but instead, was operating on a tiny limit of available free memory.  I tested `GODEBUG=madvdontneed=1` to double check that it isn't problem with lazy memory releasing.
The same traffic served with `maxIdleConnsPerHost = 50` occupies 280kB of RSS. 

### What did you expect?
Memory consumption at a steady level.
 
### What did you see instead?
Memory constantly growing

### Output of `traefik version`: 
```Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64```

**Comment by dtomcej** [comment]
Hello @theleszke,

Thanks for your interest in Traefik!

Could you provide a minimal reproducible case and/or complete logs/pprof showing the memory usage?

If this is easily reproducible, it would assist us in coming up with a solution.

Thanks!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
