### ISSUE TITLE
Traefik v2 Kubernetes Ingress Controller doesn't update Ingress resource status

### ISSUE THREAD

**Issue by joejulian** [traefik/traefik#8162]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

With Traefik 2.4.8 installed, I installed a helm chart that creates an ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    meta.helm.sh/release-name: kubernetes-dashboard
    meta.helm.sh/release-namespace: kommander
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User,Authorization,Impersonate-User,Impersonate-Group
    traefik.ingress.kubernetes.io/auth-type: forward
    traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth.kommander.svc.cluster.local:4181/
    traefik.ingress.kubernetes.io/priority: "2"
    traefik.ingress.kubernetes.io/router.middlewares: kommander-stripprefixes@kubernetescrd,kommander-forwardauth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  creationTimestamp: "2021-05-27T23:36:32Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-dashboard
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: kubernetes-dashboard-4.0.3
    helm.toolkit.fluxcd.io/name: kubernetes-dashboard
    helm.toolkit.fluxcd.io/namespace: kommander
  name: kubernetes-dashboard
  namespace: kommander
  resourceVersion: "908149"
  uid: 36633768-0f3a-4ccd-8001-81cfa7f572b3
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 9090
        path: /dkp/kubernetes
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

When the service that provides the AWS ELB LoadBalancer to Traefik is updated with the assigned external-ip/hostname, the address/hostname is not propogated through to the ingress records that would be serviced by that ELB. This breaks behavior where applications external to the cluster query the ingress record in order to find the address or hostname they need to connect to.

This cannot be configured through the command line as the address and hostname are not available until after the helm chart has been installed and AWS has assigned them. If the command line option is set with a dummy address, ie `--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1`, it is never updated with the true ELB information.

### What did you expect to see?
When the service providing the LoadBalancer has its `status.loadBalancer.ingress.ip` or `status.loadBalancer.ingress.hostname` set, I expect those to be propogated to the associated ingress records.

### What did you see instead?
The ingress loadbalancer map remains unchanged.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      2.4.8
Codename:     livarot
Go version:   go1.16.2
Built:        2021-03-23T15:48:39Z
OS/Arch:      linux/amd64
```

from container image: `traefik:2.4.8`

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

This is the [helm chart](https://github.com/traefik/traefik-helm-chart/tree/v9.19.1) values:
```yaml
access:
  enabled: true
additionalArguments:
- --serversTransport.insecureSkipVerify=true
- --metrics.prometheus=true
deployment:
  podLabels:
    app: traefik
    kommander.mesosphere.io/name: traefik
  replicas: 2
ingressRoute:
  dashboard:
    annotations:
      kubernetes.io/ingress.class: traefik
    enabled: true
    labels: {}
logs:
  access:
    enabled: true
  general:
    level: WARNING
pilot:
  dashboard: false
podDisruptionBudget:
  minAvailable: 1
providers:
  kubernetesCRD:
    enabled: true
    namespaces: []
  kubernetesIngress:
    enabled: true
    namespaces: []
    publishedService:
      enabled: false
```

I also tried adding `--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1` per https://github.com/traefik/traefik/issues/6303 but they just all get 127.0.0.1 and stay there.

**Comment by joejulian** [comment]
Discovered the publishedService key. This could probably be documented better as it didn't make its use clear.

**Comment by maelvls** [comment]
Note that it only works if you have an Ingress with the apiVersion `networking.k8s.io/v1beta1` (and maybe `extensions/v1beta1` too), but it won't work with `networking.k8s.io/v1` (see https://github.com/traefik/traefik/issues/7466)

**Comment by joejulian** [comment]
It'll still work up to 1.22. The v1 resource is still available through the old APIs.

**Comment by maelvls** [comment]
> It'll still work up to 1.22. The v1 resource is still available through the old APIs.

By `v1`, you mean `networking.k8s.io/v1`? I might be mistaken but it looked like my `networking.k8s.io/v1` ingresses wouldn't get their `status.loadBalancer.ip` updated at all
