### ISSUE TITLE
Namespace support for Consul Catalog provider

### ISSUE THREAD

**Issue by Lucretius** [traefik/traefik#8171]
### Consul namespace support

The Consul Catalog provider works very well for a Consul cluster with a single namespace.  However, in a more complex Consul cluster, with multiple namespaces, Traefik only looks at the default namespace and ignores the others.  It would be great to add support for Consul namespaces in the Consul Catalog provider.

**Comment by jbdoumenjou** [comment]
Hello @Lucretius,

Thanks for your interest in Traefik.
As a side note, to use the Namespace on service, the consul client library must be updated.
