### ISSUE TITLE
Compress middleware: add option to configure the minimum body size

### ISSUE THREAD

**Issue by antonin-arquey** [traefik/traefik#8197]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A configurable option to configure the minimum body size for the [compress middleware](https://doc.traefik.io/traefik/middlewares/compress/). 

For example: 
```
[http.middlewares]
  [http.middlewares.test-compress.compress]
    minimumBodySizeBytes = 5000
```

**Comment by lus** [comment]
Hello ^^

I would love to get into contributing to traefik and this seems like a nice issue to start with.
Would it be possible for me to give it a try?

**Comment by dtomcej** [comment]
Hello @lus,

If you would like to give it a go, please open a PR! The community is always welcome to contribute.

You can find the contribution guides and information here: (https://doc.traefik.io/traefik/contributing/thank-you/)

**Comment by lus** [comment]
Alright, I'll open a PR tomorrow.
Thanks for your reply :D
