### ISSUE TITLE
Kubectl Read Secret TLS For Dynamic Configuration

### ISSUE THREAD

**Issue by dev852com** [traefik/traefik#8214]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Generated secret from cert-manager, clusterissuer and certificate.

Helm3 Traefik Chart works. Dynamic Configuration does not have the option to read secrets.

**Comment by dtomcej** [comment]
Hello @dev852com,

Can you elaborate on what you mean?

Both ingress and ingressRoute objects have TLS secret fields to allow secrets to be used.

**Comment by dev852com** [comment]
Hello @dtomcej 

Please see configuration below:

values.yml
`
persistence:
  enabled: true
  name: data
  existingClaim: "traefik"
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: "manual"
  path: /data

additionalArguments:
  - --api.insecure
  - --api.dashboard=true
  - --log.level=INFO
  - --providers.kubernetesingress.ingressclass=traefik-cert-manager
  - --providers.file.directory=/data/
  - --providers.file.filename=/data/routes.yal
  - --providers.file.watch=true 
  # - --configFile=/data/traefik.yml
  - --serversTransport.insecureSkipVerify=true
`

routes.yml
`
http:
  routers:
    app-http:
      entryPoints:
      - web
      middlewares:
      - https-redirect
      rule: "Host(`example.com`)"
      service: app
    app-https:
      entryPoints:
      - websecure
      rule: "Host(`example.com`)"
      service: app
      **tls:**  # Does not have get tls from secret option

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://proxy.lxd"

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
`

Can we please add get tls from kubectl secrets? Thank you

**Comment by dtomcej** [comment]
Hello @dev852com,

The file provider is only file based, and does not have visibility outside of the config files themselves.

If you want to use secrets in a kubernetes environment, you have to mount them as volumes, and then reference the mounted certificate files as in the documentation. Thanks!

If you would like to discuss further, please feel free to open a thread on our [community forum](https://community.traefik.io/).
