### ISSUE TITLE
list of available provider name

### ISSUE THREAD

**Issue by WLun001** [traefik/traefik#8220]
### Do you want to request a *feature* or report a *bug*?

Feature (docs enhancement)

### What did you expect to see?
Add providers name in the [supported provider table](https://doc.traefik.io/traefik/providers/overview/#supported-providers) for [referencing dynamic configuration object](https://doc.traefik.io/traefik/providers/overview/#provider-namespace)

For example 
https://github.com/traefik/traefik/blob/ce2e02b6904329d4c62a2f04e2707869ea525271/pkg/provider/file/file.go#L23

https://github.com/traefik/traefik/blob/ce2e02b6904329d4c62a2f04e2707869ea525271/pkg/provider/kubernetes/crd/kubernetes.go#L38

**Comment by traefiker** [comment]
Closed by #8225.
