### ISSUE TITLE
Possible bug related with CORS when docker container is unreachable

### ISSUE THREAD

**Issue by gulando** [traefik/traefik#8229]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have traefik as a proxy server and  also my web-api  that responsible for some rest calls. 
My  problem is related when I try to add CORS headers in my traefik configuration. When I shut down my web-api I am getting CORS error in my browser network page although  I have added CORS headers. using docker-compose.yml as described in your documentation.

I used this documentation to add headers   https://doc.traefik.io/traefik/v2.2/middlewares/headers/

I also read this  https://github.com/traefik/traefik/issues/6278, but don't understand what do you mean when say  "a middleware need to be applied on a router".

And this also doesn't help me.  https://github.com/traefik/traefik/issues/2549

I added CORS headers  both traefik docker  configuration and web-api docker configuration, the same result. Mu OS version is  Ubuntu 18.04 

This I have added in my web-api(container name webapi) docker-compose.yml file

```
version: '3.6'
services:
webapi:
labels: 
           traefik.http.middlewares.webapi.headers.accesscontrolallowcredentials: "true"
           traefik.http.middlewares.webapi.headers.accesscontrolallowheaders: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolallowmethods: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolalloworiginlist: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolalloworigin: "*"
```

and this in my traefik docker-compose.yml file.
```
version: '3.6'
services:
proxy:
image: traefik:2.3.0
labels:
           traefik.http.middlewares.webapi.headers.accesscontrolalloworiginlist: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolallowheaders: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolallowmethods: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolalloworiginlist: "*"
           traefik.http.middlewares.webapi.headers.accesscontrolalloworigin: "*"
```

Also I have tried add labels as you mentioned in your doc, but also without any success.
```
`labels:
  - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=*"
  - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
  - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
  - "traefik.http.middlewares.testheader.headers.addvaryheader=true"`
```

### What did you see instead?

I expect see 502 or something related with bad gateway.

### What version of Traefik are you using?

2.2.0/2.3.0

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
