### ISSUE TITLE
Dynamic aggregated ipwhitelists

### ISSUE THREAD

**Issue by eugenekuhn** [traefik/traefik#8244]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Scenario:

We have multiple ipwhitelist's defined (say `vpn-whitelist@docker, external-services-whitelist@docker, gitlab-whitelist@docker` ) and we would like a way to dynamically create an aggregated whitelist. Chaining it in the middleware will obviously not work (as per other requests)

Suggestion.
Is it possible to change the behavior of defining ipwhitelist sourceranges on the fly
ie 
`traefik.http.middlewares.whitelist-custom-servicename.ipwhitelist.sourcerange=127.0.0.1/32,172.0.0.0/8,vpn-whitelist@docker,10.10.0.0/16,gitlab-whitelist@docker`
or 
`traefik.http.middlewares.whitelist-custom-servicename.ipwhitelist.sourcerange=127.0.0.1/32,172.0.0.0/8,vpn-whitelist.sourcerange,10.10.0.0/16,gitlab-whitelist.sourcerange`

**Comment by jbdoumenjou** [comment]
Hello @eugenekuhn,

We've looked at your issue, and we found an existing issue that deals with this subject.
Therefore, we will close this issue as a duplicate in favor of #7720.
