### ISSUE TITLE
Unable to install Traefik from main repo using helm install !

### ISSUE THREAD

**Issue by llynskey** [traefik/traefik#8249]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

helm repo add traefik https://helm.traefik.io/traefik

helm repo update

helm install traefik traefik/traefik

### What did you see instead?

Error: failed to install CRD crds/ingressroute.yaml: error parsing : json: line 0: invalid character '{' looking for beginning of object key string

### What version of Traefik are you using?

latest version on helm repo. Following standard install instructions.

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by RaJiska** [comment]
The issue has been reported here https://github.com/traefik/traefik-helm-chart/issues/441

**Comment by jbdoumenjou** [comment]
Already opened in helm chart repository.
