### ISSUE TITLE
Traefik consume lots of RAM and CPU power, k3s hangs. Occurred after setting the externalName

### ISSUE THREAD

**Issue by kappa-wingman** [traefik/traefik#8257]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Traefik process for k3s consumed lots of CPU and RAM, it occurred after applying below file.
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-http-analytics
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`analytics.kappawingman.com`)
      services:
        - name: extsvc-http-analytics
          port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: extsvc-http-analytics
  namespace: default
spec:
  type: ExternalName
  externalName: 10.15.0.12
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 2443
```

### What did you see instead?

I did not find specific problem from the system logs.

I do not know if the problem is Traefik or K3S.
[I also opened a bug report for K3S is in here](https://github.com/k3s-io/k3s/issues/3598)

### What version of Traefik are you using?

Traefik 2.4.8 (embedded) with k3s version v1.21.2+k3s1 (5a67e8dc)

### What is your environment & configuration?

**Environmental Info:**
k3s version v1.21.2+k3s1 (5a67e8dc)

Node(s) CPU architecture, OS, and Version: 
Linux control01 5.4.17-2102.202.5.el8uek.aarch64 #2 SMP Sat May 22 16:34:31 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
One single master node, three worker nodes
They are running in SELinux permissive mode.
Traefik v2.4.8
All components are from K3s except I just installed OpenEBS with Helm.

**Describe the bug:**
Traefik process would consume CPU and RAM, system slow down.
Kubectl command to the k3s cluster is not responsive.

The problem only occurred on the master node after below setting is
applied. It happened immediately when I try to access the URL manually.

**Steps To Reproduce:**

- Installed K3s:
The nodes need to access http proxy for fetching package from internet.
So the k3s.env has configured HTTP(S)_PROXY. http(s)_proxy and NO_PROXY environment variable.

```
http_proxy=http://server02:8008
https_proxy=http://server02:8008
HTTP_PROXY=http://server02:8008
HTTPS_PROXY=http://server02:8008
NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.15.0.0/23,10.42.0.0/15,.svc,.svc.cluster,.cluster.local,.svc.cluster.local
```

After the proxy setting is applied, when I access the HTTP port of analytics.kappawingman.com, the connection is made to one of the worker node port 80. However, the traefik process on the master node would consume lots of memory and CPU and I can't run any kubectl commands. For the externalName, the IP is not the master node, it is another node.

This process consumed lots of memory and CPU. I had to kill this process manually in the host.
```
traefik traefik --global.checknewversion --global.sendanonymoususage --entryPoints.traefik.address=:9000/tcp --entryPoints.web.address=:8000/tcp --entryPoints.websecure.address=:8443/tcp --api.dashboard=true --ping=true --providers.kubernetescrd --providers.kubernetesingress --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik --entrypoints.websecure.http.tls=true
```

I try to find the traefik process on the master node. I think this is the related container (the restart timestamp matches the time when I kill the process). I had to use --previous because I can't run it when the problem occurred.
```
# kubectl logs --previous -n kube-system traefik-97b44b794-mj9xg 

time="2021-07-08T12:07:47Z" level=info msg="Configuration loaded from flags."
W0708 12:07:47.764377       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0708 12:07:47.770908       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0708 12:07:47.909534       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
W0708 12:07:47.929629       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
W0708 12:14:41.767814       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0708 12:15:07.912699       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
```

This is the log of the pod after it is manuall restarted.
```
# kubectl logs -n kube-system traefik-97b44b794-mj9xg 

time="2021-07-08T12:19:16Z" level=info msg="Configuration loaded from flags."
W0708 12:19:17.009585       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0708 12:19:17.028958       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0708 12:19:17.149207       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
W0708 12:19:17.169306       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
W0708 12:26:37.152393       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
W0708 12:28:21.013353       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

This is the pod list
```
# kubectl get pods -A
NAMESPACE     NAME                                          READY   STATUS             RESTARTS   AGE
kube-system   helm-install-traefik-crd-v75n6                0/1     Completed          0          18h
kube-system   helm-install-traefik-pn97n                    0/1     Completed          0          18h
kube-system   svclb-traefik-248vr                           2/2     Running            0          17h
openebs       openebs-admission-server-66bf9476b4-snxhs     1/1     Running            0          16h
openebs       openebs-ndm-rxdj8                             1/1     Running            0          14h
openebs       openebs-ndm-cdjb2                             1/1     Running            0          14h
kube-system   svclb-traefik-rb9sc                           2/2     Running            0          18h
kube-system   metrics-server-86cbb8457f-svxhn               1/1     Running            1          40h
openebs       openebs-ndm-9f7xv                             1/1     Running            1          14h
kube-system   svclb-traefik-w8jnc                           2/2     Running            3          40h
kube-system   svclb-traefik-nhnzg                           2/2     Running            0          19h
openebs       openebs-ndm-g7hwc                             1/1     Running            0          14h
openebs       openebs-ndm-operator-6f584b9bdd-jtpjv         1/1     Running            0          14h
openebs       openebs-snapshot-operator-76b899b7c5-dd8t7    2/2     Running            21         16h
kube-system   coredns-7448499f4d-4lhxq                      1/1     Running            5          40h
kube-system   local-path-provisioner-5ff76fc89d-k9lt2       1/1     Running            9          40h
openebs       openebs-localpv-provisioner-965cfd6b9-dp8tt   1/1     Running            27         16h
openebs       openebs-provisioner-855f4d7598-qk5bz          1/1     Running            27         16h
kube-system   traefik-97b44b794-mj9xg                       1/1     Running            9          40h
openebs       openebs-apiserver-6bf964d6d4-np6zg            0/1     CrashLoopBackOff   184        16h
``` 

The last container doesn't seem to related to the problem. It don't have
internet connection and seems to be restarting a while after it is restarted
```
I0708 12:25:46.908409       1 start.go:288] resources applied successfully by installer
I0708 12:25:46.925852       1 start.go:193] Maya api server configuration:
I0708 12:25:46.926009       1 start.go:195]          Log Level: INFO
I0708 12:25:46.926418       1 start.go:195]             Region: global (DC: dc1)
I0708 12:25:46.926482       1 start.go:195]            Version: 2.10.0-released
I0708 12:25:46.926532       1 start.go:201]
I0708 12:25:46.926571       1 start.go:204] Maya api server started! Log data will stream in below:
I0708 12:25:46.930600       1 runner.go:37] Starting SPC controller
I0708 12:25:46.930700       1 runner.go:40] Waiting for informer caches to sync
I0708 12:25:47.030863       1 runner.go:45] Checking for preupgrade tasks
I0708 12:25:47.034235       1 runner.go:51] Starting SPC workers
I0708 12:25:47.034363       1 runner.go:58] Started SPC workers
E0708 12:25:50.962149       1 googleanalytics.go:49] Post "https://www.google-analytics.com/collect": dial tcp: lookup www.google-analytics.com on 10.43.0.10:53: server misbehaving
I0708 12:28:46.165185       1 start.go:331] Caught signal: terminated
I0708 12:28:46.165216       1 start.go:362] Gracefully shutting maya api server...
2021/07/08 12:28:46.165227 [INFO] maya api server: exiting gracefully
2021/07/08 12:28:46.165234 [DEBUG] http: Shutting down http server
2021/07/08 12:28:46.165265 [INFO] maya api server: requesting shutdown
2021/07/08 12:28:46.165266 [INFO] maya api server: shutdown complete
```

**Expected behavior:**
It should not consume lots of CPU and RAM it should return error message.

**Actual behavior:**
Lots of RAM and CPU is consumed by the traefik process.

**Additional context / logs:**
I didn't notice any special problem from log in /var/log/messages

**Comment by dtomcej** [comment]
Hello @kappa-wingman,

It sounds like you are encountering a redirect loop somewhere.

Can you enable the debug log and try again? If you are encountering a redirect loop, the debug log should be spammed with the same loop, demonstrating where it is being encountered.

**Comment by kappa-wingman** [comment]
Here's the info from traefik debug log, I trigger the access to Traefik from remote location by wget.
Some info like IP/country are redcated.

```
time="2021-07-08T15:29:54Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Me
thod\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"
ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\
"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip\"],\"Cdn-Loop\":[\"cloudflare\"],\"Cf-Con
necting-Ip\":[\"11.22.33.44\"],\"Cf-Ipcountry\":[\"XX\"],\"Cf-Ray\":[\"66ba57f8ff4b204d-NRT\"],\"Cf-Visitor\":[\"{\\
\"scheme\\\":\\\"http\\\"}\"],\"Connection\":[\"Keep-Alive\"],\"User-Agent\":[\"Wget/1.21.1\"],\"X-Forwarded-Host\":[\
"analytics.kappawingman.com\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[
\"traefik-7497ddffbd-6zvw8\"],\"X-Real-Ip\":[\"10.42.3.0\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"
analytics.kappawingman.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"
10.42.3.0:24459\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2021-07-08T15:29:55Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetescrd
time="2021-07-08T15:29:55Z" level=debug msg="Skipping Kubernetes event kind *v1.Endpoints" providerName=kubernetes
```

Those message with 'Skipping Kubernetes event' appeared before I access the location. When I access the location, The debug log is flooded with similar message like first line but the port in RemoteAddr (10.42.3.0) is slightly different.

Finally, the client side received an 'ERROR 502: Bad Gateway response'.
Thanks.

**Comment by dtomcej** [comment]
Hello @kappa-wingman,

Oxy generates 3 log entries:
- A begin ServeHTTP entry;
- A Forwarding request to URL entry; and
- A completed ServeHTTP entry.

The one we are interested is the 2nd/middle one (`vulcand/oxy/roundrobin/rr: Forwarding this request to URL`)

**Comment by kappa-wingman** [comment]
I think it's the log that you want:

time="2021-07-08T15:59:10Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip\"],\"Cdn-Loop\":[\"cloudflare\"],\"Cf-Connecting-Ip\":[\"11.22.33.44\"],\"Cf-Ipcountry\":[\"XX\"],\"Cf-Ray\":[\"66ba84a2a8691aa8-SIN\"],\"Cf-Visitor\":[\"{\\\"scheme\\\":\\\"http\\\"}\"],\"User-Agent\":[\"Wget/1.21.1\"],\"X-Forwarded-Host\":[\"analytics.kappawingman.com\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-7497ddffbd-6zvw8\"],\"X-Real-Ip\":[\"10.42.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"analytics.kappawingman.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.1.1:8233\",\"RequestURI\":\"/\",\"TLS\":null}"

time="2021-07-08T15:59:10Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip\"],\"Cdn-Loop\":[\"cloudflare\"],\"Cf-Connecting-Ip\":[\"11.22.33.44\"],\"Cf-Ipcountry\":[\"XX\"],\"Cf-Ray\":[\"66ba84a2a8691aa8-SIN\"],\"Cf-Visitor\":[\"{\\\"scheme\\\":\\\"http\\\"}\"],\"User-Agent\":[\"Wget/1.21.1\"],\"X-Forwarded-Host\":[\"analytics.kappawingman.com\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-7497ddffbd-6zvw8\"],\"X-Real-Ip\":[\"10.42.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"analytics.kappawingman.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.42.1.1:8233\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://10.15.0.12:80"

If I am correct, when it has problem, the completed ServeHTTP entry (last entry) does not immediately followed after the first two entries. Usually when I killed process, the completed Serve HTTP entry was displayed. Due to k8s/debug log, it seems it had a buffer and I am unable to get the 3 log entries of the same HTTP/request transaction.

**Comment by dtomcej** [comment]
It appears that Traefik is forwarding to `http://10.15.0.12:80` because externalname services don't have a targetPort (since there isnt a good reason to do port translation on an externalname service), the service port is returned here: https://github.com/traefik/traefik/blob/master/pkg/provider/kubernetes/crd/kubernetes.go#L367 and used here:
https://github.com/traefik/traefik/blob/master/pkg/provider/kubernetes/crd/kubernetes_http.go#L331

Since the internal service port is not connected to the entrypoint port used by Traefik, can you try this instead:

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-http-analytics
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`analytics.kappawingman.com`)
      services:
        - name: extsvc-http-analytics
          port: 2080

---
apiVersion: v1
kind: Service
metadata:
  name: extsvc-http-analytics
  namespace: default
spec:
  type: ExternalName
  externalName: 10.15.0.12
  ports:
    - name: http
      protocol: TCP
      port: 2080
    - name: https
      protocol: TCP
      port: 2443
 ```

**Comment by kappa-wingman** [comment]
@dtomcej  Your setting works. Thanks for the help.

But the correct setting is not intuitive (for me).
```
      services:
        - name: extsvc-http-analytics
          port: 2080
```
It should be a K8S problem, not directly a Traefik problem.

**Comment by dtomcej** [comment]
Hello @kappa-wingman,

Great to hear that the settings worked for you. Since this was a configuration issue, I will close this issue.

Thanks!
