### ISSUE TITLE
Undocumented Docker Compose support

### ISSUE THREAD

**Issue by grugnog** [traefik/traefik#8272]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

When starting containers with docker compose the hostname (when using the defaultRule with `normalize .Name`) will follow the pattern `docker_compose_service_name-container_name.server_hostname.com`, even when the service [has a specific container_name specified](https://github.com/compose-spec/compose-spec/blob/master/spec.md#container_name).

### What did you see instead?

I would expect the hostname to follow the pattern `container_name.server_hostname.com` as is the case for containers started using `docker --name ...`.

I think this is essentially a documentation bug - Traefik is looking at Docker Compose labels and adding prefixes to the `.Name` prior to the templating. This causes confusion (e.g. #8265) since it is unclear why the name does not follow the documented pattern.

Long term it would be nice to make this configurable - perhaps by making the service name a separate value and adding that to the default (rather than hard coding it into `.Name`.

### What version of Traefik are you using?

2.4.11

### What is your environment & configuration?

```yaml
...
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: 'Host(`{{ normalize .Name }}.server_hostname.com`)'
    network: web
```

Add more configuration information here.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
