### ISSUE TITLE
Frontend: 2.5.0-rc2 not displaying middleware details

### ISSUE THREAD

**Issue by jkreileder** [traefik/traefik#8276]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

After upgrading from v2.4.9 to 2.5.0-rc2 HTTP middleware pages don't show details. The usual details are in the answers to .../api/http/middlewares/<middleware>, they just don't get displayed in the page.

### What did you see instead?

<img width="962" alt="Screen Shot 2021-07-17 at 20 08 28" src="https://user-images.githubusercontent.com/4390544/126046128-749c99f7-d7b4-4eff-9ef9-8820ff4c357f.png">

### What version of Traefik are you using?

2.5.0-rc2

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by traefiker** [comment]
Closed by #8284.
