### ISSUE TITLE
v2.5-rc3 Consul Connect - Router defined multiple times with different configurations error

### ISSUE THREAD

**Issue by microadam** [traefik/traefik#8293]
- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What happened?

Hello.

Running v2.5-rc3 and attempting to use the new consul connect functionality with this nomad job:

```
job "sample" {
  datacenters = ["cluster"]

  group "kitchen-clock" {
    network {
      mode = "bridge"
    }

    service {
      name = "clock"
      port = "3333"
      tags = [
        "traefik.enable=true",
        "traefik.connect=true",
        "traefik.http.routers.clock.rule=Host(`sample.mydomain.com`)",
        "traefik.http.routers.clock.tls=true"
      ]
      connect {
        sidecar_service {}
      }
    }

    task "server" {
      driver = "docker"
      config {
        image = "shoenig/simple-http:v1"
        args  = ["server"]
      }
      env {
        BIND = "0.0.0.0"
        PORT = 3333
      }
    }
  }
}
```
Once the job starts running, inside traefik I have two HTTP Services:
```
clock@consulcatalog
clock-sidecar-proxy@consulcatalog
```
I also have no routers. However in the logs I get:
```
Router defined multiple times with different configurations in [ubuntu-8gb-fft1-2-clock-nomad-task-bf3767c4-7fb7-ae16-6a84-baa541575ac7-group-kitchen-clock-clock-3333 ubuntu-8gb-fft1-2-clock-sidecar-proxy-nomad-task-bf3767c4-7fb7-ae16-6a84-baa541575ac7-group-kitchen-clock-clock-3333-sidecar-proxy]" providerName=consulcatalog routerName=clock
```

### What did you expect?

I reverted to an older version of the consul connect feature that I had previously been testing with (commit hash 8007d17b3) and everything worked as it should. No "sidecar-proxy" service started and the HTTP router that I expected appeared and no errors in the logs.

### What version of Traefik are you using?

Version:      2.5.0-rc3
Codename:     brie
Go version:   go1.16.6
Built:        2021-07-20T14:56:19Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
[entryPoints]
    [entryPoints.http]
      address = ":80"
      [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entryPoint]
          to = "https"
    [entryPoints.https]
      address = ":443"
    [entryPoints.traefik]
      address = ":8081"

[api]
    dashboard = true
    insecure  = true

[accessLog]

[log]
  level = "DEBUG"

[providers.file]
  filename = "/etc/traefik/dynamic_conf.toml"

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
    prefix = "traefik"
    exposedByDefault = false
    connectAware = true

    [providers.consulCatalog.endpoint]
      address = "127.0.0.1:8501"
      scheme  = "https"
      token = "xxxx"

      [providers.consulCatalog.endpoint.tls]
        ca = "/etc/consul.d/consul-ca.pem"
        cert = "/etc/consul.d/consul.crt"
        key = "/etc/consul.d/consul.key"
```

**Comment by microadam** [comment]
@apollo13 I know you were keen to this merged having worked on it. Have you managed to get this working when running RC3 of v2.5 at all?

**Comment by ldez** [comment]
Hello,

the label is `traefik.consulcatalog.connect=true`

**Comment by microadam** [comment]
Hi @ldez! Thank you very much for pointing out my mistake. I obviously hadn't been keeping up with development on this closely enough, as I didn't realise this has changed so late on! That does indeed solve the problem. I will close this. Thanks again!
