### ISSUE TITLE
Documentation does not list proxy headers that are automatically added

### ISSUE THREAD

**Issue by dtomcej** [traefik/traefik#8294]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Read the documentation trying to find what headers are automatically added to proxied http requests.

### What did you see instead?

The documentation does not appear to clearly show what headers are added. Users coming from using other proxies are used to manually having to add proxy headers, which can lead to issues when they cannot find out how to do what is automatically done.

**Comment by traefiker** [comment]
Closed by #8418.
