### ISSUE TITLE
Utilize DataDog trace/metrics default configuration functionality

### ISSUE THREAD

**Issue by judgeaxl** [traefik/traefik#8297]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

From what I can tell, the DataDog trace integration is not using the auto-configuration features of the ddtrace library.

This means I can't use standard ddtrace environment variables to configure it, and I have to rely specifically on options being exposed by Traefik.

As an example, on master there's now custom code for injecting the DataDog host from the environment, but that's already done by the ddtrace default config. Priority Sampling is a deprecated setting that is now always on, and the global opentrace config is also automatically setup internally.

So my feature request is to update the datadog integration layer to take advantage of these features, thus simplifying setup for users.

I take it one would have to add any new settings that would be covered by this to the CLI and config file logic.

I imagine the same would go for the metrics integration, but I haven't actually looked into that.

If this is of interest to the project, I'm happy to give it a go with a PR.

Regarding deprecating obsolete settings entries, is there a guideline for how/if one should do that?

**Comment by dtomcej** [comment]
Hello @judgeaxl,

When you say:
> I can't use standard ddtrace environment variables to configure it

Can you give an example of a variable that you would want to use that is unsupported? We are trying to determine whether this is a feature request or a bug report.

**Comment by judgeaxl** [comment]
In the latest ddtrace module it will check `DD_AGENT_HOST`, `DD_TRACE_AGENT_PORT`, `DD_DOGSTATSD_PORT`, `DD_TRACE_ANALYTICS_ENABLED`, `DD_TRACE_REPORT_HOSTNAME`, `DD_TRACE_SOURCE_HOSTNAME`, `DD_ENV`, `DD_TRACE_FEATURES`, `DD_SERVICE`, `DD_VERSION`, `DD_TAGS`, `DD_TRACE_STARTUP_LOGS`, and `DD_RUNTIME_METRICS_ENABLED`.

Only the two first ones are configurable through Traefik today and I can't feed them in without modifying Traefik, since it's not using the `newConfig()` methods which is grabbing these out of the environment. All of the mentioned environment variables have corresponding `WithOptionName` methods too. 

Additionally, WithPrioritySampling is no longer needed, and will be ignored (always set to true internally).

Finally the `opentracing.SetGlobalTracer(tracer)` call is also done internally as the tracer is started.

It's possible that some of these options aren't suitable in the context of Traefik, and that you prefer to have more direct control over what options are exposed to Traefik users, which is perfectly fine, and in that case I would change the feature requests to supporting at least the `version`, `tags`, `env`, and `service` settings, as those are part of the basic tags DataDog recommends for all incoming data.

**Comment by judgeaxl** [comment]
So it's really two parts to the feature request, removing some obsolete setup, and utilizing the existing code in the module over manually setting things up, and the other is to add support for more settings, and the subset of settings is up for debate, but at least service, version, env, and tags would be very useful for me personally.

**Comment by rtribotte** [comment]
Hello @judgeaxl,

Looking at the code of the datadog tracer initialization, it looks like this is the setup of an opentracing tracer.
So, Traefik supports datadog tracer through the opentracing tracer implementation.

I understand that you ask that this must be done instead with the actual code of the datadog tracer (`Start` func), which would set the defaults configuration values through the environment variables.

Thus, by taking a look at the datadog ddtrace library, it only relies on the following environment variables: `DD_AGENT_HOST`, `DD_DOGSTATSD_PORT`, `DD_TRACE_REPORT_HOSTNAME` and `DD_LOGGING_RATE`.

So it seems that Traefik only lacks potential configuration from `DD_TRACE_REPORT_HOSTNAME` and `DD_LOGGING_RATE`.

Regarding metrics, the datadog client is based on go-kit, so I'm not sure about the changes that would be needed for that.

I wonder about the environment variables you want to use.
Can you please elaborate on your needs?

**Comment by judgeaxl** [comment]
Thanks for looking into this @rtribotte.

To get good use of metrics and traces in DataDog, it's important to "tag" them with distinguishing "dimensions". The dimensions recommended by DataDog include "service", which I would have to be "traefik" here. "env" which is the environment, like "dev", "staging", "prod", etc. And finally "version", which would be the Traefik version in this case.

We also use plenty of other tags to help dissect the data for various purposes, "managed-by", and "part-of", to name a couple.

I can set some tags on the DataDog agent itself, but that's more of a cluster-wide setting, which gets applied to all metrics and traces, not just those from Traefik, so "service", or "version" wouldn't make sense there, nor would any other pod or deployment-specific tags.

When using polling and auto-discovery in DataDog I can also add arbitrary tags to anything, but since we're relying on Traefik to push traces and metrics in this case, the Traefik specific tags would need to come from Traefik.

Thus, "env" we can put on the agent, if we don't want any sharing on the cluster, but "service" and "version", and "tags" would have to come from Traefik, otherwise there's no way that I know of for us to add them.

Actually, "service", "env", and "version" are really just three additional "tags", but they are considered somewhat special by DataDog and used for a lot of things, so they are often configured separately for clarity.

I'll admit that most of the other settings for overriding trace configuration, ports and hosts are more esoteric, at least in my setup, I merely listed them as an example of the things that are considered by the default setup.

**Comment by rtribotte** [comment]
Hello @judgeaxl,

Thanks for the clarification regarding your usage.
The current version (v1.19.0) of the ddtrace library on which Traefik depends is not providing those features.

So I would label this issue as an enhancement which would consist in updating the ddtrace library dependency, which would allow the usage of the `DD_ENV`, `DD_SERVICE`, `DD_VERSION` environment variables (at least).

**Comment by rtribotte** [comment]
Hello,

The current dependency to dd-trace-go.v1 is on version v1.56.1 on the v2.11 branch, and the usage of the `DD_ENV`, `DD_SERVICE`, `DD_VERSION` environment variables should be possible. 
I'm closing this issue accordingly.
