### ISSUE TITLE
Filter for access log entries defined in IngressRoute

### ISSUE THREAD

**Issue by frosch95** [traefik/traefik#8324]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

It would be great if there is a way to configure the filtering of access log entries for an IngressRoute definition.

Here a short description what problem we want to solve with such a feature.

Our cluster has some services that are available for public and we have some services that are only for our ops team e.g. grafana.
We do not want the grafana requests to pollute the access.log as they aren't interesting for us, but we want all the access log entries for our public services.

Currently we use a second traefik instance for grafana and other ops services to have a clear access log for our public services.

From a resource sharing perspective it would be nicer to have one traefik handle all the requests and a solution to define filters for access log entries. As the filtering depends on the routing, the IngressRoute definition might be the correct place to implement such a feature.

**Comment by mpl** [comment]
Hi,

For one thing it would be very weird to conflate the logging responsibility within the IngressRoute definition.
And in any case, fine-grained filtering should not be the responsibility of Traefik anyway. So we advise you to do this kind of  work in post-processing, in a dedicated logging tool.
