### ISSUE TITLE
Provide ability to define custom serversTransport via CLI

### ISSUE THREAD

**Issue by IronicBadger** [traefik/traefik#8327]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I want to be able to define via labels and tags only as CLI args (not the file provider) a custom named `serversTransport` as documented [here](https://doc.traefik.io/traefik/v2.4/routing/services/#serverstransport).

This would allowed something like this `      - traefik.http.services.ubiq.loadbalancer.serversTransport=stunifi` to provide per service.

**Comment by ldez** [comment]
Hello,

The CLI is used to define the [static configuration](https://docs.traefik.io/v2.4/getting-started/configuration-overview/#the-static-configuration)  and not the [dynamic configuration](https://docs.traefik.io/v2.4/getting-started/configuration-overview/#the-dynamic-configuration).

To define a "global" serversTransport you can use any of the providers (Docker, file, ...).

You can also define your default serversTransport through the CLI:
- https://doc.traefik.io/traefik/v2.4/reference/static-configuration/cli/

**Comment by empereira** [comment]
Hello @ldez 

But can I set serversTransport per service? From your answer, this is not possible.
