### ISSUE TITLE
Unclear rate liminting behavior

### ISSUE THREAD

**Issue by quentinpraz** [traefik/traefik#8330]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I want to set up a rate limting middleware.
According to the documentation, to allow 6 requests per minute, the following configuration is needed:

![image](https://user-images.githubusercontent.com/14773116/128202438-8aa9f16a-4e36-4a55-9c45-6df344f744d0.png)

https://doc.traefik.io/traefik/middlewares/ratelimit/#period

### What did you see instead?

The example above is misleading because the real limit is not `6 requests/60 sec` but `1 request/10 sec`. From my understanding, with the above configuration, I should be able to submit 5 simultaneous requests without being blocked, however it is not the case.
If it is the expected behavior, the example should be changed.

### What version of Traefik are you using?

Version:      2.4.13
Codename:     livarot
Go version:   go1.16.6
Built:        2021-07-30T15:06:29Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```yaml
[...]
labels:

     - traefik.http.middlewares.xyz.ratelimit.average=6
     - traefik.http.middlewares.xyz.ratelimit.period=1m
     - traefik.http.routers.abc.middlewares=xyz
     [...]
```

**Comment by hackervaillant** [comment]
Unclear for me as well,

Is the rate limiter working like the nginx's one using the leaky bucket algorithm ? As explained here : https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by mpl** [comment]
@quentinpraz 

1) What is it in the doc that makes you think the period is an observation period (which is indeed _not_ the case)? We do not claim such a thing, as far as I can see.

2) The configuration option you are looking for in order to achieve your example, is the burst.

@hackervaillant yes, the underlying implementation (golang.org/x/time/rate) should be inspired from the leaky bucket algorithm.
