### ISSUE TITLE
log all request headers

### ISSUE THREAD

**Issue by arrow2012** [traefik/traefik#8332]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

**Log all request headers**

traefik can only log request header by header name
But I want get all request headers just like nginx request headers( by lua)
      `       header_filter_by_lua_block {
        local cjson = require "cjson"
         local req_headers=ngx.req.get_headers()
            ngx.var.req_header =  cjson.encode(req_headers);
            ngx.var.resp_header =  cjson.encode(ngx.resp.get_headers());
       }`

**Comment by jbdoumenjou** [comment]
Hi @arrow2012,

You can configure that thanks to the access log [fields](https://doc.traefik.io/traefik/v2.4/observability/access-logs/#limiting-the-fieldsincluding-headers).

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). :smiley: 

So, I close this issue as a question.
