### ISSUE TITLE
Support for German provider all-inkl.com

### ISSUE THREAD

**Issue by abcklaus** [traefik/traefik#8337]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hi,

Please add all-inkl.com as DNS provider for Let's encrypt. This feature request was already raised in the Traefik community:

[https://community.traefik.io/t/add-all-inkl-com-dns-api/9349](https://community.traefik.io/t/add-all-inkl-com-dns-api/9349)

In the meantime the feature was implemented in lego. Any plans to move it over to Traefik?

Thanks

Michael

**Comment by ldez** [comment]
Hello,

we will update lego when the new release of lego will happen.
