### ISSUE TITLE
acme: Print attempted challenge URL to allow for failed attempt reset

### ISSUE THREAD

**Issue by snwfdhmp** [traefik/traefik#8344]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Do you want to request a feature or report a bug?
Feature / improvement (print log)

What did you do? Renewing letsencrypt SSL certificate
What did you expect to see? Line of log containing the "renewal attempt ID"
What did you see instead? Not this line
Output of traefik version: (What version of Traefik are you using?) v2.4

What is your environment & configuration (arguments, toml, provider, platform, ...)?

            - --log.level=error
            - --accesslog
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.websecure.address=:443
            - --entrypoints.traefik.address=:8080
            - --ping
            - --api.insecure
            - --providers.kubernetescrd
            - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
            - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.letsencrypt.acme.email=******@******.com
            - --certificatesresolvers.letsencrypt.acme.storage=/data/acme2.json
            - --providers.file.filename=/etc/traefik-file-provider/traefik-file-provider.yaml
            - --pilot.token=**********
            - --metrics.prometheus

## Description

Let'sencrypt limits failed attempts to 5 per hour. It also allows to reset this limit if you know the ID of the attempt. It currently isn't printed to logs.

Source : https://letsencrypt.org/docs/rate-limits/https://letsencrypt.org/docs/rate-limits/

> ### Clearing Pending Authorizations
> If you have a large number of pending authorization objects and are getting a Pending Authorizations rate limiting error, you can trigger a validation attempt for those authorization objects by submitting a JWS-signed POST to one of its challenges, as described in the ACME spec. **The pending authorization objects are represented by URLs of the form https://acme-v02.api.letsencrypt.org/acme/authz/XYZ, and should show up in your client logs**. Note that it doesn’t matter whether validation succeeds or fails. Either will take the authorization out of ‘pending’ state. If you do not have logs containing the relevant authorization URLs, you need to wait for the rate limit to expire. As described above, there is a sliding window, so this may take less than a week depending on your pattern of issuance.
>Note that having a large number of pending authorizations is generally the result of a buggy client. If you’re hitting this rate limit frequently you should double-check your client code.

**Comment by ldez** [comment]
Hello,

Traefik doesn't have the possibility to do that, the ACME behavior is handled internally by [lego](https://github.com/go-acme/lego)

In lego, if an error occurs the authorizations are automatically canceled.
