### ISSUE TITLE
TCP/UDP Middleware to redirect unsecured TCP/UDP connections

### ISSUE THREAD

**Issue by behoyh** [traefik/traefik#8353]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

TCP/UDP Middleware to redirect unsecured TCP/UDP connections from whatever is in the value to the loadbalancer IP. I can accomplish this with an external DNS.

i.e.

`- traefik.tcp.middlewares.test-redirectservice.redirect.loadbalancer: "sub.domain"`

**Comment by behoyh** [comment]
Just to clarify on this a bit, although Traefik can act like a forward proxy on http connections, this limitation makes it almost impractical to do with TCP/UDP.

**Comment by rtribotte** [comment]
Hello @behoyh,

Thanks for your interest in Traefik!

I'm sorry but I'm not sure to understand the purpose of the middleware you are describing.
What would "unsecured" connections mean at the TCP/UDP level? What are the criteria to determine that?
Also what would be the load balancer IP you are speaking of, a criterion?

Nonetheless, you are probably referring to the lack of a routing rule based on the host value for non-TLS TCP routers.
If so, a rule to match against the client IP could help to achieve more advanced routing even without TLS.
Is that something that would match/help for your use case? (We already added a new rule matcher `ClientIP` for HTTP routers, please take a look at #8169.)

If I'm not wrong, then there is no need to define a sort of load balancer through the middleware, TCP services would be sufficient.

WDYT?

**Comment by behoyh** [comment]
Hi @rtribotte! Yeah that's right, I'd like to route TCP requests without having to setup TLS.

From the docs for the HTTP client IP matcher:

```
The `ClientIP` matcher will only match the request client IP and does not use the `X-Forwarded-For` header for matching. 
```

Would this mean I could specify a `HostSNI("foo.bar")` rule for TCP connections and have that route listening for TCP? Sorry if I'm being a bit dense here.

**Comment by rtribotte** [comment]
> Would this mean I could specify a HostSNI("foo.bar") rule for TCP connections and have that route listening for TCP? Sorry if I'm being a bit dense here.

A ClientIP rule matcher for TCP routers would allow matching the remote IP.
You would be able to route specifically one or more IPs or subnets.
So I guess no, you won't be able to match a specific host.

But, for the sake of clarity, it is not possible to route based on a Host value at the TCP level.

Unfortunately, for that reason, I'll close this issue as a question.
But feel free to ask to reopen it, if you think that I missed something here.

**Comment by behoyh** [comment]
Right my use case would be a container operator creating named containers with a TCP entrypoint. So IP-based client routing won't help me there. Basically I'd like to match a container name to a route somehow over TCP.
