### ISSUE TITLE
AuthForward-Circumvention based on URL

### ISSUE THREAD

**Issue by tamaskan** [traefik/traefik#8354]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

This request is for people who use some kind of authentication through the authforward-middleware like keycloak or authelia. 
Usually apps or desktop-programs don't support this kind of authentication, therefore having a way to circumvent the middleware would be very useful.

e.g. matrix.domain/ -> middleware1 (with auth)
      matrix.domain/customtoken/ -> middleware2 (without auth) -> strip customtoken/

**Comment by jakubhajek** [comment]
Hello @tamaskan 

I am not sure if I correctly got your question but seems that the easiest way is to create a new router that matches the` matrix.domain/customtoken/` using `Host` and `PathPrefix` Rule without authentication middleware. 

As it is the question I recommend moving the conversation to our [community forum.](https://community.traefik.io/)
