### ISSUE TITLE
Allow disabling hardcoded acme rule for certain routers

### ISSUE THREAD

**Issue by DOCaCola** [traefik/traefik#8366]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I am using traefik to fetch certificates for several domains (all with http challenges) from Let's encrypt. However i have an IRC server running that requires access to the Let's encrypt certificate files directly. Therefore i have setup an instance of certbot for it's domain and route the HTTP traffic to it. However traefik intercepts all http requests to "/.well-known/acme-challenge/" before it reaches the certbot instance.

Unless i am missing something there seems no way to circumvent this rule, since it is automatically hardcoded with highest priority (MaxInt32) for every hostname as soon as you have set up any acme in Traefik, even if you don't intend to use it for a domain. The code suggests that it always falls back to a configured acme with HTTP challenge when trying to access the "/.well-known/acme-challenge/" url.

It be nice to have a way to enforce this rule to not being used for some routers or lower it's hardcoded priority so there can be ways where it can be overridden.

**Comment by rtribotte** [comment]
Hello @DOCaCola,

Thanks for your interest in Traefik!

The priority of the internal ACME router is indeed hardcoded with the MaxInt32 value.
However, on 64bit architectures, the value for the priority can be up to MaxInt64 for any router you are defining yourself, which would then actually take priority over the internal ACME router.
WDYT?

**Comment by DOCaCola** [comment]
Yes, that did indeed work. Thank you!
I tried that before and it didn't work. Turned out that the issue was the 2.2 version i had installed. I upgraded to 2.5 where the priority seems to be working just fine. (I am using the official docker image)
