### ISSUE TITLE
Possibility to customize the plugins-local location for local plugins

### ISSUE THREAD

**Issue by tcassaert** [traefik/traefik#8396]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Currently, when using Traefik local plugins, the code and the docs state that the path to your plugins should be `./plugins-local`, which means it should be located next to the Traefik binary.

This is however not completely true. When I run Traefik with `systemd`, it expects the `plugins-local` directory to be located at `/`. 

A possible solution would be to be able to customize that directory, so we can put it in a location that makes more sense than `/`.

**Comment by rtribotte** [comment]
Hello @tcassaert,

Thanks for your interest in Traefik!

I've open two PR to fix the documentation on the plugin's demo repositories.
Have you tried to change the [working directory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=) of the executed processes with `systemd`?

**Comment by tcassaert** [comment]
Thanks @rtribotte! Changing the working directory made it indeed possible to place the plugins into a custom location.
