### ISSUE TITLE
.well-known/acme-challenge path passthrough for specific domains

### ISSUE THREAD

**Issue by EthraZa** [traefik/traefik#8405]
### What did you expect to see?

I want this one container to be able to issue its won certs via HTTP-01 challenge, but Traefik is not allowing it.

### What I got

I have various containers that Traefik takes care of the SSL certs and they are ok. 
Now I'm setting up a new container with legacy system that will take care of it's own SSL.

new container docker-compose.yml:
```yml
labels:
              - "traefik.enable=true"
              - "traefik.docker.network=net_systems"

              - "traefik.http.services.apache.loadbalancer.server.port=80"
              - "traefik.http.routers.apache.entrypoints=web"
              - "traefik.http.routers.apache.rule=Host(`www.legacy.tld`)"

              - "traefik.tcp.services.apachesecure.loadbalancer.server.port=443"
              - "traefik.tcp.routers.apachesecure.entrypoints=websecure"
              - "traefik.tcp.routers.apachesecure.tls=true"
              - "traefik.tcp.routers.apachesecure.tls.passthrough=true"
              - "traefik.tcp.routers.apachesecure.rule=HostSNI(`www.legacy.tld`)"
```
The TLS passthrough is working ok. But, when I try to issue a new cert at the container using HTTP-01 challange, the issuer server can't reach the http://www.legacy.tld/.well-known/acme-challenge/xxxxxxxx because Traefik is configured with `--certificatesresolvers.le.acme.httpchallenge.entryPoint=web` for the other containers it issue certs to, so it is intercepting all requisitions to `*/.well-known/acme-challenge/`.
I have tried to create another resolver like `--certificatesresolvers.no.acme.httpchallenge=false --certificatesresolvers.no.acme.httpchallenge.entryPoint=web` and use it on the container, but without success.

There is a way to tell Traefik to ignore requisitions to .well-known folder for www.legacy.tld domain so the ACME requisitions can reach the container?
OR
There is a way to setup a tcp router passthrough for http protocol on port 80 for www.legacy.tld domain as well, instead of set it on the http router?

**Comment by ldez** [comment]
Hello,

> awesome work of https://github.com/ldez/traefik-certs-dumper 

Thank you :+1: 

To handle your use case, you have to put a priority higher than int32 on the router that you want to exclude from the acme endpoint handling.
Another solution is to use another challenge like the TLS challenge instead of the HTTP challenge.
I recommend using the TLS challenge.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
