### ISSUE TITLE
Traefik drops traffic from outside of the network 

### ISSUE THREAD

**Issue by PrudhviBoggavarapu** [traefik/traefik#8414]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I set up the traffic logs using docker 
traefik is running natively on the raspeberry pi 4 
```docker
version: "2.1"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.test.rule=Host(`test.karmarose.duckdns.org`)'
      - 'traefik.http.services.test.loadbalancer.server.port=80'
    ports:
      - 90:80
```
if i curl the ip 
```
* Connected to 10.147.17.xxx (10.147.17.xxx) port 90 (#0)
> GET / HTTP/1.1
> Host: 10.147.17.xxx:90
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.1
< Date: Tue, 31 Aug 2021 18:47:21 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 06 Jul 2021 14:59:17 GMT
< Connection: keep-alive
< ETag: "60e46fc5-264"
< Accept-Ranges: bytes
```
then sends the test page

But if i curl from outside the network, curl hangs 
 and does not get a < 

### What did you see instead?
```
* Connected to test.karmarose.duckdns.org ($PUBLIC_IP) port 80 (#0)
> GET / HTTP/1.1
> Host: test.karmarose.duckdns.org
> User-Agent: curl/7.68.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host test.karmarose.duckdns.org left intact
curl: (52) Empty reply from server
```

### What version of Traefik are you using?

Version:      2.4.13
Codename:     livarot
Go version:   go1.16.6
Built:        2021-07-30T15:06:29Z
OS/Arch:      linux/arm

### What is your environment & configuration?

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"


[api]
  dashboard = true
  insecure = true

[providers.docker]
  watch = true
  network = "web"
  exposedByDefault = false
```

Isssue is, curling test.karmarose.duckdns.org from inside the network works, curling from outside the network does not, when traefik is shutdown and nginx is on port 80, i can access it from outside of the network, so it is neither a router problem, nor an iptables issue

**Comment by tomMoulard** [comment]
Hello @PrudhviBoggavarapu,

Thanks for your interest in Traefik!

Is it possible for you to provide how you run Traefik. It is difficult to see the whole picture without it.

Thanks

**Comment by PrudhviBoggavarapu** [comment]
I run it with a raspberry pi 4 2gb model, running raspberrypi os 64
the command i run is 
```bash
sudo traefik 
```

**Comment by k0d3r1s** [comment]
can you curl/telnet public ip? i don't think this is traefik problem but more likely a network one. do you use raspberry behind a router? are the ports open?

**Comment by PrudhviBoggavarapu** [comment]
If i use nginx and curl the public ip on port 80, it works with the testpage i set up, When traefik is running, it does not work from the outside but does from the internal network 

If i (from my phone) 

LTE --> test.karmarose.duckdns.org --> Curl timeout
LTE --> public Ip with closed port 80; --> Connection refused
LTE --> karmarose.duckdns.org (with open port 80)  -->  Curl timeout

on my computer

computer On Same Lan as Pi --> test.karmarose.duckdns.org --> returns webpage
computer On Same Lan as Pi --> test.karmarose.duckdns.org (with closed port) --> Connection refused

**Comment by k0d3r1s** [comment]
if you ping your website from outside and inside, is the ip the same?

**Comment by PrudhviBoggavarapu** [comment]
Yes

**Comment by PrudhviBoggavarapu** [comment]
Karmarose.duckdns.org points to my public ip

**Comment by rtribotte** [comment]
Hello @PrudhviBoggavarapu,

To go further in troubleshooting, can you activate the logs on Traefik (DEBUG level) and share the full log trace?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
