### ISSUE TITLE
Enable https redirect for dashboard@internal service of defaultInternalEntryPoint.

### ISSUE THREAD

**Issue by JasonWangA** [traefik/traefik#8426]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

* We use traefik behind Aws Nlb, the https requests bypass Nlb first,  in this case, with the TLS Termination feature, the https request forward to traefik would change to http proto. As the default internal entrypoint's dashboard service have regexredirect rule for that, from which it will redirect to another url with http proto, as the nlb only allow the 443 port as we configured,  the
http request will block in browser. we request traefik enable the redirect for https requests bypass AWS NLB TLS Termination.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
