### ISSUE TITLE
DNSchallenge doesn't work with subdomains

### ISSUE THREAD

**Issue by phil737** [traefik/traefik#8472]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I want traefik to create a certificate for www.test.example.com using a dnsChallenge with my DNS provider.
I get a timeout error saying that traefik wasn't able to validate the certificate.

### What did you see instead?

Observing what happens on the DNS provider side I can see that the created TXT records is wrong.

It creates an _acme-challenge TXT record with **_acme-challenge.example.com** instead of **_acme-challenge.test.example.com**.

It seems to ignore the subdomain. I tried all variants but nothing works. Whereas with www.example.com it works perfectly.

### What version of Traefik are you using?

Version:      2.5.2
Codename:     livarot
Go version:   go1.17
Built:        2021-09-02T15:07:43Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

```
      [http.routers.router-geo]
         entryPoints    = ["https"]
         rule           = "Host(`www.test.example.com`)"
         service        = "service-geo"
         [http.routers.router-geo.tls]
            certResolver = "infom_resolver"
            [[http.routers.router-geo.tls.domains]]
               main = ["www.test.example.com"]
```
I tried with and without sans =, no difference. This is of course a simplified example but generates the error none the less.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
