### ISSUE TITLE
ACME cannot select preferred chain in v1.7 which generates broken certificates (expired root CA in chain)

### ISSUE THREAD

**Issue by tgerakitis** [traefik/traefik#8480]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I got a certificate with let's encrypt using traefik 1.7

### What did you see instead?

I can not select a "preferredChain" option which leads to broken SSL certificate generation. there is an expired root certificate in a part of the chain.

### What version of Traefik are you using?

1.7

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

![image](https://user-images.githubusercontent.com/34158395/135536529-dbb06992-0a30-47c3-9662-87819aa222fe.png)

**Comment by tgerakitis** [comment]
just out of curiosity, what is the ETA on bugs like this?

**Comment by SantoDE** [comment]
We did mark it as a P0 - we are working on it right now

**Comment by TheGreatDoc** [comment]
Looks like this also happens in v2.5.3

**Comment by ldez** [comment]
In the v2 you can already set the [preferredChain](https://doc.traefik.io/traefik/v2.5/https/acme/#preferredchain)

**Comment by GabrielMioranza** [comment]
![image](https://user-images.githubusercontent.com/7417152/135622777-4a4aa208-666a-4547-bd8f-3b2783997112.png)

Same on v2.5.3

**Comment by ldez** [comment]
@GabrielMioranza  As we don't have openssl inside the container, your script (that checks the CA inside the container) doesn't work.

If you install openssl inside the container, the output is:
```console
$ docker exec -i traefik /bin/sh < /tmp/verify.sh
New ISRG Root X1 already present ✓

OpenSSL newer than 1.0.2 ✓
```

**Comment by TheGreatDoc** [comment]
> In the v2 you can already set the [preferredChain](https://doc.traefik.io/traefik/v2.5/https/acme/#preferredchain)

Sorry for this, and I know its a bit offtopic. I've already set the preferredChain. Do I need to do anything else to make it work? Maybe renew the certificates? If yes, how do I force renew?

**Comment by ldez** [comment]
once the option is set, you can:
- wait for Traefik to renew your certs https://doc.traefik.io/traefik/v2.5/https/acme/#automatic-renewals
- remove your `acme.json` file and restart Traefik (beware of the Let's Encrypt rate limit https://letsencrypt.org/docs/rate-limits/)

Note, there is no major security issue behind this problem.

**Comment by kenkosmowski** [comment]
> We did mark it as a P0 - we are working on it right now @tgerakitis

Also happens in 2.5.3. When will it be fixed?

**Comment by TheGreatDoc** [comment]
> once the option is set, you can:
> 
> * wait for Traefik to renew your certs https://doc.traefik.io/traefik/v2.5/https/acme/#automatic-renewals
> * remove your `acme.json` file and restart Traefik (beware of the Let's Encrypt rate limit https://letsencrypt.org/docs/rate-limits/)

I did the second option, but only removing one cert from acme.json (just for testing) and restarting traefik.

> Note, there is no major security issue behind this problem.

It shouldnt, rigth? But shit happens (sorry for the expression). Our gitlab instance is behind traefik, was with old root certificate and since today workers were refusing to clone from the repo with:

`fatal: unable to access 'https://<obscured>': SSL certificate problem: certificate has expired`

But after doing what you said, everything is working perfectly.

**Comment by TheGreatDoc** [comment]
@kenkosmowski Just follow the comments from @ldez

**Comment by tgerakitis** [comment]
@ldez is it possible to pull the docker image from your PR even though it is not merged yet?

**Comment by ldez** [comment]
@tgerakitis we will create a release today

**Comment by felzend** [comment]
Hello.

Is PreferredChain flag working on Traefik v2? Currently pulling from Docker image "traefik:2.5.3".

Couldn't test yet on production because I'm aware of data loss on our systems.

On the Postman version before the latest one it won't work, still causes expired certificate error.

Currently using this docker-compose:

`services:
  traefik:
    image: traefik:2.5.3
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.watch=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --entryPoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.acmeresolver.acme.httpchallenge=true
      - --certificatesresolvers.acmeresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.acmeresolver.acme.email=email
      - --certificatesresolvers.acmeresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.acmeresolver.acme.preferredChain="ISRG Root X1"`

**Comment by ldez** [comment]
@felzend you have to remove the quotes

**Comment by tgerakitis** [comment]
@ldez 
I'd like to prepare my configs accordingly. is it correct to assume that the preferred chain will be configurable like this in the `traefik.toml`?
```
defaultEntryPoints = ["http", "https"]

[entryPoints]
 ...

[api]

[docker]
  ....
[acme]
preferredChain = "ISRG Root X1"
```

**Comment by ldez** [comment]
@tgerakitis https://github.com/traefik/traefik/pull/8482/commits/d22fc099a39a91d8bdb7c552b97149c3cf945fe9

**Comment by traefiker** [comment]
Closed by #8482.

**Comment by tgerakitis** [comment]
@ldez hi, I just downloaded the version of traefik 1.7.31 that should contain the fix.

I updated my `traefik.toml` to look like this:
```
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
   [entryPoints.https.tls]
   minVersion = "VersionTLS12"
   cipherSuites = [
       #TLS 1.3
       "TLS_AES_128_GCM_SHA256",
       "TLS_AES_256_GCM_SHA384",
       "TLS_CHACHA20_POLY1305_SHA256",
       #TLS 1.2
       "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
       "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
       "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
       "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
       "TLS_RSA_WITH_AES_128_GCM_SHA256",
       "TLS_RSA_WITH_AES_256_GCM_SHA384",
       "TLS_RSA_WITH_AES_128_CBC_SHA",
       "TLS_RSA_WITH_AES_256_CBC_SHA"
   ]


[accessLog]

[retry]

[api]

[docker]
  endpoint = "tcp://docker-socket-proxy:2375"
  domain = "example.com"
  watch = true
  exposedbydefault = false
[acme]
  email = "office@example.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  preferredChain = "ISRG Root X1"

[acme.httpChallenge]
  entryPoint = "http"
```

What I did:
* shut down `traefik` by running `docker-compose down` 
* deleted the `acme.json` 
* prepared a new, empty `acme.json`
  * `touch acme.json`
  * `chmod 600 acme.json`
* started traefik again `docker-compose up -d`

when checking the certificate on `sslabs.com` or via the following command, I still see the X3 path present
```
openssl s_client -connect my.example.com:https | head
> depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
> verify return:1
> depth=1 C = US, O = Let's Encrypt, CN = R3
> verify return:1
> depth=0 CN = my.example.com
> verify return:1
> CONNECTED(00000003)
> ---
> Certificate chain
>  0 s:CN = my.example.com
>    i:C = US, O = Let's Encrypt, CN = R3
>  1 s:C = US, O = Let's Encrypt, CN = R3
>    i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
>  2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
>    i:O = Digital Signature Trust Co., CN = DST Root CA X3
> ---
> 
```

my `docker-compose.yml`:
```
version: '2.4'

services:

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      CONTAINERS: 1
    restart: always
    privileged: true
    networks:
      - default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: traefik:1.7.31
    restart: always
    environment:
      GODEBUG: tls13=1
    networks:
      - web
      - default
    ports:
      - 80:80
      - 443:443
    labels:
      traefik.enable: false
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
```

**Comment by mainmachine** [comment]
I too am experiencing this issue, and have tested after pulling the new 1.7.31 with no change.

I am testing on 2 different development hosts with different fqdn's.

Using certbot 1.19.0 on a 3rd host, I can force renewal and successfully renew the cert after adding ```preferred_chain = ISRG Root X1``` to the ```/etc/letsencrypt/renewal/xxx.com.conf``` file.

I don't know if that is of any help other than to corroborate what @tgerakitis has reported.

**Comment by ldez** [comment]
You can follow #8494
