### ISSUE TITLE
Update dependency "lego" to 4.5.2: zone name as environment variable

### ISSUE THREAD

**Issue by fibbs** [traefik/traefik#8485]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I would like to see the next release of Traefik containing go-acme/lego in version 4.5.2 or whatever is released until then. We are using Traefik in a quite special combination of a split DNS setup, and one necessary setting to make this possible is the possibility to supply the actual zone name of the Azure DNS zone wanting to create verification entries in as an environment variable.
For those interested in the story: https://github.com/go-acme/lego/pull/1433
Lego has now released this fix with version 4.5.2, that's why I ask for version bump of the dependency in traefik.

**Comment by ldez** [comment]
Hello,

lego was already updated ( #8481), it will be in the next version of Traefik v2.5

**Comment by ldez** [comment]
v4.5.0 and v4.5.2 are exactly the same (I'm the maintainer of lego): I created v4.5.1 and 4.5.2 because of a CI issue.

https://github.com/go-acme/lego/blob/master/CHANGELOG.md

**Comment by fibbs** [comment]
Awesome, thanks!
