### ISSUE TITLE
Cannot build master or tag v2.5.3 from source due to missing tencentcloud dependency

### ISSUE THREAD

**Issue by lwithers** [traefik/traefik#8493]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I attempted to build `traefik` from source with:

```
git clone https://github.com/traefik/traefik.git
cd traefik
make generate-webui
cd cmd/traefik
go build
```

### What did you see instead?

The build failed:

```
go: github.com/hashicorp/consul@v1.10.0 requires
        github.com/hashicorp/go-discover@v0.0.0-20200501174627-ad1e96bde088 requires
        github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible: reading https://athens.internal.yoti.com/github.com/tencentcloud/tencentcloud-sdk-go/@v/v3.0.83+incompatible.mod: 404 Not Found
```

Please note that `athens.internal.yoti.com` is our company's internal Go module proxy; if I remove that from the chain, i.e. use the standard upstream Go module proxy for the build, then it succeeds. Thus I guess the module is cached by the public proxy, but is not actually available any longer.

This could potentially cause problems in the long run?

It appears that `hashicorp/go-discover` has seen and fixed the issue (https://github.com/hashicorp/go-discover/issues/172), but `consul` (including the latest tag `v1.10.3`) is not updated to pull the latest version.

I worked around the issue by adding:

```
replace github.com/hashicorp/go-discover => github.com/hashicorp/go-discover v0.0.0-20210818145131-c573d69da192
```

into the `go.mod`.

### What version of Traefik are you using?

The issue occured with:
- `v2.5.3`
- and also commit `969dd088a`

### What is your environment & configuration?

go version 1.17.1 on Linux.

**Comment by ldez** [comment]
Hello,

it's a problem with your Go proxy (https://athens.internal.yoti.com)
