### ISSUE TITLE
[Question] How is documentation for ACME dns01 providers generated?

### ISSUE THREAD

**Issue by kaysond** [traefik/traefik#8518]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I'm working on a project that uses traefik and the dns01 acme provider. In a setup script, I'd like to assist users in setting the correct provider name and environment variables.

I'm wondering how [docs/content/https/acme.md](https://github.com/traefik/traefik/blob/master/docs/content/https/acme.md) is generated. Is it manual or does some kind of automation pull the providers and env vars from [go-acme/lego](https://github.com/go-acme/lego)?

My guess is the former, in which case my plan is to parse traefik's [go.mod](https://github.com/traefik/traefik/blob/master/go.mod) to find the correct `go-acme/lego` version, then parse env vars from the corresponding provider source code.

This isn't especially robust, so any thoughts or input would be appreciated. Thanks!

**Comment by ldez** [comment]
Hello,

the Traefik documentation is not generated but the lego documentation is generated.
For the lego documentation you can take a look here: https://github.com/go-acme/lego/tree/master/internal/dnsdocs

**Comment by kaysond** [comment]
Thanks!
