### ISSUE TITLE
can't get basic auth middleware to work in router where tls is enabled

### ISSUE THREAD

**Issue by josh-m-sharpe** [traefik/traefik#8587]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Env:
nomad, consul, traefik

I use nomad to set tags on services in consul.  traefik is configured to use consul as its provider.
generally, the nomad/consul/traefik setup is working.

Issue:
I've been unable to get basic auth working on an https endpoint with tls enabled using lets encrypt.

Steps to enable it:
```
$ htpasswd -nbB foo bar
foo:$2y$05$OcxnOQcjZv6JPrXbiOS8Be0bKfC9VhXgcy1GXBeeV1ZYcF8cS1SQe
```
Add these tags to my nomad job, which in turn, sets them in consul:

```
"traefik.http.middlewares.phonetrac-unicorn-basic-auth.basicauth.users=foo:$2y$05$dfDorG89qsB.bBv50UPDOuK5AhyPGQfeXSsDmkhb4bB/kqlIV6NLa",
"traefik.http.middlewares.phonetrac-unicorn-basic-auth.basicauth.removeheader=true",
"traefik.http.routers.phonetrac-unicorn.middlewares=phonetrac-unicorn-basic-auth@consulcatalog",
```

Then,  make a browser-based request to our domain (which otherwise works).  I am prompted, and the user 'foo' and password 'bar' do not let me through.

I have also tried:

1) Escaping the `$` above by replacing it with: `$$`.
2) Using a nearly identical config on a non-tls router. (This setup works for that router)
3) Attempted to test it with curl: `curl -I https://foo:bar@my.domain/login` -> 401
4) Confirm the tags manifest themselves in consul correctly:
![_nomad-task-61164762-8cdd-cd10-aa66-fea7e2c0299d-group-unicorn-phonetrac-unicorn-http_-_Consul](https://user-images.githubusercontent.com/39473/142923729-3ba7c9db-1652-4d10-bae5-afa5202ea123.jpg)
5) Confirmed the router/middleware appears to be configured in traefik:
![Traefik](https://user-images.githubusercontent.com/39473/142923964-ffc0ba12-5b57-48ac-9f4d-baee553e9c98.jpg)

### What did you see instead?

Basic Auth working

### What version of Traefik are you using?

2.5.2

### What is your environment & configuration?

```yaml
[globals]
  sendAnonymousUsage = false
  checkNewVersion = false

[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.http]
    address = ":{{ env "NOMAD_PORT_http" }}"
  [entryPoints.https]
    address = ":{{ env "NOMAD_PORT_https" }}"
  [entryPoints.loki]
    address = ":{{ env "NOMAD_PORT_loki" }}"
  [entryPoints.traefik]
    address = ":{{ env "NOMAD_PORT_traefik" }}"
  [entryPoints.prometheus]
    address = ":{{ env "NOMAD_PORT_prometheus" }}"

[ping]

[metrics]
  [metrics.prometheus]
    addServicesLabels = true
    addEntryPointsLabels = true
    addRoutersLabels = true

[api]
  dashboard = true
  insecure  = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
  prefix           = "traefik"
  exposedByDefault = false

  [providers.consulCatalog.endpoint]
    address = "127.0.0.1:8500"
    scheme  = "http"
[[tls.certificates]]
  certFile = "/acme/ctmhub.app.cert"
  keyFile = "/acme/ctmhub.app.key"

[certificatesResolvers.letsencrypt.acme]
  storage = "/acme/acme.json"

```

Add more configuration information here.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by josh-m-sharpe** [comment]
Pretty sure this is a bug.
