### ISSUE TITLE
Service url support regex

### ISSUE THREAD

**Issue by Binyang2014** [traefik/traefik#8588]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hi, I am trying to migrate from nginx to traefik.
In nginx, we have a rule looks like:
```
location ~ ^/log-manager/([^/]+):(\d+)/(.*)$ {
  proxy_pass http://$1:$2/$3$is_args$args;
}
```

In traefik, due to I only can use plain text for url field in `[[http.services.my-service.loadBalancer.servers]]`. I need to create route rules for all endpoints, which maybe thousands of in some environment.

Can we support regex for backend url?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
