### ISSUE TITLE
Traefik DNS Manual Methode

### ISSUE THREAD

**Issue by chrishdx** [traefik/traefik#8589]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Hi there,
when I start the Traefik container via docker run -it and configure the toml file as described below, the txt entries that I have to set do not appear. I set logging to debug

[certificatesResolvers.myresolver.acme]
   # ...
   [certificatesResolvers.myresolver.acme.dnsChallenge]
     provider = "manual"
     delayBeforeCheck = 900

### What did you see instead?

-

### What version of Traefik are you using?

2.5.4

### What is your environment & configuration?

[certificatesResolvers.myresolver.acme]
   # ...
   [certificatesResolvers.myresolver.acme.dnsChallenge]
     provider = "manual"
     delayBeforeCheck = 900

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
