### ISSUE TITLE
Kubernetes: servers transport not found

### ISSUE THREAD

**Issue by BernhardBerbuir** [traefik/traefik#8610]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have created the following Kubernetes resources at the namespace `infra-logging`
* a Secret `elastic-certificate-chain` with key `tls.ca` and a self signed certificate as value
* a Serverstransports `elasticsearch` which references the Secret
  ```yaml
  apiVersion: traefik.containo.us/v1alpha1
  kind: ServersTransport
  metadata:
    name: elasticsearch
    namespace: infra-logging
  spec:
    rootCAsSecrets:
      - elastic-certificate-chain
  ```
* a Service with the annotation `traefik.ingress.kubernetes.io/service.serverstransport: elasticsearch@kubernetescrd`

I want to use a self-signed certificate at the elasticsearch pod. Therefore, traefik must be informed about the RootCA which signed the certificate. I'm using only a root CA, no intermediate CA.

### What did you see instead?

I get the following error message: `servers transport not found elasticsearch@kubernetes`.

### What version of Traefik are you using?

version 2.5.4

### What is your environment & configuration?

The traefik Pod uses the command line parameter `"--serverstransport.insecureskipverify=true` as not all services currently use a ServersTransport.

### If applicable, please paste the log output in DEBUG level

Configuration received from provider kubernetes:
```json
{
  "http": {
    "routers": {
      "elasticsearch-local-master-infra-logging-elasticsearch-local-master-intern-localhost": {
        "service": "infra-logging-elasticsearch-local-master-9200",
        "rule": "Host(`elasticsearch-local-master.intern.localhost`) && PathPrefix(`/`)"
      }
      ...
    },
    "services": {
      "infra-logging-elasticsearch-local-master-9200": {
        "loadBalancer": {
          "servers": [
            {
              "url": "https://172.26.1.5:9200"
            },
            {
              "url": "https://172.26.2.6:9200"
            },
            {
              "url": "https://172.26.3.6:9200"
            }
          ],
          "passHostHeader": true,
          "serversTransport": "elasticsearch@kubernetescrd"
        }
      },
      ...
      }
    }
  },
  "tcp": {}
}
```

```json
{
  "entryPointName": "intern-web",
  "level": "error",
  "msg": "servers transport not found elasticsearch@kubernetescrd",
  "routerName": "elasticsearch-local-master-infra-logging-elasticsearch-local-master-intern-localhost@kubernetes",
  "time": "2021-12-06T16:17:56Z"
}
{
  "entryPointName": "intern-secure",
  "level": "debug",
  "msg": "Adding route for elasticsearch-local-master.intern.localhost with TLS options default",
  "time": "2021-12-06T16:17:56Z"
}
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
