### ISSUE TITLE
ACME cert renewal ignores preferredChain

### ISSUE THREAD

**Issue by beardeddragon5** [traefik/traefik#8612]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Let traefik renew the certificate with only the preferred chain and expected the renewed certificate to contain only the preferred chain.

### What did you see instead?

The renewed certificate contains all chains, not only the preferred one.

### What version of Traefik are you using?

v2.4.14 but still in v2.5

#### Traefik v2.4
https://github.com/traefik/traefik/blob/3445abe7aca7255e9b9f34c0ba65562dbabe2b99/pkg/provider/acme/provider.go#L659

Lego `renew` function
https://github.com/go-acme/lego/blob/7c24212e8a1df8547ca6edb6cf630cff60e62f46/certificate/certificates.go#L379

#### Traefik v2.5
https://github.com/traefik/traefik/blob/3445abe7aca7255e9b9f34c0ba65562dbabe2b99/pkg/provider/acme/provider.go#L659

Lego `renew` function used in traefik v2.5
https://github.com/go-acme/lego/blob/6dd983b19c8ebf7d7a90333e0e6ef2349af0db42/certificate/certificates.go#L395

#### Fixed lego version 4.5.3
https://github.com/go-acme/lego/blob/3675fe68aed2c6c99d1f92eb02133ecd9af7b2be/certificate/certificates.go#L395

**Comment by beardeddragon5** [comment]
Basically update lego to 4.5.3, or provide CSR information to lego.

**Comment by kevinpollet** [comment]
Hello @beardeddragon5 and thanks for your interest in Traefik,

This has already been fixed by https://github.com/traefik/traefik/pull/8607
