### ISSUE TITLE
Add note about BasicAuth usersFile NOT needing to escape dollar signs ($)

### ISSUE THREAD

**Issue by loganmarchione** [traefik/traefik#8614]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

On the [HTTP BasicAuth](https://doc.traefik.io/traefik/middlewares/http/basicauth/) page, it is explicitly specified that you need to escape dollar signs ($) with another dollar sign (i.e., $$).  
> `# Note: all dollar signs in the hash need to be doubled for escaping.`

However, in the [usersFile](https://doc.traefik.io/traefik/middlewares/http/basicauth/#usersfile), you don't need to do that. I spent way too much time with a usersFile with $$ in it before I realized what I was doing. Please add a note [here](https://github.com/traefik/traefik/blob/d970813c20120a55fc10068e7e7a98e60abff770/docs/content/middlewares/http/basicauth.md?plain=1#L192) to indicate that you don't need $$ in the usersFile.

### What did you see instead?

N/A

### What version of Traefik are you using?

2.5.4

### What is your environment & configuration?

N/A

### If applicable, please paste the log output in DEBUG level

N/A

**Comment by tomMoulard** [comment]
Hello @loganmarchione,

Thanks for your interest in Traefik!

Indeed, [this section](https://github.com/traefik/traefik/blob/d970813c20120a55fc10068e7e7a98e60abff770/docs/content/middlewares/http/basicauth.md?plain=1#L101) does not state explicitly that this note is only used with docker-compose.

> \```yaml tab="Docker"
> \# Declaring the user list
> \#
> \# Note: all dollar signs in the hash need to be doubled for escaping.

I'd suggest following [this](https://github.com/traefik/traefik/blob/d970813c20120a55fc10068e7e7a98e60abff770/docs/content/middlewares/http/basicauth.md?plain=1#L15) note in order to make clearer that this note, in this tab, corresponds to the docker-compose configuration.

> \```yaml tab="Docker"
> \# Declaring the user list
> \#
> \# Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.

See #6967

**Comment by traefiker** [comment]
Closed by #8615.
