### ISSUE TITLE
middleware 

### ISSUE THREAD

**Issue by yuedf** [traefik/traefik#8621]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Deploy multiple traifiks in k8s. When middleware is used in custom services, it will be displayed in all traifiks

### What did you see instead?

Deploy multiple traifiks in k8s. When middleware is used in custom services, it will be displayed in all traifiks

### What version of Traefik are you using?

2.2.1

### What is your environment & configuration?

k8s 18.8
helm https://containous.github.io/traefik-helm-chart 8.8.2

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
