### ISSUE TITLE
Statsd metrics are missing service/router tags

### ISSUE THREAD

**Issue by cromega** [traefik/traefik#8622]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

We have Traefik configured to send server metrics to Statsd. The metrics, however, don't seem to have tags that would let us get a per-service breakdown. Looking at the tests this feature is missing. https://github.com/traefik/traefik/blob/master/pkg/metrics/statsd_test.go#L68-L73

Metrics for Prometheus, for example, are sent with service name tags.

Without service/router tags these metrics are largely useless.

**Comment by TPXP** [comment]
I had a similar issue. This is caused by the fact that statsd does not have a standard way of sending [tags along metrics](https://github.com/jsocol/pystatsd/issues/83). The Datadog extension does it. You may also use the prometheus exporter and import metrics from it.

**Comment by cromega** [comment]
@TPXP that is a good point about statsd. I could actually use the datadog integration to send metrics to our custom statsd service. Thanks for the idea!

I will close this issue as I'm not sure there is anything to be done about it. Maybe the documentation could be improved slightly.
