### ISSUE TITLE
traefik 1.x releases artifacts are different from traefik 2.x

### ISSUE THREAD

**Issue by chenrui333** [traefik/traefik#8628]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you see instead?

Looks like v1.x release did not include the `traefik-v1.x.x.src.tar.gz` artifact.

Before [v1.7.30](https://github.com/traefik/traefik/releases/tag/v1.7.30): 16 assets
After that (ex: [v1.7.31](https://github.com/traefik/traefik/releases/tag/v1.7.31)): 14 assets

**Comment by tomMoulard** [comment]
Hello @chenrui333,

Thanks for your interest in Traefik!

Indeed, in the [work](https://github.com/traefik/traefik/compare/v1.7.30...v1.7.31) put into `v1.7.31`, one [PR](https://github.com/traefik/traefik/pull/8486) moved the CI build from TravisCI to GitHub actions.
Doing so changed artifacts uploaded by the CI to GitHub.

You can find the equivalent of the `traefik-v1.7.31.src.tar.gz` artifact in the [GitHub source code archive](https://github.com/traefik/traefik/archive/refs/tags/v1.7.31.tar.gz).
