### ISSUE TITLE
Traefik steals an Ingress destined for another controller if annotation kubernetes.io/ingress.class is not set (but only newer spec.ingressClassName)

### ISSUE THREAD

**Issue by mimmus** [traefik/traefik#8631]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I have a k8s cluster using both Traefik and another ingress controller (Nginx).
Nginx uses newer:
```
spec:
  ingressClassName: <myIngressClass>
```
for Ingress definitions, instead of deprecated annotation:
```
kubernetes.io/ingress.class: <myIngressClass>
```
but, when annotation is missing, Traefik conflicts with Nginx, trying to 'steal' the Ingress destined to it.

### What did you see instead?

My Ingress is exposed with a Traefik endpoint instead of Nginx one

### What version of Traefik are you using?

Traefik was installed by k8s distro as Helm chart:
CHART                           APP VERSION
traefik-1.90.0                  1.7.24

### What is your environment & configuration?

kubernetes 1.20

Similari issue:
https://github.com/traefik/traefik/issues/7896

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
