### ISSUE TITLE
Traefik serve default traefik cert on non existent router

### ISSUE THREAD

**Issue by bdoublet91** [traefik/traefik#8634]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

HI,
I use traefik v2 with DNSchallenge and wildcard domain like all my docker routers exposed have the same wildcard domain.
For theses routers, all work well but when I curl a non existent router, I get default traefik cert with 404 not found

```
curl -ks https://<REPLACED>:443 -vvv
*   Trying <REPLACED>:443...
* TCP_NODELAY set
* Connected to <REPLACED> (<REPLACED>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: Dec 14 14:43:25 2021 GMT
*  expire date: Dec 14 14:43:25 2022 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b70e814e30)
> GET / HTTP/2
> Host: <REPLACED>
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Tue, 14 Dec 2021 15:05:16 GMT
< 
404 page not found
```

Is it a security problem, maybe leak of information ? 
Could I block the connection for non existent router, this way I wont serve a cert for TLS connection ?
Or maybe it's the default behavior of traefik and it's ok :).

Thanks for your time.

Best regards.

### What did you see instead?

default traefik cert server on non existent router

### What version of Traefik are you using?

traefik version
Version:      2.3.7
Codename:     picodon
Go version:   go1.15.6
Built:        2021-01-11T18:03:02Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

---

global:
  sendAnonymousUsage: false
  checkNewVersion: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - SecHeaders@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: "${PUBLIC_DOMAIN}"
            sans:
              - "*.${PUBLIC_DOMAIN}"
        options: security

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /certificate/acme/acme.json
      keyType: EC256
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      #httpChallenge:
      #  entryPoint: foobar

api:
  #insecure: true
  dashboard: true
  #debug: true

log:
  #filePath: "/etc/traefik/applog.log"
  level: DEBUG
  format: json

providers:
  docker:
    endpoint: http://dockersocket:2375
    exposedByDefault: false
    watch: true
    swarmMode: true
    network: traefik-public
    exposedByDefault: false
    constraints: "!Label(`traefik.docker.network`, `traefik-local`)"
  file:
    directory: /etc/traefik/dynamic-conf/
    watch: true

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
