### ISSUE TITLE
5 seconds cache prevent TCP router (using HostSNI) detecting good service

### ISSUE THREAD

**Issue by Yivan** [traefik/traefik#8638]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I tried to make use of TCP router with HostSNI qualified, using passthrough TLS.
A wildcard certificate is used.
It should not work, as SNI cannot distinguish two services using this same wildcard certs.
**And I was surprised, Traefik manage to route to the good service!**

To reproduce, just set 2 apache services, using the very classic TCP with TLS configuration below. They must use both the same wildcard cert.

### What did you see instead?

I should not work at all, or it should work but without this 5 seconds "cache".

Open two browser tabs, one with apache1.mydomain.com, the other with apache2.mydomain.com.
If you go on apache1.domain.com the page display well the apache1 html content, wait 5 seconds without any request on it, go on apache2.domain.com, it will display well the apache2 html content. And you can go on like this without any problem, the only things is to wait 5 seconds without any request before calling the other apache.
If you refresh the same apache (repeating click every one second), it works fine for this apache, but you have to wait 5 secs before refreshing other browser tabs with apache2 url.

But if you wait less than 5 seconds after requesting one of the apache, requesting the other apache will make the request on the first one !!

Example:
- I go on `apache1.domain.com`, wait 5 secs, i go on `apache2.domain.com` : apache2 content is displayed, this is OK
- I go on `apache1.domain.com`, wait 2 secs, i go on `apache2.domain.com` : apache1 content is displayed, this is NOT OK

I imagine some cache occurs where traefik try to resolve routing and keep it during 5 secs.
I tried looking in the traefik documentation about a 5s configuration, but found nothing (except http provider which have nothing to do with this).
Is there a way to not have this cache period ? So we can use HostSNI with wildcard certs ?
But like I said, I was really surprised Traefik manage to route because with a wildcard cert I was thinking it won't work at all : ))

Thanks.

### What version of Traefik are you using?

Latest one at this date: 2.5.5

### What is your environment & configuration?

```yaml
...
            - "traefik.tcp.routers.apache1.entrypoints=https"
            - "traefik.tcp.routers.apache1.rule=HostSNI(`apache1.mydomain.com`)"
            - "traefik.tcp.routers.apache1.tls.passthrough=true"
            - "traefik.tcp.services.apache1.loadbalancer.server.port=443"
...
            - "traefik.tcp.routers.apache2.entrypoints=https"
            - "traefik.tcp.routers.apache2.rule=HostSNI(`apache2.mydomain.com`)"
            - "traefik.tcp.routers.apache2.tls.passthrough=true"
            - "traefik.tcp.services.apache2.loadbalancer.server.port=443"
...
```

Both apache are configured on port 443 with HTTPS, and have the same wildcard certificate `*.mydomain.com`

**Comment by Yivan** [comment]
I should add this problem occurs only with tabs in the same browser. Using one browser with `https://apache1.domain.com` and another browser with `https://apache2.domain.com` all works fine.

**Comment by kevinpollet** [comment]
Hello @Yivan and thanks for your interest in Traefik,

> It should not work, as SNI cannot distinguish two services using this same wildcard certs

The SNI contains the requested domain name. Thus, if a request is sent to the `apache1.mydomain.com` the SNI contains `apache1.mydomain.com` even if the certificate used is a wildcard one (`*.mydomain.com`).

Please take a look at https://community.traefik.io/t/can-not-visit-two-sites-in-one-browser-at-the-same-time/12424 which explains the behavior.

**Comment by Yivan** [comment]
Hello, thanks for your answer and the link. Reading it answered my question.
I think HTTP/2 keep open the request for all *.mydomain.com to the same back-end, and close it after 5 seconds, so it would explain the behaviour I had.

I disabled h2 protocol in Apache, and doing this make TCP router for Apache working great even opening different domains of websites based on the same wildcard certificate.

**So to conclude this issue for those trying TCP router with Apache and wildcard certs, it works fine but HTTP/2 (h2) need to be disabled to ensure no collision between domains in the same web browser!**

Best regards.
