### ISSUE TITLE
Having a way to autogenerate self-signed certs for SNI/TLS TCP router.

### ISSUE THREAD

**Issue by Yivan** [traefik/traefik#8639]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hello,

Traefik can now handle TCP routes with SNI, but if multiple services on the same port.
In case of replicable/multiple service, using different ports would be too hard to maintain, so the best way is to have dedicated certs with unique common name so SNI can be cleanly resolved.

Use case is development environment, which usually use factive domains (so DNS-01 challenge cannot be used) or unreachable from the internet (so Let's encrypt cannot be used).
Having the possibility to autogenerate self-signed certs for TCP Route would be really helpful, and make thing simpler.

I know Traefik is based on Lego, so I opened an improvement request here : https://github.com/go-acme/lego/issues/1549

I don't know if Lego will implement it or if traefik can handle this on its side.

For our use case, we use a wildcard domain for our dev environment making it simpler (*.dev.company.com). So they can easily use this cert for multiple projects/services. But wildcard seems to have a problem with SNI/TCP router (I opened a bug issue here: https://github.com/traefik/traefik/issues/8638 for reference).

I think this will be really useful, so we can very easily create TCP Route for dev/internal company environment, it will give something like this (for instance multiple rabbitmq service):

```
...
- "traefik.tcp.routers.myrouter.entrypoints=rabbitmq"
- "traefik.tcp.routers.myrouter.rule=HostSNI(`rabbitmq1.local`)"
- "traefik.tcp.routers.myrouter.tls.certResolver=selfsigned"
- "traefik.tcp.routers.myrouter.tls=true"
- "traefik.tcp.services.myrouter.loadbalancer.server.port=5671"
...
- "traefik.tcp.routers.myrouter.entrypoints=rabbitmq"
- "traefik.tcp.routers.myrouter.rule=HostSNI(`rabbitmq2.local`)"
- "traefik.tcp.routers.myrouter.tls.certResolver=selfsigned"
- "traefik.tcp.routers.myrouter.tls=true"
- "traefik.tcp.services.myrouter.loadbalancer.server.port=5671"
...
```

Actually, this is not so simple to route TCP for developpers/internal servers (QA, stage, integration, etc.).
It is more convenient to have self-signed certs for this type of environment and having simple/ready to go configs.

I hope my suggestion is a good one ; )

Best regards.

**Comment by kevinpollet** [comment]
Hello @Yivan and thanks for your interest in Traefik,

The `certResolver` mechanism is meant to be used to retrieve certificates from an ACME server, not to generate self-signed certificates. The role of Traefik is not to implement a PKI but to provide the mechanisms to obtain certificates from third parties PKIs.

To generate certificates for development purposes, some private PKIs (ACME compliant) could be leveraged to generate self-signed certificates, see https://github.com/smallstep/certificates#readme or https://github.com/letsencrypt/pebble#readme.   

According to this, we will decline this feature request.

**Comment by Yivan** [comment]
Hello, thanks, ok I understand, go-acme answered me the same things this is only for acme providers.
So it must be a separated feature of certResolver, maybe some days I open a suggestion on it, but I think it will to much be outside of the scope of Traefik.
Relying on certResolver was to make things simple, a simple resolver name `autosign` which will tell traefik to call openssl in background to create cert for domain filled in HostSNI or domains section.

I think it can anyway be resolved without traefik new feature by modifying entrypoint of container to create selfsigned certificates using openssl (one line of bash : `openssl req -new -newkey rsa:2048 -sha256 -days 30 -nodes -x509 -subj '/CN=mydomain.com' -keyout /var/www/certificates/mydomain.com.key -out /var/www/certificates/mydomain.com.crt`) or surcharging dockerfile image.
I don't know if traefik provide "hooks" so it can run scripts when he detects a container start/reload, it could be another way to handle self cert generation. It seems not, I found nothing on this on documentation/internet.

I confirm this issue can be closed.
Thanks again for your time and support.
