### ISSUE TITLE
Disable a middleware at router level when defined at entrypoint

### ISSUE THREAD

**Issue by toxic0berliner** [traefik/traefik#8654]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

The ideas is to be able trough a label on a container to disable a container that has been set on the entrypoint.
I'm not the only one wishing for this, I found several examples of people trying this out like this one : https://community.traefik.io/t/disable-default-configuration-options-on-a-per-container-basis/8785

The idea is to define "sane defaults" that for instance apply forward-auth middlewares or other security for any router attached to the entrypoint, but still allow the router to override this when needed. 

My understanding is that there is no enabled=true/false on a middleware, and even finding a way to empty the middleware array on a router would not disable the middlewares defined at the entrypoint level.

In an ideal was I'd like to have my traefik default like this : 
```
entryPoints:
  websecure:
    address: ":443"
    http:
      middlewares:
        - forward-auth@file
```
and for the vast majority of containers, no extra labels and the middleware is applied.
But for some containers I would like to ass something like this in my compose file: 
```
labels:
  - "traefik.tcp.routers.my-container.middlewares.forward-auth.enabled=false"
  # or
  - "traefik.http.middlewares.my-container-middleware.forward-auth.enabled=false"
  # or even 
  - "traefik.http.middlewares.forward-auth.blacklist=my-container"
```

Whichever is easyes to implement or even other syntax I couldn't think of right now.

A justification why disabling it is useful, first it's probably the easyest way for traefik users. But also in my case, I use thomseddon/traefik-forward-auth and I have already used it's internal rules to effectively disable the middleware for some urls, but in fact the middleware is running, just allowing the requests without having authenticated the user. And this is not enough in some cases like running a docker registry behind traefik as this middleware does not play nice with HEAD requests (https://github.com/thomseddon/traefik-forward-auth/issues/156).

So I'm asking this feature not only because I'd like it to alleviate my current issue with HEAD requests, but becaus it's not the first time I wanted to do that and I find several people wanting it in the forums and no issue submitted here in github.

Thanks in advance for your consideration,

Best regards,
Toxic.

**Comment by StefanSchoof** [comment]
I run into the same issue with for now I use a allow action in the traefik-forward-auth config:

```
      - "--rule.vaultwarden.action=allow"
      - "--rule.vaultwarden.rule=Host(`vaultwarden.$DOMAINNAME`)"
```

This allows me at least to keep a default middleware and allow some host to use no auth. Because the config is not at the container itself, I like the solution not so much as the one you described. But it working now.

**Comment by toxic0berliner** [comment]
Thanks for pitching in @StefanSchoof !
I'm also using the exact same solution as you with explicit allow rules, but that doesn't disable the middleware, and especially with the HEAD request for a docker repository the middleware is still causing issues even with the allow rule. That's why I think fully disabling a middleware at router level is needed, even for you it's cleaner as you say, and for my usecase when the middleware is not suitable at all this becomes needed and not only wanted ;)
On this particular auth middleware we are several and have built a workaround with it's own issues that are more fitting my needs

**Comment by atdnorth** [comment]
Another use case would be for ipWhiteList where most routers {A} will accept a specific set of white list IP addresses and a small subset {B} would use a different set of ip addresses.  In this way,  no ipWhiteList middleware labels would need to be applied to routers {A}.  

From a security perspective this is useful since if one accidentally did not set the white list, at least a default white list would still be applied.

**Comment by dani** [comment]
Wouldn't a single `ignoreEntrypointsMiddlewares` option at the router level be simple enough to add ? In which case, we don't really depend on the global conf. Any middleware is simply ignored (which becomes a noop if none is present), and we can configure the one we want at the router level only.

**Comment by ldez** [comment]
I think that the answer to this problem is the same as the proposal "C" inside https://github.com/traefik/traefik/issues/5630#issuecomment-593628496

**Comment by toxic0berliner** [comment]
Thanks a lot @nmengin for the clear explanation.
I do disagree with the decision mainly because I do still have the need for this and there are inevitable dependencies between dynamic and static configs anyway, but I'm respecting your decision.
I am very thankful the issue was considered, discussed, even if refused.
