### ISSUE TITLE
failed to download goreleaser binary

### ISSUE THREAD

**Issue by handsomecheung** [traefik/traefik#8657]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

 just ran `make` command.

### What did you see instead?

It failed when downloading goreleaser binary. The error log is as below:

```
#9 7.300 goreleaser/goreleaser err hash_sha256_verify checksum for '/tmp/tmp.ejaGmh/goreleaser_Linux_x86_64.tar.gz' did not verify 4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71
#9 7.300 5847d0acf29a69549e98408b7c55ccb3fb8586b1eb5e61a89ba246079d31b3be vs 4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71
```

The error line(in build.Dockerfile):
```
RUN curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
```

Root cause:
 
goreleaser.sh uses `grep` to partial match the package's checksum in checksum.txt. Recently `sbom` packages are added to checksum.txt, then two checksums are found.

cat checksum.txt:
```
4e50446e7d53b0d9e544a119bba53e8c47ab32f06aaeea992fb42699594437d9  goreleaser_Linux_arm64.tar.gz.sbom
4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71  goreleaser_Linux_x86_64.tar.gz
4f9b0f4ae1cebc6caa407deff7502a61a94ff545444265f91f68abbcfe345403  goreleaser_Darwin_all.tar.gz.sbom
5847d0acf29a69549e98408b7c55ccb3fb8586b1eb5e61a89ba246079d31b3be  goreleaser_Linux_x86_64.tar.gz.sbom
```

grep "goreleaser_Linux_x86_64.tar.gz" checksum.txt 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1: 
```
4ef68da9014df222c94ccefa02b01fdf96d414c1c775dbee5fadda53cd74ff71 
5847d0acf29a69549e98408b7c55ccb3fb8586b1eb5e61a89ba246079d31b3be 
```

As mentioned in that script, `this script is deprecated, please do not use it anymore. check https://github.com/goreleaser/godownloader/issues/207`. `goreleaser.sh` is not supported officially, we should change the way traefik installs golang binary.

### What version of Traefik are you using?

latest master branch. 
commit id: da092e653d1ff78aaeb333e445b2275e09670e7d
commit message: Prepare release v2.6.0-rc1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

the problem is already fixed https://github.com/traefik/traefik/pull/8652
