### ISSUE TITLE
Docs: Missing creation of an ingress class

### ISSUE THREAD

**Issue by SchoolGuy** [traefik/traefik#8669]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Create a certificate via Let's Encrypt (Staging) and cert-manager.

### What did you see instead?

Problem: When using a `ingressClass` filter the Ingresses created by cert-manager are not getting picked up by Traefik. Events are shown as skipped in the DEBUG log.

Solution: Create a namespace object and Traefik picks the events up correctly.

I found this out because I read the integration tests in PR: https://github.com/traefik/traefik/pull/7915

### What version of Traefik are you using?

2.5.0

### What is your environment & configuration?

- k3s 1.22.3
- cert-manager 1.6.1

**Comment by kevinpollet** [comment]
Hey @SchoolGuy and thanks for your interest in Traefik,

In cert-manager, it is possible to specify the `ingressClass` that will be used to solve challenges for this ingress (see https://cert-manager.io/v1.6-docs/usage/ingress/#supported-annotations, the annotation is named `acme.cert-manager.io/http01-ingress-class`). So Traefik should be able to pick up those ingresses automatically.

According to this, we will close this issue. Feel free to reopen it if we are missing something.
