### ISSUE TITLE
Traefik version 2.4.8 Datadog tracer not setting parent_id for

### ISSUE THREAD

**Issue by ZStriker19** [traefik/traefik#8675]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Hi Traefik, 

I work for Datadog and a customer reached about an issue with metrics calculation. Essentially after digging into it we found the issue was that because the Traefik root level spans only sometimes had `parent_id: 0` set on them, we were missing them in our metrics calculations. When the customer upgraded from 2.4.8 to 2.5.1, the issue went away. The metrics looked (and continue to look) correct, and I could no longer find any spans missing `parent_id: 0`.  

Looking through your codebase I couldn't find a reason that this upgrade could've fixed the issue, you don't look to have upgraded the Datadog Go tracer being used, I don't see anything manually being done with parent ids, there are no release notes.

Do you have any idea why this upgrade may have started the tracer correctly adding the parent_id tag when it's the root span?

### What did you see instead?

Top level Traefik spans missing `parent_id: 0`

### What version of Traefik are you using?

2.4.8 and 2.5.1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by kevinpollet** [comment]
Hello @ZStriker19,

We looked again at the changes we made between [v2.4.8...v2.5.1](https://github.com/traefik/traefik/compare/v2.4.8...v2.5.1) but we are unable to figure out what fixed the issue. The only change we made is to use the `DATADOG` env variables for the tracer but this seems not related, so what you are seeing might be a fortunate side-effect of another change.

If you are able to figure out what fixed the issue, please let us know!

Thanks again for your interest in Traefik!
