### ISSUE TITLE
Ability for plugins to export metrics

### ISSUE THREAD

**Issue by aqos156** [traefik/traefik#8685]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Title speaks for itself. Provide an API for plugins to export metrics. This would be usefull for example in the fail2ban plugin https://github.com/tomMoulard/fail2ban/issues/58 where the plugin cloud provide metrics about banned IPs, frequency, etc...

I wanted to add this to issue https://github.com/traefik/traefik/issues/8684, but I thought rather than providing new metrics export path, the current traefik implementation of metrics could be somehow used.

**Comment by WDaan** [comment]
Yes! This would be a great addition. I currently have to hack my way around it by pushing it to an external service.

**Comment by emilevauge** [comment]
Hello here, after discussing this with the maintainers, we came into the conclusion that we can't imagine an easy way to implement this. Additionaly, the demand for this is quite low. Therefore, we are closing this proposal.
Thanks for your contribution 🙏
