### ISSUE TITLE
Traefik ingress doesnt use the default certs configured.

### ISSUE THREAD

**Issue by udhayd** [traefik/traefik#8696]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Traefik was already setup with TLS and created an TLSOption KubernetesCRD object and referenced it in an Ingress.

I expected my Ingress to use the TLSOption but it does not.

### What did you see instead?

It complains about the SSL Certificate is not valid.

### What version of Traefik are you using?

2.5.3v

### What is your environment & configuration?

      - args:
        - --global.checknewversion=false
        - --global.sendanonymoususage=false
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        - --providers.kubernetesingress.ingressendpoint.publishedservice=ingress/ingress-traefik
        - --entrypoints.web.http.redirections.entryPoint.to=:443
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entrypoints.websecure.http.tls=true
        - --entrypoints.websecure.http.tls.options=default
        - --log.level=DEBUG

apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  labels:
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    argocd.argoproj.io/instance: ingress
    helm.sh/chart: traefik-10.3.4
  name: default
  namespace: ingress
spec:
  cipherSuites:
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  maxVersion: VersionTLS12
  minVersion: VersionTLS12

apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  labels:
    argocd.argoproj.io/instance: ingress
  name: default
  namespace: ingress
spec:
  defaultCertificate:
    secretName: default-cert-tls

### If applicable, please paste the log output in DEBUG level

time="2022-01-13T09:55:55Z" level=debug msg="Creating middleware" middlewareType=Pipelining routerName=longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes serviceName=longhorn-longhorn-frontend-80 entryPointName=metrics middlewareName=pipelining
time="2022-01-13T09:55:55Z" level=debug msg="Creating middleware" middlewareName=metrics-service middlewareType=Metrics entryPointName=metrics routerName longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes serviceName=longhorn-longhorn-frontend-80
time="2022-01-13T09:55:55Z" level=debug msg="Creating load-balancer" entryPointName=metrics routerName=longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes serviceName=longhorn-longhorn-frontend-80
time="2022-01-13T09:55:55Z" level=debug msg="Creating server 0 http://100.64.1.87:8000" serviceName=longhorn-longhorn-frontend-80 serverName=0 entryPointName=metrics routerName=longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes
time="2022-01-13T09:55:55Z" level=debug msg="Added outgoing tracing middleware longhorn-longhorn-frontend-80" middlewareType=TracingForwarder entryPointName=metrics routerName=longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes middlewareName=tracing
time="2022-01-13T09:55:55Z" level=debug msg="Skipping ingress status update" namespace=longhorn ingress=longhorn-ingress
time="2022-01-13T09:55:55Z" level=debug msg="Skipping ingress status update" namespace=longhorn ingress=longhorn-ingress
time="2022-01-13T09:55:55Z" level=debug msg="Creating middleware" middlewareName=pipelining middlewareType=Pipelining entryPointName=websecure routerName=websecure-longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes serviceName=longhorn-longhorn-frontend-80
time="2022-01-13T09:55:55Z" level=debug msg="Creating middleware" entryPointName=websecure routerName=websecure-longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes serviceName=longhorn-longhorn-frontend-80 middlewareName=metrics-service middlewareType=Metrics
time="2022-01-13T09:55:55Z" level=debug msg="Creating load-balancer" serviceName=longhorn-longhorn-frontend-80 entryPointName=websecure routerName=websecure-longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes
time="2022-01-13T09:55:55Z" level=debug msg="Creating server 0 http://100.64.1.87:8000" routerName=websecure-longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes serviceName=longhorn-longhorn-frontend-80 entryPointName=websecure serverName=0
time="2022-01-13T09:55:55Z" level=debug msg="Added outgoing tracing middleware longhorn-longhorn-frontend-80" routerName=websecure-longhorn-ingress-longhorn-longhorn-new-aws-domain@kubernetes middlewareName=tracing middlewareType=TracingForwarder entryPointName=websecure
time="2022-01-13T09:55:55Z" level=debug msg="Adding route for longhorn.new.aws.domain with TLS options default" entryPointName=websecure

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
