### ISSUE TITLE
Traefik is logging the Consul ACL token

### ISSUE THREAD

**Issue by ibrahimalihc** [traefik/traefik#8698]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

During startup, Traefik logs the configuration for each configuration discovery provider. When an [ACL token](https://doc.traefik.io/traefik/providers/consul-catalog/#token) is configured on the Consul Catalog provider, the token gets emitted in the logs.

### What did you see instead?

The ACL token should not be emitted in the logs.

### What version of Traefik are you using?

```
Version:      2.5.5
Codename:     brie
Go version:   go1.17.5
Built:        2021-12-10T17:00:35Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Relevant bit of configuration:
```yaml
[providers]
  [providers.consulCatalog]
    connectAware = true
    refreshInterval = "5s"

    [providers.consulCatalog.endpoint]
      scheme  = "https"
      address = "example.com:8501"
      token   = "REDACTED"

      [providers.consulCatalog.endpoint.tls]
        ca = "local/ca-certs.pem"
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

> Starting provider *consulcatalog.Provider {"endpoint":{"address":"example.com:8501","scheme":"https","token":"REDACTED","tls":{"ca":"local/ca-certs.pem"}},"prefix":"traefik","refreshInterval":"5s","connectAware":true,"serviceName":"traefik"}"

**Comment by tomMoulard** [comment]
Closed by #8699
