### ISSUE TITLE
Support for TLS certificate thumbprints in PassTLSClientCert middleware

### ISSUE THREAD

**Issue by frohoff** [traefik/traefik#8710]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Many security-related use cases call for the use of a certificate "thumbprint" (`SHA1` or `SHA256` hash of the `DER`-encoded certificate) to be able to observe or preclude certificate changes over time. The [OAuth mTLS "Certificate-Bound Access Tokens" spec](https://datatracker.ietf.org/doc/html/rfc8705#section-3.1) is one example of this. 

Obviously downstream proxy middlewares or applications could already consume the certificate in the form of the [PEM currently supported by the `PassTLSClientInfo` middleware](https://doc.traefik.io/traefik/middlewares/http/passtlsclientcert/#pem) but this would require parsing, converting, and hashing the certificate on every request and/or complicated internal caching. 

It seems like the traefik core could probably manage this much more efficiently, lazily calculating and caching the thumbprint value only when configured in the middleware and passing the reused value downstream as a component in the `X-Forwarded-Tls-Client-Cert-Info` request header.

**Comment by rtribotte** [comment]
Hello @frohoff,

Thanks for your interest in Traefik!

We already declined a pull request that was introducing a similar feature to the PassTLSClientCert middleware (see [this comment](https://github.com/traefik/traefik/pull/8404#issuecomment-934556642)).

Furthermore, Traefik is stateless and does not cache anything, hence caching client certificate thumbprints is not something we want to introduce.

Accordingly, we are declining this proposal.
