### ISSUE TITLE
traefik v2.3  Load balancing drr

### ISSUE THREAD

**Issue by xuexue1208** [traefik/traefik#8723]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

current version  traefik v2.3.7 ,How to configure DRR load balancing algorithm in this version ；

In version 1.7, the DRR load balancing algorithm can be added to the annotations of the service： traefik.backend.loadbalancer.method=drr

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by xuexue1208** [comment]
I need help

**Comment by jakubhajek** [comment]
Hello @xuexue1208 

Thanks for your using Traefik and asking the question here.
However, there is no DRR (Dynamic Round Robin) algorithm implemented in Traefik v2.  You can try to use WRR (weighted round-robin) instead of DRR. Is there any specific requirement why you need to configure DRR?
