### ISSUE TITLE
Add s390x arch support

### ISSUE THREAD

**Issue by rohitsakala** [traefik/traefik#8728]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Can you add s390x support for Traefik? Is it planned ?

https://github.com/traefik/traefik-library-image/issues/20

PR - https://github.com/traefik/traefik/pull/8729

**Comment by traefiker** [comment]
Closed by #8729.
