### ISSUE TITLE
Traefik Docs do not reflect latest version/changes (regarding http3)

### ISSUE THREAD

**Issue by Histalek** [traefik/traefik#8733]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

- prepared to update to Traefik v2.6.0
  - looked at the [migrations page](https://doc.traefik.io/traefik/migration/v2/) to check for possibly breaking changes. nothing listed
- updated to Traefik v2.6.0
  - Traefik did not start
  - `2022/01/25 08:15:20 command traefik error: field not found, node: enableHTTP3` was the only error logged
- double checked the [relevant documentation](https://doc.traefik.io/traefik/routing/entrypoints/#enablehttp3), `enableHTTP3` is still listed and seems to be the correct usage
- checked [changelog](https://github.com/traefik/traefik/releases/tag/v2.6.0) for changes regarding http3
  - found [this PR](https://github.com/traefik/traefik/pull/8131) and looked at the changes
    - see that `enableHTTP3` doesn't exist anymore
    - see that the changed documentation from that PR is not reflected in the docs
    
i have **not** checked if the outdated documentation is specific to the http3 changes only or if other changes are also affected

### What did you see instead?

Outdated information regarding http3 in the traefik documentation https://doc.traefik.io/traefik/routing/entrypoints/#enablehttp3

### What version of Traefik are you using?

v2.6.0

### What is your environment & configuration?

not relevant

**Comment by ldez** [comment]
Hello,

Thank you for reporting, the documentation will be updated quickly, it was a misconfiguration of our CI.
