### ISSUE TITLE
Include domain name for which "Cannot retrieve the ACME challenge for token XYZ: cannot find challenge for token XYZ"

### ISSUE THREAD

**Issue by jze2** [traefik/traefik#8738]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I expect to see which domain is it related to (might be some typo in K8S environment deployment configuration or missing override of a template, which current useless log message doesn't help to find).

**Comment by traefiker** [comment]
Closed by #8740.
