### ISSUE TITLE
Error subset not found for monitoring/grafana

### ISSUE THREAD

**Issue by waterdrop01** [traefik/traefik#8743]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I ran `helm upgrade grafana grafana/grafana --version 6.21.1 --values helm-grafana-monitoring-values.yml`.

This new helm chart introduced a breaking change ([see issue](https://github.com/grafana/helm-charts/issues/996)) by adding a new Label `app.kubernetes.io/component=grafana`.

### What did you see instead?

My grafana dashboard was not available anymore `404 not found`.

Traefik logs show an error:
```
level=error msg="subset not found for monitoring/grafana" providerName=kubernetescrd ingress=grafana-tls namespace=monitoring
```

And the grafana endpoint is now `<none>`:

`kubectl get endpoints -n monitoring`
```
NAME                            ENDPOINTS                                               AGE
grafana                         <none>                                                  7m19s
```
I rolled back using Helm, but still, the issue persists: `kubectl describe endpoints grafana -n monitoring`:
```
Name:         grafana
Namespace:    monitoring
Labels:       app.kubernetes.io/component=grafana
              app.kubernetes.io/instance=grafana
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=grafana
              app.kubernetes.io/version=8.3.0
              helm.sh/chart=grafana-6.17.10
Annotations:  <none>
Subsets:
Events:  <none>
```

### What version of Traefik are you using?

Traefik 2.6.0

### What is your environment & configuration?

Kubernetes

### If applicable, please paste the log output in DEBUG level

```
2022-01-27T15:40:03.069559500Z time="2022-01-27T15:40:03Z" level=error msg="subset not found for monitoring/grafana" providerName=kubernetescrd ingress=grafana-tls namespace=monitoring
```

**Comment by kevinpollet** [comment]
Hello @waterdrop01 and thanks for your interest in Traefik,

This issue is not related to Traefik but to the grafana deployment. The error `subset not found for monitoring/grafana` is raised because no endpoints are matching the grafana service (used to route requests to the corresponding pod IPs).

As you said this might be related to the label change introduced in the grafana deployment. Maybe the grafana service is not matching any pod because of this new label.
