### ISSUE TITLE
ipWhiteList - Variable depth in X-Forwarded-For header

### ISSUE THREAD

**Issue by jfroment** [traefik/traefik#8745]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hello,

I have the use-case where i want to use IP whitelisting on a specific path based on the original Source IP range. I want to allow local ranges (10.0.0.0/8, 192.168.0.0/24...) + some other ones (accessible from the outside world).

Problem is we have a WAF (Imperva) which adds a source IP in the X-Fowarded-For header if the traffic comes from the Internet, but we do not have this IP if the traffic comes from the local network.

So the whitelisting rule has a variable depth which I do not know in advance, obviously.
![image](https://user-images.githubusercontent.com/2869798/151592671-cb20d0a0-4a8c-4dbf-8284-44f1991b4860.png)
On this illustration, all I want is to make the middleware control the "last" (when reading from right to left, like Traefik) IP,
which is the green one above.

I cannot skip Imperva ranges (using ``ipStrategy.excludedIPs`` in the middleware) because doing so, the depth parameter won't be taken into account, and I cannot add local ranges to the ``excludedIPs`` because they are part of the whitelisting rule (I want to allow them if they match the Client source IP).

Could we add some mechanism which allow Traefik middleware to read from left to right? Or to match only on the "deepest" source IP in the header?
I tried with multiple middlewares (each one using a different depth and allowing a range group) but then I hit [this issue](https://github.com/traefik/traefik/issues/6007).

**Traefik version: 2.6.0**

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
