### ISSUE TITLE
Annotation keys for kubernetes must be less than 63 characters - Some Traefik keys are longer

### ISSUE THREAD

**Issue by JohnnyMoonlight** [traefik/traefik#8762]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I tried to set the following annotation in the rancher ui for my treafik ingress:
traefik.http.middlewares.testheader.headers.accesscontrolallowmethods

### What did you see instead?

I receive the following error:

[...] metadata.annotations: Invalid value: "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods": name part must be no more than 63 characters 

The k8s docu for says the following: 

> The name segment is required and must be 63 characters or less[...].

[Source]( https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)

### What version of Traefik are you using?

2.4.8I

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by JohnnyMoonlight** [comment]
Is this somehow possible? Am I mixing things up? I cannot imagine nobody has stumbled over this issue before.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
