### ISSUE TITLE
Import the redigo package in traefik plugins prompts an error

### ISSUE THREAD

**Issue by kk-kwok** [traefik/traefik#8780]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Import the redigo package in traefik plugins prompts an error, can not start traefik

```
# plugins-local/src/infra/traefik-plugins/ratelimiter/leakybucket.go
import "github.com/gomodule/redigo/redis"
```

### What did you see instead?

```
2022/02/16 17:16:57 traefik.go:79: command traefik error: infra/traefik-plugins/ratelimiter: failed to import plugin code "infra/traefik-plugins/ratelimiter": 1:21: import "infra/traefik-plugins/ratelimiter" error: plugins-local/src/infra/traefik-plugins/ratelimiter/leakybucket.go:5:2: import "github.com/gomodule/redigo/redis" error: plugins-local/src/infra/traefik-plugins/ratelimiter/vendor/github.com/gomodule/redigo/redis/conn.go:236:20: cannot use type func(*net.Dialer, context.Context, string, string) (net.Conn, error) as type func(context.Context,string,string) (net.Conn,error) in assignment
```

### What version of Traefik are you using?

2.6.0

### What is your environment & configuration?

```yaml
experimental:
    rateLimit:
      moduleName: infra/traefik-plugins/ratelimiter
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @kk-kwok,

Thanks for your interest Traefik!

Unfortunately, the appropriate place to open bug reports related to plugins is the [Yaegi repository](https://github.com/traefik/yaegi).

Please, open a new issue on the [Yaegi repository](https://github.com/traefik/yaegi). 

Accordingly, I will close this issue.
