### ISSUE TITLE
Support configuring a delay for ACME challenge requests

### ISSUE THREAD

**Issue by consideRatio** [traefik/traefik#8803]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

# Summary

When Traefik runs in a k8s Pod's container and quickly after starting up requests an ACME HTTP-01 challenge from an ACME server, the k8s cluster may not be quick enough to setup the required networking for the k8s Pod's container where Traefik runs, to accept an incoming connection by the ACME server.

Due to that, I propose an opt-in configurable feature that anyone deploying Traefik to a k8s Pod could make use of.

## Proposed feature

I propose adding logic for a configurable initial time period, where Traefik won't request an ACME challenge from an ACME server. This configuration would be relevant for both HTTP-01 challenges and TLS-ALPN-01, as both of them requires Traefik to respond to a new connection.

The configuration would look like this in YAML.

```yaml
certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge:
        initialDelaySeconds: 10  # new configuration, defaults to 0
      httpChallenge:
        initialDelaySeconds: 10  # new configuration, defaults to 0
```

## Suggested config name

I suggested the name `initialDelaySeconds` as it is a quite descriptive name which is also for example used by Kubernetes when configuring a "[Probe](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#probe-v1-core)" to check readiness/liveness.

I suggest it is nested under `tlsChallenge` and `httpChallenge` respectively.

## Suggested default value

By defaulting the configuration's default value to 0, we would retain the current behavior without introducing a change of behavior. Having no delay seems to me like a good default as I only see a value for this configuration as a mitigation strategy of a known common situation.

## Scope of problem

I'm very confident this caused an issue I reproduced when I setup a Google cloud managed k8s cluster (GKE) with default settings as well as with settings where Calico was installed. I observed that sleeping for ten seconds before starting the Traefik software within the Pod, the ACME challenges initiated succeeded reliably 10/10 times, while failed 9/10 times or so when I had no delay.

Looking at issues reported in Traefik about this I found #8786 which I bet is what this feature would help avoid as well.

As this issue presented itself in a big cloud providers managed k8s cluster service, I would guess it isn't that uncommon.

## Background of why networking can take time in k8s

While each k8s cluster can manage networking in different ways, the [GKE clusters rely on `kube-proxy`](https://cloud.google.com/kubernetes-engine/docs/concepts/network-overview#kube-proxy). When a k8s Pod is scheduled to run on a specific node, it gets an IP address. kube-proxy, which runs on each node in a k8s cluster, will then update the nodes iptables to be able to route traffic to the pod. I think this is what can take, for kube-proxy to become aware it should setup an iptable rule.

I also noted that whenever i started a Traefik pod that had a natural delay before the container started running that was related to pulling a docker image needed to the node, I didn't have errors - only when I restarted Traefik on a node where the image was already available - because pulling a new image acted as a delay after the Pod had received an IP!

## Possible workaround tricks

See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2601#issuecomment-1050406952 for the ideas of a) inducing a dummy delay after a k8s Pod is scheduled by pulling a new Traefik image, and b) sleeping before starting the traefik software.

A downside to sleeping before starting the Traefik software is that its easy to do it wrong and fail to propegate SIGTERM signals onwards to Traefik. A symptom of failing to do that is that `kubectl delete pod <pod-not-caring-about-SIGTERM-signal>` would fail to stop on its own and be forcefully deleted after 30 seconds.

The main drawback of these workarounds are that Traefik would be slow to start, even though it didn't need to be slow, as it only sometimes need to request an ACME challenge on startup depending on if it had a certificate available in its storage already.

**Comment by Economax** [comment]
Pinging just to support this. Was a bit of a pain to debug, since I was deploying traefik as part of a JupyterHub Helm chart.

**Comment by ldez** [comment]
hello @gregingenii,

with DNS challenge you can control `<provider>_POLLING_INTERVAL` and `<provider>_PROPAGATION_TIMEOUT`.
See the additional configuration on this page https://doc.traefik.io/traefik/v2.6/https/acme/#dnschallenge

DNS challenge is completely different than the HTTP and TLS challenge.

**Comment by consideRatio** [comment]
@ldez do you think this is a viable feature to implement and maintain for Traefik? To have some tentative agreement that the feature could be worth implementing and maintaining would make for example me more interested in putting in work to open a PR.

**Comment by Martomate** [comment]
I found another workaround: add an initContainer with a `sleep 5`.

If you use helm you can add the following to the values.yaml file:
```
deployment:
  initContainers:
    - name: startup-delay
      image: busybox:1.31.1
      command: ['sh', '-c', 'sleep 5']
```

The initContainer will run (and complete) before any other containers are started in the pod.

**Comment by kevinpollet** [comment]
Hello @consideRatio,

Thanks for your interest in Traefik,

After discussing this proposal, we think that introducing a specific option to fix the wrong orchestrator behavior (starting Traefik without having the network stack working) is something we are reluctant to do, for the following reason:

We think that the `initContainer` workaround, to introduce a delay is something common in the k8s world, as explained in https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#using-init-containers:

> Because init containers run to completion before any app containers start, init containers offer a mechanism to block or delay app container startup until a set of preconditions are met. Once preconditions are met, all of the app containers in a Pod can start in parallel.

According to this, we will decline this proposal.

**Comment by consideRatio** [comment]
Thank you for the followup @kevinpollet, it is always reasonable to not add workarounds for others software failures in my mind - as it can lead to unsustainable amounts of maintenance.

**Comment by snickell** [comment]
@kevinpollet appreciate referencing the initContainer workaround, and appreciate the KISS approach traefik has taken and continues to apply here, thanks for all your work! 🤙🏽
