### ISSUE TITLE
acme.json not being created in pod (running on Kubernetes): no such file or directory

### ISSUE THREAD

**Issue by johanneskastl** [traefik/traefik#8804]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Github Issue at the traefik-helm-chart repository: https://github.com/traefik/traefik-helm-chart/issues/564

As this does not look like it is caused by the helm chart, I am opening up this bug report.

I am running traefik in a k3s kubernetes cluster, installed via helm (not using the traefik preinstalled by k3s).
I tried to configure a certificateresolver using the following content in the values.yaml:
```
additionalArguments:
  - --certificatesresolvers.hetzner-staging.acme.caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
  - --certificatesresolvers.hetzner-staging.acme.email="le-ojkastl@ojkastl.de"
  - --certificatesresolvers.hetzner-staging.acme.storage="/data/acme.json"
```

### What did you see instead?

I get the following error during startup:
```
time="2022-02-25T07:29:41Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
```

This happens:
- whether or not I am enabling persistence (so the acme.json would be in a volume and would be kept and not recreated)
- whether or not I use a sidecar container to fix the permissions (see #6972)
- whether or not I am using the annotations or fsGroup settings that were recommended in earlier bug reports for file permission problems 

### What version of Traefik are you using?

Traefik 2.6.1 from helm chart version traefik-10.14.2

### What is your environment & configuration?

`values.yaml`:
```
additionalArguments:
  - --certificatesresolvers.hetzner-staging.acme.caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
  - --certificatesresolvers.hetzner-staging.acme.email="le-ojkastl@ojkastl.de"
  - --certificatesresolvers.hetzner-staging.acme.storage="/data/acme.json"
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-02-24T21:32:56Z" level=info msg="Configuration loaded from flags."
time="2022-02-24T21:32:56Z" level=info msg="Traefik version 2.6.1 built on 2022-02-14T16:50:25Z"
time="2022-02-24T21:32:56Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true,\"sendAnonymousUsage\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"metrics\":{\"address\":\":9100/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"traefik\":{\"address\":\":9000/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"web\":{\"address\":\":8000/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"websecure\":{\"address\":\":8443/tcp\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"kubernetesIngress\":{\"ingressEndpoint\":{\"publishedService\":\"traefik-system/traefik\"}},\"kubernetesCRD\":{\"allowCrossNamespace\":true}},\"api\":{\"dashboard\":true},\"metrics\":{\"prometheus\":{\"buckets\":[0.1,0.3,1.2,5],\"addEntryPointsLabels\":true,\"addServicesLabels\":true,\"entryPoint\":\"metrics\"}},\"ping\":{\"entryPoint\":\"traefik\",\"terminatingStatusCode\":503},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"},\"certificatesResolvers\":{\"hetzner-staging\":{\"acme\":{\"email\":\"\\\"le-ojkastl@ojkastl.de\\\"\",\"caServer\":\"\\\"https://acme-staging-v02.api.letsencrypt.org/directory\\\"\",\"storage\":\"\\\"/data/acme.json\\\"\",\"keyType\":\"RSA4096\",\"certificatesDuration\":2160}}},\"pilot\":{\"dashboard\":true}}"
time="2022-02-24T21:32:56Z" level=info msg="Stats collection is enabled."
time="2022-02-24T21:32:56Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2022-02-24T21:32:56Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2022-02-24T21:32:56Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2022-02-24T21:32:56Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
time="2022-02-24T21:32:56Z" level=debug msg="Configured Prometheus metrics" metricsProviderName=prometheus
time="2022-02-24T21:32:56Z" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-02-24T21:32:56Z" level=debug msg="Start TCP Server" entryPointName=web
time="2022-02-24T21:32:56Z" level=debug msg="Start TCP Server" entryPointName=websecure
time="2022-02-24T21:32:56Z" level=debug msg="Start TCP Server" entryPointName=traefik
time="2022-02-24T21:32:56Z" level=debug msg="Start TCP Server" entryPointName=metrics
time="2022-02-24T21:32:56Z" level=info msg="Starting provider *traefik.Provider"
time="2022-02-24T21:32:56Z" level=debug msg="*traefik.Provider provider configuration: {}"
time="2022-02-24T21:32:56Z" level=info msg="Starting provider *ingress.Provider"
time="2022-02-24T21:32:56Z" level=debug msg="*ingress.Provider provider configuration: {\"ingressEndpoint\":{\"publishedService\":\"traefik-system/traefik\"}}"
time="2022-02-24T21:32:56Z" level=info msg="Starting provider *crd.Provider"
time="2022-02-24T21:32:56Z" level=info msg="ingress label selector is: \"\"" providerName=kubernetes
time="2022-02-24T21:32:56Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetes
time="2022-02-24T21:32:56Z" level=debug msg="*crd.Provider provider configuration: {\"allowCrossNamespace\":true}"
time="2022-02-24T21:32:56Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2022-02-24T21:32:56Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2022-02-24T21:32:56Z" level=warning msg="Cross-namespace reference between IngressRoutes and resources is enabled, please ensure that this is expected (see AllowCrossNamespace option)" providerName=kubernetescrd
time="2022-02-24T21:32:56Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-02-24T21:32:56Z" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
time="2022-02-24T21:32:56Z" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"ping\":{\"entryPoints\":[\"traefik\"],\"service\":\"ping@internal\",\"rule\":\"PathPrefix(`/ping`)\",\"priority\":2147483647},\"prometheus\":{\"entryPoints\":[\"metrics\"],\"service\":\"prometheus@internal\",\"rule\":\"PathPrefix(`/metrics`)\",\"priority\":2147483647}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{},\"ping\":{},\"prometheus\":{}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2022-02-24T21:32:56Z" level=debug msg="No default certificate, generating one" tlsStoreName=default
```

**Comment by mpl** [comment]
This error most likely happens because the /data directory does not exist (traefik does not create if for you). Have you checked whether that's the case? Have you tried storing it in another directory that you are sure exists? (e.g. in /tmp)

**Comment by johanneskastl** [comment]
Thanks for the reply.

Please check https://github.com/traefik/traefik-helm-chart/issues/564#issuecomment-1050605511

The directory IS being created. But the file is not being created. But the pod's user could create it.

```
$ kubectl exec -it traefik-7b67c464fd-7tfqq -- sh
/ $ ls -lhd /data/
drwxrwsrwx    1 root     65532          0 Feb 25 07:29 /data/
/ $ ls -lh /data/
total 0      
/ $ touch /data/test
/ $ ls -lh /data/
total 0      
-rw-r--r--    1 65532    65532          0 Feb 25 07:32 test
/ $ 
```

**Comment by johanneskastl** [comment]
> This error most likely happens because the /data directory does not exist (traefik does not create if for you). Have you checked whether that's the case? Have you tried storing it in another directory that you are sure exists? (e.g. in /tmp)

I did check, and it did not work:

```
time="2022-02-25T14:13:12Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/tmp/acme.json\": no such file or directory"

```

**Comment by rawkode** [comment]
Confirmed. I can reproduce and can’t get Traefik to work as expected.

**Comment by jakubhajek** [comment]
Hello!

I am just trying to reproduce the issue. I use the EKS cluster and I deployed Traefik using the official Helm Chart with the following values:

```yaml
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/*"]
      volumeMounts:
        - name: data
          mountPath: /data

additionalArguments:
  - "--certificatesresolvers.hetznerstaging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.hetznerstaging.acme.dnschallenge=true"
  - "--certificatesresolvers.hetznerstaging.acme.dnschallenge.provider=hetzner"
  - "--certificatesresolvers.hetznerstaging.acme.dnschallenge.resolvers=192.168.99.1"
  - "--certificatesresolvers.hetznerstaging.acme.email=<replace-me>"
  - "--certificatesresolvers.hetznerstaging.acme.dnschallenge.delaybeforecheck=10"
  - "--certificatesresolvers.hetznerstaging.acme.storage=/data/acme.json"

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  annotations: {
    "pv.beta.kubernetes.io/gid": "65532"
  }
podSecurityContext:
  fsGroup: 65532
```

```
❯  k logs traefik-dbc8d7655-bv9ss -c traefik
time="2022-03-03T08:54:47Z" level=info msg="Configuration loaded from flags."
```

```
❯ k exec -it traefik-dbc8d7655-bv9ss -c traefik -- ls -la /data/acme.json
-rw-------    1 65532    65532            0 Mar  3 08:54 /data/acme.json
```

My cluster is using the default storage class provisioned via `kubernetes.io/aws-ebs`.  
Seems that it works as expected or maybe I overlooked something from the previous posts?
@rawkode @johanneskastl  Would you please let me know what is environment spec you used to reproduce that issue?

Now, I am trying with K3S and the local provisioner.

**Comment by johanneskastl** [comment]
Hi @jakubhajek thanks for testing. Indeed it looks like it is working in your case.

Not sure where @rawkode tested, but I ran this on k3s with local-path-provisioner. So it would be good if you could test that, too.
I tested using k3s 1.22.6 (IIRC) and 1.21.X.
I can test again today on k3s 1.23.3.

Technically, I think those parameters are no longer needed, I just found them in old issues and tried them:
```
  annotations: {
    "pv.beta.kubernetes.io/gid": "65532"
  }
podSecurityContext:
  fsGroup: 65532
```

**Comment by johanneskastl** [comment]
Oh, can you check if this works on first installation without the initContainer? At that point there should be nothing in `/data/`, so it should actually not do anything, but just to be sure.

**Comment by johanneskastl** [comment]
When using the initContainer code you postet, that initContainer runs into a Init:CrashLoopError. As there is nothing in /data/ that can be `chmod`-ed (there is an asterisk after `/data/`).
I am surprised this worked in your environment.

And I just re-tested on k3s 1.23.3:
```
time="2022-03-03T09:55:51Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
```

**Comment by jakubhajek** [comment]
The file `acme.json` is being created by Traefik by the following argument ```--certificatesresolvers.myresolver.acme.storage=acme.json`. The `initContainers` has been added since in specific circumstances the permission of that file was set too wide.  It has no impact on the process of creating that file. 

Traefik does not create the directory `/data`, the direcotry is created by `mountPath` in `spec.containers.volumeMounts`.

**Comment by johanneskastl** [comment]
> The file `acme.json` is being created by Traefik by the following argument ```--certificatesresolvers.myresolver.acme.storage=acme.json`.

It should, yes :-)

>  The `initContainers` has been added since in specific circumstances the permission of that file was set too wide. It has no impact on the process of creating that file.

I know, I read the issue. It is just that apparently the chmod in the initContainer does not fail on AKS while it fails hard on K3s with local-path. Which is another topic, but still interesting...

> Traefik does not create the directory `/data`, the directory is created by `mountPath` in `spec.containers.volumeMounts`.

I had even tested without persistence (to rule out storage as cause) putting the acme.json into `/tmp/` which is exsting. But even that failed.

**Comment by jakubhajek** [comment]
@johanneskastl, we have discussed that issue internally and we believe that the issue is not directly related to Traefik since we are discussing the `acme.json` permissions and `initContainers` which is a feature belonging to the Traefik Helm Chart. Thus, we suggest moving our conversation to the Helm Chart and re-open [your initial issue](https://github.com/traefik/traefik-helm-chart/issues/564) on that repo. 
Let us know your opinion. 
Thanks!

**Comment by johanneskastl** [comment]
> since we are discussing the `acme.json` permissions and `initContainers` which is a feature belonging to the Traefik Helm Chart.

Actually, the initContainer is just a side note. It was introduced for another issue, and does not solve "my" issue. It does not influence it at all. I  just thought it might help in this case.

Did you check on k3s using local-path? Did it work for you there?

**Comment by johanneskastl** [comment]
OK, I did some more debugging:
- I trimmed down the Traefik installation to the bare minimum
  - no service account
  - no PVC
  - no ingress, nothing that the helm chart might or might not create
- I used an `emtpyDir` for `/data/`
- see [this gist](https://gist.github.com/johanneskastl/75ebaf3f2ee898cf67afd3cce990f389) for the yaml file I used

The error still shows up there.
```
time="2022-03-03T14:49:55Z" level=error msg="The ACME resolver \"hetzner-staging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
```

```
$ kubectl exec -it traefik-747c58b4c5-ltm9t -- sh
/ $ ls -lhd /data/
drwxrwsrwx    1 root     65532          0 Mar  3 14:49 /data/
/ $ ls -lh /data/
total 0      
/ $ touch /data/test.txt
/ $ ls -lh /data/
total 0      
-rw-r--r--    1 65532    65532          0 Mar  3 14:55 test.txt
/ $
```

Removing the following options does not help:
```
        securityContext:                                                                      
          capabilities:                                                                       
            drop:
            - ALL
           readOnlyRootFilesystem: true
```

Of course, this deployment uses the defaults from the helm chart. 

To me it looks like this is still a problem in Traefik and not in the helm chart.
But that decision is up to you.

I just would like this to get solved, and help if I can.

**Comment by jakubhajek** [comment]
Hello @johanneskastl 

Thanks a lot for spending time on that issue. 

We also did our investigation and we found the root cause. The issue is in the configuration caused by double quotes for CLI arguments to configure certResolver in `additionalArguments` section.  While it is configured in that way, 

```yaml
 # don't double quote the CLI arguments
additionalArguments:
  - --certificatesresolvers.hetznerstaging.acme.storage="/data/acme.json"
```

the Helm will escape each of the values causing further issues with Traefik, such as: 

```
time="2022-03-04T12:11:09Z" level=info msg="Configuration loaded from flags."
time="2022-03-04T12:11:09Z" level=error msg="The ACME resolver \"hetznerstaging\" is skipped from the resolvers list because: unable to get ACME account: open \"/data/acme.json\": no such file or directory"
```

The `additionalArguments `has to be configured in the following way: 

```yaml
# This is correct
additionalArguments:
  - "--certificatesresolvers.hetznerstaging.acme.storage=/data/acme.json"
 ```

Based on our investigation we can say that this is a configuration issue.
It is neither Traefk nor Traefik Helm Chart related issue. 

Thanks!

**Comment by johanneskastl** [comment]
Thank you @jakubhajek for digging into this. I had noticed the escaped double quotes in the log, but thought this is due to `msg="..."` with the message being in quotes.
Must have been the bash guy in me that made me quote arguments to shell parameters... :-)

I can confirm that the error goes away once I either quote the entire line or omit the quotes completely.

Thanks a lot for your help!
