### ISSUE TITLE
Http to Https Redirect not working

### ISSUE THREAD

**Issue by hase808** [traefik/traefik#8806]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Global Http to Https Redirect not working. 

### What did you see instead?

Redirection-Error, no acess to the redirected page.

### What version of Traefik are you using?

traefik:latest
also checked other version, with the same result as described above.

### What is your environment & configuration?

version: "3.3"

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080" 
      - "443:443"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.ssl.acme.httpChallenge=true"
      - "--certificatesresolvers.ssl.acme.email=admin@example.com"
      - "--certificatesresolvers.ssl.acme.storage=/letsencrypt/acme.json"

    volumes:
      - /nfs/infra/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    deploy:  
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  web:
    external: true
  intern:
    external: true

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
