### ISSUE TITLE
Request for support of dynamic port mapping for healthcheck for marathon apps

### ISSUE THREAD

**Issue by bobbydixit** [traefik/traefik#8809]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### Context:
We expose 2 primary ports for any application that's deployed on marathon

- Application port - port on which all our consumer APIs are exposed out off
- Admin port - port where we expose out capabilities that service administrator can leverage, for this case we expose out health check for Marathon and Traefik to check the status of the application.

**How do we perform health checks today via marathon?**
While configuring our app on marathon we specify port mapping
```
[
      {
        "containerPort": 8080,
        "hostPort": 0,
        "labels": {},
        "name": "primary-port",
        "protocol": "tcp",
        "servicePort": 10010
      },
      {
        "containerPort": 8081,
        "hostPort": 0,
        "labels": {},
        "name": "admin-port",
        "protocol": "tcp",
        "servicePort": 10011
      }
    ]
```

Marathon while initiating the application on a Mesos slave, internally maps the port configuration to the ports available on Mesos slave, **making both the exposed ports dynamic and unique per instance**, and the same mapping is shared with LB, in this case, Traefik. Traefik via the port detection configuration that we specify maps the Server port to the dynamic port based on the port index of our choice.

Sample configuration specified as marathon lable for application
`traefik.http.services.serviceName.loadbalancer.server.port=index:0`
[Port detection Document](https://doc.traefik.io/traefik/user-guides/marathon/#port-detection)

### What's the ask?
Today traefik supports the following config for specifying port for marathon application:

- specify the port directly: `traefik.http.services.serviceName.loadbalancer.server.port=8080`
- specify a port index: `traefik.http.services.serviceName.loadbalancer.server.port=index:0`
- specify a port name: `traefik.http.services.serviceName.loadbalancer.server.port=name:http`

[Reference](https://doc.traefik.io/traefik/user-guides/marathon/#port-label-syntax) 

We would like the same capability extended to health check config for marathon apps and provide support for the following config;
- specify the port directly - _already supported_: `traefik.http.services.yourServiceName.loadbalancer.healthcheck.port=8080` 
- specify a port index: `traefik.http.services.yourServiceName.loadbalancer.healthcheck.port=index:0`  
- specify a port name: `traefik.http.services.yourServiceName.loadbalancer.healthcheck.port=name:http`
 
 Via extending similar logic used to power dynamic port mapping for Server Configuration for the health check.

**Comment by tfny** [comment]
Hey @bobbydixit, Thanks for your suggestion, we think it makes a lot of sense.  Unfortunately, this would not make it to our roadmap for a while as we are focused elsewhere.  If you or another community member would like to build it, let us know and we will work with you to make sure you have all the information needed so that it can be merged.  

We prefer to work with our community members at the beginning of the design process so that we can make sure that we are aligned and can move quickly with the review and merge process.  Let us know here or create a PR before you start and we will work with you there.  

Don’t forget to check out the [contributor docs] (https://github.com/traefik/contributors-guide/blob/master/pr_guidelines.md) and to link the PR to this issue.

**Comment by tfny** [comment]
Bobbydixit, 
Let's make a PR and move the conversation there.  That way when it is reviewed (not by me) all the information is in the same place for the reviewers.  :) Thanks!

**Comment by bobbydixit** [comment]
Sure, please give me till next week, running busy with some tasks, will try to make 1st round of changes and create a PR by next week for further discussion

**Comment by tfny** [comment]
Hey @bobbydixit, I was just following up to see if you are still interested. :)

**Comment by bobbydixit** [comment]
Hi @tfny , sorry this got pushed back in my pile and then it slipped my mind
I am still interested, picking this up on priority, I will try to share a PR by next week

**Comment by bobbydixit** [comment]
@tfny was working on PR for the same 
Have hit a roadblock, which I didn't notice initially while I was proposing the changes 

Following is the [ServersLoadBalancer](https://github.com/traefik/traefik/blob/f85f3b68aaf660e26296e99d97f134950d1e1cb8/pkg/config/dynamic/http_config.go#L149) in http_config.go

There are 2 components are key for this discussion 
`
	HealthCheck        *ServerHealthCheck  `json:"healthCheck,omitempty" toml:"healthCheck,omitempty" yaml:"healthCheck,omitempty" export:"true"`
	Servers []Server `json:"servers,omitempty" toml:"servers,omitempty" yaml:"servers,omitempty" label-slice-as-struct:"server" export:"true"`
`

For marathon, servers are added at [config.go](https://github.com/traefik/traefik/blob/master/pkg/provider/marathon/config.go#L142) from tasks defined in [application.go](https://github.com/gambol99/go-marathon/blob/master/application.go#L76) of go-marathon

So long story short 
1 task => 1 server, and for each server, we assign the port in [config.go](https://github.com/traefik/traefik/blob/f85f3b68aaf660e26296e99d97f134950d1e1cb8/pkg/provider/marathon/config.go#L313) 

so config `traefik.http.services.serviceName.loadbalancer.server.port=index:0 ` works for servers as though definition is global i.e. we are stating that all servers should use their port index 0 to receive user traffic, the above-mentioned function, based on the config, for each task take out the port of index 0, and assign it to server.

I was initially thinking I would extend the same to health check, but I can't as health check is a parent property of [ServersLoadBalancer](https://github.com/traefik/traefik/blob/f85f3b68aaf660e26296e99d97f134950d1e1cb8/pkg/config/dynamic/http_config.go#L149), meaning for 1 load balancer we can define the following config 

`
{
   "servers":[
      {
         "url":"mesos101.org.env",
         "port":"33123"
      },
      {
         "url":"mesos102.org.env",
         "port":"34121"
      },
      {
         "url":"mesos101.org.env",
         "port":"31122"
      }
   ],
   "healthCheck":{
      "hostname":"mesos102.org.env",
      "path":"/admin/healthCheck",
      "port":"31122"
   }
}
`

But for us to have a health check needs to be performed on a specific port port on a specific server (one to one relationship) we would need the config to be structured like 
`{
   "servers":[
      {
         "url":"mesos101.org.env",
         "port":"33123",
         "healthCheck":{
            "path":"/admin/healthCheck",
            "port":"33124"
         }
      },
      {
         "url":"mesos102.org.env",
         "port":"34121",
         "healthCheck":{
            "path":"/admin/healthCheck",
            "port":"34122"
         }
      },
      {
         "url":"mesos101.org.env",
         "port":"31122",
         "healthCheck":{
            "path":"/admin/healthCheck",
            "port":"31123"
         }
      }
   ]
}`

meaning [server config at http_config.go](https://github.com/traefik/traefik/blob/f85f3b68aaf660e26296e99d97f134950d1e1cb8/pkg/config/dynamic/http_config.go#L200) would change to 

`
type Server struct {
	URL    string `json:"url,omitempty" toml:"url,omitempty" yaml:"url,omitempty" label:"-"`
	Scheme string `toml:"-" json:"-" yaml:"-" file:"-"`
	Port   string `toml:"-" json:"-" yaml:"-" file:"-"`
	**HealthCheck        *ServerHealthCheck  `json:"healthCheck,omitempty" toml:"healthCheck,omitempty" yaml:"healthCheck,omitempty" export:"true"`**
}
`

i.e. have a health check config for every server, and if that doesn't exist then fall back to the global LB health check config 

This would be a major paradigm shift, and would require quite a lot of changes, I have analyzed the changes but was hoping to get a go-ahead that this is an acceptable direction to go on before I start making changes for the same

**Comment by bobbydixit** [comment]
@rtribotte, @tfny bumping up the thread in case you missed it

**Comment by tfny** [comment]
Hey @bobbydixit Thanks for bumping this up, summer vacations have us a bit thin.  We will get back to you quickly.

**Comment by tfny** [comment]
Hey @bobbydixit, I am sorry for the wait.  We went through the review and in the process noticed that marathon is not much used.  Because of this, we won't be moving forward with the PR.  

I am sorry about that, we thought the use case was much higher originally.
