### ISSUE TITLE
traefik2.6 gateway-api RequestRedirect not https

### ISSUE THREAD

**Issue by robertzhang712** [traefik/traefik#8810]
traefik2.6.1 use gateway-api 4.1  ,

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: traefik-test1-httproute
  namespace: kube-system
spec:
  parentRefs:
  - name: traefik-gateway-http
    sectionName: http
  hostnames:
  - "test1.hnapay.com"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https

now ,it can't  http to https, what to do it?

------------------
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: traefik-test1-httproute
  namespace: kube-system
spec:
  parentRefs:
  - name: traefik-gateway-http
    sectionName: http
  hostnames:
  - "test1.hnapay.com"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
