### ISSUE TITLE
passing detailed TLS information to backend

### ISSUE THREAD

**Issue by jkumeboshi** [traefik/traefik#8816]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I think that it may be useful to pass to the backend information about the TLS session, such as:
- TLS version being used
- the selected ciphersuite name
- in case of client auth: if the client certificate has been validated against a list of accepted CAs

This may be forwarded using some X-FORWARED-* header

Other useful features would be:
- ability for the backend to terminate the TLS session/ticket
- totally disabling TLS session/ticketing for a specified router

**Comment by kevinpollet** [comment]
Hello @jkumeboshi,

Thanks for your interest in Traefik,

Could you give more details about the use case?

What do you mean by TLS session/ticketing? If you want Traefik to not terminate the TLS connection and let the backend terminate the TLS connection, the [passthrough](https://doc.traefik.io/traefik/v2.6/routing/routers/#passthrough) option is the way to go.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
