### ISSUE TITLE
To correct documentation since the rule HostRegexp(`example.com`, `{subdomain:[a-z]+}.example.com`, ...) doesn't work

### ISSUE THREAD

**Issue by uniuuu** [traefik/traefik#8826]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What version of Traefik are you using?
Version:      2.6.1
Codename:     rocamadour
Go version:   go1.17.7
Built:        2022-02-14T16:50:25Z
OS/Arch:      linux/amd64

### What did you do?

Documentation  https://doc.traefik.io/traefik/routing/routers/  suggests to use ```HostRegexp(`example.com`, `{subdomain:[a-z]+}.example.com`, ...)``` for ```Match the request domain. See "Regexp Syntax" below.```

But it doesn't work.  (_Note: it does work in Traefik V1_)
Example:
```
labels:
 - traefik.http.routers.nginx.rule=HostRegexp(`{subdomain:test1|test2|test3}.testdomain.com
`)"
```

The error generated:
```
time="2022-03-09T03:12:46Z"level=warning msg="No domain found in rule HostRegexp(`{subdomain:test1|tests2|test3}.testdomain.com`), the TLS options applied for this router will depend on the hostSNI of each request"entryPointName=https routerName=https-nginx@docker
```

As result it's serving the default certificate:
```
time="2022-03-09T03:37:19Z" level=debug msg="Serving default certificate for request: \"test1.testdomain.com\""
```

**The workaround solution:**
The working rule for the case mentioned in example above is next:
```
labels:
  - "traefik.http.routers.nginx.rule=(Host(`test1.testdomain.com`) || Host(`test2.testdomain.com`
) || Host(`test3.testdomain.com`))"
```

This is reported many times, sample:
1. https://community.traefik.io/t/hostregexp-example-is-very-hard-to-understand/2868
3. https://githubhot.com/repo/htpcBeginner/docker-traefik/issues/209
4. https://www.reddit.com/r/Traefik/comments/t45e9x/no_domain_found_in_rule/
5. https://github.com/traefik/traefik/issues/8824

Since it was working in V1 but it doesn't in V2 therefore it's required to update documentation.

**Comment by ldez** [comment]
Hello,

the syntax ```HostRegexp(example.com, {subdomain:[a-z]+}.example.com, ...)``` works.

> ```
> time="2022-03-09T03:12:46Z"level=warning msg="No domain found in rule HostRegexp(`{subdomain:test1|tests2|test3}.testdomain.com`), the TLS options applied for this router will depend on the hostSNI of each request"entryPointName=https routerName=https-nginx@docker
> ```

It's a warning, not an error. This warning just says that the choice of the TLS options will be based on the SNI of the request.
