### ISSUE TITLE
Traefik with ECS provider is not able to get client IP with AWS ALB

### ISSUE THREAD

**Issue by ns-ajith** [traefik/traefik#8838]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

**Background:**
I'm trying to implement traefik proxy with the ECS provider to auto-discover the backend. 
R53 --> ALB --> Traefik proxy --> applocation. 

**Configs:**
To get the client real IP i have tried the following configuration:
```
- --entryPoints.http.proxyProtocol.insecure
- --entryPoints.http.forwardedHeaders.insecure
- --entryPoints.http.proxyProtocol.trustedIPs=127.0.0.1/32,172.31.0.0/16
- --entryPoints.http.forwardedHeaders.trustedIPs=127.0.0.1/32,172.31.0.0/16
```
Also tried with the `insecure` option too. Everytime when i add these configs traefik gives `404`

I can able to achieve this with EKS + classic load balancer (not with application load balancer).  For that, i need to add the `proxy-protocol` annotation `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"` . 

I cannot use the classic load balancer in ECS because I'm using ECS fargate profile (`Classic load balancer is not supported with network mode awsvpc` ). 

traffic

### What did you see instead?

Instead of getting Loadbalalancer IP, I need to log and pass the client IP to my Backend server. 

### What version of Traefik are you using?

2.6.1

### What is your environment & configuration?

Entrypoint config: 
```yaml
            "entryPoint": [
                "traefik",
			    "--providers.ecs.clusters","development",
                "--accesslog.filepath","/var/log/traefik/app/access.log",
                "--accesslog.fields.headers.defaultmode","keep",
                "--log.level","DEBUG",
                "--log.format","json",
                "--log.filepath","/var/log/traefik/traefik.log",
                "--providers.ecs.region","eu-central-1",
                "--api.insecure",
                "--tracing.instana.loglevel","debug",
                "--entryPoints.http.proxyProtocol.trustedIPs","127.0.0.1/32,172.31.0.0/16",
                "--entryPoints.http.forwardedHeaders.trustedIPs", "127.0.0.1/32,172.31.0.0/16"
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-03-15T14:41:48Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/js/dojo/mt/nls/en/common.js\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"],\"Accept-Language\":[\"en-US,en;q=0.9\"],\"Cookie\":[\"JSESSIONID=A49CE4060037EE2A00E992DFF4E47986; AWSALB=IgEblkwjoYVohF+96XqxrETUNoEBOUyIpNhwbf0QdL4f8lg8y2fFhbwsRHAysOcZeDgG8ph0IARfn40HPzLreoRLhMT1a6Qa/ogjaGYpPQWBZMJ4THvmrno1cOol\"],\"Referer\":[\"http://infra.something-container.nl/do?action=home\"],\"Server-Timing\":[\"intid;desc=5cd6320a82ae061e\"],\"Traceparent\":[\"00-00000000000000005cd6320a82ae061e-48a9e5d6b361e05b-01\"],\"Tracestate\":[\"in=5cd6320a82ae061e;48a9e5d6b361e05b\"],\"User-Agent\":[\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36\"],\"X-Amzn-Trace-Id\":[\"Root=1-6230a5ac-26540daf7b93502f003cd854\"],\"X-Forwarded-Host\":[\"infra.something-container.nl\"],\"X-Forwarded-Port\":[\"80\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"ip-172-31-8-89.eu-central-1.compute.internal\"],\"X-Instana-L\":[\"1\"],\"X-Instana-S\":[\"48a9e5d6b361e05b\"],\"X-Instana-T\":[\"5cd6320a82ae061e\"],\"X-Real-Ip\":[\"172.31.4.93\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"infra.something-container.nl\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.31.4.93:52510\",\"RequestURI\":\"/js/dojo/mt/nls/en/common.js\",\"TLS\":null}"
```

**Comment by JohnPreston** [comment]
Hello.
I have done a blog post (new version coming) on how to get ECS and traefik working together with ELBv2 etc.
See https://labs.compose-x.io/apps/traefik_ecs_part1.html
Hope this helps

**Comment by ns-ajith** [comment]
Hello, @JohnPreston Thanks for your effort in writing the blog, Have you tried to deploy with ALB instead of NLB?

**Comment by JohnPreston** [comment]
> Hello, @JohnPreston Thanks for your effort in writing the blog, Have you tried to deploy with ALB instead of NLB?

Yes I did. In fact let me try now again (I am 99% I did try at the time). Should not be too long.
May I ask why you'd want ALB to traefik ? Is that to use the ALB features, i.e, Cognito etc. or Lambda, and have a different routing to traefik ?

**Comment by ns-ajith** [comment]
Hay @JohnPreston  Thanks for the support. Yes, we will use the ALB to route the traffic to Lambda with certain conditions. 

Do you know any other wprkaround that we can use to get client IP with ALB ? in Nginx it is straightforward but I want to leverage the traefik to self-discover and route the traffic.
