### ISSUE TITLE
Support go-redis?

### ISSUE THREAD

**Issue by linux2014linux** [traefik/traefik#8844]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Traefik don't support "unsafe" package, but go-redis use "unsafe" package. I use go-redis in private middleware. Error happen when Traefik start up. Error info:
`
2022/03/16 11:37:49 traefik.go:79: command traefik error: github.com/traefik/casauth: failed to import plugin code "github.com/traefik/casauth": 1:21: import "github.com/traefik/casauth" error: plugins-local/src/github.com/traefik/casauth/demo.go:11:2: import "github.com/go-redis/redis/v7" error: plugins-local/src/github.com/traefik/casauth/vendor/github.com/go-redis/redis/v7/cluster.go:16:2: import "github.com/go-redis/redis/v7/internal" error: plugins-local/src/github.com/traefik/casauth/vendor/github.com/go-redis/redis/v7/internal/util.go:7:2: import "github.com/go-redis/redis/v7/internal/util" error: plugins-local/src/github.com/traefik/casauth/vendor/github.com/go-redis/redis/v7/internal/util/unsafe.go:6:2: import "unsafe" error: unable to find source related to: "unsafe"
`

**Comment by ldez** [comment]
Kind of duplicates #8780
