### ISSUE TITLE
Weighted Load Balancing between ECS Services

### ISSUE THREAD

**Issue by vikas027** [traefik/traefik#8854]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I have looked around but could not find a way to have weighted load balancing between ECS Services (just like [Kubernetes](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#weighted-round-robin)).

For example, if we have two ECS services `app-v1` and `app-v2`, it would be great to have the ability to define weights for these ECS services.

This will help to have weighted/staged canary deployment and distribute a part (say 90%) of traffic to `appv1` and the remaining (say 10%) to `appv2`.

**Comment by rtribotte** [comment]
Hello @vikas027,

Thanks for your interest in Traefik!

We've looked at your issue, and we found an existing issue for that proposal, and it addresses the subject for all providers that are missing this feature.
Therefore, we will close this issue as a duplicate in favor of #5673.
