### ISSUE TITLE
Help us Improve Traefik; Take the Community Survey! (~5 min)

### ISSUE THREAD

**Issue by tfny** [traefik/traefik#8881]
We are conducting the annual [Traefik Community Survey](https://www.surveymonkey.com/r/RCYP525) and we would love to hear from you!  1 to 2 times a year we conduct a survey to look for how cloud-native networking is changing, what direction you want us to take the product in, and how we can improve your experience.  

The first half of this survey is generally about Cloud-native networking.  The second half is how we can improve the community, docs, and other services.  

[Take the survey ](https://www.surveymonkey.com/r/RCYP525)to tell us how to best serve you and you can win one of over 30 prizes worth up to $250.

**Comment by bryanpedini** [comment]
Mhh, the survey is closed as of now. Was this intentional after 9 days?

**Comment by tfny** [comment]
Yes, We ran the survey for 3 weeks.  I am sorry for not closing this comment earlier--it was not on my checklist!
