### ISSUE TITLE
request interrupt

### ISSUE THREAD

**Issue by wwdz** [traefik/traefik#8909]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

To create an ingressroutetcp, for example: redis, you need to create an entrypoint correspondingly, and then you need to restart traefik, but the restart will cause the request to be interrupted. Does this support hot update?

**Comment by ldez** [comment]
Duplicate of #6551
