### ISSUE TITLE
Need an option to disable the hub dashboard button

### ISSUE THREAD

**Issue by baalajimaestro** [traefik/traefik#8912]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I upgraded from v2.6 to v2.7-rc.

### What did you see instead?

![image](https://user-images.githubusercontent.com/34187410/161411807-52b9d1d4-0930-4d84-aab4-b4180b579d56.png)

I noticed a button for hub dashboard on the top right. I would like to have a config to disable the same, similar to
```yaml
    pilot:
         dashboard: false
```

### What version of Traefik are you using?

v2.7-rc2

### What is your environment & configuration?

Nothing specific that might help. I havent enabled hub in the config.

**Comment by lewsmith** [comment]
Yes, I'd like to see an option to have this removed also. Maybe a `--hub.dashboard=false` option. I wouldn't usually mind, but the button is not very subtle. Plus, not sure if it's just me, but it directs to this anyway:

![Screenshot from 2022-04-29 11-37-34](https://user-images.githubusercontent.com/36924006/165929731-6a9265c1-d94f-4682-be8e-a4f0f75f8d98.png)

**Comment by ddtmachado** [comment]
Hey all, thanks for sharing your stance on this.
As [2.7.0 is released](https://github.com/traefik/traefik/releases/tag/v2.7.0) and it doesn't have the Hub link anymore I'm going to close this issue.
