### ISSUE TITLE
Malformed Location header when redirecting to IPv6 address

### ISSUE THREAD

**Issue by thannaske** [traefik/traefik#8915]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I'm running Traefik on non-default ports (http/8080, https/8081) and configured a permanent redirection from `http` to `https` (see configuration below). I'm aware that this kind of schema change won't properly work, however Traefik's response is syntactically wrong as it seems to disregard IPv6 port notation rules when executing the redirect.

When `curl`-ing the http endpoint, I'd expect a proper schema change without any change in the requested host (or IP address in this case).

I would expect the following:
```
$ curl -I http://[2a07:fc00:0:xxxx::17]:8080/
HTTP/1.1 308 Permanent Redirect
Location: https://[2a07:fc00:0:xxxx::17]:8080/
Date: Mon, 04 Apr 2022 06:20:37 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

This would be a simple schema change without touching anything else of the requested host URI.

### What did you see instead?

However, the actual output is the following:

```
HTTP/1.1 308 Permanent Redirect
Location: https://2a07:8443:fc00:0:xxxx::17:8080/
Date: Mon, 04 Apr 2022 06:20:37 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

There are two major issues with the response's `Location` header:
a) The brackets around the IPv6 address is missing which is required to specify a port for an IPv6 address (according to RFC2732)
b) Traefik somehow managed to include a `8443` block into the target location IP address (between `2a07` and `fc00`). 

### What version of Traefik are you using?

```
Labels:    app.kubernetes.io/instance=traefik-10-1649015066
           app.kubernetes.io/managed-by=Helm
           app.kubernetes.io/name=traefik
           helm.sh/chart=traefik-10.19.4
[...]
Image:     traefik:2.6.3
```

### What is your environment & configuration?

I'm using the latest Helm chart to deploy Traefik inside Kubernetes, the service is exposed as NodePort, the application is deployed as DaemonSet. The following extra args are set:

```yaml
  - '--entryPoints.web.proxyProtocol.trustedIPs=10.0.0.0/8'
  - '--entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.0/8'
  - '--entryPoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8'
  - '--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8'
  - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
  - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
```

**Comment by tomMoulard** [comment]
Hello @thannaske,

Thanks for your interest in Traefik !

After investigating, and according to [rfc2732#section-2](https://datatracker.ietf.org/doc/html/rfc2732#section-2): 
> To use a literal IPv6 address in a URL, the literal address should be
> enclosed in "[" and "]" characters.

With correct format, IPv6 requests are redirected to the correct IP. A request with the following host `http://[2a07:fc00:0:xxxx::17]:8080/` get redirected with the following header : `https://[2a07:fc00:0:xxxx::17]:8080/`.

In order to continue the investigation, can you provide how your actual request was created ?

**Comment by thannaske** [comment]
Hi Tom!
Thanks for your quick reply. I used `curl` to create and send the request:

```╰─ curl -I "http://[2a07:fc00:0:xxxx::17]:8080/"         
HTTP/1.1 308 Permanent Redirect
Location: https://2a07:8443:fc00:0:xxxx::17:8080/
Date: Mon, 04 Apr 2022 19:47:38 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8
```

**Comment by tomMoulard** [comment]
After further testing, using a bare Traefik, I found no bug from this side

<details>
  <summary markdown="span">Here's my test</summary>

```bash
$ curl -6 -v [2a01::xxxx:5f95]
*   Trying 2a01::xxxx:5f95:80...
* Connected to 2a01::xxxx:5f95 (2a01::xxxx:5f95) port 80 (#0)
> GET / HTTP/1.1
> Host: [2a01::xxxx:5f95]
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: https://[2a01::xxxx:5f95]/
< Date: Tue, 05 Apr 2022 13:28:54 GMT
< Content-Length: 17
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host 2a01::xxxx:5f95 left intact
Moved Permanently
```

</details>

I can see that you defined some `trustedIPs`, does it mean that requests are going through other proxies before reaching Traefik?

If so, if a proxy redirects to traefik and removes square brackets (therefore modifies the request into an invalid one), then it's no surprise that things don't behave as expected.

If you have no proxy before Traefik, how do you manage your stack in Kubernetes (e.g., are you using k3d?)? Can you please provide a reproducible use case?

**Comment by thannaske** [comment]
There is a HAProxy in front of Traefik but it acts as layer 3 LB so the request isn't modified there. The Kubernetes is setup with RKE (Rancher Kubernetes Engine) and the Traefik service is exposed via NodePort. I'll try to get a deterministic reproduction of the bug up and running on the weekend.

Could you re-try your test with non-default ports? Maybe those interfere with the Location header handling in any way.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
