### ISSUE TITLE
Multiple HTTP providers

### ISSUE THREAD

**Issue by chrispytoes** [traefik/traefik#8925]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I came across issue #8715 to fix the documentation to clarify that only one HTTP provider endpoint can be used, and I find it rather strange that the idea of actually making it possible to use multiple endpoints wasn't even entertained. In-fact, I'm new to Traefik and it feels like common sense to me that ANY provider should be duplicable as many times as needed. Is there a specific reason why this can't be added?

My use-case is that I'm using AWS, and I want to store my configs in an S3 bucket that's privately accessible to my VPC to allow the HTTP provider to grab them. This would make it very simple to manage and update configs with Terraform by simply managing them as object resources. I know the ECS provider exists and I am using that as well, but there are other non-ECS configs I'll need too and I want a quick and simple way to update them.

**Comment by ddtmachado** [comment]
@chrispytoes FYI this is option 3 on issue #8896 and actually the selected approach to solve it. I'll update that one with more details and keep this issue linked so whenever we merge the solution it can close both.
