### ISSUE TITLE
limited paths register

### ISSUE THREAD

**Issue by Rbsn-joses** [traefik/traefik#8939]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I added a new path there is an existing host with the label traefik.frontend.rule

### What did you see instead?

Because a new path of a host was set in an environment that has several existing paths, but it is not recognizing it, with the right configuration that is usually used in paths that already exist and work.
Traefik acts as if the new container doesn't have the labels, even if set correctly.
I removed a path from one of the containers with the host and the new one pointing to the new container worked.
here is my question about it or is it a bug

### What version of Traefik are you using?

v1.6

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

rancher

**Comment by mpl** [comment]
Hello,

Sorry, but Traefik v1.X. is not supported anymore. See https://doc.traefik.io/traefik/deprecation/releases/#versions
Please do feel free to migrate to Traefik v2.X
