### ISSUE TITLE
Cannot Run Traefik.exe as Windows Service

### ISSUE THREAD

**Issue by spher0boom** [traefik/traefik#8946]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I configured Traefik as a Windows Service using sc.exe with the properties and configuration file below. 

I can run traefik successfully using the following command.
    
    "C:\Program Files\Traefik\traefik.exe" --configFile=C:\\ProgramData\\Traefik\\conf\\traefik-conf.toml

When running the executable as the Windows service it fails to start with the following error:

    The Traefik service failed to start due to the following error: 
    The service did not respond to the start or control request in a timely fashion.

However, as soon as Windows starts the service I can see that the UI/API are responding correctly, and Traefic is routing HTTP traffic on port 80 as expected ... until Windows kills the service. 

Everything seems to work correctly, except that Traefik doesn't send the proper service response to the Windows service manager, so service manager stops the service. We have other Go apps (Nomad and Consul) running with the same configuration, so it doesn't seem like this is a general Go/Windows issue.

### What did you see instead?

When running the executable as the Windows service it fails to start with the following error:

    The Traefik service failed to start due to the following error: 
    The service did not respond to the start or control request in a timely fashion.

However, as soon as Windows starts the service I can see that the UI/API are responding correctly, and Traefik is routing HTTP traffic on port 80 as expected ... until Windows kills the service. 

### What version of Traefik are you using?

[traefik_v2.6.3_windows_amd64.zip](https://github.com/traefik/traefik/releases/download/v2.6.3/traefik_v2.6.3_windows_amd64.zip) 

### What is your environment & configuration?

```yaml

[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8081"

[api]
  dashboard = true
  insecure  = true

[providers.consulCatalog]
  prefix           = "traefik"
  exposedByDefault = false

[providers.consulCatalog.endpoint]
  address = "127.0.0.1:8500"
  scheme  = "http"

[log]
  level = "DEBUG"
  filePath = "C:/ProgramData/Traefik/logs/traefik.log"
  format = "common"
  
```

The service is running on Windows Server 2022.
The Traefik exe is in the environment path.
Ports 80 and 8081 are open on the Windows Firewall (inbound and outbound).
--- service properties ---
DisplayName = Traefik
StartupType = Automatic
Description = Traefik load-balancer and reverse-proxy service.
Name = Traefik
BinaryPathName = C:\Program Files\Traefik\traefik.exe --configFile=C:\\ProgramData\\Traefik\\conf\\traefik-conf.toml 

I can run traefik successfully using the following command, which uses the config file below.
    
    "C:\Program Files\Traefik\traefik.exe" --configFile=C:\\ProgramData\\Traefik\\conf\\traefik-conf.toml

### If applicable, please paste the log output in DEBUG level

time="2022-04-15T21:11:00-05:00" level=info msg="Traefik version 2.6.3 built on 2022-03-29T13:09:27Z"
time="2022-04-15T21:11:00-05:00" level=debug msg="Static configuration loaded {\"global\":{},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"http\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}},\"traefik\":{\"address\":\":8081\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":\"10s\"},\"respondingTimeouts\":{\"idleTimeout\":\"3m0s\"}},\"forwardedHeaders\":{},\"http\":{},\"udp\":{\"timeout\":\"3s\"}}},\"providers\":{\"providersThrottleDuration\":\"2s\",\"consulCatalog\":{\"endpoint\":{\"address\":\"127.0.0.1:8500\",\"scheme\":\"http\"},\"prefix\":\"traefik\",\"refreshInterval\":\"15s\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"serviceName\":\"traefik\"}},\"api\":{\"insecure\":true,\"dashboard\":true},\"log\":{\"level\":\"DEBUG\",\"filePath\":\"C:/ProgramData/Traefik/logs/traefik.log\",\"format\":\"common\"},\"pilot\":{\"dashboard\":true}}"
time="2022-04-15T21:11:00-05:00" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
time="2022-04-15T21:11:00-05:00" level=info msg="Starting provider aggregator.ProviderAggregator"
time="2022-04-15T21:11:00-05:00" level=debug msg="Start TCP Server" entryPointName=traefik
time="2022-04-15T21:11:00-05:00" level=debug msg="Start TCP Server" entryPointName=http
time="2022-04-15T21:11:00-05:00" level=info msg="Starting provider *traefik.Provider"
time="2022-04-15T21:11:00-05:00" level=debug msg="*traefik.Provider provider configuration: {}"
time="2022-04-15T21:11:00-05:00" level=info msg="Starting provider *acme.ChallengeTLSALPN"
time="2022-04-15T21:11:00-05:00" level=debug msg="*acme.ChallengeTLSALPN provider configuration: {\"Timeout\":4000000000}"
time="2022-04-15T21:11:00-05:00" level=info msg="Starting provider *consulcatalog.Provider"
time="2022-04-15T21:11:00-05:00" level=debug msg="*consulcatalog.Provider provider configuration: {\"endpoint\":{\"address\":\"127.0.0.1:8500\",\"scheme\":\"http\"},\"prefix\":\"traefik\",\"refreshInterval\":\"15s\",\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"serviceName\":\"traefik\"}"
time="2022-04-15T21:11:00-05:00" level=debug msg="Configuration received from provider internal: {\"http\":{\"routers\":{\"api\":{\"entryPoints\":[\"traefik\"],\"service\":\"api@internal\",\"rule\":\"PathPrefix(`/api`)\",\"priority\":2147483646},\"dashboard\":{\"entryPoints\":[\"traefik\"],\"middlewares\":[\"dashboard_redirect@internal\",\"dashboard_stripprefix@internal\"],\"service\":\"dashboard@internal\",\"rule\":\"PathPrefix(`/`)\",\"priority\":2147483645}},\"services\":{\"api\":{},\"dashboard\":{},\"noop\":{}},\"middlewares\":{\"dashboard_redirect\":{\"redirectRegex\":{\"regex\":\"^(http:\\\\/\\\\/(\\\\[[\\\\w:.]+\\\\]|[\\\\w\\\\._-]+)(:\\\\d+)?)\\\\/$\",\"replacement\":\"${1}/dashboard/\",\"permanent\":true}},\"dashboard_stripprefix\":{\"stripPrefix\":{\"prefixes\":[\"/dashboard/\",\"/dashboard\"]}}},\"serversTransports\":{\"default\":{\"maxIdleConnsPerHost\":200}}},\"tcp\":{},\"tls\":{}}" providerName=internal
time="2022-04-15T21:11:00-05:00" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-04-15T21:11:00-05:00" level=debug msg="Filtering disabled item" providerName=consulcatalog serviceName=consul
time="2022-04-15T21:11:00-05:00" level=debug msg="Filtering disabled item" providerName=consulcatalog serviceName=nomad
time="2022-04-15T21:11:00-05:00" level=debug msg="Filtering disabled item" providerName=consulcatalog serviceName=nomad-client
time="2022-04-15T21:11:00-05:00" level=debug msg="Configuration received from provider consulcatalog: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=consulcatalog
time="2022-04-15T21:11:00-05:00" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareType=StripPrefix middlewareName=dashboard_stripprefix@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal entryPointName=traefik
time="2022-04-15T21:11:00-05:00" level=debug msg="Creating middleware" routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik
time="2022-04-15T21:11:00-05:00" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal middlewareName=dashboard_redirect@internal entryPointName=traefik
time="2022-04-15T21:11:00-05:00" level=debug msg="Added outgoing tracing middleware api@internal" routerName=api@internal entryPointName=traefik middlewareName=tracing middlewareType=TracingForwarder
time="2022-04-15T21:11:00-05:00" level=debug msg="Creating middleware" entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2022-04-15T21:11:00-05:00" level=debug msg="No default certificate, generating one" tlsStoreName=default
time="2022-04-15T21:11:00-05:00" level=debug msg="Added outgoing tracing middleware api@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Added outgoing tracing middleware dashboard@internal" middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Creating middleware" middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix entryPointName=traefik routerName=dashboard@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Adding tracing to middleware" middlewareName=dashboard_stripprefix@internal entryPointName=traefik routerName=dashboard@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Creating middleware" entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex
time="2022-04-15T21:11:00-05:00" level=debug msg="Setting up redirection from ^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$ to ${1}/dashboard/" middlewareName=dashboard_redirect@internal middlewareType=RedirectRegex entryPointName=traefik routerName=dashboard@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Adding tracing to middleware" routerName=dashboard@internal entryPointName=traefik middlewareName=dashboard_redirect@internal
time="2022-04-15T21:11:00-05:00" level=debug msg="Creating middleware" middlewareType=Recovery entryPointName=traefik middlewareName=traefik-internal-recovery
time="2022-04-15T21:11:15-05:00" level=debug msg="Filtering disabled item" serviceName=nomad providerName=consulcatalog
time="2022-04-15T21:11:15-05:00" level=debug msg="Filtering disabled item" providerName=consulcatalog serviceName=nomad-client
time="2022-04-15T21:11:15-05:00" level=debug msg="Filtering disabled item" providerName=consulcatalog serviceName=consul
time="2022-04-15T21:11:15-05:00" level=debug msg="Configuration received from provider consulcatalog: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=consulcatalog
time="2022-04-15T21:11:15-05:00" level=debug msg="Skipping same configuration" providerName=consulcatalog

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
