### ISSUE TITLE
Jaeger tracer B3 span IDs are not always as 16-hex strings, jaeger-client-go update needed

### ISSUE THREAD

**Issue by tarvip** [traefik/traefik#8949]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

We are using linkerd service mesh together with Traefik. From linker-proxy log I can see a lot of following messages:
```
2022-04-19T08:51:25.613469600+03:00 {"timestamp":"[1033112.197236s]","level":"WARN","fields":{"message":"Header x-b3-spanid does not contain a hex value: Odd number of digits"},"target":"linkerd_trace_context::propagation","spans":[{"name":"outbound"},{"orig_dst":"10.2.24.184:8080","name":"ingress"},{"dst":"foo.bar.svc.cluster.local:8080","name":"override"}],"threadId":"ThreadId(1)"}
```

When I investigated that it turned out that spanIds that are created by traefik do not have always correct length.

This issue is fixed in 2.30.0 jager-client-go, [see here](https://github.com/jaegertracing/jaeger-client-go/blob/master/CHANGELOG.md#2300-2021-12-07)

### What did you see instead?

We are seeing shorter span IDs and a lot of WARNING messages in linkerd-proxy.

### What version of Traefik are you using?

At the moment we are using v2.5.3, but even master branch has not fix for that as it is still using old jaeger-client-go module.

### What is your environment & configuration?

Environment conf is irrelevant at the moment.

**Comment by kevinpollet** [comment]
Closed by #9000
