### ISSUE TITLE
Support log stream to stdout and file both

### ISSUE THREAD

**Issue by joey-yoonsung** [traefik/traefik#8950]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Traefik can be set to stream the general log and access log to the file with these configurations like below. (I'm using traefik as Kubernetes ingress.)
```yaml
additionalArguments:
  - "--log.filepath=/var/log/traefik/traefik.log"
  - "--accesslog.filepath=/var/log/traefik/traefik-access.log"
```

When I set these arguments, the traefik process doesn't stream logs to stdout anymore.
The `stdout` is a very basic thing of process. Developers can figure out the application using stdout at first look. 
The stdout is useful for who don't know the deployment settings although someone make the process send a log as a file. This reduces misunderstanding about the traefik process, especially in the container environment.

It would be good to make the traefik streams log to file & stdout both.

How about adding this configuration? It would not affect existing configurations.
```
additionalArguments:
  - "--log.stdout=true"
  - "--accesslog.stdout=true"
```

**Comment by kevinpollet** [comment]
Hello @joey-yoonsung,

Thanks for your interest in Traefik,

As explained in https://kubernetes.io/docs/concepts/cluster-administration/logging/, the recommended logging method for containerized applications is to write to `stdout` and `stderr`. Then, it is up to the orchestrator or log library to collect the logs and forward them to the aggregation platform.

According to this, we will decline this issue.
