### ISSUE TITLE
Is there a possibility to block all requests with unlisted http method?

### ISSUE THREAD

**Issue by jankohout95** [traefik/traefik#8965]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am wondering if there is some way to configure blocking unexpected http methods.

For example, when there is a request with method `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`, Traefik passes that through in a specific route and the request is handled in the endpoint of that specific route.

**Desired state** is, Traefik should have some parameter which allows only listed methods and if request method does not match any of specified in a list, throws for ex. an error `405 Method Not Allowed` and does not pass request into specific route.

This issue/question is published in chain to my previous one (https://github.com/traefik/traefik/issues/8961) since response header contains allowed methods for a request with `OPTIONS` method (probably my lack of information about CORS), but accessControlAllowMethods does not restrict requests for non-matching methods.

By another words I specified only methods `accessControlAllowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]`, but it even returned response `["GET", "HEAD", "OPTIONS"]` for my `OPTIONS` like request and when I make a request with `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` method, Traefik passes it through without throwing any error.
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/100849407/165030991-2b5fb319-a492-4b3a-94bd-864aa529f5a1.png">

As I was searching, the only post where it looked like, there is a provided kind of configuration is this, https://stackoverflow.com/questions/58012063/restrict-allowed-methods-on-traefik-routes, but as you can see in comment bellow, "And this would not block the requests with an incorrect HTTP method" 

My final question is, does accessControlAllowMethods parameter restrict other methods except the specified in list, or does it have just informative purpose in OPTION like request? Is it a bug or feature? Should not it return in response all the methods, which were defined in list in configuration? Is there any other configuration which restricts access for unlisted methods?

Version and environment is equal to specified in previous issue: https://github.com/traefik/traefik/issues/8961.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
