### ISSUE TITLE
error: field not found, node: influxDB2

### ISSUE THREAD

**Issue by ar-wed** [traefik/traefik#8986]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I just wanted to add the new metric collector for InfluxDB2. So I just added to my dockers `traefik.yml` the code below in "What is your environment & configuration?" section.

### What did you see instead?

Traefik is not starting any more and I get the error message `command traefik error: field not found, node: influxDB2` in the log.  A new entry every few seconds.

If I comment the new configuration for `influxDB2` code out, traefik works just fine.

### What version of Traefik are you using?

```
Version:      2.6.6
Codename:     rocamadour
Go version:   go1.17.9
Built:        2022-05-03T16:58:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

I run traefik using docker.
`traefik.yml`:
```yaml
metrics:
  influxDB2:
    address: "http://influxdb2:8086"
    token: "<token>"
    org: "data"
    bucket: "traefik"
```

### If applicable, please paste the log output in DEBUG level

```
traefik    | 2022/05/04 17:23:26 command traefik error: field not found, node: influxDB2
traefik    | 2022/05/04 17:23:27 command traefik error: field not found, node: influxDB2
```

**Comment by ldez** [comment]
Hello,

You are reading the documentation of the experimental (branch `master`):
- https://doc.traefik.io/traefik/master/

The documentation of the v2.6 (latest) is here:
- https://doc.traefik.io/traefik/
- https://doc.traefik.io/traefik/v2.6/

The documentation of the v2.7 (RC) is here:
- https://doc.traefik.io/traefik/v2.7/

You can see the documentation version at the bottom of the menu:
![Screenshot 2022-05-04 at 20-40-30 Traefik Proxy Documentation - Traefik](https://user-images.githubusercontent.com/5674651/166803824-99c7075c-fe04-4cc9-9191-2a238d84b502.png)
