### ISSUE TITLE
Need a way to define or alter the traefik `service name` based on consul tags

### ISSUE THREAD

**Issue by breathe** [traefik/traefik#8987]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

This is a new description of an older problem originally discussed here: https://github.com/traefik/traefik/issues/3882

That issue was originally opened in such a way that it appeared related to Traefik v1 -- however the issue affects Traefik v2 as well and @ddtmachado requested a new issue be created to describe the problem.

## Problem

When using the nomad <-> consul <-> traefik integration, it is not possible to use the canary deployment workflow that is supported by nomad.

An introduction to the nomad canary roll-out strategy can be found [here](https://learn.hashicorp.com/tutorials/nomad/job-blue-green-and-canary-deployments).  The crux of the problem is that nomad will register the non-canary version of the service and the canary version of the service with the same consul service-name such that traefik routing policy cannot distinguish between the canary and non-canary instances of the service.  Both service types are presented in traefik as one 'service' representing a pool of instances of both instance types.  This means you can't use traefik routing policy to direct traffic to only one or the other instance type independently.

## Background

Nomad supports a service deployment lifecycle that includes a canary deployment process.  When a new version of a service that uses the canary deployment feature is deployed, nomad will spin up `n` instances of the canary service 'alongside' the existing service instances and allow the canary instances to be health-checked and verified as desired before they are 'promoted'.  After promotion, the normal deployment process is followed and the running older instances are replaced with the new version.

Nomad supports defining consul parameters specific for the canary instances via the [canary_tags](https://www.nomadproject.io/docs/job-specification/service#canary_tags) and [canary_meta](https://www.nomadproject.io/docs/job-specification/service#canary_meta) nomad parameters.  These parameters parallel the [tags](https://www.nomadproject.io/docs/job-specification/service#tags) and [meta](https://www.nomadproject.io/docs/job-specification/service#meta) parameters that are used to populate consul for regular instances of the service.  When nomad spins up canary instances it populates consul based on canary_tags/canary_meta and when nomad spins up regular instances it populates consul based on tags/meta.

For both canary and non-canary instances, nomad registers the service with the same consul service-name.  Nomad only allows canary/non-canary instances to differ in their presentation to consul via the canary_tags and canary_meta parameters.

Traefik on the hand, considers all consul registrations with the same name to be the 'same service'.  Its not currently possible to define a traefik routing policy that will route traffic to canary only or non-canary only nomad instances.  As far as traefik is concerned the canary and non-canary instances are the same pool of instances and these instances can't be independently addressed..

If we could customize the presentation of the service in traefik via the nomad `canary_tags` or `canary_meta` properties in such a way as to persuade traefik to consider these instance types as two distinct services, then we would be able to take advantage of the full flexibility of traefik routing behaviors to decide how we would like to route to these now distinct-from-the-perspective-of-traefik services.

## Possible Solution

I suggest allowing to define a consul parameter that allows deriving an alternate name by combining with a suffix with the base consul service name.

For example -- suppose support is added for a consul tag named `traefik.consulnamesuffix` and suppose a nomad service declaration like this:

```
service {
  name = "health-check-tool"
  port = "http"

  tags = [
    "traefik.enable=true",
    "traefik.http.middlewares.strip_canary_header.headers.customrequestheaders.Canary=",
    "traefik.http.routers.deploy_automation_tester.rule=Host(`${var.domain}`)",
    "traefik.http.routers.deploy_automation_tester.tls=true",
    "traefik.http.routers.deploy_automation_tester.entrypoints=https",
    "traefik.http.routers.deploy_automation_tester.middlewares=strip_canary_header@consulcatalog"
  ]

  canary_tags = [
    "traefik.consulnamesuffix=`canary`",
    "traefik.enable=true",
    "traefik.http.routers.deploy_automation_tester_canary.rule=Host(`${var.domain}`) && Headers(`canary`, `true`)",
    "traefik.http.routers.deploy_automation_tester_canary.tls=true",
    "traefik.http.routers.deploy_automation_tester_canary.entrypoints=https",
  ]

  connect {
    sidecar_service {}
  }

  check {
    name     = "alive"
    type     = "http"
    path     = "/ping"
    interval = "10s"
    timeout  = "2s"
  }
}
```

While an active nomad deployment is in progress we would see two services in `traefik` -- a service named `health_check_tool` which would represent the 'old' version of the service and a service named `health_check_tool_canary` which would represent the 'new' desired version of the service that is being evaluated.  In this example, there would also be two traefik routers -- one named `deploy_automation_tester`  would route traffic for `${var.domain}` to `health_check_tool` and one named `deploy_automation_tester_canary` which would route traffic for `${var.domain}` that contains the `canary: true` header to the `health_check_tool_canary` service.

A mechanism like this would integrate well with the nomad deployment lifecycle and would allow using the normal traefik routing policy mechanisms to send traffic to the canary/non-canary instances of the service in whatever manner is desired during deployment of a new service version.

**Comment by urusha** [comment]
It is really nice idea to get final traefik service name by modifying consul service name with the suffix from the tag, or even replacing full service name with the value from the tag. This will simplify configuration. Also, please see my note about router names with similar configuration https://github.com/hashicorp/nomad/issues/8073#issuecomment-1119532106

**Comment by scalp42** [comment]
Great write up @breathe, pretty much the same way that [Fabio works](https://github.com/fabiolb/fabio) basically.

**Comment by apollo13** [comment]
Btw while I do agree that something like this would be nice you can achieve the same today by running two traefik instances/job and pointing them to different tag prefixes (https://doc.traefik.io/traefik/providers/consul-catalog/#prefix)

The service would then look like this:
```
service {
  name = "health-check-tool"
  port = "http"

  tags = [
    "traefik.enable=true",
    "traefik.http.routers.deploy_automation_tester.rule=Host(`${var.domain}`)",
    "traefik.http.routers.deploy_automation_tester.tls=true",
    "traefik.http.routers.deploy_automation_tester.entrypoints=https",
  ]

  canary_tags = [
    "traefik-canary.enable=true",
    "traefik-canary.http.routers.deploy_automation_tester.rule=Host(`${var.domain}`)"",
    "traefik-canary.http.routers.deploy_automation_tester.tls=true",
    "traefik-canary.http.routers.deploy_automation_tester.entrypoints=https",
  ]

  connect {
    sidecar_service {}
  }

  check {
    name     = "alive"
    type     = "http"
    path     = "/ping"
    interval = "10s"
    timeout  = "2s"
  }
}
```

While this might feel cumbersome it also prevents one from introducing invalid configuration into the system via canary tags :) [And one needs to route canary requests with yet another loadbalancer to traefik first, so might only be feasible if one has a canary domain or similar].
