### ISSUE TITLE
fail: "Path-based Routing" example 

### ISSUE THREAD

**Issue by QizhouYang** [traefik/traefik#9025]
### Welcome!

- [ ] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

addr: https://github.com/traefik/traefik/blob/v1.7/docs/user-guide/kubernetes.md

**Path-based Routing** code 

### What did you see instead?

the picture does not show.

![1652868143(1)](https://user-images.githubusercontent.com/23524287/169013860-8f9f24e7-fe8a-4cad-a2a2-5d0a3cdd792c.png)

expect:

![1652868245(1)](https://user-images.githubusercontent.com/23524287/169014186-1dbad19b-0982-4467-8c20-9db0cad155c1.png)

### What version of Traefik are you using?

traefik: 1.7

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```
kubernetes 1.14.3
traefik 1.7
Add more configuration information here.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
