### ISSUE TITLE
http2 connection max live time

### ISSUE THREAD

**Issue by wuzhuoquan** [traefik/traefik#9034]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I use ```traefik``` in k8s cluster as ```ingress-controller``` , and use the ```layer 4 SLB``` outside the k8s cluster for the client to request to the api sevice in cluster, using http2 protocol

<img width="371" alt="image" src="https://user-images.githubusercontent.com/49891988/169507780-fe673c8b-7ec9-49bf-bf6f-d759f3e3f421.png">

the problem is , if I scale out the traefik deployment, like 2  -> 3 
I found that the request never push to new  traefik pod unless I restart the client ,to force create a new connection

It's there anyway to resolve the problem? or add a new feature to set ```max live time``` for the connection, after the max time, recreate a new connection graceful?

Thank you

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
