### ISSUE TITLE
Routing with priority doesn't work

### ISSUE THREAD

**Issue by tide34** [traefik/traefik#9048]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In example used traefik in kubernetes deployed by default helm chart.  

I have two applications. Let's call are root and profile. And have two different versions of each one: 3-21 and 3-22. For now we have 4 pod root-3-21, root-3-22, profile-3-21, profile-3-22. The applications are just simple nginx web server which return web page with the name of the service and version. For examle, root-3-21 will return:  
![image](https://user-images.githubusercontent.com/49846209/170645771-4b636882-242c-4bc1-9a97-36ceb4415906.png)
 root-3-22 will return:  
![image](https://user-images.githubusercontent.com/49846209/170645818-040056d8-a3e2-41c2-bde9-9a8ee325c188.png)  
 profile-3-21 will return:  
![image](https://user-images.githubusercontent.com/49846209/170645914-97c964f1-f2c3-4d6d-b736-d17caab61d1a.png)
 profile-3-22 will return:  
![image](https://user-images.githubusercontent.com/49846209/170646000-659548b7-fb9b-405b-a9da-21e5ea1dda96.png)  
  
## Routing rules
The applications will be reached over domain name and path like this:
1.1) app.abc/ - root application
1.2) app.abc/profile - profile application
Also we wonna if user pass header "Cookie" with value "version=3-21" to nay of request 1.1) or 1.2) they will be proxed to 3-21 version of application. If user doesn't pass header "Cookie" then request will be proxed to higher version of application (in our example 3-22). Summaries, we have next logic:
2.1) curl app.abc/ -> root-3-22  
2.2) curl app.abc/profile -> profile-3-22  
2.3) curl app.abc/ -H "Cookie: version=3.21" -> root-3-21  
2.4) curl app.abc/profile -H "Cookie: version=3.21" -> profile-3-21  
2.5) curl app.abc/ -H "Cookie: version=3.22" -> root-3-22  
2.6) curl app.abc/profile -H "Cookie: version=3.22" -> profile-3-22  
  
To realize rules above i have created next ingressroutes:  
`  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-22-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) 
    kind: Rule
    priority: 322
    services:
      - name: root-3-22
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-22-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && HeadersRegexp(`Cookie`,`version=3.22`)
    kind: Rule
    priority: 10000
    services:
      - name: root-3-22
        port: 80  
---  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-22-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)
    kind: Rule
    priority: 322
    services:
      - name: profile-3-22
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-22-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)  && HeadersRegexp(`Cookie`,`version=3.22`)
    kind: Rule
    priority: 10000
    services:
      - name: profile-3-22
        port: 80  
---  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-21-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) 
    kind: Rule
    priority: 321
    services:
      - name: root-3-21
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: root-3-21-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && HeadersRegexp(`Cookie`,`version=3.21`)
    kind: Rule
    priority: 10000
    services:
      - name: root-3-21
        port: 80  
---  
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-21-default
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)
    kind: Rule
    priority: 321
    services:
      - name: profile-3-21
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: profile-3-21-header
spec:
  entryPoints:
    - web
  routes:
  - match: Host( `app.abc` ) && PathPrefix( `/profile`)  && HeadersRegexp(`Cookie`,`version=3.21`)
    kind: Rule
    priority: 10000
    services:
      - name: profile-3-21
        port: 80  
`  
  
### Step to reproduce
Now let's start send request to application like in list 2.1 - 2.6. You will see that request routed not to the targer pod. For example: one of request in 2.1) - 2.6) will be failed:  
   
![image](https://user-images.githubusercontent.com/49846209/170652597-9418aef8-e319-4dda-b2d8-f3b3e04c9539.png)  
  
In log of traefik pod (log in debug mode below) we see that request processed by incorrect ingressroute:  
![image](https://user-images.githubusercontent.com/49846209/170655662-a62e43d7-1e56-43e5-8373-02bfca2e3567.png)
  
log from incorrect pod of application:  
![image](https://user-images.githubusercontent.com/49846209/170655108-ec2c2558-a6ab-48d8-a6e0-b41fa29994d0.png)
   
Why traefik proccese request by root-3-22-header ingressrouter? Look like a traefik **BUG**. If bug non-reproducible in your environment, just restart your traefik pod. Sometime all ingressroute working correctly, but after traefik pod restart issue happend again.

### What did you see instead?

I would see that traefik will proxed request over profile-3-22-header ingressroute, not over root-3-22-header

### What version of Traefik are you using?

2.7.0, 2.4.8

### What is your environment & configuration?

Kubernetes (v2.4.8), minikube (v2.7.0). Default helm chart was used to install traefik from documentation [here](https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-helm-chart).

### If applicable, please paste the log output in DEBUG level

{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Cookie\":[\"version=3.22\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:31906\"],\"X-Forwarded-Port\":[\"31906\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-m44wn\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:31906\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:41003\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: begin ServeHttp on request","time":"2022-05-27T07:30:58Z"}
{"ForwardURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.3:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Cookie\":[\"version=3.22\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:31906\"],\"X-Forwarded-Port\":[\"31906\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-m44wn\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:31906\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:41003\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: Forwarding this request to URL","time":"2022-05-27T07:30:58Z"}
{"Request":"{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/profile\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/1.1\",\"ProtoMajor\":1,\"ProtoMinor\":1,\"Header\":{\"Accept\":[\"*/*\"],\"Cookie\":[\"version=3.22\"],\"User-Agent\":[\"curl/7.68.0\"],\"X-Forwarded-Host\":[\"app.abc:31906\"],\"X-Forwarded-Port\":[\"31906\"],\"X-Forwarded-Proto\":[\"http\"],\"X-Forwarded-Server\":[\"traefik-84f9c9594d-m44wn\"],\"X-Real-Ip\":[\"172.17.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"app.abc:31906\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.17.0.1:41003\",\"RequestURI\":\"/profile\",\"TLS\":null}","level":"debug","msg":"vulcand/oxy/roundrobin/rr: completed ServeHttp on request","time":"2022-05-27T07:30:58Z"}
{"ClientAddr":"172.17.0.1:41003","ClientHost":"172.17.0.1","ClientPort":"41003","ClientUsername":"-","DownstreamContentSize":153,"DownstreamStatus":404,"Duration":4871750,"OriginContentSize":153,"OriginDuration":4478395,"OriginStatus":404,"Overhead":393355,"RequestAddr":"app.abc:31906","RequestContentSize":0,"RequestCount":20,"RequestHost":"app.abc","RequestMethod":"GET","RequestPath":"/profile","RequestPort":"31906","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"RouterName":"app-root-3-22-header-c78c3739d67570ccbd2f@kubernetescrd","ServiceAddr":"172.17.0.3:80","ServiceName":"app-root-3-22-header-c78c3739d67570ccbd2f@kubernetescrd","ServiceURL":{"Scheme":"http","Opaque":"","User":null,"Host":"172.17.0.3:80","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"StartLocal":"2022-05-27T07:30:58.422826867Z","StartUTC":"2022-05-27T07:30:58.422826867Z","entryPointName":"web","level":"info","msg":"","time":"2022-05-27T07:30:58Z"}

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by tide34** [comment]
@rtribotte hello. Please look at bug. Traefik incorrect route traffic

**Comment by tide34** [comment]
@rtribotte @kevinpollet please have a look guys

**Comment by tide34** [comment]
@kevinpollet

**Comment by tide34** [comment]
@rtribotte
