### ISSUE TITLE
Update go-acme/lego to v4.7.0 to Fix Tencent Cloud DNS invalid domain error

### ISSUE THREAD

**Issue by zx900930** [traefik/traefik#9064]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Correctly setting up the dnsprovider(tencentcloud)'s parameters.

### What did you see instead?

acme return error:  InvalidParameter.DomainInvalid

This bug was fixed by https://github.com/go-acme/lego/pull/1616

Pls update the go-acme/lego to [v4.7.0](https://github.com/go-acme/lego/releases/tag/v4.7.0)

### What version of Traefik are you using?

v2.7.0

### What is your environment & configuration?

```yaml
labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`mydomain.com`)"
      - "traefik.http.routers.umami.tls.certresolver=myresolver"
```

### If applicable, please paste the log output in DEBUG level

```
time="2022-06-02T09:37:01Z" level=error msg="Unable to obtain ACME certificate for domains \"mydomain.com\": unable to generate a certificate for the domains [mydomain.com]: error: one or more domains had a problem:\n[mydomain.com] [mydomain.com] acme: error presenting token: tencentcloud: create record failed: [TencentCloudSDKError] Code=InvalidParameter.DomainInvalid, Message=域名不正确，请输入主域名，如 dnspod.cn。, RequestId=67c8d5d8-f84c-4564-bc11-536b4dfacc16\n" providerName=myresolver.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=umami@docker rule="Host(`mydomain.com`)"
```

**Comment by traefiker** [comment]
Closed by #9065.
