### ISSUE TITLE
invalid value for "HostSNI" matcher when the host has a underscore 

### ISSUE THREAD

**Issue by kormoc** [traefik/traefik#9068]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have a host rule similar to ```Host(`foo_bar.example.com`)``` and due to the `almostFQDN` regex, https://github.com/traefik/traefik/blob/521109d3f2832eb92db20b1749478088c57f0f20/pkg/muxer/tcp/mux.go#L287 ,
traefik throws an error 

`Error while adding route for host: %!w(*errors.errorString=&{invalid value for \"HostSNI\" matcher, \"foo_bar.example.com\" is not a valid hostname})`

Underscore is a valid character and should be added to the `almostFQDN` regex

### What did you see instead?

`Error while adding route for host: %!w(*errors.errorString=&{invalid value for \"HostSNI\" matcher, \"foo_bar.example.com\" is not a valid hostname})`

### What version of Traefik are you using?

```
Version:      2.7.0
Codename:     epoisses
Go version:   go1.17.10
Built:        2022-05-24T17:07:05Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

`Error while adding route for host: %!w(*errors.errorString=&{invalid value for \"HostSNI\" matcher, \"foo_bar.example.com\" is not a valid hostname})`

**Comment by ldez** [comment]
RFCs about valid domain and subdomain:
- [DOMAIN NAMES - RFC1035](https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.1)
- [DOD INTERNET HOST TABLE SPECIFICATION - RFC952](https://datatracker.ietf.org/doc/html/rfc952)
- [Requirements for Internet Hosts - RFC1123](https://datatracker.ietf.org/doc/html/rfc1123)

**Comment by rtribotte** [comment]
Hello @kormoc,

Thanks for reporting this issue!

Since the underscore character is not valid for an internet hostname, we are wondering what is your current use case, can you explain why would you need this character to be allowed in the `HostSNI` matcher?
(We do understand that the underscore character has been a valid character for DNS labels.)

**Comment by kormoc** [comment]
Honestly, I didn't know underscores are valid via standard.

In this case, Windows generated a hostname based on the computer name that included a underscore. I was setting up the `Host` matcher to forward to this windows name and reused the computer name with the underscore.

It's not a difficult issue to change the windows computer name, so I completely understand if you want to stay strictly compliant, however, safari/chrome/firefox all seem to support underscores. Perhaps clearly documenting in the `Host`/`HostSNI` section the relevant RFC would be helpful.

Thank you for looking into it!

**Comment by mpl** [comment]
@kormoc thanks, we'll see if we can fit it in the doc somewhere.
