### ISSUE TITLE
Add something that blocks web access after too many failed logins like fail2ban

### ISSUE THREAD

**Issue by PhilipMay** [traefik/traefik#9072]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like to have a middleware that can track failed logins and can block the IP for some time after a configurable number of failures.

**Comment by ldez** [comment]
Hello,

you can look at [the plugins catalog](https://pilot.traefik.io/plugins).
You will find a plugin that handles fail2ban: https://pilot.traefik.io/plugins/605afbaaa5f67ab9a1b0e51c/fail2-ban.

**Comment by PhilipMay** [comment]
@ldez yes ok. This is a 3rd party plugin that might cover this functionality. 

But 3rd party plugins might have huge issues in the future.
There might be version updates in Traefik and suddenly the plugin is incompatible.
Or there might be security issues and the contributor does not fix them.

**Anyway. I would be happy if this functionality is implemented as a real part of Traefik.**

**Comment by ldez** [comment]
The plugin has been created by a Traefik maintainer.

**Comment by PhilipMay** [comment]
@ldez ok - so you suggest to just use that plugin?

Closing this issue then.
