### ISSUE TITLE
Traefik becomes ready before CRDs are loaded

### ISSUE THREAD

**Issue by fbsb** [traefik/traefik#9078]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have configured and deployed traefik in a multi-tenant way to only watch a number of namespaces related to a single tenant
and used `--providers.kubernetescrd.namespaces` and `--providers.kubernetesingress.namespaces` for this.

Some of our tenants have a large amount of namespaces e.g. > 40 namespaces.

### What did you see instead?

When configured with a high number of namespaces, traefik has a very slow startup (>1min for 40 namespaces and >10min >200 namespaces) while becoming ready way too early.
Since the pods become ready and start accepting traffic before all objects are loaded, requests end up with a 404 response thus breaking application ingress.

### What version of Traefik are you using?

```
Version:      2.6.3
Codename:     rocamadour
Go version:   go1.17.8
Built:        2022-03-29T13:09:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```
  - args:
    - --global.checknewversion=false
    - --global.sendanonymoususage=false
    - --pilot.dashboard=false
    - --api.dashboard=true
    - --ping=true
    - --serverstransport.insecureskipverify
    - --metrics.prometheus=true
    - --metrics.prometheus.entrypoint=metrics
    - --metrics.prometheus.buckets=0.001,0.005,0.01,0.02,0.05,0.1,0.3,1.2,5.0
    - --providers.kubernetescrd
    - --providers.kubernetescrd.labelselector=ingress-domain in (playground, shared)
    - --providers.kubernetescrd.namespaces=${tenant_namespaces},${shared_namespaces}
    - --providers.kubernetescrd.allowCrossNamespace=true
    - --providers.kubernetesingress
    - --providers.kubernetesingress.ingressclass=traefik2-playground
    - --providers.kubernetesingress.namespaces=${tenant_namespaces}
    - --providers.file.filename=/config/traefik.yaml
    - --entrypoints.traefik.address=:9000/tcp
    - --entrypoints.metrics.address=:9100/tcp
    - --entrypoints.dashboard.address=:9200/tcp
    - --entrypoints.http.address=:8000/tcp
    - --entrypoints.http.transport.lifecycle.gracetimeout=120s
    - --entrypoints.http.transport.lifecycle.requestacceptgracetimeout=20s
    - --entrypoints.https.address=:8443/tcp
    - --entrypoints.https.http.tls=true
    - --entrypoints.https.transport.lifecycle.gracetimeout=120s
    - --entrypoints.https.transport.lifecycle.requestacceptgracetimeout=20s
```

### If applicable, please paste the log output in DEBUG level

with 41 namespaces
```
...
I0607 10:49:55.509477       1 trace.go:205] Trace[1538044371]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (07-Jun-2022 10:48:44.122) (total time: 71387ms):
Trace[1538044371]: ---"Objects listed" 71387ms (10:49:55.509)
Trace[1538044371]: [1m11.387048212s] [1m11.387048212s] END
I0607 10:49:55.708722       1 trace.go:205] Trace[1095936439]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (07-Jun-2022 10:48:44.122) (total time: 71586ms):
Trace[1095936439]: ---"Objects listed" 71586ms (10:49:55.708)
Trace[1095936439]: [1m11.586404231s] [1m11.586404231s] END
I0607 10:49:55.909193       1 trace.go:205] Trace[858266121]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (07-Jun-2022 10:48:44.122) (total time: 71786ms):
Trace[858266121]: ---"Objects listed" 71786ms (10:49:55.909)
Trace[858266121]: [1m11.786709211s] [1m11.786709211s] END
...
```

with >200 namespaces
```
...
I0607 09:43:32.965718       1 trace.go:205] Trace[1725963254]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (07-Jun-2022 09:32:34.835) (total time: 658129ms):
Trace[1725963254]: ---"Objects listed" 658129ms (09:43:32.965)
Trace[1725963254]: [10m58.129927624s] [10m58.129927624s] END
I0607 09:43:33.171673       1 trace.go:205] Trace[1633828087]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (07-Jun-2022 09:32:34.835) (total time: 658335ms):
Trace[1633828087]: ---"Objects listed" 658335ms (09:43:33.171)
Trace[1633828087]: [10m58.335842729s] [10m58.335842729s] END
I0607 09:43:33.367442       1 trace.go:205] Trace[1658988835]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167 (07-Jun-2022 09:32:34.835) (total time: 658531ms):
Trace[1658988835]: ---"Objects listed" 658531ms (09:43:33.367)
Trace[1658988835]: [10m58.53156797s] [10m58.53156797s] END
...
```

**Comment by rtribotte** [comment]
Hello @fbsb,

Thanks for your interest in Traefik!

I understand that you are more concerned about the readiness of the Traefik pod rather than the time it takes to fetch and populate the informer's cache (when having a lot of resources/namespaces).
Is it correct?

I'm wondering if you already implemented mechanisms to check the readiness of the Traefik pod and if you identified what would be missing to check that readiness.

**Comment by rtribotte** [comment]
Hello @fbsb,

Thanks for your feedback!

Indeed the second approach seems better and just so you know, you can also expose the API ping endpoint if you don't need the dashboard.
It is true that today, the ping endpoint is only designed to signify that Traefik is started (liveness), and not to state if any configuration has been loaded or not.

>  If I'm not mistaken, there seems to be some client-side throttling slowing this process down quite a bit. This seems to not be related to the ammount of resources in the cluster, and only to the ammount of namespaces traefik has to watch.

What throttling are you referring to? The one for the Traefik Kubernetes provider itself or rather a throttling in the Kubernetes client itself?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
