### ISSUE TITLE
[feature] Distribute Traefik as an apt/deb package

### ISSUE THREAD

**Issue by LordMike** [traefik/traefik#9080]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,

I'm looking to install traefik on a server that won't be running docker, so I looked into how this would work. Luckily, traefik is also distributed as individual binaries, so that's cool - but it will make updating and maintenance cumbersome.

Could you be lured into distributing traefik as packages (apt/deb/yum), in addition to docker and so on?

This would make deployment as binaries easier, as apt would be able to handle updates -- and it would make it possible to setup systemd services or init.d scripts as well.

Mike.

**Comment by mpl** [comment]
Hello,

we have of course nothing against a .deb package for Traefik, but we won't take the burden of creating and maintaining it ourselves.
And such a package wouldn't even live on our repo anyway.

fwiw, as with most Go programs, the Traefik binary is trivial to build. I run it as binary in a systemd service myself. I can give you my service if you really need, but it's probably really dumb.
