### ISSUE TITLE
Acme DNS challenge - param validation issue

### ISSUE THREAD

**Issue by dazinator** [traefik/traefik#9082]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Configured an ACME provider with Azure DNS - got it working.
Later one the variables (in an .env file used by docker-compose) specifically for Resource Group had some additional whitespace at the end:
.env
```
AZURE_RESOURCE_GROUP=foo    
```

Note: there are a few spaces after the value `foo`

This gets passed into the traefik container as an environment variable in the compose file like so:

```
environment:
     # shortened for brevity
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
```

### What did you see instead?

Later when traefik performs the ACME dns challenge, I see this in the logs (i've redacted some info):

```
ee0fu  time="2022-06-09T22:25:19Z" level=error msg="Unable to obtain ACME certificate for domains \"*****.io\": unable to generate a certificate for the domains [*****.io]: error: one or more domains had a problem:\n[*****.io] [*****.io] acme: error presenting token: azure: dns.ZonesClient#Get: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern value=\"foo    \" details: value doesn't match pattern ^[-\\w\\._\\(\\)]+$\n" ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=reverse-proxy-forward-auth@docker rule="Host(`*****.io`)" providerName=letsEncrypt.acme
```

it subsequently fails to get the cert.

### What version of Traefik are you using?

2.7.0

### What is your environment & configuration?

relevent config posted above.

### If applicable, please paste the log output in DEBUG level

```
ee0fu  time="2022-06-09T22:25:19Z" level=error msg="Unable to obtain ACME certificate for domains \"*****.io\": unable to generate a certificate for the domains [*****.io]: error: one or more domains had a problem:\n[*****.io] [*****.io] acme: error presenting token: azure: dns.ZonesClient#Get: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=Pattern value=\"foo    \" details: value doesn't match pattern ^[-\\w\\._\\(\\)]+$\n" ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=reverse-proxy-forward-auth@docker rule="Host(`*****.io`)" providerName=letsEncrypt.acme
```

**Comment by ldez** [comment]
Hello,

The env var `AZURE_RESOURCE_GROUP` is handled by the [official Azure client](https://github.com/Azure/azure-sdk-for-go), Traefik doesn't read this env var by itself.

> value=\"foo    \" details: value doesn't match pattern ^[-\\w\\._\\(\\)]+$\n"

The error, thrown by the [official Azure client](https://github.com/Azure/azure-sdk-for-go), seems clear.

Traefik cannot clear or alter this env var.

**Comment by dazinator** [comment]
Ok thanks. I will make sure the environment variables is trimmed of whitespace prior.
