### ISSUE TITLE
Is round-robin (weighted or not) possible for docker provider to route traffic into several different services? 

### ISSUE THREAD

**Issue by bayeslearner** [traefik/traefik#9086]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I think what I'm asking pertains to apps that have multiple versions of the same services OR has their own "clustering" (such as a splunk search head cluster).  

In my docker-compose file,  I have 3  services which are 3 splunk search head clustering nodes, and no they can't be "scaled" like some other applications, so they have to be defined as separate services.  

I need to know whether it is possible to use the same traefik services for different docker-compose services. 

I know this is possible for file or ingress-route for k8s.  My question is specific to docker. 

### What did you see instead?

It doesn't work. 

### What version of Traefik are you using?

2.3

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

```
sh1:
    networks:
      splunknet:
        aliases:
          - sh1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: sh1
    container_name: sh1
    depends_on:
      - shd
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3 #,idx4,idx5,idx6,idx7,idx8,idx9,idx10,idx11,idx12,idx13,idx14,idx15
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_PREFERRED_CAPTAINCY=true
      - SPLUNK_CLUSTER_MASTER_URL=cm
      - SPLUNK_ROLE=splunk_search_head_captain
      - SPLUNK_DEPLOYER_URL=shd
      - SPLUNK_DEPLOYMENT_SERVER=ds
      - SPLUNK_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults/sh:/tmp/defaults
    labels:
       - traefik.http.routers.www-router.entrypoints=web
       - traefik.http.routers.www-router.service=www-service
       - traefik.http.routers.www-router.rule=Host(`shc.bayes-dev.lan`)
       - traefik.http.services.www-service.loadbalancer.server.port=8000

  sh2:
    networks:
      splunknet:
        aliases:
          - sh2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    command: start
    hostname: sh2
    container_name: sh2
    depends_on:
      - shd
      - sh1
      - cm
      - ds
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=idx1,idx2,idx3 #,idx4,idx5,idx6,idx7,idx8,idx9,idx10,idx11,idx12,idx13,idx14,idx15
      - SPLUNK_SEARCH_HEAD_URL=sh2,sh3
      - SPLUNK_SEARCH_HEAD_CAPTAIN_URL=sh1
      - SPLUNK_CLUSTER_MASTER_URL=cm
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_DEPLOYER_URL=shd
      - SPLUNK_DEPLOYMENT_SERVER=ds
      - SPLUNK_LICENSE_URI
      - DEBUG=true
    ports:
      - 8000
      - 8089
    volumes:
      - ./defaults/sh:/tmp/defaults
    labels:
       - traefik.http.routers.www-router.entrypoints=web
       - traefik.http.routers.www-router.service=www-service
       - traefik.http.routers.www-router.rule=Host(`shc.bayes-dev.lan`)
       - traefik.http.services.www-service.loadbalancer.server.port=8000

```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by bayeslearner** [comment]
please reopen this!
