### ISSUE TITLE
Allow other service label prefixes than "traefik" to facilitate major version migration

### ISSUE THREAD

**Issue by erikhe1** [traefik/traefik#9102]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi!

This is a bit late, I know, since Traefik v1 is EOL. However, this suggestion might also be useful to facilitate future major version migrations, and there are likely others who also are still are running v1.

# Background

I have to migrate a Docker cluster from using Traefik v1 to using Traefik v2. This of course involves replacing labels on every single service, of which there are a lot.

I'd like to avoid downtime as much as possible, so it seems to me that the safest way is to migrate services **gradually** rather than trying to switch all the services to use v2 at the same time. Doing everything at once, downtime will be unavoidable, there is a risk of errors piling up, and rollback is complicated.

I think this might be the simplest approach for gradual service migration:

1. Run both Traefik v1 and v2 at the same time, but let v2 map container ports 80 and 443 to some other host ports (e.g. `3000:80`, `3001:443`).
2. For each service, one by one: Add the v2-compliant labels without removing the v1 labels, making sure that **both** Traefik v2 and v1 route correctly to the updated services.
3. Remove the host port mapping from Traefik v1, and instead let Traefik v2 listen on the host ports 80 and 443.

After this, the migration is complete. The Traefik v1 service can be taken down and the v1 labels can be removed from all services.

# Issue

However, I found this approach might not work because [v1 and v2 labels can conflict](https://github.com/traefik/traefik/issues/8159) and cause issues (one answer in the issue links to a guide for gradual migration, but that approach seems complex and also requires running v1 and v2 in parallel, so I'm not sure how that would be any better).

# Feature request

A simple way to avoid label conflict between v1 and v2 could be to **add an *optional* configuration setting** to Traefik v2, to let Traefik look for some different label prefix than `traefik` on the Docker services, for instance `traefik2`.

So, for example, instead of setting this label on a service:

```yaml
- traefik.http.routers.traefik-public-https.entrypoints=https
```

we would be able to set:

```yaml
- traefik2.http.routers.traefik-public-https.entrypoints=https
```

This way, a service could have Traefik v1 labels, prefixed by `traefik` and Traefik v2 labels prefixed by `traefik2`. The Traefik v1 service would only look for `traefik` labels and the Traefik v2 service would only look for `traefik2` labels, ignoring any `traefik` labels. No conflicts would occur.

The default label prefix in v2 would of course still be `traefik` so the change would be non-breaking.

Does this seem reasonable? :)

**Comment by toxic0berliner** [comment]
Not sure it's a good enough reason but other reverse proxy having docker provider like Caddy and reproxy both propose a way to use labels starting with whichever string the user likes, so at least it shows there is interest and I have another (although niche) use case myself too for this

**Comment by jonasgeiler** [comment]
I believe setting a custom prefix might also help with security-through-obfuscation. For example a person building a Docker image could set malicious labels on the image that expose critical endpoints to the public internet. But if you can customize the prefix you could mitigate this by setting a unique prefix for your own infrastructure, which only your sysadmins know and are able to see, like `acmecorp-traefik`. Then, only a `acmecorp-traefik.enable=true` label enables Traefik, but not a `traefik.enable=true` label. The person building the Docker image would have to know this.
