### ISSUE TITLE
Config option to remove Hub button from dashboard

### ISSUE THREAD

**Issue by magicrobotmonkey** [traefik/traefik#9108]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In traefik 2.8, there is a big yellow button labelled "Go to Hub Dashboard" on the traefik dashboard. It would be great if there was a config option to remove this button. This issue was previously raised in #8912, but it appears that was closed because hub integration wasn't included in 2.7.

**Comment by ldez** [comment]
Hello,

could you explain why do you want to remove this button?

**Comment by magicrobotmonkey** [comment]
We don't have a hub account, so it's confusing to users. When users click it, it just takes them to a login page they don't have credentials for.

**Comment by magicrobotmonkey** [comment]
Yes but even once it's launched, I may not use it.

**Comment by ddtmachado** [comment]
@magicrobotmonkey Traefik Hub Beta is now launched so anyone clicking on the button will land on the correct page, so would you agree the original problem is not there anymore?

Also it's literally just a link, no data collection, no stop the world advertising and it's a useful link to jump to the Hub Dashboard for those that will use it. Would you still be bothered by it?

Personally, I feel that having a new config option on the static configuration would be worst than just ignoring a link/button on an UI :)

**Comment by magicrobotmonkey** [comment]
I don't disagree that more config options may not be the way to go, but considering that there appears to already be configuration around activating/configuring hub integration, maybe this button should be gated behind that?

**Comment by schodemeiss** [comment]
> I don't disagree that more config options may not be the way to go, but considering that there appears to already be configuration around activating/configuring hub integration, maybe this button could be gated behind that?

^This^. I've been trying to disable it by disabling everything I can about the hub. It's an annoying distraction of a big yellow button which none of m'colleagues will be clicking on or using anytime soon. Please consider letting us remove it.

**Comment by tfny** [comment]
Hey @magicrobotmonkey and @schodemeiss, 

Thanks for the feedback.  We don't have any plans to remove the button because we want to make sure that people using the product know that they can use Traefik Hub easily and for free.  However, when it comes time to reconsider in a few months, we will take your feedback into consideration.

We developed Traefik Hub based on community feedback to address some of the pain points of networking container-based applications. So, if you choose to give it a try, please feel free to reach out to me at [Tiffany.Long @traefik.io](mailto:Tiffany.Long@traefik.io).

I am going to close the issue for now.

**Comment by alajmo** [comment]
I would like to disable this as well, the same reasoning goes for the previous feature `pilot`, which you provided users with the possibility to disable. 
It's really bad UX if 10% of your users are interested in the `hub` feature, whereas 90% aren't. It's also quite distracting to have a big yellow button which takes away focus from all other important sections. And if you insist on having the hub functionality, why not just make it a small button similar to the `?` button and place it next to it.

**Comment by schodemeiss** [comment]
I might be off the mark here, but I wonder if the "feeling" is that "hiding it" basically removes the advertising it provides.

If that assuming is correct, my $$'s on it is, if you've seen the big yellow button; you've seen the advertising. The fact one wants to disable it means one is clearly not interesting in it. So why not allow one to stop the advertising being there?

**Comment by djpbessems** [comment]
This is just a repeat of Traefik Pilot's button being shoved into our faces; I'm considering leaving Traefik behind if this is the default attitude towards genuine requests to not show UI elements for features not being used.

**Comment by proggaras** [comment]
I was lucky to get this pilot button removed with a config option and now you start with an other annoying hub button... 👎

**Comment by mpl** [comment]
> This is just a repeat of Traefik Pilot's button being shoved into our faces; I'm considering leaving Traefik behind if this is the default attitude towards genuine requests to not show UI elements for features not being used.

So when you have a router configured with no TLS and no middleware,  should we remove as well these empty boxes for features you're not using? I am sure there's several pieces of software you're using with UI elements for features you are never using as well. Do you intend to stop using these other software as well?

![image](https://user-images.githubusercontent.com/626071/177995574-ba64b0f0-c3b3-464b-8856-58ad28f8fa7d.png)

**Comment by djpbessems** [comment]
> So when you have a router configured with no TLS and no middleware, should we remove as well these empty boxes for features you're not using? I am sure there's several pieces of software you're using with UI elements for features you are never using as well. Do you intend to stop using these other software as well?
> 

As already said by @schodemeiss ; that is not comparable at all.

I would very much appreciate it if you could stay constructive without derailing this issue.

**Comment by letian0805** [comment]
Two buttons on the dashboard make me lose interest in traefik, one is the plugins button and the other is the hub button. They can pose security risks.

**Comment by letian0805** [comment]
No one in any company wants to be forced to add an external link to their intranet system.

**Comment by Pro-Tweaker** [comment]
It's a genuine concern and the attitude towards it from the team is really disappointing.

It was possible to disable the pilot button and now we are back at the starting point: a useless big yellow button going to an external link when the feature is not needed and not used.

We need the option to hide this button.

**Comment by phyber** [comment]
> We don't have any plans to remove the button because we want to make sure that people using the product know that they can use Traefik Hub easily and for free. However, when it comes time to reconsider in a few months, we will take your feedback into consideration.

Not sure there's really a need to wait months here. People are aware of it now, and deciding that they don't want it now.

**Comment by georglauterbach** [comment]
I agree, one should be able to disable this button 👍🏼 While I understand that the dev team want people to use this service, we could easily solve this by enabling it by default, and providing an option to disable the button of users do not need it and do not want it.

**Comment by joe-eklund** [comment]
I deploy Traefik in air gapped networks with no internet access. So not only is this button annoying, but it actually doesn't even work since it has not internet access. I would very much like to be able to disable it.

I agree with https://github.com/traefik/traefik/issues/9108#issuecomment-1174869263. Traefik Hub is a rebranding of Traefik Pilot, and @SantoDE said at https://github.com/traefik/traefik/issues/7360#issuecomment-802819400 that the Traefik Pilot phone home would become configurable, which was completed in https://github.com/traefik/traefik/pull/7994. I don't understand how this is not the same thing. This was decided already and now Traefik is trying to sneak it back in.

I thought this was fixed last year but now it's back. Completely unacceptable.

**Comment by sgreiner** [comment]
We would also need to remove the "Hub" and the "Plugins" buttons, and more importantly disable the plugins und hub function completely via static configuration. It is somehow security relevant to guarantee the servers code is not changed during runtime.

**Comment by SaswatPadhi** [comment]
> So when you have a router configured with no TLS and no middleware, should we remove as well these empty boxes for features you're not using? I am sure there's several pieces of software you're using with UI elements for features you are never using as well. Do you intend to stop using these other software as well?

This can't possibly be a serious question. 

> We don't have any plans to remove the button because we want to make sure that people using the product know that they can use Traefik Hub easily and for free. However, when it comes time to reconsider in a few months, we will take your feedback into consideration.

Agreed. So keep the big yellow flashy button in the default configuration. But, if someone saw it, and still decided that it's not useful for them, respect that and give them a way to disable this feature entirely.

**Comment by zotabee** [comment]
Please, disable this button by default or add a way to hide this!

**Comment by georglauterbach** [comment]
# How To Disable This Button

**In collaboration with @rkulow - he did most of the  work!**

---

1. Enable plugins (specifically [`rewritebody`](https://github.com/traefik/plugin-rewritebody))

These are the CLI flags (if you're using K8s for example):

``` TXT
- --experimental.plugins.enabled=true
- --experimental.plugins.rewritebody.modulename=github.com/traefik/plugin-rewritebody
- --experimental.plugins.rewritebody.version=v0.3.1
```

2. Build a middleware

``` YAML
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: rewrite-traefik-dashboard

spec:
  plugin:
    rewritebody:
      lastModified: true
      rewrites:
        - regex: </head>
          replacement: |
            <style type="text/css">a.btn-hub { display: none !important; }</style>
            </head>
```

3. Add the middleware to the ingress of your dashboard

**Comment by ChristianCiach** [comment]
This is the Pilot thingy all over again! We deploy traefik air-gapped, so this button does not and will never work for us. I am also not very pleased to see advertisements sneaking into open source projects.

I think that is the end of the line. I will try to find an alternative to traefik. If there eventually will be a config to disable the Hub integration, Traefik will just rebrand and will remove the config again. I will not play this game again.
