### ISSUE TITLE
There isn't possible to define datacenter when I'm using the new Nomad Service Discovery

### ISSUE THREAD

**Issue by SrMouraSilva** [traefik/traefik#9109]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to use the new Nomad Service Discovery. I'm trying to define a custom `datacenter` ([following the documentation](https://doc.traefik.io/traefik/v2.8/providers/nomad/#datacenter)):

```bash
docker run -it --rm traefik:v2.8.0-rc1  \
  --api=true  \
  --api.dashboard=true  \
  --api.insecure=true  \
  --entrypoints.web.address=:8000  \
  --entrypoints.web-secure.address=:8443  \
  --log.level=DEBUG  \
  --serversTransport.insecureSkipVerify=true  \
  --providers.docker=true  \
  --providers.docker.swarmMode=false  \
  --providers.docker.exposedByDefault=false  \
  --providers.nomad=true  \
  --providers.nomad.endpoint.address=http://192.168.100.35:4646  \
  --providers.nomad.endpoint.datacenter=dc1 \
  --providers.nomad.endpoint.token=token  \
  --providers.nomad.exposedByDefault=false
```

### What did you see instead?

The following error appears:

```
2022/06/17 19:27:57 command traefik error: failed to decode configuration from flags: field not found, node: datacenter
```

### What version of Traefik are you using?

v2.8.0-rc1

### What is your environment & configuration?

All configurations are defined using `CLI`

**Comment by kevinpollet** [comment]
Hello @SrMouraSilva,

Thanks for pointing this out,

This is an unfortunate copy/paste from the consul catalog provider. We will open a pull request to fix that.

**Comment by traefiker** [comment]
Closed by #9111.

**Comment by SrMouraSilva** [comment]
Thanks!

**Comment by SrMouraSilva** [comment]
@kevinpollet, there are a prevision of the release date of v2.8.0? Or maybe do we have another RC candidate? I would appreciate to test it, but I didn't found any new release of traefik on Docker Hub.

Btw, apparently I should to use `namespace` instead of `datacenter`. But I also had problems with the `token` (fixed in #9111), so using v2.8.0-RC1 won't work with me.

**Comment by SrMouraSilva** [comment]
Apparently now there is another bug.

If I didn't define `providers.nomad.namespace` or define it as `default`, 
```
"--providers.nomad=true",
"--providers.nomad.endpoint.address=http://192.168.100.35:4646",
"--providers.nomad.namespace=default",
"--providers.nomad.endpoint.token=myuuidtoken,
"--providers.nomad.exposedByDefault=false",
```
Appears repeatedly `Failed to build HTTP service configuration: address is missing`
```
time="2022-06-21T23:51:58Z" level=debug msg="*nomad.Provider provider configuration: {\"defaultRule\":\"Host(`{{ normalize .Name }}`)\",\"endpoint\":{\"address\":\"http://192.168.100.35:4646\",\"token\":\"xxxx\"},\"prefix\":\"traefik\",\"namespace\":\"default\",\"exposedByDefault\":true,\"refreshInterval\":\"15s\"}"
time="2022-06-21T23:52:58Z" level=error msg="Failed to build HTTP service configuration: address is missing" providerName=nomad
time="2022-06-21T23:52:58Z" level=debug msg="Configuration received: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=nomad
time="2022-06-21T23:52:58Z" level=debug msg="Skipping unchanged configuration." providerName=nomad
time="2022-06-21T23:53:13Z" level=error msg="Failed to build HTTP service configuration: address is missing" providerName=nomad
time="2022-06-21T23:53:13Z" level=debug msg="Configuration received: {\"http\":{},\"tcp\":{},\"udp\":{}}" providerName=nomad
time="2022-06-21T23:53:13Z" level=debug msg="Skipping unchanged configuration." providerName=nomad
```
If I define something else, this error doesn't appears, but also no one device is discovered.

I probably will create another issue for this...

**Comment by kevinpollet** [comment]
Hey @SrMouraSilva,

> If I didn't define `providers.nomad.namespace` or define it as `default`

As explained in the Nomad API client [documentation](https://github.com/hashicorp/nomad/blob/main/api/api.go#L170) when the namespace is not provided the `default` namespace is used.  

> Appears repeatedly Failed to build HTTP service configuration: address is missing

This error means that the HTTP service discovered does not have an address which seems to be a configuration issue.

> If I define something else, this error doesn't appear, but also no one device is discovered.

Maybe there are no services in the configured the `namespace`, and the error is raised when setting the namespace to `default` because this is the namespace containing the services.

**Comment by SrMouraSilva** [comment]
Thanks @kevinpollet. I had some errors when I was configuring.
After some hours of tests, I can confirm that it is working.

My principal problem was caused by `nomad service stanza`. If I define the `service` at `task` level instead of `group` level, Nomad will not informs to Traefik.

I saw it on https://traefik.io/blog/traefik-proxy-fully-integrates-with-hashicorp-nomad/, but I thought that was ok.

**Comment by kevinpollet** [comment]
> My principal problem was caused by nomad service stanza. If I define the service at task level instead of group level, Nomad will not informs to Traefik.

We tried adding the `service` declaration at the `task` level and everything is working fine. As stated in the Nomad [documentation](https://www.nomadproject.io/docs/job-specification/service#service-stanza) defining the service at the `task` level is allowed.

The `service` configuration (which can be defined multiple times) is the way used to register a `service` in the Nomad service discovery. The configured service `port` will be the one advertised in the discovery and the way to send traffic to a specific task.

> Now I don't know how Traefik works if I define multiple tasks to a just one group.

As Traefik is using the Nomad service discovery to discover the router configurations, which are populated with the `service` configurations, defining multiple tasks will just work as expected.

**Comment by SrMouraSilva** [comment]
Ok @kevinpollet. Thanks for clarifications.

I'm updating the infrastructure to use Nomad + Traefik. :smile: 

--

The unique down side that I currently noticed is that Nomad (without Consul) doesn't use the Docker HealthCheck, so isn't possible to auto-promote a Canary version as I expected.

https://github.com/hashicorp/nomad/issues/5310#issuecomment-1163321663

I can use Traefik HealthCheck to avoid send data to a unhealthy container but Nomad won't avoid to promote this unhealthy container.

Do you know if something will be commented at next Webinar? (https://info.traefik.io/webinar-traefik-nomad-provider)

-- 

I apologies for consuming your time.
