### ISSUE TITLE
Nomad provider fails to load initial nomad services

### ISSUE THREAD

**Issue by DamboisP** [traefik/traefik#9119]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

A configured the new nomad provider in traefik like this:
```
  nomad:
    prefix: "traefik"
    endpoint:
      token: MY_TOKEN
      address: https://url_to_nomad
```

### What did you see instead?

When calling https://url_to_nomad/v1/services with the proper X-Nomad-Token header it works (I get a HTTP 200 response) but when that same call is made in the nomad provider it returns a 403 (see log below)

It looks like the token isn't passed at all. 
I assume the configuration is read correctly because before that I encountered other errors where my endpoint was logged.

### What version of Traefik are you using?

2.8

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

{"level":"error","msg":"Provider connection error failed to load initial nomad services: Unexpected response code: 403 (Permission denied), retrying in 2.382501263s","providerName":"nomad","time":"2022-06-21T16:15:46Z"}

**Comment by kevinpollet** [comment]
Hello @DamboisP,

Thanks for your interest in Traefik,

In https://github.com/traefik/traefik/pull/9111 we fixed an issue with the Nomad token not being used by the Nomad client.

We will release a `v2.8.0-rc2` in the coming days, in the meantime, you could use the `traefik/traefik:experimental-v2.8` image which is built from the `v2.8` branch.

Does that fix your issue?

**Comment by DamboisP** [comment]
Hello, yes it fixed my issue ! Thanks for answering so quickly and sorry for not being able to find it myself before opening that issue. 

Have a nice day
