### ISSUE TITLE
KV Provider errors with 'MOVED 3999 11.11.11.11:6379' redirect when configured against a Redis in cluster mode

### ISSUE THREAD

**Issue by Marcus-Smallman** [traefik/traefik#9120]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Configure Traefik 2.7.0 with a Redis provider with the following config:

```
[providers.redis]
    endpoints = ["10.10.10.10:6379"] // Changed to 10.10.10.10 as an example, represents the Redis cluster endpoint
```

And store the following key in Redis: `traefik/http/middlewares/test-middleware/headers/accesscontrolalloworiginlist`
With a string value of: `https://test.com,http://gv.local`

I would expect Traefik to then have a headers middleware with the test-middleware name configured with the allow origin list with the specified value.

### What did you see instead?

Traefik errors with the following:

```
time="2022-06-22T12:14:55Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 1.601344067s" providerName=redis
time="2022-06-22T12:14:57Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 1.237622777s" providerName=redis
time="2022-06-22T12:14:58Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 1.738468751s" providerName=redis
time="2022-06-22T12:15:00Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 5.257850991s" providerName=redis
time="2022-06-22T12:15:05Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 3.817382173s" providerName=redis
time="2022-06-22T12:15:09Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 5.008328454s" providerName=redis
time="2022-06-22T12:15:14Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 6.972922842s" providerName=redis
time="2022-06-22T12:15:21Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 28.261612383s" providerName=redis
time="2022-06-22T12:15:49Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 648.668248ms" providerName=redis
time="2022-06-22T12:15:50Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 680.346224ms" providerName=redis
time="2022-06-22T12:15:50Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 1.51842417s" providerName=redis
time="2022-06-22T12:15:52Z" level=error msg="KV connection error: KV store connection error: MOVED 7605 11.11.11.11:6379, retrying in 1.644962491s" providerName=redis
```
// Note: Changed the actual IP to 11.11.11.11 as an example, but it represents a different node in the Redis cluster that the key is stored on

### What version of Traefik are you using?

2.7.0

### What is your environment & configuration?

```yaml
[providers]
  [providers.redis]
    endpoints = ["10.10.10.10:6379"] // Changed to 10.10.10.10 as an example, represents the Redis cluster endpoint
```

Add more configuration information here.

**Comment by tomMoulard** [comment]
Hello @Marcus-Smallman,

Thanks for your interest in Traefik!

I've reproduced your issue. But when the `endpoints` configuration is set to the Redis cluster master node endpoint, Traefik works as expected.

But setting the master node endpoint 'manually' can be cumbersome, as it can be dynamically determined by the Redis cluster.
A better way would be to set in `endpoints` all Redis cluster nodes, and let Traefik find the master one for us. Doing so would require a change in the library Traefik uses to communicate with Redis: https://github.com/kvtools/valkeyrie.

As both of these issues are not related to Traefik in itself, we will close this issue.
