### ISSUE TITLE
IngressRouteTCP Kind unknown

### ISSUE THREAD

**Issue by universenl** [traefik/traefik#9126]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

We have deployed a new traffic 2.7.1 on Azure aks 1.23.5.
We did use the rbac and definitions from the traefik website for this version.

### What did you see instead?

error: error validating "ingress.yaml": error validating data: ValidationError(IngressRouteTCP.spec.routes[0]): unknown field "kind" in us.containo.traefik.v1alpha1.IngressRouteTCP.spec.routes; if you choose to ignore these errors, turn validation off with --validate=false

### What version of Traefik are you using?

v2.7.1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by kevinpollet** [comment]
Hello @universenl,

Thanks for your interest in Traefik,

There is no `kind` field in the `IngressRouteTCP` CRD spec, as explained in the [documentation](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp).

According to this, we will close this issue as a question.

Do not hesitate to join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik), if you need help.
