### ISSUE TITLE
Changed behavior on WebSockets between 2.7.1 and 2.7.2 

### ISSUE THREAD

**Issue by moutoum** [traefik/traefik#9155]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Traefik router is configured with the `RedirectScheme` middleware with `scheme: https` and `port: 443`.
I send an HTTP request with `Connection: upgrade` and `Upgrade: websocket` headers.

### What did you see instead?

When sending the request, I receive a `302 Found` instead of `101 Switching Protocol`.
The `Location` header in the response also contains an ill formatted URL: `https://wss://example.com`

### What version of Traefik are you using?

v2.7.2

### What is your environment & configuration?

https://community.traefik.io/t/changed-behavior-on-websockets-between-2-7-1-and-2-7-2/14953

**Comment by pangliang** [comment]
same issue v2.8.0

**Comment by croemmich** [comment]
Same. Downgrading to 2.7.1 to resolved the issue.

**Comment by mmozzano** [comment]
Excellent, been having an issue with my self hosted code-server giving me the following error when going to the URL: 

**_The workbench failed to connect to the server (Error: WebSocket close with status code 1006)_**

Have been searching for a few days for a solution, have come across this and downgraded Traefik back to 2.7.1 and the issue has gone away.

**Comment by traefiker** [comment]
Closed by #9159

**Comment by mmozzano** [comment]
For info, the issue I was having above with getting the websocket 1006 error when connecting to my self hosted code-server instance has been resolved by 2.8.1.  

Thank you very much.

**Comment by kimpenhaus** [comment]
I had issues with HomeAssistant and Gotify - both fixed with 2.8.1 👌
