### ISSUE TITLE
Documentation is a little bit confused

### ISSUE THREAD

**Issue by ivictbor** [traefik/traefik#9160]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I've recently started using Traefik, and when I searched how to use Basic Auth I quickly found Documentation page:

![image](https://user-images.githubusercontent.com/1838656/177131880-4138be79-9054-45ff-9c4a-f764f8ff2bb0.png)

But thing is that copy-pasting this snippet does not work, and you have to understand that you also need to activate middleware, probably I had to read whole doc first to understand it, but I think low number of devs doing it like this in our world where there are tons of different tools. So it works if you add:

```
labels:
  - "traefik.http.routers.api.middlewares=test-auth"
  - "traefik.http.middlewares.test-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
```

So I mean why not to just add this line to snippet too, at least to first one:

```
 - "traefik.http.routers.api.middlewares=test-auth"
```

**Comment by kevinpollet** [comment]
Hello @ivictbor,

Thanks for your interest in Traefik,

As explained in https://github.com/traefik/traefik/pull/9057#issuecomment-1143275561

> The configuration example section in a [middleware](https://doc.traefik.io/traefik/routing/providers/docker/#middleware) page contains only an example of an available configuration option for this middleware. This example is not meant to include a working router configuration, as introduced by this pull request. For that, we already have a generic page documenting how to configure a router referencing a middleware.

According to this, we will decline this issue.
