### ISSUE TITLE
Disable plugins link from dashboard

### ISSUE THREAD

**Issue by letian0805** [traefik/traefik#9196]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Incorrect use of plugins will bring risks, please provide parameters to disable plugins.

**Comment by SantoDE** [comment]
Hey @letian0805,

thanks for your interest in Traefik.

Not gonna lie, I am a bit surprised by that request. The menu item called "Plugins" is just a link to our new plugin catalog over at [https://plugins.traefik.io](https://plugins.traefik.io). A link is not causing any risks at all. Therefore, I don't see any need to disable that link

I'll close that issue accordingly.

**Comment by letian0805** [comment]
@SantoDE 
No one in any company wants to be forced to add an external link to their intranet system.
