### ISSUE TITLE
command traefik error: failed to download plugin github.com/BetterCorp/cloudflarewarp: error: 500

### ISSUE THREAD

**Issue by mrinc** [traefik/traefik#9225]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Other Refs:  https://github.com/traefik/traefik/issues/7358 - https://github.com/darkweak/souin/issues/209 - https://community.traefik.io/t/downloading-plugins-fails-with-client-timeout/8896

Spinning up an instance of traefik, with config and all defined as would be production: 
https://github.com/BetterCorp/cloudflarewarp/actions/runs/2782040700 
https://github.com/BetterCorp/cloudflarewarp/actions/runs/2783000196

### What did you see instead?

```command traefik error: failed to download plugin github.com/BetterCorp/cloudflarewarp: error: 500```  
Ref:  https://github.com/BetterCorp/cloudflarewarp/issues/12

### What version of Traefik are you using?

2.8 - traefik:latest

### What is your environment & configuration?

https://github.com/BetterCorp/cloudflarewarp/blob/master/test/traefik-prod.toml  

https://github.com/BetterCorp/cloudflarewarp/blob/master/test/traefik-compose-prod.toml

**Comment by mrinc** [comment]
I need to specifically note the following:

github connection works from the containers (local and on github)  
git clone from inside the container works no issues.  

Specifically referencing v1.0.0 of the related plugin : works  
But the latest 2.1.0 fails.

This seems to be a caching/storage issue on traefiks repo store/proxy.  

If the connection to github.com was direct, then the plugin store should be working fine.  
However, if it goes through a proxy hosted/managed by Traefik, that proxy could be erroring out.  
I am not sure where the specific code is for pulling down plugins, so was unable to further debug.

**Comment by ldez** [comment]
Hello,

> This seems to be a caching/storage issue on traefiks repo store/proxy.

The plugins service doesn't cache or store data, we just download sources from the release section of GitHub

**Comment by mrinc** [comment]
Some plugins work, some plugins don't, I am not specifically sure the details for the why.  

To replicate (as mentioned in a few related that this was an issue): have docker on your machine, and pull down the https://github.com/BetterCorp/cloudflarewarp repo.  
`cd test/` 
And run `test-prod.sh`.

This should allow you to replicate any or specific issues/plugins.

**Comment by mrinc** [comment]
@ldez Hey again haha

> The plugins service doesn't cache or store data, we just download sources from the release section of GitHub

Mmmm, I wonder what could cause it then.  
Might be some sillyness on github then.  

Will do a bit of research with this info and comment if I get anywhere :)

**Comment by ldez** [comment]
```
[stderr] {"level":"error","module_name":"github.com/BetterCorp/cloudflarewarp","module_version":"v2.1.0","error":"error: 404: 404 Not Found: not found: github.com/BetterCorp/cloudflarewarp@v2.1.0: invalid version: module contains a go.mod file, so module path must match major version (\"github.com/BetterCorp/cloudflarewarp/v2\")","message":"Failed to get module file"}
```

**Comment by ldez** [comment]
What I recommend:
- remove v2.0.0 and v2.1.0 tags
- creates something like v1.1.0 and v1.2.0

If you agree I will clean our database.

**Comment by mrinc** [comment]
Oooooooh interesting!  
Learn't something new about go versioning today   

Roger, think this is the best path to take :)   
Releases and tags nuked, will just clear and refresh the project  

Thanks!

**Comment by mrinc** [comment]
Shot! Starting from v1.3.0 which hasn't existed.... thought would be better anyway

**Comment by ldez** [comment]
In theory, you also have to add the retracted tags to the go.mod file:
https://go.dev/ref/mod#go-mod-file-retract

It's just informative but it can be useful.

**Comment by mrinc** [comment]
> ```
> {
>   "level": "error",
>   "module_name": "github.com/BetterCorp/cloudflarewarp",
>   "module_version": "v2.1.0",
>   "error": "error: 404: 404 Not Found: not found: github.com/BetterCorp/cloudflarewarp@v2.1.0: invalid version: module contains a go.mod file, so module path must match major version (\"github.com/BetterCorp/cloudflarewarp/v2\")",
>   "message": "Failed to get module file"
> }
> ```
> 
> basically, our service is a custom Go proxy, so you have to follow the same rules

Just to confirm, this error is just adding the project as a go module reference and trying to import it?

**Comment by mrinc** [comment]
> In theory, you also have to add the retracted tags to the go.mod file: https://go.dev/ref/mod#go-mod-file-retract
> 
> It's just informative but it can be useful.

Awesome shot!  
Added as well for the versions that existed.

**Comment by ldez** [comment]
I cleaned our database, the scan will happen around 4:00pm (UTC)

**Comment by ldez** [comment]
I will preshot the problem: yes your plugin is not detected, I will investigate.

**Comment by ldez** [comment]
I found the problem: we filter the repository on language (go) but you put too many scripts in your repository so now the main language of your plugin is bash.

![Screenshot 2022-08-02 at 20-38-41 Issues · BetterCorp_cloudflarewarp](https://user-images.githubusercontent.com/5674651/182449262-ef1a4e12-785b-489f-b5f9-8ca0fca25b0b.png)

**Comment by mrinc** [comment]
Whaaaa oh good lord that is funny!

... I have written a ton of tests .... 

Let me see what I can do to minimize the amount of bash scripts :)

**Comment by mrinc** [comment]
Okay,  updated now and hid the bash code from the linguistic stats

**Comment by mrinc** [comment]
Thanks again @ldez !

We're all good this side :)
