### ISSUE TITLE
Building without Docker

### ISSUE THREAD

**Issue by rienafairefr** [traefik/traefik#9226]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I tried to follow the docs here https://doc.traefik.io/traefik/contributing/building-testing/#method-2-using-go
from a fresh src download (git clone -b v2.8.1 https://github.com/traefik/traefik.git)
I wanted to build my own Docker image, so the steps using docker build/docker run were actually not working (although I'll probably use a dind build step and be done with it)
Only the webui steps seem to fail.
I tried using the IN_DOCKER env var to bypass the docker run but it didn't make a difference (the webui steps don't use it apparently)

### What did you see instead?

```console
494f4f1a6ee0:/src/traefik# IN_DOCKER=1 make binary
make build-webui-image
make[1]: Entering directory '/src/traefik'
docker build -t traefik-webui -f webui/Dockerfile webui
make[1]: docker: No such file or directory
```

### What version of Traefik are you using?

2.8.1 source

### What is your environment & configuration?

N/A

### If applicable, please paste the log output in DEBUG level

N/A

**Comment by ldez** [comment]
Hello,

if you want to create your image, I guess it's related to https://github.com/go-acme/lego/pull/1687

I recommend using the target dedicated to creating of Docker image instead of trying to create a binary: `make build-image`

**Comment by rienafairefr** [comment]
Indeed related, I've been caught/traced, seeing you there again :-)
I'll look at the `build-image` target, thanks.

**Comment by ldez** [comment]
I will close the issue
