### ISSUE TITLE
bug during plugins indexation

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#9231]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I setup a plugin that have zap in the vendors but not used during the træfik plugin runtime.  
I must see nothing like before.

### What did you see instead?

CFG post-order panic: runtime error: index out of range [0] with length 0
https://github.com/darkweak/souin/issues/243

### What version of Traefik are you using?

latest

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

Did you run your plugin in local mode before your release?
Do you run tests with yaegi inside your CI?

**Comment by darkweak** [comment]
Hello @ldez  
Yes I ran the plugin in local mode in the CI and the release was two days ago but the issue appear 7 hours ago. I thought it was a false positive but reappeared after I closed the previous one.

**Comment by ldez** [comment]
problem fixed by https://github.com/traefik/yaegi/pull/1436
