### ISSUE TITLE
ip whitelist, request rejected, avoid logging auth headers?

### ISSUE THREAD

**Issue by bitsofinfo** [traefik/traefik#9240]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm using IP whitelisting w/ Traefik and when a request is rejected and logged, the full set of headers is also logged, including the authentication. Looking at the code I don't see a way to avoid this? Is there any configuration for this or can one be added to drop the headers?

https://github.com/traefik/traefik/blob/master/pkg/middlewares/ipwhitelist/ip_whitelist.go#L68

**Comment by kevinpollet** [comment]
Closed by #9244
