### ISSUE TITLE
v2.8.2 Docker image missing architectures

### ISSUE THREAD

**Issue by justinwoodland** [traefik/traefik#9248]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using kubernetes with fluxcd to autodeploy new minor versions of apps using a regex pattern to filter tags. Today that process failed because it picked up v2.8.2, but that tag manifest is missing `linux/arm64/v8` and `linux/amd64` architectures. Kubernetes tried to deploy, but it failed because the architecture didn't match.

### What did you see instead?

My auto deployment process failed because the architectures I use are missing.

### What version of Traefik are you using?

Moved from v2.8.1 to v2.8.2

### What is your environment & configuration?

N/A

**Comment by justinwoodland** [comment]
![Screen Shot 2022-08-11 at 1 43 33 PM](https://user-images.githubusercontent.com/85194572/184225838-58be1372-e1ce-4d31-bd39-f6e5d0ba62bf.png)
Here is a screenshot of docker hub with v2.8.2 and v2.8. Notice the missing OS/Arch on v2.8.2.

**Comment by ldez** [comment]
The official Docker image is currently under construction in the Docker build system.
It's normal that you cannot pull it yet.

You have to wait a bit.
