### ISSUE TITLE
Pilot and Hub services are down and Traefik doesn't start

### ISSUE THREAD

**Issue by alexdelprete** [traefik/traefik#9267]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Configured a plugin, restarted Traefik, but pilot service (hub too) is down, so Traefik doesn't start.
Duplicate of #8617 that was closed as fixed.

### What did you see instead?

Duplicate of #8617 that was closed as solved.

### What version of Traefik are you using?

```
Version:      2.8.3
Codename:     vacherin
Go version:   go1.19
Built:        2022-08-12T14:24:34Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
# N/A
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

Thank you and we are working on it.

https://github.com/traefik/traefik-helm-chart/issues/624

**Comment by alexdelprete** [comment]
Thanks Ludovic.

Is there a way to configure Traefik to start in any case? The dependency from these remote services should not affect so severely local functionality.

**Comment by ldez** [comment]
@alexdelprete a workaround can be to use local plugins: https://github.com/traefik/plugindemo#local-mode

You will have to clone plugin repos (I can help to find it) and mount that.

**Comment by alexdelprete** [comment]
Good advice, thanks a lot. And the hub service dependency is blocking like the plugins, or it would start in that case?

**Comment by ldez** [comment]
> And the hub service dependency is blocking like the plugins, or it would start in that case?

I don't think so.

**Comment by alexdelprete** [comment]
> I don't think so.

Ok, so I guess I'll disable it for now. Thanks.

I'll check the local plugins setup now...

**Comment by rjchicago** [comment]
We experienced this issue. We disabled plugins for now and upgraded from 2.7.0 to 2.8.3 and Traefik has come back up for us. We will look into `local-mode` to re-enable plugins.

**Comment by ldez** [comment]
We're currently restoring our cluster, we are doing the quickest we can.

**Comment by alexdelprete** [comment]
> I don't think so.

Ludovic, the local plugin is working perfectly, this is the config I used:

```yaml
experimental:
  # Enable the Traefik Hub Experimental feature.
  hub: true
  http3: true
  localPlugins:
    traefik-get-real-ip:
      moduleName: github.com/Paxxs/traefik-get-real-ip
```

I didn't need to disable the hub, Traefik starts anyway, and I see no errors in the log.

**Comment by ldez** [comment]
If this can help, the list of plugins:

<details>

| plugin | clone |
|--|---|
| [github.com/17media/plugin-allowpath](https://github.com/17media/plugin-allowpath) | `git clone git@github.com:17media/plugin-allowpath.git` |
| [github.com/23deg/jwt-middleware](https://github.com/23deg/jwt-middleware) | `git clone git@github.com:23deg/jwt-middleware.git` |
| [github.com/aarlint/pathauth](https://github.com/aarlint/pathauth) | `git clone git@github.com:aarlint/pathauth.git` |
| [github.com/acouvreur/traefik-modsecurity-plugin](https://github.com/acouvreur/traefik-modsecurity-plugin) | `git clone git@github.com:acouvreur/traefik-modsecurity-plugin.git` |
| [github.com/acouvreur/traefik-ondemand-plugin](https://github.com/acouvreur/traefik-ondemand-plugin) | `git clone git@github.com:acouvreur/traefik-ondemand-plugin.git` |
| [github.com/adyanth/traefik-container-manager](https://github.com/adyanth/traefik-container-manager) | `git clone git@github.com:adyanth/traefik-container-manager.git` |
| [github.com/agence-gaya/traefik-plugin-blockuseragent](https://github.com/agence-gaya/traefik-plugin-blockuseragent) | `git clone git@github.com:agence-gaya/traefik-plugin-blockuseragent.git` |
| [github.com/alex-held/traefik-plugin-rerouter](https://github.com/alex-held/traefik-plugin-rerouter) | `git clone git@github.com:alex-held/traefik-plugin-rerouter.git` |
| [github.com/alexandrebouthinon/traefik-kuzzle-auth](https://github.com/alexandrebouthinon/traefik-kuzzle-auth) | `git clone git@github.com:alexandrebouthinon/traefik-kuzzle-auth.git` |
| [github.com/alexandreh2ag/traefik-ipfilter-basicauth](https://github.com/alexandreh2ag/traefik-ipfilter-basicauth) | `git clone git@github.com:alexandreh2ag/traefik-ipfilter-basicauth.git` |
| [github.com/apwe/headerproxy](https://github.com/apwe/headerproxy) | `git clone git@github.com:apwe/headerproxy.git` |
| [github.com/argyle-engineering/copy-header-value-traefik-plugin](https://github.com/argyle-engineering/copy-header-value-traefik-plugin) | `git clone git@github.com:argyle-engineering/copy-header-value-traefik-plugin.git` |
| [github.com/AustinHellerRepo/TraefikOutboundLimiter](https://github.com/AustinHellerRepo/TraefikOutboundLimiter) | `git clone git@github.com:AustinHellerRepo/TraefikOutboundLimiter.git` |
| [github.com/axiaoxin/traefikplugindemo](https://github.com/axiaoxin/traefikplugindemo) | `git clone git@github.com:axiaoxin/traefikplugindemo.git` |
| [github.com/bay1ts/SiriusGeo](https://github.com/bay1ts/SiriusGeo) | `git clone git@github.com:bay1ts/SiriusGeo.git` |
| [github.com/Beanow/traefik-plugin-rawdata](https://github.com/Beanow/traefik-plugin-rawdata) | `git clone git@github.com:Beanow/traefik-plugin-rawdata.git` |
| [github.com/benoitg31/traefik-forced-body-plugin](https://github.com/benoitg31/traefik-forced-body-plugin) | `git clone git@github.com:benoitg31/traefik-forced-body-plugin.git` |
| [github.com/BetterCorp/cloudflarewarp](https://github.com/BetterCorp/cloudflarewarp) | `git clone git@github.com:BetterCorp/cloudflarewarp.git` |
| [github.com/bukukasio/super-rate](https://github.com/bukukasio/super-rate) | `git clone git@github.com:bukukasio/super-rate.git` |
| [github.com/carnage-sh/sessionmapper](https://github.com/carnage-sh/sessionmapper) | `git clone git@github.com:carnage-sh/sessionmapper.git` |
| [github.com/che-incubator/header-rewrite-traefik-plugin](https://github.com/che-incubator/header-rewrite-traefik-plugin) | `git clone git@github.com:che-incubator/header-rewrite-traefik-plugin.git` |
| [github.com/CorentinMAG/geoip](https://github.com/CorentinMAG/geoip) | `git clone git@github.com:CorentinMAG/geoip.git` |
| [github.com/dariopb/traefikServiceFabricPlugin](https://github.com/dariopb/traefikServiceFabricPlugin) | `git clone git@github.com:dariopb/traefikServiceFabricPlugin.git` |
| [github.com/dariusandz/header-transmute](https://github.com/dariusandz/header-transmute) | `git clone git@github.com:dariusandz/header-transmute.git` |
| [github.com/darkweak/souin](https://github.com/darkweak/souin) | `git clone git@github.com:darkweak/souin.git` |
| [github.com/dclairac/traefik-plugin-headers](https://github.com/dclairac/traefik-plugin-headers) | `git clone git@github.com:dclairac/traefik-plugin-headers.git` |
| [github.com/dgzlopes/traefik-fault-injection](https://github.com/dgzlopes/traefik-fault-injection) | `git clone git@github.com:dgzlopes/traefik-fault-injection.git` |
| [github.com/Dimoniq/jwtvalidator](https://github.com/Dimoniq/jwtvalidator) | `git clone git@github.com:Dimoniq/jwtvalidator.git` |
| [github.com/dimorder/dimdanredirect](https://github.com/dimorder/dimdanredirect) | `git clone git@github.com:dimorder/dimdanredirect.git` |
| [github.com/dkijkuit/azurejwttokenvalidation](https://github.com/dkijkuit/azurejwttokenvalidation) | `git clone git@github.com:dkijkuit/azurejwttokenvalidation.git` |
| [github.com/dkijkuit/checkheadersplugin](https://github.com/dkijkuit/checkheadersplugin) | `git clone git@github.com:dkijkuit/checkheadersplugin.git` |
| [github.com/domainesia/traefik-plugin-reformatheader](https://github.com/domainesia/traefik-plugin-reformatheader) | `git clone git@github.com:domainesia/traefik-plugin-reformatheader.git` |
| [github.com/dragosnutu/traefik-plugin](https://github.com/dragosnutu/traefik-plugin) | `git clone git@github.com:dragosnutu/traefik-plugin.git` |
| [github.com/EasySolutionsIO/traefikxrequeststart](https://github.com/EasySolutionsIO/traefikxrequeststart) | `git clone git@github.com:EasySolutionsIO/traefikxrequeststart.git` |
| [github.com/evolves-fr/traefik-plugin-redirect](https://github.com/evolves-fr/traefik-plugin-redirect) | `git clone git@github.com:evolves-fr/traefik-plugin-redirect.git` |
| [github.com/fdufault/mapheaders](https://github.com/fdufault/mapheaders) | `git clone git@github.com:fdufault/mapheaders.git` |
| [github.com/FinalCAD/TraefikRegionalPlugin](https://github.com/FinalCAD/TraefikRegionalPlugin) | `git clone git@github.com:FinalCAD/TraefikRegionalPlugin.git` |
| [github.com/florentinl/websitepathconverter](https://github.com/florentinl/websitepathconverter) | `git clone git@github.com:florentinl/websitepathconverter.git` |
| [github.com/galaxias/traefik-vault-auth](https://github.com/galaxias/traefik-vault-auth) | `git clone git@github.com:galaxias/traefik-vault-auth.git` |
| [github.com/GiGInnovationLabs/traefikgeoip2](https://github.com/GiGInnovationLabs/traefikgeoip2) | `git clone git@github.com:GiGInnovationLabs/traefikgeoip2.git` |
| [github.com/GiGInnovationLabs/traefikuseragent](https://github.com/GiGInnovationLabs/traefikuseragent) | `git clone git@github.com:GiGInnovationLabs/traefikuseragent.git` |
| [github.com/Hongbo-Miao/traefik-plugin-disable-graphql-introspection](https://github.com/Hongbo-Miao/traefik-plugin-disable-graphql-introspection) | `git clone git@github.com:Hongbo-Miao/traefik-plugin-disable-graphql-introspection.git` |
| [github.com/igoooor/conteo-traefik-cache](https://github.com/igoooor/conteo-traefik-cache) | `git clone git@github.com:igoooor/conteo-traefik-cache.git` |
| [github.com/irotem/jwt-rewrite](https://github.com/irotem/jwt-rewrite) | `git clone git@github.com:irotem/jwt-rewrite.git` |
| [github.com/iYUYUE/traefik-forwarded-real-ip](https://github.com/iYUYUE/traefik-forwarded-real-ip) | `git clone git@github.com:iYUYUE/traefik-forwarded-real-ip.git` |
| [github.com/jackhillman/pluginesi](https://github.com/jackhillman/pluginesi) | `git clone git@github.com:jackhillman/pluginesi.git` |
| [github.com/jerrywoo96/AddForwardedHeader](https://github.com/jerrywoo96/AddForwardedHeader) | `git clone git@github.com:jerrywoo96/AddForwardedHeader.git` |
| [github.com/jerrywoo96/AddMissingHeaders](https://github.com/jerrywoo96/AddMissingHeaders) | `git clone git@github.com:jerrywoo96/AddMissingHeaders.git` |
| [github.com/jpxd/torblock](https://github.com/jpxd/torblock) | `git clone git@github.com:jpxd/torblock.git` |
| [github.com/kevtainer/denyip](https://github.com/kevtainer/denyip) | `git clone git@github.com:kevtainer/denyip.git` |
| [github.com/kingjan1999/traefik-plugin-exception-authbasic](https://github.com/kingjan1999/traefik-plugin-exception-authbasic) | `git clone git@github.com:kingjan1999/traefik-plugin-exception-authbasic.git` |
| [github.com/kucjac/traefik-block-ua](https://github.com/kucjac/traefik-block-ua) | `git clone git@github.com:kucjac/traefik-block-ua.git` |
| [github.com/kucjac/traefik-plugin-geoblock](https://github.com/kucjac/traefik-plugin-geoblock) | `git clone git@github.com:kucjac/traefik-plugin-geoblock.git` |
| [github.com/kumina/headers-by-request](https://github.com/kumina/headers-by-request) | `git clone git@github.com:kumina/headers-by-request.git` |
| [github.com/kumina/traefik-routing-plugin](https://github.com/kumina/traefik-routing-plugin) | `git clone git@github.com:kumina/traefik-routing-plugin.git` |
| [github.com/kzmake/traefik-plugin-forward-request](https://github.com/kzmake/traefik-plugin-forward-request) | `git clone git@github.com:kzmake/traefik-plugin-forward-request.git` |
| [github.com/Lepkem/traefik-plugin-response-code-override](https://github.com/Lepkem/traefik-plugin-response-code-override) | `git clone git@github.com:Lepkem/traefik-plugin-response-code-override.git` |
| [github.com/lion7/traefik-jwt-headers-plugin](https://github.com/lion7/traefik-jwt-headers-plugin) | `git clone git@github.com:lion7/traefik-jwt-headers-plugin.git` |
| [github.com/lixianliang/traefik-plugin-return-response](https://github.com/lixianliang/traefik-plugin-return-response) | `git clone git@github.com:lixianliang/traefik-plugin-return-response.git` |
| [github.com/LyuHe-uestc/traefik-plugin-check](https://github.com/LyuHe-uestc/traefik-plugin-check) | `git clone git@github.com:LyuHe-uestc/traefik-plugin-check.git` |
| [github.com/LyuHe-uestc/traefik-plugin-token-auth](https://github.com/LyuHe-uestc/traefik-plugin-token-auth) | `git clone git@github.com:LyuHe-uestc/traefik-plugin-token-auth.git` |
| [github.com/mayankkumar2/traefik-plugin-securum-exire](https://github.com/mayankkumar2/traefik-plugin-securum-exire) | `git clone git@github.com:mayankkumar2/traefik-plugin-securum-exire.git` |
| [github.com/mrdrelar/traefik-plugin-rewriteheader](https://github.com/mrdrelar/traefik-plugin-rewriteheader) | `git clone git@github.com:mrdrelar/traefik-plugin-rewriteheader.git` |
| [github.com/muhgumus/traefik-token-middleware](https://github.com/muhgumus/traefik-token-middleware) | `git clone git@github.com:muhgumus/traefik-token-middleware.git` |
| [github.com/nese/forwardcookie](https://github.com/nese/forwardcookie) | `git clone git@github.com:nese/forwardcookie.git` |
| [github.com/nilskohrs/environmentheader](https://github.com/nilskohrs/environmentheader) | `git clone git@github.com:nilskohrs/environmentheader.git` |
| [github.com/nilskohrs/headerblock](https://github.com/nilskohrs/headerblock) | `git clone git@github.com:nilskohrs/headerblock.git` |
| [github.com/nilskohrs/pathauth](https://github.com/nilskohrs/pathauth) | `git clone git@github.com:nilskohrs/pathauth.git` |
| [github.com/nilskohrs/regex2redirect](https://github.com/nilskohrs/regex2redirect) | `git clone git@github.com:nilskohrs/regex2redirect.git` |
| [github.com/nilskohrs/reproxied](https://github.com/nilskohrs/reproxied) | `git clone git@github.com:nilskohrs/reproxied.git` |
| [github.com/nilskohrs/stripcookie](https://github.com/nilskohrs/stripcookie) | `git clone git@github.com:nilskohrs/stripcookie.git` |
| [github.com/n0m4dz/jwt-cors](https://github.com/n0m4dz/jwt-cors) | `git clone git@github.com:n0m4dz/jwt-cors.git` |
| [github.com/nscuro/traefik-plugin-geoblock](https://github.com/nscuro/traefik-plugin-geoblock) | `git clone git@github.com:nscuro/traefik-plugin-geoblock.git` |
| [github.com/packruler/rewrite-body](https://github.com/packruler/rewrite-body) | `git clone git@github.com:packruler/rewrite-body.git` |
| [github.com/packruler/traefik-themepark](https://github.com/packruler/traefik-themepark) | `git clone git@github.com:packruler/traefik-themepark.git` |
| [github.com/PascalMinder/geoblock](https://github.com/PascalMinder/geoblock) | `git clone git@github.com:PascalMinder/geoblock.git` |
| [github.com/PavloZastavnyi/headerstransformation](https://github.com/PavloZastavnyi/headerstransformation) | `git clone git@github.com:PavloZastavnyi/headerstransformation.git` |
| [github.com/Paxxs/traefik-get-real-ip](https://github.com/Paxxs/traefik-get-real-ip) | `git clone git@github.com:Paxxs/traefik-get-real-ip.git` |
| [github.com/pierre-verhaeghe/traefik-replace-response-code](https://github.com/pierre-verhaeghe/traefik-replace-response-code) | `git clone git@github.com:pierre-verhaeghe/traefik-replace-response-code.git` |
| [github.com/pipe01/plugin-requestid](https://github.com/pipe01/plugin-requestid) | `git clone git@github.com:pipe01/plugin-requestid.git` |
| [github.com/portofrotterdam/environmentheader](https://github.com/portofrotterdam/environmentheader) | `git clone git@github.com:portofrotterdam/environmentheader.git` |
| [github.com/portofrotterdam/headerblock](https://github.com/portofrotterdam/headerblock) | `git clone git@github.com:portofrotterdam/headerblock.git` |
| [github.com/portofrotterdam/pathauth](https://github.com/portofrotterdam/pathauth) | `git clone git@github.com:portofrotterdam/pathauth.git` |
| [github.com/portofrotterdam/regex2redirect](https://github.com/portofrotterdam/regex2redirect) | `git clone git@github.com:portofrotterdam/regex2redirect.git` |
| [github.com/portofrotterdam/reproxied](https://github.com/portofrotterdam/reproxied) | `git clone git@github.com:portofrotterdam/reproxied.git` |
| [github.com/portofrotterdam/stripcookie](https://github.com/portofrotterdam/stripcookie) | `git clone git@github.com:portofrotterdam/stripcookie.git` |
| [github.com/pvalletbo/traefik-blocklist](https://github.com/pvalletbo/traefik-blocklist) | `git clone git@github.com:pvalletbo/traefik-blocklist.git` |
| [github.com/pvalletbo/traefik-forwarded-real-ip](https://github.com/pvalletbo/traefik-forwarded-real-ip) | `git clone git@github.com:pvalletbo/traefik-forwarded-real-ip.git` |
| [github.com/qxsugar/request-dispatch](https://github.com/qxsugar/request-dispatch) | `git clone git@github.com:qxsugar/request-dispatch.git` |
| [github.com/qxsugar/request-mark](https://github.com/qxsugar/request-mark) | `git clone git@github.com:qxsugar/request-mark.git` |
| [github.com/Rajabalian/ipclient](https://github.com/Rajabalian/ipclient) | `git clone git@github.com:Rajabalian/ipclient.git` |
| [github.com/rocdove/replacepathfromurlregex](https://github.com/rocdove/replacepathfromurlregex) | `git clone git@github.com:rocdove/replacepathfromurlregex.git` |
| [github.com/romracer/traefik-get-real-ip](https://github.com/romracer/traefik-get-real-ip) | `git clone git@github.com:romracer/traefik-get-real-ip.git` |
| [github.com/Russia9/body-size-limit](https://github.com/Russia9/body-size-limit) | `git clone git@github.com:Russia9/body-size-limit.git` |
| [github.com/scrazy77/plugin-simplecache-nocache](https://github.com/scrazy77/plugin-simplecache-nocache) | `git clone git@github.com:scrazy77/plugin-simplecache-nocache.git` |
| [github.com/snapt/traefik-nova-plugin](https://github.com/snapt/traefik-nova-plugin) | `git clone git@github.com:snapt/traefik-nova-plugin.git` |
| [github.com/soulbalz/correlationid](https://github.com/soulbalz/correlationid) | `git clone git@github.com:soulbalz/correlationid.git` |
| [github.com/soulbalz/traefik-check-body](https://github.com/soulbalz/traefik-check-body) | `git clone git@github.com:soulbalz/traefik-check-body.git` |
| [github.com/soulbalz/traefik-real-ip](https://github.com/soulbalz/traefik-real-ip) | `git clone git@github.com:soulbalz/traefik-real-ip.git` |
| [github.com/s00rk/firebase-verify-token](https://github.com/s00rk/firebase-verify-token) | `git clone git@github.com:s00rk/firebase-verify-token.git` |
| [github.com/sunalwaysknows/redirect2https](https://github.com/sunalwaysknows/redirect2https) | `git clone git@github.com:sunalwaysknows/redirect2https.git` |
| [github.com/suteqa/plugin_record](https://github.com/suteqa/plugin_record) | `git clone git@github.com:suteqa/plugin_record.git` |
| [github.com/team-carepay/traefik-jwt-plugin](https://github.com/team-carepay/traefik-jwt-plugin) | `git clone git@github.com:team-carepay/traefik-jwt-plugin.git` |
| [github.com/team-carepay/traefik-opa-plugin](https://github.com/team-carepay/traefik-opa-plugin) | `git clone git@github.com:team-carepay/traefik-opa-plugin.git` |
| [github.com/tnt-sbab/jwt-verifier](https://github.com/tnt-sbab/jwt-verifier) | `git clone git@github.com:tnt-sbab/jwt-verifier.git` |
| [github.com/tnt-sbab/token-translator](https://github.com/tnt-sbab/token-translator) | `git clone git@github.com:tnt-sbab/token-translator.git` |
| [github.com/togettoyou/traefik-timer-plugin](https://github.com/togettoyou/traefik-timer-plugin) | `git clone git@github.com:togettoyou/traefik-timer-plugin.git` |
| [github.com/tomMoulard/fail2ban](https://github.com/tomMoulard/fail2ban) | `git clone git@github.com:tomMoulard/fail2ban.git` |
| [github.com/tomMoulard/htransformation](https://github.com/tomMoulard/htransformation) | `git clone git@github.com:tomMoulard/htransformation.git` |
| [github.com/traefik/plugin-blockpath](https://github.com/traefik/plugin-blockpath) | `git clone git@github.com:traefik/plugin-blockpath.git` |
| [github.com/traefik/plugin-log4shell](https://github.com/traefik/plugin-log4shell) | `git clone git@github.com:traefik/plugin-log4shell.git` |
| [github.com/traefik/plugin-rewritebody](https://github.com/traefik/plugin-rewritebody) | `git clone git@github.com:traefik/plugin-rewritebody.git` |
| [github.com/traefik/plugin-simplecache](https://github.com/traefik/plugin-simplecache) | `git clone git@github.com:traefik/plugin-simplecache.git` |
| [github.com/traefik/plugindemo](https://github.com/traefik/plugindemo) | `git clone git@github.com:traefik/plugindemo.git` |
| [github.com/traefik/pluginproviderdemo](https://github.com/traefik/pluginproviderdemo) | `git clone git@github.com:traefik/pluginproviderdemo.git` |
| [github.com/trinnylondon/lowercase](https://github.com/trinnylondon/lowercase) | `git clone git@github.com:trinnylondon/lowercase.git` |
| [github.com/trinnylondon/redirector](https://github.com/trinnylondon/redirector) | `git clone git@github.com:trinnylondon/redirector.git` |
| [github.com/trinnylondon/traefik-add-trace-id](https://github.com/trinnylondon/traefik-add-trace-id) | `git clone git@github.com:trinnylondon/traefik-add-trace-id.git` |
| [github.com/Uscreen-video/traefik-plugin-rewritehost](https://github.com/Uscreen-video/traefik-plugin-rewritehost) | `git clone git@github.com:Uscreen-video/traefik-plugin-rewritehost.git` |
| [github.com/vaspapadopoulos/traefik-cookie-handler-plugin](https://github.com/vaspapadopoulos/traefik-cookie-handler-plugin) | `git clone git@github.com:vaspapadopoulos/traefik-cookie-handler-plugin.git` |
| [github.com/vidosits/header-pattern-proxy](https://github.com/vidosits/header-pattern-proxy) | `git clone git@github.com:vidosits/header-pattern-proxy.git` |
| [github.com/vincentinttsh/cloudflareip](https://github.com/vincentinttsh/cloudflareip) | `git clone git@github.com:vincentinttsh/cloudflareip.git` |
| [github.com/vincentinttsh/rewriteheaders](https://github.com/vincentinttsh/rewriteheaders) | `git clone git@github.com:vincentinttsh/rewriteheaders.git` |
| [github.com/virtualzone/rewriteheaders](https://github.com/virtualzone/rewriteheaders) | `git clone git@github.com:virtualzone/rewriteheaders.git` |
| [github.com/vtacquet/redbase-plugin](https://github.com/vtacquet/redbase-plugin) | `git clone git@github.com:vtacquet/redbase-plugin.git` |
| [github.com/wiltonsr/ldapAuth](https://github.com/wiltonsr/ldapAuth) | `git clone git@github.com:wiltonsr/ldapAuth.git` |
| [github.com/worldline-go/traefik-plugin-hello](https://github.com/worldline-go/traefik-plugin-hello) | `git clone git@github.com:worldline-go/traefik-plugin-hello.git` |
| [github.com/XciD/traefik-plugin-rewrite-headers](https://github.com/XciD/traefik-plugin-rewrite-headers) | `git clone git@github.com:XciD/traefik-plugin-rewrite-headers.git` |
| [github.com/0xDagal/charon-passto](https://github.com/0xDagal/charon-passto) | `git clone git@github.com:0xDagal/charon-passto.git` |
| [github.com/ytyuanxi/userinfo](https://github.com/ytyuanxi/userinfo) | `git clone git@github.com:ytyuanxi/userinfo.git` |
| [github.com/ZeroGachis/traefik-auth-middleware](https://github.com/ZeroGachis/traefik-auth-middleware) | `git clone git@github.com:ZeroGachis/traefik-auth-middleware.git` |
| [github.com/ZeroGachis/traefik-magic-jwt](https://github.com/ZeroGachis/traefik-magic-jwt) | `git clone git@github.com:ZeroGachis/traefik-magic-jwt.git` |



</details>

**Comment by alexdelprete** [comment]
> If this can help, the list of plugins:

I got the git clone line from the plugin repository, but the list is helpful for unexperienced people.

Good that the hub active config is not stopping the service.

**Comment by ldez** [comment]
> maybe Traefik could automatically cache a local copy of the plugin

Traefik works with a local copy but we have to be sure about the plugin integrity is right.
Traefik calls a service to check the integrity, if there is an integrity problem (or something else) the plugin is removed and Traefik will download again the plugin.

**Comment by alexdelprete** [comment]
> Traefik works with a local copy but we have to be sure about the plugin integrity is right.

If the plugin is run at least once, you are sure the integrity was checked positively. You can do a local check for local corruption eventually, storing a hash of the local plugin. If at the next run the local hash is correct, you can start the local copy of the plugin even if the remote plugin service is down.

**Comment by ldez** [comment]
Having a local hash and local check is not secure because both can be corrupted.

I already think about that when I created the plugin system.

**Comment by alexdelprete** [comment]
I understand what you mean, but it's always better than not starting the service because a remote site is not available.

> If you put a lock and the key in the same place you don't have a lock

So local DBs wouldn't exist. Data can be corrupted...always. YAML files can be corrupted, but Traefik relies on those to start. How do you check the integrity of those? :)

Syncing/mirroring techniques exist, it's just a matter of finding the appropriate solution, there's always a second-best solution, a compromise that's good enough.

**Comment by ldez** [comment]
The plugin services are restored.
The hem chart is restored.

The other services will come back quickly.

Sorry for the service interruption.

**Comment by alexdelprete** [comment]
Thanks a lot Ludovic.

**Comment by ldez** [comment]
All services are up now.

Sorry for the service interruption.
