### ISSUE TITLE
Integrationtest on master failing because of ConsulCatalogSuite

### ISSUE THREAD

**Issue by jandillenkofer** [traefik/traefik#9280]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I ran the integration tests with `make test-integration` with commit `626da4c0aee8f6ff9f3f5264a5e8133a4ce12584`.

### What did you see instead?

The integrationtests failed:

FAIL: consul_catalog_test.go:237: ConsulCatalogSuite.TestSimpleConfigurationWithWatch

consul_catalog_test.go:305:
    c.Assert(err, checker.IsNil)
... value *fmt.wrapError = &fmt.wrapError{msg:"try operation failed: got status code 200, wanted 404", err:(*errors.errorString)(0xc0007cfd80)} ("try operation failed: got status code 200, wanted 404")

### What version of Traefik are you using?

v2.8.3

### What is your environment & configuration?

I did no configuration changes to commit `626da4c0aee8f6ff9f3f5264a5e8133a4ce12584` at all.
Everything is set to the default.

```
Client: Docker Engine - Community
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:54:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ldez** [comment]
Hello,

our CI runs the integration tests on all commits and PRs and there is no problem.

The integration tests are slow and in some environments, you have to use `CI=1`.

```
C=1 make test-integration
```
