### ISSUE TITLE
docker: wait to remove router

### ISSUE THREAD

**Issue by Foxite** [traefik/traefik#9289]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

When updating or recreating a container, traefik will remove the associated router and then add it again. During this process, clients will receive a 404 error. It would make more sense to return a 503 error in this situation.

Furthermore, in some situations, the update is so fast that it is done before Traefik has even removed the associated router. You can see this when recreating a container with an image such as traefik/whoami, and using a command such as `watch -n 0.2 curl <host>`. In my experiments, I recreate the container using docker-compose, and I can see the hostname change to the new container's hostname before traefik removes the router and recreates it a few seconds later. There is no reason to remove the router.

My proposal to fix this, is to make the Docker provider wait a few moments, before removing a router after seeing a container get removed. If the container gets created again before the timeout expires, the router will not be removed. Of course, this should be optional, and the delay should also be configurable. When a request comes in for a router that has no running services, the response should be http 503.

This will probably be applicable to most other providers, not just Docker. I wouldn't be able to test my implementation against any of those, however.

If you think this is a good idea I'll probably work on it soon ish, hopefully. No promises :P

**Comment by ldez** [comment]
Hello,

A simplified workflow of the Traefik configuration:
- detect changes
- create new routes
- when the routing is ready, switch the routing in memory

The switch of the routing is done in memory, which means that is immediately applied.

If you have many short-time changes, you can increase `providersThrottleDuration`. 

https://doc.traefik.io/traefik/providers/overview/#providersprovidersthrottleduration

```yml
providers:
  providersThrottleDuration: 42s
```

**Comment by Foxite** [comment]
Thanks for the reply. I've tried it, but it doesn't seem to do what I need.

It appears that setting providersThrottleDuration causes the first update to immediately be applied, and any updates that come in during the specified time span after that update, will be clumped together.

This tends to make my problem worse, because the router gets immediately removed, and then there is a delay in adding it again. I noticed that providersThrottleDuration has a default value of two seconds. I set it to zero, and the problem was *mostly* solved (in testing, see note below), but it still shows a 404 error which is not what I would like.

What would be ideal, is that services are removed and created immediately, while routers are not removed until some time after their last service was removed. This would cause users to see a 503 error while the update is in progress, and this state doesn't last any longer than it needs to.

Note: This may be an entirely different problem, but my production deployment of Traefik (where I have about 20 routers, as opposed to the single one I have in testing) has a much longer delay in re-adding routers (as much as 31 seconds, whereas in testing it takes less than half a second) even though I don't specify providersThrottleDuration. I'll need to investigate that separately.

**Comment by rtribotte** [comment]
Hello @Foxite,

> What would be ideal, is that services are removed and created immediately, while routers are not removed until some time after their last service was removed. This would cause users to see a 503 error while the update is in progress, and this state doesn't last any longer than it needs to.

Unfortunately, this is not how Traefik works, because it is stateless, every router, middleware, and service is rebuilt every time the configuration has changed, which also means that the configuration is a whole, and there is no separate configuration for routers and services.
Another important point is that the configuration requires to be consistent before applying it, for instance, a router cannot point to an unknown service.

Regarding the 404 responses, if you want to make Traefik to reply 503 instead when a router is missing, please take a look at [this guide](https://doc.traefik.io/traefik/getting-started/faq/#xxx-instead-of-404) in our documentation.
