### ISSUE TITLE
Expose destination router name to ForwardAuth middleware 

### ISSUE THREAD

**Issue by MarvinJWendt** [traefik/traefik#9303]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi, we are currently building a ForwardAuth middleware to authenticate users.

We want to restrict the access to routers per user (and or user groups). Currently, we cannot get the destination router in the ForwardAuth middleware.

![diagram](https://user-images.githubusercontent.com/31022056/188290440-7c621a53-f7f1-4f2a-a72d-079e22e498da.png)

Let's say the user wants to connect to D here. Our middleware (FA) would need to know that the user tries to visit D. The current request headers only show the current `Host` (which is the domain of FA). As it seems, we have no information about D inside of FA.

The proposal now, would be that Traefik (RP) could add information about D to the header send to FA. The header could contain the router name (e.g.: `web-server@docker`)  of D to make D identifiable to FA. This would allow ForwardAuth middlewares, to decide if the user has access to a specific router.

Since the router name is probably unsecure to expose (even if it's just between RP and FA), a flag could be added to enable this behavior, similar to the `trustForwardHeader` flag. `trustForwardRouterName` would be my first thought.

EDIT: The container ID would also be quite useful to know. With that, we could add labels to our containers to specify which groups have access to it.

Feedback is very welcome, and if there is a way, that we couldn't find, to get information about D, please let us know!
Thanks in advance.

**Comment by ldez** [comment]
Hello,

You have the real Host inside the `X-Forwarded-Host` header.

https://doc.traefik.io/traefik/middlewares/http/forwardauth/#forward-request-headers

**Comment by MarvinJWendt** [comment]
Hi @ldez, thanks for the quick response! I am aware of the forwarded headers, but in my opinion they are not enough to easily identify the container / router. Multiple routers can rely on the same hostname, if used with `Path` rule, for example. Even with the forwarded `Host` and `URI`, there could still be a `Headers` rule in use, which directs the traffic to `hostname.local/some/path` to different routers, depending on the `Headers`. Then there are also query parameters etc. that can change the used router.

To get a container id / router name with this information, it would at least require access to the docker socket and then parsing the Traefik rules for every container to find a match. This step would be very inefficient, as Traefik did the rule matching already. Also, parsing the rules yourself would be quite error-prone.

**Comment by ldez** [comment]
From memory, in the `X-Forwarded-Uri`  you have the path and query parameters.

If you want to also send specific headers you can use `authrequestheaders`.

https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authrequestheaders

**Comment by MarvinJWendt** [comment]
I don't want to send specific headers. But maybe the client is doing so, and the router has a `Headers` rule.

![image](https://user-images.githubusercontent.com/31022056/188315127-49abb227-26ec-49bb-957c-40528396d08a.png)

As an example:

| Host | URI | Rules | Headers | Router Name|
|------|------|-------|----------|----------------|
|`hostname.local` | `/hello/world` | `Host(hostname.local) && Path(hello/world) && Headers(SomeUserDefinedHeader1)` | `SomeUserDefinedHeader1=asd` | router1|
|`hostname.local` | `/hello/world` | `Host(hostname.local) && Path(hello/world) && Headers(SomeUserDefinedHeader2)` | `SomeUserDefinedHeader2=asd2` | router2|
|`hostname.local` | `/hello/world` | `Host(hostname.local) && Path(hello/world) && Headers(SomeUserDefinedHeader3)` | `SomeUserDefinedHeader3=asd3` | router3|

As you can see, the forwarded `Host` and `Uri` are the same, but the responding router is different.

We have access to this information, but we would have to replicate the Traefik routing algorithm exactly to identify the responding container / router.

If multiple router rules match, Traefik supports priorities. Those are also not exposed to FA. In the case that multiple router rules match, FA could not identify a router / container, but Traefik could.

A rule like `PathPrefix("/")` would match every router, if not overwritten by another rule with a higher priority.

**Comment by ldez** [comment]
> As you can see, the forwarded Host and Uri are the same, but the responding router is different.

Yes but the rules are not the same because of the headers.

> If multiple router rules match, Traefik supports priorities.

As you know priorities, you also know that priorities are not conditional, so you will never have several of those identical routers that work at the same time.

Is your concrete use case based on this? Can you explain it?

I think (I hope) it's a edge case even in your infrastructure and this pattern is used only on a few testing routes.
If it's the case, you can set a [`headers` middleware](https://doc.traefik.io/traefik/middlewares/http/headers/) on those routers to add a specific header and forward this header by using the [`authrequestheaders` option](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authrequestheaders) of the `forwardauth` middleware.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
