### ISSUE TITLE
Feature: Support AllNamespacesNamespace when using the Nomad Provider

### ISSUE THREAD

**Issue by 0teh** [traefik/traefik#9307]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Using the AllNamespacesNamespace as the nomad provider namespace (traefik CLI option `--providers.nomad.namespace=*`) results in no services being found.

In my particular usecase, I have multiple workloads running across multiple namespaces, and would like to provide a single entrypoint for them all.  I think this would also help match user expectations when comparing the traefik configuration with querying nomad directly (`nomad service list -namespace=*`).

I am filing this as a feature request instead of a bug report because I think there are some design considerations: if nomad has two services with the same name but in different namespaces, with this feature, traefik would see one service with two servers (based on experiments with local changes to traefik).  This is fine for my own usecase but might not be for others.

I am willing to prepare a PR, especially if the design considerations above can be disregarded for now.

Thanks!

**Comment by rtribotte** [comment]
Hello @0teh,

Thanks for your interest in Traefik!

From the nomad documentation, it seems that there is no `*` value that would allow matching any namespace.
Considering that, and if we didn’t miss something, the Nomad provider only lack of the support of multiple namespaces, like Consul and ConsulCatalog providers do (https://github.com/traefik/traefik/issues/8896). WDYT?

**Comment by 0teh** [comment]
Hello,

The nomad documentation is quite sparse, but the `*` namespace can be found on the page for [`nomad service list`](https://www.nomadproject.io/docs/commands/service/list) as well as in the sample requests for the [equivalent HTTP request](https://www.nomadproject.io/api-docs/services#sample-request).  This works for listing nomad services, but fetching the details of a specific service require the exact namespace, which is part of the list results.

Supporting a namespaces array like consul would be very nice, and seems to me like an additional feature alongside `*`.  I think it makes sense that the namespace is then appended to the traefik service name.

**Comment by rtribotte** [comment]
Thanks for your feedback!

You are right. I overlooked that the `*` namespace is available for the `nomad service list` endpoint.

And we have indeed a limitation induced by how the namespace option is used right now. It is configured on the client and then used globally, so the `*` namespace cannot be used because it would then be used to read the service details.

We think that supporting the `*` namespace is a valid proposal.
We are wondering about the design, if you already thought about it, would you mind describing the approach before opening the PR?

**Comment by 0teh** [comment]
Sure, the initial change would be to [`fetchService`](https://github.com/traefik/traefik/blob/703de5331ba4d0b494fa36061c12a01e13db9dc0/pkg/provider/nomad/nomad.go#L277) with the `stub.Namespace` from the caller passed to the `QueryOptions`. 

Surfacing the namespace in the name is a bit trickier though, after looking a bit more into it, the approach taken by the consul provider depends on a static set of namespaces, but with `*`, it could change at runtime.  If multiple providers are built off of `getNomadServiceData` inside of `loadConfiguration`, then I don't see how a provider can be removed.

If instead only one provider is created, then it could prepend namespaces to the service name, similar to the [k8s provider](https://github.com/traefik/traefik/blob/703de5331ba4d0b494fa36061c12a01e13db9dc0/pkg/provider/kubernetes/ingress/kubernetes.go#L304) (if I'm understanding that correctly).  This would occur in [`getName`](https://github.com/traefik/traefik/blob/703de5331ba4d0b494fa36061c12a01e13db9dc0/pkg/provider/nomad/config.go#L272) and could also be conditional based on whether the namespace is `*` or not (as in, non `*` namespaces do not need to prepend anything)

**Comment by rtribotte** [comment]
Hello @0teh,

Thanks a lot for your feedback!

> Sure, the initial change would be to [fetchService](https://github.com/traefik/traefik/blob/703de5331ba4d0b494fa36061c12a01e13db9dc0/pkg/provider/nomad/nomad.go#L277) with the stub.Namespace from the caller passed to the QueryOptions.

Indeed, it's seems to be the best approach.

> Surfacing the namespace in the name is a bit trickier though, after looking a bit more into it, the approach taken by the consul provider depends on a static set of namespaces, but with *, it could change at runtime. If multiple providers are built off of getNomadServiceData inside of loadConfiguration, then I don't see how a provider can be removed.

We think that only a single nomad provider instance should be used to leverage the `*` value for the namespace. Today, for Consul, the instances are created on startup based on the static configuration. We are not willing to make provider instances dynamically.
So surfacing the namespace in the name should be achievable with a single provider.

> If instead only one provider is created, then it could prepend namespaces to the service name, similar to the [k8s provider](https://github.com/traefik/traefik/blob/703de5331ba4d0b494fa36061c12a01e13db9dc0/pkg/provider/kubernetes/ingress/kubernetes.go#L304) (if I'm understanding that correctly). This would occur in [getName](https://github.com/traefik/traefik/blob/703de5331ba4d0b494fa36061c12a01e13db9dc0/pkg/provider/nomad/config.go#L272) and could also be conditional based on whether the namespace is * or not (as in, non * namespaces do not need to prepend anything)

Not sure to have fully caught the explanation here, thus prepending the namespace conditionally is the way to go. 
If we not missed something, as well as when looking for the service details using the namespace from the stub of the `list services` endpoint, the resource naming should be done reusing the namespace from the stub of the `service details` endpoint.

> I am willing to prepare a PR, especially if the design considerations above can be disregarded for now.

Are you still willing to prepare a PR? If so, we will gladly welcome your contribution.

**Comment by 0teh** [comment]
Sorry for not being clear, but I think we agree: one provider, prepend the actual namespace if `*` is the `service list` namespace.

Yes, I'm still willing to create a PR, I'll link to this issue when it's ready

**Comment by rtribotte** [comment]
Hello @0teh,

Thanks for your feedback, and sure we would gladly welcome a contribution of yours to support multiple namespaces with the Nomad provider (in the same fashion as the Consul and Consul Catalog ones).
