### ISSUE TITLE
On demand docker customization based on templates.

### ISSUE THREAD

**Issue by ZappaBoy** [traefik/traefik#9308]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Regarding the use of Traefik via docker, I noticed that it is necessary to make a number of customizations to the `docker-compose.yaml` files.  In order to avoid modifying the files and thus "dirtying" the repositories I thought of creating a tool for on-demand `docker-compose.yaml` customization. 
The tool uses templates that can be customized based on the type of docker you are using. The tool was created to simplify the simplest operations and probably won't work for all occasions but it might be an idea and I thought I would share it.
Anyway, in case anyone is interested the tool is open-source and it's called [traefik-warden](https://github.com/Just-Another-Organization/traefik-warden).

I hope this idea can be useful.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by mpl** [comment]
@ZappaBoy FYI, there's a typo in the "about" section of your project (s/Warder/Warden/).

**Comment by ZappaBoy** [comment]
> @ZappaBoy FYI, there's a typo in the "about" section of your project (s/Warder/Warden/).
My bad, I renamed the repository twice. Thanks for the suggestion. 👍🏼
