### ISSUE TITLE
Cipher Suites

### ISSUE THREAD

**Issue by nidhin077** [traefik/traefik#9311]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I attempted to add the Cipher Suites using your guidelines. But still, the traefik is using default Cipher Suites.  In my domains, this might lead to a security problem.

64-bit block cipher 3DES vulnerable to SWEET32 attack
Forward Secrecy not supported by any cipher

### What did you see instead?

No response

### What version of Traefik are you using?

2.3

### What is your environment & configuration?

[global]
  sendAnonymousUsage = false

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
[entryPoints.http]
   address = ":80"
   [entryPoints.http.http.redirections.entryPoint]
     to = "https"
     scheme = "https"
   [entryPoints.http.forwardedHeaders]
     insecure = true

[entryPoints.https]
   address = ":443"
   [entryPoints.https.forwardedHeaders]
     insecure = true

[tls.options]
    preferServerCipherSuites = true
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"

    ]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
  [providers.file]
    filename = "/rules.toml"

[log]
  level = "DEBUG"
  filePath = "/var/log/traefik/service.log"

[accessLog]
  bufferingSize = 100
  filePath = "/var/log/traefik/access.log"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = ""
      storage = "acme.json"
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "http"

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
