### ISSUE TITLE
file transfers larger than 2GB break application completely with Traefik

### ISSUE THREAD

**Issue by codeagencybe** [traefik/traefik#9319]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm hosting an application that takes backup files from a web ui to restore data. 
Any backup file >2GB does not work and result in error entity too large. 

I have looked into the configuration and configured Traefik 2.7 with these 4 params:
traefik.http.middlewares.limit.buffering.maxRequestBodyBytes
traefik.http.middlewares.limit.buffering.maxResponseBodyBytes
traefik.http.middlewares.limit.buffering.memRequestBodyBytes
traefik.http.middlewares.limit.buffering.memResponseBodyBytes

Value is set to 2000000000 which resemble the 2GB limit. But as soon as I put 2000000001 or 5000000000 or whatever value that is higher, then Traefik is killing the application completely. 

When I change to NGINX or Caddy as reverse proxy, I don't have this problem. Their config just accept the limit I'm giving it. 

Is there something hard coded in Traefik that doesn't allow to go higher? 

### What did you see instead?

Completely broken application, nothing works if I set the params value higher than the current value. 

### What version of Traefik are you using?

We see this problem in multiple versions ranging from 2.5 up to 2.8

### What is your environment & configuration?

```yaml
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=2000000000"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=2000000000"
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=2000000000"
      - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=2000000000"
      - "traefik.http.routers.${ENV}-odoo-im.middlewares=gzip,sslheader,limit"

```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

Can you provide the logs?
Can you provide information about your environment? (OS, etc.)

There are no hardcoded limits inside Traefik.

**Comment by ldez** [comment]
I will answer your forum post: https://community.traefik.io/t/upload-size-2gb/15707
So I close this issue for now.
