### ISSUE TITLE
Bug: Certificate resolvers silent fail on on unexpected acme.json "the router uses a non-existent resolver

### ISSUE THREAD

**Issue by flaviut** [traefik/traefik#9325]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Deployed traefik 2.3 via the official docker image. Configured the location of acme.json in an docker overlay2 volume. This issue can happen in two ways, but basically just modify acme.json in any way, have an already existing acme.json, incorrect permissions for acme.json. Pretty much anything that traefik may not expect with the acme.json file.

### What did you expect to see?

On debug logging, an error such as incorrect file permissions 600. Or acme.json already exists.

### What did you see instead?

The certificate resolver will silent fail (on debug logging). Each router using that certresolver will fail with the router uses a non-existent resolver.

### What version of Traefik are you using?

```
Version:      2.3.1
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
--certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
```

Some others with the same issue:
https://community.traefik.io/t/a-solution-to-the-incredibly-unhelpful-the-router-uses-a-non-existent-resolver-letsencrypt-message/3859
https://community.traefik.io/t/non-existent-resolver-using-letsencrypt/3530

**Comment by flaviut** [comment]
This is a duplicate of https://github.com/traefik/traefik/issues/7414, which was closed by a robot.

Unfortunately, having a robot close issues every few months does not fix them. It instead just frustrates users and increases triage workload for you.

---

In my particular case, Traefik will end up with a zero-byte `acme.json` file for no particular reason occasionally.

**Comment by ldez** [comment]
Hello,

> Unfortunately, having a robot close issues every few months does not fix them.

The issue was closed because it was a question, not a bug. The bugs are never closed after 30 days.

---

Either the name of your resolver is not good or you have another error (in your logs) that blocks the creation of the resolver.

---

I recommend updating your Traefik, we only maintain the latest minor version (currently v2.8).
https://github.com/traefik/traefik#release-cycle

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
