### ISSUE TITLE
Traefik v1.7 to v2.5 Kubernetes Ingress field not found, node: entryPoint

### ISSUE THREAD

**Issue by tee** [traefik/traefik#9347]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am currently working to upgrade our current Traefik 1.7 infra to Traefik 2.5 to support K8 1.22. I switched the docker image being pulled from an internal 1.7 image, to the following image url: `docker.io/traefik:2.5`.

This _looks_ to be a similar configuration to https://github.com/traefik/traefik/blob/31a5f3591f278aeeccaee9de530c109c14544ab8/integration/fixtures/k8s_ingressclass.toml

Based on the documentation, i've updated the following:
version 1.7
```
[kubernetes]
ingressClass = "data-service-fabric"
```

to
version 2.5
```
[providers.kubernetesIngress]
ingressClass = "data-service-fabric"
```

### What did you see instead?

command traefik error: field not found, node: entryPoint

### What version of Traefik are you using?

v2.5

### What is your environment & configuration?

`kubectl describe` output:
```
  traefik:
    Container ID:  docker://a97209ffa5662b8a90034babfc7336cd820165ce18feda88c4979bbbbceb3e62
    Image:         docker.io/traefik:2.5
    Image ID:      docker-pullable://traefik@sha256:7d5a6ae66572b27afe1059ce893b59acb28de70f4ce298385e153d0a398ce7f8
    Ports:         12000/TCP, 13000/TCP, 15000/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      -l
      DEBUG
      --configfile=/config/dsf-router-backend-traefik/traefik.toml
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   2022/09/18 21:45:51 command traefik error: field not found, node: entryPoint
```

My TOML file is as follows: 
```
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":12000"

  [entryPoints.api]
  address = ":13000"

  [entryPoints.ping]
  address = ":14000"

  [entryPoints.metrics]
  address = ":15000"

[file]
directory = "/config/dynamic"
watch = true

[providers.kubernetesIngress]
ingressClass = "data-service-fabric"

[ping]
entryPoint = "ping"

[api]
entryPoint = "api"

[metrics]
  [metrics.prometheus]
  entryPoint = "metrics"
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by ldez** [comment]
https://community.traefik.io/t/1-7-to-2-5-field-not-found-node-entrypoint/15777/2
