### ISSUE TITLE
RC Docker Image is tagged as non-RC version (v2.9 == v2.9.0-rc3)

### ISSUE THREAD

**Issue by Michuelnik** [traefik/traefik#9353]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

My automatic update scanner reported a new release of the traefik docker image `:v2.9` but currently this turns out to be just a release candidate `:v2.9.0-rc3`. (This has been the case for past rc releases, too.)
I would expect that there is no v2.9 docker image yet.

Are there a special reasons there is a public docker image with a release tag that's actually not a release?

On github there is no v2.9 tag as of now.

### What did you see instead?

A docker image tag `:v2.9` while expecting none until v2.9 has been released properly.

### What version of Traefik are you using?

```
Version:      2.8.5
Codename:     vacherin
Go version:   go1.19.1
Built:        2022-09-13T15:19:09Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

not applicable since this report relates to the software release cycle.

**Comment by ldez** [comment]
Hello,

we always created the short tag version (ex: `v2.9`) on the Docker image.

The short tag version is a kind of group that allows people that want to follow the RC phase to don't have to update their image.

It's not a real version as it doesn't follow semver.

Your update scanner makes an erroneous assumption: the short tag version is not a real version.

**Comment by Michuelnik** [comment]
Thank you for clarification. @ldez 
I can work around this, just wanted to point out there might be something a bit off.
