### ISSUE TITLE
Proposal: serverless (lambda) services

### ISSUE THREAD

**Issue by alekitto** [traefik/traefik#9359]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

My proposal is to use Traefik to route requests to serverless platforms (AWS lambda/GCP cloud functions/others).

### Why?

Some of my customers have applications deployed on AWS lambda, using Traefik to directly route requests I can skip the additional layer of AWS load balancer/API Gateway/Function URL, saving costs and request time.  
Ideally treafik can call the platform service directly with a defined request format or mimicking the platform's load balancer format, return the correct response to the client and using traefik middlewares for header manipulation/retry rules/path manipulation/compression/...

### How?

I've already implemented a solution for this problem in my own fork (https://github.com/alekitto/traefik) that is being battle-tested and used in production in this moment: since round robin, weighted, mirroring and failover service types are not applicable to this problem, since there is no server to call, I added a new service type called `serverless` supporting AWS lambda only with `AWSLambdaFunctionArn` configuration parameter (+ params for AWS authentication).

When configured, the service will re-create the event structure of the AWS application load balancer and invokes the lambda waiting for a response. When a response is received and no error has been raised, the response body and header are decoded and sent to the client.

If needed, I can extract the code for this proposal from my fork and send a draft PR to discuss the limitations of the current implementation and work on them,

**Comment by mpl** [comment]
Hi @alekitto , 

No need for the code in a PR right now (unless you really think it's necessary to demonstrate your ideas), and we do not advise you to spend more effort on it atm as we can't guarantee to follow-up fast on it, but we sure would be interested in your analysis on the limitations you already found.

thanks.

**Comment by alekitto** [comment]
Hi @mpl,
I’m using it on multiple projects in production since 1y now and in general it works pretty well. Routing, request encoding and response decoding (json + eventual base64) are fast, so it is a good candidate to replace the provider’s own load balancer.

The limitations I’ve found in my solution are the following:

- There is no autodiscovery: I can’t really figure out how to do it, so I’m currently using the file/directory providers
- A retry middleware should be always used: sometimes (very rare TBH) AWS apis just fail. At least one retry should be strongly advised.
- There’s no check on the request body size, which can be limited by the cloud provider.
- The invoker cannot be used in middlewares/plugins: the implementation could be more generic to allow usage from the ForwardAuth middleware (for example)
- The request format cannot be changed: since I had to support AWS lambda only, I’ve implemented only the ALB request format
- The configuration is AWS-centric: same as above, I didn’t think a configuration format flexible enough to be easily expanded


IMHO the only BIG thing is the autodiscovery point, cause the others can be easily resolved.

> we can't guarantee to follow-up fast on it

Sure, I see, but there’s really no hurry: as I said I’m using it in production with my fork since 1 year, I can continue to rebase it a little bit more 🙂

But IF there’s interest in this feature I’ll be glad to take part on the discussion

**Comment by tfny** [comment]
Just a note so we don't lose it as we go, this is part of the Hackaethon.

**Comment by omri-shilton** [comment]
any update on this? we would want to use it in our platform as well

**Comment by emilevauge** [comment]
Hello,
Thanks for your proposal, however, due to the lack of traction, we made the decision to not add this feature into Traefik.
Thanks again for contributing ❤️
