### ISSUE TITLE
Improve docs about auth@file in EntryPoints HTTP Middlewares

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9374]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Just playing around with NextCloud and docker-compose and it needs some HSTS headers to be set. When also using those on NextCloud Office I need to create them twice. So I thought it would make sense to define them once in the static configuration and just assign them to each router in the dynamic configuration via labels.

[EntryPoints supports HTTP Middlewares](https://doc.traefik.io/traefik/routing/entrypoints/#middlewares), but the example is unclear to me: 
```
--entrypoints.websecure.http.middlewares=auth@file,strip@file
```
What is auth@file? It's nowhere defined nor explained.

Can I create Middlewares inline in a static configuration via CLI?
```
  - 'http.middlewares.hsts-header.headers.referrerPolicy=no-referrer'
  - 'http.middlewares.hsts-header.headers.stsSeconds=15552000'
  - 'http.middlewares.hsts-header.headers.forceSTSHeader=true'
  - 'http.middlewares.hsts-header.headers.stsPreload=true'
  - 'http.middlewares.hsts-header.headers.stsIncludeSubdomains=true'
  - 'http.middlewares.hsts-header.headers.browserXssFilter=true'
```
or is `@file` a reference? To all dynamic files or a fixed file? Please expand the documentation.

**Comment by ldez** [comment]
Hello,

In the [middleware overview](https://doc.traefik.io/traefik/middlewares/overview/) you can find a section about [Provider Namespace](https://doc.traefik.io/traefik/providers/overview/#provider-namespace).

You can also read the reference files, that contain all the available options:
- https://doc.traefik.io/traefik/reference/static-configuration/cli/
- https://doc.traefik.io/traefik/reference/dynamic-configuration/docker/

Based on the previous links to the documentation, it's not possible to define a middleware ([dynamic configuration](https://docs.traefik.io/getting-started/configuration-overview/#the-dynamic-configuration)) with CLI flags ([static configuration](https://docs.traefik.io/getting-started/configuration-overview/#the-static-configuration)).
