### ISSUE TITLE
Nomad variables as config store

### ISSUE THREAD

**Issue by chenjpu** [traefik/traefik#9381]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Add Nomad variables as a configuration store source

**Comment by rtribotte** [comment]
Hello @chenjpu,

Thanks for your interest in Traefik!

The Nomad provider already allows to define dynamic configuration through services tags, please see https://doc.traefik.io/traefik/providers/nomad/#configuration-examples.

**Comment by chenjpu** [comment]
Thanks for the reply, currently nomad managed services are implemented this way but there are some non-nomad managed services that are currently implemented relying on the kv of consul and hopefully through the variables of nomad.

**Comment by chenjpu** [comment]
@kevinpollet Thanks for the reply

The business system currently relies on nomad and consul, and plans to replace consul's services with native service with nomad, but still some traefik configurations are dependent on kv with consul, expecting kv to be replaced with Nomad variablessome traefik configurations are dependent on kv with consul, expecting kv to be replaced with Nomad variables
