### ISSUE TITLE
verify that the traefik configuration is reload successful

### ISSUE THREAD

**Issue by d9e7381f** [traefik/traefik#9383]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

when  traefik reload configuration,how can i kown it reload successful

**Comment by tomMoulard** [comment]
Hello @<user>,

Thanks for your interest in Traefik!

It can be found there : https://doc.traefik.io/traefik/observability/metrics/overview/#last-configuration-reload-success
