### ISSUE TITLE
Traefik Hackaethon: Integration of a crowdsec bouncer as a plugin

### ISSUE THREAD

**Issue by mathieuHa** [traefik/traefik#9389]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello,

We would like to present a new plugin made during the Traefik Hackaethon. (Team LittleThingProject)
This is not a bug report but more a presentation of our work.

Plugin catalog link: https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin

## Crowdsec Bouncer
This plugin is named "Crowdsec Bouncer" and it is publicly available at https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin.

This plugins aims to implement a Crowdsec Bouncer into a traefik middleware plugin.
> [CrowdSec](https://www.crowdsec.net/) is an open-source and collaborative IPS (Intrusion Prevention   System) and a security suite.
> We leverage local behavior analysis and crowd power to build the largest CTI network in the world.

The purpose is to enable Treafik to **authorize** and **block** requests from IP based and their **reputation** and **behavior**.

The Crowdsec utility will provide the community blocklist which contains highly reported and validated IP banned from the crowdsec network.

When used with Crowdsec it will leverage the local API which will analyze Traefik logs and take decisions on the requests made by users/bots. Malicious actors will be banned based on patterns against your website and infrastructure.

#### Requirements

It should be used in combination with a crowdsec service which can run in a docker-container.
The README of the project provides a docker-compose.yml file that includes traefik, crowdsec and a webservice which is protected by the middleware.

#### Initial startup

At startup the crowdsec container will fetch from a remote API (CAPI) the community blacklist, and traefik will cache this list of  decisions locally. 

#### Request flow

Every request that comes through traefik with the middleware enabled will be checked against the local cache for malicious IPs. If not found, the request will go on and else it will respond with a forbidden status code.

Every log from Traefik will be check against patterns in the Crowdsec container for what is called [scenarios](https://docs.crowdsec.net/docs/scenarios/intro). Crowdsec might then **take a decision to ban the IP locally**.
When a decision is made, Crowdsec will share it to the community anonymously. (It is possible to [opt out](https://docs.crowdsec.net/docs/faq#how-to-disable-the-central-api)).
Those meta-data are :
- The name of the scenario that was triggered
- The hash & version of the scenario that was triggered
- The timestamp of the decision
- Your machine_id
- The offending IP address (along with its geoloc info when available)

#### In the Background

Traefik will fetch regularly the new decisions made by Crowdsec and update its Blocklist.

### The Team

@maxlerebourg
@mathieuHa

#### About 

[maxlerebourg](https://github.com/maxlerebourg) and [I](https://github.com/mhanotaux) have been using traefik since 2020. We come from web developper and security engineer background and wanted to add the power of a very promising technology (Crowdsec) into the edge router we love.

We initially run into this project: https://github.com/fbonalair/traefik-crowdsec-bouncer It was using Traefik and forward auth middleware to verify every request. They had to go through a webserver which then contacts of another webservice (the crowdsec LAPI) to make a decision based on the source IP. We initially proposed some improvement by implementing a streaming mode and a local cache. 

With the Traefik hackathon we deciced to implement our solution directly as a Traefik plugin which could be found by every one on plugins.traefik.io and be more performant.

**Comment by nmengin** [comment]
The plugin is available in the [Traefik Plugins Catalog](https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin).
