### ISSUE TITLE
CertResolver unmarshal error with njalla

### ISSUE THREAD

**Issue by soupdiver** [traefik/traefik#9433]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Trying to get a LetsEncrypt certificate via dns validation from njalla.

According to https://github.com/traefik/traefik/issues/9232 and https://github.com/traefik/traefik/pull/9413 it should be fixed but I still see the same error with `2.9.1`

### What did you see instead?

`level=error msg="Unable to obtain ACME certificate for domains \"foo.coim\": unable to generate a certificate for the domains [foo.coim]: error: one or more domains had a problem:\n[foo.coim] [foo.coim] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int\n" providerName=web.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=remote-@consulcatalog rule="Host(`foo.coim`)"`

### What version of Traefik are you using?

`Traefik version 2.9.1`

### What is your environment & configuration?

```
[certificatesResolvers]
  [certificatesResolvers.web]
    [certificatesResolvers.web.acme]
      email = "xxx"
      storage = "/etc/traefik/acme/acme.json"
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      KeyType = "EC384"

    [certificatesResolvers.web.acme.dnsChallenge]
      provider ="njalla"
      delayBeforeCheck = 10
```

**Comment by ldez** [comment]
Hello,

lego has been updated after v2.9.1 (https://github.com/traefik/traefik/pull/9413) so it's will be a part of v2.9.2.

**Comment by soupdiver** [comment]
> Hello,
> 
> lego has been updated after v2.9.1 (#9413) so it's will be a part of v2.9.2.
> 
> https://github.com/traefik/traefik/commits/v2.9

Is there any ETA for the new version?

**Comment by kevinpollet** [comment]
Hi @soupdiver,

> Is there any ETA for the new version?

No ETA for now.
