### ISSUE TITLE
Persistent storage for certificates in S3

### ISSUE THREAD

**Issue by JohnPreston** [traefik/traefik#9434]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

As a Traefik user and using the very useful feature to have it provision SSL Certificates, to avoid having to request new certificates every time a container is re-created (faulty underlying HW, scaling etc), persisting in a different layer, i.e. AWS S3, with a logic of "check first if exists, generate second", would allow for a highly distributed deployment of traefik without risking rate limiting.

As of today one has to persist the certificates storage location and implement that logic externally to traefik.

Thank you for your consideration

**Comment by tomMoulard** [comment]
Hello @JohnPreston,

Thanks for your interest in Traefik!

As [the ACME HA feature was dropped](https://github.com/traefik/traefik/issues/2542#issuecomment-1242430094), and as there is no good proposition/design/implementation of the multiple certificate store proposal (#4756), this S3 persistent storage feature proposal cannot be accepted for now.
