### ISSUE TITLE
service-weights Causes traffic to be fully directed to canary pod

### ISSUE THREAD

**Issue by wolgod** [traefik/traefik#9436]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

service-weights Causes traffic to be fully directed to canary pod

### What did you see instead?

 When using the canary function, in the wrr scenario, two groups of services, A serves 9 pods, B serves 2 pods, the grayscale weight A is 80%, and B is 20%

```
http://10.168.130.220:80 | 8888
http://10.168.133.5:80 | 8888
http://10.168.134.206:80 | 8888
http://10.168.133.96:80 | 8888
http://10.168.132.180:80 | 8888
http://10.168.134.204:80 | 8888
http://10.168.133.32:80 | 8888
http://10.168.129.96:80 | 8888
http://10.168.133.167:80 | 8888
http://10.168.129.140:80 | 10000
http://10.168.129.113:80 | 10000
```
When this happens, the traffic will only be directed to the canary pods. After many verifications, it seems that it is because 80000/9 cannot be eliminated. If the test can be eliminated in other scenarios, the traffic will not be fully directed to the canary pods.

The canary weights are set as follows
```
    traefik.ingress.kubernetes.io/service-weights: |
      ttt-ww: 80%
      ttt-ww-canary: 20%
```

### What version of Traefik are you using?

1.7.26

### What is your environment & configuration?

```yaml
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/service-weights: |
      ttt-ww: 80%
      ttt-ww-canary: 20%

```

### If applicable, please paste the log output in DEBUG level

no

**Comment by kevinpollet** [comment]
Hello @wolgod and thanks for your interest in Traefik,

We are [not supporting the v1.x](https://doc.traefik.io/traefik/deprecation/releases/) branch anymore thus we will close this issue.

If you confirm the problem still exists on v2 please do not hesitate to open a new issue.
