### ISSUE TITLE
Middleware to inject `Connection: close` header probabilistically (or another means of redistributing load when autoscaling)

### ISSUE THREAD

**Issue by aecay** [traefik/traefik#9448]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I <sub>(/my employer, although I speak purely for myself here)</sub> am evaluating using traefik for managing ingress on some large (~500 nodes) company-internal kubernetes clusters.  In these clusters, we have configured pod autoscaling for our existing ingress controller (which we hope to replace with traefik) so that it can cope with fluctuations in load levels.  We'd be looking to replicate this setup with traefik.

Because our clusters serve mainly "backend" traffic (i.e. server-to-server), requests tend to come in on relatively few long-lived connections.  After the autoscaler spins up a new replica in response to increased demand, very little of the load will actually hit the new replica, because it's all being pipelined on existing connections.  (I'm reasonably sure that this is the same problem that was reported [here](https://community.traefik.io/t/new-pods-created-from-hpa-scale-not-taking-on-load/7441), incidentally.)

Our existing solution to this is to inject the `Connection: close` header in http responses at the ingress level with a certain (fixed) probability.  

<details>
<summary>If you're curious why we have chosen this approach...</summary>

...it was the simplest solution we could find that would give us eventually correct load spreading without the overhead of tracking per-connection state (such as the number of requests a connection had already handled, in order to close after a fixed number of requests).  The probability of injecting `conn:close` is tuned for the tradeoff between connection stability and reaction speed to changes in demand.  In practice, we're able to use values on the order of 1/1,000 - 1/2,000 probability of closing a connection which affords high stability while still reacting to demand shifts in an appropriate time.  This trick also works for http/2 in go, even though the spec around connection closing in http/2 is quite different -- the go http library massages things so that adding the header to a http/2 connection has the same effect even though it's implemented differently on the wire.  refs: [1](https://github.com/golang/go/issues/20977), [2](https://go-review.googlesource.com/c/net/+/121415/2/http2/server.go#2350)

</details>

Would this approach be acceptable to be coded up as a middleware to be added to traefik?  We could theoretically maintain an internal fork to add this functionality, but that's not something I'd prefer to do.  I'd much rather get the functionality upstreamed for us and also other users of the software.  I anticipate that this is something we'd be able to write ourselves and contribute.  IOW, this is not a request for you to implement this functionality for us, but just asking for a steer if this is a feature that upstream maintainers would look kindly on, or would not wish to accept / would suggest a different approach -- before we invest the effort (in things like good documentation) that would be needed for an upstream PR.

Thanks :slightly_smiling_face:

**Comment by aecay** [comment]
Hi @mpl, thanks for your response :slightly_smiling_face: 

1. Our existing ingress controller is a bit homegrown (hence why we want to replace it with something open source and more robust...).  Requests into our platform transit an haproxy layer, which handles SSL termination and a few other global/universal platform functionality (metrics, primarily).  It's also at that layer that the connection closing I've described is implemented.  Haproxy forwards to an nginx process which handles the routing and is the "ingress controller" per se.  (This all happens in a single pod: there are 3 processes running which are haproxy, nginx, and the ingress controller that translates the cluster Ingress objects into an `nginx.cfg` file for nginx to consume.  Each haproxy only talks to its local nginx, we don't have full N:M connectivity between the haproxy and nginx replicas).  This whole haproxy+nginx+controller process bundle is what we'd like to replace with traefik.

2. I looked briefly at the traefik plugin architecture.  There are two things that gave me pause:
   - It's prominently marked as experimental, and so it's not clear how well tested and supported it is.  We'd be unlikely to rely on a feature that carried such prominent disclaimers in our production environments.
   - It wasn't clear to me what the performance characteristics of the yaegi interpreter are.  A priori, it seems likely to add quite a bit of overhead (as compared to compiled code).  Has any benchmarking been done of the project?

   The two issues in combination of reliability and performance made me less inclined to pursue that option.

**Comment by juliens** [comment]
Hello @aecay 

I was reading your issue and wondering if you could resolve it with the MaxIdleConnPerHost options. ( https://doc.traefik.io/traefik/routing/services/#maxidleconnsperhost )

The MaxIdleConnPerHost would automatically close connections after a request if you reach the configured maximum number of connections between Traefik and your backend.

**Comment by mpl** [comment]
> 2. I looked briefly at the traefik plugin architecture.  There are two things that gave me pause:
>    
>    * It's prominently marked as experimental, and so it's not clear how well tested and supported it is.  We'd be unlikely to rely on a feature that carried such prominent disclaimers in our production environments.

I'd say the whole setup is pretty well honed, but there's no way around the fact that you're adding a "young" interpreter in the middle of the chain. Yaegi is (IMHO) the best and most complete Go interpreter there is, but it still has a few limitations (that we know about) and bugs (that we have yet to find out).

>    * It wasn't clear to me what the performance characteristics of the yaegi interpreter are.  A priori, it seems likely to add quite a bit of overhead (as compared to compiled code).  Has any benchmarking been done of the project?

Yes, there definitely will be some overhead, the amount of which will depend on the situation. We're doing some (micro?)-benchmarking on a private repo, but it's nothing that would be useful for you I think.
If you do go that route, and you do get some interesting performance measurement, we're very interested to know about it ;)

**Comment by nmengin** [comment]
Hey @aecay,

I guess we answered your question.
Feel free to reach out to us if you want to re-open it.
