### ISSUE TITLE
Traefik does not kill persistent connections when removing a service

### ISSUE THREAD

**Issue by thecooltechguy** [traefik/traefik#9455]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

If we register a service in Traefik's config, have a client create a persistent websocket connection to the service's backend, and then update Traefik's config to remove the service, new connections to the service's backend via Traefik will fail (as expected), but Traefik does not kill any existing persistent connections to the service (that were established prior to the service being deleted from Traefik's config).

### What did you see instead?

I believe this is an expected behavior in Traefik (as part of its graceful handling of client connections with services), but is there a way to configure a service in Traefik, such that Traefik will kill all persistent connections to that service when its deleted from the Traefik config?

### What version of Traefik are you using?

2.9.1

### What is your environment & configuration?

Docker

**Comment by kevinpollet** [comment]
Hello @thecooltechguy and thanks for your interest in Traefik,

> I believe this is an expected behavior in Traefik (as part of its graceful handling of client connections with services), but is there a way to configure a service in Traefik, such that Traefik will kill all persistent connections to that service when its deleted from the Traefik config?

As you said, this behavior is expected, and there is no way to configure Traefik to close the persistent connections when a corresponding service is deleted from the config. 

The GitHub issue tracker is dedicated to bug and feature requests. For questions, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik).
