### ISSUE TITLE
Update yaegi to 0.14.3 for better go code support

### ISSUE THREAD

**Issue by taliesins** [traefik/traefik#9470]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In order to improve the experience of writing plugins for Traefik we need to update to the latest version of yeagi. There have been a number of improvements which make it less of a worse experience when trying to write plugin code that compiles under yaegi.

https://github.com/traefik/yaegi/releases

**Comment by ldez** [comment]
Hello,

It's already updated and merged https://github.com/traefik/traefik/pull/9468

It will be shipped in the next bug fix release.
