### ISSUE TITLE
Cannot disable stats collection and "Go to Hub Dashboard" link

### ISSUE THREAD

**Issue by katbyte** [traefik/traefik#9508]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am trying to disable both the "Go to Hub Dashboard" and stats collection. when i add this to my config file:
```
[global]
  sendAnonymousUsage = false

[pilot]
  dashboard = false
```
i see this in my logs:
```
time="2022-11-14T21:29:06Z" level=info msg="Traefik version 2.9.4 built on 2022-10-27T18:44:34Z"
time="2022-11-14T21:29:06Z" level=info msg="Stats collection is enabled."
time="2022-11-14T21:29:06Z" level=info msg="Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration."
time="2022-11-14T21:29:06Z" level=info msg="Help us improve Traefik by leaving this feature on :)"
time="2022-11-14T21:29:06Z" level=info msg="More details on: https://doc.traefik.io/traefik/contributing/data-collection/"
time="2022-11-14T21:29:06Z" level=warning msg="Traefik Pilot has been removed."
```

### What did you see instead?

stats collection disabled and no "go to hub" link

### What version of Traefik are you using?

Traefik version 2.9.4 built on 2022-10-27T18:44:34Z

### What is your environment & configuration?

```yaml
[global]
  sendAnonymousUsage = false

[pilot]
  dashboard = false
```

is the only relevant part

### If applicable, please paste the log output in DEBUG level

N/A

**Comment by ldez** [comment]
Hello,

```
time="2022-11-14T21:29:06Z" level=warning msg="Traefik Pilot has been removed."
```

The following log means that to enable Pilot: when you enable Pilot, the stats are enabled also.

Pilot has been stopped https://traefik.io/blog/announcing-traefik-proxy-2-8/

So you have to remove all things related to Pilot from your configuration.

The Traefik Hub button (it's just a link, no js) cannot be disabled.
