### ISSUE TITLE
[Bug] Traefik takes as Certificate main name, a random san name!

### ISSUE THREAD

**Issue by Ramalama2** [traefik/traefik#9565]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

**### Example 1:**
```
[tls.stores]
  [tls.stores.default.defaultGeneratedCert]
    resolver = "lets-encrypt"
    [tls.stores.default.defaultGeneratedCert.domain]
      main = "jordan.de"
      sans = ["jordan.de", "kalista.de", "*.jordan.de", "*.kalista.de"]
```

**### Example 2:**
```
[http.routers.kerio-web-jordan]
  rule = "Host(`mail.jordan.de`)"
  entrypoints = ["websecure"]
  service = "kerio-srv-web"
  [http.routers.kerio-web-jordan.tls]
    certResolver = "lets-encrypt"
    [[http.routers.kerio-web-jordan.tls.domains]]
        main = "mail.jordan.de"
        sans = ["mail.jordan.de", "jordan.de", "mail.srv.jordan.de"]
```

### What did you see instead?

**### ACME Store:**

**### Example 1:**
This is the result of Example 1 above:
```
      {
        "domain": {
          "main": "*.jordan.de",
          "sans": [
            "*.kalista.de",
            "jordan.de",
            "jordan.de",
            "kalista.de"
          ]
        },
        "certificate": .....
```

**### Example 2:**
This is the result of Example 2 above:
```
      {
        "domain": {
          "main": "mail.srv.jordan.de"
        },
        "certificate": ...
```

I am using both examples in my config together and i am expecting that traefik generates and uses 2 separate certificates.
Instead, traefik combines them and uses the general certificate for everything, for example: mail.jordan.de
and only a separate certificate for mail.srv.jordan.de

The bigger issue is, that traefik doesn't my defined -> main = "mail.jordan.de"

### What version of Traefik are you using?

2.9.5

### What is your environment & configuration?

I wrote everything above!

**Comment by Ramalama2** [comment]
I have found a workaround, but i think i found also the next bug:

```
[tls.stores]
  [tls.stores.jordan.defaultGeneratedCert]
    resolver = "lets-encrypt"
    [tls.stores.jordan.defaultGeneratedCert.domain]
      main = "jordan.de"
      sans = ["*.jordan.de"]

  [tls.stores.kalista.defaultGeneratedCert]
    resolver = "lets-encrypt"
    [tls.stores.kalista.defaultGeneratedCert.domain]
      main = "kalista.de"
      sans = ["*.kalista.de"]

[http.routers.kerio-web-jordan]
  rule = "Host(`mail.jordan.de`)"
  entrypoints = ["websecure"]
  service = "kerio-srv-web"
  [http.routers.kerio-web-jordan.tls]
    certResolver = "lets-encrypt"
    [[http.routers.kerio-web-jordan.tls.domains]]
        main = "mail.jordan.de"
        sans = ["mail.jordan.de", "jordan.de", "mail.srv.jordan.de"]
```

This results in:
```
        "Store": "default"
      },
      {
        "domain": {
          "main": "*.jordan.de",
          "sans": [
            "jordan.de"
          ]
        },
        "certificate": ......


        "Store": "default"
      },
      {
        "domain": {
          "main": "*.kalista.de",
          "sans": [
            "kalista.de"
          ]
        },
        "certificate": .......


        "Store": "default"
      },
      {
        "domain": {
          "main": "mail.jordan.de",
          "sans": [
            "mail.jordan.de",
            "jordan.de",
            "mail.srv.jordan.de"
          ]
        },
        "certificate": ......
```

So i have separate certificates, as i wanted.

But there is a bug:
I defined as store name in the config jordan and kalista
But the certificate store name is "Store": "default"

However, i got it working for me and hope that helps someone either!

**Comment by Ramalama2** [comment]
```
ERRO[2022-12-01T01:02:13Z] Error while creating certificate store: unable to find certificate for domains "*.jordan.de,jordan.de": falling back to the internal generated certificate  tlsStoreName=jordan@file
ERRO[2022-12-01T01:02:13Z] Error while creating certificate store: unable to find certificate for domains "*.kalista.de,kalista.de": falling back to the internal generated certificate  tlsStoreName=kalista@file
```

I think this is related to the "second post bug", because the certificates are there and were successfull generated, but they are stored in "Store": "default" instead of  "Store": "jordan" and "Store": "kalista" as they should.

That errors pop up on every traefik container start/restart etc.

**Comment by nmengin** [comment]
Hello @Ramalama2,

Indeed, there is still a restriction in the way to manage the stores in Traefik as mentioned in the [documentation](https://doc.traefik.io/traefik/https/tls/#certificates-stores):

> Any store definition other than the default one (named default) will be ignored, and there is therefore only one globally available TLS store.

I hope it answers your question.
I close the issue, feel free to reach out to us if you want to re-open it.

**Comment by Ramalama2** [comment]
> Hello @Ramalama2,
> 
> Indeed, there is still a restriction in the way to manage the stores in Traefik as mentioned in the [documentation](https://doc.traefik.io/traefik/https/tls/#certificates-stores):
> 
> > Any store definition other than the default one (named default) will be ignored, and there is therefore only one globally available TLS store.
> 
> I hope it answers your question. I close the issue, feel free to reach out to us if you want to re-open it.

Hey @nmengin thanks for the reply, i though anyway that no one would reply on this.
The main "Bug" is still there, with Sans and the Main name.
The issues afterwards, are not a big deal.
Actually i found a nice workaround that i wanted to describe here for others. Which makes the bug on the second/third post obsolete.

However, the first one with the sans as name should be fixed 🙈

**Comment by nmengin** [comment]
Hello @Ramalama2,

Thank your for the feedback, I'd like to have more information about your us case.

> The main "Bug" is still there, with Sans and the Main name.

Could you explain why it's a problem? Indeed, the Main domain and the SANs are inspected during the TLS handshake, so whatever the order, your TLS certificate is valid.

> So i have separate certificates, as i wanted.

Why is it important to you?
Indeed, when Traefik handles a TLS connection, it checks every domain from each certificate put into the TLS store to validate the connection. So, whatever the certificate contains your domain, Traefik validates it.

**Comment by Ramalama2** [comment]
Hi @nmengin
Thanks for taking it seriously:-)

For the first, you're actually right, for the functionality of traefik it doesn't make a difference if the -main is one of the san names.
But there are 2 reasons that makes it a little confusing.
1. cert-dumper looks at the json files and export what is defined as main name.
2. The documentation, what i mean is, if -main and -sans doesn't make a difference in the config, why it should be there? Then those could be simply combined into -domains or something like that.

For the second question "why i wanted them separated".
I share the certificates with my Mailserver.
Using a wildcard certificate in a Mailserver is not recommended. Some mailservers add a score because of that.
1. So i need an mydomain.tld + mail.mydomain.tld certificate for the Mailserver
2. And an mydomain.tld + *.mydomain.tld for my "catchall, priority 1" webserver behind traefik.

For 1, mail.domain.tld is proxied to my Mailserver Webinterface and additionally that same certificate is used on the Mailserver itself through cert-dumper.
(The Mailserver exposes exchange services and smtp with that certificate) (Kerio connect)

Then i have cloud.mydomain.tld + cloud.otherdomain.tld behind traefik (nextcloud docker container).
But here traefik uses sometimes *.mydomain.tld instead of the cloud.mydomain.tld certificate.
- which is tbh not a big deal either

However, the biggest issue is mydomain.tld:
This gets routed through "catchall priotity 1" to the nginx webserver described as point 2 above.
But sometimes for mydomain.tld traefik uses the "mydomain.tld + mail.mydomain.tld" certificate instead of "mydomain.tld + *.mydomain.tld" certificate.

The problem with that is, that people that are visiting mydomain.tld, just need to look into the certificate and they will know what else im hosting behind the proxy.
And that information could be used to attack the services.

It was a simple description, but i have a lot more services and domain names and certificates.
I think tbh, it would be actually a lot easier if i post my configs, as they are pretty simple and more understandable.

On the other side, i got it actually working as i wanted. So this isn't a huge deal either.
But what i made feels more like some workarounds for everything, that will definitively break in the future 😂

**Comment by Ramalama2** [comment]
<details>
  <summary>traefik.toml</summary>

```
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
   watch = true
   network = "web"

[providers.file]
  filename = "traefik_dynamic.toml"
  directory = "traefik.d"
  watch = true

[log]
  level = "ERROR"

[api]
  dashboard = true

[certificatesResolvers.wildcard-storage.acme]
  email = "rama@jordan.de"
  storage = "/certs/acme-wildcard.json"
  [certificatesResolvers.wildcard-storage.acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 10

[certificatesResolvers.default-storage.acme]
  email = "rama@jordan.de"
  storage = "/certs/acme-default.json"
  [certificatesResolvers.default-storage.acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 10

[certificatesResolvers.internal-storage.acme]
  email = "rama@jordan.de"
  storage = "/certs/acme-internal.json"
  [certificatesResolvers.internal-storage.acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 10
```

</details>



<details>
  <summary>traefik.d/certs.toml</summary>

```
[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"

[tls.stores]
  [tls.stores.jordan.defaultGeneratedCert]
    resolver = "wildcard-storage"
    [tls.stores.jordan.defaultGeneratedCert.domain]
      main = "jordan.de"
      sans = ["*.jordan.de"]

  [tls.stores.kalista.defaultGeneratedCert]
    resolver = "wildcard-storage"
    [tls.stores.kalista.defaultGeneratedCert.domain]
      main = "kalista.de"
      sans = ["*.kalista.de"]

  [tls.stores.pupsi.defaultGeneratedCert]
    resolver = "wildcard-storage"
    [tls.stores.pupsi.defaultGeneratedCert.domain]
      main = "pupsi.de"
      sans = ["*.pupsi.de"]
```

</details>

<details>
  <summary>traefik.d/middlewares.toml</summary>

```
[http.middlewares]

  [http.middlewares.rate-limit.rateLimit]
    average = 100
    burst = 50

  [http.middlewares.rfc1918.ipWhiteList]
    sourceRange = ["192.168.27.0/24", "192.168.30.0/24", "192.168.29.0/24", "172.18.0.0/24"]

  [http.middlewares.authelia.forwardAuth]
    address = "http://authelia:9091/api/verify?rd=https://auth.jordan.de"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Name", "Remote-Email"]

  [http.middlewares.nextcloud-redirect.redirectRegex]
    permanent = true
    regex = "https://(.*)/.well-known/(card|cal)dav"
    replacement = "https://${1}/remote.php/dav/"

  [http.middlewares.nextcloud-headers.headers]
      accessControlMaxAge = 100
      hostsProxyHeaders = ["X-Forwarded-Host"]
      stsSeconds = 155520011
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true
      customFrameOptionsValue = "SAMEORIGIN"
      referrerPolicy = "same-origin"
      [http.middlewares.nextcloud-headers.headers.customResponseHeaders]
        X-Frame-Options = "SAMEORIGIN"

  [http.middlewares.chain-authelia.chain]
    middlewares = [ "rate-limit", "authelia"]

  [http.middlewares.chain-authelia-rfc1918.chain]
    middlewares = [ "rate-limit", "rfc1918", "authelia"]

  [http.middlewares.chain-nextcloud.chain]
    middlewares = [ "nextcloud-headers", "nextcloud-redirect"]
```

</details>

<details>
  <summary>traefik.d/routers.toml</summary>

```
[http.routers.api]
  rule = "Host(`proxy.srv.jordan.de`)"
  entrypoints = ["websecure"]
  middlewares = ["chain-authelia-rfc1918@file"]
  service = "api@internal"
  priority = 40
  [http.routers.api.tls]
    certResolver = "internal-storage"

[http.routers.kerio-web-jordan]
  rule = "Host(`mail.jordan.de`)"
  entrypoints = ["websecure"]
  service = "kerio-srv-web"
  priority = 90
  [http.routers.kerio-web-jordan.tls]
    certResolver = "default-storage"
    [[http.routers.kerio-web-jordan.tls.domains]]
        main = "mail.jordan.de"
        sans = ["mail.jordan.de", "mail.srv.jordan.de"]

[http.routers.kerio-web-kalista]
  rule = "Host(`mail.kalista.de`)"
  entrypoints = ["websecure"]
  service = "kerio-srv-web"
  priority = 90
  [http.routers.kerio-web-kalista.tls]
    certResolver = "default-storage"

[[http.services.kerio-srv-web.loadBalancer.servers]]
  url = "http://192.168.20.6:8800"
```

</details>

<details>
  <summary>Docker Labels:</summary>

```
Authelia Container
-l traefik.enable=true \
-l traefik.http.routers.authelia.rule="Host(\`auth.jordan.de\`)" \
-l traefik.http.routers.authelia.priority=100 \
-l traefik.http.routers.authelia.entrypoints=websecure \
-l traefik.http.routers.authelia.middlewares="rate-limit@file" \
-l traefik.http.routers.authelia.tls.certresolver=default-storage \
-l traefik.http.services.authelia.loadbalancer.server.port=9091 \

Nextcloud Container
-l traefik.enable=true \
-l traefik.http.routers.nextcloud.rule="Host(\`cloud.jordan.de\`,\`cloud.kalista.de\`)" \
-l traefik.http.routers.nextcloud.priority=80 \
-l traefik.http.routers.nextcloud.entrypoints=websecure \
-l traefik.http.routers.nextcloud.middlewares="chain-nextcloud@file" \
-l traefik.http.routers.nextcloud.tls.certresolver=default-storage \
-l traefik.http.services.nextcloud.loadbalancer.server.port=80 \

Nginx Container:
traefik.enable=true \
-l traefik.http.routers.nginx.rule='HostRegexp(`{domain:.+}`)' \
-l traefik.http.routers.nginx.priority=1 \
-l traefik.http.routers.nginx.entrypoints=websecure \
-l traefik.http.routers.nginx.tls.certresolver=wildcard-storage \
-l traefik.http.services.nginx.loadbalancer.server.port=80 \
```

</details>

Maybe that is easier to understand with the configs.
I have a lot more docker containers tho, but didn't wated to spam here.
Don't see this please as if i try to get help or something, its just a reply with trying to "Visualize" why separate certificates would be nice.
And why -main and -sans should work as expected and not random.

Thanks @nmengin really appriciated what you do here :-)
I played with nginx proxy manager some days ago, mainly because i need to use multiple dns challange accounts for different domains, but ugh there are so much other bugs xD
So traefik is actually hella amazing, just a bit limiting here xD

However, just wanted to thank you for this amazing project and your time.
Actually, if you dont want to bother, you dont need to reply, as my issues are actually not thaaat important.

Cheers
