### ISSUE TITLE
HeaderRegexp unsupported ?

### ISSUE THREAD

**Issue by emetrix** [traefik/traefik#9568]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I'm trying to implement a rule based on User-Agent evaluation using HeaderRegexp function. Traefik (2.9.5) is run as docker container.

### What did you see instead?

The traefik log files states that function "HeaderRegexp" is unsupported !?

### What version of Traefik are you using?

Version:      2.9.5
Codename:     banon
Go version:   go1.19.3
Built:        2022-11-17T15:04:26Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

Configuration is done using local toml files:

```
rule = "HeaderRegexp(\`User-Agent\`, \`{(?i:windows)}\`)"
```

### If applicable, please paste the log output in DEBUG level

```
level=error msg="error while parsing rule HeaderRegexp(`User-Agent`, `{(?i:windows)}`): **unsupported function: HeaderRegexp**"
```

**Comment by tomMoulard** [comment]
Hello @emetrix,

Thanks for your interest in Traefik !

The matcher is actually called `HeadersRegexp` (with an `s`).

**Comment by emetrix** [comment]
Thanks for clarification.
Maybe you can correct documentation at https://doc.traefik.io/traefik/master/routing/routers/ 

![image](https://user-images.githubusercontent.com/13239872/205062497-501edc9d-1076-4ff9-bbdd-d18d32355e7e.png)

**Comment by tomMoulard** [comment]
You are looking at the documentation of the master branch that has **not** been released yet. On the latest release, the matcher is `HeadersRegexp` (cf [Traefik v2.9 documentation](https://doc.traefik.io/traefik/v2.9/routing/routers/#rule)).
