### ISSUE TITLE
Add support for Private Network Access Header (PNA)

### ISSUE THREAD

**Issue by nehtor** [traefik/traefik#9573]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Since Browsers are starting to enforce Private Network Access (PNA) preflight headers (see for example [this chrome developer blog](https://developer.chrome.com/blog/private-network-access-preflight/)), it would be useful to have a corresponding `Access-Control-Allow-Private-Network` header included in the traefik middleware configuration.

When testing this in a setup with docker flags (traefik v2.9.5):
```
      - "traefik.http.routers.myservice.middlewares=setpna@docker"
      - "traefik.http.middlewares.setpna.headers.accesscontrolallowprivatenetwork=true"
```
It seems this is not currently the case and you get a `field not found, node: accesscontrolallowprivatenetwork"` error.

**Comment by tfny** [comment]
Hiya! Thanks for your suggestion. We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know and we will work with you to make sure you have all the information needed.

Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process.

**Comment by timothynfarmer** [comment]
A prime example of this use case would be the self hosting of a container such as Immich and modifying your DNS to look at the local IP address in lieu of a public IP where you're forced off network only to come back onto the same network.

**Comment by kevinpollet** [comment]
Hello,

This proposal was opened more than one year ago with almost no traction.
We will not add it to the Roadmap yet and prefer to close it.

We will re-open it later if needed.

Thank you @nehtor for the suggestion and @timothynfarmer your comment.
