### ISSUE TITLE
Add support for DNS alias mode (--challenge-alias flag) 

### ISSUE THREAD

**Issue by caissonfiv** [traefik/traefik#9584]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Do you want to request a feature or report a bug?
Feature

What did you expect to see?
Requesting support for the [DNS Alias Mode](https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode) with acme / Let's Encrypt.

This would allow me to use an _acme-challenge subdomain on a provider that does not have api support.

**Comment by ldez** [comment]
Hello,

The "DNS Alias Mode" is just the support of CNAME.

The CNAMEs are already supported:
- by default since v2.9
- by setting the en var `LEGO_EXPERIMENTAL_CNAME_SUPPORT` to `true`
