### ISSUE TITLE
multiple providers with the same rule

### ISSUE THREAD

**Issue by shantanugadgil** [traefik/traefik#9599]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Q: Is it possible to use **two different providers** with the same router `Rule` and have them round-robin load-balance among backend tasks of **both the providers**?

When I run a loop with the following code, I observe that it always hits the backends from only one provider.
The Nomad tasks echo "HELLO FROM NOMAD" and the ECS tasks echo "HELLO FROM ECS" in their respose string.

```bash
while (( 1 )); do
        curl -s http://traefik.internaldomain.vpc/hello 2>&1 | grep HELLO
        sleep 3

done
```
### What did you see instead?

When I stop tasks of any one provider. Traefik routers to backend tasks of the other provider.

I want Traefik to treat the backend tasks from the both the providers in the same "pool" (so to speak).

Is this feasible?

### What version of Traefik are you using?

2.9.6

### What is your environment & configuration?

```yaml
...

providers:
  ecs:
    exposedByDefault: false
    autoDiscoverClusters: false
    clusters:
      - my-ecs-cluster
    region: 'my-aws-region'
    ecsAnywhere: false

  nomad:
    exposedByDefault: false

```

Add more configuration information here.

Labels on the ECS task:

```
      dockerLabels = {
        "traefik.enable" : "true",
        "traefik.http.routers.myrouter.rule": "Path(`/hello`)"
        "traefik.http.routers.myrouter.priority": "1"
        "traefik.http.routers.myrouter.service": "myservice"
        "traefik.http.routers.myrouter.entrypoints": "web,websecure"
        "traefik.http.services.myservice.loadbalancer.passhostheader": "true"
      }
```

Tags on the Nomad service:
```
      service {
        provider = "nomad"

        name = "my-service-name"
        port = "http"
        tags = [
          "traefik.enable=true",
          "traefik.http.routers.myrouter.rule=Path(`/hello`)",
          "traefik.http.routers.myrouter.priority=1",
          "traefik.http.routers.myrouter.service=myservice",
          "traefik.http.routers.myrouter.entrypoints=web,websecure",
          "traefik.http.services.myservice.loadbalancer.passhostheader=true",
        ]

        check {
          name     = "health"
          type     = "http"
          path     = "/"
          interval = "30s"
          timeout  = "10s"
        }
      } # service
```

**Comment by tomMoulard** [comment]
Hello @shantanugadgil,

Thanks for your interest in Traefik!

It seems to be better when things are explicit more than implicit. It would be better to use a [load balancer](https://doc.traefik.io/traefik/routing/services/#weighted-round-robin-service) between both of your services using the [file provider](https://doc.traefik.io/traefik/providers/file/).

**Comment by ldez** [comment]
no, you need to define [services](https://doc.traefik.io/traefik/routing/services/) without routers and then reference them to a "global" router.
You don't need several Traefik.

if you want to continue the discussion, please join the [community forum](https://community.traefik.io/).

**Comment by shantanugadgil** [comment]
Hi @ldez @tomMoulard I have created a community discussion here:

https://community.traefik.io/t/multiple-providers-with-the-same-http-path-rule/16888
