### ISSUE TITLE
The retry middleware does not retry when connection is refused on a backend pod

### ISSUE THREAD

**Issue by yudingling** [traefik/traefik#9618]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

we configured the retry middleware according to the documentation (k8s), and we got 2 backend pods for the test service,  And increase the load on one of the pods (called A pod) through the test interface until all connections to this pod are rejected (connection refused).  
Then access this service through traefik, we expect that the request sent to A pod can be retryed to another pod, and finally return http status 200

### What did you see instead?

through the traefik log, we found that the requests forwarded to A pod all return 502, and RetryAttempts is 0

<img width="633" alt="image" src="https://user-images.githubusercontent.com/9546800/209547181-5f0d7fa5-52a2-456f-8a75-5cd2d2207071.png">

### What version of Traefik are you using?

traefik:v2.8.3

### What is your environment & configuration?

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-retry
spec:
  retry:
    attempts: 3

**Comment by tomMoulard** [comment]
Hello @yudingling,

Thanks for your interest in Traefik!

Reading this issue, it seems that using a [failover service](https://doc.traefik.io/traefik/routing/services/#failover-service) could solve your need.

Using such service could redirect to another pod when the pod A is not available.

WDYT ?

**Comment by yudingling** [comment]
> failover service



> Hello @yudingling,
> 
> Thanks for your interest in Traefik!
> 
> Reading this issue, it seems that using a [failover service](https://doc.traefik.io/traefik/routing/services/#failover-service) could solve your need.
> 
> Using such service could redirect to another pod when the pod A is not available.
> 
> WDYT ?

Hi @tomMoulard ,
Thanks, I read the description of failover, it means that when the health check fails, failover to other services, but my requirement is to retry to other pods of the current service. The problem in this issue is not caused by the health check, because traefik is still directly forward the request to pod A, indicating that pod A has not been eliminated by the endPoints of k8s at that time.

**Comment by tomMoulard** [comment]
According to the [doc](https://doc.traefik.io/traefik/middlewares/http/retry/), the retry middleware will only retry requests when the server did not reply.
So if the pod A replied `502` to Traefik, the middleware did not retry the request and responded to the client.

That being said, I now think that you are asking a question about the core functionality of the retry middleware, and I do not think that this issue is the place to do that.

To confirm this, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik/5).
