### ISSUE TITLE
traefik proxy 2.9 => 3.0 ClientIP()

### ISSUE THREAD

**Issue by hrolofs** [traefik/traefik#9628]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hello,

it's more of a question than a problem.

Tested my configuration for Traefik 2.9 with Beta 3.0.

Everything works without any change except the ClientIP() in the router rules.

Previously you could specify a list of IPs in ClientIP(). Only a single IP address works with 3.0. 
After I changed the router rule

```ClientIP(`ip1`,ìp2`) => (ClientIP(`a`) || ClientIP(`b`))``` everything works again.

Is this correct for 3.0 that only one argument for ClientIP() is possible?

Regards, Henry

### What did you see instead?

only a question

### What version of Traefik are you using?

Version:      3.0.0-beta2

### What is your environment & configuration?

      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain`) && ClientIP(`a,`b`)"

change to

      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain`) && (ClientIP(`a) || ClientIP(`b`))"

**Comment by ldez** [comment]
Hello,

yes, in v3.0, all the matchers take only one parameter.
Basically, the previous matchers don't follow the same rule (AND/OR) with multiple parameters, and it was confusing.

So your change is right.
