### ISSUE TITLE
 The webui interface of the traefik control panel does not have the account authority management function

### ISSUE THREAD

**Issue by cherishman2005** [traefik/traefik#9644]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The webui interface of the traefik control panel does not have the account authority management function
![image](https://user-images.githubusercontent.com/17688273/210959154-1f94df4a-41af-47c0-8db0-a51a008e4a1f.png)

**Comment by youkoulayley** [comment]
Hello @cherishman2005 and thanks for your interest in Traefik,

What do you mean by account authority management function?

**Comment by cherishman2005** [comment]
> Hello @cherishman2005 and thanks for your interest in Traefik,
> 
> What do you mean by account authority management function?

yes, account authority management function

**Comment by kevinpollet** [comment]
Hello @cherishman2005,

If you want Traefik to manage identities/rights when accessing the dashboard, this is something we are not willing to do, as we want to stay stateless. You can already secure the dashboard, as explained in the following [documentation](https://doc.traefik.io/traefik/operations/dashboard/#secure-mode)
