### ISSUE TITLE
Possibility to rewrite `proxy_cookie_domain` via Traefik.

### ISSUE THREAD

**Issue by fooness** [traefik/traefik#9675]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello everyone.

I’m searching for solutions to this issue for quite some time, but didn’t find anything helpful; please excuse if I just haven’t seen a definite solution somewhere, and please feel free to point me in the right direction if that feature already exists.

For my docker composition with multiple different services, I would like to be able to modify the cookie domain of one service (accessible via `sub.domain.tld`) so that another service (running via `domain.tld`) can access/read the cookie.

In nginx, if I’m not mistake, this can be solved via [`proxy_cookie_domain`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_domain).

Is there any way to replicate this feature in Traefik?

**Comment by mpl** [comment]
Hello @fooness 

We think your use-case seems legitimate, which is why moved this issue as a proposal.

However, we suspect there is nothing preventing that feature to be implemented as a plugin, or even better, that there already is a plugin that would address your problem. In which case, there would not be any reason to do it in traefik itself.

Have you had a look in the plugin catalog already to check if something could fit your need?
https://plugins.traefik.io/plugins

**Comment by fooness** [comment]
Hello @mpl, thank you for your kind reply and pointing me towards to plugin directory; checking the plugins matching the ”cookie” search term don’t seem to help in my specific demand, but I will take some more time to search for different domain- and proxy-related plugins, maybe I will—in fact—find something that would enable the needed functionality.

**Comment by SchmitzDan** [comment]
Hi @fooness, inspired by your use-case i implemented the plugin "Proxy Cookie" which works similar to NGINXs proxy_cookie directives: https://plugins.traefik.io/plugins/63f635069454451553c1c914/proxy-cookie
Maybe you will give it a try.
Please feel free to write an issue in the github repo if you tested the plugin and there are any problems.

**Comment by fooness** [comment]
@SchmitzDan Oh wow, thank you very much! Will definitely give this a try as soon as possible.
