### ISSUE TITLE
About etcd provider

### ISSUE THREAD

**Issue by BlackCodes** [traefik/traefik#9690]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Dear Traefik Developer:
  When I use traefik-proxy with find [a github repo](https://github.com/kvtools/etcdv3). For this repo, there is a normalize of function for each etcd key. I don't understand why use it.  why not remove it?

When I use etcd as provider, The etcd key is big trouble.
```go 
// normalize the key for usage in Etcd.
func normalize(key string) string {
	return strings.TrimPrefix(key, "/")
}

func (s *Store) list(ctx context.Context, directory string, opts *store.ReadOptions) (int64, []*store.KVPair, error) {
	ctx, cancel := context.WithTimeout(ctx, etcdDefaultTimeout)
	defer cancel()

	var resp *etcd.GetResponse
	var err error

	if opts != nil && !opts.Consistent {
		resp, err = s.client.KV.Get(ctx, normalize(directory), etcd.WithSerializable(), etcd.WithPrefix(), etcd.WithSort(etcd.SortByKey, etcd.SortDescend))
	} else {
		resp, err = s.client.KV.Get(ctx, normalize(directory), etcd.WithPrefix(), etcd.WithSort(etcd.SortByKey, etcd.SortDescend))
	}

	if err != nil {
		return 0, nil, err
	}
}
```

### What did you see instead?

remove it

### What version of Traefik are you using?

v3.0-b2

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

what is exactly your problem with the normalization of keys?
can you provide a clear example?

**Comment by BlackCodes** [comment]
> Hello,
> 
> what is exactly your problem with the normalization of keys? can you provide a clear example?

We using frame of microService, such as Kratos,Go-zero,Micro and so on, it will be registry a discover key, the key prefix is   char `/` of each one.

Kratos:
![Uploading image.png…]()

**Comment by ldez** [comment]
Your image is missing.

Your problem seems to be related to [kvtools/etcdv3](https://github.com/kvtools/etcdv3) implementation so I recommend [opening an issue in this repo](https://github.com/kvtools/etcdv3/issues).

**Comment by BlackCodes** [comment]
thks, I agree with your options.

**Comment by BlackCodes** [comment]
thks, I agree with your options.
