### ISSUE TITLE
Allow non-gzip compression methods

### ISSUE THREAD

**Issue by JaneJeon** [traefik/traefik#9695]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi, I would like to request the ability to have a non-gzip compression methods in the default `compression` middleware.

Basically, gzip is _great_ at getting great compression ratios. However, there are reasons to consider other compression methods (all of which basically fall into making trade-offs).

For example, Snappy (_cough_ it's the reason I'm making this feature request) from my experience has a compression ratio ~50% worse than gzip (which is still pretty good, considering how dang good gzip is at compression _ratios_), but in return, is _way less_ compute-intensive, often showing a ~5x (or more!) improvement in CPU cycles to compress over gzip.

For an application as concurrent as a reverse proxy (in this case, Traefik), it would make sense to make the tradeoff of "slightly less compression ratio but _much_ faster compression time" if you're constrained not by network bandwidth or payload size, but rather by the number of requests and/or concurrency and/or end-to-end latency.

Obviously, that math of whether that tradeoff is worth it or not is going to _highly_ depend on the user's setup and expected usage and whatnot, but I still feel that it would be useful to have the _option_ to make such a tradeoff using different compression algorithms.

Thanks

**Comment by JaneJeon** [comment]
Ah, I'll simply wait for the v3 release then. Thank you.

**Comment by nmengin** [comment]
According to the latest answer, duplicate of #4202
