### ISSUE TITLE
Why does traefik have such a hard to use and hard to understand documentation?

### ISSUE THREAD

**Issue by niaiwomattt** [traefik/traefik#9699]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

The characteristics of traefik documentation are that it cannot be used, it is not easy to use, it is disorganized, and it is difficult to understand.

Deploy services according to the traefik document, there are very few services that can be accessed successfully, and various configurations are scattered and messy. Except for developers, it is estimated that few people understand the traefik documentation. I successfully configured traefik in 2022, and applied it to docker, k3s and other infrastructure, but today I read the traefik documentation, and I still find it difficult to use. I hope the traefik documentation team can create a new one that can be used and is easy to use. Clear, well-organized, easy-to-understand documentation. Thanks.

**Comment by tfny** [comment]
Hey, Thanks for the feedback.  We do know that our docs can be confusing for many people, and I am happy to say that we are working to improve the language and organization.  It will take some time, but we have dedicated resources for the project and are going in the right direction. 

If you have specific suggestions to improve things in the meantime, please feel free to open a PR.  We love community help.  

If you are struggling with any particular questions visit our [Community Forum](https://community.traefik.io/).  It is very active and your question might already be answered there.
