### ISSUE TITLE
Docker Swarm provider: Support auto weight backend servers by node label

### ISSUE THREAD

**Issue by olljanat** [traefik/traefik#9710]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I thinking about add support to Docker Swarm provider (after it is separated by #9652) for auto weight backend servers based on how nodes are labeled.

For example we would be able to have multi zone/region configuration like this (I included only one weight 0 route to keep picture simpler but that would exists for all containers on both regions):
![image](https://user-images.githubusercontent.com/6213926/218402636-1f3cbfa8-0e15-48db-9259-e7097ee0e055.png)

Where all traffic between applications happens though Traefik and we want that local replicas are used as long they are healthy.
Configuration would happen in way that we tell Traefik its local zone/region with configuration like this
```yaml
providers:
  swarm:
    localZone: westeurope
    localZoneWeight: 100
```
and other zone replicas would get weight 100 - local zone weight.

WDUT, is this something which can be accepted to Traefik?

**Comment by mpl** [comment]
Hello @olljanat ,

We are not sure that the way you propose to achieve this kind of fallback is the best way to do so, and we would need to spend more time thinking about it.
However, it is unlikely that we'll be able to do so in the near future.

thanks

**Comment by emilevauge** [comment]
Hi, due to the lack of feedback from the community on this proposal, we made the decision to decline it.
Thanks again for your contribution.
