### ISSUE TITLE
Feature: Docker hub image tag that tracks github releases

### ISSUE THREAD

**Issue by yorickdowne** [traefik/traefik#9711]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently, the `latest` tag on Docker Hub is tracking both releases and pre-releases on github, and so corresponds to `3.0.0-beta2`.

It would be useful to have a tag that only tracks releases.

You could, for example, either change `latest` to only track releases, or add a tag `stable` that does so.

**Comment by ldez** [comment]
Hello,

The `latest` tag on Docker Hub is tracking only the stable release (v2.x).

https://github.com/docker-library/official-images/blob/bd72690865ffcdbb811ddc9b95b3f02910523fd2/library/traefik#L23

**Comment by yorickdowne** [comment]
So it is. How we ended up with 3.0 on `latest` will remain a mystery ...
