### ISSUE TITLE
Logging mTLS information in access logs when present.

### ISSUE THREAD

**Issue by HamishWHC** [traefik/traefik#9719]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like to see an option to log parts of the mTLS certificate subject in access logs, so that we can filter logs by user (each user has a unique certificate). Currently, I can't see in logs who is making requests. I'm using Traefik for a CTF platform for a university course, so requests commonly come from a single IP address (the uni). As far as I can tell from Traefik's docs, it isn't currently possible to log this information. Is it possible with the current system for middleware to add to access logs? If so, I'll write a plugin, but I can't figure out how to do this currently. Thanks.

**Comment by rtribotte** [comment]
Hello @HamishWHC ,

Thanks for your interest in Traefik,

It should be possible to use the [passtlsclientcert middleware](https://doc.traefik.io/traefik/middlewares/http/passtlsclientcert/) to have the `X-Forwarded-Tls-Client-Cert-Info` header fill with whatever is needed and then configure accordingly the AccessLogs to include this header: https://doc.traefik.io/traefik/observability/access-logs/#limiting-the-fieldsincluding-headers.

The GitHub issue tracker is dedicated to bug and feature requests.
For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.

**Comment by HamishWHC** [comment]
Wow I completely glossed over the headers section in the access logs docs. Sorry about that! Thanks for your help.

**Comment by jaybubs** [comment]
I was having a similar issue not too long ago so I wrote this midldeware plugin for dumping exactly that type of information into logs https://plugins.traefik.io/plugins/63e4c4329454451553c1c911/header-dump might help you too!
