### ISSUE TITLE
Not able to use fail2ban plugin

### ISSUE THREAD

**Issue by dberardo-com** [traefik/traefik#9744]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

i am experiencing this issue while installing fail2ban following the official install instruction: https://github.com/traefik/traefik/issues/8004
i am runnin traeifk v 2.9.4

### What did you see instead?

same error as in https://github.com/traefik/traefik/issues/8004

### What version of Traefik are you using?

2.9.4

### What is your environment & configuration?

```
--experimental.plugins.fail2ban.modulename=github.com/tomMoulard/fail2ban
--experimental.plugins.fail2ban.version=v0.6.6
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

from our logs, I think you have edited the configuration without restarting Traefik.
`github.com/tomMoulard/fail2ban/v0.6.6` is not a valid module name.

```
2023-02-23 21:21:08 | [ {"level":"warn","module_name":"github.com/tomMoulard/fail2ban/v0.6.6","module_version":"","error":"not found: no documents in result","caller":"/home/semaphore/go/src/github.com/traefik/plugin-service/pkg/handlers/module.go:47","message":"Unknown plugin"}
2023-02-23 21:23:56 | {"level":"warn","module_name":"fail2ban/v0.6.6","module_version":"","error":"not found: no documents in result","caller":"/home/semaphore/go/src/github.com/traefik/plugin-service/pkg/handlers/module.go:47","message":"Unknown plugin"}
```

Note, I recommend using the latest stable version (v2.9.8) https://github.com/traefik/traefik/releases

**Comment by dberardo-com** [comment]
i have been following this guide: 
![image](https://user-images.githubusercontent.com/65530457/221139256-5926f601-6499-4a28-aebd-cf7ae7554559.png)

this leads to the pod trying to download the package from here: https://plugins.traefik.io/public/download/github.com/tomMoulard/fail2ban/v0.6.6

which name should i use instead ? i am trying to browser directly your catalog, but i cant find an index page in here https://plugins.traefik.io/public/download/

**Comment by ldez** [comment]
I think I found the issue, I'm currently deploying a new version of the service.

If you still have the problem after the deployment, can you give me your logs?

**Comment by dberardo-com** [comment]
i think it works now, i have restarted the pod without changing anything and this is the log:

> level=debug msg="loading of plugin: fail2ban: github.com/tomMoulard/fail2ban@v0.6.6"

great. 

btw, where should i post a question on the "rate limit" middleware? i dont seem to find out how the "average" parameter works, it seems that only the "burst" param has an actual effect on the middleware, whereas "average" does not really do much

**Comment by ldez** [comment]
> i think it works now

:tada: 

> where should i post a question on the "rate limit" middleware?

I recommend asking in the [community forum](https://community.traefik.io/)
