### ISSUE TITLE
Consider switching to github.com/antonmedv/expr

### ISSUE THREAD

**Issue by antonmedv** [traefik/traefik#9745]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello!  Thanks for the awesome project!) 👍🏻 

May I suggest switching to using https://github.com/antonmedv/expr for rules?

Expr has a similar syntax, precompiles expressions to bytecode, and even type-checks them. And more importantly, it is fast.

**Comment by ldez** [comment]
Hello,

your issue feels like a way to promote your project :thinking:.

Our current implementation, which we maintain, works well, we don't have issues with it.

We will decline your issue, but we keep your suggestion if want to change our rule expressions system.

**Comment by antonmedv** [comment]
Yes, it is a promotional issue 😁

True, you can keep any implementation you want. 

But again, if you want to switch to Expr, I’ll be extremely glad. And can help with implementation and adding missing features to Expr. 

Expr is quite popular today already. And used at a few big companies in production for a few years already.

Im going to create a bench to show a speed difference.
