### ISSUE TITLE
Plugin is not indexed anymore?

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#9760]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Tagged a new plugin version

### What did you see instead?

Nothing

### What version of Traefik are you using?

v2.7+

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

plugins are still indexed.

**Comment by darkweak** [comment]
@ldez can you tell me why the versions I released are not indexed then? There are no opened Træfik issues on the repository so I can't debug that.

**Comment by ldez** [comment]
I recommend explaining your problem and providing details when you open an issue.
The issue description is the right place for that.

I will investigate.

**Comment by ldez** [comment]
It's because your plugin has been temporarily excluded (2023-01-20) from the indexation because of a panic produced by your plugin.

I removed the temporary exclusion, your plugin will be indexed in around 30 minutes.

**Comment by ldez** [comment]
indexed https://plugins.traefik.io/plugins/6294728cffc0cd18356a97c2/souin

**Comment by darkweak** [comment]
Thank you!
