### ISSUE TITLE
Redirect flux from api.XXX.something.com to the service XXX dynamically 

### ISSUE THREAD

**Issue by Adrien-Zemma** [traefik/traefik#9761]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

In this scenario the goal is to start test instances of my code with dockers named by the name of the branch to be tested. So is it possible that if I request the address api.VH-1234.things.com it redirects me to the VH-1234 service but dynamically without specifying service by service to which address they are linked

**Comment by ldez** [comment]
Hello,

To handle this scenario, you will have to use the default rule system.
https://doc.traefik.io/traefik/providers/docker/#defaultrule

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2).
