### ISSUE TITLE
Please mention the resource kind the "Routers" examples are supposed to work with

### ISSUE THREAD

**Issue by HouzuoGuo** [traefik/traefik#9764]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hey. On https://doc.traefik.io/traefik/routing/routers/ the examples go like:

```
## Dynamic configuration
http:
  routers:
    routerfoo:
...
```

However, there is no explanation given to indicate what kind of k8s resources the examples are supposed to work with. Please complete the examples with the resource kind name and `apiVersion`. Thanks.

**Comment by ldez** [comment]
Hello,

this example and the others on this page are related to the [file provider](https://doc.traefik.io/traefik/providers/file/) and not to Kubernetes.

**Comment by HouzuoGuo** [comment]
I'm quite confused, does that imply routers don't work with Kubernetes at all?

**Comment by HouzuoGuo** [comment]
Is the TCP router feature also exclusive to the file provider?

![image](https://user-images.githubusercontent.com/563872/223843931-e776dd6d-d48f-4362-9cc7-6ad784a7c175.png)

**Comment by ldez** [comment]
yes the examples are related to the file provider.

The sections dedicated to routing for Kubernetes are here:

- https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
- https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/
- https://doc.traefik.io/traefik/routing/providers/kubernetes-gateway/
