### ISSUE TITLE
Dedicated entrypoint for service with TLS Termination without SNI with certresolver

### ISSUE THREAD

**Issue by d3xt3r01** [traefik/traefik#9780]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Currently I have OPENLDAP behind a dedicated entry point with a rule=HostSNI(`hosthere.local.lan`). Also, for it I'm using stepca as a local acme cert provider.
The problem is that there are still some clients, like RocketChat, that use various implementations, like ldapjs, that don't do SNI by default. In this case traefik fails to route the traffic.

Using HostSNI(`*`) breaks the cert resolver getting certificates for the TLS. And I can't find a way for to tell what certificate for it to use that it can auto-use the resolver to refresh/renew.

My usecase for traefik besides the routing to containers is to do TLS termination. Most clients do know how to do SNI, ldapjs knows how to do that too, but doesn't do it by default and expects the project implementing ldapjs to add `servername: host` to enable SNI.

**Comment by rtribotte** [comment]
Hello @d3xt3r01,

Thanks for your interest in Traefik!

> Using HostSNI(*) breaks the cert resolver getting certificates for the TLS. And I can't find a way for to tell what certificate for it to use that it can auto-use the resolver to refresh/renew.

Are you looking for a way to not catch the ACME TLS challenge connections but catch every other?
If so, please consider using the `ALPN` matcher with the protocols you want to catch (e.g.: ```ALPN(`http/1.1`, `h2`)```), please see [this part](https://doc.traefik.io/traefik/v2.9/routing/routers/#rule_1) of the documentation.
Please note that ACME TLS challenge protocol (`acme-tls/1`) is forbidden to use with the `ALPN` matcher.

**Comment by d3xt3r01** [comment]
Hi!

No, the service I'm trying to use is openldap which is a tcp service. I'm using traefik to terminate TLS for it.
The problem is that I have a ldap client that can't do SNI so traefik can't route the traffic to the service.
I have a dedicated entrypoint for it, I can do HostSNI(`*`) but then the resolver can't do certificate refreshing.

**Comment by rtribotte** [comment]
Hello @d3xt3r01,

Have you tried to configure the domains in the TLS configuration of the TLS Router? Please see https://doc.traefik.io/traefik/v2.9/routing/routers/#domains_1.

**Comment by d3xt3r01** [comment]
```
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.openldap.entrypoints=openldap"
      - "traefik.tcp.routers.openldap.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.openldap.tls=true"
      - "traefik.tcp.routers.openldap.tls.options=nonstrictsni@file"
      - "traefik.tcp.routers.openldap.tls.domains.main=openldap.local.lan"
      - "traefik.tcp.routers.openldap.tls.certResolver=stepca"
      - "traefik.tcp.services.openldap.loadbalancer.server.port=1389"
      - "traefik.docker.network=docker-traefik_traefik"
```
Like this?
```
traefik_1   | time="2023-03-16T11:05:23Z" level=error msg="Unable to obtain ACME certificate for domains \"\"" error="no domain was given" routerName=openldap@docker rule="HostSNI(`*`)" providerName=stepca.acme ACME CA="https://stepca.local.lan:9000/acme/acme/directory"
traefik_1   | time="2023-03-16T11:05:31Z" level=info msg="Testing certificate renew..." providerName=stepca.acme ACME CA="https://stepca.local.lan:9000/acme/acme/directory"
```

**Comment by d3xt3r01** [comment]
I think it's `- "traefik.tcp.routers.openldap.tls.domains[0].main=openldap.local.lan"` and it might work! Tried it and didn't yell an error yet. I'll wait for a renew to make sure.

**Comment by d3xt3r01** [comment]
Yep... That was it. The docs need more examples...
Thanks and sorry for wasting your time.
