### ISSUE TITLE
= character causes mux: number of parameters must be multiple of 2

### ISSUE THREAD

**Issue by qudiqudi** [traefik/traefik#9785]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Possibly #9368 again.

`=` character introduces `mux: number of parameters must be multiple of 2` error.

Just like in the above mentioned bug report, trying to pass an api-key containing `=` via router rule.

### What did you see instead?

mux: number of parameters must be multiple of 2

### What version of Traefik are you using?

traefik 2.9.8

### What is your environment & configuration?

```
traefik.http.routers.serviceA.rule=Host(`serviceA.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$SERVICEA_API_KEY`) || Query(`apikey`, `$SERVICEA_API_KEY`))
```

The API key contains a single `=` at the end.

### If applicable, please paste the log output in DEBUG level
```
time="2023-03-17T15:19:49+01:00" level=error msg="mux: number of parameters must be multiple of 2, got [apikey ***REDACTED but important to mention that the `=` character is missing from this log output ]" routerName=serviceA-rtr-bypass@docker entryPointName=https
```

_No response_

**Comment by ldez** [comment]
Hello,

the answer is the same https://github.com/traefik/traefik/issues/9368#issuecomment-1256184660

the right syntax for the query parameter is ```Query(`api=aaa`)```

**Comment by qudiqudi** [comment]
Changing the syntax to this
```
traefik.http.routers.serviceA.rule=Host(`serviceA.$DOMAINNAME`) && (Headers(`X-Api-Key=$SERVICEA_API_KEY`) || Query(`api=$SERVICEA_API_KEY`))
```

does not change it the error unfortunately.
What do you mean by syntax? According to the documentation the syntax was right.

```
Headers(`key`, `value`)
```

**Comment by ldez** [comment]
It cannot be the exact same error with the new syntax, have you restarted your containers?
