### ISSUE TITLE
Connection timeouts when using more than 1 deployment replicas with AWS NLB

### ISSUE THREAD

**Issue by pavlospt** [traefik/traefik#9797]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hey 👋🏻 

We recently started using Traefik for one of our pre-production environments and we noticed that we get several timeouts randomly. This is happening only when the replicas of the Traefik deployment are increased to 2. When using a single replica, there is no issue at all. 

We are using 2.9.8 version through a Helm release.

### What did you see instead?

Random timeout requests when using more than 1 replica deployment for Traefik. 

Update 1 : From a deeper investigation it seems that this is related to keep-alive. Traefik does not properly close connection when operating with more than 1 replica, causing it to try re-using an existing connection which leads to the timeout. The situation is mildly mitigated when modifying `maxIdleConnectionsPerHost` to a big number, but the issue still exists. One thing to mention here, is that we do not use another proxy in-between Traefik and the service/pod it directs the traffic to, in contrast to a previously reported issue related to stale connections #9688 . 

Update 2: Another similar issue, closed without any comments: https://github.com/traefik/traefik/issues/7650

### What version of Traefik are you using?

2.9.8

### What is your environment & configuration?

```yaml
        - --entrypoints.metrics.address=:9100/tcp
        - --entrypoints.traefik.address=:9000/tcp
        - --entrypoints.web.address=:80/tcp
        - --entrypoints.websecure.address=:443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --providers.kubernetescrd
        - --providers.kubernetescrd.labelSelector=traefik=traefik-eks-public
        - --providers.kubernetescrd.ingressClass=traefik-eks-public
        - --providers.kubernetescrd.allowCrossNamespace=true
        - --providers.kubernetesingress
        - --providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik-eks-public
        - --providers.kubernetesingress.ingressClass=traefik-eks-public
        - --log.level=INFO
        - --accesslog=true
        - --accesslog.fields.defaultmode=keep
        - --accesslog.fields.headers.defaultmode=drop
        - --api.dashboard=true
        - --api.insecure=true
        - --serversTransport.insecureSkipVerify=true
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entrypoint.scheme=https
        - --entrypoints.websecure.address=:443
        - --entryPoints.web.address=:80
        - --entryPoints.web.proxyProtocol.insecure
        - --entryPoints.web.forwardedHeaders.insecure
        - --entryPoints.websecure.forwardedHeaders.insecure
```

### If applicable, please paste the log output in DEBUG level

We only get logs when the request is not timing out, so there is nothing meaningful to add here.

cURL error when the request times out:
```
* HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
* LibreSSL SSL_write: error:02FFF020:system library:func(4095):Broken pipe, errno 32
* Failed sending HTTP2 data
* Closing connection 0
```

**Comment by rtribotte** [comment]
Hello @pavlospt,

Thanks for your interest in Traefik!

The `maxIdleConnectionsPerHost` is an option on the `serversTransport` and has an effect on the client side of Traefik when dialing with backends.
It is unlikely that the issue lies on the client side of Traefik.
One possible way to get rid of that doubt would be to disable HTTP2 on services (https://doc.traefik.io/traefik/v2.9/routing/services/#disablehttp2).

If I'm not wrong the NLB is load balancing on layer 4, do you know if it is possible that it closes connections or load balance again an existing connection?

**Comment by pavlospt** [comment]
> Hello @pavlospt,
> 
> Thanks for your interest in Traefik!
> 
> The `maxIdleConnectionsPerHost` is an option on the `serversTransport` and has an effect on the client side of Traefik when dialing with backends. It is unlikely that the issue lies on the client side of Traefik. One possible way to get rid of that doubt would be to disable HTTP2 on services (https://doc.traefik.io/traefik/v2.9/routing/services/#disablehttp2).
> 
> If I'm not wrong the NLB is load balancing on layer 4, do you know if it is possible that it closes connections or load balance again an existing connection?

Hey @rtribotte 👋🏻 

Indeed NLB works on layer 4. I am not sure how it handles the last part tha you mentioned, but based on their documentation the idle timeout is set at 350 seconds, which is what we observe as a timeout, in half of the requests going to Traefik  *ONLY* when it is scaled to 2 replicas.

Amazon docs: 
```We set the idle timeout value for TCP flows to 350 seconds. You can't modify this value. Clients or targets can use TCP keepalive packets to reset the idle timeout. Keepalive packets sent to maintain TLS connections can't contain data or payload.
```

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout

**Comment by stathismar** [comment]
Regarding this issue, the problem was that we were using AWS Cloud Provider Load Balancer Controller instead of AWS Load Balancer one. Since we have deployed our cluster in EKS and we are using the Amazon VPC CNI, it seems like you have to [use the  AWS Load Balancer Controller ](https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html#network-load-balancer) in order for the NLB work properly.
We switched from:
```yaml
service.beta.kubernetes.io/aws-load-balancer-type: nlb
``` 
to 
```yaml
service.beta.kubernetes.io/aws-load-balancer-type: external
``` 
to the issue gone away. 
We are leaving it here in case someone faces a similar issue in the future.
@rtribotte Thanks for your help.
