### ISSUE TITLE
Array from configuration are considered as string

### ISSUE THREAD

**Issue by darkweak** [traefik/traefik#9818]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Trying to parse the configuration in a middleware/plugin

Given the following snippets

```yaml
your_keys:
  - one
  - two
  - three
```
```yaml
your_keys: [one, two, three]
```
will result to `║24║one║two║three` that is considered as string but it must be an array.

### What did you see instead?

`║24║one║two║three`

### What version of Traefik are you using?

v3.0+

### What is your environment & configuration?

```yaml
your_keys:
  - one
  - two
  - three
```
```yaml
your_keys: [one, two, three]
```

### If applicable, please paste the log output in DEBUG level

In the code

```go
fmt.Printf("%+v is a %T", i, i)
```

Results
```
traefik-traefik-1  | 2023-03-31T09:34:29Z DBG fmt/print.go:205 > ║24║GET║HEAD║POST is a string module=github.com/darkweak/souin plugin=plugin-souin
```

**Comment by ldez** [comment]
hello,

the string `║24║one║two║three` means that is read as a slice of string and not string.

In your plugin you are handling "manually" the configuration, I think it's the root of the problem.

**Comment by darkweak** [comment]
To be clear, I'm handling the given configuration as a `map[string]interface{}`, I'm iterating over keys, and I'm casting again to `map[string]interface{}` if the value is a complex object (string, int, ... if that's a primitive value). It worked in the past but now it doesn't. 

The full example would be like that
```yaml
default_cache:
  alllowed_http_verbs:
    - GET
    - HEAD
    - POST
```

with the following golang code
```go
type TraefikConfiguration map[string]interface{}

func parseStringSlice(i interface{}) []string {
	if value, ok := i.(string); ok {
		// Need that check because of the Træfik configuration array interpretation.
		if strings.HasPrefix(value, "║24║") {
			fmt.Println("CONTAINS prefix ", value)
			return strings.Split(strings.TrimPrefix(value, "║24║"), "║")
		}
		return strings.Split(value, ",")
	}

	if value, ok := i.([]string); ok {
		return value
	}

	return nil
}

func parseConfiguration(c map[string]interface{}) Configuration {
	configuration := Configuration{}

	for k, v := range c {
		switch k {
		// ...
		case "default_cache":
			// ...
			defaultCache := v.(map[string]interface{})
			for defaultCacheK, defaultCacheV := range defaultCache {
				switch defaultCacheK {
				// ...
				case "allowed_http_verbs":
					// defaultCacheV is equal to the string `║24║one║two║three` here
					dc.AllowedHTTPVerbs = parseStringSlice(defaultCacheV)
				// ...
			}
			// ...
		}
	}

	return configuration
}

func New(_ context.Context, next http.Handler, config *TestConfiguration, name string) (http.Handler, error) {
	fmt.Printf("%+v\n", config)
	c := parseConfiguration(*config)
	// ...
}
```
That's not only for this property but for all arrays from the configuration
If I add the debug message before the parseConfiguration call, I get the following log
```
traefik-traefik-1  | 2023-03-31T10:34:35Z DBG fmt/print.go:205 > &map[default_cache:map[allowed_http_verbs:║24║GET║HEAD║POST]] module=github.com/darkweak/souin plugin=plugin-souin
```

**Comment by darkweak** [comment]
On versions < 3.0 it worked but since I'm trying to make the plugin compatible with the version >= 3.0 it doesn't paste the arrays as expected. (I know that 3.x is currently in beta but I prefer to send some feedbacks during the beta instead of waiting the official release).
