### ISSUE TITLE
Improve docs: how to "match any request" with TCP router without TLS

### ISSUE THREAD

**Issue by bluepuma77** [traefik/traefik#9820]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It would be great to see a sentence in the [Configuring TCP Routers](https://doc.traefik.io/traefik/routing/routers/#configuring-tcp-routers) doc about the recommended way to create a "match any request" rule when TLS is not enabled.

Without TLS enabled, Traefik should not be able to read HostSNI information from a TCP request, so only a single service can be used on a plain TCP entrypoint. I feel it would be worth to add a sentence in the docs about the best practice for this, the topic came up multiple times in the Traefik community and on Reddit.

**Comment by svx** [comment]
Hello @bluepuma77 

We have this already documented on [Configuring TCP Routers](https://doc.traefik.io/traefik/routing/routers/#configuring-tcp-routers)
<img width="629" alt="SCR-20230403-nhbt" src="https://user-images.githubusercontent.com/358860/229517131-497fb68b-69a8-423a-9324-31c55c4afe42.png">

Do you think it would help if we would move it to another section of the document or how can we improve the docs?

**Comment by mbingel** [comment]
I guess I would have expected it below the two `HostSNI is example.com` boxes.

Today I read in the community forum that the UDP router uses no rule at all. Wonder if also non-TLS TCP works without rule.

**Comment by bluepuma77** [comment]
I missed that box, I guess I expected it next to the `HostSNI is example.com` boxes, but it should be fine there.
