### ISSUE TITLE
tracing.jaeger enabled, but local plugin can't get trace-id related header

### ISSUE THREAD

**Issue by caiuskong** [traefik/traefik#9831]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

## traefik config
```yaml
tracing:
  serviceName: traefik
  spanNameLimit: 150
  jaeger:
    samplingServerURL: http://jaeger:5778/sampling
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: jaeger:6831
    traceContextHeaderName: uber-trace-id
    gen128Bit: true
```

## local plugin
```go
func (p *TracingJaeger) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
	fmt.Println("###tracing start...")

	fmt.Printf("req.header: %+v\n", req.Header)
	fmt.Printf("tracing-jaeger start [uber-trace-id=%s]\n", req.Header.Get("uber-trace-id"))
	fmt.Printf("opentracing.IsGlobalTracerRegistered=%v\n", opentracing.IsGlobalTracerRegistered())
	fmt.Printf("opentracing.GlobalTracer=%v\n", opentracing.GlobalTracer())
}
```

### What did you see instead?

i can not find "trace-id" related header

### What version of Traefik are you using?

v2.9.10

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

time="2023-04-09T07:01:48Z" level=debug msg="###tracing start..." plugin=plugin-tracing-jaeger module=github.com/traefik/tracing-jaeger
time="2023-04-09T07:01:48Z" level=debug msg="req.header: map[Accept:[*/*] Accept-Encoding:[gzip, deflate, br] Connection:[keep-alive] Content-Length:[286] Content-Type:[application/json] Cookie:[_b1aff=23f9b6d29281cdab] Postman-Token:[068844f1-59c2-438e-b16d-d37668f75386] User-Agent:[PostmanRuntime/7.31.3] X-Forwarded-For:[127.0.0.1] X-Forwarded-Host:[localhost] X-Forwarded-Port:[80] X-Forwarded-Proto:[http] X-Forwarded-Server:[223034747e96] X-Real-Ip:[172.31.0.1]]" plugin=plugin-tracing-jaeger module=github.com/traefik/tracing-jaeger
time="2023-04-09T07:01:48Z" level=debug msg="rw.header: map[]" plugin=plugin-tracing-jaeger module=github.com/traefik/tracing-jaeger
time="2023-04-09T07:01:48Z" level=debug msg="tracing-jaeger start [uber-trace-id=]" plugin=plugin-tracing-jaeger module=github.com/traefik/tracing-jaeger
time="2023-04-09T07:01:48Z" level=debug msg="opentracing.IsGlobalTracerRegistered=false" module=github.com/traefik/tracing-jaeger plugin=plugin-tracing-jaeger
time="2023-04-09T07:01:48Z" level=debug msg="opentracing.GlobalTracer={}" plugin=plugin-tracing-jaeger module=github.com/traefik/tracing-jaeger

**Comment by caiuskong** [comment]
i can get trace_id in request.context(), like this:
```go
reqCtxString := fmt.Sprint(req.Context())
r := regexp.MustCompile(`\(type opentracing.contextKey, val (\S+:\S+:\S+:[0|1])\)`)
m := r.FindAllStringSubmatch(reqCtxString, -1)
for _, v := range m {
  fmt.Println(v[1])
  fmt.Printf("TraceID: %s\n", strings.Split(v[1], ":")[0])
  fmt.Printf("SpanID: %s\n", strings.Split(v[1], ":")[1])
}
```

**Comment by rtribotte** [comment]
Hello @suikast42,

Thanks for your interest in Traefik!

> i can not find "trace-id" related header

The trace forwarder middleware piece is executed after the user-defined middleware chain, which I think explains why the header is not added yet.

> i can get trace_id in request.context()

I'll close this since using the request context seems to work for you.

**Comment by caiuskong** [comment]
hello @rtribotte,

> The trace forwarder middleware piece is executed after the user-defined middleware chain (which includes plugins), which I think explains why the header is not added yet.

Thank you for your reply. 
But if traefik tracing forward middleware is executed after the local plugins chain，why i can find Span info at request.Context()?

maybe internal tracing middleware -> local plugin -> internal add request header middleware?

**Comment by rtribotte** [comment]
Hello @caiuskong,

> maybe internal tracing middleware -> local plugin -> internal add request header middleware?

Yes, there is the "entryPoint" tracing middleware extracting the span and creating the tracing context (https://github.com/traefik/traefik/blob/v2.9/pkg/middlewares/tracing/entrypoint.go), and the "forwarder" tracing middleware that is notably injecting tracing headers on the request: https://github.com/traefik/traefik/blob/4ed3964b3586565519249bbdc55eb1b961c08c49/pkg/middlewares/tracing/forwarder.go#L52.
