### ISSUE TITLE
Latest release in github currently points to a release candidate

### ISSUE THREAD

**Issue by Rumbles** [traefik/traefik#9833]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Current latest on the traefik releases page is set to https://github.com/traefik/traefik/releases/tag/v2.10.0-rc2 which is a release candidate, I believe this should have been marked as pre-release not latest. Current latest should be https://github.com/traefik/traefik/releases/tag/v2.9.10, would it be possible to update it and add logic somewhere to not publish a release candidate as the latest release somehow?

### What did you see instead?

N/A

### What version of Traefik are you using?

N/A

### What is your environment & configuration?

N/A

**Comment by rtribotte** [comment]
Hello @Rumbles,

Thanks for reporting this!

We fixed it.
