### ISSUE TITLE
[Documentation] Make it clear that Tailscale TLS provider is not yet available

### ISSUE THREAD

**Issue by nikitawootten** [traefik/traefik#9854]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am running Traefik on K3s via the official Helm chart. The documentation suggests that a Tailscale provider has been added and is available (https://doc.traefik.io/traefik/master/https/tailscale/). I followed the documentation.

### What did you see instead?

* Traefik failed to start and provided the log message `command traefik error: failed to decode configuration from flags: field not found, node: tailscale`
* A discourse link made it clear that Tailscale support will not be made available until v3: https://community.traefik.io/t/how-to-make-tailscale-tls-cert-provisioning-working/16269

It's clear to me that the Tailscale provided is not intended for use currently. **It would save people like me much confusion in the future to make it clear that the provider is not available yet.**

### What version of Traefik are you using?

Traefik Helm Chart 22.1.0 (Traefik v2.9.10)

### What is your environment & configuration?

Values provided for the helm chart:
```yaml
additionalArguments:
  - "--certificatesresolvers.ts.tailscale=true"
```

**Comment by ldez** [comment]
Hello,

you are watching the documentation of the **experimental** version (branch `master`).

`https://doc.traefik.io/traefik/master/https/tailscale/`

![Screenshot 2023-04-21 at 08-26-19 Traefik Tailscale Documentation - Traefik](https://user-images.githubusercontent.com/5674651/233557469-cc1fa37f-8775-41d5-92d4-ed3c42865bdd.png)

The documentation of the current stable version (v2.9) is here:
- https://doc.traefik.io/traefik/
- https://doc.traefik.io/traefik/v2.9/

**Comment by bluepuma77** [comment]
I think several people had some confusion with the version of the Traefik docs, maybe add the version at the top (as drop-down), like many other projects do: [bootstrap](https://getbootstrap.com/docs/5.3/getting-started/introduction/), [Elastic](https://www.elastic.co/guide/en/elastic-stack/current/index.html), [MongoDB](https://www.mongodb.com/docs/manual/).

**Comment by nikitawootten** [comment]
Ah, you know right after posting I saw `master` in the URL and suspected that may be why.

This is definitely my mistake, but I wish the version selector was displayed a little more prominently, or there was a bit more warning given when on the experimental version.

**Comment by nmengin** [comment]
Hey @nikitawootten ,

Glad to know you have found the information.
We linked this issue to another dedicated to the possible documentation enhancements.

I close this issue.
