### ISSUE TITLE
Use of X-XSS-Protection header should be discouraged and explicit disable should send the correct value

### ISSUE THREAD

**Issue by TaaviE** [traefik/traefik#9859]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Added the label `traefik.http.middlewares.testheaders.headers.browserxssfilter=false` to one of my containers. 

### What did you see instead?

Traefik does not send `X-XSS-Protection` header with the value `0`, which is unintuitive and a potential security issue. 

This is because browsers that default to `1` or sending explicit `1; block` can introduce [vulnerabilities](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection#vulnerabilities_caused_by_xss_filtering) into otherwise safe sites. So being able to send the secure value would be expected from this label.

This risk is also not documented, potentially causing insecure configurations out in the wild.

More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

### What version of Traefik are you using?

v2.7

### What is your environment & configuration?

N/A

**Comment by rtribotte** [comment]
Hello @TaaviE,

Thanks for your interest in Traefik!

This is the expected behavior.
As per the [documentation](https://doc.traefik.io/traefik/middlewares/http/headers/#browserxssfilter), the `browserXssFilter` option is only a shortcut to add the header with the value `1; mode=block`.

In your case, we recommend setting the header directly:
`traefik.http.middlewares.testheaders.headers.customresponseheaders.X-XSS-Protection=0`

**Comment by Avamander** [comment]
@rtribotte That's the thing, setting it to `0` does not send `X-XSS-Protection: 0`. 

Secondly, an option that makes things potentially less secure when enabled should come with a warning in the documentation.

**Comment by TaaviE** [comment]
@rtribotte 

That's the issue, setting it to `0` does not send `X-XSS-Protection: 0`.

Secondly, a configuration option that when enabled can cause security issues should come with a documented warning. Better yet, there should be an explicit recommended default.

**Comment by TaaviE** [comment]
So when rest of the options follow the logic of `securityheader=true` resulting in a secure configuration, doing so with browserxssfilter will result in the opposite. If it just happens that someone is aware of that pitfall, they will set it to false. But that ends up being an insecure configuration yet again, without any warning. So basically this Traefik configuration option is not even a footgun you can unload, it's a landmine.

**Comment by TaaviE** [comment]
@rtribotte I can certainly find an another way to achieve the desired result. The issue is that there's an undocumented configuration landmine in Traefik.

**Comment by rtribotte** [comment]
Hello @TaaviE,

> The issue is that there's an undocumented configuration landmine in Traefik.

What do you suggest? We are eager to improve it and we would gladly accept a contribution.
  
If I'm not overlooking this, as I mentioned in a previous comment, this option is documented and is not doing more or less than what the documentation says:
```
Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.
```

We are also pointing out in the doc the `unrolled/secure` lib [documentation](https://github.com/unrolled/secure#available-options) for the available options.

**Comment by TaaviE** [comment]
Hi, @rtribotte 

> What do you suggest? We are eager to improve it and we would gladly accept a contribution.

As the option works counter-intuitively it would be very important to document it. 

Though ideally the option would be renamed in a future release so that people who *really* want to send a value of `1; mode=block` will have to do so against explicit recommendations (of the documentation).

> If I'm not overlooking this, as I mentioned in a previous comment, this option is documented and is not doing more or less than what the documentation says:

Indeed, but given it's in a section where enabled == good (and all the outdated tutorials out there) it very likely has misled a lot of users. I personally saw this mistake in an another project's documentation, downgrading the security of that project.
