### ISSUE TITLE
Traefik using localhost 127.0.0.1 to proxy

### ISSUE THREAD

**Issue by dontcrash** [traefik/traefik#9869]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When using Traefik, it binds to localhost and uses it to proxy to servers:

```
Hostname: test
IP: 127.0.0.1
IP: 172.20.7.2
RemoteAddr: 172.20.7.1:48066
GET / HTTP/1.1
Host: test.domain.com
User-Agent: Redacted
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: Redacted
Cache-Control: max-age=0
Sec-Ch-Ua: Redacted
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: Redacted
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 172.16.2.20
X-Forwarded-Host: test.domain.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik
X-Real-Ip: 172.16.2.20
```

This causes issues with multiple applications as generally 127.0.0.1 is not trusted as a source IP for X-Forwarded-For and X-Real-Ip headers, most will only trust it coming from an RFC1918 address.

In the Traefik config, I have tried to bind to an address on the entrypoint, for example "172.16.12.2:443/tcp" and this binds but the whoami container will still show the source IP as 127.0.0.1

### What version of Traefik are you using?

2.10.0

**Comment by rtribotte** [comment]
Hello @dontcrash,

Thanks for reaching out! 

To keep the repository focused, we ask that all questions be asked in the [community forum] (https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.

**Comment by nmengin** [comment]
Hello @dontcrash,

> This wasn’t a query, it’s a genuine bug. A proxy server should not send from 127.0.0.1 ever, it’s a security issue.

Could you elaborate on this point, please?

**Comment by dontcrash** [comment]
> Hello @dontcrash,
> 
> > This wasn’t a query, it’s a genuine bug. A proxy server should not send from 127.0.0.1 ever, it’s a security issue.
> 
> Could you elaborate on this point, please?

See my original post, all the details are there.

**Comment by rtribotte** [comment]
Hello @dontcrash,

The IPs shown in the output are the whoami instance interface IP addresses, as you can see here: https://github.com/traefik/whoami/blob/f3f17505276a40958d485ce530b695f0a8f35af6/app.go#L216-L230
