### ISSUE TITLE
Allow wildcard certificates for ACME HTTP challenge

### ISSUE THREAD

**Issue by erkexzcx** [traefik/traefik#9880]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am specifically referring to this check that I believe can be removed completelly:
https://github.com/traefik/traefik/blob/8174860770e536b4afb541e0ab13b3611a101430/pkg/provider/acme/provider.go#L934-L936

I know that it is impossible to retrieve wildcard certificates using HTTP challenge.

However, some private ACME providers has an option to bypass HTTP challenge with something called `prevalidation` (in combination with EAB credentials) which technically allows to retrieve a wildcard certificate using HTTP challenge. It actually means that ACME server would not validate HTTP challenge of the client, and simply say "yeah sure, I checked your challenge and here is your cert".

I understand that my case is quite rare, but software like [go-acme/lego](https://github.com/go-acme/lego) and [caddyserver/caddy](https://github.com/caddyserver/caddy) work great in such cases, but not Traefik.

Could you please remove mentioned check, or at least add an option to bypass it? Or even better, turn it into a warning rather than a configuration check?

**Comment by nmengin** [comment]
Hello @erkexzcx!

Thanks for your suggestion.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

**Comment by rtribotte** [comment]
Hello @erkexzcx,

Thanks for the feedback.
To explain our stance, we think that removing the error would be misleading and let users have a wrong configuration.
The error inducing the failure of dynamic configuration application has been done on purpose to make things easier for users in 99% of the cases.

A possibility could be to make that behavior optional, but introducing new options for edge cases is something we try to avoid.

**Comment by rtribotte** [comment]
Hello @erkexzcx,

We experimented with the changes of #9881, and we agree with the changes because if the ACME server cannot provide other challenges than the DNS for wildcard certificates, an error will be thrown in LEGO, which is self-explanatory enough to replace the Traefik one.

Error before the changes:
```
time="2023-05-16T13:09:55Z" level=error msg="Unable to obtain ACME certificate for domains \"*.whoami.localhost\"" routerName=traefik@docker rule="Host(`traefik.localhost`)" error="unable to generate a wildcard certificate in ACME provider for domain \"*.whoami.localhost\" : ACME needs a DNSChallenge" providerName=leresolver.acme ACME CA="https://pebble:14000/dir"
```

Error after the changes:
```
2023-05-16T13:27:47Z DBG go/pkg/mod/github.com/go-acme/lego/v4@v4.10.2/log/logger.go:48 > [INFO] [*.whoami.localhost] acme: Could not find solver for: dns-01 lib=lego
2023-05-16T13:15:35Z ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [*.whoami.localhost]: error: one or more domains had a problem:\n[*.whoami.localhost] [*.whoami.localhost] acme: could not determine solvers\n" acmeCA=https://pebble:14000/dir domains=["*.whoami.localhost"] providerName=leresolver.acme routerName=traefik@docker rule=Host(`traefik.localhost`)
```

**Comment by rtribotte** [comment]
Closed by https://github.com/traefik/traefik/pull/9881
