### ISSUE TITLE
Also drop fields for logs

### ISSUE THREAD

**Issue by Jerbear0** [traefik/traefik#9882]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

> log:
>   filePath: "/traefik-log.log"
>   format: json
>   level: ERROR
>   fields:
>     defaultMode: keep
>     names:
>       entryPointName: drop

was expecting to be able to drop entryPointName from my log.
every time i recreate the docker i get spammed with the "use of closed network connection error", specifically dropping those errors would be even better.

**Comment by nmengin** [comment]
Hey @Jerbear0 !

Thanks for your suggestion.
It seems to be an interesting feature, but we'd like you to elaborate on your need to be sure we're on the same line.
We are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know and we will work with you to make sure you have all the information needed.

Let us know here before you start. We prefer to work with our community members at the beginning of the design process to ensure that we are aligned and can move quickly with the review and merge process
