### ISSUE TITLE
sendAnonymousUsage enabled even set to false

### ISSUE THREAD

**Issue by yongzhang** [traefik/traefik#9895]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

In traefik.toml, set 

```
    [global]
      checkNewVersion = false
      sendAnonymousUsage = false
```

### What did you see instead?

I see logs:

```
{"level":"info","msg":"Traefik version 2.9.10 built on 2023-04-06T16:15:08Z","time":"2023-05-15T09:17:17Z"}
{"level":"info","msg":"Stats collection is enabled.","time":"2023-05-15T09:17:17Z"}
{"level":"info","msg":"Many thanks for contributing to Traefik's improvement by allowing us to receive anonymous information from your configuration.","time":"2023-05-15T09:17:17Z"}
```

### What version of Traefik are you using?

2.9.10

### What is your environment & configuration?

```
# cat traefik.toml
[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "json"

[accesslog]
  format = "json"

[api]
  insecure = true
  dashboard = true

[ping]

[pilot]
  dashboard = false

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
    addEntryPointsLabels = true

[entryPoints]
...

[providers]
  [providers.kubernetesIngress]
    ingressClass = "traefik-public"
    allowEmptyServices = true
    allowExternalNameServices = true
  [providers.kubernetesCRD]
    ingressClass = "traefik-public"
    allowCrossNamespace = true
    allowExternalNameServices = true
  [providers.file]
    directory = "/etc/traefik/conf/dynamic"
    watch = true

[tracing]
  [tracing.jaeger]
    samplingParam = 0
    traceContextHeaderName = "X-Request-Id"
```

**Comment by ldez** [comment]
Hello,

can you provide your full static configuration?

**Comment by yongzhang** [comment]
> Hello,
> 
> can you provide your full static configuration?

Updated. Thanks.

**Comment by ldez** [comment]
It's because you have `pilot` enable.

You have to remove the `pilot` configuration.

Traefik Pilot has been closed.

**Comment by yongzhang** [comment]
> It's because you have `pilot` enable.
> 
> You have to remove the `pilot` configuration.
> 
> Traefik Pilot has been closed.

ahh, it works now! Thanks. 

So superized this parameter will impact `sendAnonymousUsage`.
