### ISSUE TITLE
Proxy http requests to a backend server of GRPC without proto file. 

### ISSUE THREAD

**Issue by helloworldyuhaiyang** [traefik/traefik#9902]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

#### The problem I face:
In many cases, our microservices serve App and Web via HTTP protocol.  But many of the back-end servers are GRPC servers that provide services via the protobuf protocol.  In this case, we usually implement an http server to hand this request and call the grpc server through a stub provided by the grpc server. We have to update the stub clients if the grpc servers update their proto-files. This is unacceptable when a large number of back-end servers are updating protofiles.

## What I need:
I want to convert an http request into a grpc request without any code over Traefik.

## How can I do it:
In the first place, GRPC has offered a reflection server to reflect the proto information. [GRPC server-reflection](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md). Then we can call grpc servers without grpc stub.

In the second place, we can implement a proxy like http proxy to convert an http request into grpc request in traefik.

Finally, I have completed it in my project.  I'd like to hear from the community, and modify my implementation.

**Comment by nmengin** [comment]
Hey @helloworldyuhaiyang!

Thanks for your suggestion.
We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

If you or another community member would like to build it before that happens, let us know and we will work with you to make sure you have all the information needed.

**Comment by helloworldyuhaiyang** [comment]
Thank you for your feedback. I will implement a simple example first. This will help others understand the convenience and necessity of this feature.  It will inherit traefik's powerful Middlewares and Providers, etc.

**Comment by helloworldyuhaiyang** [comment]
> Hey @helloworldyuhaiyang!
> 
> Thanks for your suggestion. We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.
> 
> We will reevaluate as people respond.
> 
> If you or another community member would like to build it before that happens, let us know and we will work with you to make sure you have all the information needed.

Thank you for your feedback. I will implement a simple example first. This will help others understand the convenience and necessity of this feature. It will inherit traefik's powerful Middlewares and Providers, etc.

**Comment by helloworldyuhaiyang** [comment]
I made a simple grpc gateway based on traefik.  It only completed basic function to demonstrate my thoughts.

https://github.com/helloworldyuhaiyang/grpc-gateway

**Comment by gfonseca-tc** [comment]
I would like to see this implemented, we have a very similar use case.

**Comment by rtribotte** [comment]
Hello,

Unfortunately, this issue has remained open for several months with minimal attention.
To maintain focus on our repository's most crucial features, we have decided to close this issue due to insufficient traction.
If necessary, please don't hesitate to request its reopening.
