### ISSUE TITLE
CLI commands to validate and print configuration

### ISSUE THREAD

**Issue by enspritz** [traefik/traefik#9916]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Something like this:

```bash
# Print out entire Traefik configuration including all defaults, in the specified format:
$ traefik print-config --format=yaml
---
routers:
  ...

# Print out entire configuration, after applying the specified config file:
$ traefik print-config --config-file=traefik.toml
[routers]
  ...

# Attempt to print bad configuration:
$ traefik print-config --config-file=bad-traefik.toml
Error on line 123: ...
exited 1 $

# Validate a given configuration.
$ traefik validate-config --config-file=known-good-traefik.yaml
traefik: configuration is OK

# Validate a bad configuration.
$ traefik validate-config --config-file=bad-traefik.toml
Error on line 123: ...
exited 1 $
```

### Value:
- Accelerate learning speed re: Traefik configuration, reduce friction and get to production faster.
- Speed up the edit-run-debug cycle for generating new Traefik configurations, testing new versions prior to deployment. Especially for the changes in the coming 3.0 release.

Dynamically-deduced configuration like from container labels and service discovery is not necessary; I just need to know whether the static configuration is semantically correct and whether my changes will modify Traefik's behavior in line with my desired outcome.

There is an abundance of prior art here, `nginx -t`, `postconf`, and many many more.
 
It would be a big plus if I could also confirm current running configuration, by API and the dashboard.

Thanks!

**Comment by nmengin** [comment]
Thanks for your suggestion, but this is something that we will not be able to do because we prefer to avoid adding any new subcommand to Traefik. 

Moreover, you can already check your configuration using a schema as described in the [documentation]( https://doc.traefik.io/traefik/getting-started/faq/#what-does-the-field-not-found-error-mean).

**Comment by ldez** [comment]
You can use JSON schema to validate your configuration: https://doc.traefik.io/traefik/getting-started/faq/#what-does-the-field-not-found-error-mean
All the major IDE or text editors support JSON schema.
