### ISSUE TITLE
Potential leak in ping.go

### ISSUE THREAD

**Issue by hhheiaenia** [traefik/traefik#9917]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I was wondering if the code may result in a goroutine leak in https://github.com/traefik/traefik/blob/master/pkg/ping/ping.go#LL26C15-L26C15. If the ctx.Done() never be cancelled. Which may lead the annoymous func leak. 

I don't think what I'm saying is correct, do you think that's the case?

### What did you see instead?

.

### What version of Traefik are you using?

.

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

The method `WithContext` is only called once and only once at the start of Traefik.
The context is canceled when the traefik is stopped.
So it cannot leak.
