### ISSUE TITLE
Documentation for static config file

### ISSUE THREAD

**Issue by lonix1** [traefik/traefik#9920]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

New user here. I'd like to understand the options in the "static configuration". There's a full `traefik.yml` sample [here](https://doc.traefik.io/traefik/reference/static-configuration/file/).

But it's not documented. I don't know what each option does.

Please consider adding documentation for this?

**Comment by ldez** [comment]
Hello,

the documentation of the static configuration is all the items of the documentation:
- https://doc.traefik.io/traefik/providers/overview/
- https://doc.traefik.io/traefik/routing/entrypoints/
- https://doc.traefik.io/traefik/https/overview/
- etc...


The page [here](https://doc.traefik.io/traefik/reference/static-configuration/file/) is not a sample but a full reference of the configuration fields.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2).

**Comment by svx** [comment]
Hi @lonix1, thanks for your feedback!

Just to let you know, we're aware that the docs have room for improvements.

I am happy to say that we are working to improve the language and organization. It will take some time, we don't have an ETA, and we can't say how long it will take.

If you have specific suggestions to improve things in the meantime, please feel free to open a PR. We love community help!

If you are struggling with any particular questions, visit our [Community Forum](https://community.traefik.io/). It is very active, and your question might already be answered there.
