### ISSUE TITLE
Traefik tries to request deprecated API CRDs

### ISSUE THREAD

**Issue by rgarcia89** [traefik/traefik#9923]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

With the upgrade to v2.10 new CRDs with API version traefik.io has been released. In order to ensure my users do not deploy into the CRDs of the old API we have deleted all CRDs linked to traefik.containo.us API. After that Traefik starts to report the following errors in the logs.

Is there a way to disable the check against the CRDs that are based on the old API?
I guess this is going to be removed in the near by future.

### What did you see instead?

```
W0529 17:37:49.322966       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSOption: the server could not find the requested resource (get tlsoptions.traefik.containo.us)
W0529 17:37:47.879473       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.Middleware: the server could not find the requested resource (get middlewares.traefik.containo.us)
...
```

### What version of Traefik are you using?

2.10.1

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

during the deprecation phase, the old API group (`traefik.containo.us`) is still required for compatibility reasons.

There is no way to disable the support of the old API group.

I recommend installing the new and old API group CRDs.

**Comment by rgarcia89** [comment]
Understood - I just found it somehow confusing. In that case I will re-add the old API group CRDs and remove access to them via RBAC. Is it already clear up to when the old API group will be removed completely?

**Comment by ldez** [comment]
[The old API group has been removed](https://github.com/traefik/traefik/pull/9804) from Traefik v3.
The support of the old API group will not be removed from Traefik v2.
