### ISSUE TITLE
[Feature Request]  Toggle api/dashboard at runtime

### ISSUE THREAD

**Issue by lonix1** [traefik/traefik#9936]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

It is convenient to keep the api/dashboard disabled, and only enable it when debugging / troubleshooting.

But to toggle the dashboard we must set `--api=true|false` in the static config, and restart traefik. That isn't easy, and impacts dependent services.

Please allow us to toggle the dashboard at runtime, via the dynamic config.

(Related forum discussion [here](https://community.traefik.io/t/quick-and-easy-way-to-toggle-dashboard-at-runtime/18874).)

**Comment by ldez** [comment]
Hello,

as suggested by @bluepuma77 inside the [forum](https://community.traefik.io/t/quick-and-easy-way-to-toggle-dashboard-at-runtime/18874), you can add play with dynamic configuration to enable/disable the router related to the API.
