### ISSUE TITLE
integration-test failed: ConsulCatalogSuite.TestSimpleConfigurationWithWatch

### ISSUE THREAD

**Issue by 0xDagal** [traefik/traefik#9954]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I ran `make test` on the freshly cloned repo at the master branch.

I was hoping to see all the tests pass before I started coding.

### What did you see instead?

```
FAIL: consul_catalog_test.go:237: ConsulCatalogSuite.TestSimpleConfigurationWithWatch

consul_catalog_test.go:276:
    c.Assert(err, checker.IsNil)
... value *fmt.wrapError = &fmt.wrapError{msg:"try operation failed: got status code 200, wanted 404", err:(*errors.errorString)(0xc001946350)} ("try operation failed: got status code 200, wanted 404"
```

### What version of Traefik are you using?

```
Testing against...
Client: Docker Engine - Community
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:54:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       tag v24.0.2
  Built:            Mon Jun  5 09:59:37 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        UNSET
 runc:
  Version:          1.1.6
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
  ```
  
  ```
  ~/Projects/traefik(master)$ dist/traefik version
Version:      60bc47d00e9ac7584a4bd437f53fdef347915dea
Codename:     cheddar
Go version:   go1.20.5
Built:        2023-06-13_05:33:33PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Test ran with the method 1, using docker.

**Comment by ldez** [comment]
Hello,

it can be related to a timeout, so you have to add `CI=1`.

FYI: the tests are always run in our CI.

**Comment by 0xDagal** [comment]
I tried `CI=1 make test` and know the `K8sSuite.TestCRDConfiguration` fail. Should I car or it can be due to something else and only the CI tests have to be checked ?

**Comment by ldez** [comment]
`CI=1` only increases timeout, there are no other specific things for the CI.

The integration tests are required a lot of CPU and memory.
I recommend running only the tests that you need to run:
```bash
CI=1 TESTFLAGS="-check.f K8sSuite.TestCRDLabelSelector" make test-integration 
```
