### ISSUE TITLE
Dashboard Content Type nosniff downloads just a file

### ISSUE THREAD

**Issue by wuast94** [traefik/traefik#9965]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Open the dashboard with content type nosniff set dont render the dashboard and downloads the raw html instead.

See
https://github.com/traefik/traefik/pull/9594

### What did you see instead?

see above

### What version of Traefik are you using?

Traefik version 3.0.0-beta2 built on 2022-12-07T16:32:34Z version=3.0.0-beta2

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

already fixed by #9622
