### ISSUE TITLE
New 3.0 beta3 release to match 2.10?

### ISSUE THREAD

**Issue by davhdavh** [traefik/traefik#9982]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Can we please get a beta3?
Its a mess with the CRDs renaming and bugs that were already fixed long ago, like https://github.com/traefik/traefik/issues/9617

**Comment by ldez** [comment]
Hello,

a beta3 release is coming https://github.com/traefik/traefik/pull/9978 :wink:
