### ISSUE TITLE
Swarm Mode does not work on traefik:3.0.0-beta3

### ISSUE THREAD

**Issue by leadvic** [traefik/traefik#9987]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I deployed a Docker stack of Traefik (updating) from version 2.10.1 to 3.0.0-beta3 in order to securely expose a PostgreSQL database. However, when I did this, Traefik was unable to run properly and displayed the following error:
```
failed to decode configuration from flags: field not found, node: swarmMode
```
After researching the issue, I found no relevant information available. Consequently, I decided to report this problem.

### What did you see instead?

To resolve the issue, I switched from version 3.0.0-beta3 to 3.0.0-beta2, which resolved the problem. Nevertheless, this bug is concerning and should be addressed.

### What version of Traefik are you using?

The issue exists in Traefik version 3.0.0-beta3.

### What is your environment & configuration?

Here is my configuration, in case you want to review it (I attempted using both "swarmMode" and "swarmmode" but observed no difference):

```yaml
    command:
      # Tell Traefik to discover containers using the Docker Swarm API
      - --providers.docker.swarmMode=true
      - --providers.docker.network=traefik
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      # Enable the Trafik dashboard
      - --api.dashboard=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=myemail@mail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=my.domain
      - --entrypoints.websecure.http.tls.domains[0].sans=*.my.domain
      # Set up the port 5432 for secure database connections
      - --entrypoints.dbsecure.address=:5432
      # Set up logging level
      - --log.level=ERROR
```

**Comment by ldez** [comment]
Hello,

the provider Docker has been split:
- https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/#docker-docker-swarm
- https://doc.traefik.io/traefik/v3.0/providers/swarm/
- https://github.com/traefik/traefik/releases/tag/v3.0.0-beta3
-
