### ISSUE TITLE
Remove HTTP/3 from experimental section

### ISSUE THREAD

**Issue by otbutz** [traefik/traefik#9991]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

HTTP/3 has been finalised by the IETF and is no longer a draft: https://datatracker.ietf.org/doc/rfc9114/

caddy also uses quic-go to implement HTTP/3 and has it enabled by default since [v2.6.0](https://github.com/caddyserver/caddy/releases/tag/v2.6.0)

**Comment by ldez** [comment]
Hello,

this has been already done in #9570
