### ISSUE TITLE
Documentation unusable due to "email protected" gone wild

### ISSUE THREAD

**Issue by lordgurke** [traefik/traefik#9992]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I navigated to https://doc.traefik.io/traefik/operations/api/ and wanted to know how to enable the API.  

### What did you see instead?

The very first paragraph says

> If you enable the API, a new special service named [[email protected]](https://doc.traefik.io/cdn-cgi/l/email-protection) is created and can then be referenced in a router.
  
And any other occurence of the, presumably, service name I need to know, is replaced by "email protected" which is not helpful.  
For reference, this is a screenshot from the page I'm seeing right now:  
   
![grafik](https://github.com/traefik/traefik/assets/25770486/c4daaeee-a5c3-48dc-b639-9cf258f864c7)  
  
A quick search brings up many other pages with the same problem - including the page which should show an e-mail address used [to subscribe to security advisories](https://doc.traefik.io/traefik/contributing/submitting-security-issues/).

### What version of Traefik are you using?

Not applicable, it's a documentation issue

### What is your environment & configuration?

Not applicable, it's a documentation issue

**Comment by ldez** [comment]
Hello,

the mask appears because you have disabled Javascript:

> The website from which you got to this page is protected by Cloudflare. Email addresses on that page have been hidden in order to keep them from being accessed by malicious bots. **You must enable Javascript in your browser in order to decode the e-mail address**.
> https://doc.traefik.io/cdn-cgi/l/email-protection

With Javascript enabled you will see:
![Screenshot 2023-06-26 at 20-45-13 Traefik API Documentation - Traefik](https://github.com/traefik/traefik/assets/5674651/94c61189-fbbf-47b9-987d-10b86c18788c)

This protection is the website to protect against spammers.
