### ISSUE TITLE
Accesslog get Status code explanation of middleware

### ISSUE THREAD

**Issue by tom42530** [traefik/traefik#9995]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,

Currently i have an traefik instance running with a chain middleware containing two middleware :
inFlightReq and rateLimit.
In accessslog i see status code 429 when a middleware "trigger", but i wonder if it is possible to get also status code explanation for example "rate limite quota exausted" in case of rateLimit or "to many active connexion" for inFlightReq

Thanks in advance

**Comment by nmengin** [comment]
Hey @tom42530.

Thanks for your suggestion.

We are interested in this issue, but we are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

With that being said, please note that we think that this feature makes sense only the Accesslogs are provided in the JSON format.

**Comment by Youri-Crown** [comment]
Hi @nmengin  . We are using traefik , and more particularly for middlewares usage. I think it's a good idea to get the middleware name in logs when a middleware rule has been triggered. That's will be very helpfull to debug and ajust rate limit for exemple.  Thanks for push this request !

**Comment by nmengin** [comment]
Hey @tom42530 and @Youri-Crown,

After internal discussion, I will close this issue.

Indeed, @tom42530 we think that the status code sent by Traefik is enough to identify the error.
@Youri-Crown, we encourage you to use the tracing feature to obtain an accurate view of the middlewares used on your request path.
