### ISSUE TITLE
Add an option to disable connection reuse across domains

### ISSUE THREAD

**Issue by toxic0berliner** [traefik/traefik#9997]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I would like to be able to tell traefik to always return what I believe should be a http 421 when a connection is being reused by a client with a different host header.

In fact, I am running haproxy in front of 2 traefik instances and since there is some overlap with the wildcard certificate on both my traefik instances, I see the client reusing connections and therefore bypassing some of the haproxy logic since it relies on sni that doesn't happen again when reusing connections.

So I wouldn't mind the extra traffic that disabling connection reuse would cause and it would make my life quite easier 🤣

I dug around quite a bit and couldn't find a solution to do that except avoiding wildcard certificates all together.

**Comment by nmengin** [comment]
Hey @toxic0berliner !
Thanks for your suggestion.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.

We will reevaluate as people respond.

**Comment by toxic0berliner** [comment]
hoping agains all odds that I won't be alone ^^

**Comment by CNLHC** [comment]
I think this isssue is probably related to this one https://github.com/traefik/traefik/issues/9688.

**Comment by toxic0berliner** [comment]
It just occured to me that @nmengin might just have not understood my use case, so let me clarify:
because my traefik has a valid wildcard certificate, the browser will attempt to reuse an existing connection to one of my traefik instance if it has been established with a matching wildcard certificate.
This prevents my haproxy to see an SNI header and perform some routing before traefik, therefore, the request end up reusing the existing tunnel to traefik1 instance that does not have any router valid for the new request despite having a valid wildcard certificate.

So the steps to reproduce for me : 
- setup 1 traefik instance with a valid cert for *.example.com and a single router/service matching one.example.com on machineone.local
- setup a second traefik instance with a valid cert ony for two.example.com (no wildcard) on a separate machinetwo.local
- setup haproxy in front to do SNI routing with 
  - one.example.com backed by machineone.local 
  - and two.example.com backed by machinetwo.local
  - ensure that DNS for *.example.com points to this haproxy
- open firefox
  - browse to one.example.com ==> 200OK
  - browse to two.example.com ==> 404 Not found (this should be a 421 is is the purpose of this issue)
- close and reopen firefox
  - browse to two.example.com ==> 200OK
  - browse to one.example.com ==> 200OK (because the cert owned by machine2.local is not valid for one.example.com firefox will not reuse connections)

I am avoiding this issue mainly by avoiding wildcard certificates as much as possible but to be honest it's a bit of a shame as this would be much simpler for me and quite a bit lighter on letsencrypt side and for my DNS provider if it worked with a 421.

I *believe* firefox would quietly attempt a new http connection without reusing the existing one if it recieves a 421 and therefore haproxy would be able to see the SNI header and direct the TCP traffic to the correct machinetwo.local backend, would be invisible to the user in his browser.

On traefik side, the setting should allow to replace any 404 by a 421 _in case of connection being reused_ (and maybe if the hostname has indeed changed), we do not want to get rid of all 404, only those taking advantage of connection reuse that could have prevented SNI inspection upstream of traefik.
